// src/lib/documents/us/child-travel-consent/questions.ts
import type { FormQuestion } from '@/types/documents';

export const childTravelConsentQuestions: FormQuestion[] = [
  {
    id: 'childName',
    type: 'text',
    label: 'Child Full Name',
    placeholder: 'Enter child full legal name',
    required: true,
    group: 'child',
  },
  {
    id: 'childBirthDate',
    type: 'text',
    label: 'Child Birth Date',
    placeholder: 'Enter child date of birth',
    required: false,
    group: 'child',
  },
  {
    id: 'parent1Name',
    type: 'text',
    label: 'First Parent/Guardian Name',
    placeholder: 'Enter first parent full name',
    required: true,
    group: 'parents',
  },
  {
    id: 'parent1Relationship',
    type: 'select',
    label: 'Relationship to Child',
    options: [
      { value: 'mother', label: 'Mother' },
      { value: 'father', label: 'Father' },
      { value: 'guardian', label: 'Legal Guardian' },
      { value: 'adoptive-parent', label: 'Adoptive Parent' },
    ],
    required: false,
    group: 'parents',
  },
  {
    id: 'accompanyingAdultName',
    type: 'text',
    label: 'Accompanying Adult Name',
    placeholder: 'Enter name of traveling adult',
    required: false,
    group: 'travel',
  },
  {
    id: 'travelDestination',
    type: 'text',
    label: 'Travel Destination',
    placeholder: 'Enter destination city and state/country',
    required: false,
    group: 'travel',
  },
  {
    id: 'travelDates',
    type: 'text',
    label: 'Travel Dates',
    placeholder: 'Enter departure and return dates',
    required: false,
    group: 'travel',
  },
  {
    id: 'travelPurpose',
    type: 'select',
    label: 'Purpose of Travel',
    options: [
      { value: 'vacation', label: 'Vacation' },
      { value: 'family-visit', label: 'Family Visit' },
      { value: 'education', label: 'Educational Trip' },
      { value: 'medical', label: 'Medical Treatment' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
    group: 'travel',
  },
  {
    id: 'emergencyContactName',
    type: 'text',
    label: 'Emergency Contact Name',
    placeholder: 'Enter emergency contact person',
    required: false,
    group: 'emergency',
  },
  {
    id: 'emergencyContactPhone',
    type: 'text',
    label: 'Emergency Contact Phone',
    placeholder: 'Enter emergency contact phone number',
    required: false,
    group: 'emergency',
  },
  {
    id: 'medicalConditions',
    type: 'textarea',
    label: 'Medical Conditions',
    placeholder: 'List any medical conditions or allergies',
    required: false,
    group: 'medical',
  },
  {
    id: 'internationalTravel',
    type: 'boolean',
    label: 'International travel?',
    required: false,
    group: 'travel',
  },
];