import type { Question } from '@/types/documents';

export const questions: Question[] = [
  // Company Information
  {
    id: 'companyName',
    type: 'text',
    label: 'Company Name',
    required: true,
    category: 'Company Information',
  },
  {
    id: 'companyAddress',
    type: 'text',
    label: 'Company Street Address',
    required: true,
    category: 'Company Information',
  },
  {
    id: 'companyCity',
    type: 'text',
    label: 'Company City',
    required: true,
    category: 'Company Information',
  },
  {
    id: 'companyState',
    type: 'select',
    label: 'Company State',
    required: true,
    category: 'Company Information',
    options: [
      'Alabama',
      'Alaska',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'Florida',
      'Georgia',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'New York',
      'North Carolina',
      'North Dakota',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Pennsylvania',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Vermont',
      'Virginia',
      'Washington',
      'West Virginia',
      'Wisconsin',
      'Wyoming',
    ],
  },
  {
    id: 'companyZip',
    type: 'text',
    label: 'Company ZIP Code',
    required: true,
    category: 'Company Information',
  },

  // Executive Information
  {
    id: 'executiveName',
    type: 'text',
    label: 'Executive Full Name',
    required: true,
    category: 'Executive Information',
  },
  {
    id: 'executiveAddress',
    type: 'text',
    label: 'Executive Street Address',
    required: true,
    category: 'Executive Information',
  },
  {
    id: 'executiveCity',
    type: 'text',
    label: 'Executive City',
    required: true,
    category: 'Executive Information',
  },
  {
    id: 'executiveState',
    type: 'select',
    label: 'Executive State',
    required: true,
    category: 'Executive Information',
    options: [
      'Alabama',
      'Alaska',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'Florida',
      'Georgia',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'New York',
      'North Carolina',
      'North Dakota',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Pennsylvania',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Vermont',
      'Virginia',
      'Washington',
      'West Virginia',
      'Wisconsin',
      'Wyoming',
    ],
  },
  {
    id: 'executiveZip',
    type: 'text',
    label: 'Executive ZIP Code',
    required: true,
    category: 'Executive Information',
  },

  // Position Details
  {
    id: 'jobTitle',
    type: 'text',
    label: 'Job Title',
    required: true,
    category: 'Position Details',
    placeholder:
      'e.g., Chief Executive Officer, President, Chief Technology Officer',
  },
  {
    id: 'department',
    type: 'text',
    label: 'Department (Optional)',
    required: false,
    category: 'Position Details',
  },
  {
    id: 'reportsTo',
    type: 'text',
    label: 'Reports To',
    required: true,
    category: 'Position Details',
    placeholder: 'e.g., Board of Directors, Chief Executive Officer',
  },
  {
    id: 'startDate',
    type: 'date',
    label: 'Employment Start Date',
    required: true,
    category: 'Position Details',
  },

  // Compensation
  {
    id: 'annualSalary',
    type: 'currency',
    label: 'Annual Base Salary',
    required: true,
    category: 'Compensation',
  },
  {
    id: 'payFrequency',
    type: 'select',
    label: 'Pay Frequency',
    required: true,
    category: 'Compensation',
    options: ['Weekly', 'Bi-weekly', 'Semi-monthly', 'Monthly'],
  },
  {
    id: 'bonusEligible',
    type: 'radio',
    label: 'Is the executive eligible for performance bonuses?',
    required: true,
    category: 'Compensation',
    options: ['Yes', 'No'],
  },
  {
    id: 'bonusStructure',
    type: 'textarea',
    label: 'Bonus Structure Details (if applicable)',
    required: false,
    category: 'Compensation',
    condition: { field: 'bonusEligible', value: 'Yes' },
    placeholder: 'Describe the bonus structure, targets, and payment terms',
  },
  {
    id: 'stockOptions',
    type: 'radio',
    label: 'Does the executive receive stock options or equity compensation?',
    required: true,
    category: 'Compensation',
    options: ['Yes', 'No'],
  },
  {
    id: 'stockOptionsDetails',
    type: 'textarea',
    label: 'Stock Options/Equity Details (if applicable)',
    required: false,
    category: 'Compensation',
    condition: { field: 'stockOptions', value: 'Yes' },
  },

  // Benefits
  {
    id: 'healthInsurance',
    type: 'radio',
    label: 'Health Insurance Provided?',
    required: true,
    category: 'Benefits',
    options: ['Yes', 'No'],
  },
  {
    id: 'dentalInsurance',
    type: 'radio',
    label: 'Dental Insurance Provided?',
    required: true,
    category: 'Benefits',
    options: ['Yes', 'No'],
  },
  {
    id: 'visionInsurance',
    type: 'radio',
    label: 'Vision Insurance Provided?',
    required: true,
    category: 'Benefits',
    options: ['Yes', 'No'],
  },
  {
    id: 'retirementPlan',
    type: 'radio',
    label: 'Retirement Plan Available?',
    required: true,
    category: 'Benefits',
    options: ['Yes', 'No'],
  },
  {
    id: 'retirementMatch',
    type: 'text',
    label: 'Company Match Details (if applicable)',
    required: false,
    category: 'Benefits',
    condition: { field: 'retirementPlan', value: 'Yes' },
    placeholder: 'e.g., 50% match up to 6% of salary',
  },
  {
    id: 'vacationDays',
    type: 'number',
    label: 'Annual Vacation Days',
    required: true,
    category: 'Benefits',
  },
  {
    id: 'sickDays',
    type: 'number',
    label: 'Annual Sick Days',
    required: true,
    category: 'Benefits',
  },
  {
    id: 'personalDays',
    type: 'number',
    label: 'Annual Personal Days (Optional)',
    required: false,
    category: 'Benefits',
  },

  // Executive Perks
  {
    id: 'companyVehicle',
    type: 'radio',
    label: 'Company Vehicle Provided?',
    required: true,
    category: 'Executive Perks',
    options: ['Yes', 'No'],
  },
  {
    id: 'vehicleAllowance',
    type: 'currency',
    label: 'Vehicle Allowance (if no company vehicle)',
    required: false,
    category: 'Executive Perks',
    condition: { field: 'companyVehicle', value: 'No' },
  },
  {
    id: 'countryClubMembership',
    type: 'radio',
    label: 'Country Club/Professional Membership Provided?',
    required: true,
    category: 'Executive Perks',
    options: ['Yes', 'No'],
  },
  {
    id: 'executivePhysical',
    type: 'radio',
    label: 'Annual Executive Physical Provided?',
    required: true,
    category: 'Executive Perks',
    options: ['Yes', 'No'],
  },
  {
    id: 'travelAllowance',
    type: 'currency',
    label: 'Annual Travel/Entertainment Allowance (Optional)',
    required: false,
    category: 'Executive Perks',
  },
  {
    id: 'expenseAccount',
    type: 'radio',
    label: 'Corporate Expense Account?',
    required: true,
    category: 'Executive Perks',
    options: ['Yes', 'No'],
  },

  // Termination Terms
  {
    id: 'terminationNotice',
    type: 'select',
    label: 'Termination Notice Period',
    required: true,
    category: 'Termination Terms',
    options: ['30 days', '60 days', '90 days', '6 months', '1 year'],
  },
  {
    id: 'severancePackage',
    type: 'radio',
    label: 'Severance Package Included?',
    required: true,
    category: 'Termination Terms',
    options: ['Yes', 'No'],
  },
  {
    id: 'severanceDetails',
    type: 'textarea',
    label: 'Severance Package Details (if applicable)',
    required: false,
    category: 'Termination Terms',
    condition: { field: 'severancePackage', value: 'Yes' },
    placeholder: 'Describe severance terms, duration, and conditions',
  },
  {
    id: 'nonCompetePeriod',
    type: 'select',
    label: 'Non-Compete Period (Optional)',
    required: false,
    category: 'Termination Terms',
    options: ['None', '6 months', '1 year', '18 months', '2 years'],
  },
  {
    id: 'nonSolicitPeriod',
    type: 'select',
    label: 'Non-Solicitation Period (Optional)',
    required: false,
    category: 'Termination Terms',
    options: ['None', '6 months', '1 year', '18 months', '2 years'],
  },

  // Confidentiality and IP
  {
    id: 'nonDisclosurePeriod',
    type: 'select',
    label: 'Confidentiality Period',
    required: true,
    category: 'Confidentiality',
    options: ['2 years', '3 years', '5 years', 'Indefinite'],
  },

  // Governing Law
  {
    id: 'governingState',
    type: 'select',
    label: 'Governing State Law',
    required: true,
    category: 'Legal Terms',
    options: [
      'Alabama',
      'Alaska',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'Florida',
      'Georgia',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'New York',
      'North Carolina',
      'North Dakota',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Pennsylvania',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Vermont',
      'Virginia',
      'Washington',
      'West Virginia',
      'Wisconsin',
      'Wyoming',
    ],
  },

  // Signatures
  {
    id: 'signatureDate',
    type: 'date',
    label: 'Agreement Date',
    required: true,
    category: 'Signatures',
  },
  {
    id: 'witnessRequired',
    type: 'radio',
    label: 'Witness Required?',
    required: true,
    category: 'Signatures',
    options: ['Yes', 'No'],
  },
  {
    id: 'witnessName',
    type: 'text',
    label: 'Witness Name (if required)',
    required: false,
    category: 'Signatures',
    condition: { field: 'witnessRequired', value: 'Yes' },
  },
];
