import { usStates } from '@/lib/usStates';
import type { Question } from '@/types/documents';

export const promissoryNoteBalloonPaymentsQuestions: Question[] = [
  { id: 'date', label: 'Date of Note', type: 'date', required: true },
  {
    id: 'placeOfExecution',
    label: 'Place of Execution',
    type: 'text',
    required: true,
    placeholder: 'City, State',
  },
  { id: 'lenderName', label: 'Lender Name', type: 'text', required: true },
  {
    id: 'lenderAddress',
    label: 'Lender Address',
    type: 'text',
    required: true,
    placeholder: 'Street, City, State, ZIP',
  },
  { id: 'borrowerName', label: 'Borrower Name', type: 'text', required: true },
  {
    id: 'borrowerAddress',
    label: 'Borrower Address',
    type: 'text',
    required: true,
    placeholder: 'Street, City, State, ZIP',
  },
  {
    id: 'principalAmount',
    label: 'Principal Amount',
    type: 'number',
    required: true,
    placeholder: 'e.g., 50000',
  },
  {
    id: 'interestRate',
    label: 'Interest Rate (%)',
    type: 'number',
    required: true,
    placeholder: 'e.g., 6',
  },
  {
    id: 'regularPaymentAmount',
    label: 'Regular Payment Amount',
    type: 'number',
    required: true,
    placeholder: 'e.g., 500',
  },
  {
    id: 'paymentFrequency',
    label: 'Payment Frequency',
    type: 'select',
    required: true,
    options: [
      { value: 'Monthly', label: 'Monthly' },
      { value: 'Quarterly', label: 'Quarterly' },
      { value: 'Semi-annually', label: 'Semi-annually' },
    ],
  },
  {
    id: 'balloonPaymentAmount',
    label: 'Balloon Payment Amount',
    type: 'number',
    required: true,
    placeholder: 'e.g., 25000',
  },
  {
    id: 'balloonPaymentDate',
    label: 'Balloon Payment Date',
    type: 'date',
    required: true,
  },
  {
    id: 'firstPaymentDate',
    label: 'First Payment Date',
    type: 'date',
    required: true,
  },
  {
    id: 'governingLaw',
    label: 'Governing Law',
    type: 'select',
    required: true,
    options: usStates.map((s) => ({ value: s.value, label: s.label })),
  },
  {
    id: 'lateFeeAmount',
    label: 'Late Fee Amount ($)',
    type: 'number',
    required: false,
    tooltip: 'Fixed dollar amount charged for late payments',
  },
  {
    id: 'gracePerod',
    label: 'Grace Period (Days)',
    type: 'number',
    required: false,
    tooltip: 'Days allowed before late fees apply',
  },
  {
    id: 'balloonPaymentNotice',
    label: 'Balloon Payment Notice (Days)',
    type: 'number',
    required: false,
    tooltip: 'Days before balloon payment to notify borrower',
  },
  {
    id: 'refinancingOption',
    label: 'Refinancing Option Available',
    type: 'boolean',
    required: false,
    tooltip: 'Whether borrower can refinance balloon payment',
  },
];
