// src/lib/documents/us/bar-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const barAgreementQuestions: FormQuestion[] = [
  {
    id: 'primaryPartyName',
    type: 'text',
    label: 'Primary Party Name',
    placeholder: 'Enter primary party name',
    required: true,
    group: 'parties',
  },
  {
    id: 'secondaryPartyName',
    type: 'text',
    label: 'Secondary Party Name',
    placeholder: 'Enter secondary party name',
    required: true,
    group: 'parties',
  },
  {
    id: 'barName',
    type: 'text',
    label: 'Bar Name',
    placeholder: 'Enter bar name',
    required: true,
    group: 'bar',
  },
  {
    id: 'barAddress',
    type: 'text',
    label: 'Bar Address',
    placeholder: 'Enter bar address',
    required: false,
    group: 'bar',
  },
  {
    id: 'barType',
    type: 'select',
    label: 'Bar Type',
    options: [
      { value: 'sports-bar', label: 'Sports Bar' },
      { value: 'cocktail-bar', label: 'Cocktail Bar' },
      { value: 'dive-bar', label: 'Dive Bar' },
      { value: 'wine-bar', label: 'Wine Bar' },
      { value: 'nightclub', label: 'Nightclub' },
      { value: 'pub', label: 'Pub' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
    group: 'bar',
  },
  {
    id: 'seatingCapacity',
    type: 'text',
    label: 'Seating Capacity',
    placeholder: 'Enter seating capacity',
    required: false,
    group: 'bar',
  },
  {
    id: 'liquorLicense',
    type: 'boolean',
    label: 'Liquor license required?',
    required: false,
    group: 'licenses',
  },
  {
    id: 'liquorLicenseNumber',
    type: 'text',
    label: 'Liquor License Number',
    placeholder: 'Enter liquor license number',
    required: false,
    group: 'licenses',
  },
  {
    id: 'fullLiquorLicense',
    type: 'boolean',
    label: 'Full liquor license?',
    required: false,
    group: 'licenses',
  },
  {
    id: 'totalInvestment',
    type: 'text',
    label: 'Total Investment',
    placeholder: 'Enter total investment amount',
    required: false,
    group: 'financial',
  },
  {
    id: 'ownershipPercentage',
    type: 'text',
    label: 'Ownership Percentage',
    placeholder: 'Enter ownership split (e.g., 50/50)',
    required: false,
    group: 'financial',
  },
  {
    id: 'operatingHours',
    type: 'text',
    label: 'Operating Hours',
    placeholder: 'Enter operating hours',
    required: false,
    group: 'operations',
  },
  {
    id: 'happyHourSchedule',
    type: 'text',
    label: 'Happy Hour Schedule',
    placeholder: 'Enter happy hour times',
    required: false,
    group: 'operations',
  },
  {
    id: 'lastCall',
    type: 'text',
    label: 'Last Call Time',
    placeholder: 'Enter last call time',
    required: false,
    group: 'operations',
  },
  {
    id: 'dailyOperations',
    type: 'select',
    label: 'Daily Operations Management',
    options: [
      { value: 'joint', label: 'Joint Management' },
      { value: 'primary-party', label: 'Primary Party' },
      { value: 'secondary-party', label: 'Secondary Party' },
      { value: 'manager', label: 'Hired Manager' },
    ],
    required: false,
    group: 'management',
  },
  {
    id: 'staffManagement',
    type: 'select',
    label: 'Staff Management',
    options: [
      { value: 'joint', label: 'Joint Responsibility' },
      { value: 'primary-party', label: 'Primary Party' },
      { value: 'secondary-party', label: 'Secondary Party' },
      { value: 'manager', label: 'Hired Manager' },
    ],
    required: false,
    group: 'management',
  },
  {
    id: 'drinkMenuControl',
    type: 'select',
    label: 'Drink Menu Control',
    options: [
      { value: 'joint', label: 'Joint Decision' },
      { value: 'primary-party', label: 'Primary Party' },
      { value: 'secondary-party', label: 'Secondary Party' },
      { value: 'bartender', label: 'Head Bartender' },
    ],
    required: false,
    group: 'beverage',
  },
  {
    id: 'specialtyDrinks',
    type: 'textarea',
    label: 'Specialty Drinks',
    placeholder: 'Describe signature cocktails or specialty drinks',
    required: false,
    group: 'beverage',
  },
  {
    id: 'foodService',
    type: 'boolean',
    label: 'Food service offered?',
    required: false,
    group: 'food',
  },
  {
    id: 'kitchenFacilities',
    type: 'boolean',
    label: 'Kitchen facilities available?',
    required: false,
    group: 'food',
  },
  {
    id: 'liveEntertainment',
    type: 'boolean',
    label: 'Live entertainment offered?',
    required: false,
    group: 'entertainment',
  },
  {
    id: 'sportsEvents',
    type: 'boolean',
    label: 'Sports events shown?',
    required: false,
    group: 'entertainment',
  },
  {
    id: 'entertainmentBudget',
    type: 'text',
    label: 'Entertainment Budget',
    placeholder: 'Enter monthly entertainment budget',
    required: false,
    group: 'entertainment',
  },
  {
    id: 'securityStaff',
    type: 'boolean',
    label: 'Security staff required?',
    required: false,
    group: 'staffing',
  },
  {
    id: 'minimumStaffing',
    type: 'text',
    label: 'Minimum Staffing',
    placeholder: 'Describe minimum staffing requirements',
    required: false,
    group: 'staffing',
  },
  {
    id: 'posSystem',
    type: 'boolean',
    label: 'POS system installed?',
    required: false,
    group: 'equipment',
  },
  {
    id: 'securitySystem',
    type: 'boolean',
    label: 'Security system installed?',
    required: false,
    group: 'equipment',
  },
  {
    id: 'televisions',
    type: 'boolean',
    label: 'Televisions for entertainment?',
    required: false,
    group: 'equipment',
  },
  {
    id: 'marketingStrategy',
    type: 'textarea',
    label: 'Marketing Strategy',
    placeholder: 'Describe marketing and promotion strategy',
    required: false,
    group: 'marketing',
  },
  {
    id: 'loyaltyProgram',
    type: 'boolean',
    label: 'Customer loyalty program?',
    required: false,
    group: 'marketing',
  },
  {
    id: 'alcoholSafetyTraining',
    type: 'boolean',
    label: 'Alcohol safety training required?',
    required: false,
    group: 'safety',
  },
  {
    id: 'ageVerificationProcedures',
    type: 'textarea',
    label: 'Age Verification Procedures',
    placeholder: 'Describe ID checking procedures',
    required: false,
    group: 'safety',
  },
  {
    id: 'smokingPolicy',
    type: 'select',
    label: 'Smoking Policy',
    options: [
      { value: 'no-smoking', label: 'No Smoking' },
      { value: 'smoking-allowed', label: 'Smoking Allowed' },
      { value: 'designated-area', label: 'Designated Smoking Area' },
    ],
    required: false,
    group: 'policies',
  },
  {
    id: 'agreementTerm',
    type: 'text',
    label: 'Agreement Term',
    placeholder: 'Enter agreement duration (e.g., 3 years)',
    required: false,
    group: 'term',
  },
  {
    id: 'renewalOptions',
    type: 'boolean',
    label: 'Include renewal options?',
    required: false,
    group: 'term',
  },
  {
    id: 'nonCompeteClause',
    type: 'boolean',
    label: 'Include non-compete clause?',
    required: false,
    group: 'termination',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'Enter governing law/state',
    required: false,
    group: 'legal',
  },
];
