// src/lib/documents/us/water-rights-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const waterRightsAgreementQuestions: FormQuestion[] = [
  {
    id: 'ownerName',
    type: 'text',
    label: 'Water Rights Owner Name',
    placeholder: 'Enter current water rights owner',
    required: true,
    group: 'owner',
  },
  {
    id: 'userName',
    type: 'text',
    label: 'Water User Name',
    placeholder: 'Enter water rights transferee/user',
    required: true,
    group: 'user',
  },
  {
    id: 'waterRightNumber',
    type: 'text',
    label: 'Water Right Number',
    placeholder: 'Enter state water right permit number',
    required: false,
    group: 'water-right',
  },
  {
    id: 'waterSource',
    type: 'select',
    label: 'Water Source Type',
    options: [
      { value: 'surface', label: 'Surface Water' },
      { value: 'groundwater', label: 'Groundwater' },
      { value: 'spring', label: 'Spring' },
      { value: 'well', label: 'Well' },
      { value: 'river', label: 'River' },
      { value: 'lake', label: 'Lake' },
    ],
    required: false,
    group: 'water-right',
  },
  {
    id: 'agreementType',
    type: 'select',
    label: 'Agreement Type',
    options: [
      { value: 'sale', label: 'Sale' },
      { value: 'lease', label: 'Lease' },
      { value: 'transfer', label: 'Transfer' },
      { value: 'exchange', label: 'Exchange' },
      { value: 'sharing', label: 'Sharing' },
    ],
    required: false,
    group: 'agreement',
  },
  {
    id: 'annualQuantity',
    type: 'text',
    label: 'Annual Water Quantity',
    placeholder: 'Enter annual water allocation',
    required: false,
    group: 'quantity',
  },
  {
    id: 'measurementUnit',
    type: 'select',
    label: 'Measurement Unit',
    options: [
      { value: 'acre-feet', label: 'Acre-Feet' },
      { value: 'gallons', label: 'Gallons' },
      { value: 'cubic-feet', label: 'Cubic Feet' },
      { value: 'liters', label: 'Liters' },
    ],
    required: false,
    group: 'quantity',
  },
  {
    id: 'authorizedUses',
    type: 'multi-select',
    label: 'Authorized Uses',
    options: [
      { value: 'irrigation', label: 'Irrigation' },
      { value: 'municipal', label: 'Municipal' },
      { value: 'industrial', label: 'Industrial' },
      { value: 'domestic', label: 'Domestic' },
      { value: 'livestock', label: 'Livestock' },
      { value: 'recreation', label: 'Recreation' },
      { value: 'environmental', label: 'Environmental' },
    ],
    required: false,
    group: 'usage',
  },
  {
    id: 'purchasePrice',
    type: 'text',
    label: 'Purchase Price/Lease Payment',
    placeholder: 'Enter payment amount',
    required: false,
    group: 'payment',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'annually', label: 'Annually' },
      { value: 'semi-annually', label: 'Semi-Annually' },
      { value: 'quarterly', label: 'Quarterly' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'lump-sum', label: 'Lump Sum' },
    ],
    required: false,
    group: 'payment',
  },
  {
    id: 'deliveryMethod',
    type: 'select',
    label: 'Water Delivery Method',
    options: [
      { value: 'canal', label: 'Canal' },
      { value: 'pipeline', label: 'Pipeline' },
      { value: 'ditch', label: 'Ditch' },
      { value: 'natural-flow', label: 'Natural Flow' },
      { value: 'pumping', label: 'Pumping' },
    ],
    required: false,
    group: 'delivery',
  },
  {
    id: 'environmentalCompliance',
    type: 'boolean',
    label: 'Environmental compliance required?',
    required: false,
    group: 'environmental',
  },
  {
    id: 'qualityTesting',
    type: 'boolean',
    label: 'Water quality testing required?',
    required: false,
    group: 'quality',
  },
  {
    id: 'droughtRestrictions',
    type: 'boolean',
    label: 'Drought restrictions applicable?',
    required: false,
    group: 'restrictions',
  },
];
