// src/lib/documents/us/service-level-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const serviceLevelAgreementQuestions: FormQuestion[] = [
  {
    id: 'serviceType',
    type: 'select',
    label: 'Type of Service',
    options: [
      { value: 'it-support', label: 'IT Support Services' },
      { value: 'cloud-services', label: 'Cloud Services' },
      { value: 'managed-services', label: 'Managed Services' },
      { value: 'consulting', label: 'Consulting Services' },
      { value: 'maintenance', label: 'Maintenance Services' },
      { value: 'other', label: 'Other Services' },
    ],
    required: true,
    group: 'basic',
  },
  {
    id: 'serviceDescription',
    type: 'textarea',
    label: 'Service Description',
    placeholder: 'Describe the services to be provided',
    required: true,
    group: 'basic',
  },
  {
    id: 'serviceScope',
    type: 'textarea',
    label: 'Service Scope',
    placeholder: 'Define the scope and boundaries of the services',
    required: true,
    group: 'basic',
  },
  {
    id: 'deliverables',
    type: 'textarea',
    label: 'Deliverables',
    placeholder: 'List specific deliverables or outcomes',
    required: false,
    group: 'basic',
  },
  {
    id: 'serviceProvider',
    type: 'text',
    label: 'Service Provider Name',
    placeholder: 'Enter service provider company name',
    required: true,
    group: 'provider',
  },
  {
    id: 'serviceProviderAddress',
    type: 'textarea',
    label: 'Service Provider Address',
    placeholder: 'Enter complete business address',
    required: true,
    group: 'provider',
  },
  {
    id: 'serviceProviderContact',
    type: 'text',
    label: 'Service Provider Contact',
    placeholder: 'Primary contact person and details',
    required: false,
    group: 'provider',
  },
  {
    id: 'client',
    type: 'text',
    label: 'Client Name',
    placeholder: 'Enter client company or individual name',
    required: true,
    group: 'client',
  },
  {
    id: 'clientAddress',
    type: 'textarea',
    label: 'Client Address',
    placeholder: 'Enter complete client address',
    required: true,
    group: 'client',
  },
  {
    id: 'clientContact',
    type: 'text',
    label: 'Client Contact',
    placeholder: 'Primary contact person and details',
    required: false,
    group: 'client',
  },
  {
    id: 'availabilityTarget',
    type: 'text',
    label: 'Availability Target',
    placeholder: 'e.g., 99.9% uptime, 24/7 availability',
    required: false,
    group: 'performance',
  },
  {
    id: 'uptimeRequirement',
    type: 'text',
    label: 'Uptime Requirement',
    placeholder: 'e.g., 99.5% monthly uptime',
    required: false,
    group: 'performance',
  },
  {
    id: 'responseTimeTargets',
    type: 'textarea',
    label: 'Response Time Targets',
    placeholder: 'e.g., Critical: 1 hour, High: 4 hours, Medium: 8 hours',
    required: false,
    group: 'performance',
  },
  {
    id: 'resolutionTimeTargets',
    type: 'textarea',
    label: 'Resolution Time Targets',
    placeholder: 'e.g., Critical: 4 hours, High: 24 hours, Medium: 72 hours',
    required: false,
    group: 'performance',
  },
  {
    id: 'performanceMetrics',
    type: 'textarea',
    label: 'Performance Metrics',
    placeholder: 'Define key performance indicators and measurement criteria',
    required: false,
    group: 'performance',
  },
  {
    id: 'qualityStandards',
    type: 'textarea',
    label: 'Quality Standards',
    placeholder: 'Specify quality standards and acceptance criteria',
    required: false,
    group: 'performance',
  },
  {
    id: 'serviceHours',
    type: 'text',
    label: 'Service Hours',
    placeholder: 'e.g., 8 AM - 6 PM EST, 24/7',
    required: false,
    group: 'schedule',
  },
  {
    id: 'businessHours',
    type: 'text',
    label: 'Business Hours',
    placeholder: 'e.g., Monday-Friday 9 AM - 5 PM',
    required: false,
    group: 'schedule',
  },
  {
    id: 'afterHoursSupport',
    type: 'checkbox',
    label: 'After-hours support available',
    required: false,
    group: 'schedule',
  },
  {
    id: 'holidaySupport',
    type: 'checkbox',
    label: 'Holiday support available',
    required: false,
    group: 'schedule',
  },
  {
    id: 'escalationProcedure',
    type: 'textarea',
    label: 'Escalation Procedure',
    placeholder: 'Describe the escalation process for issues',
    required: false,
    group: 'schedule',
  },
  {
    id: 'reportingFrequency',
    type: 'select',
    label: 'Reporting Frequency',
    options: [
      { value: 'daily', label: 'Daily' },
      { value: 'weekly', label: 'Weekly' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
    ],
    required: false,
    group: 'reporting',
  },
  {
    id: 'reportingFormat',
    type: 'text',
    label: 'Reporting Format',
    placeholder: 'e.g., Dashboard, Email reports, Written reports',
    required: false,
    group: 'reporting',
  },
  {
    id: 'performanceReports',
    type: 'textarea',
    label: 'Performance Reports',
    placeholder: 'Specify what performance data should be reported',
    required: false,
    group: 'reporting',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Effective Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'expirationDate',
    type: 'date',
    label: 'Expiration Date',
    required: false,
    group: 'timeline',
  },
  {
    id: 'termLength',
    type: 'text',
    label: 'Term Length',
    placeholder: 'e.g., 1 year, 2 years, ongoing',
    required: false,
    group: 'timeline',
  },
  {
    id: 'renewalTerms',
    type: 'textarea',
    label: 'Renewal Terms',
    placeholder: 'Specify how the agreement can be renewed',
    required: false,
    group: 'timeline',
  },
  {
    id: 'serviceFees',
    type: 'textarea',
    label: 'Service Fees',
    placeholder: 'Specify service fees and pricing structure',
    required: false,
    group: 'financial',
  },
  {
    id: 'paymentTerms',
    type: 'textarea',
    label: 'Payment Terms',
    placeholder: 'Specify payment terms and conditions',
    required: false,
    group: 'financial',
  },
  {
    id: 'billingSchedule',
    type: 'select',
    label: 'Billing Schedule',
    options: [
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
      { value: 'annually', label: 'Annually' },
      { value: 'milestone-based', label: 'Milestone-based' },
    ],
    required: false,
    group: 'financial',
  },
  {
    id: 'providerResponsibilities',
    type: 'textarea',
    label: 'Provider Responsibilities',
    placeholder: 'List specific responsibilities of the service provider',
    required: true,
    group: 'responsibilities',
  },
  {
    id: 'clientResponsibilities',
    type: 'textarea',
    label: 'Client Responsibilities',
    placeholder: 'List specific responsibilities of the client',
    required: true,
    group: 'responsibilities',
  },
  {
    id: 'mutualResponsibilities',
    type: 'textarea',
    label: 'Mutual Responsibilities',
    placeholder: 'Describe shared responsibilities',
    required: false,
    group: 'responsibilities',
  },
  {
    id: 'penaltyStructure',
    type: 'textarea',
    label: 'Penalty Structure',
    placeholder: 'Define penalties for not meeting service levels',
    required: false,
    group: 'penalties',
  },
  {
    id: 'serviceCreditTerms',
    type: 'textarea',
    label: 'Service Credit Terms',
    placeholder: 'Specify service credits for performance failures',
    required: false,
    group: 'penalties',
  },
  {
    id: 'performanceIncentives',
    type: 'textarea',
    label: 'Performance Incentives',
    placeholder: 'Define incentives for exceeding service levels',
    required: false,
    group: 'penalties',
  },
  {
    id: 'securityRequirements',
    type: 'textarea',
    label: 'Security Requirements',
    placeholder: 'Specify security standards and requirements',
    required: false,
    group: 'security',
  },
  {
    id: 'dataProtection',
    type: 'textarea',
    label: 'Data Protection',
    placeholder: 'Describe data protection and privacy requirements',
    required: false,
    group: 'security',
  },
  {
    id: 'backupRequirements',
    type: 'textarea',
    label: 'Backup Requirements',
    placeholder: 'Specify backup and recovery requirements',
    required: false,
    group: 'security',
  },
  {
    id: 'changeRequestProcess',
    type: 'textarea',
    label: 'Change Request Process',
    placeholder: 'Describe how changes to services are requested and approved',
    required: false,
    group: 'change',
  },
  {
    id: 'terminationClause',
    type: 'textarea',
    label: 'Termination Conditions',
    placeholder:
      'Specify conditions under which the agreement can be terminated',
    required: false,
    group: 'termination',
  },
  {
    id: 'noticePeriod',
    type: 'text',
    label: 'Notice Period for Termination',
    placeholder: '30 days',
    required: false,
    group: 'termination',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'negotiation', label: 'Good Faith Negotiation' },
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'litigation', label: 'Court Litigation' },
    ],
    required: false,
    group: 'disputes',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'e.g., State of California',
    required: false,
    group: 'disputes',
  },
  {
    id: 'confidentialityClause',
    type: 'checkbox',
    label: 'Include confidentiality provisions',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'additionalTerms',
    type: 'textarea',
    label: 'Additional Terms',
    placeholder: 'Any additional terms or special provisions',
    required: false,
    group: 'additional',
  },
];
