// src/lib/documents/us/personal-loan-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const personalLoanAgreementQuestions: FormQuestion[] = [
  {
    id: 'lenderName',
    type: 'text',
    label: 'Lender Name',
    placeholder: 'Enter lender full name',
    required: true,
    group: 'lender',
  },
  {
    id: 'lenderAddress',
    type: 'text',
    label: 'Lender Address',
    placeholder: 'Enter complete lender address',
    required: true,
    group: 'lender',
  },
  {
    id: 'lenderPhone',
    type: 'text',
    label: 'Lender Phone Number',
    placeholder: 'Enter lender phone number',
    required: false,
    group: 'lender',
  },
  {
    id: 'lenderEmail',
    type: 'email',
    label: 'Lender Email',
    placeholder: 'Enter lender email address',
    required: false,
    group: 'lender',
  },
  {
    id: 'borrowerName',
    type: 'text',
    label: 'Borrower Name',
    placeholder: 'Enter borrower full name',
    required: true,
    group: 'borrower',
  },
  {
    id: 'borrowerAddress',
    type: 'text',
    label: 'Borrower Address',
    placeholder: 'Enter complete borrower address',
    required: true,
    group: 'borrower',
  },
  {
    id: 'borrowerPhone',
    type: 'text',
    label: 'Borrower Phone Number',
    placeholder: 'Enter borrower phone number',
    required: false,
    group: 'borrower',
  },
  {
    id: 'borrowerEmail',
    type: 'email',
    label: 'Borrower Email',
    placeholder: 'Enter borrower email address',
    required: false,
    group: 'borrower',
  },
  {
    id: 'borrowerSSN',
    type: 'text',
    label: 'Borrower SSN (optional)',
    placeholder: 'Enter Social Security Number',
    required: false,
    group: 'borrower',
  },
  {
    id: 'hasCoBorrower',
    type: 'checkbox',
    label: 'Include co-borrower',
    required: false,
    group: 'co-borrower',
  },
  {
    id: 'coBorrowerName',
    type: 'text',
    label: 'Co-borrower Name',
    placeholder: 'Enter co-borrower full name',
    required: false,
    group: 'co-borrower',
    dependsOn: 'hasCoBorrower',
  },
  {
    id: 'coBorrowerAddress',
    type: 'text',
    label: 'Co-borrower Address',
    placeholder: 'Enter co-borrower address',
    required: false,
    group: 'co-borrower',
    dependsOn: 'hasCoBorrower',
  },
  {
    id: 'loanAmount',
    type: 'text',
    label: 'Loan Amount',
    placeholder: 'Enter loan amount (e.g., $10,000)',
    required: true,
    group: 'loan-details',
  },
  {
    id: 'loanPurpose',
    type: 'text',
    label: 'Loan Purpose',
    placeholder: 'e.g., Home improvement, debt consolidation',
    required: true,
    group: 'loan-details',
  },
  {
    id: 'loanDate',
    type: 'date',
    label: 'Loan Date',
    required: true,
    group: 'loan-details',
  },
  {
    id: 'interestRate',
    type: 'text',
    label: 'Interest Rate',
    placeholder: 'e.g., 5.25% per year',
    required: true,
    group: 'interest',
  },
  {
    id: 'interestType',
    type: 'select',
    label: 'Interest Type',
    options: [
      { value: 'fixed', label: 'Fixed Rate' },
      { value: 'variable', label: 'Variable Rate' },
    ],
    required: true,
    group: 'interest',
  },
  {
    id: 'compoundingFrequency',
    type: 'select',
    label: 'Interest Compounding Frequency',
    options: [
      { value: 'daily', label: 'Daily' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
      { value: 'annually', label: 'Annually' },
    ],
    required: true,
    group: 'interest',
  },
  {
    id: 'loanTerm',
    type: 'text',
    label: 'Loan Term',
    placeholder: 'e.g., 3 years, 36 months',
    required: true,
    group: 'repayment',
  },
  {
    id: 'paymentAmount',
    type: 'text',
    label: 'Payment Amount',
    placeholder: 'Amount of each payment',
    required: true,
    group: 'repayment',
  },
  {
    id: 'paymentFrequency',
    type: 'select',
    label: 'Payment Frequency',
    options: [
      { value: 'weekly', label: 'Weekly' },
      { value: 'bi-weekly', label: 'Bi-weekly' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
    ],
    required: true,
    group: 'repayment',
  },
  {
    id: 'firstPaymentDate',
    type: 'date',
    label: 'First Payment Date',
    required: true,
    group: 'repayment',
  },
  {
    id: 'maturityDate',
    type: 'date',
    label: 'Final Payment Date',
    required: true,
    group: 'repayment',
  },
  {
    id: 'paymentMethod',
    type: 'select',
    label: 'Payment Method',
    options: [
      { value: 'check', label: 'Check' },
      { value: 'bank-transfer', label: 'Bank Transfer' },
      { value: 'automatic-deduction', label: 'Automatic Deduction' },
      { value: 'cash', label: 'Cash' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'payment-method',
  },
  {
    id: 'lateFee',
    type: 'checkbox',
    label: 'Include late fee provisions',
    required: false,
    group: 'penalties',
  },
  {
    id: 'lateFeeAmount',
    type: 'text',
    label: 'Late Fee Amount',
    placeholder: 'e.g., $25 or 5% of payment',
    required: false,
    group: 'penalties',
    dependsOn: 'lateFee',
  },
  {
    id: 'gracePeriod',
    type: 'text',
    label: 'Grace Period',
    placeholder: 'e.g., 10 days',
    required: false,
    group: 'penalties',
    dependsOn: 'lateFee',
  },
  {
    id: 'prepaymentAllowed',
    type: 'checkbox',
    label: 'Allow early payment without penalty',
    required: false,
    group: 'prepayment',
  },
  {
    id: 'prepaymentPenalty',
    type: 'checkbox',
    label: 'Include prepayment penalty',
    required: false,
    group: 'prepayment',
  },
  {
    id: 'prepaymentPenaltyAmount',
    type: 'text',
    label: 'Prepayment Penalty Amount',
    placeholder: 'e.g., 2% of remaining balance',
    required: false,
    group: 'prepayment',
    dependsOn: 'prepaymentPenalty',
  },
  {
    id: 'isSecured',
    type: 'checkbox',
    label: 'Secured loan (has collateral)',
    required: false,
    group: 'security',
  },
  {
    id: 'collateralDescription',
    type: 'textarea',
    label: 'Collateral Description',
    placeholder: 'Describe the collateral securing this loan',
    required: false,
    group: 'security',
    dependsOn: 'isSecured',
  },
  {
    id: 'collateralValue',
    type: 'text',
    label: 'Collateral Value',
    placeholder: 'Estimated value of collateral',
    required: false,
    group: 'security',
    dependsOn: 'isSecured',
  },
  {
    id: 'hasGuarantor',
    type: 'checkbox',
    label: 'Include guarantor',
    required: false,
    group: 'guarantor',
  },
  {
    id: 'guarantorName',
    type: 'text',
    label: 'Guarantor Name',
    placeholder: 'Enter guarantor full name',
    required: false,
    group: 'guarantor',
    dependsOn: 'hasGuarantor',
  },
  {
    id: 'guarantorAddress',
    type: 'text',
    label: 'Guarantor Address',
    placeholder: 'Enter guarantor address',
    required: false,
    group: 'guarantor',
    dependsOn: 'hasGuarantor',
  },
  {
    id: 'defaultClause',
    type: 'checkbox',
    label: 'Include default provisions',
    required: false,
    group: 'default',
  },
  {
    id: 'accelerationClause',
    type: 'checkbox',
    label: 'Include acceleration clause',
    required: false,
    group: 'default',
  },
  {
    id: 'curePeriod',
    type: 'text',
    label: 'Cure Period for Default',
    placeholder: 'e.g., 30 days to cure default',
    required: false,
    group: 'default',
  },
  {
    id: 'requireInsurance',
    type: 'checkbox',
    label: 'Require insurance on collateral',
    required: false,
    group: 'insurance',
  },
  {
    id: 'insuranceType',
    type: 'text',
    label: 'Insurance Type Required',
    placeholder: 'e.g., Life insurance, property insurance',
    required: false,
    group: 'insurance',
    dependsOn: 'requireInsurance',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law (State)',
    placeholder: 'e.g., State of California',
    required: false,
    group: 'legal',
  },
  {
    id: 'attorneyFees',
    type: 'checkbox',
    label: 'Include attorney fees clause',
    required: false,
    group: 'legal',
  },
  {
    id: 'creditCheck',
    type: 'checkbox',
    label: 'Require credit check',
    required: false,
    group: 'requirements',
  },
  {
    id: 'incomeVerification',
    type: 'checkbox',
    label: 'Require income verification',
    required: false,
    group: 'requirements',
  },
  {
    id: 'requireNotarization',
    type: 'checkbox',
    label: 'Require notarization',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireBorrowerSignature',
    type: 'checkbox',
    label: 'Require borrower signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireLenderSignature',
    type: 'checkbox',
    label: 'Require lender signature',
    required: false,
    group: 'signatures',
  },
];
