// src/lib/documents/us/employee-handbook/questions.ts
import type { FormQuestion } from '@/types/documents';

export const employeeHandbookQuestions: FormQuestion[] = [
  {
    id: 'companyName',
    type: 'text',
    label: 'Company Name',
    placeholder: 'Enter your company name',
    required: true,
    group: 'company',
  },
  {
    id: 'companyAddress',
    type: 'textarea',
    label: 'Company Address',
    placeholder: 'Enter your company address',
    required: true,
    group: 'company',
  },
  {
    id: 'companyPhone',
    type: 'tel',
    label: 'Company Phone',
    placeholder: '(555) 123-4567',
    required: false,
    group: 'company',
  },
  {
    id: 'companyWebsite',
    type: 'text',
    label: 'Company Website',
    placeholder: 'www.company.com',
    required: false,
    group: 'company',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Handbook Effective Date',
    required: true,
    group: 'handbook',
  },
  {
    id: 'handbookVersion',
    type: 'text',
    label: 'Handbook Version',
    placeholder: 'e.g., 2.0, 2024.1',
    required: false,
    group: 'handbook',
  },
  {
    id: 'standardWorkWeek',
    type: 'text',
    label: 'Standard Work Week',
    placeholder: '40 hours',
    required: false,
    group: 'schedule',
  },
  {
    id: 'workingHours',
    type: 'text',
    label: 'Working Hours',
    placeholder: '9:00 AM - 5:00 PM',
    required: false,
    group: 'schedule',
  },
  {
    id: 'lunchBreak',
    type: 'text',
    label: 'Lunch Break Duration',
    placeholder: '1 hour',
    required: false,
    group: 'schedule',
  },
  {
    id: 'flexibleSchedule',
    type: 'checkbox',
    label: 'Flexible schedule options available',
    required: false,
    group: 'schedule',
  },
  {
    id: 'remoteWork',
    type: 'checkbox',
    label: 'Remote work options available',
    required: false,
    group: 'schedule',
  },
  {
    id: 'payFrequency',
    type: 'select',
    label: 'Pay Frequency',
    options: [
      { value: 'weekly', label: 'Weekly' },
      { value: 'bi-weekly', label: 'Bi-weekly' },
      { value: 'semi-monthly', label: 'Semi-monthly' },
      { value: 'monthly', label: 'Monthly' },
    ],
    required: true,
    group: 'compensation',
  },
  {
    id: 'overtimePolicy',
    type: 'textarea',
    label: 'Overtime Policy',
    placeholder: 'Describe overtime pay and approval process',
    required: false,
    group: 'compensation',
  },
  {
    id: 'healthInsurance',
    type: 'checkbox',
    label: 'Health insurance provided',
    required: false,
    group: 'benefits',
  },
  {
    id: 'retirementPlan',
    type: 'checkbox',
    label: 'Retirement plan (401k, etc.) provided',
    required: false,
    group: 'benefits',
  },
  {
    id: 'vacationPolicy',
    type: 'textarea',
    label: 'Vacation Policy',
    placeholder: 'Describe vacation accrual, approval, and usage',
    required: false,
    group: 'benefits',
  },
  {
    id: 'sickLeave',
    type: 'textarea',
    label: 'Sick Leave Policy',
    placeholder: 'Describe sick leave accrual and usage',
    required: false,
    group: 'benefits',
  },
  {
    id: 'holidays',
    type: 'textarea',
    label: 'Company Holidays',
    placeholder: 'List observed holidays',
    required: false,
    group: 'benefits',
  },
  {
    id: 'attendancePolicy',
    type: 'textarea',
    label: 'Attendance Policy',
    placeholder: 'Describe attendance expectations and consequences',
    required: false,
    group: 'attendance',
  },
  {
    id: 'tardinessPolicy',
    type: 'textarea',
    label: 'Tardiness Policy',
    placeholder: 'Describe policy for late arrivals',
    required: false,
    group: 'attendance',
  },
  {
    id: 'absenceNotification',
    type: 'textarea',
    label: 'Absence Notification Requirements',
    placeholder: 'How and when to report absences',
    required: false,
    group: 'attendance',
  },
  {
    id: 'fmlaPolicy',
    type: 'checkbox',
    label: 'FMLA (Family Medical Leave Act) applies',
    required: false,
    group: 'leave',
  },
  {
    id: 'maternityLeave',
    type: 'textarea',
    label: 'Maternity Leave Policy',
    placeholder: 'Describe maternity leave benefits',
    required: false,
    group: 'leave',
  },
  {
    id: 'paternityLeave',
    type: 'textarea',
    label: 'Paternity Leave Policy',
    placeholder: 'Describe paternity leave benefits',
    required: false,
    group: 'leave',
  },
  {
    id: 'dressCode',
    type: 'textarea',
    label: 'Dress Code Policy',
    placeholder: 'Describe workplace attire expectations',
    required: false,
    group: 'conduct',
  },
  {
    id: 'internetUsage',
    type: 'textarea',
    label: 'Internet Usage Policy',
    placeholder: 'Describe acceptable internet and email use',
    required: false,
    group: 'conduct',
  },
  {
    id: 'socialMediaPolicy',
    type: 'textarea',
    label: 'Social Media Policy',
    placeholder: 'Guidelines for social media use related to work',
    required: false,
    group: 'conduct',
  },
  {
    id: 'confidentialityPolicy',
    type: 'textarea',
    label: 'Confidentiality Policy',
    placeholder: 'Describe expectations for handling confidential information',
    required: false,
    group: 'conduct',
  },
  {
    id: 'drugFreeWorkplace',
    type: 'checkbox',
    label: 'Drug-free workplace policy',
    required: false,
    group: 'safety',
  },
  {
    id: 'workplaceSafety',
    type: 'textarea',
    label: 'Workplace Safety Policy',
    placeholder: 'Describe safety procedures and expectations',
    required: false,
    group: 'safety',
  },
  {
    id: 'emergencyProcedures',
    type: 'textarea',
    label: 'Emergency Procedures',
    placeholder: 'Describe procedures for emergencies',
    required: false,
    group: 'safety',
  },
  {
    id: 'performanceReviews',
    type: 'textarea',
    label: 'Performance Review Process',
    placeholder: 'Describe how and when performance reviews are conducted',
    required: false,
    group: 'performance',
  },
  {
    id: 'disciplinaryProcess',
    type: 'textarea',
    label: 'Disciplinary Process',
    placeholder: 'Describe progressive discipline procedures',
    required: false,
    group: 'performance',
  },
  {
    id: 'grievanceProcedure',
    type: 'textarea',
    label: 'Grievance Procedure',
    placeholder: 'How employees can file complaints or grievances',
    required: false,
    group: 'performance',
  },
  {
    id: 'terminationPolicy',
    type: 'textarea',
    label: 'Termination Policy',
    placeholder: 'Describe termination procedures and final pay',
    required: false,
    group: 'performance',
  },
  {
    id: 'acknowledgmentRequired',
    type: 'checkbox',
    label: 'Require employee acknowledgment of handbook receipt',
    required: false,
    group: 'acknowledgment',
  },
  {
    id: 'acknowledgmentText',
    type: 'textarea',
    label: 'Acknowledgment Text',
    placeholder: 'Text for employee to acknowledge receipt and understanding',
    required: false,
    group: 'acknowledgment',
    dependsOn: 'acknowledgmentRequired',
  },
];
