// src/lib/documents/us/lease-renewal-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const leaseRenewalAgreementQuestions: FormQuestion[] = [
  {
    id: 'landlordName',
    type: 'text',
    label: 'Landlord Name',
    placeholder: 'Enter landlord full name',
    required: true,
    group: 'parties',
  },
  {
    id: 'tenantName',
    type: 'text',
    label: 'Tenant Name',
    placeholder: 'Enter tenant full name',
    required: true,
    group: 'parties',
  },
  {
    id: 'propertyAddress',
    type: 'textarea',
    label: 'Property Address',
    placeholder: 'Enter the rental property address',
    required: true,
    group: 'parties',
  },
  {
    id: 'originalLeaseDate',
    type: 'date',
    label: 'Original Lease Start Date',
    required: true,
    group: 'original',
  },
  {
    id: 'originalLeaseEndDate',
    type: 'date',
    label: 'Original Lease End Date',
    required: true,
    group: 'original',
  },
  {
    id: 'renewalStartDate',
    type: 'date',
    label: 'Renewal Start Date',
    required: true,
    group: 'renewal',
  },
  {
    id: 'renewalEndDate',
    type: 'date',
    label: 'Renewal End Date',
    required: true,
    group: 'renewal',
  },
  {
    id: 'renewalTerm',
    type: 'select',
    label: 'Renewal Term',
    options: [
      { value: '6 months', label: '6 Months' },
      { value: '1 year', label: '1 Year' },
      { value: '2 years', label: '2 Years' },
      { value: 'month-to-month', label: 'Month-to-Month' },
    ],
    required: true,
    group: 'renewal',
  },
  {
    id: 'newMonthlyRent',
    type: 'number',
    label: 'New Monthly Rent ($)',
    placeholder: '1200',
    required: true,
    group: 'financial',
  },
  {
    id: 'rentIncreaseAmount',
    type: 'number',
    label: 'Rent Increase Amount ($)',
    placeholder: '50',
    required: false,
    group: 'financial',
  },
  {
    id: 'rentIncreasePercentage',
    type: 'number',
    label: 'Rent Increase Percentage (%)',
    placeholder: '5',
    required: false,
    group: 'financial',
  },
  {
    id: 'newSecurityDeposit',
    type: 'number',
    label: 'Security Deposit ($)',
    placeholder: '1200',
    required: false,
    group: 'financial',
  },
  {
    id: 'termsRemainSame',
    type: 'checkbox',
    label: 'All other terms remain the same as original lease',
    required: false,
    group: 'terms',
  },
  {
    id: 'modifiedTerms',
    type: 'textarea',
    label: 'Modified Terms',
    placeholder: 'Describe any changes to the original lease terms',
    required: false,
    group: 'terms',
  },
  {
    id: 'additionalTerms',
    type: 'textarea',
    label: 'Additional Terms',
    placeholder: 'Any new terms or conditions',
    required: false,
    group: 'terms',
  },
];
