// src/lib/documents/us/construction-contract/questions.ts
import type { FormQuestion } from '@/types/documents';

export const constructionContractQuestions: FormQuestion[] = [
  {
    id: 'ownerName',
    type: 'text',
    label: 'Owner Name',
    placeholder: 'Enter property owner name',
    required: true,
    group: 'owner',
  },
  {
    id: 'ownerAddress',
    type: 'text',
    label: 'Owner Address',
    placeholder: 'Enter complete owner address',
    required: true,
    group: 'owner',
  },
  {
    id: 'ownerPhone',
    type: 'text',
    label: 'Owner Phone',
    placeholder: 'Enter phone number',
    required: true,
    group: 'owner',
  },
  {
    id: 'ownerEmail',
    type: 'email',
    label: 'Owner Email',
    placeholder: 'Enter email address',
    required: false,
    group: 'owner',
  },
  {
    id: 'contractorName',
    type: 'text',
    label: 'Contractor Name',
    placeholder: 'Enter contractor/company name',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorAddress',
    type: 'text',
    label: 'Contractor Address',
    placeholder: 'Enter complete contractor address',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorPhone',
    type: 'text',
    label: 'Contractor Phone',
    placeholder: 'Enter phone number',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorEmail',
    type: 'email',
    label: 'Contractor Email',
    placeholder: 'Enter email address',
    required: false,
    group: 'contractor',
  },
  {
    id: 'contractorLicense',
    type: 'text',
    label: 'Contractor License Number',
    placeholder: 'Enter contractor license number',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorBond',
    type: 'text',
    label: 'Contractor Bond Number',
    placeholder: 'Enter bond number if applicable',
    required: false,
    group: 'contractor',
  },
  {
    id: 'hasArchitect',
    type: 'checkbox',
    label: 'Project involves architect/engineer',
    required: false,
    group: 'architect',
  },
  {
    id: 'architectName',
    type: 'text',
    label: 'Architect Name',
    placeholder: 'Enter architect/engineer name',
    required: false,
    group: 'architect',
    dependsOn: 'hasArchitect',
  },
  {
    id: 'architectAddress',
    type: 'text',
    label: 'Architect Address',
    placeholder: 'Enter architect address',
    required: false,
    group: 'architect',
    dependsOn: 'hasArchitect',
  },
  {
    id: 'projectName',
    type: 'text',
    label: 'Project Name',
    placeholder: 'Enter project name/title',
    required: true,
    group: 'project',
  },
  {
    id: 'projectAddress',
    type: 'text',
    label: 'Project Address',
    placeholder: 'Where construction will take place',
    required: true,
    group: 'project',
  },
  {
    id: 'projectDescription',
    type: 'textarea',
    label: 'Project Description',
    placeholder: 'Detailed description of construction work',
    required: true,
    group: 'project',
  },
  {
    id: 'projectType',
    type: 'select',
    label: 'Project Type',
    options: [
      { value: 'residential-new', label: 'New Residential Construction' },
      {
        value: 'residential-addition',
        label: 'Residential Addition/Renovation',
      },
      { value: 'commercial-new', label: 'New Commercial Construction' },
      { value: 'commercial-renovation', label: 'Commercial Renovation' },
      { value: 'industrial', label: 'Industrial Construction' },
      { value: 'infrastructure', label: 'Infrastructure Project' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'project',
  },
  {
    id: 'plansAndSpecifications',
    type: 'checkbox',
    label: 'Plans and specifications attached',
    required: false,
    group: 'documents',
  },
  {
    id: 'technicalSpecifications',
    type: 'textarea',
    label: 'Technical Specifications',
    placeholder: 'Detailed technical requirements',
    required: false,
    group: 'documents',
  },
  {
    id: 'contractDate',
    type: 'date',
    label: 'Contract Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'commencementDate',
    type: 'date',
    label: 'Work Commencement Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'substantialCompletionDate',
    type: 'date',
    label: 'Substantial Completion Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'finalCompletionDate',
    type: 'date',
    label: 'Final Completion Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'contractPriceType',
    type: 'select',
    label: 'Contract Price Type',
    options: [
      { value: 'lump-sum', label: 'Lump Sum' },
      { value: 'cost-plus-fee', label: 'Cost Plus Fixed Fee' },
      { value: 'cost-plus-percentage', label: 'Cost Plus Percentage' },
      { value: 'unit-price', label: 'Unit Price' },
      { value: 'guaranteed-maximum', label: 'Guaranteed Maximum Price' },
    ],
    required: true,
    group: 'pricing',
  },
  {
    id: 'contractPrice',
    type: 'text',
    label: 'Contract Price',
    placeholder: 'Enter total contract amount',
    required: true,
    group: 'pricing',
  },
  {
    id: 'contingencyAmount',
    type: 'text',
    label: 'Contingency Amount',
    placeholder: 'Amount set aside for contingencies',
    required: false,
    group: 'pricing',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'monthly-progress', label: 'Monthly Progress Payments' },
      { value: 'milestone-based', label: 'Milestone-Based Payments' },
      { value: 'percentage-completion', label: 'Percentage of Completion' },
      { value: 'custom', label: 'Custom Schedule' },
    ],
    required: true,
    group: 'payment',
  },
  {
    id: 'retainagePercentage',
    type: 'text',
    label: 'Retainage Percentage',
    placeholder: 'e.g., 10%',
    required: false,
    group: 'payment',
  },
  {
    id: 'performanceBondRequired',
    type: 'checkbox',
    label: 'Require performance bond',
    required: false,
    group: 'bonds',
  },
  {
    id: 'performanceBondAmount',
    type: 'text',
    label: 'Performance Bond Amount',
    placeholder: 'Bond amount or percentage',
    required: false,
    group: 'bonds',
    dependsOn: 'performanceBondRequired',
  },
  {
    id: 'paymentBondRequired',
    type: 'checkbox',
    label: 'Require payment bond',
    required: false,
    group: 'bonds',
  },
  {
    id: 'paymentBondAmount',
    type: 'text',
    label: 'Payment Bond Amount',
    placeholder: 'Bond amount or percentage',
    required: false,
    group: 'bonds',
    dependsOn: 'paymentBondRequired',
  },
  {
    id: 'generalLiabilityInsurance',
    type: 'text',
    label: 'General Liability Insurance Amount',
    placeholder: 'Minimum coverage amount',
    required: true,
    group: 'insurance',
  },
  {
    id: 'workersCompensationInsurance',
    type: 'checkbox',
    label: 'Require workers compensation insurance',
    required: false,
    group: 'insurance',
  },
  {
    id: 'builderRiskInsurance',
    type: 'checkbox',
    label: "Require builder's risk insurance",
    required: false,
    group: 'insurance',
  },
  {
    id: 'permitsAndLicenses',
    type: 'select',
    label: 'Permits and Licenses Responsibility',
    options: [
      { value: 'owner-responsibility', label: 'Owner Responsible' },
      { value: 'contractor-responsibility', label: 'Contractor Responsible' },
      { value: 'shared-responsibility', label: 'Shared Responsibility' },
    ],
    required: true,
    group: 'permits',
  },
  {
    id: 'permitCosts',
    type: 'select',
    label: 'Permit Costs',
    options: [
      { value: 'owner-pays', label: 'Owner Pays' },
      { value: 'contractor-pays', label: 'Contractor Pays' },
      { value: 'included-in-price', label: 'Included in Contract Price' },
    ],
    required: true,
    group: 'permits',
  },
  {
    id: 'buildingCodeCompliance',
    type: 'checkbox',
    label: 'Work must comply with building codes',
    required: false,
    group: 'permits',
  },
  {
    id: 'workScope',
    type: 'textarea',
    label: 'Work Scope',
    placeholder: 'Detailed scope of work to be performed',
    required: true,
    group: 'scope',
  },
  {
    id: 'qualityStandards',
    type: 'textarea',
    label: 'Quality Standards',
    placeholder: 'Quality standards and requirements',
    required: false,
    group: 'scope',
  },
  {
    id: 'materialStandards',
    type: 'textarea',
    label: 'Material Standards',
    placeholder: 'Material specifications and standards',
    required: false,
    group: 'scope',
  },
  {
    id: 'timeExtensionClauses',
    type: 'checkbox',
    label: 'Include time extension clauses',
    required: false,
    group: 'time',
  },
  {
    id: 'liquidatedDamages',
    type: 'checkbox',
    label: 'Include liquidated damages for delays',
    required: false,
    group: 'time',
  },
  {
    id: 'liquidatedDamagesAmount',
    type: 'text',
    label: 'Liquidated Damages Amount',
    placeholder: 'Daily amount for delays',
    required: false,
    group: 'time',
    dependsOn: 'liquidatedDamages',
  },
  {
    id: 'changeOrderProcedures',
    type: 'checkbox',
    label: 'Include change order procedures',
    required: false,
    group: 'changes',
  },
  {
    id: 'changeOrderApproval',
    type: 'select',
    label: 'Change Order Approval Authority',
    options: [
      { value: 'written-only', label: 'Written Approval Only' },
      { value: 'architect-approval', label: 'Architect Approval' },
      { value: 'owner-approval', label: 'Owner Approval' },
    ],
    required: false,
    group: 'changes',
    dependsOn: 'changeOrderProcedures',
  },
  {
    id: 'markupOnChanges',
    type: 'text',
    label: 'Markup on Change Orders',
    placeholder: 'e.g., 15% markup',
    required: false,
    group: 'changes',
  },
  {
    id: 'subcontractorApproval',
    type: 'checkbox',
    label: 'Require owner approval of subcontractors',
    required: false,
    group: 'subcontractors',
  },
  {
    id: 'subcontractorInsurance',
    type: 'checkbox',
    label: 'Require subcontractor insurance',
    required: false,
    group: 'subcontractors',
  },
  {
    id: 'safetyProgram',
    type: 'checkbox',
    label: 'Require safety program',
    required: false,
    group: 'safety',
  },
  {
    id: 'oshaCompliance',
    type: 'checkbox',
    label: 'Require OSHA compliance',
    required: false,
    group: 'safety',
  },
  {
    id: 'safetyOfficer',
    type: 'checkbox',
    label: 'Require on-site safety officer',
    required: false,
    group: 'safety',
  },
  {
    id: 'environmentalCompliance',
    type: 'checkbox',
    label: 'Include environmental compliance requirements',
    required: false,
    group: 'environmental',
  },
  {
    id: 'hazardousMaterialsHandling',
    type: 'checkbox',
    label: 'Address hazardous materials handling',
    required: false,
    group: 'environmental',
  },
  {
    id: 'constructionWarranty',
    type: 'checkbox',
    label: 'Include construction warranty',
    required: false,
    group: 'warranty',
  },
  {
    id: 'warrantyPeriod',
    type: 'text',
    label: 'Warranty Period',
    placeholder: 'e.g., 1 year, 2 years',
    required: false,
    group: 'warranty',
    dependsOn: 'constructionWarranty',
  },
  {
    id: 'materialWarranties',
    type: 'checkbox',
    label: 'Transfer material warranties to owner',
    required: false,
    group: 'warranty',
  },
  {
    id: 'punchListProcedures',
    type: 'checkbox',
    label: 'Include punch list procedures',
    required: false,
    group: 'completion',
  },
  {
    id: 'certificateOfOccupancy',
    type: 'checkbox',
    label: 'Require certificate of occupancy',
    required: false,
    group: 'completion',
  },
  {
    id: 'finalInspection',
    type: 'checkbox',
    label: 'Require final inspection',
    required: false,
    group: 'completion',
  },
  {
    id: 'superintendentRequired',
    type: 'checkbox',
    label: 'Require on-site superintendent',
    required: false,
    group: 'administration',
  },
  {
    id: 'progressReporting',
    type: 'checkbox',
    label: 'Require progress reporting',
    required: false,
    group: 'administration',
  },
  {
    id: 'meetingSchedule',
    type: 'text',
    label: 'Meeting Schedule',
    placeholder: 'e.g., Weekly progress meetings',
    required: false,
    group: 'administration',
  },
  {
    id: 'disputeResolutionMethod',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'negotiation', label: 'Negotiation' },
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'litigation', label: 'Court Litigation' },
    ],
    required: true,
    group: 'disputes',
  },
  {
    id: 'attorneyFees',
    type: 'checkbox',
    label: 'Include attorney fees clause',
    required: false,
    group: 'disputes',
  },
  {
    id: 'terminationForConvenience',
    type: 'checkbox',
    label: 'Allow termination for convenience',
    required: false,
    group: 'termination',
  },
  {
    id: 'terminationForCause',
    type: 'checkbox',
    label: 'Allow termination for cause',
    required: false,
    group: 'termination',
  },
  {
    id: 'terminationNotice',
    type: 'text',
    label: 'Termination Notice Period',
    placeholder: 'e.g., 30 days written notice',
    required: false,
    group: 'termination',
  },
  {
    id: 'lienWaivers',
    type: 'checkbox',
    label: 'Require lien waivers',
    required: false,
    group: 'liens',
  },
  {
    id: 'progressLienWaivers',
    type: 'checkbox',
    label: 'Progress lien waivers with payments',
    required: false,
    group: 'liens',
    dependsOn: 'lienWaivers',
  },
  {
    id: 'finalLienWaiver',
    type: 'checkbox',
    label: 'Final lien waiver with final payment',
    required: false,
    group: 'liens',
    dependsOn: 'lienWaivers',
  },
  {
    id: 'contractorIndemnifiesOwner',
    type: 'checkbox',
    label: 'Contractor indemnifies owner',
    required: false,
    group: 'indemnification',
  },
  {
    id: 'forceMajeureClause',
    type: 'checkbox',
    label: 'Include force majeure clause',
    required: false,
    group: 'force-majeure',
  },
  {
    id: 'assignmentRights',
    type: 'checkbox',
    label: 'Allow assignment of contract',
    required: false,
    group: 'miscellaneous',
  },
  {
    id: 'requireOwnerSignature',
    type: 'checkbox',
    label: 'Require owner signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireContractorSignature',
    type: 'checkbox',
    label: 'Require contractor signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireArchitectSignature',
    type: 'checkbox',
    label: 'Require architect signature',
    required: false,
    group: 'signatures',
    dependsOn: 'hasArchitect',
  },
];
