// src/lib/documents/us/farm-lease-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const farmLeaseAgreementQuestions: FormQuestion[] = [
  {
    id: 'landlordName',
    type: 'text',
    label: 'Landlord Name',
    placeholder: 'Enter landowner name',
    required: true,
    group: 'landlord',
  },
  {
    id: 'tenantName',
    type: 'text',
    label: 'Tenant Name',
    placeholder: 'Enter farmer/tenant name',
    required: true,
    group: 'tenant',
  },
  {
    id: 'farmDescription',
    type: 'textarea',
    label: 'Farm Description',
    placeholder: 'Describe the farm property',
    required: false,
    group: 'property',
  },
  {
    id: 'totalAcres',
    type: 'text',
    label: 'Total Acres',
    placeholder: 'Enter total farm acreage',
    required: false,
    group: 'property',
  },
  {
    id: 'tillableAcres',
    type: 'text',
    label: 'Tillable Acres',
    placeholder: 'Enter cultivatable acreage',
    required: false,
    group: 'property',
  },
  {
    id: 'leaseType',
    type: 'select',
    label: 'Lease Type',
    options: [
      { value: 'cash-rent', label: 'Cash Rent' },
      { value: 'crop-share', label: 'Crop Share' },
      { value: 'cash-plus-crop', label: 'Cash Plus Crop Share' },
      { value: 'flexible-cash', label: 'Flexible Cash Rent' },
    ],
    required: false,
    group: 'lease-terms',
  },
  {
    id: 'annualRent',
    type: 'text',
    label: 'Annual Rent',
    placeholder: 'Enter yearly rent amount',
    required: false,
    group: 'lease-terms',
  },
  {
    id: 'cropSharePercentage',
    type: 'text',
    label: 'Crop Share Percentage',
    placeholder: 'Enter landlord share percentage',
    required: false,
    group: 'lease-terms',
  },
  {
    id: 'primaryUse',
    type: 'select',
    label: 'Primary Farm Use',
    options: [
      { value: 'crop-production', label: 'Crop Production' },
      { value: 'livestock', label: 'Livestock' },
      { value: 'mixed-farming', label: 'Mixed Farming' },
      { value: 'organic-farming', label: 'Organic Farming' },
      { value: 'specialty-crops', label: 'Specialty Crops' },
    ],
    required: false,
    group: 'farming',
  },
  {
    id: 'cropTypes',
    type: 'multi-select',
    label: 'Crop Types',
    options: [
      { value: 'corn', label: 'Corn' },
      { value: 'soybeans', label: 'Soybeans' },
      { value: 'wheat', label: 'Wheat' },
      { value: 'cotton', label: 'Cotton' },
      { value: 'rice', label: 'Rice' },
      { value: 'vegetables', label: 'Vegetables' },
      { value: 'fruits', label: 'Fruits' },
      { value: 'hay', label: 'Hay' },
      { value: 'pasture', label: 'Pasture' },
    ],
    required: false,
    group: 'farming',
  },
  {
    id: 'dwellingIncluded',
    type: 'boolean',
    label: 'Farm dwelling included?',
    required: false,
    group: 'buildings',
  },
  {
    id: 'irrigationSystems',
    type: 'boolean',
    label: 'Irrigation systems included?',
    required: false,
    group: 'equipment',
  },
  {
    id: 'conservationPlan',
    type: 'boolean',
    label: 'Conservation plan required?',
    required: false,
    group: 'conservation',
  },
  {
    id: 'organicCertification',
    type: 'boolean',
    label: 'Organic certification required?',
    required: false,
    group: 'farming',
  },
  {
    id: 'liabilityAmount',
    type: 'text',
    label: 'Required Insurance Amount',
    placeholder: 'Enter minimum insurance coverage',
    required: false,
    group: 'insurance',
  },
];
