import { usStates } from '@/lib/usStates';
import type { Question } from '@/types/documents';

export const debtSettlementAgreementQuestions: Question[] = [
  { id: 'date', label: 'Agreement Date', type: 'date', required: true },
  { id: 'creditorName', label: 'Creditor Name', type: 'text', required: true },
  {
    id: 'creditorAddress',
    label: 'Creditor Address',
    type: 'text',
    required: true,
    placeholder: 'Street, City, State, ZIP',
  },
  { id: 'debtorName', label: 'Debtor Name', type: 'text', required: true },
  {
    id: 'debtorAddress',
    label: 'Debtor Address',
    type: 'text',
    required: true,
    placeholder: 'Street, City, State, ZIP',
  },
  {
    id: 'originalDebtAmount',
    label: 'Original Debt Amount',
    type: 'number',
    required: true,
    placeholder: 'e.g., 15000',
  },
  {
    id: 'settlementAmount',
    label: 'Settlement Amount',
    type: 'number',
    required: true,
    placeholder: 'e.g., 8000',
  },
  {
    id: 'accountNumber',
    label: 'Account Number',
    type: 'text',
    required: true,
    placeholder: 'Original account or reference number',
  },
  {
    id: 'settlementType',
    label: 'Settlement Type',
    type: 'select',
    required: true,
    options: [
      { value: 'Lump Sum', label: 'Lump Sum Payment' },
      { value: 'Payment Plan', label: 'Payment Plan' },
    ],
  },
  {
    id: 'paymentAmount',
    label: 'Payment Amount',
    type: 'number',
    required: true,
    placeholder: 'Amount per payment or lump sum',
  },
  {
    id: 'paymentDate',
    label: 'First Payment Date',
    type: 'date',
    required: true,
  },
  {
    id: 'numberOfPayments',
    label: 'Number of Payments',
    type: 'number',
    required: false,
    tooltip: 'Required for payment plans',
  },
  {
    id: 'paymentFrequency',
    label: 'Payment Frequency',
    type: 'select',
    required: false,
    options: [
      { value: 'Monthly', label: 'Monthly' },
      { value: 'Bi-weekly', label: 'Bi-weekly' },
      { value: 'Weekly', label: 'Weekly' },
    ],
    tooltip: 'Required for payment plans',
  },
  {
    id: 'finalPaymentDate',
    label: 'Final Payment Date',
    type: 'date',
    required: false,
    tooltip: 'Required for payment plans',
  },
  {
    id: 'governingLaw',
    label: 'Governing Law',
    type: 'select',
    required: true,
    options: usStates.map((s) => ({ value: s.value, label: s.label })),
  },
  {
    id: 'creditReportingClause',
    label: 'Include Credit Reporting Clause',
    type: 'boolean',
    required: true,
    tooltip: 'Whether to include agreement on credit reporting',
  },
  {
    id: 'releaseTerm',
    label: 'Release Terms',
    type: 'select',
    required: true,
    options: [
      { value: 'Upon Final Payment', label: 'Upon Final Payment' },
      { value: 'Upon First Payment', label: 'Upon First Payment' },
      { value: 'Immediate', label: 'Immediate' },
    ],
  },
  {
    id: 'defaultConsequences',
    label: 'Default Consequences',
    type: 'textarea',
    required: true,
    placeholder: 'What happens if debtor defaults on this agreement...',
  },
  {
    id: 'witnessRequired',
    label: 'Witness Required',
    type: 'boolean',
    required: false,
    tooltip: 'Whether witness signatures are required',
  },
];
