// src/lib/documents/us/advance-directive-revocation/questions.ts
import type { Question } from '@/types/documents';

export const questions: Question[] = [
  // Section 1: Principal Information
  {
    id: 'principalName',
    type: 'text',
    label: 'Your Full Legal Name',
    required: true,
    section: 'Principal Information',
    placeholder: 'Enter your full legal name',
    description:
      'You are the person who created the original advance directive.',
  },
  {
    id: 'principalAddress',
    type: 'text',
    label: 'Your Street Address',
    required: true,
    section: 'Principal Information',
    placeholder: 'Enter your street address',
  },
  {
    id: 'principalCity',
    type: 'text',
    label: 'Your City',
    required: true,
    section: 'Principal Information',
    placeholder: 'Enter your city',
  },
  {
    id: 'principalState',
    type: 'select',
    label: 'Your State',
    required: true,
    section: 'Principal Information',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
  },
  {
    id: 'principalZip',
    type: 'text',
    label: 'Your ZIP Code',
    required: true,
    section: 'Principal Information',
    placeholder: 'Enter your ZIP code',
  },
  {
    id: 'principalPhone',
    type: 'text',
    label: 'Your Phone Number',
    required: true,
    section: 'Principal Information',
    placeholder: 'Enter your phone number',
  },
  {
    id: 'principalDateOfBirth',
    type: 'date',
    label: 'Your Date of Birth',
    required: true,
    section: 'Principal Information',
  },

  // Section 2: Original Advance Directive Information
  {
    id: 'originalDirectiveDate',
    type: 'date',
    label: 'Date of Original Advance Directive',
    required: true,
    section: 'Original Advance Directive',
    description: 'The date when you signed the original advance directive.',
  },
  {
    id: 'originalDirectiveLocation',
    type: 'text',
    label: 'Where was the Original Directive Signed?',
    required: false,
    section: 'Original Advance Directive',
    placeholder: 'e.g., City, State OR Attorney office, Hospital',
    description: 'Location where the original advance directive was executed.',
  },
  {
    id: 'originalNotaryName',
    type: 'text',
    label: 'Original Notary Public Name',
    required: false,
    section: 'Original Advance Directive',
    placeholder: 'Enter notary name (if known)',
  },
  {
    id: 'originalWitnessNames',
    type: 'text',
    label: 'Original Witness Names',
    required: false,
    section: 'Original Advance Directive',
    placeholder: 'Enter witness names separated by commas',
  },

  // Section 3: Previous Health Care Agent
  {
    id: 'previousAgentName',
    type: 'text',
    label: 'Previous Health Care Agent Name',
    required: false,
    section: 'Previous Health Care Agent',
    placeholder: 'Enter the name of your previous health care agent',
  },
  {
    id: 'previousAgentAddress',
    type: 'text',
    label: 'Previous Agent Address',
    required: false,
    section: 'Previous Health Care Agent',
    placeholder: 'Enter previous agent address',
  },
  {
    id: 'previousAgentPhone',
    type: 'text',
    label: 'Previous Agent Phone Number',
    required: false,
    section: 'Previous Health Care Agent',
    placeholder: 'Enter previous agent phone number',
  },
  {
    id: 'previousAgentRelationship',
    type: 'text',
    label: 'Previous Agent Relationship to You',
    required: false,
    section: 'Previous Health Care Agent',
    placeholder: 'e.g., Spouse, Child, Sibling, Friend',
  },

  // Section 4: Previous Alternate Agent
  {
    id: 'hadAlternateAgent',
    type: 'radio',
    label: 'Did you have an alternate health care agent?',
    required: true,
    section: 'Previous Alternate Agent',
    options: [
      { value: 'true', label: 'Yes, I had an alternate agent' },
      { value: 'false', label: 'No, I did not have an alternate agent' },
    ],
  },
  {
    id: 'previousAlternateAgentName',
    type: 'text',
    label: 'Previous Alternate Agent Name',
    required: false,
    section: 'Previous Alternate Agent',
    placeholder: 'Enter the name of your previous alternate agent',
    condition: { field: 'hadAlternateAgent', value: 'true' },
  },
  {
    id: 'previousAlternateAgentAddress',
    type: 'text',
    label: 'Previous Alternate Agent Address',
    required: false,
    section: 'Previous Alternate Agent',
    placeholder: 'Enter previous alternate agent address',
    condition: { field: 'hadAlternateAgent', value: 'true' },
  },
  {
    id: 'previousAlternateAgentPhone',
    type: 'text',
    label: 'Previous Alternate Agent Phone Number',
    required: false,
    section: 'Previous Alternate Agent',
    placeholder: 'Enter previous alternate agent phone number',
    condition: { field: 'hadAlternateAgent', value: 'true' },
  },

  // Section 5: Revocation Details
  {
    id: 'revocationType',
    type: 'radio',
    label: 'Type of Revocation',
    required: true,
    section: 'Revocation Details',
    options: [
      {
        value: 'complete',
        label:
          'Complete revocation - I want to revoke my entire advance directive',
      },
      {
        value: 'partial',
        label: 'Partial revocation - I want to revoke only certain provisions',
      },
      {
        value: 'replacement',
        label: 'Replacement - I am creating a new advance directive',
      },
    ],
  },
  {
    id: 'revocationReason',
    type: 'textarea',
    label: 'Reason for Revocation',
    required: true,
    section: 'Revocation Details',
    placeholder: 'Explain why you are revoking your advance directive...',
    description:
      'Provide a clear explanation for why you are revoking the directive.',
  },
  {
    id: 'specificProvisionsRevoked',
    type: 'textarea',
    label: 'Specific Provisions Being Revoked',
    required: false,
    section: 'Revocation Details',
    placeholder: 'Describe the specific provisions you are revoking...',
    condition: { field: 'revocationType', value: 'partial' },
    description:
      'For partial revocation, specify exactly which provisions are being revoked.',
  },

  // Section 6: Mental Capacity Declaration
  {
    id: 'mentalCapacityConfirmation',
    type: 'radio',
    label: 'Mental Capacity Confirmation',
    required: true,
    section: 'Mental Capacity',
    options: [
      {
        value: 'true',
        label:
          'I confirm that I am of sound mind and capable of making this decision',
      },
      { value: 'false', label: 'I have concerns about my mental capacity' },
    ],
    description: 'You must be mentally capable to revoke an advance directive.',
  },
  {
    id: 'capacityWitnessName',
    type: 'text',
    label: 'Witness to Mental Capacity',
    required: false,
    section: 'Mental Capacity',
    placeholder: 'Enter name of person who can attest to your mental capacity',
    description: 'Optional: Someone who can verify your mental capacity.',
  },
  {
    id: 'capacityWitnessAddress',
    type: 'text',
    label: 'Mental Capacity Witness Address',
    required: false,
    section: 'Mental Capacity',
    placeholder: 'Enter witness address',
    condition: { field: 'capacityWitnessName', value: '!empty' },
  },

  // Section 7: Notification of Agents
  {
    id: 'agentNotified',
    type: 'radio',
    label: 'Have you notified your health care agent of this revocation?',
    required: true,
    section: 'Agent Notification',
    options: [
      { value: 'true', label: 'Yes, I have notified my health care agent' },
      {
        value: 'false',
        label: 'No, I have not yet notified my health care agent',
      },
    ],
  },
  {
    id: 'agentNotificationDate',
    type: 'date',
    label: 'Date Agent was Notified',
    required: false,
    section: 'Agent Notification',
    condition: { field: 'agentNotified', value: 'true' },
  },
  {
    id: 'agentNotificationMethod',
    type: 'text',
    label: 'Method of Notification',
    required: false,
    section: 'Agent Notification',
    placeholder: 'e.g., In person, Phone call, Certified mail, Email',
    condition: { field: 'agentNotified', value: 'true' },
  },
  {
    id: 'alternateAgentNotified',
    type: 'radio',
    label: 'Have you notified your alternate health care agent (if any)?',
    required: false,
    section: 'Agent Notification',
    options: [
      { value: 'true', label: 'Yes, I have notified my alternate agent' },
      { value: 'false', label: 'No, I have not notified my alternate agent' },
    ],
    condition: { field: 'hadAlternateAgent', value: 'true' },
  },
  {
    id: 'alternateAgentNotificationDate',
    type: 'date',
    label: 'Date Alternate Agent was Notified',
    required: false,
    section: 'Agent Notification',
    condition: { field: 'alternateAgentNotified', value: 'true' },
  },
  {
    id: 'alternateAgentNotificationMethod',
    type: 'text',
    label: 'Method of Notification for Alternate Agent',
    required: false,
    section: 'Agent Notification',
    placeholder: 'e.g., In person, Phone call, Certified mail, Email',
    condition: { field: 'alternateAgentNotified', value: 'true' },
  },

  // Section 8: Medical Provider Notification
  {
    id: 'physiciansNotified',
    type: 'radio',
    label: 'Do you need to notify any physicians or doctors?',
    required: true,
    section: 'Medical Provider Notification',
    options: [
      { value: 'true', label: 'Yes, I need to notify physicians' },
      { value: 'false', label: 'No, no physicians need to be notified' },
    ],
  },
  {
    id: 'physiciansList',
    type: 'array',
    label: 'Physicians to Notify',
    required: false,
    section: 'Medical Provider Notification',
    condition: { field: 'physiciansNotified', value: 'true' },
    description:
      'List all physicians who should be notified of this revocation.',
    arrayConfig: {
      minItems: 1,
      maxItems: 10,
      fields: [
        {
          id: 'name',
          type: 'text',
          label: 'Physician Name',
          required: true,
          placeholder: 'Enter physician full name',
        },
        {
          id: 'address',
          type: 'text',
          label: 'Office Address',
          required: true,
          placeholder: 'Enter physician office address',
        },
        {
          id: 'notificationDate',
          type: 'date',
          label: 'Date Notified',
          required: false,
        },
        {
          id: 'notificationMethod',
          type: 'text',
          label: 'Notification Method',
          required: false,
          placeholder: 'e.g., Certified mail, Phone, Fax',
        },
      ],
    },
  },

  // Section 9: Medical Facilities Notification
  {
    id: 'facilitiesNotified',
    type: 'radio',
    label: 'Do you need to notify any hospitals or medical facilities?',
    required: true,
    section: 'Medical Facilities Notification',
    options: [
      { value: 'true', label: 'Yes, I need to notify medical facilities' },
      {
        value: 'false',
        label: 'No, no medical facilities need to be notified',
      },
    ],
  },
  {
    id: 'facilitiesList',
    type: 'array',
    label: 'Medical Facilities to Notify',
    required: false,
    section: 'Medical Facilities Notification',
    condition: { field: 'facilitiesNotified', value: 'true' },
    description:
      'List all hospitals or medical facilities that should be notified.',
    arrayConfig: {
      minItems: 1,
      maxItems: 10,
      fields: [
        {
          id: 'name',
          type: 'text',
          label: 'Facility Name',
          required: true,
          placeholder: 'Enter hospital or facility name',
        },
        {
          id: 'address',
          type: 'text',
          label: 'Facility Address',
          required: true,
          placeholder: 'Enter facility address',
        },
        {
          id: 'notificationDate',
          type: 'date',
          label: 'Date Notified',
          required: false,
        },
        {
          id: 'notificationMethod',
          type: 'text',
          label: 'Notification Method',
          required: false,
          placeholder: 'e.g., Certified mail, Phone, Fax',
        },
      ],
    },
  },

  // Section 10: Family Notification
  {
    id: 'familyNotified',
    type: 'radio',
    label: 'Do you need to notify family members or others?',
    required: true,
    section: 'Family Notification',
    options: [
      {
        value: 'true',
        label: 'Yes, I need to notify family members or others',
      },
      { value: 'false', label: 'No, no family members need to be notified' },
    ],
  },
  {
    id: 'familyList',
    type: 'array',
    label: 'Family Members/Others to Notify',
    required: false,
    section: 'Family Notification',
    condition: { field: 'familyNotified', value: 'true' },
    description:
      'List family members or others who should be notified of this revocation.',
    arrayConfig: {
      minItems: 1,
      maxItems: 10,
      fields: [
        {
          id: 'name',
          type: 'text',
          label: 'Name',
          required: true,
          placeholder: 'Enter full name',
        },
        {
          id: 'relationship',
          type: 'text',
          label: 'Relationship',
          required: true,
          placeholder: 'e.g., Spouse, Child, Sibling, Friend',
        },
        {
          id: 'address',
          type: 'text',
          label: 'Address',
          required: false,
          placeholder: 'Enter address',
        },
        {
          id: 'phone',
          type: 'text',
          label: 'Phone Number',
          required: false,
          placeholder: 'Enter phone number',
        },
        {
          id: 'notificationDate',
          type: 'date',
          label: 'Date Notified',
          required: false,
        },
      ],
    },
  },

  // Section 11: Replacement Document
  {
    id: 'hasReplacementDirective',
    type: 'radio',
    label: 'Are you creating a new advance directive to replace this one?',
    required: true,
    section: 'Replacement Document',
    options: [
      { value: 'true', label: 'Yes, I am creating a new advance directive' },
      { value: 'false', label: 'No, I am not creating a replacement' },
    ],
  },
  {
    id: 'replacementDirectiveDate',
    type: 'date',
    label: 'Date of New Advance Directive',
    required: false,
    section: 'Replacement Document',
    condition: { field: 'hasReplacementDirective', value: 'true' },
  },
  {
    id: 'newAgentName',
    type: 'text',
    label: 'New Health Care Agent Name',
    required: false,
    section: 'Replacement Document',
    placeholder: 'Enter new agent name',
    condition: { field: 'hasReplacementDirective', value: 'true' },
  },
  {
    id: 'newAgentAddress',
    type: 'text',
    label: 'New Agent Address',
    required: false,
    section: 'Replacement Document',
    placeholder: 'Enter new agent address',
    condition: { field: 'hasReplacementDirective', value: 'true' },
  },
  {
    id: 'newAgentPhone',
    type: 'text',
    label: 'New Agent Phone Number',
    required: false,
    section: 'Replacement Document',
    placeholder: 'Enter new agent phone number',
    condition: { field: 'hasReplacementDirective', value: 'true' },
  },

  // Section 12: Destruction of Original Document
  {
    id: 'originalDocumentDestroyed',
    type: 'radio',
    label: 'Have you destroyed the original advance directive document?',
    required: true,
    section: 'Document Destruction',
    options: [
      { value: 'true', label: 'Yes, I have destroyed the original document' },
      { value: 'false', label: 'No, the original document still exists' },
    ],
  },
  {
    id: 'destructionDate',
    type: 'date',
    label: 'Date of Destruction',
    required: false,
    section: 'Document Destruction',
    condition: { field: 'originalDocumentDestroyed', value: 'true' },
  },
  {
    id: 'destructionWitness',
    type: 'text',
    label: 'Witness to Destruction',
    required: false,
    section: 'Document Destruction',
    placeholder: 'Enter name of witness to destruction',
    condition: { field: 'originalDocumentDestroyed', value: 'true' },
  },
  {
    id: 'copiesLocation',
    type: 'textarea',
    label: 'Location of Copies',
    required: false,
    section: 'Document Destruction',
    placeholder:
      'Describe where copies of the original directive exist and your plan for them...',
    description: 'List any copies that exist and how they will be handled.',
  },

  // Section 13: Additional Information
  {
    id: 'additionalInstructions',
    type: 'textarea',
    label: 'Additional Instructions',
    required: false,
    section: 'Additional Information',
    placeholder: 'Provide any additional instructions or information...',
    description:
      'Include any other relevant information about this revocation.',
  },
  {
    id: 'emergencyContact',
    type: 'text',
    label: 'Emergency Contact Name',
    required: false,
    section: 'Additional Information',
    placeholder: 'Enter emergency contact name',
  },
  {
    id: 'emergencyContactPhone',
    type: 'text',
    label: 'Emergency Contact Phone',
    required: false,
    section: 'Additional Information',
    placeholder: 'Enter emergency contact phone number',
    condition: { field: 'emergencyContact', value: '!empty' },
  },

  // Section 14: Witnesses
  {
    id: 'witness1Name',
    type: 'text',
    label: 'First Witness Full Name',
    required: true,
    section: 'Witnesses',
    placeholder: 'Enter first witness full name',
    description:
      'Witnesses should be disinterested parties who can verify your identity and mental capacity.',
  },
  {
    id: 'witness1Address',
    type: 'text',
    label: 'First Witness Address',
    required: true,
    section: 'Witnesses',
    placeholder: 'Enter first witness address',
  },
  {
    id: 'witness2Name',
    type: 'text',
    label: 'Second Witness Full Name',
    required: true,
    section: 'Witnesses',
    placeholder: 'Enter second witness full name',
  },
  {
    id: 'witness2Address',
    type: 'text',
    label: 'Second Witness Address',
    required: true,
    section: 'Witnesses',
    placeholder: 'Enter second witness address',
  },

  // Section 15: Legal Information
  {
    id: 'state',
    type: 'select',
    label: 'State Where This Revocation Will Be Used',
    required: true,
    section: 'Legal Information',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
    description: 'Select the state where this revocation will be effective.',
  },
  {
    id: 'county',
    type: 'text',
    label: 'County',
    required: true,
    section: 'Legal Information',
    placeholder: 'Enter the county name',
  },
  {
    id: 'dateCreated',
    type: 'date',
    label: 'Date of Creation',
    required: true,
    section: 'Legal Information',
    description: 'The date this revocation document is being created.',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Effective Date of Revocation',
    required: true,
    section: 'Legal Information',
    description:
      'The date when this revocation becomes effective (usually today).',
  },

  // Section 16: Notarization
  {
    id: 'notaryName',
    type: 'text',
    label: 'Notary Public Name',
    required: false,
    section: 'Notarization',
    placeholder: 'Enter notary public name',
    description: 'This will be filled when the document is notarized.',
  },
  {
    id: 'notaryCommissionExpires',
    type: 'date',
    label: 'Notary Commission Expires',
    required: false,
    section: 'Notarization',
    description: 'This will be filled when the document is notarized.',
  },
];
