// src/lib/documents/us/sublease-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const subleaseAgreementQuestions: FormQuestion[] = [
  {
    id: 'landlordName',
    type: 'text',
    label: 'Original Landlord Name',
    placeholder: 'Enter the original landlord\'s full name',
    required: true,
    group: 'landlord',
  },
  {
    id: 'landlordAddress',
    type: 'textarea',
    label: 'Landlord Address',
    placeholder: 'Enter the landlord\'s address',
    required: true,
    group: 'landlord',
  },
  {
    id: 'sublessorName',
    type: 'text',
    label: 'Sublessor Name (Original Tenant)',
    placeholder: 'Enter your full legal name',
    required: true,
    group: 'sublessor',
  },
  {
    id: 'sublessorAddress',
    type: 'textarea',
    label: 'Sublessor Address',
    placeholder: 'Enter your current address',
    required: true,
    group: 'sublessor',
  },
  {
    id: 'sublessorPhone',
    type: 'tel',
    label: 'Sublessor Phone',
    placeholder: '(555) 123-4567',
    required: false,
    group: 'sublessor',
  },
  {
    id: 'sublessorEmail',
    type: 'email',
    label: 'Sublessor Email',
    placeholder: 'your@email.com',
    required: false,
    group: 'sublessor',
  },
  {
    id: 'subtenantName',
    type: 'text',
    label: 'Subtenant Name',
    placeholder: 'Enter the subtenant\'s full legal name',
    required: true,
    group: 'subtenant',
  },
  {
    id: 'subtenantAddress',
    type: 'textarea',
    label: 'Subtenant Address',
    placeholder: 'Enter the subtenant\'s current address',
    required: true,
    group: 'subtenant',
  },
  {
    id: 'subtenantPhone',
    type: 'tel',
    label: 'Subtenant Phone',
    placeholder: '(555) 123-4567',
    required: false,
    group: 'subtenant',
  },
  {
    id: 'subtenantEmail',
    type: 'email',
    label: 'Subtenant Email',
    placeholder: 'subtenant@email.com',
    required: false,
    group: 'subtenant',
  },
  {
    id: 'propertyAddress',
    type: 'textarea',
    label: 'Property Address',
    placeholder: 'Enter the full address of the rental property',
    required: true,
    group: 'property',
  },
  {
    id: 'unitDescription',
    type: 'textarea',
    label: 'Unit Description',
    placeholder: 'Describe the unit (apartment number, specific areas, etc.)',
    required: false,
    group: 'property',
  },
  {
    id: 'originalLeaseDate',
    type: 'date',
    label: 'Original Lease Start Date',
    required: true,
    group: 'original-lease',
  },
  {
    id: 'originalLeaseEndDate',
    type: 'date',
    label: 'Original Lease End Date',
    required: true,
    group: 'original-lease',
  },
  {
    id: 'landlordConsent',
    type: 'checkbox',
    label: 'Landlord has given consent for subletting',
    required: false,
    group: 'original-lease',
  },
  {
    id: 'subleaseStartDate',
    type: 'date',
    label: 'Sublease Start Date',
    required: true,
    group: 'terms',
  },
  {
    id: 'subleaseEndDate',
    type: 'date',
    label: 'Sublease End Date',
    required: true,
    group: 'terms',
  },
  {
    id: 'monthlyRent',
    type: 'number',
    label: 'Monthly Rent ($)',
    placeholder: '1200',
    required: true,
    group: 'financial',
  },
  {
    id: 'securityDeposit',
    type: 'number',
    label: 'Security Deposit ($)',
    placeholder: '1200',
    required: true,
    group: 'financial',
  },
  {
    id: 'rentDueDate',
    type: 'number',
    label: 'Rent Due Date (Day of Month)',
    placeholder: '1',
    required: true,
    min: 1,
    max: 31,
    group: 'financial',
  },
  {
    id: 'utilitiesIncluded',
    type: 'checkbox',
    label: 'Utilities Included in Rent',
    required: false,
    group: 'financial',
  },
  {
    id: 'utilitiesDescription',
    type: 'textarea',
    label: 'Utilities Details',
    placeholder: 'Specify which utilities are included',
    required: false,
    group: 'financial',
    dependsOn: 'utilitiesIncluded',
  },
  {
    id: 'maintenanceResponsibility',
    type: 'select',
    label: 'Maintenance Responsibility',
    options: [
      { value: 'subtenant', label: 'Subtenant' },
      { value: 'sublessor', label: 'Sublessor' },
      { value: 'shared', label: 'Shared' },
    ],
    required: true,
    group: 'responsibilities',
  },
  {
    id: 'repairResponsibility',
    type: 'select',
    label: 'Repair Responsibility',
    options: [
      { value: 'subtenant', label: 'Subtenant' },
      { value: 'sublessor', label: 'Sublessor' },
      { value: 'shared', label: 'Shared' },
    ],
    required: true,
    group: 'responsibilities',
  },
  {
    id: 'furnishedStatus',
    type: 'select',
    label: 'Furnished Status',
    options: [
      { value: 'furnished', label: 'Fully Furnished' },
      { value: 'unfurnished', label: 'Unfurnished' },
      { value: 'partially-furnished', label: 'Partially Furnished' },
    ],
    required: true,
    group: 'property-details',
  },
  {
    id: 'smokingAllowed',
    type: 'checkbox',
    label: 'Smoking Allowed',
    required: false,
    group: 'rules',
  },
  {
    id: 'petsAllowed',
    type: 'checkbox',
    label: 'Pets Allowed',
    required: false,
    group: 'rules',
  },
  {
    id: 'sublettingAllowed',
    type: 'checkbox',
    label: 'Further Subletting Allowed',
    required: false,
    group: 'rules',
  },
  {
    id: 'parkingIncluded',
    type: 'checkbox',
    label: 'Parking Included',
    required: false,
    group: 'additional',
  },
  {
    id: 'additionalTerms',
    type: 'textarea',
    label: 'Additional Terms',
    placeholder: 'Any additional terms or conditions',
    required: false,
    group: 'additional',
  },
];