import type { Question } from '@/types/documents';

export const achAuthorizationFormQuestions: Question[] = [
  { id: 'date', label: 'Authorization Date', type: 'date', required: true },
  { id: 'customerName', label: 'Customer Name', type: 'text', required: true },
  {
    id: 'customerAddress',
    label: 'Customer Address',
    type: 'text',
    required: true,
    placeholder: 'Street, City, State, ZIP',
  },
  {
    id: 'customerPhone',
    label: 'Customer Phone',
    type: 'text',
    required: true,
    placeholder: '(555) 123-4567',
  },
  {
    id: 'customerEmail',
    label: 'Customer Email',
    type: 'email',
    required: false,
    placeholder: 'customer@example.com',
  },
  { id: 'companyName', label: 'Company Name', type: 'text', required: true },
  {
    id: 'companyAddress',
    label: 'Company Address',
    type: 'text',
    required: true,
    placeholder: 'Street, City, State, ZIP',
  },
  { id: 'bankName', label: 'Bank Name', type: 'text', required: true },
  {
    id: 'bankAddress',
    label: 'Bank Address',
    type: 'text',
    required: true,
    placeholder: 'Street, City, State, ZIP',
  },
  {
    id: 'accountHolderName',
    label: 'Account Holder Name',
    type: 'text',
    required: true,
    placeholder: 'Name on bank account',
  },
  {
    id: 'routingNumber',
    label: 'Bank Routing Number',
    type: 'text',
    required: true,
    placeholder: '9-digit routing number',
  },
  {
    id: 'accountNumber',
    label: 'Account Number',
    type: 'text',
    required: true,
    placeholder: 'Bank account number',
  },
  {
    id: 'accountType',
    label: 'Account Type',
    type: 'select',
    required: true,
    options: [
      { value: 'Checking', label: 'Checking' },
      { value: 'Savings', label: 'Savings' },
    ],
  },
  {
    id: 'transactionType',
    label: 'Transaction Type',
    type: 'select',
    required: true,
    options: [
      { value: 'One-time', label: 'One-time Payment' },
      { value: 'Recurring', label: 'Recurring Payments' },
    ],
  },
  {
    id: 'paymentAmount',
    label: 'Payment Amount',
    type: 'number',
    required: true,
    placeholder: 'Amount per payment',
  },
  {
    id: 'paymentFrequency',
    label: 'Payment Frequency',
    type: 'select',
    required: false,
    options: [
      { value: 'Weekly', label: 'Weekly' },
      { value: 'Bi-weekly', label: 'Bi-weekly' },
      { value: 'Monthly', label: 'Monthly' },
      { value: 'Quarterly', label: 'Quarterly' },
    ],
    tooltip: 'Required for recurring payments',
  },
  { id: 'firstPaymentDate', label: 'First Payment Date', type: 'date', required: true },
  {
    id: 'finalPaymentDate',
    label: 'Final Payment Date',
    type: 'date',
    required: false,
    tooltip: 'For recurring payments with end date',
  },
  {
    id: 'purposeOfPayment',
    label: 'Purpose of Payment',
    type: 'text',
    required: true,
    placeholder: 'What these payments are for',
  },
  {
    id: 'preNotificationRequired',
    label: 'Pre-notification Required',
    type: 'boolean',
    required: true,
    tooltip: 'Whether customer should be notified before each payment',
  },
  {
    id: 'notificationDays',
    label: 'Notification Days',
    type: 'number',
    required: false,
    tooltip: 'Days before payment to notify customer',
  },
  {
    id: 'revocationTerms',
    label: 'Revocation Terms',
    type: 'textarea',
    required: true,
    placeholder: 'How customer can revoke this authorization...',
  },
  {
    id: 'returnedPaymentFee',
    label: 'Returned Payment Fee ($)',
    type: 'number',
    required: false,
    tooltip: 'Fee charged for returned/failed payments',
  },
];
