// src/lib/documents/us/membership-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const membershipAgreementQuestions: FormQuestion[] = [
  {
    id: 'organizationName',
    type: 'text',
    label: 'Organization Name',
    placeholder: 'Enter organization name',
    required: true,
    group: 'organization',
  },
  {
    id: 'organizationType',
    type: 'select',
    label: 'Organization Type',
    options: [
      { value: 'gym', label: 'Gym/Fitness Center' },
      { value: 'club', label: 'Club' },
      { value: 'professional', label: 'Professional Association' },
      { value: 'social', label: 'Social Club' },
      { value: 'religious', label: 'Religious Organization' },
      { value: 'educational', label: 'Educational Institution' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
    group: 'organization',
  },
  {
    id: 'memberName',
    type: 'text',
    label: 'Member Name',
    placeholder: 'Enter member full name',
    required: true,
    group: 'member',
  },
  {
    id: 'memberEmail',
    type: 'email',
    label: 'Member Email',
    placeholder: 'Enter member email',
    required: false,
    group: 'member',
  },
  {
    id: 'membershipType',
    type: 'select',
    label: 'Membership Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'family', label: 'Family' },
      { value: 'corporate', label: 'Corporate' },
      { value: 'student', label: 'Student' },
      { value: 'senior', label: 'Senior' },
      { value: 'vip', label: 'VIP' },
    ],
    required: false,
    group: 'membership',
  },
  {
    id: 'membershipLevel',
    type: 'select',
    label: 'Membership Level',
    options: [
      { value: 'basic', label: 'Basic' },
      { value: 'standard', label: 'Standard' },
      { value: 'premium', label: 'Premium' },
      { value: 'platinum', label: 'Platinum' },
    ],
    required: false,
    group: 'membership',
  },
  {
    id: 'membershipStartDate',
    type: 'date',
    label: 'Membership Start Date',
    required: false,
    group: 'membership',
  },
  {
    id: 'membershipDuration',
    type: 'select',
    label: 'Membership Duration',
    options: [
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
      { value: 'semi-annual', label: 'Semi-Annual' },
      { value: 'annual', label: 'Annual' },
      { value: 'lifetime', label: 'Lifetime' },
    ],
    required: false,
    group: 'membership',
  },
  {
    id: 'accessPrivileges',
    type: 'textarea',
    label: 'Access Privileges',
    placeholder: 'Describe member access privileges',
    required: false,
    group: 'benefits',
  },
  {
    id: 'guestPrivileges',
    type: 'boolean',
    label: 'Guest privileges included?',
    required: false,
    group: 'benefits',
  },
  {
    id: 'membershipFee',
    type: 'text',
    label: 'Membership Fee',
    placeholder: 'Enter membership fee amount',
    required: false,
    group: 'fees',
  },
  {
    id: 'initiationFee',
    type: 'text',
    label: 'Initiation Fee',
    placeholder: 'Enter initiation fee (if any)',
    required: false,
    group: 'fees',
  },
  {
    id: 'paymentFrequency',
    type: 'select',
    label: 'Payment Frequency',
    options: [
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
      { value: 'semi-annual', label: 'Semi-Annual' },
      { value: 'annual', label: 'Annual' },
      { value: 'one-time', label: 'One-Time' },
    ],
    required: false,
    group: 'fees',
  },
  {
    id: 'paymentMethod',
    type: 'select',
    label: 'Payment Method',
    options: [
      { value: 'credit-card', label: 'Credit Card' },
      { value: 'bank-transfer', label: 'Bank Transfer' },
      { value: 'check', label: 'Check' },
      { value: 'cash', label: 'Cash' },
    ],
    required: false,
    group: 'fees',
  },
  {
    id: 'autoRenewal',
    type: 'boolean',
    label: 'Auto-renewal enabled?',
    required: false,
    group: 'fees',
  },
  {
    id: 'codeOfConduct',
    type: 'textarea',
    label: 'Code of Conduct',
    placeholder: 'Describe member code of conduct',
    required: false,
    group: 'rules',
  },
  {
    id: 'facilityHours',
    type: 'text',
    label: 'Facility Hours',
    placeholder: 'Enter facility operating hours',
    required: false,
    group: 'rules',
  },
  {
    id: 'cancellationNotice',
    type: 'text',
    label: 'Cancellation Notice Period',
    placeholder: 'Enter notice period (e.g., 30 days)',
    required: false,
    group: 'cancellation',
  },
  {
    id: 'freezeOption',
    type: 'boolean',
    label: 'Membership freeze option available?',
    required: false,
    group: 'cancellation',
  },
  {
    id: 'transferable',
    type: 'boolean',
    label: 'Membership transferable?',
    required: false,
    group: 'transfer',
  },
  {
    id: 'liabilityWaiver',
    type: 'boolean',
    label: 'Liability waiver required?',
    required: false,
    group: 'liability',
  },
  {
    id: 'personalTraining',
    type: 'boolean',
    label: 'Personal training included?',
    required: false,
    group: 'services',
  },
  {
    id: 'classesIncluded',
    type: 'boolean',
    label: 'Classes included?',
    required: false,
    group: 'services',
  },
  {
    id: 'parkingIncluded',
    type: 'boolean',
    label: 'Parking included?',
    required: false,
    group: 'services',
  },
  {
    id: 'communicationPreferences',
    type: 'select',
    label: 'Communication Preferences',
    options: [
      { value: 'email', label: 'Email' },
      { value: 'phone', label: 'Phone' },
      { value: 'mail', label: 'Mail' },
      { value: 'text', label: 'Text' },
    ],
    required: false,
    group: 'communication',
  },
  {
    id: 'photographyConsent',
    type: 'boolean',
    label: 'Photography consent?',
    required: false,
    group: 'consent',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'Enter governing law/state',
    required: false,
    group: 'legal',
  },
];
