import { usStates } from '@/lib/usStates';
import type { Question } from '@/types/documents';

export const promissoryNoteInstallmentPaymentsQuestions: Question[] = [
  { id: 'date', label: 'Date of Note', type: 'date', required: true },
  {
    id: 'placeOfExecution',
    label: 'Place of Execution',
    type: 'text',
    required: true,
    placeholder: 'City, State',
  },
  { id: 'lenderName', label: 'Lender Name', type: 'text', required: true },
  {
    id: 'lenderAddress',
    label: 'Lender Address',
    type: 'text',
    required: true,
    placeholder: 'Street, City, State, ZIP',
  },
  { id: 'borrowerName', label: 'Borrower Name', type: 'text', required: true },
  {
    id: 'borrowerAddress',
    label: 'Borrower Address',
    type: 'text',
    required: true,
    placeholder: 'Street, City, State, ZIP',
  },
  {
    id: 'principalAmount',
    label: 'Principal Amount',
    type: 'number',
    required: true,
    placeholder: 'e.g., 10000',
  },
  {
    id: 'interestRate',
    label: 'Interest Rate (%)',
    type: 'number',
    required: true,
    placeholder: 'e.g., 5',
  },
  {
    id: 'numberOfInstallments',
    label: 'Number of Installments',
    type: 'number',
    required: true,
    placeholder: 'e.g., 12',
  },
  {
    id: 'installmentAmount',
    label: 'Installment Amount',
    type: 'number',
    required: true,
    placeholder: 'e.g., 500',
  },
  {
    id: 'firstPaymentDate',
    label: 'First Payment Date',
    type: 'date',
    required: true,
  },
  {
    id: 'paymentFrequency',
    label: 'Payment Frequency',
    type: 'select',
    required: true,
    options: [
      { value: 'Monthly', label: 'Monthly' },
      { value: 'Bi-weekly', label: 'Bi-weekly' },
      { value: 'Weekly', label: 'Weekly' },
      { value: 'Quarterly', label: 'Quarterly' },
    ],
  },
  {
    id: 'finalPaymentDate',
    label: 'Final Payment Date',
    type: 'date',
    required: true,
  },
  {
    id: 'governingLaw',
    label: 'Governing Law',
    type: 'select',
    required: true,
    options: usStates.map((s) => ({ value: s.value, label: s.label })),
  },
  {
    id: 'lateFeeAmount',
    label: 'Late Fee Amount ($)',
    type: 'number',
    required: false,
    tooltip: 'Fixed dollar amount charged for late payments',
  },
  {
    id: 'gracePerod',
    label: 'Grace Period (Days)',
    type: 'number',
    required: false,
    tooltip: 'Days allowed before late fees apply',
  },
  {
    id: 'defaultInterestRate',
    label: 'Default Interest Rate (%)',
    type: 'number',
    required: false,
    tooltip: 'Higher interest rate applied after default',
  },
  {
    id: 'prepaymentPenalty',
    label: 'Prepayment Penalty',
    type: 'boolean',
    required: false,
    tooltip: 'Whether penalty applies for early payment',
  },
];
