import type { Question } from '@/types/documents';

export const debtValidationLetterQuestions: Question[] = [
  { id: 'date', label: 'Date of Letter', type: 'date', required: true },
  { id: 'debtorName', label: 'Your Name', type: 'text', required: true },
  {
    id: 'debtorAddress',
    label: 'Your Address',
    type: 'text',
    required: true,
    placeholder: 'Street, City, State, ZIP',
  },
  {
    id: 'collectorName',
    label: 'Debt Collector Name',
    type: 'text',
    required: true,
  },
  {
    id: 'collectorAddress',
    label: 'Debt Collector Address',
    type: 'text',
    required: true,
    placeholder: 'Street, City, State, ZIP',
  },
  {
    id: 'accountNumber',
    label: 'Account Number',
    type: 'text',
    required: true,
    placeholder: 'Account or reference number from collector',
  },
  {
    id: 'claimedDebtAmount',
    label: 'Claimed Debt Amount',
    type: 'number',
    required: true,
    placeholder: 'e.g., 2500',
  },
  {
    id: 'originalCreditorName',
    label: 'Original Creditor Name',
    type: 'text',
    required: true,
    placeholder: 'Name of original creditor if known',
  },
  {
    id: 'dateOfLastPayment',
    label: 'Date of Last Payment',
    type: 'date',
    required: false,
    tooltip: 'Last payment made on this account, if known',
  },
  {
    id: 'requestType',
    label: 'Request Type',
    type: 'select',
    required: true,
    options: [
      { value: 'Validation', label: 'Debt Validation' },
      { value: 'Verification', label: 'Debt Verification' },
      { value: 'Both', label: 'Both Validation and Verification' },
    ],
  },
  {
    id: 'disputeReason',
    label: 'Reason for Dispute',
    type: 'select',
    required: false,
    options: [
      { value: 'Not My Debt', label: 'This is not my debt' },
      { value: 'Amount Incorrect', label: 'Amount is incorrect' },
      {
        value: 'Statute of Limitations',
        label: 'Statute of limitations expired',
      },
      { value: 'Already Paid', label: 'Debt already paid' },
      { value: 'Identity Theft', label: 'Result of identity theft' },
      { value: 'Other', label: 'Other reason' },
    ],
  },
  {
    id: 'requestCeaseContact',
    label: 'Request Cease Communication',
    type: 'boolean',
    required: true,
    tooltip: 'Request that collector stop contacting you',
  },
  {
    id: 'requestWrittenCommunication',
    label: 'Request Written Communication Only',
    type: 'boolean',
    required: true,
    tooltip: 'Request all future communication be in writing only',
  },
  {
    id: 'customMessage',
    label: 'Additional Message',
    type: 'textarea',
    required: false,
    placeholder: 'Any additional information or requests...',
  },
];
