// src/lib/documents/us/arbitration-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const arbitrationAgreementQuestions: FormQuestion[] = [
  {
    id: 'party1Name',
    type: 'text',
    label: 'Party 1 Name',
    placeholder: 'Enter first party name',
    required: true,
    group: 'parties',
  },
  {
    id: 'party1Address',
    type: 'text',
    label: 'Party 1 Address',
    placeholder: 'Enter complete address',
    required: true,
    group: 'parties',
  },
  {
    id: 'party1Type',
    type: 'select',
    label: 'Party 1 Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'business', label: 'Business' },
      { value: 'organization', label: 'Organization' },
    ],
    required: true,
    group: 'parties',
  },
  {
    id: 'party2Name',
    type: 'text',
    label: 'Party 2 Name',
    placeholder: 'Enter second party name',
    required: true,
    group: 'parties',
  },
  {
    id: 'party2Address',
    type: 'text',
    label: 'Party 2 Address',
    placeholder: 'Enter complete address',
    required: true,
    group: 'parties',
  },
  {
    id: 'party2Type',
    type: 'select',
    label: 'Party 2 Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'business', label: 'Business' },
      { value: 'organization', label: 'Organization' },
    ],
    required: true,
    group: 'parties',
  },
  {
    id: 'agreementType',
    type: 'select',
    label: 'Agreement Type',
    options: [
      { value: 'standalone', label: 'Standalone Agreement' },
      { value: 'part-of-contract', label: 'Part of Another Contract' },
      { value: 'employment', label: 'Employment Context' },
      { value: 'consumer', label: 'Consumer Context' },
      { value: 'commercial', label: 'Commercial Context' },
    ],
    required: true,
    group: 'context',
  },
  {
    id: 'underlyingAgreement',
    type: 'text',
    label: 'Underlying Agreement',
    placeholder: 'Name of main contract or agreement',
    required: false,
    group: 'context',
    dependsOn: 'agreementType',
  },
  {
    id: 'relationshipType',
    type: 'text',
    label: 'Relationship Type',
    placeholder: 'e.g., Employment, Service Agreement, Partnership',
    required: false,
    group: 'context',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Effective Date',
    required: true,
    group: 'context',
  },
  {
    id: 'disputeScope',
    type: 'select',
    label: 'Scope of Disputes',
    options: [
      { value: 'all-disputes', label: 'All Disputes' },
      { value: 'contract-disputes', label: 'Contract Disputes Only' },
      { value: 'specific-disputes', label: 'Specific Types of Disputes' },
      {
        value: 'excluding-certain-disputes',
        label: 'All Except Certain Disputes',
      },
    ],
    required: true,
    group: 'scope',
  },
  {
    id: 'specificDisputes',
    type: 'multiselect',
    label: 'Specific Disputes to Include',
    options: [
      { value: 'breach-of-contract', label: 'Breach of Contract' },
      { value: 'payment-disputes', label: 'Payment Disputes' },
      { value: 'performance-disputes', label: 'Performance Disputes' },
      { value: 'termination-disputes', label: 'Termination Disputes' },
      { value: 'intellectual-property', label: 'Intellectual Property' },
      { value: 'confidentiality', label: 'Confidentiality' },
    ],
    required: false,
    group: 'scope',
    dependsOn: 'disputeScope',
  },
  {
    id: 'excludedDisputes',
    type: 'multiselect',
    label: 'Disputes to Exclude',
    options: [
      { value: 'injunctive-relief', label: 'Injunctive Relief' },
      { value: 'intellectual-property', label: 'Intellectual Property' },
      { value: 'real-estate', label: 'Real Estate' },
      { value: 'criminal-matters', label: 'Criminal Matters' },
      { value: 'regulatory-violations', label: 'Regulatory Violations' },
    ],
    required: false,
    group: 'scope',
  },
  {
    id: 'futureDisputes',
    type: 'checkbox',
    label: 'Cover future disputes',
    required: false,
    group: 'scope',
  },
  {
    id: 'existingDisputes',
    type: 'checkbox',
    label: 'Cover existing disputes',
    required: false,
    group: 'scope',
  },
  {
    id: 'contractClaims',
    type: 'checkbox',
    label: 'Include contract claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'tortClaims',
    type: 'checkbox',
    label: 'Include tort claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'statutoryClaims',
    type: 'checkbox',
    label: 'Include statutory claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'employmentClaims',
    type: 'checkbox',
    label: 'Include employment claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'discriminationClaims',
    type: 'checkbox',
    label: 'Include discrimination claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'intellectualPropertyClaims',
    type: 'checkbox',
    label: 'Include intellectual property claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'consumerProtectionClaims',
    type: 'checkbox',
    label: 'Include consumer protection claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'arbitrationRules',
    type: 'select',
    label: 'Arbitration Rules',
    options: [
      { value: 'aaa-commercial', label: 'AAA Commercial Rules' },
      { value: 'aaa-consumer', label: 'AAA Consumer Rules' },
      { value: 'aaa-employment', label: 'AAA Employment Rules' },
      { value: 'jams', label: 'JAMS Rules' },
      { value: 'cpradr', label: 'CPR Rules' },
      { value: 'custom', label: 'Custom Rules' },
      { value: 'state-rules', label: 'State Court Rules' },
    ],
    required: true,
    group: 'rules',
  },
  {
    id: 'customRules',
    type: 'textarea',
    label: 'Custom Rules Description',
    placeholder: 'Describe the custom arbitration rules',
    required: false,
    group: 'rules',
    dependsOn: 'arbitrationRules',
  },
  {
    id: 'administrationOrganization',
    type: 'text',
    label: 'Administering Organization',
    placeholder: 'e.g., American Arbitration Association',
    required: false,
    group: 'rules',
  },
  {
    id: 'numberOfArbitrators',
    type: 'select',
    label: 'Number of Arbitrators',
    options: [
      { value: '1', label: 'Single Arbitrator' },
      { value: '3', label: 'Three Arbitrators' },
      { value: 'panel', label: 'Panel (More than 3)' },
    ],
    required: true,
    group: 'arbitrators',
  },
  {
    id: 'arbitratorQualifications',
    type: 'text',
    label: 'Arbitrator Qualifications',
    placeholder: 'Required qualifications or experience',
    required: false,
    group: 'arbitrators',
  },
  {
    id: 'arbitratorSelection',
    type: 'select',
    label: 'Arbitrator Selection Method',
    options: [
      { value: 'mutual-agreement', label: 'Mutual Agreement' },
      { value: 'organization-appointment', label: 'Organization Appointment' },
      { value: 'striking-method', label: 'Striking Method' },
      { value: 'rotation-list', label: 'Rotation List' },
    ],
    required: true,
    group: 'arbitrators',
  },
  {
    id: 'challengeProcess',
    type: 'checkbox',
    label: 'Allow arbitrator challenges',
    required: false,
    group: 'arbitrators',
  },
  {
    id: 'neutralArbitrator',
    type: 'checkbox',
    label: 'Require neutral arbitrator',
    required: false,
    group: 'arbitrators',
  },
  {
    id: 'arbitrationLocation',
    type: 'text',
    label: 'Arbitration Location',
    placeholder: 'City and state where arbitration will occur',
    required: true,
    group: 'location',
  },
  {
    id: 'venueSelection',
    type: 'select',
    label: 'Venue Selection Method',
    options: [
      { value: 'fixed-location', label: 'Fixed Location' },
      { value: 'convenient-location', label: 'Convenient Location' },
      { value: 'party-agreement', label: 'By Party Agreement' },
      { value: 'arbitrator-decision', label: 'Arbitrator Decision' },
    ],
    required: true,
    group: 'location',
  },
  {
    id: 'virtualHearings',
    type: 'checkbox',
    label: 'Allow virtual hearings',
    required: false,
    group: 'location',
  },
  {
    id: 'documentOnlyArbitration',
    type: 'checkbox',
    label: 'Allow document-only arbitration',
    required: false,
    group: 'location',
  },
  {
    id: 'arbitrationLanguage',
    type: 'text',
    label: 'Arbitration Language',
    placeholder: 'Language for proceedings',
    required: false,
    group: 'procedures',
  },
  {
    id: 'discoveryAllowed',
    type: 'checkbox',
    label: 'Allow discovery',
    required: false,
    group: 'procedures',
  },
  {
    id: 'discoveryLimitations',
    type: 'text',
    label: 'Discovery Limitations',
    placeholder: 'Describe any limitations on discovery',
    required: false,
    group: 'procedures',
    dependsOn: 'discoveryAllowed',
  },
  {
    id: 'depositionsAllowed',
    type: 'checkbox',
    label: 'Allow depositions',
    required: false,
    group: 'procedures',
  },
  {
    id: 'documentProduction',
    type: 'checkbox',
    label: 'Allow document production',
    required: false,
    group: 'procedures',
  },
  {
    id: 'oralHearing',
    type: 'checkbox',
    label: 'Include oral hearing',
    required: false,
    group: 'hearing',
  },
  {
    id: 'hearingDuration',
    type: 'text',
    label: 'Hearing Duration Limit',
    placeholder: 'Maximum hearing duration',
    required: false,
    group: 'hearing',
  },
  {
    id: 'witnessTestimony',
    type: 'checkbox',
    label: 'Allow witness testimony',
    required: false,
    group: 'hearing',
  },
  {
    id: 'expertWitnesses',
    type: 'checkbox',
    label: 'Allow expert witnesses',
    required: false,
    group: 'hearing',
  },
  {
    id: 'recordKeeping',
    type: 'checkbox',
    label: 'Require record keeping',
    required: false,
    group: 'hearing',
  },
  {
    id: 'costAllocation',
    type: 'select',
    label: 'Cost Allocation',
    options: [
      { value: 'each-pays-own', label: 'Each Party Pays Own Costs' },
      { value: 'loser-pays', label: 'Losing Party Pays All' },
      { value: 'proportional', label: 'Proportional Allocation' },
      { value: 'arbitrator-decision', label: 'Arbitrator Decides' },
    ],
    required: true,
    group: 'costs',
  },
  {
    id: 'arbitratorFees',
    type: 'select',
    label: 'Arbitrator Fees',
    options: [
      { value: 'shared-equally', label: 'Shared Equally' },
      { value: 'initiating-party', label: 'Initiating Party Pays' },
      { value: 'losing-party', label: 'Losing Party Pays' },
      { value: 'proportional', label: 'Proportional' },
    ],
    required: true,
    group: 'costs',
  },
  {
    id: 'administrativeFees',
    type: 'select',
    label: 'Administrative Fees',
    options: [
      { value: 'shared-equally', label: 'Shared Equally' },
      { value: 'initiating-party', label: 'Initiating Party Pays' },
      { value: 'losing-party', label: 'Losing Party Pays' },
      { value: 'proportional', label: 'Proportional' },
    ],
    required: true,
    group: 'costs',
  },
  {
    id: 'attorneyFees',
    type: 'select',
    label: 'Attorney Fees',
    options: [
      { value: 'each-pays-own', label: 'Each Pays Own' },
      { value: 'prevailing-party', label: 'Prevailing Party Recovery' },
      { value: 'arbitrator-decision', label: 'Arbitrator Decides' },
    ],
    required: true,
    group: 'costs',
  },
  {
    id: 'costAdvance',
    type: 'checkbox',
    label: 'Require cost advance',
    required: false,
    group: 'costs',
  },
  {
    id: 'initiationDeadline',
    type: 'text',
    label: 'Initiation Deadline',
    placeholder: 'Time limit to start arbitration',
    required: false,
    group: 'timing',
  },
  {
    id: 'responseDeadline',
    type: 'text',
    label: 'Response Deadline',
    placeholder: 'Time limit to respond',
    required: false,
    group: 'timing',
  },
  {
    id: 'completionDeadline',
    type: 'text',
    label: 'Completion Deadline',
    placeholder: 'Time limit to complete arbitration',
    required: false,
    group: 'timing',
  },
  {
    id: 'expeditedProcedures',
    type: 'checkbox',
    label: 'Allow expedited procedures',
    required: false,
    group: 'timing',
  },
  {
    id: 'emergencyArbitrator',
    type: 'checkbox',
    label: 'Allow emergency arbitrator',
    required: false,
    group: 'timing',
  },
  {
    id: 'awardType',
    type: 'select',
    label: 'Award Type',
    options: [
      { value: 'reasoned-award', label: 'Reasoned Award' },
      { value: 'standard-award', label: 'Standard Award' },
      { value: 'summary-award', label: 'Summary Award' },
    ],
    required: true,
    group: 'award',
  },
  {
    id: 'awardFinality',
    type: 'checkbox',
    label: 'Award is final and binding',
    required: false,
    group: 'award',
  },
  {
    id: 'appealRights',
    type: 'checkbox',
    label: 'Allow appeal rights',
    required: false,
    group: 'award',
  },
  {
    id: 'modificationRights',
    type: 'checkbox',
    label: 'Allow modification rights',
    required: false,
    group: 'award',
  },
  {
    id: 'monetaryDamages',
    type: 'checkbox',
    label: 'Allow monetary damages',
    required: false,
    group: 'remedies',
  },
  {
    id: 'equitableRelief',
    type: 'checkbox',
    label: 'Allow equitable relief',
    required: false,
    group: 'remedies',
  },
  {
    id: 'injunctiveRelief',
    type: 'checkbox',
    label: 'Allow injunctive relief',
    required: false,
    group: 'remedies',
  },
  {
    id: 'specificPerformance',
    type: 'checkbox',
    label: 'Allow specific performance',
    required: false,
    group: 'remedies',
  },
  {
    id: 'punitiveDamages',
    type: 'checkbox',
    label: 'Allow punitive damages',
    required: false,
    group: 'remedies',
  },
  {
    id: 'attorneyFeesRecovery',
    type: 'checkbox',
    label: 'Allow attorney fees recovery',
    required: false,
    group: 'remedies',
  },
  {
    id: 'confidentialityClause',
    type: 'checkbox',
    label: 'Include confidentiality clause',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'hearingConfidentiality',
    type: 'checkbox',
    label: 'Keep hearings confidential',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'awardConfidentiality',
    type: 'checkbox',
    label: 'Keep award confidential',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'documentConfidentiality',
    type: 'checkbox',
    label: 'Keep documents confidential',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'classActionWaiver',
    type: 'checkbox',
    label: 'Include class action waiver',
    required: false,
    group: 'class-actions',
  },
  {
    id: 'collectiveActionWaiver',
    type: 'checkbox',
    label: 'Include collective action waiver',
    required: false,
    group: 'class-actions',
  },
  {
    id: 'representativeActionWaiver',
    type: 'checkbox',
    label: 'Include representative action waiver',
    required: false,
    group: 'class-actions',
  },
  {
    id: 'consolidationAllowed',
    type: 'checkbox',
    label: 'Allow consolidation of claims',
    required: false,
    group: 'class-actions',
  },
  {
    id: 'smallClaimsException',
    type: 'checkbox',
    label: 'Include small claims exception',
    required: false,
    group: 'exceptions',
  },
  {
    id: 'smallClaimsLimit',
    type: 'text',
    label: 'Small Claims Limit',
    placeholder: 'Dollar amount for small claims',
    required: false,
    group: 'exceptions',
    dependsOn: 'smallClaimsException',
  },
  {
    id: 'emergencyReliefException',
    type: 'checkbox',
    label: 'Include emergency relief exception',
    required: false,
    group: 'exceptions',
  },
  {
    id: 'mandatoryMediation',
    type: 'checkbox',
    label: 'Require mediation first',
    required: false,
    group: 'pre-arbitration',
  },
  {
    id: 'goodFaithNegotiation',
    type: 'checkbox',
    label: 'Require good faith negotiation',
    required: false,
    group: 'pre-arbitration',
  },
  {
    id: 'noticeRequirement',
    type: 'checkbox',
    label: 'Require notice before arbitration',
    required: false,
    group: 'pre-arbitration',
  },
  {
    id: 'noticeMethod',
    type: 'text',
    label: 'Notice Method',
    placeholder: 'How notice must be given',
    required: false,
    group: 'pre-arbitration',
    dependsOn: 'noticeRequirement',
  },
  {
    id: 'noticePeriod',
    type: 'text',
    label: 'Notice Period',
    placeholder: 'How long before arbitration can start',
    required: false,
    group: 'pre-arbitration',
    dependsOn: 'noticeRequirement',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'e.g., State of California',
    required: false,
    group: 'legal',
  },
  {
    id: 'federalArbitrationAct',
    type: 'checkbox',
    label: 'Governed by Federal Arbitration Act',
    required: false,
    group: 'legal',
  },
  {
    id: 'stateArbitrationLaw',
    type: 'checkbox',
    label: 'Governed by state arbitration law',
    required: false,
    group: 'legal',
  },
  {
    id: 'separabilityClause',
    type: 'checkbox',
    label: 'Include separability clause',
    required: false,
    group: 'contract-terms',
  },
  {
    id: 'severabilityClause',
    type: 'checkbox',
    label: 'Include severability clause',
    required: false,
    group: 'contract-terms',
  },
  {
    id: 'entireAgreementClause',
    type: 'checkbox',
    label: 'Include entire agreement clause',
    required: false,
    group: 'contract-terms',
  },
  {
    id: 'requireBothSignatures',
    type: 'checkbox',
    label: 'Require both party signatures',
    required: false,
    group: 'signatures',
  },
  {
    id: 'witnessRequirement',
    type: 'checkbox',
    label: 'Require witness',
    required: false,
    group: 'signatures',
  },
  {
    id: 'notarizationRequirement',
    type: 'checkbox',
    label: 'Require notarization',
    required: false,
    group: 'signatures',
  },
  {
    id: 'electronicSignatureAccepted',
    type: 'checkbox',
    label: 'Accept electronic signatures',
    required: false,
    group: 'signatures',
  },
  {
    id: 'acknowledgmentOfUnderstanding',
    type: 'checkbox',
    label: 'Include acknowledgment of understanding',
    required: false,
    group: 'signatures',
  },
];
