// src/lib/documents/us/pet-custody-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const petCustodyAgreementQuestions: FormQuestion[] = [
  {
    id: 'partyAName',
    type: 'text',
    label: 'Party A Name',
    placeholder: 'Enter first party name',
    required: true,
    group: 'party-a',
  },
  {
    id: 'partyAAddress',
    type: 'text',
    label: 'Party A Address',
    placeholder: 'Enter complete address',
    required: true,
    group: 'party-a',
  },
  {
    id: 'partyAPhone',
    type: 'text',
    label: 'Party A Phone Number',
    placeholder: 'Enter phone number',
    required: false,
    group: 'party-a',
  },
  {
    id: 'partyBName',
    type: 'text',
    label: 'Party B Name',
    placeholder: 'Enter second party name',
    required: true,
    group: 'party-b',
  },
  {
    id: 'partyBAddress',
    type: 'text',
    label: 'Party B Address',
    placeholder: 'Enter complete address',
    required: true,
    group: 'party-b',
  },
  {
    id: 'partyBPhone',
    type: 'text',
    label: 'Party B Phone Number',
    placeholder: 'Enter phone number',
    required: false,
    group: 'party-b',
  },
  {
    id: 'agreementDate',
    type: 'date',
    label: 'Agreement Date',
    required: true,
    group: 'agreement-details',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Effective Date',
    required: true,
    group: 'agreement-details',
  },
  {
    id: 'petName',
    type: 'text',
    label: 'Pet Name',
    placeholder: 'Enter pet name',
    required: true,
    group: 'pet-info',
  },
  {
    id: 'petType',
    type: 'select',
    label: 'Pet Type',
    options: [
      { value: 'dog', label: 'Dog' },
      { value: 'cat', label: 'Cat' },
      { value: 'bird', label: 'Bird' },
      { value: 'fish', label: 'Fish' },
      { value: 'reptile', label: 'Reptile' },
      { value: 'small-mammal', label: 'Small Mammal' },
      { value: 'horse', label: 'Horse' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'pet-info',
  },
  {
    id: 'petBreed',
    type: 'text',
    label: 'Pet Breed',
    placeholder: 'Enter breed if known',
    required: false,
    group: 'pet-info',
  },
  {
    id: 'petAge',
    type: 'text',
    label: 'Pet Age',
    placeholder: 'e.g., 3 years old',
    required: false,
    group: 'pet-info',
  },
  {
    id: 'petGender',
    type: 'select',
    label: 'Pet Gender',
    options: [
      { value: 'male', label: 'Male' },
      { value: 'female', label: 'Female' },
      { value: 'neutered-male', label: 'Neutered Male' },
      { value: 'spayed-female', label: 'Spayed Female' },
    ],
    required: false,
    group: 'pet-info',
  },
  {
    id: 'petDescription',
    type: 'textarea',
    label: 'Pet Description',
    placeholder: 'Describe pet appearance, markings, etc.',
    required: false,
    group: 'pet-info',
  },
  {
    id: 'microchipNumber',
    type: 'text',
    label: 'Microchip Number',
    placeholder: 'Enter microchip ID if applicable',
    required: false,
    group: 'pet-info',
  },
  {
    id: 'hasMultiplePets',
    type: 'checkbox',
    label: 'Agreement covers multiple pets',
    required: false,
    group: 'pet-info',
  },
  {
    id: 'custodyType',
    type: 'select',
    label: 'Custody Arrangement Type',
    options: [
      { value: 'sole-custody', label: 'Sole Custody' },
      { value: 'joint-custody', label: 'Joint Custody' },
      { value: 'alternating-custody', label: 'Alternating Custody' },
      { value: 'visitation-schedule', label: 'Visitation Schedule' },
    ],
    required: true,
    group: 'custody',
  },
  {
    id: 'primaryCustodian',
    type: 'select',
    label: 'Primary Custodian (if applicable)',
    options: [
      { value: 'party-a', label: 'Party A' },
      { value: 'party-b', label: 'Party B' },
      { value: 'shared', label: 'Shared' },
    ],
    required: false,
    group: 'custody',
  },
  {
    id: 'weekdaySchedule',
    type: 'text',
    label: 'Weekday Schedule',
    placeholder: 'e.g., Monday-Wednesday with Party A',
    required: false,
    group: 'schedule',
  },
  {
    id: 'weekendSchedule',
    type: 'text',
    label: 'Weekend Schedule',
    placeholder: 'e.g., Alternating weekends',
    required: false,
    group: 'schedule',
  },
  {
    id: 'holidaySchedule',
    type: 'text',
    label: 'Holiday Schedule',
    placeholder: 'Describe holiday arrangements',
    required: false,
    group: 'schedule',
  },
  {
    id: 'pickupDropoffLocation',
    type: 'text',
    label: 'Pickup/Dropoff Location',
    placeholder: 'Where exchanges will occur',
    required: false,
    group: 'schedule',
  },
  {
    id: 'transportationResponsibility',
    type: 'select',
    label: 'Transportation Responsibility',
    options: [
      { value: 'party-a', label: 'Party A' },
      { value: 'party-b', label: 'Party B' },
      { value: 'alternating', label: 'Alternating' },
      { value: 'mutual', label: 'Mutual Agreement' },
    ],
    required: false,
    group: 'schedule',
  },
  {
    id: 'veterinaryCosts',
    type: 'select',
    label: 'Veterinary Costs Responsibility',
    options: [
      { value: 'party-a', label: 'Party A Pays' },
      { value: 'party-b', label: 'Party B Pays' },
      { value: 'shared', label: 'Shared 50/50' },
      { value: 'proportional', label: 'Proportional to Income' },
    ],
    required: true,
    group: 'financial',
  },
  {
    id: 'emergencyVetCosts',
    type: 'select',
    label: 'Emergency Veterinary Costs',
    options: [
      { value: 'party-a', label: 'Party A Pays' },
      { value: 'party-b', label: 'Party B Pays' },
      { value: 'shared', label: 'Shared 50/50' },
      { value: 'proportional', label: 'Proportional to Income' },
    ],
    required: true,
    group: 'financial',
  },
  {
    id: 'foodCosts',
    type: 'select',
    label: 'Food Costs Responsibility',
    options: [
      { value: 'party-a', label: 'Party A Pays' },
      { value: 'party-b', label: 'Party B Pays' },
      { value: 'shared', label: 'Shared 50/50' },
      { value: 'custodian-pays', label: 'Current Custodian Pays' },
    ],
    required: true,
    group: 'financial',
  },
  {
    id: 'groomingCosts',
    type: 'select',
    label: 'Grooming Costs Responsibility',
    options: [
      { value: 'party-a', label: 'Party A Pays' },
      { value: 'party-b', label: 'Party B Pays' },
      { value: 'shared', label: 'Shared 50/50' },
      { value: 'custodian-pays', label: 'Current Custodian Pays' },
    ],
    required: true,
    group: 'financial',
  },
  {
    id: 'primaryVeterinarian',
    type: 'text',
    label: 'Primary Veterinarian',
    placeholder: 'Name and practice of primary vet',
    required: false,
    group: 'veterinary-care',
  },
  {
    id: 'vetContactInfo',
    type: 'text',
    label: 'Veterinarian Contact Information',
    placeholder: 'Phone number and address',
    required: false,
    group: 'veterinary-care',
  },
  {
    id: 'medicalDecisionMaking',
    type: 'select',
    label: 'Medical Decision Making Authority',
    options: [
      { value: 'party-a', label: 'Party A' },
      { value: 'party-b', label: 'Party B' },
      { value: 'joint', label: 'Joint Decision' },
      { value: 'primary-custodian', label: 'Primary Custodian' },
    ],
    required: true,
    group: 'veterinary-care',
  },
  {
    id: 'petInsurance',
    type: 'checkbox',
    label: 'Pet has insurance coverage',
    required: false,
    group: 'insurance',
  },
  {
    id: 'insuranceProvider',
    type: 'text',
    label: 'Insurance Provider',
    placeholder: 'Name of pet insurance company',
    required: false,
    group: 'insurance',
    dependsOn: 'petInsurance',
  },
  {
    id: 'insuranceResponsibility',
    type: 'select',
    label: 'Insurance Premium Responsibility',
    options: [
      { value: 'party-a', label: 'Party A Pays' },
      { value: 'party-b', label: 'Party B Pays' },
      { value: 'shared', label: 'Shared 50/50' },
    ],
    required: false,
    group: 'insurance',
    dependsOn: 'petInsurance',
  },
  {
    id: 'housingRequirements',
    type: 'textarea',
    label: 'Housing Requirements',
    placeholder: 'Describe minimum housing standards',
    required: false,
    group: 'living-conditions',
  },
  {
    id: 'yardRequirements',
    type: 'text',
    label: 'Yard Requirements',
    placeholder: 'e.g., Fenced yard required',
    required: false,
    group: 'living-conditions',
  },
  {
    id: 'otherPetsAllowed',
    type: 'checkbox',
    label: 'Other pets allowed in household',
    required: false,
    group: 'living-conditions',
  },
  {
    id: 'smokingRestrictions',
    type: 'checkbox',
    label: 'No smoking around pet',
    required: false,
    group: 'living-conditions',
  },
  {
    id: 'travelNotification',
    type: 'checkbox',
    label: 'Require notification before travel with pet',
    required: false,
    group: 'travel',
  },
  {
    id: 'travelNotificationPeriod',
    type: 'text',
    label: 'Travel Notification Period',
    placeholder: 'e.g., 7 days advance notice',
    required: false,
    group: 'travel',
    dependsOn: 'travelNotification',
  },
  {
    id: 'relocationNotification',
    type: 'checkbox',
    label: 'Require notification before relocation',
    required: false,
    group: 'travel',
  },
  {
    id: 'communicationMethod',
    type: 'select',
    label: 'Primary Communication Method',
    options: [
      { value: 'phone', label: 'Phone' },
      { value: 'email', label: 'Email' },
      { value: 'text', label: 'Text Message' },
      { value: 'app', label: 'Mobile App' },
      { value: 'written', label: 'Written Communication' },
    ],
    required: false,
    group: 'communication',
  },
  {
    id: 'photoSharing',
    type: 'checkbox',
    label: 'Share photos and updates about pet',
    required: false,
    group: 'communication',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'court', label: 'Court Proceedings' },
    ],
    required: false,
    group: 'dispute-resolution',
  },
  {
    id: 'modificationClause',
    type: 'checkbox',
    label: 'Include modification clause',
    required: false,
    group: 'modification',
  },
  {
    id: 'emergencyProcedures',
    type: 'textarea',
    label: 'Emergency Procedures',
    placeholder: 'Describe procedures for pet emergencies',
    required: false,
    group: 'emergency',
  },
  {
    id: 'alternateCaregiver',
    type: 'text',
    label: 'Alternate Caregiver',
    placeholder: 'Backup caregiver if both parties unavailable',
    required: false,
    group: 'emergency',
  },
  {
    id: 'breedingRestrictions',
    type: 'checkbox',
    label: 'Restrict breeding activities',
    required: false,
    group: 'breeding',
  },
  {
    id: 'breedingConsent',
    type: 'checkbox',
    label: 'Require mutual consent for breeding',
    required: false,
    group: 'breeding',
  },
  {
    id: 'trainingRequirements',
    type: 'textarea',
    label: 'Training Requirements',
    placeholder: 'Describe any required training or behavior standards',
    required: false,
    group: 'training',
  },
  {
    id: 'licensingRequirements',
    type: 'checkbox',
    label: 'Maintain current pet licensing',
    required: false,
    group: 'legal-compliance',
  },
  {
    id: 'vaccinationRequirements',
    type: 'checkbox',
    label: 'Keep vaccinations current',
    required: false,
    group: 'legal-compliance',
  },
  {
    id: 'specificNeeds',
    type: 'textarea',
    label: 'Pet Specific Needs',
    placeholder: 'Describe any special care requirements',
    required: false,
    group: 'special-care',
  },
  {
    id: 'dietaryRestrictions',
    type: 'text',
    label: 'Dietary Restrictions',
    placeholder: 'Special diet requirements or restrictions',
    required: false,
    group: 'special-care',
  },
  {
    id: 'requirePartyASignature',
    type: 'checkbox',
    label: 'Require Party A signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requirePartyBSignature',
    type: 'checkbox',
    label: 'Require Party B signature',
    required: false,
    group: 'signatures',
  },
];