// src/lib/documents/us/tuition-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const tuitionAgreementQuestions: FormQuestion[] = [
  {
    id: 'institutionName',
    type: 'text',
    label: 'Institution Name',
    placeholder: 'Enter educational institution name',
    required: true,
    group: 'institution',
  },
  {
    id: 'institutionType',
    type: 'select',
    label: 'Institution Type',
    options: [
      { value: 'public', label: 'Public School' },
      { value: 'private', label: 'Private School' },
      { value: 'charter', label: 'Charter School' },
      { value: 'religious', label: 'Religious School' },
      { value: 'vocational', label: 'Vocational School' },
      { value: 'online', label: 'Online School' },
    ],
    required: false,
    group: 'institution',
  },
  {
    id: 'studentName',
    type: 'text',
    label: 'Student Name',
    placeholder: 'Enter student full name',
    required: true,
    group: 'student',
  },
  {
    id: 'studentEmail',
    type: 'email',
    label: 'Student Email',
    placeholder: 'Enter student email',
    required: false,
    group: 'student',
  },
  {
    id: 'studentId',
    type: 'text',
    label: 'Student ID',
    placeholder: 'Enter student ID number',
    required: false,
    group: 'student',
  },
  {
    id: 'parentGuardianName',
    type: 'text',
    label: 'Parent/Guardian Name',
    placeholder: 'Enter parent or guardian name',
    required: false,
    group: 'parent',
  },
  {
    id: 'financialResponsibility',
    type: 'select',
    label: 'Financial Responsibility',
    options: [
      { value: 'student', label: 'Student' },
      { value: 'parent', label: 'Parent' },
      { value: 'guardian', label: 'Guardian' },
      { value: 'sponsor', label: 'Sponsor' },
      { value: 'shared', label: 'Shared' },
    ],
    required: false,
    group: 'parent',
  },
  {
    id: 'programName',
    type: 'text',
    label: 'Program Name',
    placeholder: 'Enter academic program name',
    required: false,
    group: 'academic',
  },
  {
    id: 'gradeLevel',
    type: 'text',
    label: 'Grade Level',
    placeholder: 'Enter grade level or year',
    required: false,
    group: 'academic',
  },
  {
    id: 'academicYear',
    type: 'text',
    label: 'Academic Year',
    placeholder: 'Enter academic year (e.g., 2024-2025)',
    required: false,
    group: 'academic',
  },
  {
    id: 'enrollmentStatus',
    type: 'select',
    label: 'Enrollment Status',
    options: [
      { value: 'full-time', label: 'Full-Time' },
      { value: 'part-time', label: 'Part-Time' },
      { value: 'audit', label: 'Audit' },
    ],
    required: false,
    group: 'academic',
  },
  {
    id: 'tuitionAmount',
    type: 'text',
    label: 'Tuition Amount',
    placeholder: 'Enter tuition amount',
    required: false,
    group: 'fees',
  },
  {
    id: 'registrationFee',
    type: 'text',
    label: 'Registration Fee',
    placeholder: 'Enter registration fee',
    required: false,
    group: 'fees',
  },
  {
    id: 'totalAmount',
    type: 'text',
    label: 'Total Amount Due',
    placeholder: 'Enter total amount due',
    required: false,
    group: 'fees',
  },
  {
    id: 'paymentPlan',
    type: 'select',
    label: 'Payment Plan',
    options: [
      { value: 'full-payment', label: 'Full Payment' },
      { value: 'semester', label: 'Per Semester' },
      { value: 'quarterly', label: 'Quarterly' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'custom', label: 'Custom Plan' },
    ],
    required: false,
    group: 'payment',
  },
  {
    id: 'paymentDueDate',
    type: 'date',
    label: 'Payment Due Date',
    required: false,
    group: 'payment',
  },
  {
    id: 'lateFee',
    type: 'text',
    label: 'Late Fee',
    placeholder: 'Enter late fee amount',
    required: false,
    group: 'payment',
  },
  {
    id: 'financialAidApplied',
    type: 'boolean',
    label: 'Financial aid applied?',
    required: false,
    group: 'aid',
  },
  {
    id: 'scholarshipAmount',
    type: 'text',
    label: 'Scholarship Amount',
    placeholder: 'Enter scholarship amount',
    required: false,
    group: 'aid',
  },
  {
    id: 'withdrawalDeadline',
    type: 'date',
    label: 'Withdrawal Deadline',
    required: false,
    group: 'refund',
  },
  {
    id: 'proRataRefund',
    type: 'boolean',
    label: 'Pro-rata refund available?',
    required: false,
    group: 'refund',
  },
  {
    id: 'mealPlan',
    type: 'boolean',
    label: 'Meal plan included?',
    required: false,
    group: 'services',
  },
  {
    id: 'housing',
    type: 'boolean',
    label: 'Housing included?',
    required: false,
    group: 'services',
  },
  {
    id: 'parking',
    type: 'boolean',
    label: 'Parking included?',
    required: false,
    group: 'services',
  },
  {
    id: 'booksIncluded',
    type: 'boolean',
    label: 'Books included?',
    required: false,
    group: 'supplies',
  },
  {
    id: 'healthInsuranceRequired',
    type: 'boolean',
    label: 'Health insurance required?',
    required: false,
    group: 'insurance',
  },
  {
    id: 'transcriptHold',
    type: 'boolean',
    label: 'Hold transcripts for non-payment?',
    required: false,
    group: 'default',
  },
  {
    id: 'statementDelivery',
    type: 'select',
    label: 'Statement Delivery Method',
    options: [
      { value: 'mail', label: 'Mail' },
      { value: 'email', label: 'Email' },
      { value: 'online-portal', label: 'Online Portal' },
    ],
    required: false,
    group: 'communication',
  },
  {
    id: 'internationalStudent',
    type: 'boolean',
    label: 'International student?',
    required: false,
    group: 'special',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'Enter governing law/state',
    required: false,
    group: 'legal',
  },
];
