// src/lib/documents/us/mediation-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const mediationAgreementQuestions: FormQuestion[] = [
  {
    id: 'party1Name',
    type: 'text',
    label: 'Party 1 Name',
    placeholder: 'Enter first party name',
    required: true,
    group: 'parties',
  },
  {
    id: 'party1Address',
    type: 'text',
    label: 'Party 1 Address',
    placeholder: 'Enter complete address',
    required: true,
    group: 'parties',
  },
  {
    id: 'party1Type',
    type: 'select',
    label: 'Party 1 Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'business', label: 'Business' },
      { value: 'organization', label: 'Organization' },
    ],
    required: true,
    group: 'parties',
  },
  {
    id: 'party2Name',
    type: 'text',
    label: 'Party 2 Name',
    placeholder: 'Enter second party name',
    required: true,
    group: 'parties',
  },
  {
    id: 'party2Address',
    type: 'text',
    label: 'Party 2 Address',
    placeholder: 'Enter complete address',
    required: true,
    group: 'parties',
  },
  {
    id: 'party2Type',
    type: 'select',
    label: 'Party 2 Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'business', label: 'Business' },
      { value: 'organization', label: 'Organization' },
    ],
    required: true,
    group: 'parties',
  },
  {
    id: 'additionalParties',
    type: 'multiselect',
    label: 'Additional Parties',
    options: [
      { value: 'party3', label: 'Third Party' },
      { value: 'party4', label: 'Fourth Party' },
      { value: 'party5', label: 'Fifth Party' },
    ],
    required: false,
    group: 'parties',
  },
  {
    id: 'disputeDescription',
    type: 'textarea',
    label: 'Dispute Description',
    placeholder: 'Describe the nature of the dispute',
    required: true,
    group: 'dispute',
  },
  {
    id: 'disputeType',
    type: 'select',
    label: 'Dispute Type',
    options: [
      { value: 'contract', label: 'Contract Dispute' },
      { value: 'employment', label: 'Employment Dispute' },
      { value: 'family', label: 'Family Dispute' },
      { value: 'commercial', label: 'Commercial Dispute' },
      { value: 'personal-injury', label: 'Personal Injury' },
      { value: 'property', label: 'Property Dispute' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'dispute',
  },
  {
    id: 'disputeValue',
    type: 'text',
    label: 'Dispute Value',
    placeholder: 'Estimated monetary value in dispute',
    required: false,
    group: 'dispute',
  },
  {
    id: 'disputeDate',
    type: 'text',
    label: 'Dispute Origin Date',
    placeholder: 'When did the dispute arise?',
    required: false,
    group: 'dispute',
  },
  {
    id: 'relationshipContext',
    type: 'text',
    label: 'Relationship Context',
    placeholder: 'Nature of relationship between parties',
    required: false,
    group: 'dispute',
  },
  {
    id: 'mediationType',
    type: 'select',
    label: 'Mediation Type',
    options: [
      { value: 'voluntary', label: 'Voluntary Mediation' },
      { value: 'court-ordered', label: 'Court-Ordered Mediation' },
      { value: 'contractual-requirement', label: 'Contractual Requirement' },
      { value: 'pre-litigation', label: 'Pre-Litigation Mediation' },
    ],
    required: true,
    group: 'process',
  },
  {
    id: 'mediationGoal',
    type: 'select',
    label: 'Mediation Goal',
    options: [
      { value: 'settlement', label: 'Reach Settlement' },
      { value: 'communication', label: 'Improve Communication' },
      { value: 'relationship-repair', label: 'Repair Relationship' },
      { value: 'understanding', label: 'Better Understanding' },
    ],
    required: true,
    group: 'process',
  },
  {
    id: 'mediationFormat',
    type: 'select',
    label: 'Mediation Format',
    options: [
      { value: 'in-person', label: 'In-Person' },
      { value: 'virtual', label: 'Virtual/Online' },
      { value: 'hybrid', label: 'Hybrid (In-Person & Virtual)' },
      { value: 'shuttle', label: 'Shuttle Mediation' },
    ],
    required: true,
    group: 'process',
  },
  {
    id: 'sessionStructure',
    type: 'select',
    label: 'Session Structure',
    options: [
      { value: 'single-session', label: 'Single Session' },
      { value: 'multiple-sessions', label: 'Multiple Sessions' },
      { value: 'open-ended', label: 'Open-Ended' },
    ],
    required: true,
    group: 'process',
  },
  {
    id: 'mediatorSelection',
    type: 'select',
    label: 'Mediator Selection Method',
    options: [
      { value: 'mutual-agreement', label: 'Mutual Agreement' },
      { value: 'organization-appointment', label: 'Organization Appointment' },
      { value: 'rotation-list', label: 'Rotation List' },
      { value: 'named-mediator', label: 'Named Mediator' },
    ],
    required: true,
    group: 'mediator',
  },
  {
    id: 'namedMediator',
    type: 'text',
    label: 'Named Mediator',
    placeholder: 'Enter mediator name if pre-selected',
    required: false,
    group: 'mediator',
    dependsOn: 'mediatorSelection',
  },
  {
    id: 'mediatorQualifications',
    type: 'text',
    label: 'Mediator Qualifications',
    placeholder: 'Required qualifications or certifications',
    required: false,
    group: 'mediator',
  },
  {
    id: 'mediatorExperience',
    type: 'text',
    label: 'Mediator Experience',
    placeholder: 'Required experience level',
    required: false,
    group: 'mediator',
  },
  {
    id: 'mediatorSpecialization',
    type: 'text',
    label: 'Mediator Specialization',
    placeholder: 'Area of specialization needed',
    required: false,
    group: 'mediator',
  },
  {
    id: 'mediationOrganization',
    type: 'text',
    label: 'Mediation Organization',
    placeholder: 'e.g., American Arbitration Association',
    required: false,
    group: 'organization',
  },
  {
    id: 'organizationRules',
    type: 'checkbox',
    label: 'Follow organization rules',
    required: false,
    group: 'organization',
  },
  {
    id: 'administrationFees',
    type: 'checkbox',
    label: 'Organization charges administration fees',
    required: false,
    group: 'organization',
  },
  {
    id: 'organizationFacilities',
    type: 'checkbox',
    label: 'Use organization facilities',
    required: false,
    group: 'organization',
  },
  {
    id: 'mediationLocation',
    type: 'text',
    label: 'Mediation Location',
    placeholder: 'Where mediation will take place',
    required: true,
    group: 'location',
  },
  {
    id: 'locationSelection',
    type: 'select',
    label: 'Location Selection Method',
    options: [
      { value: 'fixed-location', label: 'Fixed Location' },
      { value: 'neutral-location', label: 'Neutral Location' },
      { value: 'rotating-location', label: 'Rotating Location' },
      { value: 'virtual-only', label: 'Virtual Only' },
    ],
    required: true,
    group: 'location',
  },
  {
    id: 'schedulingMethod',
    type: 'select',
    label: 'Scheduling Method',
    options: [
      { value: 'mutual-agreement', label: 'Mutual Agreement' },
      {
        value: 'mediator-availability',
        label: 'Based on Mediator Availability',
      },
      { value: 'organization-scheduling', label: 'Organization Scheduling' },
    ],
    required: true,
    group: 'timing',
  },
  {
    id: 'timeframe',
    type: 'text',
    label: 'Target Timeframe',
    placeholder: 'When should mediation be completed?',
    required: false,
    group: 'timing',
  },
  {
    id: 'sessionDuration',
    type: 'text',
    label: 'Session Duration',
    placeholder: 'Expected length of each session',
    required: false,
    group: 'timing',
  },
  {
    id: 'principalAttendance',
    type: 'checkbox',
    label: 'Require principal party attendance',
    required: false,
    group: 'participation',
  },
  {
    id: 'attorneyAttendance',
    type: 'select',
    label: 'Attorney Attendance',
    options: [
      { value: 'required', label: 'Required' },
      { value: 'optional', label: 'Optional' },
      { value: 'prohibited', label: 'Prohibited' },
      { value: 'advisory-only', label: 'Advisory Only' },
    ],
    required: true,
    group: 'participation',
  },
  {
    id: 'decisionMakingAuthority',
    type: 'checkbox',
    label: 'Attendees must have decision-making authority',
    required: false,
    group: 'participation',
  },
  {
    id: 'preparationRequirements',
    type: 'text',
    label: 'Preparation Requirements',
    placeholder: 'What must parties prepare before mediation?',
    required: false,
    group: 'participation',
  },
  {
    id: 'documentExchange',
    type: 'checkbox',
    label: 'Require document exchange',
    required: false,
    group: 'participation',
  },
  {
    id: 'confidentialityClause',
    type: 'checkbox',
    label: 'Include confidentiality clause',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'mediatorConfidentiality',
    type: 'checkbox',
    label: 'Mediator bound by confidentiality',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'partyConfidentiality',
    type: 'checkbox',
    label: 'Parties bound by confidentiality',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'documentConfidentiality',
    type: 'checkbox',
    label: 'Documents kept confidential',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'communicationConfidentiality',
    type: 'checkbox',
    label: 'Communications kept confidential',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'futureDisclosureProhibition',
    type: 'checkbox',
    label: 'Prohibit future disclosure',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'mediationPrivilege',
    type: 'checkbox',
    label: 'Apply mediation privilege',
    required: false,
    group: 'privilege',
  },
  {
    id: 'settlementPrivilege',
    type: 'checkbox',
    label: 'Apply settlement privilege',
    required: false,
    group: 'privilege',
  },
  {
    id: 'withoutPrejudice',
    type: 'checkbox',
    label: 'Mark discussions as "without prejudice"',
    required: false,
    group: 'privilege',
  },
  {
    id: 'inadmissibilityClause',
    type: 'checkbox',
    label: 'Include inadmissibility clause',
    required: false,
    group: 'privilege',
  },
  {
    id: 'caucusConfidentiality',
    type: 'checkbox',
    label: 'Keep caucus discussions confidential',
    required: false,
    group: 'information-sharing',
  },
  {
    id: 'jointSessionSharing',
    type: 'checkbox',
    label: 'Allow sharing in joint sessions',
    required: false,
    group: 'information-sharing',
  },
  {
    id: 'expertInformation',
    type: 'checkbox',
    label: 'Allow expert information sharing',
    required: false,
    group: 'information-sharing',
  },
  {
    id: 'financialDisclosure',
    type: 'checkbox',
    label: 'Require financial disclosure',
    required: false,
    group: 'information-sharing',
  },
  {
    id: 'documentProduction',
    type: 'checkbox',
    label: 'Allow document production',
    required: false,
    group: 'information-sharing',
  },
  {
    id: 'goodFaithRequirement',
    type: 'checkbox',
    label: 'Require good faith participation',
    required: false,
    group: 'good-faith',
  },
  {
    id: 'preparationStandard',
    type: 'text',
    label: 'Preparation Standard',
    placeholder: 'Standard for adequate preparation',
    required: false,
    group: 'good-faith',
  },
  {
    id: 'participationStandard',
    type: 'text',
    label: 'Participation Standard',
    placeholder: 'Standard for meaningful participation',
    required: false,
    group: 'good-faith',
  },
  {
    id: 'communicationStandard',
    type: 'text',
    label: 'Communication Standard',
    placeholder: 'Standard for open communication',
    required: false,
    group: 'good-faith',
  },
  {
    id: 'considerationStandard',
    type: 'text',
    label: 'Consideration Standard',
    placeholder: 'Standard for considering proposals',
    required: false,
    group: 'good-faith',
  },
  {
    id: 'costSharing',
    type: 'select',
    label: 'Cost Sharing Method',
    options: [
      { value: 'equal-split', label: 'Equal Split' },
      { value: 'proportional', label: 'Proportional to Dispute Value' },
      { value: 'initiating-party', label: 'Initiating Party Pays' },
      { value: 'ability-to-pay', label: 'Based on Ability to Pay' },
      { value: 'other', label: 'Other Method' },
    ],
    required: true,
    group: 'costs',
  },
  {
    id: 'mediatorFees',
    type: 'select',
    label: 'Mediator Fee Structure',
    options: [
      { value: 'hourly', label: 'Hourly Rate' },
      { value: 'daily', label: 'Daily Rate' },
      { value: 'flat-fee', label: 'Flat Fee' },
      { value: 'sliding-scale', label: 'Sliding Scale' },
    ],
    required: true,
    group: 'costs',
  },
  {
    id: 'feeAmount',
    type: 'text',
    label: 'Fee Amount',
    placeholder: 'Mediator fee amount',
    required: false,
    group: 'costs',
  },
  {
    id: 'expenseSharing',
    type: 'checkbox',
    label: 'Share additional expenses',
    required: false,
    group: 'costs',
  },
  {
    id: 'paymentSchedule',
    type: 'text',
    label: 'Payment Schedule',
    placeholder: 'When and how fees will be paid',
    required: false,
    group: 'costs',
  },
  {
    id: 'settlementAuthority',
    type: 'checkbox',
    label: 'Parties have settlement authority',
    required: false,
    group: 'settlement',
  },
  {
    id: 'approvalRequirements',
    type: 'text',
    label: 'Approval Requirements',
    placeholder: 'Who must approve any settlement?',
    required: false,
    group: 'settlement',
  },
  {
    id: 'ratificationProcess',
    type: 'text',
    label: 'Ratification Process',
    placeholder: 'How will agreements be ratified?',
    required: false,
    group: 'settlement',
  },
  {
    id: 'bindingCommitments',
    type: 'checkbox',
    label: 'Allow binding commitments during mediation',
    required: false,
    group: 'settlement',
  },
  {
    id: 'tentativeAgreements',
    type: 'checkbox',
    label: 'Allow tentative agreements',
    required: false,
    group: 'settlement',
  },
  {
    id: 'sessionRecords',
    type: 'checkbox',
    label: 'Keep session records',
    required: false,
    group: 'documentation',
  },
  {
    id: 'agreementDocumentation',
    type: 'checkbox',
    label: 'Document any agreements',
    required: false,
    group: 'documentation',
  },
  {
    id: 'draftingResponsibility',
    type: 'select',
    label: 'Drafting Responsibility',
    options: [
      { value: 'mediator', label: 'Mediator' },
      { value: 'parties', label: 'Parties' },
      { value: 'attorneys', label: 'Attorneys' },
      { value: 'mutual', label: 'Mutual Effort' },
    ],
    required: true,
    group: 'documentation',
  },
  {
    id: 'legalReview',
    type: 'checkbox',
    label: 'Require legal review of agreements',
    required: false,
    group: 'documentation',
  },
  {
    id: 'terminationRights',
    type: 'checkbox',
    label: 'Parties may terminate mediation',
    required: false,
    group: 'termination',
  },
  {
    id: 'terminationNotice',
    type: 'text',
    label: 'Termination Notice',
    placeholder: 'How much notice to terminate?',
    required: false,
    group: 'termination',
  },
  {
    id: 'impasseDeclaration',
    type: 'checkbox',
    label: 'Allow impasse declaration',
    required: false,
    group: 'termination',
  },
  {
    id: 'continuationOptions',
    type: 'text',
    label: 'Continuation Options',
    placeholder: 'Options if mediation continues',
    required: false,
    group: 'termination',
  },
  {
    id: 'alternativeProcesses',
    type: 'text',
    label: 'Alternative Processes',
    placeholder: 'What happens if mediation fails?',
    required: false,
    group: 'termination',
  },
  {
    id: 'neutralityRequirement',
    type: 'checkbox',
    label: 'Require mediator neutrality',
    required: false,
    group: 'ethics',
  },
  {
    id: 'impartialityStandard',
    type: 'checkbox',
    label: 'Require mediator impartiality',
    required: false,
    group: 'ethics',
  },
  {
    id: 'conflictOfInterestDisclosure',
    type: 'checkbox',
    label: 'Require conflict of interest disclosure',
    required: false,
    group: 'ethics',
  },
  {
    id: 'professionalStandards',
    type: 'checkbox',
    label: 'Follow professional standards',
    required: false,
    group: 'ethics',
  },
  {
    id: 'ethicalGuidelines',
    type: 'text',
    label: 'Ethical Guidelines',
    placeholder: 'Specific ethical guidelines to follow',
    required: false,
    group: 'ethics',
  },
  {
    id: 'virtualPlatform',
    type: 'text',
    label: 'Virtual Platform',
    placeholder: 'Platform for virtual mediation',
    required: false,
    group: 'technology',
  },
  {
    id: 'documentSharing',
    type: 'checkbox',
    label: 'Allow electronic document sharing',
    required: false,
    group: 'technology',
  },
  {
    id: 'realTimeCollaboration',
    type: 'checkbox',
    label: 'Allow real-time collaboration tools',
    required: false,
    group: 'technology',
  },
  {
    id: 'electronicSignatures',
    type: 'checkbox',
    label: 'Accept electronic signatures',
    required: false,
    group: 'technology',
  },
  {
    id: 'recordingProhibition',
    type: 'checkbox',
    label: 'Prohibit recording of sessions',
    required: false,
    group: 'technology',
  },
  {
    id: 'languageNeeds',
    type: 'text',
    label: 'Language Needs',
    placeholder: 'Language requirements',
    required: false,
    group: 'cultural',
  },
  {
    id: 'interpreterServices',
    type: 'checkbox',
    label: 'Provide interpreter services',
    required: false,
    group: 'cultural',
  },
  {
    id: 'accommodationRequirements',
    type: 'text',
    label: 'Accommodation Requirements',
    placeholder: 'Special accommodations needed',
    required: false,
    group: 'cultural',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'e.g., State of California',
    required: false,
    group: 'legal',
  },
  {
    id: 'requireAllPartySignatures',
    type: 'checkbox',
    label: 'Require all party signatures',
    required: false,
    group: 'signatures',
  },
  {
    id: 'witnessRequirement',
    type: 'checkbox',
    label: 'Require witness',
    required: false,
    group: 'signatures',
  },
  {
    id: 'notarizationRequirement',
    type: 'checkbox',
    label: 'Require notarization',
    required: false,
    group: 'signatures',
  },
  {
    id: 'electronicSignatureAccepted',
    type: 'checkbox',
    label: 'Accept electronic signatures',
    required: false,
    group: 'signatures',
  },
];
