import type { Question } from '@/types/documents';
import { usStates } from '@/lib/document-library/utils';

export const jointVentureAgreementQuestions: Question[] = [
  {
    id: 'ventureName',
    label: 'Joint Venture Name',
    type: 'text',
    required: true,
    placeholder: 'e.g., Tech Innovation Joint Venture',
  },
  {
    id: 'ventureDescription',
    label: 'Venture Description',
    type: 'textarea',
    required: true,
    placeholder: 'Describe the specific project or business venture',
  },
  {
    id: 'party1Name',
    label: 'Party 1 Name',
    type: 'text',
    required: true,
    placeholder: 'e.g., ABC Corporation',
  },
  {
    id: 'party1Address',
    label: 'Party 1 Address',
    type: 'textarea',
    required: true,
  },
  {
    id: 'party1Type',
    label: 'Party 1 Entity Type',
    type: 'select',
    required: true,
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'llc', label: 'Limited Liability Company' },
      { value: 'partnership', label: 'Partnership' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'party2Name',
    label: 'Party 2 Name',
    type: 'text',
    required: true,
    placeholder: 'e.g., XYZ Technologies LLC',
  },
  {
    id: 'party2Address',
    label: 'Party 2 Address',
    type: 'textarea',
    required: true,
  },
  {
    id: 'party2Type',
    label: 'Party 2 Entity Type',
    type: 'select',
    required: true,
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'llc', label: 'Limited Liability Company' },
      { value: 'partnership', label: 'Partnership' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'additionalParties',
    label: 'Additional Parties (if any)',
    type: 'textarea',
    placeholder: 'List any additional parties to the joint venture',
  },
  {
    id: 'ventureObjectives',
    label: 'Venture Objectives',
    type: 'textarea',
    required: true,
    placeholder: 'Describe the specific goals and objectives of the joint venture',
  },
  {
    id: 'contributions',
    label: 'Party Contributions',
    type: 'textarea',
    required: true,
    placeholder: 'Describe what each party will contribute (money, resources, expertise, etc.)',
  },
  {
    id: 'profitSharing',
    label: 'Profit Sharing',
    type: 'textarea',
    required: true,
    placeholder: 'How profits will be shared between parties',
  },
  {
    id: 'lossSharing',
    label: 'Loss Sharing',
    type: 'textarea',
    required: true,
    placeholder: 'How losses will be shared between parties',
  },
  {
    id: 'managementStructure',
    label: 'Management Structure',
    type: 'textarea',
    required: true,
    placeholder: 'How the joint venture will be managed and who has authority',
  },
  {
    id: 'decisionMaking',
    label: 'Decision Making Process',
    type: 'textarea',
    required: true,
    placeholder: 'How major decisions will be made (voting, consensus, etc.)',
  },
  {
    id: 'intellectualProperty',
    label: 'Intellectual Property Rights',
    type: 'textarea',
    required: true,
    placeholder: 'How intellectual property created or used will be owned and protected',
  },
  {
    id: 'confidentiality',
    label: 'Confidentiality Terms',
    type: 'textarea',
    required: true,
    placeholder: 'Confidentiality obligations regarding trade secrets and sensitive information',
  },
  {
    id: 'terminationConditions',
    label: 'Termination Conditions',
    type: 'textarea',
    required: true,
    placeholder: 'Conditions under which the joint venture can be terminated',
  },
  {
    id: 'disputeResolution',
    label: 'Dispute Resolution Method',
    type: 'select',
    required: true,
    options: [
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'litigation', label: 'Court Litigation' },
    ],
  },
  {
    id: 'term',
    label: 'Venture Term',
    type: 'text',
    required: true,
    placeholder: 'e.g., 2 years, or until project completion',
  },
  {
    id: 'governingLaw',
    label: 'Governing Law',
    type: 'text',
    required: true,
    placeholder: 'Which state or jurisdiction laws will govern the agreement',
  },
  {
    id: 'effectiveDate',
    label: 'Effective Date',
    type: 'date',
    required: true,
  },
  {
    id: 'state',
    label: 'State',
    type: 'select',
    required: true,
    options: usStates.map((s) => ({ value: s.value, label: s.label })),
  },
];