// src/lib/documents/us/contract-amendment/questions.ts
import type { FormQuestion } from '@/types/documents';

export const contractAmendmentQuestions: FormQuestion[] = [
  // Original Contract Information
  {
    id: 'originalContractTitle',
    type: 'text',
    label: 'Original Contract Title',
    placeholder: 'Enter the title of the contract being amended',
    required: true,
    section: 'Original Contract Information',
  },
  {
    id: 'originalContractDate',
    type: 'date',
    label: 'Original Contract Date',
    required: true,
    section: 'Original Contract Information',
  },
  {
    id: 'originalContractParties',
    type: 'textarea',
    label: 'Original Contract Parties',
    placeholder: 'List all parties to the original contract',
    required: true,
    section: 'Original Contract Information',
  },
  {
    id: 'contractReference',
    type: 'text',
    label: 'Contract Reference Number (if applicable)',
    placeholder: 'Enter contract reference or file number',
    required: false,
    section: 'Original Contract Information',
  },

  // Amendment Information
  {
    id: 'amendmentNumber',
    type: 'text',
    label: 'Amendment Number',
    placeholder: 'e.g., Amendment #1, First Amendment',
    required: true,
    section: 'Amendment Details',
  },
  {
    id: 'amendmentDate',
    type: 'date',
    label: 'Amendment Date',
    required: true,
    section: 'Amendment Details',
  },
  {
    id: 'amendmentEffectiveDate',
    type: 'date',
    label: 'Amendment Effective Date',
    required: true,
    section: 'Amendment Details',
  },

  // Parties Information
  {
    id: 'partyOneName',
    type: 'text',
    label: 'First Party Name',
    placeholder: 'Enter first party name',
    required: true,
    section: 'Parties Information',
  },
  {
    id: 'partyOneAddress',
    type: 'address',
    label: 'First Party Address',
    placeholder: 'Enter first party address',
    required: true,
    section: 'Parties Information',
  },
  {
    id: 'partyOneType',
    type: 'select',
    label: 'First Party Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'llc', label: 'LLC' },
      { value: 'partnership', label: 'Partnership' },
    ],
    required: true,
    section: 'Parties Information',
  },
  {
    id: 'partyTwoName',
    type: 'text',
    label: 'Second Party Name',
    placeholder: 'Enter second party name',
    required: true,
    section: 'Parties Information',
  },
  {
    id: 'partyTwoAddress',
    type: 'address',
    label: 'Second Party Address',
    placeholder: 'Enter second party address',
    required: true,
    section: 'Parties Information',
  },
  {
    id: 'partyTwoType',
    type: 'select',
    label: 'Second Party Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'llc', label: 'LLC' },
      { value: 'partnership', label: 'Partnership' },
    ],
    required: true,
    section: 'Parties Information',
  },

  // Amendment Type and Details
  {
    id: 'amendmentType',
    type: 'select',
    label: 'Type of Amendment',
    options: [
      { value: 'modification', label: 'Modification of existing terms' },
      { value: 'addition', label: 'Addition of new terms' },
      { value: 'deletion', label: 'Deletion of existing terms' },
      { value: 'clarification', label: 'Clarification of existing terms' },
      { value: 'extension', label: 'Extension of contract period' },
      { value: 'termination_date_change', label: 'Change of termination date' },
    ],
    required: true,
    section: 'Amendment Content',
  },
  {
    id: 'sectionsAmended',
    type: 'textarea',
    label: 'Sections Being Amended',
    placeholder:
      'Specify which sections, clauses, or provisions are being amended',
    required: true,
    section: 'Amendment Content',
  },
  {
    id: 'originalLanguage',
    type: 'textarea',
    label: 'Original Contract Language',
    placeholder:
      'Copy the exact language from the original contract that is being changed',
    required: true,
    section: 'Amendment Content',
  },
  {
    id: 'amendedLanguage',
    type: 'textarea',
    label: 'New Amended Language',
    placeholder: 'Enter the new language that will replace the original text',
    required: true,
    section: 'Amendment Content',
  },
  {
    id: 'reasonForAmendment',
    type: 'textarea',
    label: 'Reason for Amendment',
    placeholder: 'Explain why this amendment is necessary',
    required: true,
    section: 'Amendment Content',
  },

  // Specific Changes
  {
    id: 'priceAdjustment',
    type: 'radio',
    label: 'Does this amendment involve price changes?',
    options: [
      { value: true, label: 'Yes, price adjustment included' },
      { value: false, label: 'No price changes' },
    ],
    required: true,
    section: 'Specific Changes',
  },
  {
    id: 'newPrice',
    type: 'currency',
    label: 'New Price/Amount',
    placeholder: 'Enter new price or amount',
    required: false,
    section: 'Specific Changes',
    conditional: {
      field: 'priceAdjustment',
      value: [true],
    },
  },
  {
    id: 'priceChangeReason',
    type: 'textarea',
    label: 'Reason for Price Change',
    placeholder: 'Explain the reason for the price adjustment',
    required: false,
    section: 'Specific Changes',
    conditional: {
      field: 'priceAdjustment',
      value: [true],
    },
  },
  {
    id: 'timelineAdjustment',
    type: 'radio',
    label: 'Does this amendment involve timeline changes?',
    options: [
      { value: true, label: 'Yes, timeline adjustment included' },
      { value: false, label: 'No timeline changes' },
    ],
    required: true,
    section: 'Specific Changes',
  },
  {
    id: 'newDeadline',
    type: 'date',
    label: 'New Deadline/Date',
    required: false,
    section: 'Specific Changes',
    conditional: {
      field: 'timelineAdjustment',
      value: [true],
    },
  },
  {
    id: 'timelineChangeReason',
    type: 'textarea',
    label: 'Reason for Timeline Change',
    placeholder: 'Explain the reason for the timeline adjustment',
    required: false,
    section: 'Specific Changes',
    conditional: {
      field: 'timelineAdjustment',
      value: [true],
    },
  },
  {
    id: 'scopeChange',
    type: 'radio',
    label: 'Does this amendment involve scope changes?',
    options: [
      { value: true, label: 'Yes, scope change included' },
      { value: false, label: 'No scope changes' },
    ],
    required: true,
    section: 'Specific Changes',
  },
  {
    id: 'scopeChangeDescription',
    type: 'textarea',
    label: 'Scope Change Description',
    placeholder: 'Describe the changes to the project or service scope',
    required: false,
    section: 'Specific Changes',
    conditional: {
      field: 'scopeChange',
      value: [true],
    },
  },

  // Legal Provisions
  {
    id: 'severabilityClause',
    type: 'radio',
    label: 'Include severability clause?',
    options: [
      { value: true, label: 'Yes, include severability clause' },
      { value: false, label: 'No severability clause' },
    ],
    required: true,
    section: 'Legal Provisions',
  },
  {
    id: 'remainingTermsValid',
    type: 'radio',
    label: 'All other terms remain in effect?',
    options: [
      { value: true, label: 'Yes, all other terms remain valid' },
      { value: false, label: 'No, other terms are also affected' },
    ],
    required: true,
    section: 'Legal Provisions',
  },
  {
    id: 'amendmentPrecedence',
    type: 'radio',
    label: 'Amendment takes precedence over original?',
    options: [
      { value: true, label: 'Yes, amendment supersedes conflicting terms' },
      { value: false, label: 'No, original contract takes precedence' },
    ],
    required: true,
    section: 'Legal Provisions',
  },

  // Authority and Representatives
  {
    id: 'partyOneAuthorizedRepresentative',
    type: 'text',
    label: 'First Party Authorized Representative',
    placeholder: 'Name of person authorized to sign for first party',
    required: true,
    section: 'Authorization',
  },
  {
    id: 'partyOneTitle',
    type: 'text',
    label: 'First Party Representative Title',
    placeholder: 'Title of first party representative',
    required: false,
    section: 'Authorization',
  },
  {
    id: 'partyTwoAuthorizedRepresentative',
    type: 'text',
    label: 'Second Party Authorized Representative',
    placeholder: 'Name of person authorized to sign for second party',
    required: true,
    section: 'Authorization',
  },
  {
    id: 'partyTwoTitle',
    type: 'text',
    label: 'Second Party Representative Title',
    placeholder: 'Title of second party representative',
    required: false,
    section: 'Authorization',
  },

  // Governing Law
  {
    id: 'governingState',
    type: 'select',
    label: 'Governing State Law',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
    required: true,
    section: 'Legal Terms',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'courts', label: 'Court litigation' },
      { value: 'arbitration', label: 'Binding arbitration' },
      { value: 'mediation', label: 'Mediation first, then courts' },
    ],
    required: true,
    section: 'Legal Terms',
  },

  // Additional Terms
  {
    id: 'additionalTerms',
    type: 'textarea',
    label: 'Additional Terms',
    placeholder: 'Enter any additional terms or conditions',
    required: false,
    section: 'Additional Terms',
  },
  {
    id: 'specialConditions',
    type: 'textarea',
    label: 'Special Conditions',
    placeholder: 'Enter any special conditions or requirements',
    required: false,
    section: 'Additional Terms',
  },

  // Execution
  {
    id: 'executionDate',
    type: 'date',
    label: 'Amendment Execution Date',
    required: true,
    section: 'Signatures',
  },
  {
    id: 'witnessRequired',
    type: 'radio',
    label: 'Are witnesses required?',
    options: [
      { value: true, label: 'Yes, witnesses are required' },
      { value: false, label: 'No, witnesses are not required' },
    ],
    required: true,
    section: 'Signatures',
  },
  {
    id: 'witnessName',
    type: 'text',
    label: 'Witness Name',
    placeholder: 'Enter witness full name',
    required: false,
    section: 'Signatures',
    conditional: {
      field: 'witnessRequired',
      value: [true],
    },
  },
  {
    id: 'notaryRequired',
    type: 'radio',
    label: 'Is notarization required?',
    options: [
      { value: true, label: 'Yes, notarization is required' },
      { value: false, label: 'No, notarization is not required' },
    ],
    required: true,
    section: 'Signatures',
  },
];
