// src/lib/documents/us/affidavit-of-survivorship/questions.ts
import type { Question } from '@/types/documents';

export const questions: Question[] = [
  // Section 1: Surviving Owner Information
  {
    id: 'survivorName',
    type: 'text',
    label: 'Your Full Legal Name (Surviving Owner)',
    required: true,
    section: 'Surviving Owner Information',
    placeholder: 'Enter your full legal name',
    description: 'You are the surviving joint owner.',
  },
  {
    id: 'survivorAddress',
    type: 'text',
    label: 'Your Street Address',
    required: true,
    section: 'Surviving Owner Information',
    placeholder: 'Enter your street address',
  },
  {
    id: 'survivorCity',
    type: 'text',
    label: 'Your City',
    required: true,
    section: 'Surviving Owner Information',
    placeholder: 'Enter your city',
  },
  {
    id: 'survivorState',
    type: 'select',
    label: 'Your State',
    required: true,
    section: 'Surviving Owner Information',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
  },
  {
    id: 'survivorZip',
    type: 'text',
    label: 'Your ZIP Code',
    required: true,
    section: 'Surviving Owner Information',
    placeholder: 'Enter your ZIP code',
  },
  {
    id: 'survivorPhone',
    type: 'text',
    label: 'Your Phone Number',
    required: true,
    section: 'Surviving Owner Information',
    placeholder: 'Enter your phone number',
  },
  {
    id: 'survivorSSN',
    type: 'text',
    label: 'Your Social Security Number',
    required: true,
    section: 'Surviving Owner Information',
    placeholder: 'XXX-XX-XXXX',
    description: 'Required for property transfer.',
  },

  // Section 2: Deceased Owner Information
  {
    id: 'decedentName',
    type: 'text',
    label: "Deceased Owner's Full Legal Name",
    required: true,
    section: 'Deceased Owner Information',
    placeholder: "Enter the deceased owner's full legal name",
  },
  {
    id: 'decedentDateOfDeath',
    type: 'date',
    label: 'Date of Death',
    required: true,
    section: 'Deceased Owner Information',
  },
  {
    id: 'decedentDateOfBirth',
    type: 'date',
    label: 'Date of Birth',
    required: true,
    section: 'Deceased Owner Information',
  },
  {
    id: 'decedentAddress',
    type: 'text',
    label: "Deceased Owner's Last Known Address",
    required: true,
    section: 'Deceased Owner Information',
    placeholder: "Enter the deceased owner's street address",
  },
  {
    id: 'decedentCity',
    type: 'text',
    label: 'City',
    required: true,
    section: 'Deceased Owner Information',
    placeholder: "Enter the deceased owner's city",
  },
  {
    id: 'decedentState',
    type: 'select',
    label: 'State',
    required: true,
    section: 'Deceased Owner Information',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
  },
  {
    id: 'decedentZip',
    type: 'text',
    label: 'ZIP Code',
    required: true,
    section: 'Deceased Owner Information',
    placeholder: "Enter the deceased owner's ZIP code",
  },
  {
    id: 'decedentSSN',
    type: 'text',
    label: "Deceased Owner's Social Security Number",
    required: true,
    section: 'Deceased Owner Information',
    placeholder: 'XXX-XX-XXXX',
    description: 'Required for property transfer.',
  },

  // Section 3: Relationship Information
  {
    id: 'relationshipToDeceased',
    type: 'text',
    label: 'Your Relationship to the Deceased',
    required: true,
    section: 'Relationship Information',
    placeholder: 'e.g., Spouse, Domestic Partner, Business Partner',
  },
  {
    id: 'marriageDate',
    type: 'date',
    label: 'Date of Marriage',
    required: false,
    section: 'Relationship Information',
    description: 'Required if you were married to the deceased.',
  },
  {
    id: 'marriagePlace',
    type: 'text',
    label: 'Place of Marriage',
    required: false,
    section: 'Relationship Information',
    placeholder: 'City, State',
    description: 'Required if you were married to the deceased.',
  },

  // Section 4: Property Information
  {
    id: 'propertyType',
    type: 'radio',
    label: 'Type of Property/Asset',
    required: true,
    section: 'Property Information',
    options: [
      { value: 'real_estate', label: 'Real Estate (house, land, etc.)' },
      { value: 'bank_account', label: 'Bank Account' },
      { value: 'investment_account', label: 'Investment Account' },
      { value: 'vehicle', label: 'Vehicle (car, truck, boat, etc.)' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'propertyTypeOther',
    type: 'text',
    label: 'Specify Other Property Type',
    required: false,
    section: 'Property Information',
    placeholder: 'Describe the type of property',
    condition: { field: 'propertyType', value: 'other' },
  },
  {
    id: 'propertyDescription',
    type: 'textarea',
    label: 'Detailed Property Description',
    required: true,
    section: 'Property Information',
    placeholder: 'Provide a detailed description of the property or asset...',
    description:
      'Include all identifying information such as legal description, account numbers, etc.',
  },
  {
    id: 'propertyAddress',
    type: 'text',
    label: 'Property Address',
    required: true,
    section: 'Property Information',
    placeholder: 'Enter the property street address',
    description:
      'For accounts, enter the institution address. For vehicles, enter where located.',
  },
  {
    id: 'propertyCity',
    type: 'text',
    label: 'Property City',
    required: true,
    section: 'Property Information',
    placeholder: 'Enter the property city',
  },
  {
    id: 'propertyState',
    type: 'select',
    label: 'Property State',
    required: true,
    section: 'Property Information',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
  },
  {
    id: 'propertyZip',
    type: 'text',
    label: 'Property ZIP Code',
    required: true,
    section: 'Property Information',
    placeholder: 'Enter the property ZIP code',
  },

  // Section 5: Financial Institution Information (conditional)
  {
    id: 'institutionName',
    type: 'text',
    label: 'Financial Institution Name',
    required: false,
    section: 'Account Information',
    placeholder: 'Enter bank or financial institution name',
    condition: {
      field: 'propertyType',
      value: ['bank_account', 'investment_account'],
    },
  },
  {
    id: 'accountNumber',
    type: 'text',
    label: 'Account Number',
    required: false,
    section: 'Account Information',
    placeholder: 'Enter account number',
    condition: {
      field: 'propertyType',
      value: ['bank_account', 'investment_account'],
    },
  },
  {
    id: 'accountType',
    type: 'text',
    label: 'Account Type',
    required: false,
    section: 'Account Information',
    placeholder: 'e.g., Checking, Savings, CD, Investment',
    condition: {
      field: 'propertyType',
      value: ['bank_account', 'investment_account'],
    },
  },

  // Section 6: Vehicle Information (conditional)
  {
    id: 'vehicleVIN',
    type: 'text',
    label: 'Vehicle Identification Number (VIN)',
    required: false,
    section: 'Vehicle Information',
    placeholder: 'Enter 17-character VIN',
    condition: { field: 'propertyType', value: 'vehicle' },
  },
  {
    id: 'vehicleYear',
    type: 'text',
    label: 'Vehicle Year',
    required: false,
    section: 'Vehicle Information',
    placeholder: 'Enter year',
    condition: { field: 'propertyType', value: 'vehicle' },
  },
  {
    id: 'vehicleMake',
    type: 'text',
    label: 'Vehicle Make',
    required: false,
    section: 'Vehicle Information',
    placeholder: 'e.g., Ford, Toyota, Honda',
    condition: { field: 'propertyType', value: 'vehicle' },
  },
  {
    id: 'vehicleModel',
    type: 'text',
    label: 'Vehicle Model',
    required: false,
    section: 'Vehicle Information',
    placeholder: 'e.g., Camry, F-150, Civic',
    condition: { field: 'propertyType', value: 'vehicle' },
  },

  // Section 7: Ownership Details
  {
    id: 'ownershipType',
    type: 'radio',
    label: 'Type of Joint Ownership',
    required: true,
    section: 'Ownership Details',
    options: [
      {
        value: 'joint_tenants',
        label: 'Joint Tenants with Right of Survivorship',
      },
      { value: 'tenants_entirety', label: 'Tenants by the Entirety' },
      {
        value: 'joint_account',
        label: 'Joint Account with Right of Survivorship',
      },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'ownershipTypeOther',
    type: 'text',
    label: 'Specify Other Ownership Type',
    required: false,
    section: 'Ownership Details',
    placeholder: 'Describe the ownership arrangement',
    condition: { field: 'ownershipType', value: 'other' },
  },
  {
    id: 'ownershipPercentages',
    type: 'text',
    label: 'Ownership Percentages',
    required: true,
    section: 'Ownership Details',
    placeholder: 'e.g., 50% each, Equal ownership',
    description:
      'Describe how the property was owned between you and the deceased.',
  },
  {
    id: 'survivorshipRights',
    type: 'radio',
    label: 'Did the ownership include survivorship rights?',
    required: true,
    section: 'Ownership Details',
    options: [
      { value: 'true', label: 'Yes, ownership included right of survivorship' },
      {
        value: 'false',
        label: 'No, ownership did not include right of survivorship',
      },
    ],
    description:
      "Right of survivorship means the surviving owner automatically inherits the deceased owner's share.",
  },
  {
    id: 'survivorshipDescription',
    type: 'textarea',
    label: 'Description of Survivorship Rights',
    required: true,
    section: 'Ownership Details',
    placeholder:
      'Describe the survivorship provisions and how ownership passes to you...',
    description:
      'Explain how the property ownership transfers to you as the survivor.',
  },

  // Section 8: Original Ownership Documentation
  {
    id: 'originalDeedDate',
    type: 'date',
    label: 'Date of Original Deed/Document',
    required: true,
    section: 'Original Documentation',
    description: 'The date the original ownership document was created.',
  },
  {
    id: 'originalDeedBook',
    type: 'text',
    label: 'Deed Book Number',
    required: false,
    section: 'Original Documentation',
    placeholder: 'Enter deed book number (if applicable)',
    description: 'For real estate, the book where the deed was recorded.',
  },
  {
    id: 'originalDeedPage',
    type: 'text',
    label: 'Deed Page Number',
    required: false,
    section: 'Original Documentation',
    placeholder: 'Enter page number (if applicable)',
    description: 'For real estate, the page where the deed was recorded.',
  },
  {
    id: 'originalRecordingInfo',
    type: 'textarea',
    label: 'Additional Recording Information',
    required: false,
    section: 'Original Documentation',
    placeholder:
      'Provide any additional recording or documentation information...',
    description:
      'Include any other relevant information about the original ownership documents.',
  },

  // Section 9: Death Certificate Information
  {
    id: 'deathCertificateNumber',
    type: 'text',
    label: 'Death Certificate Number',
    required: false,
    section: 'Death Certificate',
    placeholder: 'Enter death certificate number',
  },
  {
    id: 'deathCertificateIssuer',
    type: 'text',
    label: 'Death Certificate Issuing Authority',
    required: false,
    section: 'Death Certificate',
    placeholder: 'e.g., County Health Department, State Vital Records',
  },
  {
    id: 'deathCertificateDate',
    type: 'date',
    label: 'Death Certificate Issue Date',
    required: false,
    section: 'Death Certificate',
  },

  // Section 10: Additional Owners
  {
    id: 'hasAdditionalOwners',
    type: 'radio',
    label: 'Were there any other owners besides you and the deceased?',
    required: true,
    section: 'Additional Owners',
    options: [
      { value: 'true', label: 'Yes, there were other owners' },
      {
        value: 'false',
        label: 'No, only you and the deceased owned this property',
      },
    ],
  },
  {
    id: 'additionalOwners',
    type: 'array',
    label: 'Additional Owners',
    required: false,
    section: 'Additional Owners',
    condition: { field: 'hasAdditionalOwners', value: 'true' },
    description: 'List any other owners of this property.',
    arrayConfig: {
      minItems: 1,
      maxItems: 10,
      fields: [
        {
          id: 'name',
          type: 'text',
          label: 'Owner Name',
          required: true,
          placeholder: 'Enter owner full name',
        },
        {
          id: 'status',
          type: 'radio',
          label: 'Status',
          required: true,
          options: [
            { value: 'living', label: 'Living' },
            { value: 'deceased', label: 'Deceased' },
          ],
        },
        {
          id: 'address',
          type: 'text',
          label: 'Address',
          required: false,
          placeholder: 'Enter current address if living',
          condition: { field: 'status', value: 'living' },
        },
        {
          id: 'dateOfDeath',
          type: 'date',
          label: 'Date of Death',
          required: false,
          condition: { field: 'status', value: 'deceased' },
        },
      ],
    },
  },

  // Section 11: Estate Information
  {
    id: 'hasProbateProceedings',
    type: 'radio',
    label: 'Are there any probate proceedings for the deceased?',
    required: true,
    section: 'Estate Information',
    options: [
      { value: 'true', label: 'Yes, there are probate proceedings' },
      { value: 'false', label: 'No, there are no probate proceedings' },
    ],
  },
  {
    id: 'probateDetails',
    type: 'textarea',
    label: 'Probate Proceedings Details',
    required: false,
    section: 'Estate Information',
    placeholder: 'Describe the probate proceedings...',
    condition: { field: 'hasProbateProceedings', value: 'true' },
  },
  {
    id: 'hasWill',
    type: 'radio',
    label: 'Did the deceased leave a will?',
    required: true,
    section: 'Estate Information',
    options: [
      { value: 'true', label: 'Yes, the deceased left a will' },
      { value: 'false', label: 'No, the deceased died without a will' },
    ],
  },
  {
    id: 'willDetails',
    type: 'textarea',
    label: 'Will Details',
    required: false,
    section: 'Estate Information',
    placeholder: 'Describe relevant provisions of the will...',
    condition: { field: 'hasWill', value: 'true' },
  },

  // Section 12: Legal Declarations
  {
    id: 'noLiens',
    type: 'radio',
    label: 'Are there any liens or encumbrances on this property?',
    required: true,
    section: 'Legal Declarations',
    options: [
      { value: 'false', label: 'Yes, there are liens or encumbrances' },
      { value: 'true', label: 'No, there are no liens or encumbrances' },
    ],
  },
  {
    id: 'noDebts',
    type: 'radio',
    label: 'Are there any debts or obligations related to this property?',
    required: true,
    section: 'Legal Declarations',
    options: [
      { value: 'false', label: 'Yes, there are debts or obligations' },
      { value: 'true', label: 'No, there are no debts or obligations' },
    ],
  },
  {
    id: 'debtInformation',
    type: 'textarea',
    label: 'Debt/Lien Information',
    required: false,
    section: 'Legal Declarations',
    placeholder: 'Describe any liens, debts, or obligations...',
    condition: { field: 'noDebts', value: 'false' },
  },

  // Section 13: Additional Information
  {
    id: 'additionalInformation',
    type: 'textarea',
    label: 'Additional Information',
    required: false,
    section: 'Additional Information',
    placeholder: 'Provide any additional relevant information...',
    description:
      'Include any other information relevant to the survivorship claim.',
  },

  // Section 14: Legal Information
  {
    id: 'state',
    type: 'select',
    label: 'State Where This Affidavit Will Be Used',
    required: true,
    section: 'Legal Information',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
    description: 'Select the state where this affidavit will be filed.',
  },
  {
    id: 'county',
    type: 'text',
    label: 'County',
    required: true,
    section: 'Legal Information',
    placeholder: 'Enter the county name',
  },
  {
    id: 'dateCreated',
    type: 'date',
    label: 'Date of Creation',
    required: true,
    section: 'Legal Information',
    description: 'The date this affidavit is being created.',
  },

  // Section 15: Notarization
  {
    id: 'notaryName',
    type: 'text',
    label: 'Notary Public Name',
    required: false,
    section: 'Notarization',
    placeholder: 'Enter notary public name',
    description: 'This will be filled when the document is notarized.',
  },
  {
    id: 'notaryCommissionExpires',
    type: 'date',
    label: 'Notary Commission Expires',
    required: false,
    section: 'Notarization',
    description: 'This will be filled when the document is notarized.',
  },
];
