import type { Question } from '@/types/documents';

export const questions: Question[] = [
  {
    id: 'companyName',
    type: 'text',
    label: 'Company Name',
    required: true,
    category: 'Company Information',
  },
  {
    id: 'employeeName',
    type: 'text',
    label: 'Employee Full Name',
    required: true,
    category: 'Employee Information',
  },
  {
    id: 'jobTitle',
    type: 'text',
    label: 'Job Title',
    required: true,
    category: 'Employee Information',
  },
  {
    id: 'agreementStartDate',
    type: 'date',
    label: 'Agreement Start Date',
    required: true,
    category: 'Agreement Terms',
  },
  {
    id: 'workSchedule',
    type: 'select',
    label: 'Remote Work Schedule',
    required: true,
    category: 'Work Arrangement',
    options: ['Full-time remote', 'Part-time remote', 'Hybrid'],
  },
  {
    id: 'workHours',
    type: 'text',
    label: 'Work Hours',
    required: true,
    category: 'Work Arrangement',
    placeholder: 'e.g., 9:00 AM - 5:00 PM EST',
  },
  {
    id: 'primaryWorkLocation',
    type: 'text',
    label: 'Primary Remote Work Location',
    required: true,
    category: 'Work Location',
    placeholder: "Employee's home address or designated workspace",
  },
  {
    id: 'companyEquipmentProvided',
    type: 'radio',
    label: 'Will company provide equipment?',
    required: true,
    category: 'Equipment',
    options: ['Yes', 'No'],
  },
  {
    id: 'equipmentList',
    type: 'textarea',
    label: 'Equipment List (if provided)',
    required: false,
    category: 'Equipment',
    condition: { field: 'companyEquipmentProvided', value: 'Yes' },
    placeholder: 'List all equipment provided by company',
  },
  {
    id: 'internetReimbursement',
    type: 'radio',
    label: 'Internet Reimbursement Provided?',
    required: true,
    category: 'Reimbursements',
    options: ['Yes', 'No'],
  },
  {
    id: 'communicationTools',
    type: 'text',
    label: 'Required Communication Tools',
    required: true,
    category: 'Communication',
    placeholder: 'e.g., Slack, Zoom, Microsoft Teams',
  },
  {
    id: 'performanceMetrics',
    type: 'textarea',
    label: 'Performance Metrics',
    required: true,
    category: 'Performance',
    placeholder: 'How will performance be measured?',
  },
  {
    id: 'reportingFrequency',
    type: 'select',
    label: 'Reporting Frequency',
    required: true,
    category: 'Performance',
    options: ['Daily', 'Weekly', 'Bi-weekly', 'Monthly'],
  },
  {
    id: 'dataSecurityRequirements',
    type: 'textarea',
    label: 'Data Security Requirements',
    required: true,
    category: 'Security',
    placeholder: 'Describe security protocols and requirements',
  },
  {
    id: 'vpnRequired',
    type: 'radio',
    label: 'VPN Required?',
    required: true,
    category: 'Security',
    options: ['Yes', 'No'],
  },
  {
    id: 'signatureDate',
    type: 'date',
    label: 'Agreement Date',
    required: true,
    category: 'Signatures',
  },
];
