// src/lib/documents/us/small-estate-affidavit/questions.ts
import type { Question } from '@/types/documents';

export const questions: Question[] = [
  // Section 1: Deceased Person Information
  {
    id: 'decedentName',
    type: 'text',
    label: "Deceased Person's Full Legal Name",
    required: true,
    section: 'Deceased Person Information',
    placeholder: "Enter the deceased person's full legal name",
  },
  {
    id: 'decedentDateOfDeath',
    type: 'date',
    label: 'Date of Death',
    required: true,
    section: 'Deceased Person Information',
  },
  {
    id: 'decedentDateOfBirth',
    type: 'date',
    label: 'Date of Birth',
    required: true,
    section: 'Deceased Person Information',
  },
  {
    id: 'decedentAddress',
    type: 'text',
    label: "Deceased Person's Last Known Address",
    required: true,
    section: 'Deceased Person Information',
    placeholder: "Enter the deceased person's street address",
  },
  {
    id: 'decedentCity',
    type: 'text',
    label: 'City',
    required: true,
    section: 'Deceased Person Information',
    placeholder: "Enter the deceased person's city",
  },
  {
    id: 'decedentState',
    type: 'select',
    label: 'State',
    required: true,
    section: 'Deceased Person Information',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
  },
  {
    id: 'decedentZip',
    type: 'text',
    label: 'ZIP Code',
    required: true,
    section: 'Deceased Person Information',
    placeholder: "Enter the deceased person's ZIP code",
  },
  {
    id: 'decedentSSN',
    type: 'text',
    label: "Deceased Person's Social Security Number",
    required: true,
    section: 'Deceased Person Information',
    placeholder: 'XXX-XX-XXXX',
    description: 'This information is required for estate processing.',
  },

  // Section 2: Affiant Information
  {
    id: 'affiantName',
    type: 'text',
    label: 'Your Full Legal Name',
    required: true,
    section: 'Affiant Information',
    placeholder: 'Enter your full legal name',
    description: 'You are the person making this affidavit.',
  },
  {
    id: 'affiantAddress',
    type: 'text',
    label: 'Your Street Address',
    required: true,
    section: 'Affiant Information',
    placeholder: 'Enter your street address',
  },
  {
    id: 'affiantCity',
    type: 'text',
    label: 'Your City',
    required: true,
    section: 'Affiant Information',
    placeholder: 'Enter your city',
  },
  {
    id: 'affiantState',
    type: 'select',
    label: 'Your State',
    required: true,
    section: 'Affiant Information',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
  },
  {
    id: 'affiantZip',
    type: 'text',
    label: 'Your ZIP Code',
    required: true,
    section: 'Affiant Information',
    placeholder: 'Enter your ZIP code',
  },
  {
    id: 'affiantPhone',
    type: 'text',
    label: 'Your Phone Number',
    required: true,
    section: 'Affiant Information',
    placeholder: 'Enter your phone number',
  },
  {
    id: 'affiantRelationship',
    type: 'text',
    label: 'Your Relationship to the Deceased',
    required: true,
    section: 'Affiant Information',
    placeholder: 'e.g., Spouse, Child, Sibling, Grandchild',
  },

  // Section 3: Estate Information
  {
    id: 'estateValue',
    type: 'text',
    label: 'Total Value of Estate',
    required: true,
    section: 'Estate Information',
    placeholder: 'Enter total dollar amount (e.g., $50,000)',
    description: 'Include the value of all assets owned by the deceased at time of death.',
  },
  {
    id: 'hasWill',
    type: 'radio',
    label: 'Did the deceased leave a will?',
    required: true,
    section: 'Estate Information',
    options: [
      { value: 'true', label: 'Yes, the deceased left a will' },
      { value: 'false', label: 'No, the deceased died without a will (intestate)' },
    ],
  },
  {
    id: 'hasProbateProceedings',
    type: 'radio',
    label: 'Are there any probate proceedings pending?',
    required: true,
    section: 'Estate Information',
    options: [
      { value: 'true', label: 'Yes, there are probate proceedings' },
      { value: 'false', label: 'No, there are no probate proceedings' },
    ],
    description: 'Small estate affidavits are typically used when no formal probate is required.',
  },

  // Section 4: Heirs Information
  {
    id: 'heirs',
    type: 'array',
    label: 'Heirs and Beneficiaries',
    required: true,
    section: 'Heirs and Beneficiaries',
    description: 'List all persons entitled to inherit from the estate.',
    arrayConfig: {
      minItems: 1,
      maxItems: 10,
      fields: [
        {
          id: 'name',
          type: 'text',
          label: 'Full Name',
          required: true,
          placeholder: 'Enter heir full name',
        },
        {
          id: 'relationship',
          type: 'text',
          label: 'Relationship to Deceased',
          required: true,
          placeholder: 'e.g., Spouse, Child, Parent, Sibling',
        },
        {
          id: 'address',
          type: 'text',
          label: 'Address',
          required: true,
          placeholder: 'Enter heir complete address',
        },
        {
          id: 'share',
          type: 'text',
          label: 'Share of Estate',
          required: true,
          placeholder: 'e.g., 50%, 1/3, $10,000',
        },
        {
          id: 'age',
          type: 'text',
          label: 'Age',
          required: true,
          placeholder: 'Enter age',
        },
      ],
    },
  },

  // Section 5: Debts and Liabilities
  {
    id: 'totalDebts',
    type: 'text',
    label: 'Total Amount of Debts and Liabilities',
    required: true,
    section: 'Debts and Liabilities',
    placeholder: 'Enter total dollar amount (e.g., $5,000 or $0)',
    description: 'Include all known debts, loans, and liabilities of the deceased.',
  },
  {
    id: 'debtsPaid',
    type: 'radio',
    label: 'Have all debts and liabilities been paid?',
    required: true,
    section: 'Debts and Liabilities',
    options: [
      { value: 'true', label: 'Yes, all debts have been paid' },
      { value: 'false', label: 'No, some debts remain unpaid' },
    ],
  },
  {
    id: 'debtDescription',
    type: 'textarea',
    label: 'Description of Remaining Debts',
    required: false,
    section: 'Debts and Liabilities',
    placeholder: 'Describe any remaining debts and arrangements for payment...',
    condition: { field: 'debtsPaid', value: 'false' },
  },

  // Section 6: Assets
  {
    id: 'assets',
    type: 'array',
    label: 'Estate Assets',
    required: true,
    section: 'Estate Assets',
    description: 'List all assets owned by the deceased at time of death.',
    arrayConfig: {
      minItems: 1,
      maxItems: 20,
      fields: [
        {
          id: 'description',
          type: 'text',
          label: 'Asset Description',
          required: true,
          placeholder: 'e.g., Bank account at ABC Bank, 2010 Honda Civic, Real estate at 123 Main St',
        },
        {
          id: 'value',
          type: 'text',
          label: 'Estimated Value',
          required: true,
          placeholder: 'e.g., $15,000',
        },
        {
          id: 'location',
          type: 'text',
          label: 'Location/Institution',
          required: false,
          placeholder: 'e.g., First National Bank, 123 Oak Street',
        },
      ],
    },
  },

  // Section 7: Funeral Expenses
  {
    id: 'funeralExpenses',
    type: 'text',
    label: 'Total Funeral and Burial Expenses',
    required: true,
    section: 'Funeral Expenses',
    placeholder: 'Enter total dollar amount (e.g., $8,000)',
  },
  {
    id: 'funeralExpensesPaid',
    type: 'radio',
    label: 'Have funeral expenses been paid?',
    required: true,
    section: 'Funeral Expenses',
    options: [
      { value: 'true', label: 'Yes, funeral expenses have been paid' },
      { value: 'false', label: 'No, funeral expenses are still owed' },
    ],
  },

  // Section 8: Additional Information
  {
    id: 'additionalInformation',
    type: 'textarea',
    label: 'Additional Information',
    required: false,
    section: 'Additional Information',
    placeholder: 'Provide any additional relevant information about the estate...',
    description: 'Include any other relevant information about the estate or circumstances.',
  },

  // Section 9: Legal Information
  {
    id: 'state',
    type: 'select',
    label: 'State Where This Affidavit Will Be Used',
    required: true,
    section: 'Legal Information',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
    description: 'Select the state where this small estate affidavit will be filed.',
  },
  {
    id: 'county',
    type: 'text',
    label: 'County',
    required: true,
    section: 'Legal Information',
    placeholder: 'Enter the county name',
  },
  {
    id: 'dateCreated',
    type: 'date',
    label: 'Date of Creation',
    required: true,
    section: 'Legal Information',
    description: 'The date this affidavit is being created.',
  },

  // Section 10: Notarization
  {
    id: 'notaryName',
    type: 'text',
    label: 'Notary Public Name',
    required: false,
    section: 'Notarization',
    placeholder: 'Enter notary public name',
    description: 'This will be filled when the document is notarized.',
  },
  {
    id: 'notaryCommissionExpires',
    type: 'date',
    label: 'Notary Commission Expires',
    required: false,
    section: 'Notarization',
    description: 'This will be filled when the document is notarized.',
  },
];