// src/lib/documents/us/trademark-license-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const trademarkLicenseAgreementQuestions: FormQuestion[] = [
  {
    id: 'licensorName',
    type: 'text',
    label: 'Licensor Name (Trademark Owner)',
    placeholder: 'Enter trademark owner name',
    required: true,
    group: 'licensor',
  },
  {
    id: 'licensorAddress',
    type: 'text',
    label: 'Licensor Address',
    placeholder: 'Enter complete licensor address',
    required: true,
    group: 'licensor',
  },
  {
    id: 'licensorType',
    type: 'select',
    label: 'Licensor Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'partnership', label: 'Partnership' },
      { value: 'llc', label: 'LLC' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'licensor',
  },
  {
    id: 'licenseeName',
    type: 'text',
    label: 'Licensee Name',
    placeholder: 'Enter licensee name',
    required: true,
    group: 'licensee',
  },
  {
    id: 'licenseeAddress',
    type: 'text',
    label: 'Licensee Address',
    placeholder: 'Enter complete licensee address',
    required: true,
    group: 'licensee',
  },
  {
    id: 'licenseeType',
    type: 'select',
    label: 'Licensee Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'partnership', label: 'Partnership' },
      { value: 'llc', label: 'LLC' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'licensee',
  },
  {
    id: 'licenseDate',
    type: 'date',
    label: 'License Agreement Date',
    required: true,
    group: 'dates',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Effective Date',
    required: true,
    group: 'dates',
  },
  {
    id: 'trademarkName',
    type: 'text',
    label: 'Trademark Name',
    placeholder: 'Enter trademark name/brand',
    required: true,
    group: 'trademark',
  },
  {
    id: 'trademarkDescription',
    type: 'textarea',
    label: 'Trademark Description',
    placeholder: 'Describe the trademark and associated logos/designs',
    required: true,
    group: 'trademark',
  },
  {
    id: 'registrationNumber',
    type: 'text',
    label: 'Registration Number (if registered)',
    placeholder: 'Enter trademark registration number',
    required: false,
    group: 'trademark',
  },
  {
    id: 'registrationDate',
    type: 'date',
    label: 'Registration Date',
    required: false,
    group: 'trademark',
  },
  {
    id: 'trademarkClass',
    type: 'text',
    label: 'Trademark Class(es)',
    placeholder: 'e.g., Class 25 (Clothing)',
    required: false,
    group: 'trademark',
  },
  {
    id: 'licenseType',
    type: 'select',
    label: 'License Type',
    options: [
      { value: 'exclusive', label: 'Exclusive License' },
      { value: 'non-exclusive', label: 'Non-exclusive License' },
      { value: 'sole', label: 'Sole License' },
    ],
    required: true,
    group: 'license-grant',
  },
  {
    id: 'licenseScope',
    type: 'select',
    label: 'License Scope',
    options: [
      { value: 'full-rights', label: 'Full Rights' },
      { value: 'limited-use', label: 'Limited Use' },
      { value: 'specific-products', label: 'Specific Products Only' },
      { value: 'specific-services', label: 'Specific Services Only' },
    ],
    required: true,
    group: 'license-grant',
  },
  {
    id: 'territoryScope',
    type: 'select',
    label: 'Territory Scope',
    options: [
      { value: 'worldwide', label: 'Worldwide' },
      { value: 'united-states', label: 'United States Only' },
      { value: 'specific-states', label: 'Specific States' },
      { value: 'specific-countries', label: 'Specific Countries' },
      { value: 'specific-regions', label: 'Specific Regions' },
    ],
    required: true,
    group: 'territory',
  },
  {
    id: 'specificTerritory',
    type: 'text',
    label: 'Specific Territory',
    placeholder: 'List specific states, countries, or regions',
    required: false,
    group: 'territory',
    dependsOn: 'territoryScope',
  },
  {
    id: 'termType',
    type: 'select',
    label: 'License Term Type',
    options: [
      { value: 'perpetual', label: 'Perpetual' },
      { value: 'fixed-term', label: 'Fixed Term' },
      { value: 'renewable', label: 'Renewable Term' },
      { value: 'at-will', label: 'At-Will' },
    ],
    required: true,
    group: 'term',
  },
  {
    id: 'termLength',
    type: 'text',
    label: 'Term Length',
    placeholder: 'e.g., 5 years',
    required: false,
    group: 'term',
    dependsOn: 'termType',
  },
  {
    id: 'expirationDate',
    type: 'date',
    label: 'Expiration Date',
    required: false,
    group: 'term',
    dependsOn: 'termType',
  },
  {
    id: 'hasRoyalties',
    type: 'checkbox',
    label: 'Include royalty payments',
    required: false,
    group: 'royalties',
  },
  {
    id: 'royaltyType',
    type: 'select',
    label: 'Royalty Type',
    options: [
      { value: 'percentage', label: 'Percentage of Sales' },
      { value: 'flat-fee', label: 'Flat Fee' },
      { value: 'minimum-guarantee', label: 'Minimum Guarantee' },
      { value: 'tiered', label: 'Tiered Structure' },
    ],
    required: false,
    group: 'royalties',
    dependsOn: 'hasRoyalties',
  },
  {
    id: 'royaltyRate',
    type: 'text',
    label: 'Royalty Rate',
    placeholder: 'e.g., 5% of net sales',
    required: false,
    group: 'royalties',
    dependsOn: 'hasRoyalties',
  },
  {
    id: 'minimumRoyalty',
    type: 'text',
    label: 'Minimum Royalty',
    placeholder: 'Minimum payment per period',
    required: false,
    group: 'royalties',
    dependsOn: 'hasRoyalties',
  },
  {
    id: 'upfrontFee',
    type: 'text',
    label: 'Upfront License Fee',
    placeholder: 'Initial payment amount',
    required: false,
    group: 'royalties',
  },
  {
    id: 'paymentFrequency',
    type: 'select',
    label: 'Payment Frequency',
    options: [
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
      { value: 'annually', label: 'Annually' },
      { value: 'upon-sale', label: 'Upon Sale' },
    ],
    required: false,
    group: 'payment-terms',
    dependsOn: 'hasRoyalties',
  },
  {
    id: 'reportingRequirements',
    type: 'checkbox',
    label: 'Require sales reporting',
    required: false,
    group: 'payment-terms',
  },
  {
    id: 'qualityStandards',
    type: 'checkbox',
    label: 'Include quality control standards',
    required: false,
    group: 'quality-control',
  },
  {
    id: 'qualityControlDescription',
    type: 'textarea',
    label: 'Quality Control Description',
    placeholder: 'Describe quality standards and requirements',
    required: false,
    group: 'quality-control',
    dependsOn: 'qualityStandards',
  },
  {
    id: 'inspectionRights',
    type: 'checkbox',
    label: 'Licensor inspection rights',
    required: false,
    group: 'quality-control',
  },
  {
    id: 'approvalRequired',
    type: 'checkbox',
    label: 'Require licensor approval for products',
    required: false,
    group: 'quality-control',
  },
  {
    id: 'advertisingApproval',
    type: 'checkbox',
    label: 'Require approval for advertising',
    required: false,
    group: 'marketing',
  },
  {
    id: 'marketingGuidelines',
    type: 'checkbox',
    label: 'Include marketing guidelines',
    required: false,
    group: 'marketing',
  },
  {
    id: 'brandingRequirements',
    type: 'textarea',
    label: 'Branding Requirements',
    placeholder: 'Describe branding and logo usage requirements',
    required: false,
    group: 'marketing',
  },
  {
    id: 'minimumSalesRequirements',
    type: 'text',
    label: 'Minimum Sales Requirements',
    placeholder: 'e.g., $100,000 annually',
    required: false,
    group: 'performance',
  },
  {
    id: 'sublicensingAllowed',
    type: 'checkbox',
    label: 'Allow sublicensing',
    required: false,
    group: 'sublicensing',
  },
  {
    id: 'sublicenseApproval',
    type: 'checkbox',
    label: 'Require approval for sublicenses',
    required: false,
    group: 'sublicensing',
    dependsOn: 'sublicensingAllowed',
  },
  {
    id: 'assignmentAllowed',
    type: 'checkbox',
    label: 'Allow assignment of license',
    required: false,
    group: 'assignment',
  },
  {
    id: 'terminationForCause',
    type: 'checkbox',
    label: 'Include termination for cause',
    required: false,
    group: 'termination',
  },
  {
    id: 'terminationNotice',
    type: 'text',
    label: 'Termination Notice Period',
    placeholder: 'e.g., 30 days written notice',
    required: false,
    group: 'termination',
  },
  {
    id: 'curePeriod',
    type: 'text',
    label: 'Cure Period',
    placeholder: 'e.g., 30 days to cure breach',
    required: false,
    group: 'termination',
  },
  {
    id: 'discontinueUse',
    type: 'checkbox',
    label: 'Require discontinuation of use upon termination',
    required: false,
    group: 'post-termination',
  },
  {
    id: 'selloffPeriod',
    type: 'text',
    label: 'Sell-off Period',
    placeholder: 'e.g., 90 days to sell existing inventory',
    required: false,
    group: 'post-termination',
  },
  {
    id: 'licenseeIndemnifies',
    type: 'checkbox',
    label: 'Licensee indemnifies licensor',
    required: false,
    group: 'indemnification',
  },
  {
    id: 'requireInsurance',
    type: 'checkbox',
    label: 'Require liability insurance',
    required: false,
    group: 'insurance',
  },
  {
    id: 'insuranceAmount',
    type: 'text',
    label: 'Insurance Amount',
    placeholder: 'Minimum insurance coverage',
    required: false,
    group: 'insurance',
    dependsOn: 'requireInsurance',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law (State)',
    placeholder: 'e.g., State of California',
    required: false,
    group: 'legal',
  },
  {
    id: 'recordWithTrademark',
    type: 'checkbox',
    label: 'Record license with Trademark Office',
    required: false,
    group: 'recordation',
  },
  {
    id: 'requireLicensorSignature',
    type: 'checkbox',
    label: 'Require licensor signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireLicenseeSignature',
    type: 'checkbox',
    label: 'Require licensee signature',
    required: false,
    group: 'signatures',
  },
];
