// src/lib/documents/us/social-media-management-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const socialMediaManagementAgreementQuestions: FormQuestion[] = [
  {
    id: 'providerName',
    type: 'text',
    label: 'Service Provider Name',
    placeholder: 'Enter agency or provider name',
    required: true,
    group: 'provider',
  },
  {
    id: 'providerBusinessName',
    type: 'text',
    label: 'Provider Business Name',
    placeholder: 'Enter business name if different',
    required: false,
    group: 'provider',
  },
  {
    id: 'providerAddress',
    type: 'text',
    label: 'Provider Address',
    placeholder: 'Enter complete business address',
    required: true,
    group: 'provider',
  },
  {
    id: 'providerPhone',
    type: 'text',
    label: 'Provider Phone',
    placeholder: 'Enter phone number',
    required: false,
    group: 'provider',
  },
  {
    id: 'providerEmail',
    type: 'email',
    label: 'Provider Email',
    placeholder: 'Enter email address',
    required: false,
    group: 'provider',
  },
  {
    id: 'providerWebsite',
    type: 'text',
    label: 'Provider Website',
    placeholder: 'Enter website URL',
    required: false,
    group: 'provider',
  },
  {
    id: 'clientName',
    type: 'text',
    label: 'Client Name',
    placeholder: 'Enter client name',
    required: true,
    group: 'client',
  },
  {
    id: 'clientBusinessName',
    type: 'text',
    label: 'Client Business Name',
    placeholder: 'Enter business name',
    required: false,
    group: 'client',
  },
  {
    id: 'clientAddress',
    type: 'text',
    label: 'Client Address',
    placeholder: 'Enter complete address',
    required: true,
    group: 'client',
  },
  {
    id: 'clientPhone',
    type: 'text',
    label: 'Client Phone',
    placeholder: 'Enter phone number',
    required: false,
    group: 'client',
  },
  {
    id: 'clientEmail',
    type: 'email',
    label: 'Client Email',
    placeholder: 'Enter email address',
    required: false,
    group: 'client',
  },
  {
    id: 'clientWebsite',
    type: 'text',
    label: 'Client Website',
    placeholder: 'Enter website URL',
    required: false,
    group: 'client',
  },
  {
    id: 'clientIndustry',
    type: 'text',
    label: 'Client Industry',
    placeholder: 'e.g., Retail, Healthcare, Technology',
    required: false,
    group: 'client',
  },
  {
    id: 'platforms',
    type: 'multiselect',
    label: 'Social Media Platforms',
    options: [
      { value: 'facebook', label: 'Facebook' },
      { value: 'instagram', label: 'Instagram' },
      { value: 'twitter', label: 'Twitter/X' },
      { value: 'linkedin', label: 'LinkedIn' },
      { value: 'youtube', label: 'YouTube' },
      { value: 'tiktok', label: 'TikTok' },
      { value: 'pinterest', label: 'Pinterest' },
      { value: 'snapchat', label: 'Snapchat' },
    ],
    required: false,
    group: 'platforms',
  },
  {
    id: 'existingAccounts',
    type: 'checkbox',
    label: 'Client has existing accounts',
    required: false,
    group: 'platforms',
  },
  {
    id: 'accountSetup',
    type: 'checkbox',
    label: 'Include account setup services',
    required: false,
    group: 'platforms',
  },
  {
    id: 'accountOptimization',
    type: 'checkbox',
    label: 'Include account optimization',
    required: false,
    group: 'platforms',
  },
  {
    id: 'profileManagement',
    type: 'checkbox',
    label: 'Include profile management',
    required: false,
    group: 'platforms',
  },
  {
    id: 'serviceType',
    type: 'select',
    label: 'Service Type',
    options: [
      { value: 'management-only', label: 'Management Only' },
      { value: 'content-creation', label: 'Content Creation Only' },
      { value: 'full-service', label: 'Full Service' },
      { value: 'consulting', label: 'Consulting Only' },
    ],
    required: true,
    group: 'services',
  },
  {
    id: 'includedServices',
    type: 'multiselect',
    label: 'Included Services',
    options: [
      { value: 'content-creation', label: 'Content Creation' },
      { value: 'content-scheduling', label: 'Content Scheduling' },
      { value: 'community-management', label: 'Community Management' },
      { value: 'analytics-reporting', label: 'Analytics & Reporting' },
      { value: 'paid-advertising', label: 'Paid Advertising' },
      { value: 'influencer-outreach', label: 'Influencer Outreach' },
      { value: 'crisis-management', label: 'Crisis Management' },
    ],
    required: false,
    group: 'services',
  },
  {
    id: 'excludedServices',
    type: 'multiselect',
    label: 'Excluded Services',
    options: [
      { value: 'website-development', label: 'Website Development' },
      { value: 'email-marketing', label: 'Email Marketing' },
      { value: 'seo-services', label: 'SEO Services' },
      { value: 'graphic-design', label: 'Graphic Design' },
      { value: 'video-production', label: 'Video Production' },
      { value: 'photography', label: 'Photography' },
    ],
    required: false,
    group: 'services',
  },
  {
    id: 'contentCreation',
    type: 'checkbox',
    label: 'Include content creation',
    required: false,
    group: 'content-services',
  },
  {
    id: 'contentStrategy',
    type: 'checkbox',
    label: 'Include content strategy',
    required: false,
    group: 'content-services',
  },
  {
    id: 'contentCalendar',
    type: 'checkbox',
    label: 'Include content calendar',
    required: false,
    group: 'content-services',
  },
  {
    id: 'originalContent',
    type: 'checkbox',
    label: 'Create original content',
    required: false,
    group: 'content-services',
  },
  {
    id: 'curatedContent',
    type: 'checkbox',
    label: 'Include curated content',
    required: false,
    group: 'content-services',
  },
  {
    id: 'userGeneratedContent',
    type: 'checkbox',
    label: 'Include user-generated content',
    required: false,
    group: 'content-services',
  },
  {
    id: 'textPosts',
    type: 'checkbox',
    label: 'Create text posts',
    required: false,
    group: 'content-types',
  },
  {
    id: 'imageContent',
    type: 'checkbox',
    label: 'Create image content',
    required: false,
    group: 'content-types',
  },
  {
    id: 'videoContent',
    type: 'checkbox',
    label: 'Create video content',
    required: false,
    group: 'content-types',
  },
  {
    id: 'stories',
    type: 'checkbox',
    label: 'Create stories content',
    required: false,
    group: 'content-types',
  },
  {
    id: 'reels',
    type: 'checkbox',
    label: 'Create reels/short videos',
    required: false,
    group: 'content-types',
  },
  {
    id: 'liveStreams',
    type: 'checkbox',
    label: 'Manage live streams',
    required: false,
    group: 'content-types',
  },
  {
    id: 'postsPerWeek',
    type: 'text',
    label: 'Posts Per Week',
    placeholder: 'Number of posts per week',
    required: false,
    group: 'posting-schedule',
  },
  {
    id: 'postsPerMonth',
    type: 'text',
    label: 'Posts Per Month',
    placeholder: 'Number of posts per month',
    required: false,
    group: 'posting-schedule',
  },
  {
    id: 'postingFrequency',
    type: 'select',
    label: 'Posting Frequency',
    options: [
      { value: 'daily', label: 'Daily' },
      { value: 'multiple-daily', label: 'Multiple Times Daily' },
      { value: 'weekly', label: 'Weekly' },
      { value: 'custom', label: 'Custom Schedule' },
    ],
    required: true,
    group: 'posting-schedule',
  },
  {
    id: 'schedulingTool',
    type: 'text',
    label: 'Scheduling Tool',
    placeholder: 'e.g., Hootsuite, Buffer, Later',
    required: false,
    group: 'posting-schedule',
  },
  {
    id: 'optimalTiming',
    type: 'checkbox',
    label: 'Post at optimal times',
    required: false,
    group: 'posting-schedule',
  },
  {
    id: 'communityManagement',
    type: 'checkbox',
    label: 'Include community management',
    required: false,
    group: 'engagement',
  },
  {
    id: 'responseManagement',
    type: 'checkbox',
    label: 'Include response management',
    required: false,
    group: 'engagement',
  },
  {
    id: 'commentModeration',
    type: 'checkbox',
    label: 'Include comment moderation',
    required: false,
    group: 'engagement',
  },
  {
    id: 'directMessageResponse',
    type: 'checkbox',
    label: 'Respond to direct messages',
    required: false,
    group: 'engagement',
  },
  {
    id: 'engagementStrategy',
    type: 'checkbox',
    label: 'Develop engagement strategy',
    required: false,
    group: 'engagement',
  },
  {
    id: 'influencerOutreach',
    type: 'checkbox',
    label: 'Include influencer outreach',
    required: false,
    group: 'engagement',
  },
  {
    id: 'performanceTracking',
    type: 'checkbox',
    label: 'Include performance tracking',
    required: false,
    group: 'analytics',
  },
  {
    id: 'monthlyReports',
    type: 'checkbox',
    label: 'Provide monthly reports',
    required: false,
    group: 'analytics',
  },
  {
    id: 'analyticsTools',
    type: 'text',
    label: 'Analytics Tools',
    placeholder: 'Tools used for analytics',
    required: false,
    group: 'analytics',
  },
  {
    id: 'kpiTracking',
    type: 'multiselect',
    label: 'KPI Tracking',
    options: [
      { value: 'followers', label: 'Follower Growth' },
      { value: 'engagement-rate', label: 'Engagement Rate' },
      { value: 'reach', label: 'Reach' },
      { value: 'impressions', label: 'Impressions' },
      { value: 'clicks', label: 'Clicks' },
      { value: 'conversions', label: 'Conversions' },
      { value: 'mentions', label: 'Brand Mentions' },
    ],
    required: false,
    group: 'analytics',
  },
  {
    id: 'competitorAnalysis',
    type: 'checkbox',
    label: 'Include competitor analysis',
    required: false,
    group: 'analytics',
  },
  {
    id: 'reportingFrequency',
    type: 'select',
    label: 'Reporting Frequency',
    options: [
      { value: 'weekly', label: 'Weekly' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
    ],
    required: true,
    group: 'analytics',
  },
  {
    id: 'paidAdvertising',
    type: 'checkbox',
    label: 'Include paid advertising',
    required: false,
    group: 'advertising',
  },
  {
    id: 'adCampaignManagement',
    type: 'checkbox',
    label: 'Include ad campaign management',
    required: false,
    group: 'advertising',
  },
  {
    id: 'adCreativeDesign',
    type: 'checkbox',
    label: 'Include ad creative design',
    required: false,
    group: 'advertising',
  },
  {
    id: 'budgetManagement',
    type: 'checkbox',
    label: 'Include budget management',
    required: false,
    group: 'advertising',
  },
  {
    id: 'adSpendLimit',
    type: 'text',
    label: 'Ad Spend Limit',
    placeholder: 'Monthly ad spend limit',
    required: false,
    group: 'advertising',
  },
  {
    id: 'roiTracking',
    type: 'checkbox',
    label: 'Include ROI tracking',
    required: false,
    group: 'advertising',
  },
  {
    id: 'brandGuidelinesProvided',
    type: 'checkbox',
    label: 'Brand guidelines provided by client',
    required: false,
    group: 'brand',
  },
  {
    id: 'brandVoice',
    type: 'text',
    label: 'Brand Voice',
    placeholder: 'Describe brand voice and tone',
    required: false,
    group: 'brand',
  },
  {
    id: 'visualIdentity',
    type: 'text',
    label: 'Visual Identity',
    placeholder: 'Describe visual identity guidelines',
    required: false,
    group: 'brand',
  },
  {
    id: 'contentApprovalRequired',
    type: 'checkbox',
    label: 'Content approval required',
    required: false,
    group: 'brand',
  },
  {
    id: 'brandCompliance',
    type: 'checkbox',
    label: 'Ensure brand compliance',
    required: false,
    group: 'brand',
  },
  {
    id: 'approvalProcess',
    type: 'select',
    label: 'Approval Process',
    options: [
      { value: 'pre-approval', label: 'Pre-approval Required' },
      { value: 'post-approval', label: 'Post-approval' },
      { value: 'no-approval', label: 'No Approval Needed' },
    ],
    required: true,
    group: 'approval',
  },
  {
    id: 'approvalTimeframe',
    type: 'text',
    label: 'Approval Timeframe',
    placeholder: 'Time allowed for client approval',
    required: false,
    group: 'approval',
  },
  {
    id: 'revisionRounds',
    type: 'text',
    label: 'Revision Rounds',
    placeholder: 'Number of revision rounds included',
    required: false,
    group: 'approval',
  },
  {
    id: 'emergencyPostingRights',
    type: 'checkbox',
    label: 'Emergency posting rights',
    required: false,
    group: 'approval',
  },
  {
    id: 'pricingModel',
    type: 'select',
    label: 'Pricing Model',
    options: [
      { value: 'monthly-retainer', label: 'Monthly Retainer' },
      { value: 'hourly', label: 'Hourly Rate' },
      { value: 'per-post', label: 'Per Post' },
      { value: 'performance-based', label: 'Performance Based' },
    ],
    required: true,
    group: 'pricing',
  },
  {
    id: 'monthlyRetainer',
    type: 'text',
    label: 'Monthly Retainer',
    placeholder: 'Monthly retainer amount',
    required: false,
    group: 'pricing',
    dependsOn: 'pricingModel',
  },
  {
    id: 'hourlyRate',
    type: 'text',
    label: 'Hourly Rate',
    placeholder: 'Hourly rate amount',
    required: false,
    group: 'pricing',
    dependsOn: 'pricingModel',
  },
  {
    id: 'perPostRate',
    type: 'text',
    label: 'Per Post Rate',
    placeholder: 'Rate per post',
    required: false,
    group: 'pricing',
    dependsOn: 'pricingModel',
  },
  {
    id: 'setupFee',
    type: 'text',
    label: 'Setup Fee',
    placeholder: 'One-time setup fee',
    required: false,
    group: 'pricing',
  },
  {
    id: 'additionalServiceFees',
    type: 'checkbox',
    label: 'Additional service fees apply',
    required: false,
    group: 'pricing',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
      { value: 'advance', label: 'In Advance' },
    ],
    required: true,
    group: 'payment',
  },
  {
    id: 'paymentDueDate',
    type: 'text',
    label: 'Payment Due Date',
    placeholder: 'e.g., 1st of each month',
    required: false,
    group: 'payment',
  },
  {
    id: 'latePaymentFees',
    type: 'checkbox',
    label: 'Include late payment fees',
    required: false,
    group: 'payment',
  },
  {
    id: 'expenseReimbursement',
    type: 'checkbox',
    label: 'Include expense reimbursement',
    required: false,
    group: 'payment',
  },
  {
    id: 'accountLoginProvision',
    type: 'checkbox',
    label: 'Client provides account login access',
    required: false,
    group: 'access',
  },
  {
    id: 'adminAccess',
    type: 'checkbox',
    label: 'Provider gets admin access',
    required: false,
    group: 'access',
  },
  {
    id: 'businessManagerAccess',
    type: 'checkbox',
    label: 'Business manager access provided',
    required: false,
    group: 'access',
  },
  {
    id: 'passwordSecurity',
    type: 'checkbox',
    label: 'Maintain password security',
    required: false,
    group: 'access',
  },
  {
    id: 'accessRevocation',
    type: 'checkbox',
    label: 'Access can be revoked',
    required: false,
    group: 'access',
  },
  {
    id: 'followerGrowthGoals',
    type: 'text',
    label: 'Follower Growth Goals',
    placeholder: 'Target follower growth',
    required: false,
    group: 'performance',
  },
  {
    id: 'engagementGoals',
    type: 'text',
    label: 'Engagement Goals',
    placeholder: 'Target engagement rate',
    required: false,
    group: 'performance',
  },
  {
    id: 'reachGoals',
    type: 'text',
    label: 'Reach Goals',
    placeholder: 'Target reach metrics',
    required: false,
    group: 'performance',
  },
  {
    id: 'conversionGoals',
    type: 'text',
    label: 'Conversion Goals',
    placeholder: 'Target conversion metrics',
    required: false,
    group: 'performance',
  },
  {
    id: 'performanceGuarantees',
    type: 'checkbox',
    label: 'Include performance guarantees',
    required: false,
    group: 'performance',
  },
  {
    id: 'communicationMethod',
    type: 'select',
    label: 'Primary Communication Method',
    options: [
      { value: 'email', label: 'Email' },
      { value: 'phone', label: 'Phone' },
      { value: 'slack', label: 'Slack' },
      { value: 'project-management', label: 'Project Management Tool' },
    ],
    required: true,
    group: 'communication',
  },
  {
    id: 'responseTimeframe',
    type: 'text',
    label: 'Response Timeframe',
    placeholder: 'Expected response time',
    required: false,
    group: 'communication',
  },
  {
    id: 'meetingFrequency',
    type: 'select',
    label: 'Meeting Frequency',
    options: [
      { value: 'weekly', label: 'Weekly' },
      { value: 'bi-weekly', label: 'Bi-weekly' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
    ],
    required: true,
    group: 'communication',
  },
  {
    id: 'emergencyContact',
    type: 'checkbox',
    label: 'Provide emergency contact',
    required: false,
    group: 'communication',
  },
  {
    id: 'confidentialityClause',
    type: 'checkbox',
    label: 'Include confidentiality clause',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'ndaRequired',
    type: 'checkbox',
    label: 'Require separate NDA',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'proprietaryInformation',
    type: 'checkbox',
    label: 'Protect proprietary information',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'clientDataProtection',
    type: 'checkbox',
    label: 'Include client data protection',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'contractTerm',
    type: 'text',
    label: 'Contract Term',
    placeholder: 'Length of contract',
    required: false,
    group: 'term',
  },
  {
    id: 'automaticRenewal',
    type: 'checkbox',
    label: 'Include automatic renewal',
    required: false,
    group: 'term',
  },
  {
    id: 'terminationNotice',
    type: 'text',
    label: 'Termination Notice',
    placeholder: 'Required notice for termination',
    required: false,
    group: 'term',
  },
  {
    id: 'accountTransfer',
    type: 'checkbox',
    label: 'Transfer account access upon termination',
    required: false,
    group: 'term',
  },
  {
    id: 'liabilityLimitation',
    type: 'checkbox',
    label: 'Include liability limitation',
    required: false,
    group: 'liability',
  },
  {
    id: 'liabilityAmount',
    type: 'text',
    label: 'Liability Limitation Amount',
    placeholder: 'Maximum liability amount',
    required: false,
    group: 'liability',
    dependsOn: 'liabilityLimitation',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'negotiation', label: 'Negotiation' },
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'litigation', label: 'Court Litigation' },
    ],
    required: false,
    group: 'legal',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'e.g., State of California',
    required: false,
    group: 'legal',
  },
  {
    id: 'jurisdiction',
    type: 'text',
    label: 'Jurisdiction',
    placeholder: 'Where disputes will be resolved',
    required: false,
    group: 'legal',
  },
  {
    id: 'requireProviderSignature',
    type: 'checkbox',
    label: 'Require provider signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireClientSignature',
    type: 'checkbox',
    label: 'Require client signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'witnessRequired',
    type: 'checkbox',
    label: 'Require witness',
    required: false,
    group: 'signatures',
  },
  {
    id: 'notarizationRequired',
    type: 'checkbox',
    label: 'Require notarization',
    required: false,
    group: 'signatures',
  },
  {
    id: 'electronicSignatureAccepted',
    type: 'checkbox',
    label: 'Accept electronic signatures',
    required: false,
    group: 'signatures',
  },
];