// src/lib/documents/us/codicil-to-will/questions.ts
import type { FormQuestion } from '@/types/documents';

export const codicilToWillQuestions: FormQuestion[] = [
  {
    id: 'testatorName',
    type: 'text',
    label: 'Your Full Legal Name',
    placeholder: 'Enter your full legal name',
    required: true,
    group: 'testator',
  },
  {
    id: 'testatorAddress',
    type: 'textarea',
    label: 'Your Address',
    placeholder: 'Enter your complete address',
    required: true,
    group: 'testator',
  },
  {
    id: 'testatorCounty',
    type: 'text',
    label: 'County',
    placeholder: 'Enter your county',
    required: true,
    group: 'testator',
  },
  {
    id: 'testatorState',
    type: 'text',
    label: 'State',
    placeholder: 'Enter your state',
    required: true,
    group: 'testator',
  },
  {
    id: 'originalWillDate',
    type: 'date',
    label: 'Date of Original Will',
    required: true,
    group: 'original-will',
  },
  {
    id: 'originalWillLocation',
    type: 'text',
    label: 'Location Where Original Will is Kept',
    placeholder: 'e.g., Safe deposit box, Attorney office',
    required: false,
    group: 'original-will',
  },
  {
    id: 'amendmentType',
    type: 'select',
    label: 'Type of Amendment',
    options: [
      { value: 'addition', label: 'Add New Provision' },
      { value: 'deletion', label: 'Delete Existing Provision' },
      { value: 'modification', label: 'Modify Existing Provision' },
      { value: 'revocation', label: 'Revoke Specific Provision' },
    ],
    required: true,
    group: 'amendment',
  },
  {
    id: 'amendmentDescription',
    type: 'textarea',
    label: 'Description of Amendment',
    placeholder: 'Clearly describe what you want to change, add, or remove',
    required: true,
    group: 'amendment',
  },
  {
    id: 'specificClause',
    type: 'textarea',
    label: 'Specific Clause Reference',
    placeholder: 'Reference the specific section or clause being amended',
    required: false,
    group: 'amendment',
  },
  {
    id: 'newProvisions',
    type: 'textarea',
    label: 'New Provisions to Add',
    placeholder: 'Enter the exact text of new provisions',
    required: false,
    group: 'additions',
  },
  {
    id: 'beneficiaryChanges',
    type: 'textarea',
    label: 'Beneficiary Changes',
    placeholder: 'Describe changes to beneficiaries or their shares',
    required: false,
    group: 'beneficiaries',
  },
  {
    id: 'newBeneficiaryName',
    type: 'text',
    label: 'New Beneficiary Name',
    placeholder: 'Full name of new beneficiary',
    required: false,
    group: 'beneficiaries',
  },
  {
    id: 'newBeneficiaryRelationship',
    type: 'text',
    label: 'New Beneficiary Relationship',
    placeholder: 'e.g., daughter, friend, charity',
    required: false,
    group: 'beneficiaries',
  },
  {
    id: 'newBeneficiaryShare',
    type: 'text',
    label: 'New Beneficiary Share',
    placeholder: 'e.g., 25%, $10,000, specific item',
    required: false,
    group: 'beneficiaries',
  },
  {
    id: 'executorChanges',
    type: 'checkbox',
    label: 'I want to change my executor',
    required: false,
    group: 'executor',
  },
  {
    id: 'newExecutorName',
    type: 'text',
    label: 'New Executor Name',
    placeholder: 'Full name of new executor',
    required: false,
    group: 'executor',
    dependsOn: 'executorChanges',
  },
  {
    id: 'newExecutorAddress',
    type: 'textarea',
    label: 'New Executor Address',
    placeholder: 'Complete address of new executor',
    required: false,
    group: 'executor',
    dependsOn: 'executorChanges',
  },
  {
    id: 'newExecutorRelationship',
    type: 'text',
    label: 'New Executor Relationship',
    placeholder: 'e.g., son, attorney, friend',
    required: false,
    group: 'executor',
    dependsOn: 'executorChanges',
  },
  {
    id: 'guardianChanges',
    type: 'checkbox',
    label: 'I want to change the guardian for my minor children',
    required: false,
    group: 'guardian',
  },
  {
    id: 'newGuardianName',
    type: 'text',
    label: 'New Guardian Name',
    placeholder: 'Full name of new guardian',
    required: false,
    group: 'guardian',
    dependsOn: 'guardianChanges',
  },
  {
    id: 'newGuardianAddress',
    type: 'textarea',
    label: 'New Guardian Address',
    placeholder: 'Complete address of new guardian',
    required: false,
    group: 'guardian',
    dependsOn: 'guardianChanges',
  },
  {
    id: 'revocationDetails',
    type: 'textarea',
    label: 'Provisions to Revoke',
    placeholder: 'Specify which provisions of the original will to revoke',
    required: false,
    group: 'revocation',
  },
  {
    id: 'confirmRemainingTerms',
    type: 'checkbox',
    label: 'All other terms of my original will remain in full force and effect',
    required: false,
    group: 'confirmation',
  },
];