// src/lib/documents/us/affidavit-of-death/questions.ts
import type { Question } from '@/types/documents';

export const questions: Question[] = [
  // Section 1: Deceased Person Information
  {
    id: 'decedentName',
    type: 'text',
    label: "Deceased Person's Full Legal Name",
    required: true,
    section: 'Deceased Person Information',
    placeholder: "Enter the deceased person's full legal name",
  },
  {
    id: 'decedentDateOfDeath',
    type: 'date',
    label: 'Date of Death',
    required: true,
    section: 'Deceased Person Information',
  },
  {
    id: 'decedentPlaceOfDeath',
    type: 'text',
    label: 'Place of Death',
    required: true,
    section: 'Deceased Person Information',
    placeholder: 'e.g., Hospital name, City, State OR Home address',
    description: 'Include specific location where death occurred.',
  },
  {
    id: 'decedentDateOfBirth',
    type: 'date',
    label: 'Date of Birth',
    required: true,
    section: 'Deceased Person Information',
  },
  {
    id: 'decedentAddress',
    type: 'text',
    label: "Deceased Person's Last Known Address",
    required: true,
    section: 'Deceased Person Information',
    placeholder: "Enter the deceased person's street address",
  },
  {
    id: 'decedentCity',
    type: 'text',
    label: 'City',
    required: true,
    section: 'Deceased Person Information',
    placeholder: "Enter the deceased person's city",
  },
  {
    id: 'decedentState',
    type: 'select',
    label: 'State',
    required: true,
    section: 'Deceased Person Information',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
  },
  {
    id: 'decedentZip',
    type: 'text',
    label: 'ZIP Code',
    required: true,
    section: 'Deceased Person Information',
    placeholder: "Enter the deceased person's ZIP code",
  },
  {
    id: 'decedentSSN',
    type: 'text',
    label: "Deceased Person's Social Security Number",
    required: true,
    section: 'Deceased Person Information',
    placeholder: 'XXX-XX-XXXX',
    description: 'Required for verification purposes.',
  },

  // Section 2: Affiant Information
  {
    id: 'affiantName',
    type: 'text',
    label: 'Your Full Legal Name',
    required: true,
    section: 'Affiant Information',
    placeholder: 'Enter your full legal name',
    description: 'You are the person making this affidavit.',
  },
  {
    id: 'affiantAddress',
    type: 'text',
    label: 'Your Street Address',
    required: true,
    section: 'Affiant Information',
    placeholder: 'Enter your street address',
  },
  {
    id: 'affiantCity',
    type: 'text',
    label: 'Your City',
    required: true,
    section: 'Affiant Information',
    placeholder: 'Enter your city',
  },
  {
    id: 'affiantState',
    type: 'select',
    label: 'Your State',
    required: true,
    section: 'Affiant Information',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
  },
  {
    id: 'affiantZip',
    type: 'text',
    label: 'Your ZIP Code',
    required: true,
    section: 'Affiant Information',
    placeholder: 'Enter your ZIP code',
  },
  {
    id: 'affiantPhone',
    type: 'text',
    label: 'Your Phone Number',
    required: true,
    section: 'Affiant Information',
    placeholder: 'Enter your phone number',
  },
  {
    id: 'affiantRelationship',
    type: 'text',
    label: 'Your Relationship to the Deceased',
    required: true,
    section: 'Affiant Information',
    placeholder: 'e.g., Spouse, Child, Sibling, Friend, Executor',
  },

  // Section 3: Purpose of Affidavit
  {
    id: 'purposeOfAffidavit',
    type: 'textarea',
    label: 'Purpose of This Affidavit',
    required: true,
    section: 'Purpose of Affidavit',
    placeholder:
      'Explain why you need this affidavit of death (e.g., to close bank accounts, transfer property, collect benefits, etc.)',
    description: 'Describe the specific reason why this affidavit is needed.',
  },
  {
    id: 'specificInstitution',
    type: 'text',
    label: 'Specific Institution or Organization',
    required: false,
    section: 'Purpose of Affidavit',
    placeholder:
      'e.g., First National Bank, Social Security Administration, Insurance Company',
    description: 'Name the specific institution that requires this affidavit.',
  },
  {
    id: 'institutionAddress',
    type: 'text',
    label: 'Institution Address',
    required: false,
    section: 'Purpose of Affidavit',
    placeholder: 'Enter the institution address',
  },
  {
    id: 'urgentRequest',
    type: 'radio',
    label: 'Is this an urgent request?',
    required: true,
    section: 'Purpose of Affidavit',
    options: [
      { value: 'true', label: 'Yes, this is urgent' },
      { value: 'false', label: 'No, this is not urgent' },
    ],
  },
  {
    id: 'urgentReason',
    type: 'textarea',
    label: 'Reason for Urgency',
    required: false,
    section: 'Purpose of Affidavit',
    placeholder: 'Explain why this affidavit is needed urgently...',
    condition: { field: 'urgentRequest', value: 'true' },
  },

  // Section 4: Death Certificate Information
  {
    id: 'deathCertificateAttached',
    type: 'radio',
    label: 'Do you have a certified death certificate?',
    required: true,
    section: 'Death Certificate Information',
    options: [
      { value: 'true', label: 'Yes, I have a certified death certificate' },
      {
        value: 'false',
        label: 'No, I do not have a certified death certificate',
      },
    ],
    description:
      'A certified death certificate is the preferred proof of death.',
  },
  {
    id: 'deathCertificateNumber',
    type: 'text',
    label: 'Death Certificate Number',
    required: false,
    section: 'Death Certificate Information',
    placeholder: 'Enter death certificate number',
    condition: { field: 'deathCertificateAttached', value: 'true' },
  },
  {
    id: 'deathCertificateIssuer',
    type: 'text',
    label: 'Death Certificate Issuing Authority',
    required: false,
    section: 'Death Certificate Information',
    placeholder: 'e.g., County Health Department, State Vital Records',
    condition: { field: 'deathCertificateAttached', value: 'true' },
  },
  {
    id: 'deathCertificateDate',
    type: 'date',
    label: 'Death Certificate Issue Date',
    required: false,
    section: 'Death Certificate Information',
    condition: { field: 'deathCertificateAttached', value: 'true' },
  },

  // Section 5: Circumstances of Death (if no death certificate)
  {
    id: 'causeOfDeath',
    type: 'text',
    label: 'Cause of Death',
    required: false,
    section: 'Circumstances of Death',
    placeholder: 'Enter cause of death (if known)',
    condition: { field: 'deathCertificateAttached', value: 'false' },
  },
  {
    id: 'deathCircumstances',
    type: 'textarea',
    label: 'Circumstances of Death',
    required: false,
    section: 'Circumstances of Death',
    placeholder: 'Describe the circumstances surrounding the death...',
    condition: { field: 'deathCertificateAttached', value: 'false' },
  },
  {
    id: 'attendingPhysician',
    type: 'text',
    label: 'Attending Physician',
    required: false,
    section: 'Circumstances of Death',
    placeholder: 'Enter name of attending physician',
    condition: { field: 'deathCertificateAttached', value: 'false' },
  },
  {
    id: 'hospitalOrLocation',
    type: 'text',
    label: 'Hospital or Medical Facility',
    required: false,
    section: 'Circumstances of Death',
    placeholder: 'Enter hospital or medical facility name',
    condition: { field: 'deathCertificateAttached', value: 'false' },
  },
  {
    id: 'lastSeenAlive',
    type: 'date',
    label: 'When was the deceased last seen alive?',
    required: false,
    section: 'Circumstances of Death',
    condition: { field: 'deathCertificateAttached', value: 'false' },
  },
  {
    id: 'lastSeenAliveBy',
    type: 'text',
    label: 'Who last saw the deceased alive?',
    required: false,
    section: 'Circumstances of Death',
    placeholder: 'Enter name and relationship',
    condition: { field: 'deathCertificateAttached', value: 'false' },
  },
  {
    id: 'medicalConditions',
    type: 'textarea',
    label: 'Known Medical Conditions',
    required: false,
    section: 'Circumstances of Death',
    placeholder: 'Describe any known medical conditions...',
    condition: { field: 'deathCertificateAttached', value: 'false' },
  },

  // Section 6: Witnesses (if no death certificate)
  {
    id: 'hasWitnesses',
    type: 'radio',
    label: 'Are there witnesses to the death or who can verify the death?',
    required: false,
    section: 'Witnesses',
    options: [
      { value: 'true', label: 'Yes, there are witnesses' },
      { value: 'false', label: 'No, there are no witnesses' },
    ],
    condition: { field: 'deathCertificateAttached', value: 'false' },
  },
  {
    id: 'witnesses',
    type: 'array',
    label: 'Witnesses',
    required: false,
    section: 'Witnesses',
    condition: { field: 'hasWitnesses', value: 'true' },
    description:
      'List people who witnessed the death or can verify the death occurred.',
    arrayConfig: {
      minItems: 1,
      maxItems: 5,
      fields: [
        {
          id: 'name',
          type: 'text',
          label: 'Witness Name',
          required: true,
          placeholder: 'Enter witness full name',
        },
        {
          id: 'address',
          type: 'text',
          label: 'Witness Address',
          required: true,
          placeholder: 'Enter witness address',
        },
        {
          id: 'relationship',
          type: 'text',
          label: 'Relationship to Deceased',
          required: true,
          placeholder: 'e.g., Family member, Friend, Nurse, Doctor',
        },
        {
          id: 'phone',
          type: 'text',
          label: 'Phone Number',
          required: false,
          placeholder: 'Enter phone number',
        },
      ],
    },
  },

  // Section 7: Family Information
  {
    id: 'survivingSpouse',
    type: 'text',
    label: 'Surviving Spouse (if any)',
    required: false,
    section: 'Family Information',
    placeholder: 'Enter surviving spouse full name',
  },
  {
    id: 'spouseAddress',
    type: 'text',
    label: 'Surviving Spouse Address',
    required: false,
    section: 'Family Information',
    placeholder: 'Enter surviving spouse address',
    condition: { field: 'survivingSpouse', value: '!empty' },
  },
  {
    id: 'children',
    type: 'array',
    label: 'Children of the Deceased',
    required: false,
    section: 'Family Information',
    description: 'List any children of the deceased.',
    arrayConfig: {
      minItems: 0,
      maxItems: 10,
      fields: [
        {
          id: 'name',
          type: 'text',
          label: 'Child Name',
          required: true,
          placeholder: 'Enter child full name',
        },
        {
          id: 'address',
          type: 'text',
          label: 'Child Address',
          required: false,
          placeholder: 'Enter child address',
        },
        {
          id: 'age',
          type: 'text',
          label: 'Age',
          required: false,
          placeholder: 'Enter age',
        },
      ],
    },
  },

  // Section 8: Funeral Information
  {
    id: 'funeralHome',
    type: 'text',
    label: 'Funeral Home',
    required: false,
    section: 'Funeral Information',
    placeholder: 'Enter funeral home name',
  },
  {
    id: 'funeralHomeAddress',
    type: 'text',
    label: 'Funeral Home Address',
    required: false,
    section: 'Funeral Information',
    placeholder: 'Enter funeral home address',
  },
  {
    id: 'funeralDate',
    type: 'date',
    label: 'Funeral Date',
    required: false,
    section: 'Funeral Information',
  },
  {
    id: 'burialPlace',
    type: 'text',
    label: 'Burial Place',
    required: false,
    section: 'Funeral Information',
    placeholder: 'Enter cemetery or burial location',
  },
  {
    id: 'burialDate',
    type: 'date',
    label: 'Burial Date',
    required: false,
    section: 'Funeral Information',
  },

  // Section 9: Assets/Property Information
  {
    id: 'assetsInvolved',
    type: 'radio',
    label: 'Are there specific assets or property involved?',
    required: true,
    section: 'Assets Information',
    options: [
      { value: 'true', label: 'Yes, there are specific assets' },
      { value: 'false', label: 'No, this is a general affidavit of death' },
    ],
  },
  {
    id: 'assetDescription',
    type: 'textarea',
    label: 'Description of Assets',
    required: false,
    section: 'Assets Information',
    placeholder: 'Describe the assets or property involved...',
    condition: { field: 'assetsInvolved', value: 'true' },
  },
  {
    id: 'assetValue',
    type: 'text',
    label: 'Estimated Value of Assets',
    required: false,
    section: 'Assets Information',
    placeholder: 'e.g., $50,000',
    condition: { field: 'assetsInvolved', value: 'true' },
  },

  // Section 10: Additional Information
  {
    id: 'additionalInformation',
    type: 'textarea',
    label: 'Additional Information',
    required: false,
    section: 'Additional Information',
    placeholder:
      'Provide any additional relevant information about the death or circumstances...',
    description:
      'Include any other information that supports the fact of death.',
  },

  // Section 11: Legal Information
  {
    id: 'state',
    type: 'select',
    label: 'State Where This Affidavit Will Be Used',
    required: true,
    section: 'Legal Information',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
    description: 'Select the state where this affidavit will be used.',
  },
  {
    id: 'county',
    type: 'text',
    label: 'County',
    required: true,
    section: 'Legal Information',
    placeholder: 'Enter the county name',
  },
  {
    id: 'dateCreated',
    type: 'date',
    label: 'Date of Creation',
    required: true,
    section: 'Legal Information',
    description: 'The date this affidavit is being created.',
  },

  // Section 12: Notarization
  {
    id: 'notaryName',
    type: 'text',
    label: 'Notary Public Name',
    required: false,
    section: 'Notarization',
    placeholder: 'Enter notary public name',
    description: 'This will be filled when the document is notarized.',
  },
  {
    id: 'notaryCommissionExpires',
    type: 'date',
    label: 'Notary Commission Expires',
    required: false,
    section: 'Notarization',
    description: 'This will be filled when the document is notarized.',
  },
];
