// src/lib/documents/us/child-support-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const childSupportAgreementQuestions: FormQuestion[] = [
  {
    id: 'obligorName',
    type: 'text',
    label: 'Obligor Name (Paying Parent)',
    placeholder: 'Enter name of parent paying support',
    required: true,
    group: 'obligor',
  },
  {
    id: 'obligorAddress',
    type: 'text',
    label: 'Obligor Address',
    placeholder: 'Enter complete address of paying parent',
    required: true,
    group: 'obligor',
  },
  {
    id: 'obligorPhone',
    type: 'text',
    label: 'Obligor Phone Number',
    placeholder: 'Enter phone number',
    required: false,
    group: 'obligor',
  },
  {
    id: 'obligorEmployer',
    type: 'text',
    label: 'Obligor Employer',
    placeholder: 'Enter employer name',
    required: false,
    group: 'obligor',
  },
  {
    id: 'obligeeName',
    type: 'text',
    label: 'Obligee Name (Receiving Parent)',
    placeholder: 'Enter name of parent receiving support',
    required: true,
    group: 'obligee',
  },
  {
    id: 'obligeeAddress',
    type: 'text',
    label: 'Obligee Address',
    placeholder: 'Enter complete address of receiving parent',
    required: true,
    group: 'obligee',
  },
  {
    id: 'obligeePhone',
    type: 'text',
    label: 'Obligee Phone Number',
    placeholder: 'Enter phone number',
    required: false,
    group: 'obligee',
  },
  {
    id: 'childName',
    type: 'text',
    label: 'Child Name',
    placeholder: 'Enter child full name',
    required: true,
    group: 'child',
  },
  {
    id: 'childBirthDate',
    type: 'date',
    label: 'Child Birth Date',
    required: true,
    group: 'child',
  },
  {
    id: 'hasMultipleChildren',
    type: 'checkbox',
    label: 'Multiple children covered by this agreement',
    required: false,
    group: 'child',
  },
  {
    id: 'agreementDate',
    type: 'date',
    label: 'Agreement Date',
    required: true,
    group: 'agreement-details',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Effective Date',
    required: true,
    group: 'agreement-details',
  },
  {
    id: 'supportAmount',
    type: 'text',
    label: 'Support Amount',
    placeholder: 'Enter support amount per payment period',
    required: true,
    group: 'support-amount',
  },
  {
    id: 'paymentFrequency',
    type: 'select',
    label: 'Payment Frequency',
    options: [
      { value: 'weekly', label: 'Weekly' },
      { value: 'bi-weekly', label: 'Bi-weekly' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'support-amount',
  },
  {
    id: 'paymentDueDate',
    type: 'text',
    label: 'Payment Due Date',
    placeholder: 'e.g., 1st of each month, every Friday',
    required: true,
    group: 'support-amount',
  },
  {
    id: 'paymentMethod',
    type: 'select',
    label: 'Payment Method',
    options: [
      { value: 'direct-payment', label: 'Direct Payment' },
      { value: 'wage-garnishment', label: 'Wage Garnishment' },
      { value: 'state-disbursement', label: 'State Disbursement Unit' },
      { value: 'automatic-transfer', label: 'Automatic Bank Transfer' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'payment-method',
  },
  {
    id: 'paymentDetails',
    type: 'text',
    label: 'Payment Details',
    placeholder: 'Provide additional payment details if needed',
    required: false,
    group: 'payment-method',
  },
  {
    id: 'obligorIncome',
    type: 'text',
    label: 'Obligor Income',
    placeholder: 'Annual or monthly income',
    required: false,
    group: 'income',
  },
  {
    id: 'obligeeIncome',
    type: 'text',
    label: 'Obligee Income',
    placeholder: 'Annual or monthly income',
    required: false,
    group: 'income',
  },
  {
    id: 'childCareExpenses',
    type: 'checkbox',
    label: 'Include child care expenses',
    required: false,
    group: 'additional-expenses',
  },
  {
    id: 'childCareAmount',
    type: 'text',
    label: 'Child Care Amount',
    placeholder: 'Monthly child care costs',
    required: false,
    group: 'additional-expenses',
    dependsOn: 'childCareExpenses',
  },
  {
    id: 'childCareResponsibility',
    type: 'select',
    label: 'Child Care Payment Responsibility',
    options: [
      { value: 'obligor', label: 'Obligor Pays' },
      { value: 'obligee', label: 'Obligee Pays' },
      { value: 'shared', label: 'Shared Responsibility' },
    ],
    required: false,
    group: 'additional-expenses',
    dependsOn: 'childCareExpenses',
  },
  {
    id: 'healthInsurance',
    type: 'checkbox',
    label: 'Include health insurance provisions',
    required: false,
    group: 'health-medical',
  },
  {
    id: 'healthInsuranceProvider',
    type: 'select',
    label: 'Health Insurance Provider',
    options: [
      { value: 'obligor', label: 'Obligor Provides' },
      { value: 'obligee', label: 'Obligee Provides' },
      { value: 'shared', label: 'Shared Responsibility' },
    ],
    required: false,
    group: 'health-medical',
    dependsOn: 'healthInsurance',
  },
  {
    id: 'uninsuredMedical',
    type: 'select',
    label: 'Uninsured Medical Expenses',
    options: [
      { value: 'obligor', label: 'Obligor Pays' },
      { value: 'obligee', label: 'Obligee Pays' },
      { value: 'shared', label: 'Shared Responsibility' },
    ],
    required: false,
    group: 'health-medical',
  },
  {
    id: 'educationalExpenses',
    type: 'checkbox',
    label: 'Include educational expenses',
    required: false,
    group: 'education',
  },
  {
    id: 'educationResponsibility',
    type: 'select',
    label: 'Educational Expense Responsibility',
    options: [
      { value: 'obligor', label: 'Obligor Pays' },
      { value: 'obligee', label: 'Obligee Pays' },
      { value: 'shared', label: 'Shared Responsibility' },
    ],
    required: false,
    group: 'education',
    dependsOn: 'educationalExpenses',
  },
  {
    id: 'collegeExpenses',
    type: 'checkbox',
    label: 'Include college/higher education expenses',
    required: false,
    group: 'education',
  },
  {
    id: 'extracurricularExpenses',
    type: 'checkbox',
    label: 'Include extracurricular activity expenses',
    required: false,
    group: 'extracurricular',
  },
  {
    id: 'extracurricularResponsibility',
    type: 'select',
    label: 'Extracurricular Expense Responsibility',
    options: [
      { value: 'obligor', label: 'Obligor Pays' },
      { value: 'obligee', label: 'Obligee Pays' },
      { value: 'shared', label: 'Shared Responsibility' },
    ],
    required: false,
    group: 'extracurricular',
    dependsOn: 'extracurricularExpenses',
  },
  {
    id: 'supportDuration',
    type: 'select',
    label: 'Support Duration/Termination',
    options: [
      { value: 'age-18', label: 'Until Child Reaches Age 18' },
      { value: 'age-19', label: 'Until Child Reaches Age 19' },
      { value: 'high-school-graduation', label: 'Until High School Graduation' },
      { value: 'college-graduation', label: 'Until College Graduation' },
      { value: 'specific-date', label: 'Until Specific Date' },
      { value: 'court-order', label: 'Until Court Order' },
    ],
    required: true,
    group: 'duration',
  },
  {
    id: 'terminationDate',
    type: 'date',
    label: 'Specific Termination Date',
    required: false,
    group: 'duration',
    dependsOn: 'supportDuration',
  },
  {
    id: 'modificationClause',
    type: 'checkbox',
    label: 'Include modification clause',
    required: false,
    group: 'modification',
  },
  {
    id: 'automaticAdjustment',
    type: 'checkbox',
    label: 'Include automatic cost-of-living adjustments',
    required: false,
    group: 'modification',
  },
  {
    id: 'latePaymentPenalty',
    type: 'checkbox',
    label: 'Include late payment penalties',
    required: false,
    group: 'enforcement',
  },
  {
    id: 'interestOnArrears',
    type: 'text',
    label: 'Interest Rate on Arrears',
    placeholder: 'e.g., 10% per year',
    required: false,
    group: 'enforcement',
  },
  {
    id: 'taxDependencyExemption',
    type: 'select',
    label: 'Tax Dependency Exemption',
    options: [
      { value: 'obligor', label: 'Obligor Claims' },
      { value: 'obligee', label: 'Obligee Claims' },
      { value: 'alternating', label: 'Alternating Years' },
      { value: 'shared', label: 'Shared/Split' },
    ],
    required: false,
    group: 'tax',
  },
  {
    id: 'lifeInsurance',
    type: 'checkbox',
    label: 'Require life insurance',
    required: false,
    group: 'insurance',
  },
  {
    id: 'lifeInsuranceAmount',
    type: 'text',
    label: 'Life Insurance Amount',
    placeholder: 'Minimum coverage amount',
    required: false,
    group: 'insurance',
    dependsOn: 'lifeInsurance',
  },
  {
    id: 'lifeInsuranceBeneficiary',
    type: 'text',
    label: 'Life Insurance Beneficiary',
    placeholder: 'Who receives the benefit',
    required: false,
    group: 'insurance',
    dependsOn: 'lifeInsurance',
  },
  {
    id: 'custodyArrangement',
    type: 'text',
    label: 'Custody Arrangement',
    placeholder: 'Describe current custody arrangement',
    required: false,
    group: 'custody',
  },
  {
    id: 'visitationImpact',
    type: 'checkbox',
    label: 'Support amount considers visitation time',
    required: false,
    group: 'custody',
  },
  {
    id: 'stateGuidelines',
    type: 'checkbox',
    label: 'Support calculated per state guidelines',
    required: false,
    group: 'state-guidelines',
  },
  {
    id: 'deviationReason',
    type: 'textarea',
    label: 'Reason for Deviation from Guidelines',
    placeholder: 'Explain why support deviates from state guidelines',
    required: false,
    group: 'state-guidelines',
  },
  {
    id: 'colaAdjustments',
    type: 'checkbox',
    label: 'Include cost-of-living adjustments',
    required: false,
    group: 'cola',
  },
  {
    id: 'colaFrequency',
    type: 'select',
    label: 'COLA Adjustment Frequency',
    options: [
      { value: 'annual', label: 'Annual' },
      { value: 'biennial', label: 'Every Two Years' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
    group: 'cola',
    dependsOn: 'colaAdjustments',
  },
  {
    id: 'periodicReview',
    type: 'checkbox',
    label: 'Include periodic review provision',
    required: false,
    group: 'review',
  },
  {
    id: 'reviewFrequency',
    type: 'select',
    label: 'Review Frequency',
    options: [
      { value: 'annual', label: 'Annual' },
      { value: 'biennial', label: 'Every Two Years' },
      { value: 'triennial', label: 'Every Three Years' },
    ],
    required: false,
    group: 'review',
    dependsOn: 'periodicReview',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law (State)',
    placeholder: 'e.g., State of California',
    required: false,
    group: 'legal',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'court', label: 'Court Proceedings' },
    ],
    required: false,
    group: 'legal',
  },
  {
    id: 'attorneyFees',
    type: 'checkbox',
    label: 'Include attorney fees clause',
    required: false,
    group: 'attorney-fees',
  },
  {
    id: 'attorneyFeeResponsibility',
    type: 'select',
    label: 'Attorney Fee Responsibility',
    options: [
      { value: 'obligor', label: 'Obligor Pays' },
      { value: 'obligee', label: 'Obligee Pays' },
      { value: 'prevailing-party', label: 'Prevailing Party' },
    ],
    required: false,
    group: 'attorney-fees',
    dependsOn: 'attorneyFees',
  },
  {
    id: 'requireNotarization',
    type: 'checkbox',
    label: 'Require notarization',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireObligorSignature',
    type: 'checkbox',
    label: 'Require obligor signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireObligeeSignature',
    type: 'checkbox',
    label: 'Require obligee signature',
    required: false,
    group: 'signatures',
  },
];