import type { Question } from '@/types/documents';

export const questions: Question[] = [
  {
    id: 'companyName',
    type: 'text',
    label: 'Company Name',
    required: true,
    category: 'Company Information',
  },
  {
    id: 'companyAddress',
    type: 'text',
    label: 'Company Address',
    required: true,
    category: 'Company Information',
  },
  {
    id: 'policyTitle',
    type: 'text',
    label: 'Policy Title',
    required: true,
    category: 'Policy Details',
    placeholder: 'e.g., Progressive Discipline Policy',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Policy Effective Date',
    required: true,
    category: 'Policy Details',
  },
  {
    id: 'applicableEmployees',
    type: 'text',
    label: 'Applicable Employees',
    required: true,
    category: 'Policy Scope',
    placeholder: 'e.g., All employees, Non-union employees',
  },
  {
    id: 'step1Description',
    type: 'text',
    label: 'Step 1: Verbal Warning Description',
    required: true,
    category: 'Disciplinary Steps',
    placeholder: 'e.g., Informal counseling and verbal warning',
  },
  {
    id: 'step1Consequences',
    type: 'text',
    label: 'Step 1: Consequences',
    required: true,
    category: 'Disciplinary Steps',
    placeholder: 'e.g., Documentation in employee file',
  },
  {
    id: 'step2Description',
    type: 'text',
    label: 'Step 2: Written Warning Description',
    required: true,
    category: 'Disciplinary Steps',
    placeholder: 'e.g., Formal written warning',
  },
  {
    id: 'step2Consequences',
    type: 'text',
    label: 'Step 2: Consequences',
    required: true,
    category: 'Disciplinary Steps',
    placeholder: 'e.g., Written documentation and improvement plan',
  },
  {
    id: 'step3Description',
    type: 'text',
    label: 'Step 3: Final Warning Description',
    required: true,
    category: 'Disciplinary Steps',
    placeholder: 'e.g., Final written warning',
  },
  {
    id: 'step3Consequences',
    type: 'text',
    label: 'Step 3: Consequences',
    required: true,
    category: 'Disciplinary Steps',
    placeholder: 'e.g., Formal warning that termination may result',
  },
  {
    id: 'step4Description',
    type: 'text',
    label: 'Step 4: Termination Description',
    required: true,
    category: 'Disciplinary Steps',
    placeholder: 'e.g., Employment termination',
  },
  {
    id: 'step4Consequences',
    type: 'text',
    label: 'Step 4: Consequences',
    required: true,
    category: 'Disciplinary Steps',
    placeholder: 'e.g., Immediate termination of employment',
  },
  {
    id: 'seriousOffensesList',
    type: 'textarea',
    label: 'Serious Offenses List',
    required: true,
    category: 'Serious Offenses',
    placeholder: 'List offenses that may result in immediate termination',
  },
  {
    id: 'seriousOffenseConsequences',
    type: 'text',
    label: 'Serious Offense Consequences',
    required: true,
    category: 'Serious Offenses',
    placeholder: 'e.g., Immediate termination or suspension',
  },
  {
    id: 'documentationRequirements',
    type: 'textarea',
    label: 'Documentation Requirements',
    required: true,
    category: 'Documentation',
    placeholder: 'Describe required documentation for disciplinary actions',
  },
  {
    id: 'recordRetentionPeriod',
    type: 'text',
    label: 'Record Retention Period',
    required: true,
    category: 'Documentation',
    placeholder: 'e.g., 3 years, Duration of employment',
  },
  {
    id: 'appealProcess',
    type: 'textarea',
    label: 'Appeal Process',
    required: true,
    category: 'Employee Rights',
    placeholder: 'Describe how employees can appeal disciplinary actions',
  },
  {
    id: 'governingState',
    type: 'select',
    label: 'Governing State',
    required: true,
    category: 'Legal Compliance',
    options: [
      'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 
      'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 
      'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 
      'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 
      'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 
      'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 
      'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'
    ],
  },
  {
    id: 'approvalDate',
    type: 'date',
    label: 'Policy Approval Date',
    required: true,
    category: 'Approval',
  },
  {
    id: 'approvedBy',
    type: 'text',
    label: 'Approved By',
    required: true,
    category: 'Approval',
    placeholder: 'e.g., HR Director, CEO',
  },
];