import type { Question } from '@/types/documents';

export const questions: Question[] = [
  {
    id: 'trustorName',
    label: 'Trustor Full Name (Trust Creator)',
    type: 'text',
    required: true,
    placeholder: 'Enter your full legal name',
  },
  {
    id: 'trustorAddress',
    label: 'Trustor Address',
    type: 'textarea',
    required: true,
    placeholder: 'Enter your complete address',
  },
  {
    id: 'trustName',
    label: 'Education Trust Name',
    type: 'text',
    required: true,
    placeholder: 'e.g., The Smith Family Education Trust',
  },
  {
    id: 'trustDate',
    label: 'Trust Creation Date',
    type: 'date',
    required: true,
  },
  {
    id: 'trusteeName',
    label: 'Trustee Full Name',
    type: 'text',
    required: true,
    placeholder: 'Person responsible for managing the trust',
  },
  {
    id: 'trusteeAddress',
    label: 'Trustee Address',
    type: 'textarea',
    required: true,
    placeholder: 'Complete address of the trustee',
  },
  {
    id: 'successorTrusteeName',
    label: 'Successor Trustee Full Name (Optional)',
    type: 'text',
    placeholder: 'Alternative trustee if primary is unable to serve',
  },
  {
    id: 'successorTrusteeAddress',
    label: 'Successor Trustee Address (Optional)',
    type: 'textarea',
    placeholder: 'Complete address of successor trustee',
  },
  {
    id: 'primaryBeneficiary',
    label: 'Primary Beneficiary Full Name',
    type: 'text',
    required: true,
    placeholder: 'Student who will benefit from the education trust',
  },
  {
    id: 'primaryBeneficiaryAge',
    label: 'Primary Beneficiary Current Age',
    type: 'text',
    required: true,
    placeholder: 'Current age of the primary beneficiary',
  },
  {
    id: 'primaryBeneficiaryRelation',
    label: 'Relationship to Primary Beneficiary',
    type: 'text',
    required: true,
    placeholder: 'e.g., child, grandchild, niece, nephew',
  },
  {
    id: 'additionalBeneficiaries',
    label: 'Additional Beneficiaries (Optional)',
    type: 'textarea',
    placeholder: 'Other students who may benefit from this trust',
  },
  {
    id: 'educationalPurpose',
    label: 'Educational Purpose and Goals',
    type: 'textarea',
    required: true,
    placeholder: 'Describe the educational goals and purpose of this trust',
  },
  {
    id: 'eligibleExpenses',
    label: 'Eligible Educational Expenses',
    type: 'textarea',
    required: true,
    placeholder: 'Define what educational expenses can be paid (tuition, books, room & board, etc.)',
  },
  {
    id: 'initialFunding',
    label: 'Initial Funding Amount',
    type: 'text',
    required: true,
    placeholder: 'Initial amount being placed in the trust',
  },
  {
    id: 'additionalContributions',
    label: 'Additional Contribution Guidelines (Optional)',
    type: 'textarea',
    placeholder: 'Rules for additional contributions to the trust',
  },
  {
    id: 'investmentGuidelines',
    label: 'Investment Guidelines',
    type: 'textarea',
    required: true,
    placeholder: 'How trust funds should be invested and managed',
  },
  {
    id: 'distributionTriggers',
    label: 'Distribution Triggers',
    type: 'textarea',
    required: true,
    placeholder: 'When distributions can be made (enrollment, grades, expenses incurred, etc.)',
  },
  {
    id: 'distributionLimitations',
    label: 'Distribution Limitations',
    type: 'textarea',
    required: true,
    placeholder: 'Any limits on distributions (annual maximums, percentage limits, etc.)',
  },
  {
    id: 'ageRestrictions',
    label: 'Age Restrictions (Optional)',
    type: 'textarea',
    placeholder: 'Any age limits for beneficiaries to receive distributions',
  },
  {
    id: 'academicRequirements',
    label: 'Academic Requirements (Optional)',
    type: 'textarea',
    placeholder: 'GPA requirements, enrollment status, or other academic conditions',
  },
  {
    id: 'institutionRequirements',
    label: 'Educational Institution Requirements',
    type: 'textarea',
    required: true,
    placeholder: 'Requirements for eligible schools (accredited institutions, degree programs, etc.)',
  },
  {
    id: 'surplusFundsDisposition',
    label: 'Surplus Funds Disposition',
    type: 'textarea',
    required: true,
    placeholder: 'What happens to unused funds if beneficiary doesn\'t use all educational funding',
  },
  {
    id: 'terminationConditions',
    label: 'Trust Termination Conditions',
    type: 'textarea',
    required: true,
    placeholder: 'When and how the trust will terminate',
  },
  {
    id: 'reportingRequirements',
    label: 'Reporting Requirements',
    type: 'textarea',
    required: true,
    placeholder: 'Reporting obligations of trustee to trustor and beneficiaries',
  },
  {
    id: 'specialProvisions',
    label: 'Special Provisions (Optional)',
    type: 'textarea',
    placeholder: 'Any additional terms, conditions, or special instructions',
  },
  {
    id: 'witnessOneName',
    label: 'First Witness Full Name',
    type: 'text',
    required: true,
    placeholder: 'Adult witness to trust signing',
  },
  {
    id: 'witnessOneAddress',
    label: 'First Witness Address',
    type: 'textarea',
    required: true,
    placeholder: 'Complete address of first witness',
  },
  {
    id: 'witnessTwoName',
    label: 'Second Witness Full Name',
    type: 'text',
    required: true,
    placeholder: 'Second adult witness to trust signing',
  },
  {
    id: 'witnessTwoAddress',
    label: 'Second Witness Address',
    type: 'textarea',
    required: true,
    placeholder: 'Complete address of second witness',
  },
  {
    id: 'executionDate',
    label: 'Trust Execution Date',
    type: 'date',
    required: true,
  },
  {
    id: 'executionState',
    label: 'State Where Trust is Executed',
    type: 'text',
    required: true,
    placeholder: 'State where you are signing this trust',
  },
  {
    id: 'executionCounty',
    label: 'County Where Trust is Executed',
    type: 'text',
    required: true,
    placeholder: 'County where you are signing this trust',
  },
];