// src/lib/documents/us/restaurant-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const restaurantAgreementQuestions: FormQuestion[] = [
  {
    id: 'primaryPartyName',
    type: 'text',
    label: 'Primary Party Name',
    placeholder: 'Enter primary party name',
    required: true,
    group: 'parties',
  },
  {
    id: 'primaryPartyRole',
    type: 'select',
    label: 'Primary Party Role',
    options: [
      { value: 'owner', label: 'Owner' },
      { value: 'partner', label: 'Partner' },
      { value: 'manager', label: 'Manager' },
      { value: 'investor', label: 'Investor' },
      { value: 'franchisee', label: 'Franchisee' },
    ],
    required: false,
    group: 'parties',
  },
  {
    id: 'secondaryPartyName',
    type: 'text',
    label: 'Secondary Party Name',
    placeholder: 'Enter secondary party name',
    required: true,
    group: 'parties',
  },
  {
    id: 'secondaryPartyRole',
    type: 'select',
    label: 'Secondary Party Role',
    options: [
      { value: 'owner', label: 'Owner' },
      { value: 'partner', label: 'Partner' },
      { value: 'manager', label: 'Manager' },
      { value: 'investor', label: 'Investor' },
      { value: 'franchisee', label: 'Franchisee' },
    ],
    required: false,
    group: 'parties',
  },
  {
    id: 'agreementType',
    type: 'select',
    label: 'Agreement Type',
    options: [
      { value: 'partnership', label: 'Partnership' },
      { value: 'management', label: 'Management' },
      { value: 'franchise', label: 'Franchise' },
      { value: 'lease', label: 'Lease' },
      { value: 'supplier', label: 'Supplier' },
      { value: 'employment', label: 'Employment' },
    ],
    required: false,
    group: 'agreement',
  },
  {
    id: 'restaurantName',
    type: 'text',
    label: 'Restaurant Name',
    placeholder: 'Enter restaurant name',
    required: true,
    group: 'restaurant',
  },
  {
    id: 'restaurantAddress',
    type: 'text',
    label: 'Restaurant Address',
    placeholder: 'Enter restaurant address',
    required: false,
    group: 'restaurant',
  },
  {
    id: 'restaurantType',
    type: 'select',
    label: 'Restaurant Type',
    options: [
      { value: 'fast-food', label: 'Fast Food' },
      { value: 'casual-dining', label: 'Casual Dining' },
      { value: 'fine-dining', label: 'Fine Dining' },
      { value: 'cafe', label: 'Cafe' },
      { value: 'bar', label: 'Bar' },
      { value: 'food-truck', label: 'Food Truck' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
    group: 'restaurant',
  },
  {
    id: 'cuisineType',
    type: 'text',
    label: 'Cuisine Type',
    placeholder: 'Enter cuisine type (e.g., Italian, Mexican)',
    required: false,
    group: 'restaurant',
  },
  {
    id: 'seatingCapacity',
    type: 'text',
    label: 'Seating Capacity',
    placeholder: 'Enter seating capacity',
    required: false,
    group: 'restaurant',
  },
  {
    id: 'businessEntity',
    type: 'select',
    label: 'Business Entity Type',
    options: [
      { value: 'llc', label: 'LLC' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'partnership', label: 'Partnership' },
      { value: 'sole-proprietorship', label: 'Sole Proprietorship' },
    ],
    required: false,
    group: 'business',
  },
  {
    id: 'totalInvestment',
    type: 'text',
    label: 'Total Investment',
    placeholder: 'Enter total investment amount',
    required: false,
    group: 'financial',
  },
  {
    id: 'ownershipPercentage',
    type: 'text',
    label: 'Ownership Percentage',
    placeholder: 'Enter ownership percentage split',
    required: false,
    group: 'financial',
  },
  {
    id: 'profitSharing',
    type: 'text',
    label: 'Profit Sharing',
    placeholder: 'Describe profit sharing arrangement',
    required: false,
    group: 'financial',
  },
  {
    id: 'operatingHours',
    type: 'text',
    label: 'Operating Hours',
    placeholder: 'Enter operating hours (e.g., 7 AM - 10 PM)',
    required: false,
    group: 'operations',
  },
  {
    id: 'menuControl',
    type: 'select',
    label: 'Menu Control',
    options: [
      { value: 'joint', label: 'Joint Decision' },
      { value: 'primary-party', label: 'Primary Party' },
      { value: 'secondary-party', label: 'Secondary Party' },
      { value: 'chef', label: 'Chef' },
    ],
    required: false,
    group: 'operations',
  },
  {
    id: 'pricingControl',
    type: 'select',
    label: 'Pricing Control',
    options: [
      { value: 'joint', label: 'Joint Decision' },
      { value: 'primary-party', label: 'Primary Party' },
      { value: 'secondary-party', label: 'Secondary Party' },
      { value: 'manager', label: 'Manager' },
    ],
    required: false,
    group: 'operations',
  },
  {
    id: 'staffingResponsibility',
    type: 'select',
    label: 'Staffing Responsibility',
    options: [
      { value: 'joint', label: 'Joint Responsibility' },
      { value: 'primary-party', label: 'Primary Party' },
      { value: 'secondary-party', label: 'Secondary Party' },
      { value: 'manager', label: 'Manager' },
    ],
    required: false,
    group: 'staffing',
  },
  {
    id: 'minimumStaffLevels',
    type: 'text',
    label: 'Minimum Staff Levels',
    placeholder: 'Describe minimum staffing requirements',
    required: false,
    group: 'staffing',
  },
  {
    id: 'marketingBudget',
    type: 'text',
    label: 'Marketing Budget',
    placeholder: 'Enter marketing budget amount',
    required: false,
    group: 'marketing',
  },
  {
    id: 'advertisingStrategy',
    type: 'textarea',
    label: 'Advertising Strategy',
    placeholder: 'Describe advertising and marketing strategy',
    required: false,
    group: 'marketing',
  },
  {
    id: 'liquorLicense',
    type: 'boolean',
    label: 'Liquor license required?',
    required: false,
    group: 'licenses',
  },
  {
    id: 'healthPermits',
    type: 'boolean',
    label: 'Health permits required?',
    required: false,
    group: 'licenses',
  },
  {
    id: 'healthSafetyStandards',
    type: 'textarea',
    label: 'Health & Safety Standards',
    placeholder: 'Describe health and safety standards',
    required: false,
    group: 'quality',
  },
  {
    id: 'agreementTerm',
    type: 'text',
    label: 'Agreement Term',
    placeholder: 'Enter agreement duration (e.g., 5 years)',
    required: false,
    group: 'term',
  },
  {
    id: 'renewalOptions',
    type: 'boolean',
    label: 'Include renewal options?',
    required: false,
    group: 'term',
  },
  {
    id: 'terminationNotice',
    type: 'text',
    label: 'Termination Notice Period',
    placeholder: 'Enter notice period (e.g., 30 days)',
    required: false,
    group: 'termination',
  },
  {
    id: 'nonCompeteClause',
    type: 'boolean',
    label: 'Include non-compete clause?',
    required: false,
    group: 'termination',
  },
  {
    id: 'disputeResolutionMethod',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'court', label: 'Court' },
    ],
    required: false,
    group: 'legal',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'Enter governing law/state',
    required: false,
    group: 'legal',
  },
];