// src/lib/documents/us/vacation-rental-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const vacationRentalAgreementQuestions: FormQuestion[] = [
  {
    id: 'ownerName',
    type: 'text',
    label: 'Property Owner Name',
    placeholder: 'Enter property owner name',
    required: true,
    group: 'owner',
  },
  {
    id: 'ownerEmail',
    type: 'email',
    label: 'Owner Email',
    placeholder: 'Enter owner email address',
    required: false,
    group: 'owner',
  },
  {
    id: 'ownerPhone',
    type: 'text',
    label: 'Owner Phone',
    placeholder: 'Enter owner phone number',
    required: false,
    group: 'owner',
  },
  {
    id: 'guestName',
    type: 'text',
    label: 'Guest Name',
    placeholder: 'Enter guest full name',
    required: true,
    group: 'guest',
  },
  {
    id: 'guestEmail',
    type: 'email',
    label: 'Guest Email',
    placeholder: 'Enter guest email address',
    required: false,
    group: 'guest',
  },
  {
    id: 'numberOfGuests',
    type: 'text',
    label: 'Number of Guests',
    placeholder: 'Enter total number of guests',
    required: false,
    group: 'guest',
  },
  {
    id: 'propertyAddress',
    type: 'text',
    label: 'Property Address',
    placeholder: 'Enter complete property address',
    required: true,
    group: 'property',
  },
  {
    id: 'propertyType',
    type: 'select',
    label: 'Property Type',
    options: [
      { value: 'house', label: 'House' },
      { value: 'apartment', label: 'Apartment' },
      { value: 'condo', label: 'Condo' },
      { value: 'cabin', label: 'Cabin' },
      { value: 'villa', label: 'Villa' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
    group: 'property',
  },
  {
    id: 'bedrooms',
    type: 'text',
    label: 'Number of Bedrooms',
    placeholder: 'Enter number of bedrooms',
    required: false,
    group: 'property',
  },
  {
    id: 'bathrooms',
    type: 'text',
    label: 'Number of Bathrooms',
    placeholder: 'Enter number of bathrooms',
    required: false,
    group: 'property',
  },
  {
    id: 'maxOccupancy',
    type: 'text',
    label: 'Maximum Occupancy',
    placeholder: 'Enter maximum number of guests',
    required: false,
    group: 'property',
  },
  {
    id: 'checkInDate',
    type: 'date',
    label: 'Check-in Date',
    required: false,
    group: 'rental',
  },
  {
    id: 'checkOutDate',
    type: 'date',
    label: 'Check-out Date',
    required: false,
    group: 'rental',
  },
  {
    id: 'checkInTime',
    type: 'text',
    label: 'Check-in Time',
    placeholder: 'Enter check-in time (e.g., 3:00 PM)',
    required: false,
    group: 'rental',
  },
  {
    id: 'checkOutTime',
    type: 'text',
    label: 'Check-out Time',
    placeholder: 'Enter check-out time (e.g., 11:00 AM)',
    required: false,
    group: 'rental',
  },
  {
    id: 'nightlyRate',
    type: 'text',
    label: 'Nightly Rate',
    placeholder: 'Enter nightly rate',
    required: false,
    group: 'pricing',
  },
  {
    id: 'totalRentalCost',
    type: 'text',
    label: 'Total Rental Cost',
    placeholder: 'Enter total cost for stay',
    required: false,
    group: 'pricing',
  },
  {
    id: 'cleaningFee',
    type: 'text',
    label: 'Cleaning Fee',
    placeholder: 'Enter cleaning fee amount',
    required: false,
    group: 'pricing',
  },
  {
    id: 'securityDeposit',
    type: 'text',
    label: 'Security Deposit',
    placeholder: 'Enter security deposit amount',
    required: false,
    group: 'deposits',
  },
  {
    id: 'depositRefundable',
    type: 'boolean',
    label: 'Is security deposit refundable?',
    required: false,
    group: 'deposits',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'full-upfront', label: 'Full Payment Upfront' },
      { value: 'deposit-then-balance', label: 'Deposit Then Balance' },
      { value: 'installments', label: 'Installments' },
    ],
    required: false,
    group: 'payment',
  },
  {
    id: 'smokingAllowed',
    type: 'boolean',
    label: 'Smoking allowed?',
    required: false,
    group: 'rules',
  },
  {
    id: 'petsAllowed',
    type: 'boolean',
    label: 'Pets allowed?',
    required: false,
    group: 'rules',
  },
  {
    id: 'petRestrictions',
    type: 'textarea',
    label: 'Pet Restrictions',
    placeholder: 'Describe any pet restrictions',
    required: false,
    group: 'rules',
  },
  {
    id: 'partiesAllowed',
    type: 'boolean',
    label: 'Parties allowed?',
    required: false,
    group: 'rules',
  },
  {
    id: 'quietHours',
    type: 'text',
    label: 'Quiet Hours',
    placeholder: 'Enter quiet hours (e.g., 10 PM - 8 AM)',
    required: false,
    group: 'rules',
  },
  {
    id: 'wifi',
    type: 'boolean',
    label: 'WiFi included?',
    required: false,
    group: 'amenities',
  },
  {
    id: 'parking',
    type: 'boolean',
    label: 'Parking available?',
    required: false,
    group: 'amenities',
  },
  {
    id: 'kitchen',
    type: 'boolean',
    label: 'Kitchen available?',
    required: false,
    group: 'amenities',
  },
  {
    id: 'laundry',
    type: 'boolean',
    label: 'Laundry facilities?',
    required: false,
    group: 'amenities',
  },
  {
    id: 'pool',
    type: 'boolean',
    label: 'Pool available?',
    required: false,
    group: 'amenities',
  },
  {
    id: 'hotTub',
    type: 'boolean',
    label: 'Hot tub available?',
    required: false,
    group: 'amenities',
  },
  {
    id: 'cleaningServiceIncluded',
    type: 'boolean',
    label: 'Cleaning service included?',
    required: false,
    group: 'services',
  },
  {
    id: 'linenService',
    type: 'boolean',
    label: 'Linen service included?',
    required: false,
    group: 'services',
  },
  {
    id: 'keyPickupLocation',
    type: 'text',
    label: 'Key Pickup Location',
    placeholder: 'Enter key pickup location',
    required: false,
    group: 'access',
  },
  {
    id: 'keylessEntry',
    type: 'boolean',
    label: 'Keyless entry available?',
    required: false,
    group: 'access',
  },
  {
    id: 'emergencyContacts',
    type: 'textarea',
    label: 'Emergency Contacts',
    placeholder: 'Enter emergency contact information',
    required: false,
    group: 'emergency',
  },
  {
    id: 'cancellationPolicy',
    type: 'select',
    label: 'Cancellation Policy',
    options: [
      { value: 'strict', label: 'Strict' },
      { value: 'moderate', label: 'Moderate' },
      { value: 'flexible', label: 'Flexible' },
      { value: 'super-strict', label: 'Super Strict' },
    ],
    required: false,
    group: 'cancellation',
  },
  {
    id: 'houseRules',
    type: 'textarea',
    label: 'House Rules',
    placeholder: 'Enter specific house rules',
    required: false,
    group: 'terms',
  },
  {
    id: 'specialInstructions',
    type: 'textarea',
    label: 'Special Instructions',
    placeholder: 'Enter any special instructions for guests',
    required: false,
    group: 'terms',
  },
];
