// src/lib/documents/us/copyright-assignment-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const copyrightAssignmentAgreementQuestions: FormQuestion[] = [
  {
    id: 'assignorName',
    type: 'text',
    label: 'Assignor Name (Current Owner)',
    placeholder: 'Enter current copyright owner name',
    required: true,
    group: 'assignor',
  },
  {
    id: 'assignorAddress',
    type: 'text',
    label: 'Assignor Address',
    placeholder: 'Enter complete assignor address',
    required: true,
    group: 'assignor',
  },
  {
    id: 'assignorType',
    type: 'select',
    label: 'Assignor Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'partnership', label: 'Partnership' },
      { value: 'llc', label: 'LLC' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'assignor',
  },
  {
    id: 'assigneeName',
    type: 'text',
    label: 'Assignee Name (New Owner)',
    placeholder: 'Enter new copyright owner name',
    required: true,
    group: 'assignee',
  },
  {
    id: 'assigneeAddress',
    type: 'text',
    label: 'Assignee Address',
    placeholder: 'Enter complete assignee address',
    required: true,
    group: 'assignee',
  },
  {
    id: 'assigneeType',
    type: 'select',
    label: 'Assignee Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'partnership', label: 'Partnership' },
      { value: 'llc', label: 'LLC' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'assignee',
  },
  {
    id: 'assignmentDate',
    type: 'date',
    label: 'Assignment Date',
    required: true,
    group: 'dates',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Effective Date',
    required: true,
    group: 'dates',
  },
  {
    id: 'workTitle',
    type: 'text',
    label: 'Work Title',
    placeholder: 'Enter title of the copyrighted work',
    required: true,
    group: 'work',
  },
  {
    id: 'workDescription',
    type: 'textarea',
    label: 'Work Description',
    placeholder: 'Provide detailed description of the work',
    required: true,
    group: 'work',
  },
  {
    id: 'workType',
    type: 'select',
    label: 'Type of Work',
    options: [
      { value: 'literary', label: 'Literary Work' },
      { value: 'musical', label: 'Musical Work' },
      { value: 'dramatic', label: 'Dramatic Work' },
      { value: 'choreographic', label: 'Choreographic Work' },
      { value: 'pictorial', label: 'Pictorial Work' },
      { value: 'graphic', label: 'Graphic Work' },
      { value: 'sculptural', label: 'Sculptural Work' },
      { value: 'motion-picture', label: 'Motion Picture' },
      { value: 'sound-recording', label: 'Sound Recording' },
      { value: 'architectural', label: 'Architectural Work' },
      { value: 'software', label: 'Software/Computer Program' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'work',
  },
  {
    id: 'creationDate',
    type: 'date',
    label: 'Creation Date (if known)',
    required: false,
    group: 'work',
  },
  {
    id: 'completionDate',
    type: 'date',
    label: 'Completion Date (if known)',
    required: false,
    group: 'work',
  },
  {
    id: 'copyrightRegistered',
    type: 'checkbox',
    label: 'Copyright is registered',
    required: false,
    group: 'copyright-details',
  },
  {
    id: 'registrationNumber',
    type: 'text',
    label: 'Registration Number',
    placeholder: 'Enter copyright registration number',
    required: false,
    group: 'copyright-details',
    dependsOn: 'copyrightRegistered',
  },
  {
    id: 'registrationDate',
    type: 'date',
    label: 'Registration Date',
    required: false,
    group: 'copyright-details',
    dependsOn: 'copyrightRegistered',
  },
  {
    id: 'assignmentType',
    type: 'select',
    label: 'Type of Assignment',
    options: [
      { value: 'complete', label: 'Complete Assignment' },
      { value: 'partial', label: 'Partial Assignment' },
      { value: 'exclusive-license', label: 'Exclusive License' },
      { value: 'non-exclusive-license', label: 'Non-exclusive License' },
    ],
    required: true,
    group: 'assignment-scope',
  },
  {
    id: 'territoryScope',
    type: 'select',
    label: 'Territory Scope',
    options: [
      { value: 'worldwide', label: 'Worldwide' },
      { value: 'united-states', label: 'United States Only' },
      { value: 'specific-countries', label: 'Specific Countries' },
      { value: 'specific-regions', label: 'Specific Regions' },
    ],
    required: true,
    group: 'assignment-scope',
  },
  {
    id: 'specificTerritory',
    type: 'text',
    label: 'Specific Territory',
    placeholder: 'List specific countries or regions',
    required: false,
    group: 'assignment-scope',
    dependsOn: 'territoryScope',
  },
  {
    id: 'rightOfReproduction',
    type: 'checkbox',
    label: 'Right of reproduction',
    required: false,
    group: 'rights',
  },
  {
    id: 'rightOfDistribution',
    type: 'checkbox',
    label: 'Right of distribution',
    required: false,
    group: 'rights',
  },
  {
    id: 'rightOfPublicPerformance',
    type: 'checkbox',
    label: 'Right of public performance',
    required: false,
    group: 'rights',
  },
  {
    id: 'rightOfPublicDisplay',
    type: 'checkbox',
    label: 'Right of public display',
    required: false,
    group: 'rights',
  },
  {
    id: 'rightOfPreparation',
    type: 'checkbox',
    label: 'Right to prepare derivative works',
    required: false,
    group: 'rights',
  },
  {
    id: 'rightOfDigitalTransmission',
    type: 'checkbox',
    label: 'Right of digital transmission',
    required: false,
    group: 'rights',
  },
  {
    id: 'assignmentTerm',
    type: 'select',
    label: 'Assignment Term',
    options: [
      { value: 'perpetual', label: 'Perpetual' },
      { value: 'life-plus-70', label: 'Life of Author Plus 70 Years' },
      { value: 'specific-years', label: 'Specific Number of Years' },
      { value: 'specific-date', label: 'Until Specific Date' },
    ],
    required: true,
    group: 'term',
  },
  {
    id: 'specificYears',
    type: 'text',
    label: 'Number of Years',
    placeholder: 'Enter number of years',
    required: false,
    group: 'term',
    dependsOn: 'assignmentTerm',
  },
  {
    id: 'terminationDate',
    type: 'date',
    label: 'Termination Date',
    required: false,
    group: 'term',
    dependsOn: 'assignmentTerm',
  },
  {
    id: 'hasConsideration',
    type: 'checkbox',
    label: 'Include payment/consideration',
    required: false,
    group: 'consideration',
  },
  {
    id: 'considerationType',
    type: 'select',
    label: 'Type of Consideration',
    options: [
      { value: 'monetary', label: 'Monetary Payment' },
      { value: 'royalty', label: 'Royalty Payments' },
      { value: 'other-works', label: 'Other Creative Works' },
      { value: 'services', label: 'Services' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
    group: 'consideration',
    dependsOn: 'hasConsideration',
  },
  {
    id: 'monetaryAmount',
    type: 'text',
    label: 'Payment Amount',
    placeholder: 'Enter payment amount',
    required: false,
    group: 'consideration',
    dependsOn: 'hasConsideration',
  },
  {
    id: 'royaltyPercentage',
    type: 'text',
    label: 'Royalty Percentage',
    placeholder: 'e.g., 10% of net revenues',
    required: false,
    group: 'consideration',
    dependsOn: 'hasConsideration',
  },
  {
    id: 'warrantyOfOwnership',
    type: 'checkbox',
    label: 'Warrant ownership of copyright',
    required: false,
    group: 'warranties',
  },
  {
    id: 'warrantyOfOriginality',
    type: 'checkbox',
    label: 'Warrant work is original',
    required: false,
    group: 'warranties',
  },
  {
    id: 'warrantyNoInfringement',
    type: 'checkbox',
    label: 'Warrant no infringement of third-party rights',
    required: false,
    group: 'warranties',
  },
  {
    id: 'warrantyNoEncumbrances',
    type: 'checkbox',
    label: 'Warrant no liens or encumbrances',
    required: false,
    group: 'warranties',
  },
  {
    id: 'creditRequirement',
    type: 'checkbox',
    label: 'Require attribution/credit',
    required: false,
    group: 'additional-terms',
  },
  {
    id: 'creditText',
    type: 'text',
    label: 'Credit Text',
    placeholder: 'Specify required attribution text',
    required: false,
    group: 'additional-terms',
    dependsOn: 'creditRequirement',
  },
  {
    id: 'approvalRights',
    type: 'checkbox',
    label: 'Assignor retains approval rights',
    required: false,
    group: 'additional-terms',
  },
  {
    id: 'reversionRights',
    type: 'checkbox',
    label: 'Include reversion rights',
    required: false,
    group: 'additional-terms',
  },
  {
    id: 'allowDerivativeWorks',
    type: 'checkbox',
    label: 'Allow creation of derivative works',
    required: false,
    group: 'derivative-works',
  },
  {
    id: 'approvalForDerivatives',
    type: 'checkbox',
    label: 'Require approval for derivative works',
    required: false,
    group: 'derivative-works',
    dependsOn: 'allowDerivativeWorks',
  },
  {
    id: 'hasCollaborators',
    type: 'checkbox',
    label: 'Work has other collaborators/co-owners',
    required: false,
    group: 'collaboration',
  },
  {
    id: 'collaboratorConsent',
    type: 'checkbox',
    label: 'Collaborator consent obtained',
    required: false,
    group: 'collaboration',
    dependsOn: 'hasCollaborators',
  },
  {
    id: 'assignorIndemnifies',
    type: 'checkbox',
    label: 'Assignor indemnifies assignee',
    required: false,
    group: 'indemnification',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law (State)',
    placeholder: 'e.g., State of California',
    required: false,
    group: 'legal',
  },
  {
    id: 'recordWithCopyrightOffice',
    type: 'checkbox',
    label: 'Record assignment with Copyright Office',
    required: false,
    group: 'recordation',
  },
  {
    id: 'recordingResponsibility',
    type: 'select',
    label: 'Recording Responsibility',
    options: [
      { value: 'assignor', label: 'Assignor' },
      { value: 'assignee', label: 'Assignee' },
      { value: 'both', label: 'Both Parties' },
    ],
    required: false,
    group: 'recordation',
    dependsOn: 'recordWithCopyrightOffice',
  },
  {
    id: 'includeFutureWorks',
    type: 'checkbox',
    label: 'Include future works',
    required: false,
    group: 'future-works',
  },
  {
    id: 'futureWorksDescription',
    type: 'textarea',
    label: 'Future Works Description',
    placeholder: 'Describe future works to be included',
    required: false,
    group: 'future-works',
    dependsOn: 'includeFutureWorks',
  },
  {
    id: 'requireNotarization',
    type: 'checkbox',
    label: 'Require notarization',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireAssignorSignature',
    type: 'checkbox',
    label: 'Require assignor signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireAssigneeSignature',
    type: 'checkbox',
    label: 'Require assignee signature',
    required: false,
    group: 'signatures',
  },
];