// src/lib/documents/us/construction-bid-form/questions.ts
import type { FormQuestion } from '@/types/documents';

export const constructionbidformQuestions: FormQuestion[] = [
  {
    id: 'projectName',
    type: 'text',
    label: 'Project Name',
    placeholder: 'Enter project name',
    required: true,
    group: 'project',
  },
  {
    id: 'projectNumber',
    type: 'text',
    label: 'Project Number',
    placeholder: 'Project reference number',
    required: false,
    group: 'project',
  },
  {
    id: 'projectLocation',
    type: 'text',
    label: 'Project Location',
    placeholder: 'Complete project address',
    required: true,
    group: 'project',
  },
  {
    id: 'bidOpeningDate',
    type: 'date',
    label: 'Bid Opening Date',
    required: true,
    group: 'project',
  },
  {
    id: 'bidOpeningTime',
    type: 'text',
    label: 'Bid Opening Time',
    placeholder: 'e.g., 2:00 PM EST',
    required: false,
    group: 'project',
  },
  {
    id: 'ownerName',
    type: 'text',
    label: 'Owner Name',
    placeholder: 'Property owner or organization',
    required: true,
    group: 'owner',
  },
  {
    id: 'ownerAddress',
    type: 'text',
    label: 'Owner Address',
    placeholder: 'Complete owner address',
    required: true,
    group: 'owner',
  },
  {
    id: 'ownerPhone',
    type: 'text',
    label: 'Owner Phone',
    placeholder: 'Contact phone number',
    required: false,
    group: 'owner',
  },
  {
    id: 'ownerEmail',
    type: 'email',
    label: 'Owner Email',
    placeholder: 'Contact email address',
    required: false,
    group: 'owner',
  },
  {
    id: 'architectName',
    type: 'text',
    label: 'Architect/Engineer Name',
    placeholder: 'Design professional name',
    required: false,
    group: 'architect',
  },
  {
    id: 'architectAddress',
    type: 'text',
    label: 'Architect Address',
    placeholder: 'Architect office address',
    required: false,
    group: 'architect',
  },
  {
    id: 'architectPhone',
    type: 'text',
    label: 'Architect Phone',
    placeholder: 'Architect contact number',
    required: false,
    group: 'architect',
  },
  {
    id: 'contractorName',
    type: 'text',
    label: 'Contractor Name',
    placeholder: 'Bidding contractor name',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorAddress',
    type: 'text',
    label: 'Contractor Address',
    placeholder: 'Complete business address',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorPhone',
    type: 'text',
    label: 'Contractor Phone',
    placeholder: 'Business phone number',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorEmail',
    type: 'email',
    label: 'Contractor Email',
    placeholder: 'Business email address',
    required: false,
    group: 'contractor',
  },
  {
    id: 'contractorLicense',
    type: 'text',
    label: 'Contractor License Number',
    placeholder: 'State license number',
    required: true,
    group: 'contractor',
  },
  {
    id: 'bidAmount',
    type: 'text',
    label: 'Total Bid Amount',
    placeholder: 'Total bid amount in dollars',
    required: true,
    group: 'bid',
  },
  {
    id: 'bidAmountWords',
    type: 'text',
    label: 'Bid Amount in Words',
    placeholder: 'Bid amount written out in words',
    required: true,
    group: 'bid',
  },
  {
    id: 'bidValidityPeriod',
    type: 'text',
    label: 'Bid Validity Period',
    placeholder: 'e.g., 30 days, 60 days',
    required: false,
    group: 'bid',
  },
  {
    id: 'proposedStartDate',
    type: 'date',
    label: 'Proposed Start Date',
    required: false,
    group: 'schedule',
  },
  {
    id: 'proposedCompletionDate',
    type: 'date',
    label: 'Proposed Completion Date',
    required: false,
    group: 'schedule',
  },
  {
    id: 'bidBondRequired',
    type: 'checkbox',
    label: 'Bid bond required',
    required: false,
    group: 'bonds',
  },
  {
    id: 'bidBondAmount',
    type: 'text',
    label: 'Bid Bond Amount',
    placeholder: 'Bond amount or percentage',
    required: false,
    group: 'bonds',
    dependsOn: 'bidBondRequired',
  },
  {
    id: 'bidBondType',
    type: 'select',
    label: 'Bid Bond Type',
    options: [
      { value: 'surety-bond', label: 'Surety Bond' },
      { value: 'certified-check', label: 'Certified Check' },
      { value: 'cashiers-check', label: 'Cashiers Check' },
      { value: 'bid-bond', label: 'Bid Bond' },
    ],
    required: false,
    group: 'bonds',
    dependsOn: 'bidBondRequired',
  },
  {
    id: 'bidBondSuretyCompany',
    type: 'text',
    label: 'Bid Bond Surety Company',
    placeholder: 'Surety company name',
    required: false,
    group: 'bonds',
    dependsOn: 'bidBondRequired',
  },
  {
    id: 'performanceBondRequired',
    type: 'checkbox',
    label: 'Performance bond required',
    required: false,
    group: 'bonds',
  },
  {
    id: 'performanceBondAmount',
    type: 'text',
    label: 'Performance Bond Amount',
    placeholder: 'Bond amount or percentage',
    required: false,
    group: 'bonds',
    dependsOn: 'performanceBondRequired',
  },
  {
    id: 'paymentBondRequired',
    type: 'checkbox',
    label: 'Payment bond required',
    required: false,
    group: 'bonds',
  },
  {
    id: 'paymentBondAmount',
    type: 'text',
    label: 'Payment Bond Amount',
    placeholder: 'Bond amount or percentage',
    required: false,
    group: 'bonds',
    dependsOn: 'paymentBondRequired',
  },
  {
    id: 'generalLiabilityRequired',
    type: 'checkbox',
    label: 'General liability insurance required',
    required: false,
    group: 'insurance',
  },
  {
    id: 'generalLiabilityAmount',
    type: 'text',
    label: 'General Liability Amount',
    placeholder: 'Insurance coverage amount',
    required: false,
    group: 'insurance',
    dependsOn: 'generalLiabilityRequired',
  },
  {
    id: 'workersCompRequired',
    type: 'checkbox',
    label: 'Workers compensation insurance required',
    required: false,
    group: 'insurance',
  },
  {
    id: 'vehicleInsuranceRequired',
    type: 'checkbox',
    label: 'Vehicle insurance required',
    required: false,
    group: 'insurance',
  },
  {
    id: 'builderRiskRequired',
    type: 'checkbox',
    label: "Builder's risk insurance required",
    required: false,
    group: 'insurance',
  },
  {
    id: 'yearsInBusiness',
    type: 'text',
    label: 'Years in Business',
    placeholder: 'Number of years in business',
    required: false,
    group: 'experience',
  },
  {
    id: 'similarProjectsCompleted',
    type: 'text',
    label: 'Similar Projects Completed',
    placeholder: 'Number of similar projects',
    required: false,
    group: 'experience',
  },
  {
    id: 'currentWorkload',
    type: 'text',
    label: 'Current Workload',
    placeholder: 'Description of current projects',
    required: false,
    group: 'experience',
  },
  {
    id: 'projectManager',
    type: 'text',
    label: 'Assigned Project Manager',
    placeholder: 'Project manager name',
    required: false,
    group: 'personnel',
  },
  {
    id: 'superintendent',
    type: 'text',
    label: 'Assigned Superintendent',
    placeholder: 'Superintendent name',
    required: false,
    group: 'personnel',
  },
  {
    id: 'financialStatement',
    type: 'checkbox',
    label: 'Financial statement provided',
    required: false,
    group: 'financial',
  },
  {
    id: 'proposedSchedule',
    type: 'textarea',
    label: 'Proposed Schedule',
    placeholder: 'Detailed project schedule',
    required: false,
    group: 'schedule',
  },
  {
    id: 'weatherDays',
    type: 'text',
    label: 'Weather Days Allowance',
    placeholder: 'Number of weather delay days',
    required: false,
    group: 'schedule',
  },
  {
    id: 'safetyRecord',
    type: 'text',
    label: 'Safety Record',
    placeholder: 'Description of safety record',
    required: false,
    group: 'safety',
  },
  {
    id: 'safetyProgram',
    type: 'checkbox',
    label: 'Written safety program in place',
    required: false,
    group: 'safety',
  },
  {
    id: 'oshaRecordable',
    type: 'text',
    label: 'OSHA Recordable Incidents',
    placeholder: 'Number of incidents in past 3 years',
    required: false,
    group: 'safety',
  },
  {
    id: 'qualityControlPlan',
    type: 'checkbox',
    label: 'Quality control plan provided',
    required: false,
    group: 'quality',
  },
  {
    id: 'environmentalCompliance',
    type: 'checkbox',
    label: 'Environmental compliance certification',
    required: false,
    group: 'environmental',
  },
  {
    id: 'technicalSpecifications',
    type: 'textarea',
    label: 'Technical Specifications',
    placeholder: 'Special technical requirements',
    required: false,
    group: 'specifications',
  },
  {
    id: 'acknowledgeAddenda',
    type: 'checkbox',
    label: 'Acknowledge receipt of all addenda',
    required: false,
    group: 'acknowledgments',
  },
  {
    id: 'bidWithdrawalRights',
    type: 'checkbox',
    label: 'Reserve bid withdrawal rights',
    required: false,
    group: 'conditions',
  },
  {
    id: 'acceptAwardConditions',
    type: 'checkbox',
    label: 'Accept all award conditions',
    required: false,
    group: 'conditions',
  },
  {
    id: 'contractExecutionTime',
    type: 'text',
    label: 'Contract Execution Time',
    placeholder: 'Time to execute contract after award',
    required: false,
    group: 'conditions',
  },
  {
    id: 'bidderSignature',
    type: 'checkbox',
    label: 'Require bidder signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'bidderTitle',
    type: 'text',
    label: 'Bidder Title',
    placeholder: 'Title of person signing',
    required: false,
    group: 'signatures',
  },
  {
    id: 'witnessSignature',
    type: 'checkbox',
    label: 'Require witness signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'notarization',
    type: 'checkbox',
    label: 'Require notarization',
    required: false,
    group: 'signatures',
  },
  {
    id: 'certificationStatement',
    type: 'checkbox',
    label: 'Include certification statement',
    required: false,
    group: 'signatures',
  },
];
