// src/lib/documents/us/bookkeeping-services-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const bookkeepingServicesAgreementQuestions: FormQuestion[] = [
  {
    id: 'providerName',
    type: 'text',
    label: 'Service Provider Name',
    placeholder: 'Enter bookkeeper/accountant name',
    required: true,
    group: 'provider',
  },
  {
    id: 'providerBusinessName',
    type: 'text',
    label: 'Business Name',
    placeholder: 'Enter business or firm name',
    required: false,
    group: 'provider',
  },
  {
    id: 'providerAddress',
    type: 'text',
    label: 'Provider Address',
    placeholder: 'Enter complete business address',
    required: true,
    group: 'provider',
  },
  {
    id: 'providerPhone',
    type: 'text',
    label: 'Provider Phone',
    placeholder: 'Enter phone number',
    required: false,
    group: 'provider',
  },
  {
    id: 'providerEmail',
    type: 'email',
    label: 'Provider Email',
    placeholder: 'Enter email address',
    required: false,
    group: 'provider',
  },
  {
    id: 'providerLicense',
    type: 'text',
    label: 'License Number',
    placeholder: 'Professional license number',
    required: false,
    group: 'provider',
  },
  {
    id: 'providerCredentials',
    type: 'text',
    label: 'Professional Credentials',
    placeholder: 'e.g., CPA, QuickBooks ProAdvisor',
    required: false,
    group: 'provider',
  },
  {
    id: 'clientName',
    type: 'text',
    label: 'Client Name',
    placeholder: 'Enter client name',
    required: true,
    group: 'client',
  },
  {
    id: 'clientBusinessName',
    type: 'text',
    label: 'Client Business Name',
    placeholder: 'Enter business name',
    required: false,
    group: 'client',
  },
  {
    id: 'clientAddress',
    type: 'text',
    label: 'Client Address',
    placeholder: 'Enter complete address',
    required: true,
    group: 'client',
  },
  {
    id: 'clientPhone',
    type: 'text',
    label: 'Client Phone',
    placeholder: 'Enter phone number',
    required: false,
    group: 'client',
  },
  {
    id: 'clientEmail',
    type: 'email',
    label: 'Client Email',
    placeholder: 'Enter email address',
    required: false,
    group: 'client',
  },
  {
    id: 'clientEIN',
    type: 'text',
    label: 'Client EIN',
    placeholder: 'Employer Identification Number',
    required: false,
    group: 'client',
  },
  {
    id: 'businessType',
    type: 'text',
    label: 'Business Type',
    placeholder: 'e.g., LLC, Corporation, Sole Proprietorship',
    required: false,
    group: 'client',
  },
  {
    id: 'serviceType',
    type: 'select',
    label: 'Service Type',
    options: [
      { value: 'basic-bookkeeping', label: 'Basic Bookkeeping' },
      { value: 'full-service', label: 'Full-Service Accounting' },
      { value: 'custom-package', label: 'Custom Package' },
    ],
    required: true,
    group: 'services',
  },
  {
    id: 'includedServices',
    type: 'multiselect',
    label: 'Included Services',
    options: [
      { value: 'data-entry', label: 'Data Entry' },
      { value: 'bank-reconciliation', label: 'Bank Reconciliation' },
      { value: 'accounts-payable', label: 'Accounts Payable' },
      { value: 'accounts-receivable', label: 'Accounts Receivable' },
      { value: 'invoicing', label: 'Invoicing' },
      { value: 'financial-reports', label: 'Financial Reports' },
      { value: 'tax-preparation', label: 'Tax Preparation' },
      { value: 'payroll', label: 'Payroll Processing' },
    ],
    required: false,
    group: 'services',
  },
  {
    id: 'excludedServices',
    type: 'multiselect',
    label: 'Excluded Services',
    options: [
      { value: 'audit-services', label: 'Audit Services' },
      { value: 'legal-advice', label: 'Legal Advice' },
      { value: 'investment-advice', label: 'Investment Advice' },
      { value: 'loan-applications', label: 'Loan Applications' },
      { value: 'business-valuation', label: 'Business Valuation' },
    ],
    required: false,
    group: 'services',
  },
  {
    id: 'recordsToMaintain',
    type: 'multiselect',
    label: 'Records to Maintain',
    options: [
      { value: 'general-ledger', label: 'General Ledger' },
      { value: 'cash-receipts', label: 'Cash Receipts' },
      { value: 'cash-disbursements', label: 'Cash Disbursements' },
      { value: 'sales-records', label: 'Sales Records' },
      { value: 'purchase-records', label: 'Purchase Records' },
      { value: 'inventory-records', label: 'Inventory Records' },
      { value: 'payroll-records', label: 'Payroll Records' },
    ],
    required: false,
    group: 'services',
  },
  {
    id: 'reportingFrequency',
    type: 'select',
    label: 'Reporting Frequency',
    options: [
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
      { value: 'annually', label: 'Annually' },
      { value: 'as-needed', label: 'As Needed' },
    ],
    required: true,
    group: 'services',
  },
  {
    id: 'dataEntry',
    type: 'checkbox',
    label: 'Include data entry services',
    required: false,
    group: 'bookkeeping-services',
  },
  {
    id: 'bankReconciliation',
    type: 'checkbox',
    label: 'Include bank reconciliation',
    required: false,
    group: 'bookkeeping-services',
  },
  {
    id: 'invoicing',
    type: 'checkbox',
    label: 'Include invoicing services',
    required: false,
    group: 'bookkeeping-services',
  },
  {
    id: 'billPaying',
    type: 'checkbox',
    label: 'Include bill paying services',
    required: false,
    group: 'bookkeeping-services',
  },
  {
    id: 'payrollProcessing',
    type: 'checkbox',
    label: 'Include payroll processing',
    required: false,
    group: 'bookkeeping-services',
  },
  {
    id: 'taxPreparation',
    type: 'checkbox',
    label: 'Include tax preparation',
    required: false,
    group: 'bookkeeping-services',
  },
  {
    id: 'financialReporting',
    type: 'checkbox',
    label: 'Include financial reporting',
    required: false,
    group: 'bookkeeping-services',
  },
  {
    id: 'budgetPlanning',
    type: 'checkbox',
    label: 'Include budget planning',
    required: false,
    group: 'bookkeeping-services',
  },
  {
    id: 'bookkeepingSoftware',
    type: 'text',
    label: 'Bookkeeping Software',
    placeholder: 'e.g., QuickBooks, Xero, FreshBooks',
    required: false,
    group: 'software',
  },
  {
    id: 'clientProvidedSoftware',
    type: 'checkbox',
    label: 'Client provides software',
    required: false,
    group: 'software',
  },
  {
    id: 'softwareTraining',
    type: 'checkbox',
    label: 'Include software training',
    required: false,
    group: 'software',
  },
  {
    id: 'dataBackup',
    type: 'checkbox',
    label: 'Include data backup services',
    required: false,
    group: 'software',
  },
  {
    id: 'cloudBasedServices',
    type: 'checkbox',
    label: 'Use cloud-based services',
    required: false,
    group: 'software',
  },
  {
    id: 'securityMeasures',
    type: 'text',
    label: 'Security Measures',
    placeholder: 'Describe security measures in place',
    required: false,
    group: 'software',
  },
  {
    id: 'feeStructure',
    type: 'select',
    label: 'Fee Structure',
    options: [
      { value: 'monthly-retainer', label: 'Monthly Retainer' },
      { value: 'hourly', label: 'Hourly Rate' },
      { value: 'per-transaction', label: 'Per Transaction' },
      { value: 'project-based', label: 'Project Based' },
    ],
    required: true,
    group: 'fees',
  },
  {
    id: 'monthlyRetainer',
    type: 'text',
    label: 'Monthly Retainer Amount',
    placeholder: 'Enter monthly retainer fee',
    required: false,
    group: 'fees',
    dependsOn: 'feeStructure',
  },
  {
    id: 'hourlyRate',
    type: 'text',
    label: 'Hourly Rate',
    placeholder: 'Enter hourly rate',
    required: false,
    group: 'fees',
    dependsOn: 'feeStructure',
  },
  {
    id: 'perTransactionFee',
    type: 'text',
    label: 'Per Transaction Fee',
    placeholder: 'Enter fee per transaction',
    required: false,
    group: 'fees',
    dependsOn: 'feeStructure',
  },
  {
    id: 'minimumMonthlyFee',
    type: 'text',
    label: 'Minimum Monthly Fee',
    placeholder: 'Enter minimum monthly fee',
    required: false,
    group: 'fees',
  },
  {
    id: 'additionalServiceFees',
    type: 'checkbox',
    label: 'Charge additional fees for extra services',
    required: false,
    group: 'fees',
  },
  {
    id: 'expenseReimbursement',
    type: 'checkbox',
    label: 'Include expense reimbursement',
    required: false,
    group: 'fees',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
      { value: 'upon-completion', label: 'Upon Completion' },
      { value: 'advance', label: 'In Advance' },
    ],
    required: true,
    group: 'payment',
  },
  {
    id: 'paymentDueDate',
    type: 'text',
    label: 'Payment Due Date',
    placeholder: 'e.g., 15th of each month',
    required: false,
    group: 'payment',
  },
  {
    id: 'latePaymentFees',
    type: 'checkbox',
    label: 'Include late payment fees',
    required: false,
    group: 'payment',
  },
  {
    id: 'latePaymentRate',
    type: 'text',
    label: 'Late Payment Rate',
    placeholder: 'e.g., 1.5% per month',
    required: false,
    group: 'payment',
    dependsOn: 'latePaymentFees',
  },
  {
    id: 'acceptedPaymentMethods',
    type: 'multiselect',
    label: 'Accepted Payment Methods',
    options: [
      { value: 'check', label: 'Check' },
      { value: 'credit-card', label: 'Credit Card' },
      { value: 'bank-transfer', label: 'Bank Transfer' },
      { value: 'ach', label: 'ACH Transfer' },
      { value: 'paypal', label: 'PayPal' },
      { value: 'cash', label: 'Cash' },
    ],
    required: false,
    group: 'payment',
  },
  {
    id: 'autoPayment',
    type: 'checkbox',
    label: 'Allow automatic payment',
    required: false,
    group: 'payment',
  },
  {
    id: 'timelyDocumentProvision',
    type: 'checkbox',
    label: 'Client must provide documents timely',
    required: false,
    group: 'client-responsibilities',
  },
  {
    id: 'accurateInformation',
    type: 'checkbox',
    label: 'Client must provide accurate information',
    required: false,
    group: 'client-responsibilities',
  },
  {
    id: 'recordOrganization',
    type: 'checkbox',
    label: 'Client responsible for record organization',
    required: false,
    group: 'client-responsibilities',
  },
  {
    id: 'promptCommunication',
    type: 'checkbox',
    label: 'Client must communicate promptly',
    required: false,
    group: 'client-responsibilities',
  },
  {
    id: 'accessToAccounts',
    type: 'checkbox',
    label: 'Client provides access to accounts',
    required: false,
    group: 'client-responsibilities',
  },
  {
    id: 'softwareAccess',
    type: 'checkbox',
    label: 'Client provides software access',
    required: false,
    group: 'client-responsibilities',
  },
  {
    id: 'timelyService',
    type: 'checkbox',
    label: 'Provider delivers timely service',
    required: false,
    group: 'provider-responsibilities',
  },
  {
    id: 'accurateRecords',
    type: 'checkbox',
    label: 'Provider maintains accurate records',
    required: false,
    group: 'provider-responsibilities',
  },
  {
    id: 'confidentialityMaintenance',
    type: 'checkbox',
    label: 'Provider maintains confidentiality',
    required: false,
    group: 'provider-responsibilities',
  },
  {
    id: 'professionalStandards',
    type: 'checkbox',
    label: 'Provider follows professional standards',
    required: false,
    group: 'provider-responsibilities',
  },
  {
    id: 'regulatoryCompliance',
    type: 'checkbox',
    label: 'Provider ensures regulatory compliance',
    required: false,
    group: 'provider-responsibilities',
  },
  {
    id: 'backupServices',
    type: 'checkbox',
    label: 'Provider maintains backup services',
    required: false,
    group: 'provider-responsibilities',
  },
  {
    id: 'monthlyReports',
    type: 'checkbox',
    label: 'Provide monthly reports',
    required: false,
    group: 'deliverables',
  },
  {
    id: 'quarterlyReports',
    type: 'checkbox',
    label: 'Provide quarterly reports',
    required: false,
    group: 'deliverables',
  },
  {
    id: 'annualReports',
    type: 'checkbox',
    label: 'Provide annual reports',
    required: false,
    group: 'deliverables',
  },
  {
    id: 'customReports',
    type: 'checkbox',
    label: 'Provide custom reports',
    required: false,
    group: 'deliverables',
  },
  {
    id: 'dashboardAccess',
    type: 'checkbox',
    label: 'Provide dashboard access',
    required: false,
    group: 'deliverables',
  },
  {
    id: 'reportDeliveryMethod',
    type: 'select',
    label: 'Report Delivery Method',
    options: [
      { value: 'email', label: 'Email' },
      { value: 'portal', label: 'Client Portal' },
      { value: 'mail', label: 'Mail' },
      { value: 'in-person', label: 'In-Person' },
    ],
    required: true,
    group: 'deliverables',
  },
  {
    id: 'clientDataAccess',
    type: 'checkbox',
    label: 'Client has data access rights',
    required: false,
    group: 'data-security',
  },
  {
    id: 'dataEncryption',
    type: 'checkbox',
    label: 'Use data encryption',
    required: false,
    group: 'data-security',
  },
  {
    id: 'secureTransmission',
    type: 'checkbox',
    label: 'Use secure data transmission',
    required: false,
    group: 'data-security',
  },
  {
    id: 'passwordProtection',
    type: 'checkbox',
    label: 'Use password protection',
    required: false,
    group: 'data-security',
  },
  {
    id: 'dataRetentionPeriod',
    type: 'text',
    label: 'Data Retention Period',
    placeholder: 'How long data will be retained',
    required: false,
    group: 'data-security',
  },
  {
    id: 'recordRetentionPeriod',
    type: 'text',
    label: 'Record Retention Period',
    placeholder: 'How long records will be kept',
    required: false,
    group: 'records',
  },
  {
    id: 'clientRecordReturn',
    type: 'checkbox',
    label: 'Return client records upon request',
    required: false,
    group: 'records',
  },
  {
    id: 'providerRecordKeeping',
    type: 'checkbox',
    label: 'Provider maintains own records',
    required: false,
    group: 'records',
  },
  {
    id: 'digitalRecords',
    type: 'checkbox',
    label: 'Allow digital record keeping',
    required: false,
    group: 'records',
  },
  {
    id: 'physicalRecords',
    type: 'checkbox',
    label: 'Maintain physical records',
    required: false,
    group: 'records',
  },
  {
    id: 'primaryContact',
    type: 'text',
    label: 'Primary Contact',
    placeholder: 'Name of primary contact person',
    required: false,
    group: 'communication',
  },
  {
    id: 'communicationMethod',
    type: 'select',
    label: 'Primary Communication Method',
    options: [
      { value: 'phone', label: 'Phone' },
      { value: 'email', label: 'Email' },
      { value: 'portal', label: 'Client Portal' },
      { value: 'in-person', label: 'In-Person' },
    ],
    required: true,
    group: 'communication',
  },
  {
    id: 'responseTimeframe',
    type: 'text',
    label: 'Response Timeframe',
    placeholder: 'Expected response time',
    required: false,
    group: 'communication',
  },
  {
    id: 'meetingSchedule',
    type: 'select',
    label: 'Meeting Schedule',
    options: [
      { value: 'weekly', label: 'Weekly' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
      { value: 'as-needed', label: 'As Needed' },
    ],
    required: true,
    group: 'communication',
  },
  {
    id: 'emergencyContact',
    type: 'checkbox',
    label: 'Provide emergency contact option',
    required: false,
    group: 'communication',
  },
  {
    id: 'confidentialityClause',
    type: 'checkbox',
    label: 'Include confidentiality clause',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'clientPrivilege',
    type: 'checkbox',
    label: 'Include client privilege protection',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'thirdPartyDisclosure',
    type: 'checkbox',
    label: 'Allow third-party disclosure',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'governmentDisclosure',
    type: 'checkbox',
    label: 'Allow government disclosure as required',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'confidentialityDuration',
    type: 'text',
    label: 'Confidentiality Duration',
    placeholder: 'How long confidentiality lasts',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'liabilityLimitation',
    type: 'checkbox',
    label: 'Include liability limitation',
    required: false,
    group: 'liability',
  },
  {
    id: 'liabilityScope',
    type: 'select',
    label: 'Liability Scope',
    options: [
      { value: 'negligence', label: 'Negligence Only' },
      { value: 'errors-omissions', label: 'Errors and Omissions' },
      { value: 'full-liability', label: 'Full Liability' },
    ],
    required: true,
    group: 'liability',
  },
  {
    id: 'insuranceRequirement',
    type: 'checkbox',
    label: 'Require professional insurance',
    required: false,
    group: 'liability',
  },
  {
    id: 'insuranceAmount',
    type: 'text',
    label: 'Insurance Amount',
    placeholder: 'Required insurance coverage amount',
    required: false,
    group: 'liability',
    dependsOn: 'insuranceRequirement',
  },
  {
    id: 'agreementTerm',
    type: 'text',
    label: 'Agreement Term',
    placeholder: 'Length of agreement',
    required: false,
    group: 'term',
  },
  {
    id: 'automaticRenewal',
    type: 'checkbox',
    label: 'Include automatic renewal',
    required: false,
    group: 'term',
  },
  {
    id: 'terminationNotice',
    type: 'text',
    label: 'Termination Notice',
    placeholder: 'Required notice for termination',
    required: false,
    group: 'term',
  },
  {
    id: 'fileTransfer',
    type: 'checkbox',
    label: 'Transfer files upon termination',
    required: false,
    group: 'term',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'negotiation', label: 'Negotiation' },
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'litigation', label: 'Court Litigation' },
    ],
    required: false,
    group: 'legal',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'e.g., State of California',
    required: false,
    group: 'legal',
  },
  {
    id: 'jurisdiction',
    type: 'text',
    label: 'Jurisdiction',
    placeholder: 'Where disputes will be resolved',
    required: false,
    group: 'legal',
  },
  {
    id: 'attorneyFees',
    type: 'checkbox',
    label: 'Include attorney fees clause',
    required: false,
    group: 'legal',
  },
  {
    id: 'requireProviderSignature',
    type: 'checkbox',
    label: 'Require provider signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireClientSignature',
    type: 'checkbox',
    label: 'Require client signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'witnessRequired',
    type: 'checkbox',
    label: 'Require witness',
    required: false,
    group: 'signatures',
  },
  {
    id: 'notarizationRequired',
    type: 'checkbox',
    label: 'Require notarization',
    required: false,
    group: 'signatures',
  },
  {
    id: 'electronicSignatureAccepted',
    type: 'checkbox',
    label: 'Accept electronic signatures',
    required: false,
    group: 'signatures',
  },
];