// src/lib/documents/us/tenant-maintenance-request/questions.ts
import type { FormQuestion } from '@/types/documents';

export const tenantMaintenanceRequestQuestions: FormQuestion[] = [
  // Tenant Information
  {
    id: 'tenantName',
    type: 'text',
    label: 'Tenant Full Name',
    placeholder: 'Enter your full legal name',
    required: true,
    group: 'tenant',
  },
  {
    id: 'tenantPhone',
    type: 'tel',
    label: 'Tenant Phone Number',
    placeholder: '(555) 123-4567',
    required: true,
    group: 'tenant',
  },
  {
    id: 'tenantEmail',
    type: 'email',
    label: 'Tenant Email',
    placeholder: 'tenant@example.com',
    required: true,
    group: 'tenant',
  },

  // Property Information
  {
    id: 'propertyAddress',
    type: 'textarea',
    label: 'Property Address',
    placeholder: 'Enter the full address of the rental property',
    required: true,
    group: 'property',
  },
  {
    id: 'unitNumber',
    type: 'text',
    label: 'Unit/Apartment Number',
    placeholder: 'e.g., Apt 2B',
    required: false,
    group: 'property',
  },
  {
    id: 'landlordName',
    type: 'text',
    label: 'Landlord Name',
    placeholder: "Enter landlord's full name",
    required: true,
    group: 'property',
  },
  {
    id: 'landlordPhone',
    type: 'tel',
    label: 'Landlord Phone Number',
    placeholder: '(555) 123-4567',
    required: false,
    group: 'property',
  },
  {
    id: 'landlordEmail',
    type: 'email',
    label: 'Landlord Email',
    placeholder: 'landlord@example.com',
    required: false,
    group: 'property',
  },
  {
    id: 'propertyManagerName',
    type: 'text',
    label: 'Property Manager Name (if applicable)',
    placeholder: "Enter property manager's name",
    required: false,
    group: 'property',
  },
  {
    id: 'propertyManagerPhone',
    type: 'tel',
    label: 'Property Manager Phone',
    placeholder: '(555) 123-4567',
    required: false,
    group: 'property',
  },

  // Request Details
  {
    id: 'requestDate',
    type: 'date',
    label: 'Request Date',
    required: true,
    group: 'request',
  },
  {
    id: 'urgencyLevel',
    type: 'select',
    label: 'Urgency Level',
    options: [
      { value: 'emergency', label: 'Emergency (Immediate attention required)' },
      { value: 'urgent', label: 'Urgent (Within 24-48 hours)' },
      { value: 'routine', label: 'Routine (Non-urgent)' },
    ],
    required: true,
    group: 'request',
  },
  {
    id: 'problemCategory',
    type: 'select',
    label: 'Problem Category',
    options: [
      { value: 'plumbing', label: 'Plumbing' },
      { value: 'electrical', label: 'Electrical' },
      { value: 'hvac', label: 'Heating/Cooling (HVAC)' },
      { value: 'appliance', label: 'Appliance' },
      { value: 'structural', label: 'Structural' },
      { value: 'pest', label: 'Pest Control' },
      { value: 'security', label: 'Security/Locks' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'request',
  },
  {
    id: 'problemLocation',
    type: 'text',
    label: 'Problem Location',
    placeholder: 'e.g., Kitchen, Master Bedroom, Bathroom',
    required: true,
    group: 'request',
  },
  {
    id: 'problemDescription',
    type: 'textarea',
    label: 'Detailed Problem Description',
    placeholder: 'Please describe the issue in detail...',
    required: true,
    group: 'request',
  },

  // Detailed Issues
  {
    id: 'waterLeak',
    type: 'checkbox',
    label: 'Water leak or flooding',
    required: false,
    group: 'issues',
  },
  {
    id: 'noPower',
    type: 'checkbox',
    label: 'No electricity/power outage',
    required: false,
    group: 'issues',
  },
  {
    id: 'noHeat',
    type: 'checkbox',
    label: 'No heat',
    required: false,
    group: 'issues',
  },
  {
    id: 'noAC',
    type: 'checkbox',
    label: 'No air conditioning',
    required: false,
    group: 'issues',
  },
  {
    id: 'brokenAppliance',
    type: 'checkbox',
    label: 'Broken appliance',
    required: false,
    group: 'issues',
  },
  {
    id: 'pestInfestation',
    type: 'checkbox',
    label: 'Pest infestation',
    required: false,
    group: 'issues',
  },
  {
    id: 'brokenLock',
    type: 'checkbox',
    label: 'Broken lock or security issue',
    required: false,
    group: 'issues',
  },
  {
    id: 'otherIssue',
    type: 'checkbox',
    label: 'Other issue',
    required: false,
    group: 'issues',
  },

  // Additional Information
  {
    id: 'howLongProblem',
    type: 'text',
    label: 'How long has this problem existed?',
    placeholder: 'e.g., 2 days, 1 week',
    required: false,
    group: 'additional',
  },
  {
    id: 'previouslyReported',
    type: 'checkbox',
    label: 'This issue has been previously reported',
    required: false,
    group: 'additional',
  },
  {
    id: 'previousReportDate',
    type: 'date',
    label: 'Previous Report Date',
    required: false,
    group: 'additional',
    dependsOn: 'previouslyReported',
  },
  {
    id: 'attemptedRepairs',
    type: 'textarea',
    label: "Any repairs you've attempted",
    placeholder: 'Describe any attempts to fix the issue...',
    required: false,
    group: 'additional',
  },

  // Access Information
  {
    id: 'preferredContactMethod',
    type: 'select',
    label: 'Preferred Contact Method',
    options: [
      { value: 'phone', label: 'Phone' },
      { value: 'email', label: 'Email' },
      { value: 'text', label: 'Text Message' },
    ],
    required: true,
    group: 'access',
  },
  {
    id: 'bestTimeToContact',
    type: 'text',
    label: 'Best Time to Contact',
    placeholder: 'e.g., Weekdays 9AM-5PM',
    required: false,
    group: 'access',
  },
  {
    id: 'accessInstructions',
    type: 'textarea',
    label: 'Special Access Instructions',
    placeholder: 'Any special instructions for accessing the property...',
    required: false,
    group: 'access',
  },
  {
    id: 'petsPresent',
    type: 'checkbox',
    label: 'Pets present in the unit',
    required: false,
    group: 'access',
  },
  {
    id: 'petDetails',
    type: 'text',
    label: 'Pet Details',
    placeholder: 'Type and location of pets',
    required: false,
    group: 'access',
    dependsOn: 'petsPresent',
  },

  // Emergency Contact
  {
    id: 'emergencyContactName',
    type: 'text',
    label: 'Emergency Contact Name',
    placeholder: 'Name of emergency contact',
    required: false,
    group: 'emergency',
  },
  {
    id: 'emergencyContactPhone',
    type: 'tel',
    label: 'Emergency Contact Phone',
    placeholder: '(555) 123-4567',
    required: false,
    group: 'emergency',
  },

  // Documentation
  {
    id: 'photosAvailable',
    type: 'checkbox',
    label: 'I have photos of the issue',
    required: false,
    group: 'documentation',
  },
  {
    id: 'videoAvailable',
    type: 'checkbox',
    label: 'I have video of the issue',
    required: false,
    group: 'documentation',
  },
  {
    id: 'additionalNotes',
    type: 'textarea',
    label: 'Additional Notes',
    placeholder: 'Any other relevant information...',
    required: false,
    group: 'documentation',
  },
];
