// src/lib/documents/us/letter-of-intent/questions.ts
import type { FormQuestion } from '@/types/documents';

export const letterOfIntentQuestions: FormQuestion[] = [
  {
    id: 'intentType',
    type: 'select',
    label: 'Type of Intent',
    options: [
      { value: 'purchase', label: 'Purchase/Acquisition' },
      { value: 'partnership', label: 'Business Partnership' },
      { value: 'merger', label: 'Merger' },
      { value: 'joint-venture', label: 'Joint Venture' },
      { value: 'licensing', label: 'Licensing Agreement' },
      { value: 'employment', label: 'Employment' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'intent',
  },
  {
    id: 'subject',
    type: 'text',
    label: 'Letter Subject',
    placeholder: 'e.g., Letter of Intent for Business Acquisition',
    required: true,
    group: 'basic',
  },
  {
    id: 'letterDate',
    type: 'date',
    label: 'Letter Date',
    required: true,
    group: 'basic',
  },
  {
    id: 'senderName',
    type: 'text',
    label: 'Your Name',
    placeholder: 'Enter your full name',
    required: true,
    group: 'sender',
  },
  {
    id: 'senderTitle',
    type: 'text',
    label: 'Your Title',
    placeholder: 'e.g., CEO, President, Owner',
    required: false,
    group: 'sender',
  },
  {
    id: 'senderCompany',
    type: 'text',
    label: 'Your Company',
    placeholder: 'Enter your company name',
    required: false,
    group: 'sender',
  },
  {
    id: 'senderAddress',
    type: 'textarea',
    label: 'Your Address',
    placeholder: 'Enter your complete address',
    required: true,
    group: 'sender',
  },
  {
    id: 'senderPhone',
    type: 'tel',
    label: 'Your Phone',
    placeholder: '(555) 123-4567',
    required: false,
    group: 'sender',
  },
  {
    id: 'senderEmail',
    type: 'email',
    label: 'Your Email',
    placeholder: 'your@email.com',
    required: false,
    group: 'sender',
  },
  {
    id: 'recipientName',
    type: 'text',
    label: 'Recipient Name',
    placeholder: 'Enter recipient full name',
    required: true,
    group: 'recipient',
  },
  {
    id: 'recipientTitle',
    type: 'text',
    label: 'Recipient Title',
    placeholder: 'e.g., CEO, President, Owner',
    required: false,
    group: 'recipient',
  },
  {
    id: 'recipientCompany',
    type: 'text',
    label: 'Recipient Company',
    placeholder: 'Enter recipient company name',
    required: false,
    group: 'recipient',
  },
  {
    id: 'recipientAddress',
    type: 'textarea',
    label: 'Recipient Address',
    placeholder: 'Enter recipient complete address',
    required: true,
    group: 'recipient',
  },
  {
    id: 'transactionDescription',
    type: 'textarea',
    label: 'Transaction Description',
    placeholder: 'Describe the proposed transaction or business arrangement',
    required: true,
    group: 'transaction',
  },
  {
    id: 'proposedTerms',
    type: 'textarea',
    label: 'Proposed Terms',
    placeholder: 'Outline the key terms of the proposed arrangement',
    required: false,
    group: 'transaction',
  },
  {
    id: 'timeframe',
    type: 'text',
    label: 'Proposed Timeframe',
    placeholder: 'e.g., 90 days, 6 months',
    required: false,
    group: 'transaction',
  },
  {
    id: 'conditions',
    type: 'textarea',
    label: 'Conditions',
    placeholder: 'List any conditions that must be met',
    required: false,
    group: 'transaction',
  },
  {
    id: 'hasFinancialTerms',
    type: 'checkbox',
    label: 'Include financial terms',
    required: false,
    group: 'financial',
  },
  {
    id: 'proposedPrice',
    type: 'number',
    label: 'Proposed Price ($)',
    placeholder: '100000',
    required: false,
    group: 'financial',
    dependsOn: 'hasFinancialTerms',
  },
  {
    id: 'paymentTerms',
    type: 'textarea',
    label: 'Payment Terms',
    placeholder: 'Describe proposed payment structure',
    required: false,
    group: 'financial',
    dependsOn: 'hasFinancialTerms',
  },
  {
    id: 'dueDiligencePeriod',
    type: 'text',
    label: 'Due Diligence Period',
    placeholder: 'e.g., 30 days, 60 days',
    required: false,
    group: 'due-diligence',
  },
  {
    id: 'dueDiligenceConditions',
    type: 'textarea',
    label: 'Due Diligence Conditions',
    placeholder: 'Specify what due diligence will include',
    required: false,
    group: 'due-diligence',
  },
  {
    id: 'exclusivityPeriod',
    type: 'text',
    label: 'Exclusivity Period',
    placeholder: 'e.g., 60 days, 90 days',
    required: false,
    group: 'exclusivity',
  },
  {
    id: 'exclusivityTerms',
    type: 'textarea',
    label: 'Exclusivity Terms',
    placeholder: 'Describe the exclusivity arrangement',
    required: false,
    group: 'exclusivity',
  },
  {
    id: 'confidentialityClause',
    type: 'checkbox',
    label: 'Include confidentiality clause',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'confidentialityTerms',
    type: 'textarea',
    label: 'Confidentiality Terms',
    placeholder: 'Describe confidentiality obligations',
    required: false,
    group: 'confidentiality',
    dependsOn: 'confidentialityClause',
  },
  {
    id: 'nextSteps',
    type: 'textarea',
    label: 'Next Steps',
    placeholder: 'Outline the next steps in the process',
    required: false,
    group: 'next-steps',
  },
  {
    id: 'proposedMeetingDate',
    type: 'date',
    label: 'Proposed Meeting Date',
    required: false,
    group: 'next-steps',
  },
  {
    id: 'responseDeadline',
    type: 'date',
    label: 'Response Deadline',
    required: false,
    group: 'next-steps',
  },
  {
    id: 'bindingStatement',
    type: 'select',
    label: 'Binding Nature',
    options: [
      { value: 'non-binding', label: 'Non-binding (Intent Only)' },
      { value: 'partially-binding', label: 'Partially Binding' },
      { value: 'binding', label: 'Fully Binding' },
    ],
    required: false,
    group: 'legal',
  },
  {
    id: 'legalDisclaimer',
    type: 'textarea',
    label: 'Legal Disclaimer',
    placeholder: 'Add any legal disclaimers or clarifications',
    required: false,
    group: 'legal',
  },
  {
    id: 'additionalTerms',
    type: 'textarea',
    label: 'Additional Terms',
    placeholder: 'Any additional terms or special provisions',
    required: false,
    group: 'additional',
  },
];