import type { Question } from '@/types/documents';

export const questions: Question[] = [
  {
    id: 'trustorOneName',
    label: 'First Spouse Full Name',
    type: 'text',
    required: true,
    placeholder: 'Enter the full legal name of the first spouse',
  },
  {
    id: 'trustorTwoName',
    label: 'Second Spouse Full Name',
    type: 'text',
    required: true,
    placeholder: 'Enter the full legal name of the second spouse',
  },
  {
    id: 'trustName',
    label: 'Joint Trust Name',
    type: 'text',
    required: true,
    placeholder: 'e.g., The Smith Family Trust',
  },
  {
    id: 'trustDate',
    label: 'Trust Creation Date',
    type: 'date',
    required: true,
  },
  {
    id: 'marriageDate',
    label: 'Marriage Date',
    type: 'date',
    required: true,
  },
  {
    id: 'marriageState',
    label: 'State Where Married',
    type: 'text',
    required: true,
    placeholder: 'State where the marriage took place',
  },
  {
    id: 'trustorOneAddress',
    label: 'First Spouse Address',
    type: 'textarea',
    required: true,
    placeholder: 'Complete address of first spouse',
  },
  {
    id: 'trustorTwoAddress',
    label: 'Second Spouse Address',
    type: 'textarea',
    required: true,
    placeholder: 'Complete address of second spouse',
  },
  {
    id: 'initialTrustees',
    label: 'Initial Trustees',
    type: 'text',
    required: true,
    placeholder: 'Usually both spouses serve as initial co-trustees',
  },
  {
    id: 'successorTrustee',
    label: 'Successor Trustee Full Name',
    type: 'text',
    required: true,
    placeholder: 'Person to serve as trustee if both spouses are unable',
  },
  {
    id: 'successorTrusteeAddress',
    label: 'Successor Trustee Address',
    type: 'textarea',
    required: true,
    placeholder: 'Complete address of successor trustee',
  },
  {
    id: 'backupSuccessorTrustee',
    label: 'Backup Successor Trustee (Optional)',
    type: 'text',
    placeholder: 'Alternative successor trustee',
  },
  {
    id: 'backupSuccessorTrusteeAddress',
    label: 'Backup Successor Trustee Address (Optional)',
    type: 'textarea',
    placeholder: 'Complete address of backup successor trustee',
  },
  {
    id: 'trustPurpose',
    label: 'Trust Purpose',
    type: 'textarea',
    required: true,
    placeholder: 'Describe the purpose and goals of the joint trust',
  },
  {
    id: 'jointAssets',
    label: 'Joint Assets to be Placed in Trust',
    type: 'textarea',
    required: true,
    placeholder:
      'Describe all joint assets including real estate, bank accounts, investments, etc.',
  },
  {
    id: 'separateAssetsSpouseOne',
    label: 'First Spouse Separate Assets (Optional)',
    type: 'textarea',
    placeholder: 'Any separate property of first spouse to be included',
  },
  {
    id: 'separateAssetsSpouseTwo',
    label: 'Second Spouse Separate Assets (Optional)',
    type: 'textarea',
    placeholder: 'Any separate property of second spouse to be included',
  },
  {
    id: 'distributionDuringLifetime',
    label: "Distribution Terms During Both Spouses' Lifetime",
    type: 'textarea',
    required: true,
    placeholder: 'How trust assets may be used while both spouses are alive',
  },
  {
    id: 'distributionUponFirstDeath',
    label: 'Distribution Upon First Spouse Death',
    type: 'textarea',
    required: true,
    placeholder: 'How assets are handled when the first spouse dies',
  },
  {
    id: 'distributionUponSecondDeath',
    label: 'Distribution Upon Second Spouse Death',
    type: 'textarea',
    required: true,
    placeholder: 'How remaining assets are distributed to beneficiaries',
  },
  {
    id: 'primaryBeneficiaries',
    label: 'Primary Beneficiaries',
    type: 'textarea',
    required: true,
    placeholder: 'List primary beneficiaries and their shares (children, etc.)',
  },
  {
    id: 'contingentBeneficiaries',
    label: 'Contingent Beneficiaries (Optional)',
    type: 'textarea',
    placeholder:
      'Alternative beneficiaries if primary beneficiaries cannot inherit',
  },
  {
    id: 'incapacityProvisions',
    label: 'Incapacity Provisions',
    type: 'textarea',
    required: true,
    placeholder:
      'Instructions for trust management if one or both spouses become incapacitated',
  },
  {
    id: 'specialProvisions',
    label: 'Special Provisions (Optional)',
    type: 'textarea',
    placeholder: 'Any special instructions, conditions, or provisions',
  },
  {
    id: 'witnessOneName',
    label: 'First Witness Full Name',
    type: 'text',
    required: true,
    placeholder: 'Adult witness to trust signing',
  },
  {
    id: 'witnessOneAddress',
    label: 'First Witness Address',
    type: 'textarea',
    required: true,
    placeholder: 'Complete address of first witness',
  },
  {
    id: 'witnessTwoName',
    label: 'Second Witness Full Name',
    type: 'text',
    required: true,
    placeholder: 'Second adult witness to trust signing',
  },
  {
    id: 'witnessTwoAddress',
    label: 'Second Witness Address',
    type: 'textarea',
    required: true,
    placeholder: 'Complete address of second witness',
  },
  {
    id: 'executionDate',
    label: 'Trust Execution Date',
    type: 'date',
    required: true,
  },
  {
    id: 'executionState',
    label: 'State Where Trust is Executed',
    type: 'text',
    required: true,
    placeholder: 'State where you are signing this trust',
  },
  {
    id: 'executionCounty',
    label: 'County Where Trust is Executed',
    type: 'text',
    required: true,
    placeholder: 'County where you are signing this trust',
  },
];
