// src/lib/documents/us/sales-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const salesAgreementQuestions: FormQuestion[] = [
  {
    id: 'sellerName',
    type: 'text',
    label: 'Seller Name',
    placeholder: 'Enter seller full name or company name',
    required: true,
    group: 'seller',
  },
  {
    id: 'sellerAddress',
    type: 'textarea',
    label: 'Seller Address',
    placeholder: 'Enter seller complete address',
    required: true,
    group: 'seller',
  },
  {
    id: 'sellerPhone',
    type: 'tel',
    label: 'Seller Phone',
    placeholder: '(555) 123-4567',
    required: false,
    group: 'seller',
  },
  {
    id: 'sellerEmail',
    type: 'email',
    label: 'Seller Email',
    placeholder: 'seller@email.com',
    required: false,
    group: 'seller',
  },
  {
    id: 'buyerName',
    type: 'text',
    label: 'Buyer Name',
    placeholder: 'Enter buyer full name or company name',
    required: true,
    group: 'buyer',
  },
  {
    id: 'buyerAddress',
    type: 'textarea',
    label: 'Buyer Address',
    placeholder: 'Enter buyer complete address',
    required: true,
    group: 'buyer',
  },
  {
    id: 'buyerPhone',
    type: 'tel',
    label: 'Buyer Phone',
    placeholder: '(555) 123-4567',
    required: false,
    group: 'buyer',
  },
  {
    id: 'buyerEmail',
    type: 'email',
    label: 'Buyer Email',
    placeholder: 'buyer@email.com',
    required: false,
    group: 'buyer',
  },
  {
    id: 'productDescription',
    type: 'textarea',
    label: 'Product Description',
    placeholder: 'Provide detailed description of the product(s) being sold',
    required: true,
    group: 'product',
  },
  {
    id: 'productCategory',
    type: 'select',
    label: 'Product Category',
    options: [
      { value: 'electronics', label: 'Electronics' },
      { value: 'furniture', label: 'Furniture' },
      { value: 'vehicle', label: 'Vehicle' },
      { value: 'equipment', label: 'Equipment/Machinery' },
      { value: 'inventory', label: 'Business Inventory' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'product',
  },
  {
    id: 'quantity',
    type: 'number',
    label: 'Quantity',
    placeholder: '1',
    required: true,
    group: 'product',
  },
  {
    id: 'unitOfMeasure',
    type: 'text',
    label: 'Unit of Measure',
    placeholder: 'e.g., pieces, pounds, gallons',
    required: false,
    group: 'product',
  },
  {
    id: 'productCondition',
    type: 'select',
    label: 'Product Condition',
    options: [
      { value: 'new', label: 'New' },
      { value: 'used', label: 'Used' },
      { value: 'refurbished', label: 'Refurbished' },
      { value: 'as-is', label: 'As-Is' },
    ],
    required: true,
    group: 'product',
  },
  {
    id: 'unitPrice',
    type: 'number',
    label: 'Unit Price ($)',
    placeholder: '100.00',
    required: true,
    group: 'pricing',
  },
  {
    id: 'totalPrice',
    type: 'number',
    label: 'Total Price ($)',
    placeholder: '1000.00',
    required: true,
    group: 'pricing',
  },
  {
    id: 'taxesIncluded',
    type: 'checkbox',
    label: 'Taxes included in price',
    required: false,
    group: 'pricing',
  },
  {
    id: 'salesTax',
    type: 'number',
    label: 'Sales Tax Amount ($)',
    placeholder: '80.00',
    required: false,
    group: 'pricing',
  },
  {
    id: 'paymentMethod',
    type: 'select',
    label: 'Payment Method',
    options: [
      { value: 'cash', label: 'Cash' },
      { value: 'check', label: 'Check' },
      { value: 'wire-transfer', label: 'Wire Transfer' },
      { value: 'credit-card', label: 'Credit Card' },
      { value: 'financing', label: 'Financing' },
    ],
    required: true,
    group: 'payment',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'full-upfront', label: 'Full Payment Upfront' },
      { value: 'deposit-and-balance', label: 'Deposit + Balance' },
      { value: 'installments', label: 'Installment Payments' },
    ],
    required: true,
    group: 'payment',
  },
  {
    id: 'depositAmount',
    type: 'number',
    label: 'Deposit Amount ($)',
    placeholder: '200.00',
    required: false,
    group: 'payment',
  },
  {
    id: 'paymentDueDate',
    type: 'date',
    label: 'Payment Due Date',
    required: false,
    group: 'payment',
  },
  {
    id: 'deliveryRequired',
    type: 'checkbox',
    label: 'Delivery is required',
    required: false,
    group: 'delivery',
  },
  {
    id: 'deliveryAddress',
    type: 'textarea',
    label: 'Delivery Address',
    placeholder: 'Enter delivery address if different from buyer address',
    required: false,
    group: 'delivery',
    dependsOn: 'deliveryRequired',
  },
  {
    id: 'deliveryDate',
    type: 'date',
    label: 'Delivery Date',
    required: false,
    group: 'delivery',
    dependsOn: 'deliveryRequired',
  },
  {
    id: 'deliveryMethod',
    type: 'text',
    label: 'Delivery Method',
    placeholder: 'e.g., UPS, FedEx, Personal Delivery',
    required: false,
    group: 'delivery',
    dependsOn: 'deliveryRequired',
  },
  {
    id: 'deliveryCost',
    type: 'number',
    label: 'Delivery Cost ($)',
    placeholder: '50.00',
    required: false,
    group: 'delivery',
    dependsOn: 'deliveryRequired',
  },
  {
    id: 'warrantyOffered',
    type: 'checkbox',
    label: 'Warranty is offered',
    required: false,
    group: 'warranty',
  },
  {
    id: 'warrantyPeriod',
    type: 'text',
    label: 'Warranty Period',
    placeholder: 'e.g., 1 year, 90 days',
    required: false,
    group: 'warranty',
    dependsOn: 'warrantyOffered',
  },
  {
    id: 'warrantyTerms',
    type: 'textarea',
    label: 'Warranty Terms',
    placeholder: 'Describe what the warranty covers',
    required: false,
    group: 'warranty',
    dependsOn: 'warrantyOffered',
  },
  {
    id: 'inspectionPeriod',
    type: 'text',
    label: 'Inspection Period',
    placeholder: 'e.g., 7 days, 30 days',
    required: false,
    group: 'inspection',
  },
  {
    id: 'returnPolicy',
    type: 'checkbox',
    label: 'Returns are allowed',
    required: false,
    group: 'returns',
  },
  {
    id: 'returnPeriod',
    type: 'text',
    label: 'Return Period',
    placeholder: 'e.g., 30 days, 14 days',
    required: false,
    group: 'returns',
    dependsOn: 'returnPolicy',
  },
  {
    id: 'returnConditions',
    type: 'textarea',
    label: 'Return Conditions',
    placeholder: 'Specify conditions for returns',
    required: false,
    group: 'returns',
    dependsOn: 'returnPolicy',
  },
  {
    id: 'specialConditions',
    type: 'textarea',
    label: 'Special Conditions',
    placeholder: 'Any special terms or conditions',
    required: false,
    group: 'additional',
  },
  {
    id: 'additionalTerms',
    type: 'textarea',
    label: 'Additional Terms',
    placeholder: 'Any additional terms or provisions',
    required: false,
    group: 'additional',
  },
];