// src/lib/documents/us/affiliate-marketing-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const affiliateMarketingAgreementQuestions: FormQuestion[] = [
  {
    id: 'merchantName',
    type: 'text',
    label: 'Merchant Name',
    placeholder: 'Enter merchant or company name',
    required: true,
    group: 'merchant',
  },
  {
    id: 'merchantCompanyName',
    type: 'text',
    label: 'Merchant Company Name',
    placeholder: 'Enter legal company name if different',
    required: false,
    group: 'merchant',
  },
  {
    id: 'merchantAddress',
    type: 'text',
    label: 'Merchant Address',
    placeholder: 'Enter complete business address',
    required: true,
    group: 'merchant',
  },
  {
    id: 'merchantWebsite',
    type: 'text',
    label: 'Merchant Website',
    placeholder: 'Enter website URL',
    required: true,
    group: 'merchant',
  },
  {
    id: 'affiliateName',
    type: 'text',
    label: 'Affiliate Name',
    placeholder: 'Enter affiliate name',
    required: true,
    group: 'affiliate',
  },
  {
    id: 'affiliateAddress',
    type: 'text',
    label: 'Affiliate Address',
    placeholder: 'Enter complete address',
    required: true,
    group: 'affiliate',
  },
  {
    id: 'programName',
    type: 'text',
    label: 'Program Name',
    placeholder: 'Enter affiliate program name',
    required: true,
    group: 'program',
  },
  {
    id: 'programDescription',
    type: 'textarea',
    label: 'Program Description',
    placeholder: 'Describe the affiliate program',
    required: true,
    group: 'program',
  },
  {
    id: 'commissionType',
    type: 'select',
    label: 'Commission Type',
    options: [
      { value: 'percentage', label: 'Percentage' },
      { value: 'fixed', label: 'Fixed Amount' },
      { value: 'tiered', label: 'Tiered Structure' },
      { value: 'hybrid', label: 'Hybrid' },
    ],
    required: true,
    group: 'commission',
  },
  {
    id: 'commissionRate',
    type: 'text',
    label: 'Commission Rate',
    placeholder: 'e.g., 10% or $50',
    required: false,
    group: 'commission',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'weekly', label: 'Weekly' },
      { value: 'bi-weekly', label: 'Bi-weekly' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
    ],
    required: true,
    group: 'payment',
  },
  {
    id: 'minimumPayoutThreshold',
    type: 'text',
    label: 'Minimum Payout Threshold',
    placeholder: 'Minimum amount before payment',
    required: false,
    group: 'payment',
  },
  {
    id: 'trackingMethod',
    type: 'select',
    label: 'Tracking Method',
    options: [
      { value: 'cookies', label: 'Cookies' },
      { value: 'links', label: 'Tracking Links' },
      { value: 'codes', label: 'Promo Codes' },
      { value: 'pixels', label: 'Tracking Pixels' },
    ],
    required: true,
    group: 'tracking',
  },
  {
    id: 'cookieDuration',
    type: 'text',
    label: 'Cookie Duration',
    placeholder: 'e.g., 30 days',
    required: false,
    group: 'tracking',
  },
];
