// src/lib/documents/us/mechanics-lien/questions.ts
import type { FormQuestion } from '@/types/documents';

export const mechanicsLienQuestions: FormQuestion[] = [
  {
    id: 'claimantName',
    type: 'text',
    label: 'Claimant Name',
    placeholder: 'Enter name of person/company filing lien',
    required: true,
    group: 'claimant',
  },
  {
    id: 'claimantAddress',
    type: 'text',
    label: 'Claimant Address',
    placeholder: 'Enter complete claimant address',
    required: true,
    group: 'claimant',
  },
  {
    id: 'claimantPhone',
    type: 'text',
    label: 'Claimant Phone',
    placeholder: 'Enter phone number',
    required: true,
    group: 'claimant',
  },
  {
    id: 'claimantTitle',
    type: 'text',
    label: 'Claimant Title/Capacity',
    placeholder: 'e.g., Owner, President, Authorized Agent',
    required: true,
    group: 'claimant',
  },
  {
    id: 'ownerName',
    type: 'text',
    label: 'Property Owner Name',
    placeholder: 'Enter property owner name',
    required: true,
    group: 'owner',
  },
  {
    id: 'ownerAddress',
    type: 'text',
    label: 'Property Owner Address',
    placeholder: 'Enter property owner address',
    required: true,
    group: 'owner',
  },
  {
    id: 'propertyAddress',
    type: 'text',
    label: 'Property Address',
    placeholder: 'Address where work was performed',
    required: true,
    group: 'property',
  },
  {
    id: 'propertyDescription',
    type: 'textarea',
    label: 'Property Description',
    placeholder: 'Detailed description of the property',
    required: true,
    group: 'property',
  },
  {
    id: 'county',
    type: 'text',
    label: 'County',
    placeholder: 'County where property is located',
    required: true,
    group: 'property',
  },
  {
    id: 'state',
    type: 'text',
    label: 'State',
    placeholder: 'State where property is located',
    required: true,
    group: 'property',
  },
  {
    id: 'workDescription',
    type: 'textarea',
    label: 'Work Description',
    placeholder: 'Detailed description of work performed or materials supplied',
    required: true,
    group: 'work',
  },
  {
    id: 'workType',
    type: 'select',
    label: 'Type of Work',
    options: [
      { value: 'labor', label: 'Labor Only' },
      { value: 'materials', label: 'Materials Only' },
      { value: 'equipment', label: 'Equipment Rental' },
      { value: 'labor-and-materials', label: 'Labor and Materials' },
      { value: 'professional-services', label: 'Professional Services' },
    ],
    required: true,
    group: 'work',
  },
  {
    id: 'workStartDate',
    type: 'date',
    label: 'Work Start Date',
    required: true,
    group: 'work',
  },
  {
    id: 'workEndDate',
    type: 'date',
    label: 'Work End Date',
    required: true,
    group: 'work',
  },
  {
    id: 'lastWorkDate',
    type: 'date',
    label: 'Last Date Work Performed',
    required: true,
    group: 'work',
  },
  {
    id: 'relationshipToOwner',
    type: 'select',
    label: 'Relationship to Property Owner',
    options: [
      { value: 'direct-contract', label: 'Direct Contract with Owner' },
      { value: 'subcontractor', label: 'Subcontractor' },
      { value: 'sub-subcontractor', label: 'Sub-subcontractor' },
      { value: 'material-supplier', label: 'Material Supplier' },
    ],
    required: true,
    group: 'contract',
  },
  {
    id: 'contractorName',
    type: 'text',
    label: 'General Contractor Name',
    placeholder: 'Name of general contractor (if applicable)',
    required: false,
    group: 'contract',
  },
  {
    id: 'totalAmountOwed',
    type: 'text',
    label: 'Total Amount Owed',
    placeholder: 'Total amount owed for work/materials',
    required: true,
    group: 'financial',
  },
  {
    id: 'amountPaid',
    type: 'text',
    label: 'Amount Paid',
    placeholder: 'Amount already paid (if any)',
    required: false,
    group: 'financial',
  },
  {
    id: 'balanceDue',
    type: 'text',
    label: 'Balance Due',
    placeholder: 'Remaining balance owed',
    required: true,
    group: 'financial',
  },
  {
    id: 'lienAmount',
    type: 'text',
    label: 'Lien Amount',
    placeholder: 'Amount of lien claim',
    required: true,
    group: 'lien',
  },
  {
    id: 'firstFurnishedDate',
    type: 'date',
    label: 'First Date Work/Materials Furnished',
    required: true,
    group: 'lien',
  },
  {
    id: 'lastFurnishedDate',
    type: 'date',
    label: 'Last Date Work/Materials Furnished',
    required: true,
    group: 'lien',
  },
  {
    id: 'preliminaryNoticeServed',
    type: 'checkbox',
    label: 'Preliminary notice was served',
    required: false,
    group: 'notices',
  },
  {
    id: 'preliminaryNoticeDate',
    type: 'date',
    label: 'Preliminary Notice Date',
    required: false,
    group: 'notices',
    dependsOn: 'preliminaryNoticeServed',
  },
  {
    id: 'demandForPaymentServed',
    type: 'checkbox',
    label: 'Demand for payment was served',
    required: false,
    group: 'notices',
  },
  {
    id: 'demandForPaymentDate',
    type: 'date',
    label: 'Demand for Payment Date',
    required: false,
    group: 'notices',
    dependsOn: 'demandForPaymentServed',
  },
  {
    id: 'contractAttached',
    type: 'checkbox',
    label: 'Contract documents attached',
    required: false,
    group: 'documentation',
  },
  {
    id: 'invoicesAttached',
    type: 'checkbox',
    label: 'Invoices attached',
    required: false,
    group: 'documentation',
  },
  {
    id: 'workOrdersAttached',
    type: 'checkbox',
    label: 'Work orders attached',
    required: false,
    group: 'documentation',
  },
  {
    id: 'attorneyFees',
    type: 'checkbox',
    label: 'Claim attorney fees',
    required: false,
    group: 'additional-claims',
  },
  {
    id: 'courtCosts',
    type: 'checkbox',
    label: 'Claim court costs',
    required: false,
    group: 'additional-claims',
  },
  {
    id: 'paymentDeadline',
    type: 'date',
    label: 'Payment Deadline',
    required: false,
    group: 'enforcement',
  },
];
