import type { Question } from '@/types/documents';

export const powerOfAttorneyQuestions: Question[] = [
  // Principal Information
  {
    id: 'principal_name',
    label: "Principal's Full Name (Person granting power)",
    type: 'text',
    required: true,
    placeholder: 'Enter principal full name...',
  },
  {
    id: 'principal_address',
    label: "Principal's Street Address",
    type: 'address',
    required: true,
    placeholder: 'Enter principal street address...',
  },
  {
    id: 'principal_city',
    label: "Principal's City",
    type: 'text',
    required: true,
    placeholder: 'Enter principal city...',
  },
  {
    id: 'principal_state',
    label: "Principal's State",
    type: 'select',
    required: true,
    options: [
      { value: 'Alabama', label: 'Alabama' },
      { value: 'Alaska', label: 'Alaska' },
      { value: 'Arizona', label: 'Arizona' },
      { value: 'Arkansas', label: 'Arkansas' },
      { value: 'California', label: 'California' },
      { value: 'Colorado', label: 'Colorado' },
      { value: 'Connecticut', label: 'Connecticut' },
      { value: 'Delaware', label: 'Delaware' },
      { value: 'Florida', label: 'Florida' },
      { value: 'Georgia', label: 'Georgia' },
      { value: 'Hawaii', label: 'Hawaii' },
      { value: 'Idaho', label: 'Idaho' },
      { value: 'Illinois', label: 'Illinois' },
      { value: 'Indiana', label: 'Indiana' },
      { value: 'Iowa', label: 'Iowa' },
      { value: 'Kansas', label: 'Kansas' },
      { value: 'Kentucky', label: 'Kentucky' },
      { value: 'Louisiana', label: 'Louisiana' },
      { value: 'Maine', label: 'Maine' },
      { value: 'Maryland', label: 'Maryland' },
      { value: 'Massachusetts', label: 'Massachusetts' },
      { value: 'Michigan', label: 'Michigan' },
      { value: 'Minnesota', label: 'Minnesota' },
      { value: 'Mississippi', label: 'Mississippi' },
      { value: 'Missouri', label: 'Missouri' },
      { value: 'Montana', label: 'Montana' },
      { value: 'Nebraska', label: 'Nebraska' },
      { value: 'Nevada', label: 'Nevada' },
      { value: 'New Hampshire', label: 'New Hampshire' },
      { value: 'New Jersey', label: 'New Jersey' },
      { value: 'New Mexico', label: 'New Mexico' },
      { value: 'New York', label: 'New York' },
      { value: 'North Carolina', label: 'North Carolina' },
      { value: 'North Dakota', label: 'North Dakota' },
      { value: 'Ohio', label: 'Ohio' },
      { value: 'Oklahoma', label: 'Oklahoma' },
      { value: 'Oregon', label: 'Oregon' },
      { value: 'Pennsylvania', label: 'Pennsylvania' },
      { value: 'Rhode Island', label: 'Rhode Island' },
      { value: 'South Carolina', label: 'South Carolina' },
      { value: 'South Dakota', label: 'South Dakota' },
      { value: 'Tennessee', label: 'Tennessee' },
      { value: 'Texas', label: 'Texas' },
      { value: 'Utah', label: 'Utah' },
      { value: 'Vermont', label: 'Vermont' },
      { value: 'Virginia', label: 'Virginia' },
      { value: 'Washington', label: 'Washington' },
      { value: 'West Virginia', label: 'West Virginia' },
      { value: 'Wisconsin', label: 'Wisconsin' },
      { value: 'Wyoming', label: 'Wyoming' },
    ],
  },
  {
    id: 'principal_zip',
    label: "Principal's ZIP Code",
    type: 'text',
    required: true,
    placeholder: 'Enter principal ZIP code...',
  },
  {
    id: 'principal_phone',
    label: "Principal's Phone Number",
    type: 'tel',
    required: false,
    placeholder: 'Enter principal phone number...',
  },
  {
    id: 'principal_dob',
    label: "Principal's Date of Birth",
    type: 'date',
    required: false,
    placeholder: 'Select principal date of birth...',
  },
  
  // Agent Information
  {
    id: 'agent_name',
    label: "Agent's Full Name (Attorney-in-Fact)",
    type: 'text',
    required: true,
    placeholder: 'Enter agent full name...',
  },
  {
    id: 'agent_address',
    label: "Agent's Street Address",
    type: 'address',
    required: true,
    placeholder: 'Enter agent street address...',
  },
  {
    id: 'agent_city',
    label: "Agent's City",
    type: 'text',
    required: true,
    placeholder: 'Enter agent city...',
  },
  {
    id: 'agent_state',
    label: "Agent's State",
    type: 'select',
    required: true,
    options: [
      { value: 'Alabama', label: 'Alabama' },
      { value: 'Alaska', label: 'Alaska' },
      { value: 'Arizona', label: 'Arizona' },
      { value: 'Arkansas', label: 'Arkansas' },
      { value: 'California', label: 'California' },
      { value: 'Colorado', label: 'Colorado' },
      { value: 'Connecticut', label: 'Connecticut' },
      { value: 'Delaware', label: 'Delaware' },
      { value: 'Florida', label: 'Florida' },
      { value: 'Georgia', label: 'Georgia' },
      { value: 'Hawaii', label: 'Hawaii' },
      { value: 'Idaho', label: 'Idaho' },
      { value: 'Illinois', label: 'Illinois' },
      { value: 'Indiana', label: 'Indiana' },
      { value: 'Iowa', label: 'Iowa' },
      { value: 'Kansas', label: 'Kansas' },
      { value: 'Kentucky', label: 'Kentucky' },
      { value: 'Louisiana', label: 'Louisiana' },
      { value: 'Maine', label: 'Maine' },
      { value: 'Maryland', label: 'Maryland' },
      { value: 'Massachusetts', label: 'Massachusetts' },
      { value: 'Michigan', label: 'Michigan' },
      { value: 'Minnesota', label: 'Minnesota' },
      { value: 'Mississippi', label: 'Mississippi' },
      { value: 'Missouri', label: 'Missouri' },
      { value: 'Montana', label: 'Montana' },
      { value: 'Nebraska', label: 'Nebraska' },
      { value: 'Nevada', label: 'Nevada' },
      { value: 'New Hampshire', label: 'New Hampshire' },
      { value: 'New Jersey', label: 'New Jersey' },
      { value: 'New Mexico', label: 'New Mexico' },
      { value: 'New York', label: 'New York' },
      { value: 'North Carolina', label: 'North Carolina' },
      { value: 'North Dakota', label: 'North Dakota' },
      { value: 'Ohio', label: 'Ohio' },
      { value: 'Oklahoma', label: 'Oklahoma' },
      { value: 'Oregon', label: 'Oregon' },
      { value: 'Pennsylvania', label: 'Pennsylvania' },
      { value: 'Rhode Island', label: 'Rhode Island' },
      { value: 'South Carolina', label: 'South Carolina' },
      { value: 'South Dakota', label: 'South Dakota' },
      { value: 'Tennessee', label: 'Tennessee' },
      { value: 'Texas', label: 'Texas' },
      { value: 'Utah', label: 'Utah' },
      { value: 'Vermont', label: 'Vermont' },
      { value: 'Virginia', label: 'Virginia' },
      { value: 'Washington', label: 'Washington' },
      { value: 'West Virginia', label: 'West Virginia' },
      { value: 'Wisconsin', label: 'Wisconsin' },
      { value: 'Wyoming', label: 'Wyoming' },
    ],
  },
  {
    id: 'agent_zip',
    label: "Agent's ZIP Code",
    type: 'text',
    required: true,
    placeholder: 'Enter agent ZIP code...',
  },
  {
    id: 'agent_phone',
    label: "Agent's Phone Number",
    type: 'tel',
    required: false,
    placeholder: 'Enter agent phone number...',
  },
  {
    id: 'relationship_to_principal',
    label: "Agent's Relationship to Principal",
    type: 'text',
    required: false,
    placeholder: 'e.g., Spouse, Child, Friend, Attorney...',
  },
  
  // POA Type
  {
    id: 'poa_type',
    label: 'Type of Power of Attorney',
    type: 'select',
    required: true,
    options: [
      { value: 'General', label: 'General Power of Attorney' },
      { value: 'Limited', label: 'Limited Power of Attorney' },
      { value: 'Durable', label: 'Durable Power of Attorney' },
      { value: 'Springing', label: 'Springing Power of Attorney' },
    ],
  },
  
  // Powers
  {
    id: 'general_powers',
    label: 'Grant General Powers (broad authority)',
    type: 'radio',
    required: false,
    options: [
      { value: true, label: 'Yes - General Powers' },
      { value: false, label: 'No - Limited Specific Powers' },
    ],
  },
  
  // Specific Powers
  {
    id: 'banking_powers',
    label: 'Banking and Financial Transactions',
    type: 'radio',
    required: false,
    options: [
      { value: true, label: 'Authorized' },
      { value: false, label: 'Not Authorized' },
    ],
    conditional: { field: 'general_powers', value: false },
  },
  {
    id: 'real_estate_powers',
    label: 'Real Estate Transactions',
    type: 'radio',
    required: false,
    options: [
      { value: true, label: 'Authorized' },
      { value: false, label: 'Not Authorized' },
    ],
    conditional: { field: 'general_powers', value: false },
  },
  {
    id: 'investment_powers',
    label: 'Investment Management',
    type: 'radio',
    required: false,
    options: [
      { value: true, label: 'Authorized' },
      { value: false, label: 'Not Authorized' },
    ],
    conditional: { field: 'general_powers', value: false },
  },
  {
    id: 'business_powers',
    label: 'Business Operations',
    type: 'radio',
    required: false,
    options: [
      { value: true, label: 'Authorized' },
      { value: false, label: 'Not Authorized' },
    ],
    conditional: { field: 'general_powers', value: false },
  },
  
  // Effective Period
  {
    id: 'immediate_effective',
    label: 'When does this POA become effective?',
    type: 'radio',
    required: true,
    options: [
      { value: true, label: 'Immediately upon signing' },
      { value: false, label: 'Only upon specific condition (Springing)' },
    ],
  },
  {
    id: 'springing_condition',
    label: 'Condition for POA to become effective',
    type: 'text',
    required: false,
    placeholder: 'e.g., upon my incapacity as certified by two physicians...',
    conditional: { field: 'immediate_effective', value: false },
  },
  {
    id: 'durable_poa',
    label: 'Is this a Durable POA (remains effective if you become incapacitated)?',
    type: 'radio',
    required: true,
    options: [
      { value: true, label: 'Yes - Durable (continues if incapacitated)' },
      { value: false, label: 'No - Terminates upon incapacity' },
    ],
  },
  
  // Agent Compensation
  {
    id: 'agent_compensation',
    label: 'Should the agent receive compensation?',
    type: 'radio',
    required: false,
    options: [
      { value: true, label: 'Yes' },
      { value: false, label: 'No' },
    ],
  },
  {
    id: 'compensation_terms',
    label: 'Compensation Terms',
    type: 'text',
    required: false,
    placeholder: 'Describe compensation terms...',
    conditional: { field: 'agent_compensation', value: true },
  },
  
  // Gift Limit
  {
    id: 'gift_limit',
    label: 'Annual Gift Limit for Agent',
    type: 'text',
    required: false,
    placeholder: 'e.g., $1,000, $5,000...',
  },
  
  // Healthcare Powers
  {
    id: 'healthcare_powers',
    label: 'Include Healthcare Decision Authority?',
    type: 'radio',
    required: false,
    options: [
      { value: true, label: 'Yes' },
      { value: false, label: 'No' },
    ],
  },
  {
    id: 'healthcare_decision_authority',
    label: 'Healthcare Decision Authority',
    type: 'textarea',
    required: false,
    placeholder: 'Describe healthcare decision-making authority...',
    conditional: { field: 'healthcare_powers', value: true },
  },
  
  // Legal
  {
    id: 'governing_state',
    label: 'Governing State',
    type: 'select',
    required: true,
    options: [
      { value: 'Alabama', label: 'Alabama' },
      { value: 'Alaska', label: 'Alaska' },
      { value: 'Arizona', label: 'Arizona' },
      { value: 'Arkansas', label: 'Arkansas' },
      { value: 'California', label: 'California' },
      { value: 'Colorado', label: 'Colorado' },
      { value: 'Connecticut', label: 'Connecticut' },
      { value: 'Delaware', label: 'Delaware' },
      { value: 'Florida', label: 'Florida' },
      { value: 'Georgia', label: 'Georgia' },
      { value: 'Hawaii', label: 'Hawaii' },
      { value: 'Idaho', label: 'Idaho' },
      { value: 'Illinois', label: 'Illinois' },
      { value: 'Indiana', label: 'Indiana' },
      { value: 'Iowa', label: 'Iowa' },
      { value: 'Kansas', label: 'Kansas' },
      { value: 'Kentucky', label: 'Kentucky' },
      { value: 'Louisiana', label: 'Louisiana' },
      { value: 'Maine', label: 'Maine' },
      { value: 'Maryland', label: 'Maryland' },
      { value: 'Massachusetts', label: 'Massachusetts' },
      { value: 'Michigan', label: 'Michigan' },
      { value: 'Minnesota', label: 'Minnesota' },
      { value: 'Mississippi', label: 'Mississippi' },
      { value: 'Missouri', label: 'Missouri' },
      { value: 'Montana', label: 'Montana' },
      { value: 'Nebraska', label: 'Nebraska' },
      { value: 'Nevada', label: 'Nevada' },
      { value: 'New Hampshire', label: 'New Hampshire' },
      { value: 'New Jersey', label: 'New Jersey' },
      { value: 'New Mexico', label: 'New Mexico' },
      { value: 'New York', label: 'New York' },
      { value: 'North Carolina', label: 'North Carolina' },
      { value: 'North Dakota', label: 'North Dakota' },
      { value: 'Ohio', label: 'Ohio' },
      { value: 'Oklahoma', label: 'Oklahoma' },
      { value: 'Oregon', label: 'Oregon' },
      { value: 'Pennsylvania', label: 'Pennsylvania' },
      { value: 'Rhode Island', label: 'Rhode Island' },
      { value: 'South Carolina', label: 'South Carolina' },
      { value: 'South Dakota', label: 'South Dakota' },
      { value: 'Tennessee', label: 'Tennessee' },
      { value: 'Texas', label: 'Texas' },
      { value: 'Utah', label: 'Utah' },
      { value: 'Vermont', label: 'Vermont' },
      { value: 'Virginia', label: 'Virginia' },
      { value: 'Washington', label: 'Washington' },
      { value: 'West Virginia', label: 'West Virginia' },
      { value: 'Wisconsin', label: 'Wisconsin' },
      { value: 'Wyoming', label: 'Wyoming' },
    ],
  },
  {
    id: 'effective_date',
    label: 'Effective Date',
    type: 'date',
    required: true,
    placeholder: 'Select effective date...',
  },
];