// src/lib/documents/us/travel-insurance-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const travelInsuranceAgreementQuestions: FormQuestion[] = [
  {
    id: 'policyholderName',
    type: 'text',
    label: 'Policyholder Name',
    placeholder: 'Enter policyholder full name',
    required: true,
    group: 'policyholder',
  },
  {
    id: 'policyholderEmail',
    type: 'email',
    label: 'Policyholder Email',
    placeholder: 'Enter email address',
    required: false,
    group: 'policyholder',
  },
  {
    id: 'policyholderDateOfBirth',
    type: 'date',
    label: 'Date of Birth',
    required: false,
    group: 'policyholder',
  },
  {
    id: 'insuranceCompanyName',
    type: 'text',
    label: 'Insurance Company Name',
    placeholder: 'Enter insurance company name',
    required: true,
    group: 'insurance',
  },
  {
    id: 'policyNumber',
    type: 'text',
    label: 'Policy Number',
    placeholder: 'Enter policy number',
    required: false,
    group: 'insurance',
  },
  {
    id: 'travelDestination',
    type: 'text',
    label: 'Travel Destination',
    placeholder: 'Enter destination(s)',
    required: false,
    group: 'travel',
  },
  {
    id: 'travelStartDate',
    type: 'date',
    label: 'Travel Start Date',
    required: false,
    group: 'travel',
  },
  {
    id: 'travelEndDate',
    type: 'date',
    label: 'Travel End Date',
    required: false,
    group: 'travel',
  },
  {
    id: 'travelPurpose',
    type: 'select',
    label: 'Travel Purpose',
    options: [
      { value: 'leisure', label: 'Leisure' },
      { value: 'business', label: 'Business' },
      { value: 'study', label: 'Study' },
      { value: 'medical', label: 'Medical' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
    group: 'travel',
  },
  {
    id: 'numberOfTravelers',
    type: 'text',
    label: 'Number of Travelers',
    placeholder: 'Enter number of travelers',
    required: false,
    group: 'travelers',
  },
  {
    id: 'familyPolicy',
    type: 'boolean',
    label: 'Family policy?',
    required: false,
    group: 'travelers',
  },
  {
    id: 'medicalCoverage',
    type: 'boolean',
    label: 'Medical coverage?',
    required: false,
    group: 'coverage',
  },
  {
    id: 'medicalCoverageAmount',
    type: 'text',
    label: 'Medical Coverage Amount',
    placeholder: 'Enter coverage amount',
    required: false,
    group: 'coverage',
  },
  {
    id: 'emergencyEvacuation',
    type: 'boolean',
    label: 'Emergency evacuation coverage?',
    required: false,
    group: 'coverage',
  },
  {
    id: 'tripCancellation',
    type: 'boolean',
    label: 'Trip cancellation coverage?',
    required: false,
    group: 'coverage',
  },
  {
    id: 'tripCancellationAmount',
    type: 'text',
    label: 'Trip Cancellation Amount',
    placeholder: 'Enter coverage amount',
    required: false,
    group: 'coverage',
  },
  {
    id: 'baggageCoverage',
    type: 'boolean',
    label: 'Baggage coverage?',
    required: false,
    group: 'coverage',
  },
  {
    id: 'flightDelay',
    type: 'boolean',
    label: 'Flight delay coverage?',
    required: false,
    group: 'additional',
  },
  {
    id: 'rentalCarCoverage',
    type: 'boolean',
    label: 'Rental car coverage?',
    required: false,
    group: 'additional',
  },
  {
    id: 'preExistingConditions',
    type: 'boolean',
    label: 'Any pre-existing medical conditions?',
    required: false,
    group: 'medical',
  },
  {
    id: 'preExistingConditionsCovered',
    type: 'boolean',
    label: 'Cover pre-existing conditions?',
    required: false,
    group: 'medical',
  },
  {
    id: 'premiumAmount',
    type: 'text',
    label: 'Premium Amount',
    placeholder: 'Enter premium amount',
    required: false,
    group: 'terms',
  },
  {
    id: 'deductibleAmount',
    type: 'text',
    label: 'Deductible Amount',
    placeholder: 'Enter deductible amount',
    required: false,
    group: 'terms',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'one-time', label: 'One-time' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
      { value: 'annually', label: 'Annually' },
    ],
    required: false,
    group: 'terms',
  },
  {
    id: 'extremeSportsExclusion',
    type: 'boolean',
    label: 'Exclude extreme sports?',
    required: false,
    group: 'exclusions',
  },
  {
    id: 'terrorismExclusion',
    type: 'boolean',
    label: 'Exclude terrorism?',
    required: false,
    group: 'exclusions',
  },
  {
    id: 'emergencyContactNumber',
    type: 'text',
    label: 'Emergency Contact Number',
    placeholder: 'Enter 24-hour emergency number',
    required: false,
    group: 'assistance',
  },
  {
    id: 'emergencyAssistance',
    type: 'boolean',
    label: 'Emergency assistance services?',
    required: false,
    group: 'assistance',
  },
  {
    id: 'cancellationPolicy',
    type: 'textarea',
    label: 'Cancellation Policy',
    placeholder: 'Describe cancellation terms',
    required: false,
    group: 'cancellation',
  },
  {
    id: 'freeLookPeriod',
    type: 'text',
    label: 'Free Look Period',
    placeholder: 'Enter free look period (e.g., 10 days)',
    required: false,
    group: 'cancellation',
  },
  {
    id: 'adventureSports',
    type: 'boolean',
    label: 'Cover adventure sports?',
    required: false,
    group: 'activities',
  },
  {
    id: 'winterSports',
    type: 'boolean',
    label: 'Cover winter sports?',
    required: false,
    group: 'activities',
  },
  {
    id: 'worldwideCoverage',
    type: 'boolean',
    label: 'Worldwide coverage?',
    required: false,
    group: 'geographic',
  },
  {
    id: 'countryRestrictions',
    type: 'textarea',
    label: 'Country Restrictions',
    placeholder: 'List any country restrictions',
    required: false,
    group: 'geographic',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'Enter governing law/state',
    required: false,
    group: 'legal',
  },
];