import type { Question } from '@/types/documents';

export const questions: Question[] = [
  {
    id: 'principalName',
    label: 'Your Full Legal Name (Principal)',
    type: 'text',
    required: true,
    placeholder: 'Enter your full legal name as it appears on the original POA',
  },
  {
    id: 'principalAddress',
    label: 'Your Current Address',
    type: 'textarea',
    required: true,
    placeholder: 'Enter your complete current address',
  },
  {
    id: 'agentName',
    label: 'Agent\'s Full Name (Person Being Revoked)',
    type: 'text',
    required: true,
    placeholder: 'Full name of the agent whose authority is being revoked',
  },
  {
    id: 'agentAddress',
    label: 'Agent\'s Address',
    type: 'textarea',
    required: true,
    placeholder: 'Complete address of the agent',
  },
  {
    id: 'originalPOADate',
    label: 'Date of Original Power of Attorney',
    type: 'date',
    required: true,
  },
  {
    id: 'originalPOAType',
    label: 'Type of Original Power of Attorney',
    type: 'select',
    required: true,
    options: [
      { value: 'general', label: 'General Power of Attorney' },
      { value: 'durable', label: 'Durable Power of Attorney' },
      { value: 'financial', label: 'Financial Power of Attorney' },
      { value: 'healthcare', label: 'Healthcare Power of Attorney' },
      { value: 'medical', label: 'Medical Power of Attorney' },
      { value: 'limited', label: 'Limited Power of Attorney' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'notaryOfOriginalPOA',
    label: 'Notary of Original POA (Optional)',
    type: 'text',
    placeholder: 'Name of notary who notarized the original POA',
  },
  {
    id: 'recordingInformation',
    label: 'Recording Information (Optional)',
    type: 'textarea',
    placeholder: 'If the original POA was recorded, provide book/page or document number',
  },
  {
    id: 'revocationDate',
    label: 'Revocation Date',
    type: 'date',
    required: true,
  },
  {
    id: 'revocationReason',
    label: 'Reason for Revocation (Optional)',
    type: 'textarea',
    placeholder: 'Briefly explain why you are revoking this POA',
  },
  {
    id: 'effectiveDate',
    label: 'When Should This Revocation Take Effect?',
    type: 'select',
    required: true,
    options: [
      { value: 'immediately', label: 'Immediately upon signing' },
      { value: 'specific_date', label: 'On a specific date' },
    ],
  },
  {
    id: 'specificEffectiveDate',
    label: 'Specific Effective Date (if applicable)',
    type: 'date',
    dependsOn: { field: 'effectiveDate', value: 'specific_date' },
  },
  {
    id: 'partialRevocation',
    label: 'Is This a Partial Revocation?',
    type: 'checkbox',
    defaultValue: false,
  },
  {
    id: 'specificPowersRevoked',
    label: 'Specific Powers Being Revoked (if partial)',
    type: 'textarea',
    placeholder: 'List the specific powers being revoked',
    dependsOn: { field: 'partialRevocation', value: true },
  },
  {
    id: 'remainingPowers',
    label: 'Powers That Remain in Effect (if partial)',
    type: 'textarea',
    placeholder: 'List the powers that will continue',
    dependsOn: { field: 'partialRevocation', value: true },
  },
  {
    id: 'newAgent',
    label: 'New Agent Full Name (Optional)',
    type: 'text',
    placeholder: 'If appointing a new agent, enter their full name',
  },
  {
    id: 'newAgentAddress',
    label: 'New Agent Address (Optional)',
    type: 'textarea',
    placeholder: 'Complete address of new agent',
    dependsOn: { field: 'newAgent' },
  },
  {
    id: 'notificationRequirements',
    label: 'Notification Requirements',
    type: 'textarea',
    required: true,
    placeholder: 'Describe how the agent and relevant parties will be notified',
  },
  {
    id: 'bankNotification',
    label: 'Notify Banks and Financial Institutions',
    type: 'checkbox',
    defaultValue: false,
  },
  {
    id: 'bankNames',
    label: 'Bank Names (if applicable)',
    type: 'textarea',
    placeholder: 'List banks and financial institutions to notify',
    dependsOn: { field: 'bankNotification', value: true },
  },
  {
    id: 'medicalProviderNotification',
    label: 'Notify Medical Providers',
    type: 'checkbox',
    defaultValue: false,
  },
  {
    id: 'medicalProviderNames',
    label: 'Medical Provider Names (if applicable)',
    type: 'textarea',
    placeholder: 'List medical providers to notify',
    dependsOn: { field: 'medicalProviderNotification', value: true },
  },
  {
    id: 'governmentAgencyNotification',
    label: 'Notify Government Agencies',
    type: 'checkbox',
    defaultValue: false,
  },
  {
    id: 'governmentAgencyNames',
    label: 'Government Agency Names (if applicable)',
    type: 'textarea',
    placeholder: 'List government agencies to notify',
    dependsOn: { field: 'governmentAgencyNotification', value: true },
  },
  {
    id: 'additionalNotifications',
    label: 'Additional Parties to Notify (Optional)',
    type: 'textarea',
    placeholder: 'Any other parties that should be notified of this revocation',
  },
  {
    id: 'confirmationOfCapacity',
    label: 'Confirmation of Mental Capacity',
    type: 'textarea',
    required: true,
    placeholder: 'Confirm that you are of sound mind and under no duress',
  },
  {
    id: 'witnessOneName',
    label: 'First Witness Full Name',
    type: 'text',
    required: true,
    placeholder: 'Adult witness to revocation signing',
  },
  {
    id: 'witnessOneAddress',
    label: 'First Witness Address',
    type: 'textarea',
    required: true,
    placeholder: 'Complete address of first witness',
  },
  {
    id: 'witnessTwoName',
    label: 'Second Witness Full Name',
    type: 'text',
    required: true,
    placeholder: 'Second adult witness to revocation signing',
  },
  {
    id: 'witnessTwoAddress',
    label: 'Second Witness Address',
    type: 'textarea',
    required: true,
    placeholder: 'Complete address of second witness',
  },
  {
    id: 'executionDate',
    label: 'Revocation Execution Date',
    type: 'date',
    required: true,
  },
  {
    id: 'executionState',
    label: 'State Where Revocation is Executed',
    type: 'text',
    required: true,
    placeholder: 'State where you are signing this revocation',
  },
  {
    id: 'executionCounty',
    label: 'County Where Revocation is Executed',
    type: 'text',
    required: true,
    placeholder: 'County where you are signing this revocation',
  },
];