import { z } from 'zod';

export const schema = z.object({
  principalName: z.string().min(1, 'Principal name is required'),
  principalAddress: z.string().min(1, 'Principal address is required'),
  agentName: z.string().min(1, 'Agent name is required'),
  agentAddress: z.string().min(1, 'Agent address is required'),
  originalPOADate: z.string().min(1, 'Original POA date is required'),
  originalPOAType: z.string().min(1, 'Original POA type is required'),
  notaryOfOriginalPOA: z.string().optional(),
  recordingInformation: z.string().optional(),
  revocationDate: z.string().min(1, 'Revocation date is required'),
  revocationReason: z.string().optional(),
  effectiveDate: z.enum(['immediately', 'specific_date']),
  specificEffectiveDate: z.string().optional(),
  partialRevocation: z.boolean().default(false),
  specificPowersRevoked: z.string().optional(),
  remainingPowers: z.string().optional(),
  newAgent: z.string().optional(),
  newAgentAddress: z.string().optional(),
  notificationRequirements: z
    .string()
    .min(1, 'Notification requirements are required'),
  thirdPartyNotification: z.string().optional(),
  bankNotification: z.boolean().default(false),
  bankNames: z.string().optional(),
  financialInstitutionNotification: z.boolean().default(false),
  financialInstitutionNames: z.string().optional(),
  medicalProviderNotification: z.boolean().default(false),
  medicalProviderNames: z.string().optional(),
  governmentAgencyNotification: z.boolean().default(false),
  governmentAgencyNames: z.string().optional(),
  additionalNotifications: z.string().optional(),
  confirmationOfCapacity: z
    .string()
    .min(1, 'Confirmation of capacity is required'),
  witnessOneName: z.string().min(1, 'First witness name is required'),
  witnessOneAddress: z.string().min(1, 'First witness address is required'),
  witnessTwoName: z.string().min(1, 'Second witness name is required'),
  witnessTwoAddress: z.string().min(1, 'Second witness address is required'),
  notaryName: z.string().optional(),
  notaryCommission: z.string().optional(),
  executionDate: z.string().min(1, 'Execution date is required'),
  executionState: z.string().min(1, 'State of execution is required'),
  executionCounty: z.string().min(1, 'County of execution is required'),
});
