import type { Question } from '@/types/documents';

export const loanModificationLetterQuestions: Question[] = [
  { id: 'date', label: 'Date of Letter', type: 'date', required: true },
  { id: 'borrowerName', label: 'Your Name', type: 'text', required: true },
  {
    id: 'borrowerAddress',
    label: 'Your Address',
    type: 'text',
    required: true,
    placeholder: 'Street, City, State, ZIP',
  },
  { id: 'lenderName', label: 'Lender Name', type: 'text', required: true },
  {
    id: 'lenderAddress',
    label: 'Lender Address',
    type: 'text',
    required: true,
    placeholder: 'Street, City, State, ZIP',
  },
  {
    id: 'loanAccountNumber',
    label: 'Loan Account Number',
    type: 'text',
    required: true,
    placeholder: 'Account or loan number',
  },
  {
    id: 'originalLoanAmount',
    label: 'Original Loan Amount',
    type: 'number',
    required: true,
    placeholder: 'e.g., 250000',
  },
  {
    id: 'currentBalance',
    label: 'Current Loan Balance',
    type: 'number',
    required: true,
    placeholder: 'e.g., 200000',
  },
  {
    id: 'originalPaymentAmount',
    label: 'Current Payment Amount',
    type: 'number',
    required: true,
    placeholder: 'e.g., 1500',
  },
  {
    id: 'requestedPaymentAmount',
    label: 'Requested Payment Amount',
    type: 'number',
    required: true,
    placeholder: 'e.g., 1200',
  },
  {
    id: 'reasonForModification',
    label: 'Reason for Modification Request',
    type: 'select',
    required: true,
    options: [
      { value: 'Job Loss', label: 'Job Loss' },
      { value: 'Income Reduction', label: 'Income Reduction' },
      { value: 'Medical Emergency', label: 'Medical Emergency' },
      { value: 'Divorce', label: 'Divorce' },
      { value: 'Death in Family', label: 'Death in Family' },
      { value: 'Other Financial Hardship', label: 'Other Financial Hardship' },
    ],
  },
  {
    id: 'detailedExplanation',
    label: 'Detailed Explanation',
    type: 'textarea',
    required: true,
    placeholder: 'Provide detailed explanation of your financial situation...',
  },
  {
    id: 'monthlyIncome',
    label: 'Monthly Income',
    type: 'number',
    required: true,
    placeholder: 'e.g., 4000',
  },
  {
    id: 'monthlyExpenses',
    label: 'Monthly Expenses',
    type: 'number',
    required: true,
    placeholder: 'e.g., 3500',
  },
  {
    id: 'proposedTerm',
    label: 'Proposed Modification Term',
    type: 'select',
    required: true,
    options: [
      { value: 'Temporary', label: 'Temporary (3-12 months)' },
      { value: 'Permanent', label: 'Permanent' },
    ],
  },
  { id: 'requestedStartDate', label: 'Requested Start Date', type: 'date', required: true },
  {
    id: 'contactPhone',
    label: 'Contact Phone',
    type: 'text',
    required: true,
    placeholder: '(555) 123-4567',
  },
  {
    id: 'contactEmail',
    label: 'Contact Email',
    type: 'email',
    required: false,
    placeholder: 'your.email@example.com',
  },
];
