// src/lib/documents/us/oil-gas-lease-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const oilGasLeaseAgreementQuestions: FormQuestion[] = [
  {
    id: 'lessorName',
    type: 'text',
    label: 'Lessor Name',
    placeholder: 'Enter mineral rights owner name',
    required: true,
    group: 'lessor',
  },
  {
    id: 'lesseeName',
    type: 'text',
    label: 'Lessee Name',
    placeholder: 'Enter oil/gas company name',
    required: true,
    group: 'lessee',
  },
  {
    id: 'propertyDescription',
    type: 'textarea',
    label: 'Property Description',
    placeholder: 'Describe the leased property',
    required: false,
    group: 'property',
  },
  {
    id: 'acres',
    type: 'text',
    label: 'Leased Acres',
    placeholder: 'Enter number of acres',
    required: false,
    group: 'property',
  },
  {
    id: 'primaryTerm',
    type: 'text',
    label: 'Primary Term',
    placeholder: 'Enter lease duration (e.g., 3 years)',
    required: false,
    group: 'terms',
  },
  {
    id: 'royaltyRate',
    type: 'text',
    label: 'Royalty Rate',
    placeholder: 'Enter royalty percentage (e.g., 12.5%)',
    required: false,
    group: 'payment',
  },
  {
    id: 'bonusPayment',
    type: 'text',
    label: 'Bonus Payment per Acre',
    placeholder: 'Enter bonus payment amount',
    required: false,
    group: 'payment',
  },
  {
    id: 'delayRental',
    type: 'text',
    label: 'Delay Rental per Acre',
    placeholder: 'Enter annual rental amount',
    required: false,
    group: 'payment',
  },
  {
    id: 'oil',
    type: 'boolean',
    label: 'Oil rights included?',
    required: false,
    group: 'substances',
  },
  {
    id: 'gas',
    type: 'boolean',
    label: 'Gas rights included?',
    required: false,
    group: 'substances',
  },
  {
    id: 'naturalGasLiquids',
    type: 'boolean',
    label: 'Natural gas liquids included?',
    required: false,
    group: 'substances',
  },
  {
    id: 'surfaceUse',
    type: 'boolean',
    label: 'Surface use rights granted?',
    required: false,
    group: 'surface',
  },
  {
    id: 'horizontalClause',
    type: 'boolean',
    label: 'Horizontal drilling permitted?',
    required: false,
    group: 'drilling',
  },
  {
    id: 'unitization',
    type: 'boolean',
    label: 'Unitization clause included?',
    required: false,
    group: 'operations',
  },
  {
    id: 'liabilityAmount',
    type: 'text',
    label: 'Required Insurance Amount',
    placeholder: 'Enter minimum insurance coverage',
    required: false,
    group: 'insurance',
  },
];
