// src/lib/documents/us/hunting-lease-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const huntingLeaseAgreementQuestions: FormQuestion[] = [
  {
    id: 'landownerName',
    type: 'text',
    label: 'Landowner Name',
    placeholder: 'Enter property owner name',
    required: true,
    group: 'landowner',
  },
  {
    id: 'lesseeName',
    type: 'text',
    label: 'Hunter/Lessee Name',
    placeholder: 'Enter hunter or hunting group name',
    required: true,
    group: 'lessee',
  },
  {
    id: 'propertyDescription',
    type: 'textarea',
    label: 'Property Description',
    placeholder: 'Describe the hunting property',
    required: false,
    group: 'property',
  },
  {
    id: 'totalAcres',
    type: 'text',
    label: 'Total Property Acres',
    placeholder: 'Enter total property size',
    required: false,
    group: 'property',
  },
  {
    id: 'huntingAcres',
    type: 'text',
    label: 'Hunting Acres',
    placeholder: 'Enter huntable acreage',
    required: false,
    group: 'property',
  },
  {
    id: 'huntingRightsType',
    type: 'select',
    label: 'Hunting Rights Type',
    options: [
      { value: 'exclusive', label: 'Exclusive Rights' },
      { value: 'non-exclusive', label: 'Non-Exclusive Rights' },
      { value: 'shared', label: 'Shared Rights' },
    ],
    required: false,
    group: 'rights',
  },
  {
    id: 'gameTypes',
    type: 'multi-select',
    label: 'Game Types',
    options: [
      { value: 'deer', label: 'Deer' },
      { value: 'turkey', label: 'Turkey' },
      { value: 'duck', label: 'Duck' },
      { value: 'dove', label: 'Dove' },
      { value: 'quail', label: 'Quail' },
      { value: 'rabbit', label: 'Rabbit' },
      { value: 'squirrel', label: 'Squirrel' },
      { value: 'wild-hog', label: 'Wild Hog' },
      { value: 'elk', label: 'Elk' },
      { value: 'bear', label: 'Bear' },
      { value: 'waterfowl', label: 'Waterfowl' },
    ],
    required: false,
    group: 'hunting',
  },
  {
    id: 'huntingMethods',
    type: 'multi-select',
    label: 'Allowed Hunting Methods',
    options: [
      { value: 'bow', label: 'Bow' },
      { value: 'rifle', label: 'Rifle' },
      { value: 'shotgun', label: 'Shotgun' },
      { value: 'muzzleloader', label: 'Muzzleloader' },
      { value: 'crossbow', label: 'Crossbow' },
    ],
    required: false,
    group: 'hunting',
  },
  {
    id: 'annualFee',
    type: 'text',
    label: 'Annual Lease Fee',
    placeholder: 'Enter yearly hunting fee',
    required: false,
    group: 'payment',
  },
  {
    id: 'maximumHunters',
    type: 'text',
    label: 'Maximum Number of Hunters',
    placeholder: 'Enter hunter limit',
    required: false,
    group: 'hunters',
  },
  {
    id: 'campingAllowed',
    type: 'boolean',
    label: 'Camping allowed?',
    required: false,
    group: 'access',
  },
  {
    id: 'atvUse',
    type: 'boolean',
    label: 'ATV use permitted?',
    required: false,
    group: 'access',
  },
  {
    id: 'feedingAllowed',
    type: 'boolean',
    label: 'Wildlife feeding allowed?',
    required: false,
    group: 'management',
  },
  {
    id: 'liabilityInsurance',
    type: 'boolean',
    label: 'Liability insurance required?',
    required: false,
    group: 'insurance',
  },
  {
    id: 'insuranceAmount',
    type: 'text',
    label: 'Required Insurance Amount',
    placeholder: 'Enter minimum coverage amount',
    required: false,
    group: 'insurance',
  },
];
