// src/lib/documents/us/room-rental-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const roomRentalAgreementQuestions: FormQuestion[] = [
  {
    id: 'landlordName',
    type: 'text',
    label: 'Landlord Full Name',
    placeholder: "Enter the landlord's full legal name",
    required: true,
    group: 'landlord',
  },
  {
    id: 'landlordAddress',
    type: 'textarea',
    label: 'Landlord Address',
    placeholder: "Enter the landlord's mailing address",
    required: true,
    group: 'landlord',
  },
  {
    id: 'landlordPhone',
    type: 'tel',
    label: 'Landlord Phone Number',
    placeholder: '(555) 123-4567',
    required: false,
    group: 'landlord',
  },
  {
    id: 'landlordEmail',
    type: 'email',
    label: 'Landlord Email',
    placeholder: 'landlord@example.com',
    required: false,
    group: 'landlord',
  },
  {
    id: 'tenantName',
    type: 'text',
    label: 'Tenant Full Name',
    placeholder: "Enter the tenant's full legal name",
    required: true,
    group: 'tenant',
  },
  {
    id: 'tenantPhone',
    type: 'tel',
    label: 'Tenant Phone Number',
    placeholder: '(555) 123-4567',
    required: false,
    group: 'tenant',
  },
  {
    id: 'tenantEmail',
    type: 'email',
    label: 'Tenant Email',
    placeholder: 'tenant@example.com',
    required: false,
    group: 'tenant',
  },
  {
    id: 'propertyAddress',
    type: 'textarea',
    label: 'Property Address',
    placeholder: 'Enter the full address of the rental property',
    required: true,
    group: 'property',
  },
  {
    id: 'roomDescription',
    type: 'textarea',
    label: 'Room Description',
    placeholder: 'Describe the room being rented (size, features, etc.)',
    required: true,
    group: 'property',
  },
  {
    id: 'furnishedStatus',
    type: 'select',
    label: 'Furnished Status',
    options: [
      { value: 'furnished', label: 'Fully Furnished' },
      { value: 'unfurnished', label: 'Unfurnished' },
      { value: 'partially-furnished', label: 'Partially Furnished' },
    ],
    required: true,
    group: 'property',
  },
  {
    id: 'leaseStartDate',
    type: 'date',
    label: 'Lease Start Date',
    required: true,
    group: 'terms',
  },
  {
    id: 'leaseEndDate',
    type: 'date',
    label: 'Lease End Date',
    required: false,
    group: 'terms',
  },
  {
    id: 'monthToMonth',
    type: 'checkbox',
    label: 'Month-to-Month Rental',
    required: false,
    group: 'terms',
  },
  {
    id: 'monthlyRent',
    type: 'number',
    label: 'Monthly Rent ($)',
    placeholder: '500',
    required: true,
    group: 'financial',
  },
  {
    id: 'securityDeposit',
    type: 'number',
    label: 'Security Deposit ($)',
    placeholder: '500',
    required: true,
    group: 'financial',
  },
  {
    id: 'utilitiesIncluded',
    type: 'checkbox',
    label: 'Utilities Included in Rent',
    required: false,
    group: 'financial',
  },
  {
    id: 'utilitiesDescription',
    type: 'textarea',
    label: 'Utilities Details',
    placeholder: 'Specify which utilities are included or how they are divided',
    required: false,
    group: 'financial',
    dependsOn: 'utilitiesIncluded',
  },
  {
    id: 'kitchenAccess',
    type: 'checkbox',
    label: 'Kitchen Access',
    required: false,
    group: 'shared',
  },
  {
    id: 'bathroomAccess',
    type: 'checkbox',
    label: 'Bathroom Access',
    required: false,
    group: 'shared',
  },
  {
    id: 'livingRoomAccess',
    type: 'checkbox',
    label: 'Living Room Access',
    required: false,
    group: 'shared',
  },
  {
    id: 'smokingAllowed',
    type: 'checkbox',
    label: 'Smoking Allowed',
    required: false,
    group: 'rules',
  },
  {
    id: 'petsAllowed',
    type: 'checkbox',
    label: 'Pets Allowed',
    required: false,
    group: 'rules',
  },
  {
    id: 'guestsAllowed',
    type: 'checkbox',
    label: 'Guests Allowed',
    required: false,
    group: 'rules',
  },
  {
    id: 'quietHours',
    type: 'text',
    label: 'Quiet Hours',
    placeholder: 'e.g., 10 PM - 8 AM',
    required: false,
    group: 'rules',
  },
  {
    id: 'parkingIncluded',
    type: 'checkbox',
    label: 'Parking Included',
    required: false,
    group: 'additional',
  },
  {
    id: 'internetIncluded',
    type: 'checkbox',
    label: 'Internet Included',
    required: false,
    group: 'additional',
  },
  {
    id: 'additionalTerms',
    type: 'textarea',
    label: 'Additional Terms',
    placeholder: 'Any additional terms or conditions',
    required: false,
    group: 'additional',
  },
];
