// src/lib/documents/us/dog-breeding-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const dogBreedingAgreementQuestions: FormQuestion[] = [
  {
    id: 'studOwnerName',
    type: 'text',
    label: 'Stud Owner Name',
    placeholder: 'Enter stud owner name',
    required: true,
    group: 'studOwner',
  },
  {
    id: 'bitchOwnerName',
    type: 'text',
    label: 'Bitch Owner Name',
    placeholder: 'Enter bitch owner name',
    required: true,
    group: 'bitchOwner',
  },
  {
    id: 'studName',
    type: 'text',
    label: 'Stud Dog Name',
    placeholder: 'Enter stud dog name',
    required: true,
    group: 'stud',
  },
  {
    id: 'studBreed',
    type: 'text',
    label: 'Stud Breed',
    placeholder: 'Enter breed',
    required: false,
    group: 'stud',
  },
  {
    id: 'bitchName',
    type: 'text',
    label: 'Bitch Name',
    placeholder: 'Enter bitch name',
    required: true,
    group: 'bitch',
  },
  {
    id: 'breedingMethod',
    type: 'select',
    label: 'Breeding Method',
    options: [
      { value: 'natural', label: 'Natural Breeding' },
      { value: 'artificial-insemination', label: 'Artificial Insemination' },
      { value: 'either', label: 'Either Method' },
    ],
    required: false,
    group: 'breeding',
  },
  {
    id: 'studFee',
    type: 'text',
    label: 'Stud Fee',
    placeholder: 'Enter stud fee amount',
    required: false,
    group: 'financial',
  },
  {
    id: 'paymentTerms',
    type: 'select',
    label: 'Payment Terms',
    options: [
      { value: 'upfront', label: 'Upfront Payment' },
      { value: 'on-confirmation', label: 'On Pregnancy Confirmation' },
      { value: 'on-whelping', label: 'On Whelping' },
      { value: 'pick-of-litter', label: 'Pick of Litter' },
    ],
    required: false,
    group: 'financial',
  },
  {
    id: 'pickOfLitter',
    type: 'boolean',
    label: 'Pick of litter included?',
    required: false,
    group: 'litter',
  },
  {
    id: 'breedingRights',
    type: 'select',
    label: 'Breeding Rights',
    options: [
      { value: 'full', label: 'Full Breeding Rights' },
      { value: 'limited', label: 'Limited Registration' },
      { value: 'none', label: 'No Breeding Rights' },
    ],
    required: false,
    group: 'rights',
  },
  {
    id: 'healthGuarantee',
    type: 'text',
    label: 'Health Guarantee Period',
    placeholder: 'Enter health guarantee period',
    required: false,
    group: 'health',
  },
];
