// src/lib/documents/us/statement-of-work/questions.ts
import type { FormQuestion } from '@/types/documents';

export const statementOfWorkQuestions: FormQuestion[] = [
  {
    id: 'projectTitle',
    type: 'text',
    label: 'Project Title',
    placeholder: 'e.g., Website Development Project, Marketing Campaign',
    required: true,
    group: 'project',
  },
  {
    id: 'projectDescription',
    type: 'textarea',
    label: 'Project Description',
    placeholder: 'Provide a detailed description of the project',
    required: true,
    group: 'project',
  },
  {
    id: 'projectObjectives',
    type: 'textarea',
    label: 'Project Objectives',
    placeholder: 'List the main objectives and goals of this project',
    required: true,
    group: 'project',
  },
  {
    id: 'projectBackground',
    type: 'textarea',
    label: 'Project Background',
    placeholder: 'Provide context and background information',
    required: false,
    group: 'project',
  },
  {
    id: 'client',
    type: 'text',
    label: 'Client Name',
    placeholder: 'Enter client company or individual name',
    required: true,
    group: 'client',
  },
  {
    id: 'clientAddress',
    type: 'textarea',
    label: 'Client Address',
    placeholder: 'Enter complete client address',
    required: true,
    group: 'client',
  },
  {
    id: 'clientContact',
    type: 'text',
    label: 'Client Contact Person',
    placeholder: 'Primary contact person and details',
    required: false,
    group: 'client',
  },
  {
    id: 'contractor',
    type: 'text',
    label: 'Contractor Name',
    placeholder: 'Enter contractor company or individual name',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorAddress',
    type: 'textarea',
    label: 'Contractor Address',
    placeholder: 'Enter complete contractor address',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorContact',
    type: 'text',
    label: 'Contractor Contact Person',
    placeholder: 'Primary contact person and details',
    required: false,
    group: 'contractor',
  },
  {
    id: 'scopeDescription',
    type: 'textarea',
    label: 'Scope of Work Description',
    placeholder: 'Describe the complete scope of work to be performed',
    required: true,
    group: 'scope',
  },
  {
    id: 'deliverables',
    type: 'textarea',
    label: 'Deliverables',
    placeholder: 'List all deliverables and expected outcomes',
    required: true,
    group: 'scope',
  },
  {
    id: 'tasksAndActivities',
    type: 'textarea',
    label: 'Tasks and Activities',
    placeholder: 'Detail specific tasks and activities to be performed',
    required: false,
    group: 'scope',
  },
  {
    id: 'workLocation',
    type: 'text',
    label: 'Work Location',
    placeholder: 'e.g., Remote, On-site, Hybrid',
    required: false,
    group: 'scope',
  },
  {
    id: 'inclusionsExclusions',
    type: 'textarea',
    label: 'Inclusions and Exclusions',
    placeholder: 'Specify what is included and excluded from the scope',
    required: false,
    group: 'scope',
  },
  {
    id: 'projectStartDate',
    type: 'date',
    label: 'Project Start Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'projectEndDate',
    type: 'date',
    label: 'Project End Date',
    required: false,
    group: 'timeline',
  },
  {
    id: 'projectDuration',
    type: 'text',
    label: 'Project Duration',
    placeholder: 'e.g., 3 months, 12 weeks',
    required: false,
    group: 'timeline',
  },
  {
    id: 'keyMilestones',
    type: 'textarea',
    label: 'Key Milestones',
    placeholder: 'List important milestones and their target dates',
    required: false,
    group: 'timeline',
  },
  {
    id: 'deliverySchedule',
    type: 'textarea',
    label: 'Delivery Schedule',
    placeholder: 'Specify when deliverables will be provided',
    required: false,
    group: 'timeline',
  },
  {
    id: 'totalProjectValue',
    type: 'number',
    label: 'Total Project Value ($)',
    placeholder: '50000',
    required: false,
    group: 'financial',
  },
  {
    id: 'paymentStructure',
    type: 'textarea',
    label: 'Payment Structure',
    placeholder: 'Describe the payment structure and amounts',
    required: false,
    group: 'financial',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'milestone-based', label: 'Milestone-based' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'completion', label: 'Upon Completion' },
      { value: 'time-and-materials', label: 'Time and Materials' },
    ],
    required: false,
    group: 'financial',
  },
  {
    id: 'paymentTerms',
    type: 'textarea',
    label: 'Payment Terms',
    placeholder: 'Specify payment terms and conditions',
    required: false,
    group: 'financial',
  },
  {
    id: 'acceptanceCriteria',
    type: 'textarea',
    label: 'Acceptance Criteria',
    placeholder: 'Define criteria for accepting deliverables',
    required: true,
    group: 'quality',
  },
  {
    id: 'qualityStandards',
    type: 'textarea',
    label: 'Quality Standards',
    placeholder: 'Specify quality standards and requirements',
    required: false,
    group: 'quality',
  },
  {
    id: 'testingRequirements',
    type: 'textarea',
    label: 'Testing Requirements',
    placeholder: 'Describe testing and validation requirements',
    required: false,
    group: 'quality',
  },
  {
    id: 'reviewProcesses',
    type: 'textarea',
    label: 'Review Processes',
    placeholder: 'Outline review and approval processes',
    required: false,
    group: 'quality',
  },
  {
    id: 'contractorResponsibilities',
    type: 'textarea',
    label: 'Contractor Responsibilities',
    placeholder: 'List specific responsibilities of the contractor',
    required: true,
    group: 'responsibilities',
  },
  {
    id: 'clientResponsibilities',
    type: 'textarea',
    label: 'Client Responsibilities',
    placeholder: 'List specific responsibilities of the client',
    required: false,
    group: 'responsibilities',
  },
  {
    id: 'sharedResponsibilities',
    type: 'textarea',
    label: 'Shared Responsibilities',
    placeholder: 'Describe responsibilities shared by both parties',
    required: false,
    group: 'responsibilities',
  },
  {
    id: 'communicationPlan',
    type: 'textarea',
    label: 'Communication Plan',
    placeholder: 'Outline communication protocols and schedules',
    required: false,
    group: 'responsibilities',
  },
  {
    id: 'resourceRequirements',
    type: 'textarea',
    label: 'Resource Requirements',
    placeholder: 'Specify required resources, personnel, equipment',
    required: false,
    group: 'resources',
  },
  {
    id: 'personnelAssigned',
    type: 'textarea',
    label: 'Personnel Assigned',
    placeholder: 'List key personnel assigned to the project',
    required: false,
    group: 'resources',
  },
  {
    id: 'equipmentNeeded',
    type: 'textarea',
    label: 'Equipment Needed',
    placeholder: 'Specify any equipment requirements',
    required: false,
    group: 'resources',
  },
  {
    id: 'identifiedRisks',
    type: 'textarea',
    label: 'Identified Risks',
    placeholder: 'List potential risks and concerns',
    required: false,
    group: 'risks',
  },
  {
    id: 'riskMitigation',
    type: 'textarea',
    label: 'Risk Mitigation Strategies',
    placeholder: 'Describe strategies to mitigate identified risks',
    required: false,
    group: 'risks',
  },
  {
    id: 'contingencyPlans',
    type: 'textarea',
    label: 'Contingency Plans',
    placeholder: 'Outline contingency plans for potential issues',
    required: false,
    group: 'risks',
  },
  {
    id: 'changeControlProcess',
    type: 'textarea',
    label: 'Change Control Process',
    placeholder: 'Describe how changes to scope will be handled',
    required: false,
    group: 'change',
  },
  {
    id: 'approvalProcedure',
    type: 'textarea',
    label: 'Approval Procedure',
    placeholder: 'Outline approval procedures for changes',
    required: false,
    group: 'change',
  },
  {
    id: 'ipOwnership',
    type: 'select',
    label: 'Intellectual Property Ownership',
    options: [
      { value: 'client', label: 'Client Owns' },
      { value: 'contractor', label: 'Contractor Owns' },
      { value: 'shared', label: 'Shared Ownership' },
      { value: 'retained', label: 'Each Party Retains Their Own' },
    ],
    required: false,
    group: 'intellectual',
  },
  {
    id: 'workForHire',
    type: 'checkbox',
    label: 'This is work for hire',
    required: false,
    group: 'intellectual',
  },
  {
    id: 'confidentialityRequirements',
    type: 'textarea',
    label: 'Confidentiality Requirements',
    placeholder: 'Specify confidentiality obligations',
    required: false,
    group: 'intellectual',
  },
  {
    id: 'performanceMetrics',
    type: 'textarea',
    label: 'Performance Metrics',
    placeholder: 'Define key performance indicators',
    required: false,
    group: 'monitoring',
  },
  {
    id: 'reportingRequirements',
    type: 'textarea',
    label: 'Reporting Requirements',
    placeholder: 'Specify reporting obligations and formats',
    required: false,
    group: 'monitoring',
  },
  {
    id: 'meetingSchedule',
    type: 'text',
    label: 'Meeting Schedule',
    placeholder: 'e.g., Weekly status meetings, Monthly reviews',
    required: false,
    group: 'monitoring',
  },
  {
    id: 'completionCriteria',
    type: 'textarea',
    label: 'Completion Criteria',
    placeholder: 'Define what constitutes project completion',
    required: false,
    group: 'completion',
  },
  {
    id: 'deliverableHandover',
    type: 'textarea',
    label: 'Deliverable Handover Process',
    placeholder: 'Describe the handover process for deliverables',
    required: false,
    group: 'completion',
  },
  {
    id: 'postCompletionSupport',
    type: 'textarea',
    label: 'Post-Completion Support',
    placeholder: 'Specify any support provided after completion',
    required: false,
    group: 'completion',
  },
  {
    id: 'warrantyProvisions',
    type: 'textarea',
    label: 'Warranty Provisions',
    placeholder: 'Specify warranty terms and coverage',
    required: false,
    group: 'completion',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'e.g., State of California',
    required: false,
    group: 'legal',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'negotiation', label: 'Good Faith Negotiation' },
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'litigation', label: 'Court Litigation' },
    ],
    required: false,
    group: 'legal',
  },
  {
    id: 'additionalTerms',
    type: 'textarea',
    label: 'Additional Terms',
    placeholder: 'Any additional terms or special provisions',
    required: false,
    group: 'additional',
  },
];