// src/lib/documents/us/roommate-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const roommateAgreementQuestions: FormQuestion[] = [
  {
    id: 'propertyAddress',
    type: 'textarea',
    label: 'Property Address',
    placeholder: 'Enter the complete address of the shared property',
    required: true,
    group: 'property',
  },
  {
    id: 'propertyType',
    type: 'select',
    label: 'Property Type',
    options: [
      { value: 'apartment', label: 'Apartment' },
      { value: 'house', label: 'House' },
      { value: 'condo', label: 'Condominium' },
      { value: 'townhouse', label: 'Townhouse' },
    ],
    required: true,
    group: 'property',
  },
  {
    id: 'roommate1Name',
    type: 'text',
    label: 'Roommate 1 Name',
    placeholder: 'Enter first roommate full name',
    required: true,
    group: 'roommates',
  },
  {
    id: 'roommate1Phone',
    type: 'tel',
    label: 'Roommate 1 Phone',
    placeholder: '(555) 123-4567',
    required: false,
    group: 'roommates',
  },
  {
    id: 'roommate1Email',
    type: 'email',
    label: 'Roommate 1 Email',
    placeholder: 'roommate1@email.com',
    required: false,
    group: 'roommates',
  },
  {
    id: 'roommate2Name',
    type: 'text',
    label: 'Roommate 2 Name',
    placeholder: 'Enter second roommate full name',
    required: true,
    group: 'roommates',
  },
  {
    id: 'roommate2Phone',
    type: 'tel',
    label: 'Roommate 2 Phone',
    placeholder: '(555) 123-4567',
    required: false,
    group: 'roommates',
  },
  {
    id: 'roommate2Email',
    type: 'email',
    label: 'Roommate 2 Email',
    placeholder: 'roommate2@email.com',
    required: false,
    group: 'roommates',
  },
  {
    id: 'hasAdditionalRoommates',
    type: 'checkbox',
    label: 'There are additional roommates',
    required: false,
    group: 'roommates',
  },
  {
    id: 'agreementStartDate',
    type: 'date',
    label: 'Agreement Start Date',
    required: true,
    group: 'terms',
  },
  {
    id: 'agreementEndDate',
    type: 'date',
    label: 'Agreement End Date',
    required: false,
    group: 'terms',
  },
  {
    id: 'monthToMonth',
    type: 'checkbox',
    label: 'Month-to-Month Agreement',
    required: false,
    group: 'terms',
  },
  {
    id: 'totalMonthlyRent',
    type: 'number',
    label: 'Total Monthly Rent ($)',
    placeholder: '2000',
    required: true,
    group: 'financial',
  },
  {
    id: 'rentSplitMethod',
    type: 'select',
    label: 'How to Split Rent',
    options: [
      { value: 'equal', label: 'Split Equally' },
      { value: 'by-room-size', label: 'By Room Size' },
      { value: 'custom', label: 'Custom Split' },
    ],
    required: true,
    group: 'financial',
  },
  {
    id: 'roommate1RentShare',
    type: 'number',
    label: 'Roommate 1 Rent Share ($)',
    placeholder: '1000',
    required: true,
    group: 'financial',
  },
  {
    id: 'roommate2RentShare',
    type: 'number',
    label: 'Roommate 2 Rent Share ($)',
    placeholder: '1000',
    required: true,
    group: 'financial',
  },
  {
    id: 'totalUtilities',
    type: 'number',
    label: 'Total Monthly Utilities ($)',
    placeholder: '200',
    required: false,
    group: 'utilities',
  },
  {
    id: 'utilitiesSplitMethod',
    type: 'select',
    label: 'How to Split Utilities',
    options: [
      { value: 'equal', label: 'Split Equally' },
      { value: 'by-usage', label: 'By Usage' },
      { value: 'custom', label: 'Custom Split' },
    ],
    required: false,
    group: 'utilities',
  },
  {
    id: 'totalSecurityDeposit',
    type: 'number',
    label: 'Total Security Deposit ($)',
    placeholder: '2000',
    required: false,
    group: 'deposit',
  },
  {
    id: 'roommate1Room',
    type: 'text',
    label: 'Roommate 1 Room/Area',
    placeholder: 'e.g., Master bedroom, Room A',
    required: false,
    group: 'living',
  },
  {
    id: 'roommate2Room',
    type: 'text',
    label: 'Roommate 2 Room/Area',
    placeholder: 'e.g., Second bedroom, Room B',
    required: false,
    group: 'living',
  },
  {
    id: 'quietHours',
    type: 'text',
    label: 'Quiet Hours',
    placeholder: 'e.g., 10 PM - 8 AM',
    required: false,
    group: 'rules',
  },
  {
    id: 'guestPolicy',
    type: 'textarea',
    label: 'Guest Policy',
    placeholder: 'Rules about overnight guests, advance notice, etc.',
    required: false,
    group: 'rules',
  },
  {
    id: 'smokingPolicy',
    type: 'select',
    label: 'Smoking Policy',
    options: [
      { value: 'allowed', label: 'Smoking Allowed' },
      { value: 'not-allowed', label: 'No Smoking' },
      { value: 'outside-only', label: 'Outside Only' },
    ],
    required: false,
    group: 'rules',
  },
  {
    id: 'petPolicy',
    type: 'select',
    label: 'Pet Policy',
    options: [
      { value: 'allowed', label: 'Pets Allowed' },
      { value: 'not-allowed', label: 'No Pets' },
      { value: 'with-approval', label: 'With Roommate Approval' },
    ],
    required: false,
    group: 'rules',
  },
  {
    id: 'cleaningSchedule',
    type: 'textarea',
    label: 'Cleaning Schedule',
    placeholder: 'How cleaning duties will be shared',
    required: false,
    group: 'responsibilities',
  },
  {
    id: 'noticeToTerminate',
    type: 'text',
    label: 'Notice to Terminate',
    placeholder: '30 days',
    required: false,
    group: 'termination',
  },
  {
    id: 'additionalTerms',
    type: 'textarea',
    label: 'Additional Terms',
    placeholder: 'Any additional rules or agreements',
    required: false,
    group: 'additional',
  },
];