// src/lib/documents/us/lease-termination-letter/questions.ts
import type { FormQuestion } from '@/types/documents';

export const leaseTerminationLetterQuestions: FormQuestion[] = [
  {
    id: 'senderName',
    type: 'text',
    label: 'Your Name',
    placeholder: 'Enter your full name',
    required: true,
    group: 'sender',
  },
  {
    id: 'senderAddress',
    type: 'textarea',
    label: 'Your Address',
    placeholder: 'Enter your current address',
    required: true,
    group: 'sender',
  },
  {
    id: 'senderPhone',
    type: 'tel',
    label: 'Your Phone Number',
    placeholder: '(555) 123-4567',
    required: false,
    group: 'sender',
  },
  {
    id: 'senderEmail',
    type: 'email',
    label: 'Your Email',
    placeholder: 'your@email.com',
    required: false,
    group: 'sender',
  },
  {
    id: 'recipientName',
    type: 'text',
    label: 'Landlord/Tenant Name',
    placeholder: 'Enter recipient full name',
    required: true,
    group: 'recipient',
  },
  {
    id: 'recipientAddress',
    type: 'textarea',
    label: 'Landlord/Tenant Address',
    placeholder: 'Enter recipient address',
    required: true,
    group: 'recipient',
  },
  {
    id: 'propertyAddress',
    type: 'textarea',
    label: 'Rental Property Address',
    placeholder: 'Enter the address of the rental property',
    required: true,
    group: 'property',
  },
  {
    id: 'unitNumber',
    type: 'text',
    label: 'Unit Number',
    placeholder: 'Apt 2B, Unit 5, etc.',
    required: false,
    group: 'property',
  },
  {
    id: 'leaseStartDate',
    type: 'date',
    label: 'Lease Start Date',
    required: true,
    group: 'lease',
  },
  {
    id: 'currentLeaseEndDate',
    type: 'date',
    label: 'Current Lease End Date',
    required: false,
    group: 'lease',
  },
  {
    id: 'noticeType',
    type: 'select',
    label: 'Notice Type',
    options: [
      { value: '30-day', label: '30-Day Notice' },
      { value: '60-day', label: '60-Day Notice' },
      { value: '90-day', label: '90-Day Notice' },
      { value: 'end-of-lease', label: 'End of Lease Term' },
      { value: 'immediate', label: 'Immediate Termination' },
    ],
    required: true,
    group: 'termination',
  },
  {
    id: 'terminationDate',
    type: 'date',
    label: 'Lease Termination Date',
    required: true,
    group: 'termination',
  },
  {
    id: 'moveOutDate',
    type: 'date',
    label: 'Move-Out Date',
    required: true,
    group: 'termination',
  },
  {
    id: 'terminationReason',
    type: 'select',
    label: 'Reason for Termination',
    options: [
      { value: 'end-of-lease', label: 'End of Lease Term' },
      { value: 'moving', label: 'Moving to New Location' },
      { value: 'purchase', label: 'Purchasing a Home' },
      { value: 'job-relocation', label: 'Job Relocation' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'termination',
  },
  {
    id: 'customReason',
    type: 'text',
    label: 'Custom Reason',
    placeholder: 'Specify your reason',
    required: false,
    group: 'termination',
    dependsOn: 'terminationReason',
  },
  {
    id: 'forwardingAddress',
    type: 'textarea',
    label: 'Forwarding Address',
    placeholder: 'Enter your new address for security deposit return',
    required: false,
    group: 'moveout',
  },
  {
    id: 'securityDepositAmount',
    type: 'number',
    label: 'Security Deposit Amount ($)',
    placeholder: '1200',
    required: false,
    group: 'deposit',
  },
  {
    id: 'securityDepositReturn',
    type: 'textarea',
    label: 'Security Deposit Instructions',
    placeholder: 'Special instructions for security deposit return',
    required: false,
    group: 'deposit',
  },
  {
    id: 'additionalNotes',
    type: 'textarea',
    label: 'Additional Notes',
    placeholder: 'Any additional information or requests',
    required: false,
    group: 'additional',
  },
];
