// src/lib/documents/us/architect-contract/questions.ts
import type { FormQuestion } from '@/types/documents';

export const architectContractQuestions: FormQuestion[] = [
  {
    id: 'clientName',
    type: 'text',
    label: 'Client Name',
    placeholder: 'Enter client full name or company',
    required: true,
    group: 'client',
  },
  {
    id: 'clientAddress',
    type: 'text',
    label: 'Client Address',
    placeholder: 'Enter complete client address',
    required: true,
    group: 'client',
  },
  {
    id: 'clientPhone',
    type: 'text',
    label: 'Client Phone',
    placeholder: 'Enter phone number',
    required: true,
    group: 'client',
  },
  {
    id: 'architectName',
    type: 'text',
    label: 'Architect Name',
    placeholder: 'Enter architect full name',
    required: true,
    group: 'architect',
  },
  {
    id: 'architectFirm',
    type: 'text',
    label: 'Architecture Firm',
    placeholder: 'Enter firm name if applicable',
    required: false,
    group: 'architect',
  },
  {
    id: 'architectAddress',
    type: 'text',
    label: 'Architect Address',
    placeholder: 'Enter complete architect address',
    required: true,
    group: 'architect',
  },
  {
    id: 'architectLicense',
    type: 'text',
    label: 'Architect License Number',
    placeholder: 'Enter professional license number',
    required: true,
    group: 'architect',
  },
  {
    id: 'projectName',
    type: 'text',
    label: 'Project Name',
    placeholder: 'Enter project name/title',
    required: true,
    group: 'project',
  },
  {
    id: 'projectAddress',
    type: 'text',
    label: 'Project Address',
    placeholder: 'Where architectural services will be provided',
    required: true,
    group: 'project',
  },
  {
    id: 'projectDescription',
    type: 'textarea',
    label: 'Project Description',
    placeholder: 'Detailed description of architectural project',
    required: true,
    group: 'project',
  },
  {
    id: 'projectType',
    type: 'select',
    label: 'Project Type',
    options: [
      { value: 'residential-new', label: 'New Residential Construction' },
      { value: 'residential-renovation', label: 'Residential Renovation' },
      { value: 'commercial-new', label: 'New Commercial Construction' },
      { value: 'commercial-renovation', label: 'Commercial Renovation' },
      { value: 'institutional', label: 'Institutional Building' },
      { value: 'industrial', label: 'Industrial Facility' },
      { value: 'mixed-use', label: 'Mixed-Use Development' },
    ],
    required: true,
    group: 'project',
  },
  {
    id: 'servicesPhase1',
    type: 'checkbox',
    label: 'Schematic Design Phase',
    required: false,
    group: 'services',
  },
  {
    id: 'servicesPhase2',
    type: 'checkbox',
    label: 'Design Development Phase',
    required: false,
    group: 'services',
  },
  {
    id: 'servicesPhase3',
    type: 'checkbox',
    label: 'Construction Documents Phase',
    required: false,
    group: 'services',
  },
  {
    id: 'servicesPhase4',
    type: 'checkbox',
    label: 'Bidding/Negotiation Phase',
    required: false,
    group: 'services',
  },
  {
    id: 'servicesPhase5',
    type: 'checkbox',
    label: 'Construction Administration Phase',
    required: false,
    group: 'services',
  },
  {
    id: 'feeStructure',
    type: 'select',
    label: 'Fee Structure',
    options: [
      { value: 'fixed-fee', label: 'Fixed Fee' },
      { value: 'hourly-rate', label: 'Hourly Rate' },
      { value: 'percentage-of-construction', label: 'Percentage of Construction Cost' },
      { value: 'cost-plus-fee', label: 'Cost Plus Fee' },
    ],
    required: true,
    group: 'compensation',
  },
  {
    id: 'totalFee',
    type: 'text',
    label: 'Total Fee',
    placeholder: 'Enter total project fee',
    required: false,
    group: 'compensation',
  },
  {
    id: 'hourlyRate',
    type: 'text',
    label: 'Hourly Rate',
    placeholder: 'Enter hourly rate',
    required: false,
    group: 'compensation',
    dependsOn: 'feeStructure',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'monthly', label: 'Monthly Payments' },
      { value: 'phase-based', label: 'Phase-Based Payments' },
      { value: 'milestone-based', label: 'Milestone-Based Payments' },
      { value: 'other', label: 'Other Schedule' },
    ],
    required: true,
    group: 'payment',
  },
  {
    id: 'contractDate',
    type: 'date',
    label: 'Contract Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'serviceStartDate',
    type: 'date',
    label: 'Service Start Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'drawingsRequired',
    type: 'checkbox',
    label: 'Architectural drawings required',
    required: false,
    group: 'deliverables',
  },
  {
    id: 'specificationsRequired',
    type: 'checkbox',
    label: 'Technical specifications required',
    required: false,
    group: 'deliverables',
  },
  {
    id: 'renderings',
    type: 'checkbox',
    label: 'Renderings/visualizations included',
    required: false,
    group: 'deliverables',
  },
  {
    id: 'permitDocuments',
    type: 'checkbox',
    label: 'Permit documents included',
    required: false,
    group: 'deliverables',
  },
  {
    id: 'professionalLiabilityInsurance',
    type: 'text',
    label: 'Professional Liability Insurance Amount',
    placeholder: 'Minimum coverage amount required',
    required: true,
    group: 'insurance',
  },
  {
    id: 'sealAndSignature',
    type: 'checkbox',
    label: 'Professional seal and signature required',
    required: false,
    group: 'professional',
  },
  {
    id: 'codeCompliance',
    type: 'checkbox',
    label: 'Building code compliance required',
    required: false,
    group: 'professional',
  },
  {
    id: 'copyrightOwnership',
    type: 'select',
    label: 'Copyright Ownership',
    options: [
      { value: 'architect-retains', label: 'Architect Retains Copyright' },
      { value: 'client-owns', label: 'Client Owns Copyright' },
      { value: 'shared', label: 'Shared Copyright' },
    ],
    required: true,
    group: 'intellectual-property',
  },
  {
    id: 'revisionPolicy',
    type: 'checkbox',
    label: 'Include revision policy',
    required: false,
    group: 'changes',
  },
  {
    id: 'additionalRevisionFee',
    type: 'text',
    label: 'Additional Revision Fee',
    placeholder: 'Fee for revisions beyond scope',
    required: false,
    group: 'changes',
    dependsOn: 'revisionPolicy',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'negotiation', label: 'Negotiation' },
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'litigation', label: 'Court Litigation' },
    ],
    required: true,
    group: 'disputes',
  },
];