import { usStates } from '@/lib/usStates';
import type { Question } from '@/types/documents';

export const serviceAgreementQuestions: Question[] = [
  {
    id: 'providerName',
    label: 'Service provider legal name',
    type: 'text',
    required: true,
    placeholder: 'e.g., Brightside Creative LLC',
  },
  {
    id: 'providerBusinessStructure',
    label: 'Provider business structure',
    type: 'select',
    required: true,
    options: [
      { value: 'sole-proprietor', label: 'Sole proprietor' },
      { value: 'llc', label: 'Limited liability company (LLC)' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'partnership', label: 'Partnership' },
      { value: 'nonprofit', label: 'Nonprofit' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'providerAddress',
    label: 'Provider mailing address',
    type: 'textarea',
    placeholder: 'Street, city, state, ZIP',
  },
  {
    id: 'clientName',
    label: 'Client name',
    type: 'text',
    required: true,
    placeholder: 'Name of the hiring business or individual',
  },
  {
    id: 'clientBusinessStructure',
    label: 'Client business type',
    type: 'select',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'sole-proprietor', label: 'Sole proprietor' },
      { value: 'llc', label: 'LLC' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'partnership', label: 'Partnership' },
      { value: 'nonprofit', label: 'Nonprofit' },
      { value: 'government', label: 'Government entity' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'clientAddress',
    label: 'Client mailing address',
    type: 'textarea',
    placeholder: 'Street, city, state, ZIP',
  },
  {
    id: 'serviceDescription',
    label: 'Describe the services to be provided',
    type: 'textarea',
    required: true,
    placeholder: 'Outline the primary services and objectives',
  },
  {
    id: 'projectScope',
    label: 'Project scope or milestones',
    type: 'textarea',
    placeholder: 'List phases, milestones, or key tasks',
  },
  {
    id: 'startDate',
    label: 'Service start date',
    type: 'date',
    required: true,
  },
  {
    id: 'completionDate',
    label: 'Target completion date',
    type: 'date',
    helperText: 'Leave blank if the agreement is ongoing or evergreen.',
  },
  {
    id: 'paymentStructure',
    label: 'Payment structure',
    type: 'select',
    required: true,
    options: [
      { value: 'flat-fee', label: 'Flat fee' },
      { value: 'hourly', label: 'Hourly' },
      { value: 'milestone', label: 'Milestone-based' },
      { value: 'retainer', label: 'Retainer' },
      { value: 'time-and-materials', label: 'Time and materials' },
    ],
  },
  {
    id: 'paymentAmount',
    label: 'Total fee or rate',
    type: 'number',
    placeholder: 'Enter amount (numbers only)',
    helperText: 'For hourly or milestone work, note the expected rate or installment amount.',
  },
  {
    id: 'paymentSchedule',
    label: 'Payment schedule',
    type: 'select',
    required: true,
    options: [
      { value: 'on-acceptance', label: 'Upon signing' },
      { value: 'weekly', label: 'Weekly' },
      { value: 'bi-weekly', label: 'Bi-weekly' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'upon-completion', label: 'Upon completion' },
      { value: 'per-milestone', label: 'Per milestone' },
    ],
  },
  {
    id: 'expensesReimbursed',
    label: 'Will the client reimburse expenses?',
    type: 'boolean',
  },
  {
    id: 'expensePolicy',
    label: 'Expense reimbursement policy',
    type: 'textarea',
    placeholder: 'Describe categories, caps, and approval process',
    conditional: { field: 'expensesReimbursed', value: true },
  },
  {
    id: 'deliverables',
    label: 'Expected deliverables',
    type: 'textarea',
    placeholder: 'List final deliverables or outputs',
  },
  {
    id: 'acceptanceCriteria',
    label: 'Acceptance criteria',
    type: 'textarea',
    placeholder: 'Explain how the client will accept or approve work',
  },
  {
    id: 'confidentiality',
    label: 'Include a confidentiality clause?',
    type: 'boolean',
    required: true,
  },
  {
    id: 'ipOwnership',
    label: 'Who will own the intellectual property?',
    type: 'select',
    required: true,
    options: [
      { value: 'service-provider', label: 'Service provider retains ownership' },
      { value: 'client', label: 'Client receives ownership' },
      { value: 'shared', label: 'Shared ownership / joint rights' },
    ],
  },
  {
    id: 'supportAndMaintenance',
    label: 'Ongoing support or maintenance obligations',
    type: 'textarea',
    placeholder: 'Outline response times, maintenance windows, or exclusions',
  },
  {
    id: 'terminationNoticeDays',
    label: 'Notice required to terminate (days)',
    type: 'number',
    helperText: 'Typical agreements use 15, 30, or 60 days notice.',
  },
  {
    id: 'disputeResolution',
    label: 'Preferred dispute resolution method',
    type: 'select',
    required: true,
    options: [
      { value: 'negotiation', label: 'Good-faith negotiation' },
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Binding arbitration' },
      { value: 'litigation', label: 'Court litigation' },
    ],
  },
  {
    id: 'governingLawState',
    label: 'State governing the agreement',
    type: 'select',
    required: true,
    options: usStates.map((s) => ({ value: s.value, label: s.label })),
  },
  {
    id: 'noticesEmail',
    label: 'Email for official notices',
    type: 'text',
    placeholder: 'name@example.com',
  },
];
