// src/lib/documents/us/business-contract/questions.ts
import type { FormQuestion } from '@/types/documents';

export const businessContractQuestions: FormQuestion[] = [
  {
    id: 'contractType',
    type: 'select',
    label: 'Type of Business Contract',
    options: [
      { value: 'goods', label: 'Sale/Purchase of Goods' },
      { value: 'services', label: 'Service Agreement' },
      { value: 'partnership', label: 'Business Partnership' },
      { value: 'distribution', label: 'Distribution Agreement' },
      { value: 'consulting', label: 'Consulting Agreement' },
    ],
    required: true,
    group: 'basic',
  },
  {
    id: 'contractTitle',
    type: 'text',
    label: 'Contract Title',
    placeholder:
      'e.g., Software Development Agreement, Product Supply Contract',
    required: true,
    group: 'basic',
  },
  {
    id: 'contractDescription',
    type: 'textarea',
    label: 'Contract Description',
    placeholder: 'Describe the purpose and scope of this contract',
    required: true,
    group: 'basic',
  },
  {
    id: 'party1Name',
    type: 'text',
    label: 'First Party Name',
    placeholder: 'Enter company or individual name',
    required: true,
    group: 'party1',
  },
  {
    id: 'party1Type',
    type: 'select',
    label: 'First Party Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'llc', label: 'LLC' },
      { value: 'partnership', label: 'Partnership' },
    ],
    required: true,
    group: 'party1',
  },
  {
    id: 'party1Address',
    type: 'textarea',
    label: 'First Party Address',
    placeholder: 'Enter complete business address',
    required: true,
    group: 'party1',
  },
  {
    id: 'party1Contact',
    type: 'text',
    label: 'First Party Contact Person',
    placeholder: 'Contact person name and title',
    required: false,
    group: 'party1',
  },
  {
    id: 'party2Name',
    type: 'text',
    label: 'Second Party Name',
    placeholder: 'Enter company or individual name',
    required: true,
    group: 'party2',
  },
  {
    id: 'party2Type',
    type: 'select',
    label: 'Second Party Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'llc', label: 'LLC' },
      { value: 'partnership', label: 'Partnership' },
    ],
    required: true,
    group: 'party2',
  },
  {
    id: 'party2Address',
    type: 'textarea',
    label: 'Second Party Address',
    placeholder: 'Enter complete business address',
    required: true,
    group: 'party2',
  },
  {
    id: 'party2Contact',
    type: 'text',
    label: 'Second Party Contact Person',
    placeholder: 'Contact person name and title',
    required: false,
    group: 'party2',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Contract Effective Date',
    required: true,
    group: 'terms',
  },
  {
    id: 'expirationDate',
    type: 'date',
    label: 'Contract Expiration Date',
    required: false,
    group: 'terms',
  },
  {
    id: 'termLength',
    type: 'text',
    label: 'Contract Term',
    placeholder: 'e.g., 1 year, 6 months, ongoing',
    required: false,
    group: 'terms',
  },
  {
    id: 'autoRenewal',
    type: 'checkbox',
    label: 'Automatic renewal clause',
    required: false,
    group: 'terms',
  },
  {
    id: 'hasPayment',
    type: 'checkbox',
    label: 'This contract involves payment',
    required: false,
    group: 'financial',
  },
  {
    id: 'paymentAmount',
    type: 'number',
    label: 'Payment Amount ($)',
    placeholder: '10000',
    required: false,
    group: 'financial',
    dependsOn: 'hasPayment',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'one-time', label: 'One-time Payment' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
      { value: 'annually', label: 'Annually' },
      { value: 'milestone-based', label: 'Milestone-based' },
    ],
    required: false,
    group: 'financial',
    dependsOn: 'hasPayment',
  },
  {
    id: 'paymentTerms',
    type: 'textarea',
    label: 'Payment Terms',
    placeholder: 'Specify payment terms, due dates, methods, etc.',
    required: false,
    group: 'financial',
    dependsOn: 'hasPayment',
  },
  {
    id: 'deliverables',
    type: 'textarea',
    label: 'Deliverables/Services',
    placeholder: 'Describe what will be delivered or performed',
    required: false,
    group: 'deliverables',
  },
  {
    id: 'deliverySchedule',
    type: 'textarea',
    label: 'Delivery Schedule',
    placeholder: 'Specify delivery dates and milestones',
    required: false,
    group: 'deliverables',
  },
  {
    id: 'performanceStandards',
    type: 'textarea',
    label: 'Performance Standards',
    placeholder: 'Define quality standards and acceptance criteria',
    required: false,
    group: 'deliverables',
  },
  {
    id: 'confidentialityClause',
    type: 'checkbox',
    label: 'Include confidentiality clause',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'confidentialityTerms',
    type: 'textarea',
    label: 'Confidentiality Terms',
    placeholder: 'Specify confidentiality obligations',
    required: false,
    group: 'confidentiality',
    dependsOn: 'confidentialityClause',
  },
  {
    id: 'terminationClause',
    type: 'textarea',
    label: 'Termination Conditions',
    placeholder:
      'Specify conditions under which the contract can be terminated',
    required: false,
    group: 'termination',
  },
  {
    id: 'noticePeriod',
    type: 'text',
    label: 'Notice Period for Termination',
    placeholder: '30 days',
    required: false,
    group: 'termination',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'litigation', label: 'Court Litigation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'mediation', label: 'Mediation' },
    ],
    required: false,
    group: 'disputes',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'e.g., State of California',
    required: false,
    group: 'disputes',
  },
  {
    id: 'additionalTerms',
    type: 'textarea',
    label: 'Additional Terms',
    placeholder: 'Any additional terms or special provisions',
    required: false,
    group: 'additional',
  },
];
