// src/lib/documents/us/durable-power-of-attorney/questions.ts
import type { FormQuestion } from '@/types/documents';

export const durablePowerOfAttorneyQuestions: FormQuestion[] = [
  {
    id: 'principalName',
    type: 'text',
    label: 'Your Full Legal Name (Principal)',
    placeholder: 'Enter your full legal name',
    required: true,
    group: 'principal',
  },
  {
    id: 'principalAddress',
    type: 'textarea',
    label: 'Your Address',
    placeholder: 'Enter your complete address',
    required: true,
    group: 'principal',
  },
  {
    id: 'principalPhone',
    type: 'tel',
    label: 'Your Phone Number',
    placeholder: '(555) 123-4567',
    required: false,
    group: 'principal',
  },
  {
    id: 'principalEmail',
    type: 'email',
    label: 'Your Email',
    placeholder: 'your@email.com',
    required: false,
    group: 'principal',
  },
  {
    id: 'agentName',
    type: 'text',
    label: 'Agent Name (Attorney-in-Fact)',
    placeholder: 'Full name of person you are appointing',
    required: true,
    group: 'agent',
  },
  {
    id: 'agentAddress',
    type: 'textarea',
    label: 'Agent Address',
    placeholder: 'Complete address of your agent',
    required: true,
    group: 'agent',
  },
  {
    id: 'agentPhone',
    type: 'tel',
    label: 'Agent Phone Number',
    placeholder: '(555) 123-4567',
    required: false,
    group: 'agent',
  },
  {
    id: 'agentEmail',
    type: 'email',
    label: 'Agent Email',
    placeholder: 'agent@email.com',
    required: false,
    group: 'agent',
  },
  {
    id: 'agentRelationship',
    type: 'text',
    label: 'Agent Relationship to You',
    placeholder: 'e.g., spouse, child, attorney, friend',
    required: true,
    group: 'agent',
  },
  {
    id: 'hasSuccessorAgent',
    type: 'checkbox',
    label: 'I want to name a successor agent',
    required: false,
    group: 'successor',
  },
  {
    id: 'successorAgentName',
    type: 'text',
    label: 'Successor Agent Name',
    placeholder: 'Full name of successor agent',
    required: false,
    group: 'successor',
    dependsOn: 'hasSuccessorAgent',
  },
  {
    id: 'successorAgentAddress',
    type: 'textarea',
    label: 'Successor Agent Address',
    placeholder: 'Complete address of successor agent',
    required: false,
    group: 'successor',
    dependsOn: 'hasSuccessorAgent',
  },
  {
    id: 'successorAgentRelationship',
    type: 'text',
    label: 'Successor Agent Relationship',
    placeholder: 'e.g., daughter, attorney, brother',
    required: false,
    group: 'successor',
    dependsOn: 'hasSuccessorAgent',
  },
  {
    id: 'immediatelyEffective',
    type: 'checkbox',
    label: 'This power of attorney is effective immediately',
    required: false,
    group: 'effective',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Effective Date (if not immediate)',
    required: false,
    group: 'effective',
  },
  {
    id: 'springingPOA',
    type: 'checkbox',
    label: 'This is a "springing" power of attorney (becomes effective upon my incapacity)',
    required: false,
    group: 'effective',
  },
  {
    id: 'springingConditions',
    type: 'textarea',
    label: 'Conditions for Springing POA',
    placeholder: 'Describe the conditions that must be met for the POA to become effective',
    required: false,
    group: 'effective',
    dependsOn: 'springingPOA',
  },
  {
    id: 'giftingPowers',
    type: 'checkbox',
    label: 'Grant agent power to make gifts',
    required: false,
    group: 'special-powers',
  },
  {
    id: 'giftingLimits',
    type: 'textarea',
    label: 'Gifting Limitations',
    placeholder: 'Specify any limits on gifting powers',
    required: false,
    group: 'special-powers',
    dependsOn: 'giftingPowers',
  },
  {
    id: 'createTrustPowers',
    type: 'checkbox',
    label: 'Grant agent power to create, modify, or revoke trusts',
    required: false,
    group: 'special-powers',
  },
  {
    id: 'changeBeneficiaryPowers',
    type: 'checkbox',
    label: 'Grant agent power to change beneficiaries on accounts and policies',
    required: false,
    group: 'special-powers',
  },
  {
    id: 'powerLimitations',
    type: 'textarea',
    label: 'Limitations on Agent Powers',
    placeholder: 'Specify any limitations on the agent\'s authority',
    required: false,
    group: 'limitations',
  },
  {
    id: 'prohibitedActions',
    type: 'textarea',
    label: 'Prohibited Actions',
    placeholder: 'List any actions the agent is specifically prohibited from taking',
    required: false,
    group: 'limitations',
  },
  {
    id: 'agentCompensation',
    type: 'select',
    label: 'Agent Compensation',
    options: [
      { value: 'none', label: 'No Compensation' },
      { value: 'reasonable', label: 'Reasonable Compensation' },
      { value: 'specific-amount', label: 'Specific Amount' },
    ],
    required: false,
    group: 'compensation',
  },
  {
    id: 'compensationAmount',
    type: 'text',
    label: 'Compensation Amount/Terms',
    placeholder: 'Specify compensation amount or terms',
    required: false,
    group: 'compensation',
    dependsOn: 'agentCompensation',
  },
  {
    id: 'terminationConditions',
    type: 'textarea',
    label: 'Termination Conditions',
    placeholder: 'Specify conditions under which this POA will terminate',
    required: false,
    group: 'termination',
  },
  {
    id: 'additionalProvisions',
    type: 'textarea',
    label: 'Additional Provisions',
    placeholder: 'Any additional terms or provisions',
    required: false,
    group: 'additional',
  },
];