// src/lib/documents/us/work-from-home-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const workFromHomeAgreementQuestions: FormQuestion[] = [
  {
    id: 'companyName',
    type: 'text',
    label: 'Company Name',
    placeholder: 'Enter company name',
    required: true,
    group: 'company',
  },
  {
    id: 'companyAddress',
    type: 'text',
    label: 'Company Address',
    placeholder: 'Enter complete company address',
    required: true,
    group: 'company',
  },
  {
    id: 'employeeName',
    type: 'text',
    label: 'Employee Name',
    placeholder: 'Enter employee full name',
    required: true,
    group: 'employee',
  },
  {
    id: 'employeeAddress',
    type: 'text',
    label: 'Employee Address',
    placeholder: 'Enter employee address',
    required: true,
    group: 'employee',
  },
  {
    id: 'jobTitle',
    type: 'text',
    label: 'Job Title',
    placeholder: 'Enter employee job title',
    required: true,
    group: 'employee',
  },
  {
    id: 'department',
    type: 'text',
    label: 'Department',
    placeholder: 'Enter department name',
    required: false,
    group: 'employee',
  },
  {
    id: 'agreementDate',
    type: 'date',
    label: 'Agreement Date',
    required: true,
    group: 'dates',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Effective Date',
    required: true,
    group: 'dates',
  },
  {
    id: 'isTemporary',
    type: 'checkbox',
    label: 'Temporary work from home arrangement',
    required: false,
    group: 'dates',
  },
  {
    id: 'endDate',
    type: 'date',
    label: 'End Date',
    required: false,
    group: 'dates',
    dependsOn: 'isTemporary',
  },
  {
    id: 'workDays',
    type: 'checkbox',
    label: 'Work Days (select all that apply)',
    options: [
      { value: 'monday', label: 'Monday' },
      { value: 'tuesday', label: 'Tuesday' },
      { value: 'wednesday', label: 'Wednesday' },
      { value: 'thursday', label: 'Thursday' },
      { value: 'friday', label: 'Friday' },
      { value: 'saturday', label: 'Saturday' },
      { value: 'sunday', label: 'Sunday' },
    ],
    required: true,
    group: 'schedule',
  },
  {
    id: 'workHours',
    type: 'text',
    label: 'Work Hours',
    placeholder: 'e.g., 9:00 AM - 5:00 PM',
    required: true,
    group: 'schedule',
  },
  {
    id: 'timeZone',
    type: 'text',
    label: 'Time Zone',
    placeholder: 'e.g., Eastern Time',
    required: false,
    group: 'schedule',
  },
  {
    id: 'coreHours',
    type: 'text',
    label: 'Core Hours (if applicable)',
    placeholder: 'e.g., 10:00 AM - 3:00 PM',
    required: false,
    group: 'schedule',
  },
  {
    id: 'flexibleSchedule',
    type: 'checkbox',
    label: 'Allow flexible schedule within core hours',
    required: false,
    group: 'schedule',
  },
  {
    id: 'homeAddress',
    type: 'text',
    label: 'Home Work Address',
    placeholder: 'Where employee will be working from',
    required: true,
    group: 'location',
  },
  {
    id: 'dedicatedWorkspace',
    type: 'checkbox',
    label: 'Require dedicated workspace',
    required: false,
    group: 'location',
  },
  {
    id: 'workspaceRequirements',
    type: 'textarea',
    label: 'Workspace Requirements',
    placeholder: 'Describe any specific workspace requirements',
    required: false,
    group: 'location',
  },
  {
    id: 'companyEquipment',
    type: 'checkbox',
    label: 'Company will provide equipment',
    required: false,
    group: 'equipment',
  },
  {
    id: 'employeeEquipment',
    type: 'checkbox',
    label: 'Employee will use personal equipment',
    required: false,
    group: 'equipment',
  },
  {
    id: 'internetReimbursement',
    type: 'checkbox',
    label: 'Provide internet reimbursement',
    required: false,
    group: 'reimbursement',
  },
  {
    id: 'reimbursementAmount',
    type: 'text',
    label: 'Internet Reimbursement Amount',
    placeholder: 'Monthly amount',
    required: false,
    group: 'reimbursement',
    dependsOn: 'internetReimbursement',
  },
  {
    id: 'phoneReimbursement',
    type: 'checkbox',
    label: 'Provide phone reimbursement',
    required: false,
    group: 'reimbursement',
  },
  {
    id: 'phoneAmount',
    type: 'text',
    label: 'Phone Reimbursement Amount',
    placeholder: 'Monthly amount',
    required: false,
    group: 'reimbursement',
    dependsOn: 'phoneReimbursement',
  },
  {
    id: 'utilityReimbursement',
    type: 'checkbox',
    label: 'Provide utility reimbursement',
    required: false,
    group: 'reimbursement',
  },
  {
    id: 'utilityAmount',
    type: 'text',
    label: 'Utility Reimbursement Amount',
    placeholder: 'Monthly amount',
    required: false,
    group: 'reimbursement',
    dependsOn: 'utilityReimbursement',
  },
  {
    id: 'officeSupplies',
    type: 'checkbox',
    label: 'Company provides office supplies',
    required: false,
    group: 'reimbursement',
  },
  {
    id: 'vpnRequired',
    type: 'checkbox',
    label: 'Require VPN for data security',
    required: false,
    group: 'security',
  },
  {
    id: 'securitySoftware',
    type: 'checkbox',
    label: 'Require company security software',
    required: false,
    group: 'security',
  },
  {
    id: 'confidentialityAgreement',
    type: 'checkbox',
    label: 'Include confidentiality requirements',
    required: false,
    group: 'security',
  },
  {
    id: 'reportingSchedule',
    type: 'select',
    label: 'Reporting Schedule',
    options: [
      { value: 'daily', label: 'Daily' },
      { value: 'weekly', label: 'Weekly' },
      { value: 'bi-weekly', label: 'Bi-weekly' },
      { value: 'monthly', label: 'Monthly' },
    ],
    required: false,
    group: 'communication',
  },
  {
    id: 'checkInFrequency',
    type: 'select',
    label: 'Check-in Frequency',
    options: [
      { value: 'daily', label: 'Daily' },
      { value: 'weekly', label: 'Weekly' },
      { value: 'bi-weekly', label: 'Bi-weekly' },
      { value: 'monthly', label: 'Monthly' },
    ],
    required: false,
    group: 'communication',
  },
  {
    id: 'officeAccess',
    type: 'checkbox',
    label: 'Employee retains office access',
    required: false,
    group: 'office',
  },
  {
    id: 'officeVisitRequirements',
    type: 'text',
    label: 'Office Visit Requirements',
    placeholder: 'e.g., Monthly team meetings',
    required: false,
    group: 'office',
  },
  {
    id: 'ergonomicRequirements',
    type: 'checkbox',
    label: 'Include ergonomic workspace requirements',
    required: false,
    group: 'safety',
  },
  {
    id: 'workersCompCoverage',
    type: 'checkbox',
    label: 'Workers compensation covers home office',
    required: false,
    group: 'safety',
  },
  {
    id: 'terminationClause',
    type: 'checkbox',
    label: 'Include termination clause',
    required: false,
    group: 'termination',
  },
  {
    id: 'noticeRequirement',
    type: 'text',
    label: 'Notice Requirement for Termination',
    placeholder: 'e.g., 30 days written notice',
    required: false,
    group: 'termination',
    dependsOn: 'terminationClause',
  },
  {
    id: 'equipmentReturn',
    type: 'checkbox',
    label: 'Require equipment return upon termination',
    required: false,
    group: 'termination',
  },
  {
    id: 'taxImplications',
    type: 'checkbox',
    label: 'Include tax implications notice',
    required: false,
    group: 'legal',
  },
  {
    id: 'laborLawCompliance',
    type: 'checkbox',
    label: 'Include labor law compliance clause',
    required: false,
    group: 'legal',
  },
  {
    id: 'requireEmployeeSignature',
    type: 'checkbox',
    label: 'Require employee signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireEmployerSignature',
    type: 'checkbox',
    label: 'Require employer signature',
    required: false,
    group: 'signatures',
  },
];
