// src/lib/documents/us/purchase-order/questions.ts
import type { FormQuestion } from '@/types/documents';

export const purchaseOrderQuestions: FormQuestion[] = [
  // Purchase Order Header
  {
    id: 'poNumber',
    type: 'text',
    label: 'Purchase Order Number',
    placeholder: 'Enter PO number (e.g., PO-2024-001)',
    required: true,
    section: 'Purchase Order Information',
  },
  {
    id: 'poDate',
    type: 'date',
    label: 'Purchase Order Date',
    required: true,
    section: 'Purchase Order Information',
  },
  {
    id: 'requisitionNumber',
    type: 'text',
    label: 'Requisition Number (if applicable)',
    placeholder: 'Enter requisition number',
    required: false,
    section: 'Purchase Order Information',
  },
  {
    id: 'priority',
    type: 'select',
    label: 'Priority Level',
    options: [
      { value: 'standard', label: 'Standard' },
      { value: 'urgent', label: 'Urgent' },
      { value: 'rush', label: 'Rush' },
    ],
    required: true,
    section: 'Purchase Order Information',
  },

  // Buyer Information
  {
    id: 'buyerCompany',
    type: 'text',
    label: 'Buyer Company Name',
    placeholder: 'Enter your company name',
    required: true,
    section: 'Buyer Information',
  },
  {
    id: 'buyerAddress',
    type: 'address',
    label: 'Buyer Address',
    placeholder: 'Enter complete buyer address',
    required: true,
    section: 'Buyer Information',
  },
  {
    id: 'buyerContact',
    type: 'text',
    label: 'Buyer Contact Person',
    placeholder: 'Enter contact person name',
    required: true,
    section: 'Buyer Information',
  },
  {
    id: 'buyerPhone',
    type: 'tel',
    label: 'Buyer Phone Number',
    placeholder: 'Enter phone number',
    required: true,
    section: 'Buyer Information',
  },
  {
    id: 'buyerEmail',
    type: 'email',
    label: 'Buyer Email Address',
    placeholder: 'Enter email address',
    required: true,
    section: 'Buyer Information',
  },
  {
    id: 'buyerDepartment',
    type: 'text',
    label: 'Department (if applicable)',
    placeholder: 'Enter department name',
    required: false,
    section: 'Buyer Information',
  },

  // Vendor Information
  {
    id: 'vendorCompany',
    type: 'text',
    label: 'Vendor Company Name',
    placeholder: 'Enter vendor/supplier company name',
    required: true,
    section: 'Vendor Information',
  },
  {
    id: 'vendorAddress',
    type: 'address',
    label: 'Vendor Address',
    placeholder: 'Enter complete vendor address',
    required: true,
    section: 'Vendor Information',
  },
  {
    id: 'vendorContact',
    type: 'text',
    label: 'Vendor Contact Person',
    placeholder: 'Enter vendor contact name',
    required: false,
    section: 'Vendor Information',
  },
  {
    id: 'vendorPhone',
    type: 'tel',
    label: 'Vendor Phone Number',
    placeholder: 'Enter vendor phone number',
    required: false,
    section: 'Vendor Information',
  },
  {
    id: 'vendorEmail',
    type: 'email',
    label: 'Vendor Email Address',
    placeholder: 'Enter vendor email',
    required: false,
    section: 'Vendor Information',
  },
  {
    id: 'vendorAccountNumber',
    type: 'text',
    label: 'Vendor Account Number',
    placeholder: 'Enter your account number with vendor',
    required: false,
    section: 'Vendor Information',
  },

  // Shipping Information
  {
    id: 'shipToCompany',
    type: 'text',
    label: 'Ship To Company',
    placeholder: 'Enter shipping destination company',
    required: true,
    section: 'Shipping Information',
  },
  {
    id: 'shipToAddress',
    type: 'address',
    label: 'Ship To Address',
    placeholder: 'Enter complete shipping address',
    required: true,
    section: 'Shipping Information',
  },
  {
    id: 'shipToContact',
    type: 'text',
    label: 'Ship To Contact Person',
    placeholder: 'Enter contact at shipping location',
    required: false,
    section: 'Shipping Information',
  },
  {
    id: 'shipToPhone',
    type: 'tel',
    label: 'Ship To Phone Number',
    placeholder: 'Enter shipping location phone',
    required: false,
    section: 'Shipping Information',
  },
  {
    id: 'shippingMethod',
    type: 'select',
    label: 'Preferred Shipping Method',
    options: [
      { value: 'ground', label: 'Ground shipping' },
      { value: 'express', label: 'Express shipping' },
      { value: 'overnight', label: 'Overnight shipping' },
      { value: 'freight', label: 'Freight shipping' },
      { value: 'pickup', label: 'Pickup' },
      { value: 'standard', label: 'Standard shipping' },
    ],
    required: true,
    section: 'Shipping Information',
  },
  {
    id: 'requestedDeliveryDate',
    type: 'date',
    label: 'Requested Delivery Date',
    required: true,
    section: 'Shipping Information',
  },

  // Billing Information
  {
    id: 'billToCompany',
    type: 'text',
    label: 'Bill To Company',
    placeholder: 'Enter billing company name',
    required: true,
    section: 'Billing Information',
  },
  {
    id: 'billToAddress',
    type: 'address',
    label: 'Bill To Address',
    placeholder: 'Enter complete billing address',
    required: true,
    section: 'Billing Information',
  },
  {
    id: 'billToContact',
    type: 'text',
    label: 'Bill To Contact Person',
    placeholder: 'Enter billing contact name',
    required: false,
    section: 'Billing Information',
  },
  {
    id: 'billToPhone',
    type: 'tel',
    label: 'Bill To Phone Number',
    placeholder: 'Enter billing contact phone',
    required: false,
    section: 'Billing Information',
  },

  // Line Items
  {
    id: 'lineItems',
    type: 'textarea',
    label: 'Line Items',
    placeholder:
      'List items to purchase:\n\nItem 1: Description, Quantity, Unit Price\nItem 2: Description, Quantity, Unit Price\n\nExample:\nOffice Chairs, 10, $150.00 each\nDesks, 5, $300.00 each',
    required: true,
    section: 'Items to Purchase',
  },

  // Totals
  {
    id: 'subtotal',
    type: 'currency',
    label: 'Subtotal',
    placeholder: 'Enter subtotal amount',
    required: true,
    section: 'Pricing',
  },
  {
    id: 'taxRate',
    type: 'text',
    label: 'Tax Rate (if applicable)',
    placeholder: 'e.g., 8.25%',
    required: false,
    section: 'Pricing',
  },
  {
    id: 'taxAmount',
    type: 'currency',
    label: 'Tax Amount (if applicable)',
    placeholder: 'Enter tax amount',
    required: false,
    section: 'Pricing',
  },
  {
    id: 'shippingCost',
    type: 'currency',
    label: 'Shipping Cost (if applicable)',
    placeholder: 'Enter shipping cost',
    required: false,
    section: 'Pricing',
  },
  {
    id: 'discountAmount',
    type: 'currency',
    label: 'Discount Amount (if applicable)',
    placeholder: 'Enter discount amount',
    required: false,
    section: 'Pricing',
  },
  {
    id: 'totalAmount',
    type: 'currency',
    label: 'Total Amount',
    placeholder: 'Enter total purchase amount',
    required: true,
    section: 'Pricing',
  },

  // Payment Terms
  {
    id: 'paymentTerms',
    type: 'select',
    label: 'Payment Terms',
    options: [
      { value: 'net_15', label: 'Net 15 days' },
      { value: 'net_30', label: 'Net 30 days' },
      { value: 'net_45', label: 'Net 45 days' },
      { value: 'net_60', label: 'Net 60 days' },
      { value: 'due_on_receipt', label: 'Due on receipt' },
      { value: 'cod', label: 'Cash on delivery (COD)' },
      { value: 'prepaid', label: 'Prepaid' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    section: 'Payment Terms',
  },
  {
    id: 'paymentTermsOther',
    type: 'text',
    label: 'Other Payment Terms',
    placeholder: 'Specify other payment terms',
    required: false,
    section: 'Payment Terms',
    conditional: {
      field: 'paymentTerms',
      value: ['other'],
    },
  },
  {
    id: 'paymentMethod',
    type: 'select',
    label: 'Payment Method',
    options: [
      { value: 'check', label: 'Check' },
      { value: 'ach', label: 'ACH/Electronic transfer' },
      { value: 'wire_transfer', label: 'Wire transfer' },
      { value: 'credit_card', label: 'Credit card' },
      { value: 'purchase_card', label: 'Purchase card' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    section: 'Payment Terms',
  },

  // Delivery Terms
  {
    id: 'deliveryTerms',
    type: 'select',
    label: 'Delivery Terms',
    options: [
      { value: 'fob_origin', label: 'FOB Origin' },
      { value: 'fob_destination', label: 'FOB Destination' },
      { value: 'cif', label: 'CIF (Cost, Insurance, Freight)' },
      { value: 'exw', label: 'EXW (Ex Works)' },
      { value: 'dap', label: 'DAP (Delivered at Place)' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    section: 'Delivery Terms',
  },
  {
    id: 'deliveryTermsOther',
    type: 'text',
    label: 'Other Delivery Terms',
    placeholder: 'Specify other delivery terms',
    required: false,
    section: 'Delivery Terms',
    conditional: {
      field: 'deliveryTerms',
      value: ['other'],
    },
  },

  // Approval Information
  {
    id: 'approvedBy',
    type: 'text',
    label: 'Approved By',
    placeholder: 'Enter approver name',
    required: true,
    section: 'Approval',
  },
  {
    id: 'approverTitle',
    type: 'text',
    label: 'Approver Title',
    placeholder: 'Enter approver title',
    required: false,
    section: 'Approval',
  },
  {
    id: 'approvalDate',
    type: 'date',
    label: 'Approval Date',
    required: true,
    section: 'Approval',
  },
  {
    id: 'budgetCode',
    type: 'text',
    label: 'Budget Code (if applicable)',
    placeholder: 'Enter budget code',
    required: false,
    section: 'Approval',
  },
  {
    id: 'projectCode',
    type: 'text',
    label: 'Project Code (if applicable)',
    placeholder: 'Enter project code',
    required: false,
    section: 'Approval',
  },

  // Tax Information
  {
    id: 'currency',
    type: 'select',
    label: 'Currency',
    options: [
      { value: 'USD', label: 'US Dollar (USD)' },
      { value: 'EUR', label: 'Euro (EUR)' },
      { value: 'CAD', label: 'Canadian Dollar (CAD)' },
      { value: 'GBP', label: 'British Pound (GBP)' },
    ],
    required: true,
    section: 'Tax Information',
  },
  {
    id: 'taxExempt',
    type: 'radio',
    label: 'Tax exempt status',
    options: [
      { value: true, label: 'Tax exempt' },
      { value: false, label: 'Subject to tax' },
    ],
    required: true,
    section: 'Tax Information',
  },
  {
    id: 'taxExemptNumber',
    type: 'text',
    label: 'Tax Exempt Number',
    placeholder: 'Enter tax exempt certificate number',
    required: false,
    section: 'Tax Information',
    conditional: {
      field: 'taxExempt',
      value: [true],
    },
  },

  // Vendor Response
  {
    id: 'vendorConfirmationRequired',
    type: 'radio',
    label: 'Vendor confirmation required?',
    options: [
      { value: true, label: 'Yes, vendor must confirm' },
      { value: false, label: 'No confirmation required' },
    ],
    required: true,
    section: 'Vendor Response',
  },
  {
    id: 'vendorResponseDeadline',
    type: 'date',
    label: 'Vendor Response Deadline',
    required: false,
    section: 'Vendor Response',
    conditional: {
      field: 'vendorConfirmationRequired',
      value: [true],
    },
  },

  // Contract Reference
  {
    id: 'contractReference',
    type: 'text',
    label: 'Contract Reference (if applicable)',
    placeholder: 'Enter contract reference number',
    required: false,
    section: 'Contract Information',
  },
  {
    id: 'agreementNumber',
    type: 'text',
    label: 'Agreement Number (if applicable)',
    placeholder: 'Enter agreement number',
    required: false,
    section: 'Contract Information',
  },

  // Special Instructions
  {
    id: 'specialInstructions',
    type: 'textarea',
    label: 'Special Instructions',
    placeholder: 'Enter any special instructions for the vendor',
    required: false,
    section: 'Instructions',
  },
  {
    id: 'packingInstructions',
    type: 'textarea',
    label: 'Packing Instructions',
    placeholder: 'Enter specific packing requirements',
    required: false,
    section: 'Instructions',
  },
  {
    id: 'qualityRequirements',
    type: 'textarea',
    label: 'Quality Requirements',
    placeholder: 'Enter quality standards or requirements',
    required: false,
    section: 'Instructions',
  },

  // Terms and Conditions
  {
    id: 'warrantyRequirements',
    type: 'textarea',
    label: 'Warranty Requirements',
    placeholder: 'Enter warranty requirements',
    required: false,
    section: 'Terms and Conditions',
  },
  {
    id: 'returnPolicy',
    type: 'textarea',
    label: 'Return Policy',
    placeholder: 'Enter return policy requirements',
    required: false,
    section: 'Terms and Conditions',
  },
  {
    id: 'cancellationPolicy',
    type: 'textarea',
    label: 'Cancellation Policy',
    placeholder: 'Enter cancellation terms',
    required: false,
    section: 'Terms and Conditions',
  },
  {
    id: 'complianceRequirements',
    type: 'textarea',
    label: 'Compliance Requirements',
    placeholder: 'Enter any compliance requirements',
    required: false,
    section: 'Terms and Conditions',
  },

  // Tracking
  {
    id: 'expedite',
    type: 'radio',
    label: 'Expedite this order?',
    options: [
      { value: true, label: 'Yes, expedite this order' },
      { value: false, label: 'No, standard processing' },
    ],
    required: true,
    section: 'Order Tracking',
  },
  {
    id: 'expediteReason',
    type: 'textarea',
    label: 'Expedite Reason',
    placeholder: 'Explain why expediting is necessary',
    required: false,
    section: 'Order Tracking',
    conditional: {
      field: 'expedite',
      value: [true],
    },
  },
  {
    id: 'followUpRequired',
    type: 'radio',
    label: 'Follow-up required?',
    options: [
      { value: true, label: 'Yes, follow-up required' },
      { value: false, label: 'No follow-up needed' },
    ],
    required: true,
    section: 'Order Tracking',
  },
  {
    id: 'followUpDate',
    type: 'date',
    label: 'Follow-up Date',
    required: false,
    section: 'Order Tracking',
    conditional: {
      field: 'followUpRequired',
      value: [true],
    },
  },

  // Attachments
  {
    id: 'attachments',
    type: 'textarea',
    label: 'Attachments',
    placeholder: 'List any attached documents (specifications, drawings, etc.)',
    required: false,
    section: 'Attachments',
  },
  {
    id: 'technicalSpecifications',
    type: 'textarea',
    label: 'Technical Specifications',
    placeholder: 'Enter detailed technical specifications',
    required: false,
    section: 'Attachments',
  },
  {
    id: 'drawingsRequired',
    type: 'radio',
    label: 'Technical drawings required?',
    options: [
      { value: true, label: 'Yes, technical drawings required' },
      { value: false, label: 'No drawings required' },
    ],
    required: true,
    section: 'Attachments',
  },

  // Notes
  {
    id: 'internalNotes',
    type: 'textarea',
    label: 'Internal Notes',
    placeholder: 'Enter internal notes (not visible to vendor)',
    required: false,
    section: 'Notes',
  },
  {
    id: 'vendorNotes',
    type: 'textarea',
    label: 'Notes to Vendor',
    placeholder: 'Enter additional notes for the vendor',
    required: false,
    section: 'Notes',
  },
];
