// src/lib/documents/us/bill-of-sale-vehicle/questions.ts
// Ordered question list for the vehicle bill of sale wizard
import { usStates } from '@/lib/document-library/utils';

export const billOfSaleVehicleQuestions = [
  {
    id: 'seller_info',
    label: 'documents.us.bill-of-sale-vehicle.seller_info.label',
    type: 'group',
    fields: [
      'seller_name',
      'seller_phone',
      'seller_address',
      'seller2_name',
      'seller2_phone',
    ],
  },
  {
    id: 'buyer_info',
    label: 'documents.us.bill-of-sale-vehicle.buyer_info.label',
    type: 'group',
    fields: [
      'buyer_name',
      'buyer_phone',
      'buyer_address',
      'buyer2_name',
      'buyer2_phone',
    ],
  },
  {
    id: 'year',
    label: 'documents.us.bill-of-sale-vehicle.year.label',
    type: 'number',
    placeholder: 'e.g., 2020',
    required: true,
    tooltip: 'documents.us.bill-of-sale-vehicle.year.tooltip',
  },
  {
    id: 'make',
    label: 'documents.us.bill-of-sale-vehicle.make.label',
    type: 'text',
    placeholder: 'e.g., Toyota',
    required: true,
    tooltip: 'documents.us.bill-of-sale-vehicle.make.tooltip',
  },
  {
    id: 'model',
    label: 'documents.us.bill-of-sale-vehicle.model.label',
    type: 'text',
    placeholder: 'e.g., Camry',
    required: true,
    tooltip: 'documents.us.bill-of-sale-vehicle.model.tooltip',
  },
  {
    id: 'color',
    label: 'documents.us.bill-of-sale-vehicle.color.label',
    type: 'text',
    placeholder: 'e.g., Blue',
    required: true,
    tooltip: 'documents.us.bill-of-sale-vehicle.color.tooltip',
  },
  {
    id: 'vin',
    label: 'documents.us.bill-of-sale-vehicle.vin.label',
    type: 'text',
    required: true,
    tooltip: 'documents.us.bill-of-sale-vehicle.vin.tooltip',
  },
  {
    id: 'odometer',
    label: 'documents.us.bill-of-sale-vehicle.odometer.label',
    type: 'number',
    required: true,
    tooltip: 'documents.us.bill-of-sale-vehicle.odometer.tooltip',
  },
  {
    id: 'odo_status',
    label: 'documents.us.bill-of-sale-vehicle.odo_status.label',
    type: 'select',
    required: true,
    options: [
      { value: 'ACTUAL', label: 'Actual Mileage' },
      { value: 'EXCEEDS', label: 'Exceeds Mechanical Limits' },
      { value: 'NOT_ACTUAL', label: 'Not Actual Mileage (Warning)' },
    ],
    tooltip: 'documents.us.bill-of-sale-vehicle.odo_status.tooltip',
  },
  {
    id: 'price',
    label: 'documents.us.bill-of-sale-vehicle.price.label',
    type: 'number',
    required: true,
    tooltip: 'documents.us.bill-of-sale-vehicle.price.tooltip',
  },
  {
    id: 'payment_method',
    label: 'documents.us.bill-of-sale-vehicle.payment_method.label',
    type: 'select',
    required: false,
    options: [
      { value: 'cash', label: 'Cash' },
      { value: 'check', label: 'Check' },
      { value: 'wire', label: 'Wire Transfer' },
      { value: 'paypal', label: 'PayPal' },
      { value: 'credit_card', label: 'Credit / Debit Card' },
    ],
    tooltip: 'documents.us.bill-of-sale-vehicle.payment_method.tooltip',
  },
  {
    id: 'sale_date',
    label: 'documents.us.bill-of-sale-vehicle.sale_date.label',
    type: 'date',
    required: true,
    tooltip: 'documents.us.bill-of-sale-vehicle.sale_date.tooltip',
  },
  {
    id: 'existing_liens',
    label: 'documents.us.bill-of-sale-vehicle.existing_liens.label',
    type: 'text',
    placeholder: 'e.g., None, or Loan with XYZ Bank',
    tooltip: 'documents.us.bill-of-sale-vehicle.existing_liens.tooltip',
  },
  {
    id: 'as_is',
    label: 'documents.us.bill-of-sale-vehicle.as_is.label',
    type: 'boolean',
    required: true,
    tooltip: 'documents.us.bill-of-sale-vehicle.as_is.tooltip',
  },
  {
    id: 'warranty_text',
    label: 'documents.us.bill-of-sale-vehicle.warranty_text.label',
    type: 'textarea',
    placeholder: 'e.g., 30-day warranty on drivetrain (if applicable)',
    tooltip: 'documents.us.bill-of-sale-vehicle.warranty_text.tooltip',
  },
  {
    id: 'state',
    label: 'documents.us.bill-of-sale-vehicle.state.label',
    type: 'select',
    required: true,
    options: usStates.map((s) => ({ value: s.value, label: s.label })),
    tooltip: 'documents.us.bill-of-sale-vehicle.state.tooltip',
  },
  {
    id: 'county',
    label: 'documents.us.bill-of-sale-vehicle.county.label',
    type: 'text',
    required: false,
    tooltip: 'documents.us.bill-of-sale-vehicle.county.tooltip',
  },
];

