// src/lib/documents/us/government-contract-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const governmentContractAgreementQuestions: FormQuestion[] = [
  {
    id: 'agencyName',
    type: 'text',
    label: 'Government Agency Name',
    placeholder: 'Enter government agency name',
    required: true,
    group: 'agency',
  },
  {
    id: 'contractingOfficer',
    type: 'text',
    label: 'Contracting Officer',
    placeholder: 'Enter contracting officer name',
    required: false,
    group: 'agency',
  },
  {
    id: 'agencyLevel',
    type: 'select',
    label: 'Agency Level',
    options: [
      { value: 'federal', label: 'Federal' },
      { value: 'state', label: 'State' },
      { value: 'county', label: 'County' },
      { value: 'municipal', label: 'Municipal' },
    ],
    required: false,
    group: 'agency',
  },
  {
    id: 'contractorName',
    type: 'text',
    label: 'Contractor Name',
    placeholder: 'Enter contractor company name',
    required: true,
    group: 'contractor',
  },
  {
    id: 'dunsBradstreetNumber',
    type: 'text',
    label: 'DUNS Number',
    placeholder: 'Enter DUNS Bradstreet number',
    required: false,
    group: 'contractor',
  },
  {
    id: 'cageCode',
    type: 'text',
    label: 'CAGE Code',
    placeholder: 'Enter Commercial and Government Entity code',
    required: false,
    group: 'contractor',
  },
  {
    id: 'contractType',
    type: 'select',
    label: 'Contract Type',
    options: [
      { value: 'fixed-price', label: 'Fixed Price' },
      { value: 'cost-reimbursement', label: 'Cost Reimbursement' },
      { value: 'time-materials', label: 'Time & Materials' },
      { value: 'indefinite-delivery', label: 'Indefinite Delivery' },
    ],
    required: false,
    group: 'contract',
  },
  {
    id: 'contractValue',
    type: 'text',
    label: 'Contract Value',
    placeholder: 'Enter total contract value',
    required: false,
    group: 'contract',
  },
  {
    id: 'performancePeriod',
    type: 'text',
    label: 'Performance Period',
    placeholder: 'Enter contract performance period',
    required: false,
    group: 'contract',
  },
  {
    id: 'procurementMethod',
    type: 'select',
    label: 'Procurement Method',
    options: [
      { value: 'sealed-bid', label: 'Sealed Bid' },
      { value: 'competitive-proposal', label: 'Competitive Proposal' },
      { value: 'sole-source', label: 'Sole Source' },
      { value: 'small-business-set-aside', label: 'Small Business Set-Aside' },
    ],
    required: false,
    group: 'procurement',
  },
  {
    id: 'naicsCode',
    type: 'text',
    label: 'NAICS Code',
    placeholder: 'Enter North American Industry Classification code',
    required: false,
    group: 'procurement',
  },
  {
    id: 'smallBusiness',
    type: 'boolean',
    label: 'Small Business?',
    required: false,
    group: 'certifications',
  },
  {
    id: 'womanOwned',
    type: 'boolean',
    label: 'Woman-Owned Business?',
    required: false,
    group: 'certifications',
  },
  {
    id: 'veteranOwned',
    type: 'boolean',
    label: 'Veteran-Owned Business?',
    required: false,
    group: 'certifications',
  },
  {
    id: 'hubzoneEligible',
    type: 'boolean',
    label: 'HUBZone Eligible?',
    required: false,
    group: 'certifications',
  },
  {
    id: 'workDescription',
    type: 'textarea',
    label: 'Work Description',
    placeholder: 'Describe the work to be performed',
    required: false,
    group: 'scope',
  },
  {
    id: 'deliverables',
    type: 'textarea',
    label: 'Deliverables',
    placeholder: 'List contract deliverables',
    required: false,
    group: 'scope',
  },
  {
    id: 'farCompliance',
    type: 'boolean',
    label: 'FAR Compliance Required?',
    required: false,
    group: 'compliance',
  },
  {
    id: 'dfarCompliance',
    type: 'boolean',
    label: 'DFAR Compliance Required?',
    required: false,
    group: 'compliance',
  },
  {
    id: 'securityClearance',
    type: 'boolean',
    label: 'Security Clearance Required?',
    required: false,
    group: 'security',
  },
  {
    id: 'clearanceLevel',
    type: 'select',
    label: 'Clearance Level',
    options: [
      { value: 'none', label: 'None' },
      { value: 'confidential', label: 'Confidential' },
      { value: 'secret', label: 'Secret' },
      { value: 'top-secret', label: 'Top Secret' },
    ],
    required: false,
    group: 'security',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'monthly', label: 'Monthly' },
      { value: 'milestone', label: 'Milestone-Based' },
      { value: 'completion', label: 'Upon Completion' },
      { value: 'progress', label: 'Progress Payments' },
    ],
    required: false,
    group: 'payment',
  },
  {
    id: 'paymentTerms',
    type: 'select',
    label: 'Payment Terms',
    options: [
      { value: 'net-30', label: 'Net 30 Days' },
      { value: 'net-45', label: 'Net 45 Days' },
      { value: 'net-60', label: 'Net 60 Days' },
    ],
    required: false,
    group: 'payment',
  },
  {
    id: 'subcontractingAllowed',
    type: 'boolean',
    label: 'Subcontracting Allowed?',
    required: false,
    group: 'subcontracting',
  },
  {
    id: 'performanceBond',
    type: 'boolean',
    label: 'Performance Bond Required?',
    required: false,
    group: 'bonding',
  },
  {
    id: 'paymentBond',
    type: 'boolean',
    label: 'Payment Bond Required?',
    required: false,
    group: 'bonding',
  },
  {
    id: 'dataRights',
    type: 'select',
    label: 'Data Rights',
    options: [
      { value: 'unlimited', label: 'Unlimited Rights' },
      { value: 'limited', label: 'Limited Rights' },
      { value: 'restricted', label: 'Restricted Rights' },
      { value: 'government-purpose', label: 'Government Purpose Rights' },
    ],
    required: false,
    group: 'intellectual-property',
  },
  {
    id: 'buyAmerican',
    type: 'boolean',
    label: 'Buy American Requirements?',
    required: false,
    group: 'trade',
  },
  {
    id: 'exportControlled',
    type: 'boolean',
    label: 'Export Controlled Technology?',
    required: false,
    group: 'export',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution',
    options: [
      { value: 'contracting-officer', label: 'Contracting Officer Decision' },
      { value: 'appeals-board', label: 'Board of Contract Appeals' },
      { value: 'court-claims', label: 'Court of Federal Claims' },
    ],
    required: false,
    group: 'disputes',
  },
  {
    id: 'terminationForConvenience',
    type: 'boolean',
    label: 'Termination for Convenience Clause?',
    required: false,
    group: 'termination',
  },
];
