import type { Question } from '@/types/documents';

export const questions: Question[] = [
  {
    id: 'companyName',
    type: 'text',
    label: 'Company Name',
    required: true,
    category: 'Company Information',
  },
  {
    id: 'planName',
    type: 'text',
    label: 'Plan Name',
    required: true,
    category: 'Plan Details',
    placeholder: 'e.g., 2024 Equity Incentive Plan',
  },
  {
    id: 'planType',
    type: 'select',
    label: 'Plan Type',
    required: true,
    category: 'Plan Details',
    options: [
      'Stock Option Plan',
      'Restricted Stock Plan',
      'ESPP',
      'Combined Plan',
    ],
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Plan Effective Date',
    required: true,
    category: 'Plan Details',
  },
  {
    id: 'planTerm',
    type: 'text',
    label: 'Plan Term',
    required: true,
    category: 'Plan Details',
    placeholder: 'e.g., 10 years from effective date',
  },
  {
    id: 'totalSharesAuthorized',
    type: 'text',
    label: 'Total Shares Authorized',
    required: true,
    category: 'Share Authorization',
    placeholder: 'Number of shares reserved for the plan',
  },
  {
    id: 'shareClass',
    type: 'text',
    label: 'Share Class',
    required: true,
    category: 'Share Authorization',
    placeholder: 'e.g., Common Stock, Class A Common Stock',
  },
  {
    id: 'eligibleParticipants',
    type: 'textarea',
    label: 'Eligible Participants',
    required: true,
    category: 'Eligibility',
    placeholder: 'Define who can participate in the plan',
  },
  {
    id: 'employmentRequirement',
    type: 'text',
    label: 'Employment Requirement',
    required: true,
    category: 'Eligibility',
    placeholder: 'e.g., Must be actively employed',
  },
  {
    id: 'pricingMethod',
    type: 'select',
    label: 'Option Pricing Method',
    required: false,
    category: 'Stock Options',
    options: ['Fair Market Value', 'Board Determined', 'Formula Based'],
  },
  {
    id: 'vestingSchedule',
    type: 'text',
    label: 'Vesting Schedule',
    required: true,
    category: 'Stock Options',
    placeholder: 'e.g., 25% per year over 4 years',
  },
  {
    id: 'vestingCliff',
    type: 'text',
    label: 'Vesting Cliff (Optional)',
    required: false,
    category: 'Stock Options',
    placeholder: 'e.g., 12 months',
  },
  {
    id: 'exercisePeriod',
    type: 'text',
    label: 'Exercise Period',
    required: true,
    category: 'Exercise Terms',
    placeholder: 'e.g., 10 years from grant date',
  },
  {
    id: 'exerciseMethod',
    type: 'text',
    label: 'Exercise Method',
    required: true,
    category: 'Exercise Terms',
    placeholder: 'e.g., Cash payment, cashless exercise',
  },
  {
    id: 'restrictedStockGrants',
    type: 'radio',
    label: 'Include Restricted Stock Grants?',
    required: true,
    category: 'Restricted Stock',
    options: ['Yes', 'No'],
  },
  {
    id: 'restrictionPeriod',
    type: 'text',
    label: 'Restriction Period (if applicable)',
    required: false,
    category: 'Restricted Stock',
    condition: { field: 'restrictedStockGrants', value: 'Yes' },
    placeholder: 'e.g., 3 years from grant date',
  },
  {
    id: 'planAdministrator',
    type: 'text',
    label: 'Plan Administrator',
    required: true,
    category: 'Plan Administration',
    placeholder: 'e.g., Board of Directors, Compensation Committee',
  },
  {
    id: 'boardAuthority',
    type: 'textarea',
    label: 'Board Authority',
    required: true,
    category: 'Plan Administration',
    placeholder: "Describe the board's authority over the plan",
  },
  {
    id: 'terminationProvisions',
    type: 'textarea',
    label: 'Termination Provisions',
    required: true,
    category: 'Termination Events',
    placeholder: 'What happens to grants upon termination?',
  },
  {
    id: 'changeInControlProvisions',
    type: 'textarea',
    label: 'Change in Control Provisions',
    required: true,
    category: 'Termination Events',
    placeholder: 'What happens during a change in control?',
  },
  {
    id: 'taxTreatment',
    type: 'textarea',
    label: 'Tax Treatment',
    required: true,
    category: 'Tax Implications',
    placeholder: 'Describe tax implications for participants',
  },
  {
    id: 'section409aCompliance',
    type: 'radio',
    label: 'Section 409A Compliance Required?',
    required: true,
    category: 'Tax Implications',
    options: ['Yes', 'No'],
  },
  {
    id: 'amendmentRights',
    type: 'textarea',
    label: 'Amendment Rights',
    required: true,
    category: 'Amendment and Termination',
    placeholder: 'Who can amend the plan and under what conditions?',
  },
  {
    id: 'planTermination',
    type: 'textarea',
    label: 'Plan Termination Provisions',
    required: true,
    category: 'Amendment and Termination',
    placeholder: 'Under what conditions can the plan be terminated?',
  },
  {
    id: 'governingState',
    type: 'select',
    label: 'Governing State',
    required: true,
    category: 'Legal Terms',
    options: [
      'Alabama',
      'Alaska',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'Florida',
      'Georgia',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'New York',
      'North Carolina',
      'North Dakota',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Pennsylvania',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Vermont',
      'Virginia',
      'Washington',
      'West Virginia',
      'Wisconsin',
      'Wyoming',
    ],
  },
  {
    id: 'signatureDate',
    type: 'date',
    label: 'Plan Adoption Date',
    required: true,
    category: 'Signatures',
  },
];
