// src/lib/documents/us/performance-bond/questions.ts
import type { FormQuestion } from '@/types/documents';

export const performanceBondQuestions: FormQuestion[] = [
  {
    id: 'principalName',
    type: 'text',
    label: 'Principal (Contractor) Name',
    placeholder: 'Enter contractor/principal name',
    required: true,
    group: 'principal',
  },
  {
    id: 'principalAddress',
    type: 'text',
    label: 'Principal Address',
    placeholder: 'Enter complete principal address',
    required: true,
    group: 'principal',
  },
  {
    id: 'principalPhone',
    type: 'text',
    label: 'Principal Phone',
    placeholder: 'Enter phone number',
    required: true,
    group: 'principal',
  },
  {
    id: 'obligeeName',
    type: 'text',
    label: 'Obligee (Project Owner) Name',
    placeholder: 'Enter project owner name',
    required: true,
    group: 'obligee',
  },
  {
    id: 'obligeeAddress',
    type: 'text',
    label: 'Obligee Address',
    placeholder: 'Enter complete obligee address',
    required: true,
    group: 'obligee',
  },
  {
    id: 'obligeePhone',
    type: 'text',
    label: 'Obligee Phone',
    placeholder: 'Enter phone number',
    required: true,
    group: 'obligee',
  },
  {
    id: 'suretyName',
    type: 'text',
    label: 'Surety Company Name',
    placeholder: 'Enter surety/bonding company name',
    required: true,
    group: 'surety',
  },
  {
    id: 'suretyAddress',
    type: 'text',
    label: 'Surety Address',
    placeholder: 'Enter complete surety address',
    required: true,
    group: 'surety',
  },
  {
    id: 'suretyLicense',
    type: 'text',
    label: 'Surety License/Authorization',
    placeholder: 'Enter surety license or authorization number',
    required: true,
    group: 'surety',
  },
  {
    id: 'contractDescription',
    type: 'textarea',
    label: 'Contract Description',
    placeholder: 'Detailed description of the contract work',
    required: true,
    group: 'contract',
  },
  {
    id: 'contractDate',
    type: 'date',
    label: 'Contract Date',
    required: true,
    group: 'contract',
  },
  {
    id: 'contractAmount',
    type: 'text',
    label: 'Contract Amount',
    placeholder: 'Total contract value',
    required: true,
    group: 'contract',
  },
  {
    id: 'projectLocation',
    type: 'text',
    label: 'Project Location',
    placeholder: 'Where the work will be performed',
    required: true,
    group: 'contract',
  },
  {
    id: 'bondAmount',
    type: 'text',
    label: 'Bond Amount',
    placeholder: 'Enter bond amount',
    required: true,
    group: 'bond',
  },
  {
    id: 'bondType',
    type: 'select',
    label: 'Bond Type',
    options: [
      { value: 'performance', label: 'Performance Bond' },
      {
        value: 'payment-and-performance',
        label: 'Payment and Performance Bond',
      },
      { value: 'completion', label: 'Completion Bond' },
      { value: 'maintenance', label: 'Maintenance Bond' },
    ],
    required: true,
    group: 'bond',
  },
  {
    id: 'bondEffectiveDate',
    type: 'date',
    label: 'Bond Effective Date',
    required: true,
    group: 'bond',
  },
  {
    id: 'bondExpirationDate',
    type: 'date',
    label: 'Bond Expiration Date',
    required: true,
    group: 'bond',
  },
  {
    id: 'performanceStandards',
    type: 'textarea',
    label: 'Performance Standards',
    placeholder: 'Specific performance requirements and standards',
    required: true,
    group: 'performance',
  },
  {
    id: 'completionDate',
    type: 'date',
    label: 'Project Completion Date',
    required: true,
    group: 'performance',
  },
  {
    id: 'qualityRequirements',
    type: 'textarea',
    label: 'Quality Requirements',
    placeholder: 'Specific quality standards and requirements',
    required: false,
    group: 'performance',
  },
  {
    id: 'premium',
    type: 'text',
    label: 'Bond Premium',
    placeholder: 'Premium amount or percentage',
    required: false,
    group: 'financial',
  },
  {
    id: 'maintenancePeriod',
    type: 'checkbox',
    label: 'Include maintenance period',
    required: false,
    group: 'maintenance',
  },
  {
    id: 'maintenanceDuration',
    type: 'text',
    label: 'Maintenance Period Duration',
    placeholder: 'e.g., 1 year, 2 years',
    required: false,
    group: 'maintenance',
    dependsOn: 'maintenancePeriod',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'litigation', label: 'Court Litigation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'mediation', label: 'Mediation' },
    ],
    required: true,
    group: 'legal',
  },
];
