// src/lib/documents/us/bid-proposal/questions.ts
import type { FormQuestion } from '@/types/documents';

export const bidproposalQuestions: FormQuestion[] = [
  {
    id: 'bidderName',
    type: 'text',
    label: 'Bidder/Contractor Name',
    placeholder: 'Enter contractor or company name',
    required: true,
    group: 'bidder',
  },
  {
    id: 'bidderAddress',
    type: 'text',
    label: 'Bidder Address',
    placeholder: 'Enter complete business address',
    required: true,
    group: 'bidder',
  },
  {
    id: 'bidderPhone',
    type: 'text',
    label: 'Bidder Phone',
    placeholder: 'Enter phone number',
    required: true,
    group: 'bidder',
  },
  {
    id: 'bidderEmail',
    type: 'email',
    label: 'Bidder Email',
    placeholder: 'Enter email address',
    required: false,
    group: 'bidder',
  },
  {
    id: 'bidderLicense',
    type: 'text',
    label: 'Contractor License Number',
    placeholder: 'Enter license number',
    required: true,
    group: 'bidder',
  },
  {
    id: 'bidderBond',
    type: 'text',
    label: 'Bond Number',
    placeholder: 'Enter bond number if applicable',
    required: false,
    group: 'bidder',
  },
  {
    id: 'ownerName',
    type: 'text',
    label: 'Owner/Client Name',
    placeholder: 'Enter property owner name',
    required: true,
    group: 'owner',
  },
  {
    id: 'ownerAddress',
    type: 'text',
    label: 'Owner Address',
    placeholder: 'Enter owner address',
    required: true,
    group: 'owner',
  },
  {
    id: 'ownerPhone',
    type: 'text',
    label: 'Owner Phone',
    placeholder: 'Enter phone number',
    required: false,
    group: 'owner',
  },
  {
    id: 'ownerEmail',
    type: 'email',
    label: 'Owner Email',
    placeholder: 'Enter email address',
    required: false,
    group: 'owner',
  },
  {
    id: 'projectName',
    type: 'text',
    label: 'Project Name',
    placeholder: 'Enter project name or title',
    required: true,
    group: 'project',
  },
  {
    id: 'projectAddress',
    type: 'text',
    label: 'Project Address',
    placeholder: 'Where work will be performed',
    required: true,
    group: 'project',
  },
  {
    id: 'projectDescription',
    type: 'textarea',
    label: 'Project Description',
    placeholder: 'Detailed description of the project',
    required: true,
    group: 'project',
  },
  {
    id: 'projectType',
    type: 'select',
    label: 'Project Type',
    options: [
      { value: 'residential', label: 'Residential' },
      { value: 'commercial', label: 'Commercial' },
      { value: 'industrial', label: 'Industrial' },
      { value: 'renovation', label: 'Renovation' },
      { value: 'addition', label: 'Addition' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'project',
  },
  {
    id: 'bidDate',
    type: 'date',
    label: 'Bid Date',
    required: true,
    group: 'bid',
  },
  {
    id: 'bidNumber',
    type: 'text',
    label: 'Bid Number',
    placeholder: 'Bid reference number',
    required: false,
    group: 'bid',
  },
  {
    id: 'bidOpeningDate',
    type: 'date',
    label: 'Bid Opening Date',
    required: false,
    group: 'bid',
  },
  {
    id: 'bidValidityPeriod',
    type: 'text',
    label: 'Bid Validity Period',
    placeholder: 'e.g., 30 days, 60 days',
    required: false,
    group: 'bid',
  },
  {
    id: 'workScope',
    type: 'textarea',
    label: 'Scope of Work',
    placeholder: 'Detailed description of work to be performed',
    required: true,
    group: 'scope',
  },
  {
    id: 'pricingType',
    type: 'select',
    label: 'Pricing Type',
    options: [
      { value: 'lump-sum', label: 'Lump Sum' },
      { value: 'unit-price', label: 'Unit Price' },
      { value: 'cost-plus', label: 'Cost Plus' },
      { value: 'time-and-materials', label: 'Time and Materials' },
    ],
    required: true,
    group: 'pricing',
  },
  {
    id: 'baseBidAmount',
    type: 'text',
    label: 'Base Bid Amount',
    placeholder: 'Total bid amount',
    required: true,
    group: 'pricing',
  },
  {
    id: 'materialsCost',
    type: 'text',
    label: 'Materials Cost',
    placeholder: 'Estimated materials cost',
    required: false,
    group: 'cost-breakdown',
  },
  {
    id: 'laborCost',
    type: 'text',
    label: 'Labor Cost',
    placeholder: 'Estimated labor cost',
    required: false,
    group: 'cost-breakdown',
  },
  {
    id: 'equipmentCost',
    type: 'text',
    label: 'Equipment Cost',
    placeholder: 'Equipment rental/usage cost',
    required: false,
    group: 'cost-breakdown',
  },
  {
    id: 'subcontractorCost',
    type: 'text',
    label: 'Subcontractor Cost',
    placeholder: 'Subcontractor costs',
    required: false,
    group: 'cost-breakdown',
  },
  {
    id: 'projectDuration',
    type: 'text',
    label: 'Project Duration',
    placeholder: 'e.g., 6 months, 120 days',
    required: false,
    group: 'schedule',
  },
  {
    id: 'startDate',
    type: 'date',
    label: 'Proposed Start Date',
    required: false,
    group: 'schedule',
  },
  {
    id: 'completionDate',
    type: 'date',
    label: 'Proposed Completion Date',
    required: false,
    group: 'schedule',
  },
  {
    id: 'paymentTerms',
    type: 'textarea',
    label: 'Payment Terms',
    placeholder: 'Payment terms and conditions',
    required: false,
    group: 'terms',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'monthly-progress', label: 'Monthly Progress Payments' },
      { value: 'milestone-based', label: 'Milestone-Based Payments' },
      { value: 'percentage-completion', label: 'Percentage of Completion' },
      { value: 'net-30', label: 'Net 30 Days' },
    ],
    required: false,
    group: 'terms',
  },
  {
    id: 'retainagePercentage',
    type: 'text',
    label: 'Retainage Percentage',
    placeholder: 'e.g., 10%',
    required: false,
    group: 'terms',
  },
  {
    id: 'performanceBondRequired',
    type: 'checkbox',
    label: 'Performance bond required',
    required: false,
    group: 'bonds',
  },
  {
    id: 'performanceBondAmount',
    type: 'text',
    label: 'Performance Bond Amount',
    placeholder: 'Bond amount or percentage',
    required: false,
    group: 'bonds',
    dependsOn: 'performanceBondRequired',
  },
  {
    id: 'paymentBondRequired',
    type: 'checkbox',
    label: 'Payment bond required',
    required: false,
    group: 'bonds',
  },
  {
    id: 'paymentBondAmount',
    type: 'text',
    label: 'Payment Bond Amount',
    placeholder: 'Bond amount or percentage',
    required: false,
    group: 'bonds',
    dependsOn: 'paymentBondRequired',
  },
  {
    id: 'generalLiabilityInsurance',
    type: 'text',
    label: 'General Liability Insurance',
    placeholder: 'Insurance coverage amount',
    required: false,
    group: 'insurance',
  },
  {
    id: 'workersCompensationInsurance',
    type: 'checkbox',
    label: 'Workers compensation insurance provided',
    required: false,
    group: 'insurance',
  },
  {
    id: 'builderRiskInsurance',
    type: 'checkbox',
    label: "Builder's risk insurance provided",
    required: false,
    group: 'insurance',
  },
  {
    id: 'yearsInBusiness',
    type: 'text',
    label: 'Years in Business',
    placeholder: 'Number of years in business',
    required: false,
    group: 'qualifications',
  },
  {
    id: 'similarProjectsCompleted',
    type: 'text',
    label: 'Similar Projects Completed',
    placeholder: 'Number of similar projects',
    required: false,
    group: 'qualifications',
  },
  {
    id: 'qualityStandards',
    type: 'textarea',
    label: 'Quality Standards',
    placeholder: 'Quality standards and certifications',
    required: false,
    group: 'specifications',
  },
  {
    id: 'permitResponsibility',
    type: 'select',
    label: 'Permit Responsibility',
    options: [
      { value: 'bidder', label: 'Bidder Responsible' },
      { value: 'owner', label: 'Owner Responsible' },
      { value: 'shared', label: 'Shared Responsibility' },
    ],
    required: false,
    group: 'permits',
  },
  {
    id: 'permitCosts',
    type: 'select',
    label: 'Permit Costs',
    options: [
      { value: 'included', label: 'Included in Bid' },
      { value: 'excluded', label: 'Excluded from Bid' },
      { value: 'reimbursable', label: 'Reimbursable' },
    ],
    required: false,
    group: 'permits',
  },
  {
    id: 'environmentalCompliance',
    type: 'checkbox',
    label: 'Environmental compliance included',
    required: false,
    group: 'environmental',
  },
  {
    id: 'safetyPlan',
    type: 'checkbox',
    label: 'Safety plan included',
    required: false,
    group: 'environmental',
  },
  {
    id: 'hazardousMaterials',
    type: 'checkbox',
    label: 'Hazardous materials handling included',
    required: false,
    group: 'environmental',
  },
  {
    id: 'workmanshipWarranty',
    type: 'text',
    label: 'Workmanship Warranty',
    placeholder: 'e.g., 1 year, 2 years',
    required: false,
    group: 'warranties',
  },
  {
    id: 'materialWarranties',
    type: 'checkbox',
    label: 'Material warranties transferred to owner',
    required: false,
    group: 'warranties',
  },
  {
    id: 'equipmentWarranties',
    type: 'checkbox',
    label: 'Equipment warranties transferred to owner',
    required: false,
    group: 'warranties',
  },
  {
    id: 'subcontractorsListed',
    type: 'checkbox',
    label: 'Major subcontractors listed',
    required: false,
    group: 'subcontractors',
  },
  {
    id: 'weatherConsiderations',
    type: 'checkbox',
    label: 'Weather delays considered',
    required: false,
    group: 'risk',
  },
  {
    id: 'siteConditions',
    type: 'textarea',
    label: 'Site Conditions',
    placeholder: 'Known site conditions and assumptions',
    required: false,
    group: 'risk',
  },
  {
    id: 'proposalValidityPeriod',
    type: 'text',
    label: 'Proposal Validity Period',
    placeholder: 'e.g., 30 days from bid date',
    required: false,
    group: 'acceptance',
  },
  {
    id: 'acceptanceTerms',
    type: 'textarea',
    label: 'Acceptance Terms',
    placeholder: 'Terms for proposal acceptance',
    required: false,
    group: 'acceptance',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution',
    options: [
      { value: 'negotiation', label: 'Negotiation' },
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'litigation', label: 'Litigation' },
    ],
    required: false,
    group: 'legal',
  },
  {
    id: 'limitationOfLiability',
    type: 'checkbox',
    label: 'Include limitation of liability clause',
    required: false,
    group: 'legal',
  },
  {
    id: 'requireBidderSignature',
    type: 'checkbox',
    label: 'Require bidder signature',
    required: false,
    group: 'signatures',
  },
];
