// src/lib/documents/us/employment-verification-letter/questions.ts
import type { FormQuestion } from '@/types/documents';

export const employmentVerificationLetterQuestions: FormQuestion[] = [
  {
    id: 'companyName',
    type: 'text',
    label: 'Company Name',
    placeholder: 'Enter company name',
    required: true,
    group: 'company',
  },
  {
    id: 'companyAddress',
    type: 'text',
    label: 'Company Address',
    placeholder: 'Enter complete company address',
    required: true,
    group: 'company',
  },
  {
    id: 'companyPhone',
    type: 'text',
    label: 'Company Phone Number',
    placeholder: 'Enter company phone number',
    required: false,
    group: 'company',
  },
  {
    id: 'signerName',
    type: 'text',
    label: 'Letter Signer Name',
    placeholder: 'Enter name of person signing letter',
    required: true,
    group: 'signer',
  },
  {
    id: 'signerTitle',
    type: 'text',
    label: 'Signer Title',
    placeholder: 'e.g., HR Manager, Director',
    required: true,
    group: 'signer',
  },
  {
    id: 'signerEmail',
    type: 'email',
    label: 'Signer Email',
    placeholder: 'Enter signer email address',
    required: false,
    group: 'signer',
  },
  {
    id: 'employeeName',
    type: 'text',
    label: 'Employee Name',
    placeholder: 'Enter employee full name',
    required: true,
    group: 'employee',
  },
  {
    id: 'employeeTitle',
    type: 'text',
    label: 'Employee Job Title',
    placeholder: 'Enter employee job title',
    required: true,
    group: 'employee',
  },
  {
    id: 'department',
    type: 'text',
    label: 'Department',
    placeholder: 'Enter department name',
    required: false,
    group: 'employee',
  },
  {
    id: 'employeeId',
    type: 'text',
    label: 'Employee ID',
    placeholder: 'Enter employee ID number',
    required: false,
    group: 'employee',
  },
  {
    id: 'startDate',
    type: 'date',
    label: 'Employment Start Date',
    required: true,
    group: 'employment',
  },
  {
    id: 'employmentStatus',
    type: 'select',
    label: 'Employment Status',
    options: [
      { value: 'active', label: 'Active' },
      { value: 'inactive', label: 'Inactive' },
      { value: 'terminated', label: 'Terminated' },
    ],
    required: true,
    group: 'employment',
  },
  {
    id: 'employmentType',
    type: 'select',
    label: 'Employment Type',
    options: [
      { value: 'full-time', label: 'Full-time' },
      { value: 'part-time', label: 'Part-time' },
      { value: 'contract', label: 'Contract' },
      { value: 'temporary', label: 'Temporary' },
    ],
    required: true,
    group: 'employment',
  },
  {
    id: 'includeSalary',
    type: 'checkbox',
    label: 'Include salary information',
    required: false,
    group: 'salary',
  },
  {
    id: 'salaryAmount',
    type: 'text',
    label: 'Salary Amount',
    placeholder: 'Enter salary amount',
    required: false,
    group: 'salary',
    dependsOn: 'includeSalary',
  },
  {
    id: 'salaryFrequency',
    type: 'select',
    label: 'Salary Frequency',
    options: [
      { value: 'hourly', label: 'Hourly' },
      { value: 'weekly', label: 'Weekly' },
      { value: 'bi-weekly', label: 'Bi-weekly' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'annually', label: 'Annually' },
    ],
    required: false,
    group: 'salary',
    dependsOn: 'includeSalary',
  },
  {
    id: 'includeSchedule',
    type: 'checkbox',
    label: 'Include work schedule information',
    required: false,
    group: 'schedule',
  },
  {
    id: 'hoursPerWeek',
    type: 'text',
    label: 'Hours Per Week',
    placeholder: 'e.g., 40 hours',
    required: false,
    group: 'schedule',
    dependsOn: 'includeSchedule',
  },
  {
    id: 'workSchedule',
    type: 'text',
    label: 'Work Schedule',
    placeholder: 'e.g., Monday-Friday, 9 AM - 5 PM',
    required: false,
    group: 'schedule',
    dependsOn: 'includeSchedule',
  },
  {
    id: 'includePerformance',
    type: 'checkbox',
    label: 'Include performance note',
    required: false,
    group: 'additional',
  },
  {
    id: 'performanceNote',
    type: 'textarea',
    label: 'Performance Note',
    placeholder: 'Brief note about employee performance',
    required: false,
    group: 'additional',
    dependsOn: 'includePerformance',
  },
  {
    id: 'includeEligibility',
    type: 'checkbox',
    label: 'Include rehire eligibility',
    required: false,
    group: 'additional',
  },
  {
    id: 'rehireEligible',
    type: 'select',
    label: 'Rehire Eligible',
    options: [
      { value: true, label: 'Yes' },
      { value: false, label: 'No' },
    ],
    required: false,
    group: 'additional',
    dependsOn: 'includeEligibility',
  },
  {
    id: 'verificationPurpose',
    type: 'text',
    label: 'Purpose of Verification',
    placeholder: 'e.g., Loan application, Background check',
    required: false,
    group: 'purpose',
  },
  {
    id: 'requestedBy',
    type: 'text',
    label: 'Requested By',
    placeholder: 'Name or organization requesting verification',
    required: false,
    group: 'purpose',
  },
  {
    id: 'letterDate',
    type: 'date',
    label: 'Letter Date',
    required: true,
    group: 'basic',
  },
  {
    id: 'includeContactInfo',
    type: 'checkbox',
    label: 'Include contact information for verification',
    required: false,
    group: 'contact',
  },
  {
    id: 'contactName',
    type: 'text',
    label: 'Contact Name',
    placeholder: 'Name for follow-up questions',
    required: false,
    group: 'contact',
    dependsOn: 'includeContactInfo',
  },
  {
    id: 'contactPhone',
    type: 'text',
    label: 'Contact Phone',
    placeholder: 'Phone number for verification',
    required: false,
    group: 'contact',
    dependsOn: 'includeContactInfo',
  },
  {
    id: 'contactEmail',
    type: 'email',
    label: 'Contact Email',
    placeholder: 'Email for verification inquiries',
    required: false,
    group: 'contact',
    dependsOn: 'includeContactInfo',
  },
];
