// src/lib/documents/us/affidavit-of-heirship/questions.ts
import type { Question } from '@/types/documents';

export const questions: Question[] = [
  // Section 1: Deceased Person Information
  {
    id: 'decedentName',
    type: 'text',
    label: "Deceased Person's Full Legal Name",
    required: true,
    section: 'Deceased Person Information',
    placeholder: "Enter the deceased person's full legal name",
  },
  {
    id: 'decedentDateOfDeath',
    type: 'date',
    label: 'Date of Death',
    required: true,
    section: 'Deceased Person Information',
  },
  {
    id: 'decedentDateOfBirth',
    type: 'date',
    label: 'Date of Birth',
    required: true,
    section: 'Deceased Person Information',
  },
  {
    id: 'decedentAddress',
    type: 'text',
    label: "Deceased Person's Last Known Address",
    required: true,
    section: 'Deceased Person Information',
    placeholder: "Enter the deceased person's street address",
  },
  {
    id: 'decedentCity',
    type: 'text',
    label: 'City',
    required: true,
    section: 'Deceased Person Information',
    placeholder: "Enter the deceased person's city",
  },
  {
    id: 'decedentState',
    type: 'select',
    label: 'State',
    required: true,
    section: 'Deceased Person Information',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
  },
  {
    id: 'decedentZip',
    type: 'text',
    label: 'ZIP Code',
    required: true,
    section: 'Deceased Person Information',
    placeholder: "Enter the deceased person's ZIP code",
  },
  {
    id: 'decedentSSN',
    type: 'text',
    label: "Deceased Person's Social Security Number",
    required: true,
    section: 'Deceased Person Information',
    placeholder: 'XXX-XX-XXXX',
    description: 'This information is required for heir identification.',
  },

  // Section 2: Affiant Information
  {
    id: 'affiantName',
    type: 'text',
    label: 'Your Full Legal Name',
    required: true,
    section: 'Affiant Information',
    placeholder: 'Enter your full legal name',
    description: 'You are the person making this affidavit.',
  },
  {
    id: 'affiantAddress',
    type: 'text',
    label: 'Your Street Address',
    required: true,
    section: 'Affiant Information',
    placeholder: 'Enter your street address',
  },
  {
    id: 'affiantCity',
    type: 'text',
    label: 'Your City',
    required: true,
    section: 'Affiant Information',
    placeholder: 'Enter your city',
  },
  {
    id: 'affiantState',
    type: 'select',
    label: 'Your State',
    required: true,
    section: 'Affiant Information',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
  },
  {
    id: 'affiantZip',
    type: 'text',
    label: 'Your ZIP Code',
    required: true,
    section: 'Affiant Information',
    placeholder: 'Enter your ZIP code',
  },
  {
    id: 'affiantPhone',
    type: 'text',
    label: 'Your Phone Number',
    required: true,
    section: 'Affiant Information',
    placeholder: 'Enter your phone number',
  },
  {
    id: 'affiantRelationship',
    type: 'text',
    label: 'Your Relationship to the Deceased',
    required: true,
    section: 'Affiant Information',
    placeholder: 'e.g., Spouse, Child, Sibling, Friend, Neighbor',
  },
  {
    id: 'yearsKnownDecedent',
    type: 'text',
    label: 'How many years did you know the deceased?',
    required: true,
    section: 'Affiant Information',
    placeholder: 'e.g., 25 years',
  },
  {
    id: 'relationshipDuration',
    type: 'text',
    label: 'Duration and nature of your relationship',
    required: true,
    section: 'Affiant Information',
    placeholder:
      'e.g., Close family friend for 25 years, neighbor for 10 years',
  },

  // Section 3: Marital Status
  {
    id: 'decedentMaritalStatus',
    type: 'radio',
    label: "Deceased Person's Marital Status at Time of Death",
    required: true,
    section: 'Family Information',
    options: [
      { value: 'single', label: 'Single (never married)' },
      { value: 'married', label: 'Married' },
      { value: 'divorced', label: 'Divorced' },
      { value: 'widowed', label: 'Widowed' },
    ],
  },

  // Section 4: Spouse Information
  {
    id: 'spouseName',
    type: 'text',
    label: "Spouse's Full Name",
    required: false,
    section: 'Spouse Information',
    placeholder: "Enter spouse's full name",
    condition: {
      field: 'decedentMaritalStatus',
      value: ['married', 'widowed'],
    },
  },
  {
    id: 'spouseStillLiving',
    type: 'radio',
    label: 'Is the spouse still living?',
    required: false,
    section: 'Spouse Information',
    options: [
      { value: 'true', label: 'Yes, spouse is still living' },
      { value: 'false', label: 'No, spouse is deceased' },
    ],
    condition: {
      field: 'decedentMaritalStatus',
      value: ['married', 'widowed'],
    },
  },
  {
    id: 'spouseDateOfDeath',
    type: 'date',
    label: "Spouse's Date of Death",
    required: false,
    section: 'Spouse Information',
    condition: { field: 'spouseStillLiving', value: 'false' },
  },
  {
    id: 'marriageDate',
    type: 'date',
    label: 'Date of Marriage',
    required: false,
    section: 'Spouse Information',
    condition: {
      field: 'decedentMaritalStatus',
      value: ['married', 'widowed'],
    },
  },
  {
    id: 'marriagePlace',
    type: 'text',
    label: 'Place of Marriage',
    required: false,
    section: 'Spouse Information',
    placeholder: 'City, State',
    condition: {
      field: 'decedentMaritalStatus',
      value: ['married', 'widowed'],
    },
  },

  // Section 5: Children Information
  {
    id: 'hasChildren',
    type: 'radio',
    label: 'Did the deceased have any children?',
    required: true,
    section: 'Children',
    options: [
      { value: 'true', label: 'Yes, the deceased had children' },
      { value: 'false', label: 'No, the deceased had no children' },
    ],
  },
  {
    id: 'children',
    type: 'array',
    label: 'Children Information',
    required: false,
    section: 'Children',
    condition: { field: 'hasChildren', value: 'true' },
    description:
      'List all children of the deceased, including adopted children.',
    arrayConfig: {
      minItems: 1,
      maxItems: 20,
      fields: [
        {
          id: 'name',
          type: 'text',
          label: 'Full Name',
          required: true,
          placeholder: 'Enter child full name',
        },
        {
          id: 'dateOfBirth',
          type: 'date',
          label: 'Date of Birth',
          required: true,
        },
        {
          id: 'isLiving',
          type: 'radio',
          label: 'Living Status',
          required: true,
          options: [
            { value: 'true', label: 'Living' },
            { value: 'false', label: 'Deceased' },
          ],
        },
        {
          id: 'dateOfDeath',
          type: 'date',
          label: 'Date of Death',
          required: false,
          condition: { field: 'isLiving', value: 'false' },
        },
        {
          id: 'address',
          type: 'text',
          label: 'Current Address',
          required: false,
          placeholder: 'Enter current address if living',
          condition: { field: 'isLiving', value: 'true' },
        },
      ],
    },
  },

  // Section 6: Parents Information
  {
    id: 'fatherName',
    type: 'text',
    label: "Deceased's Father's Name",
    required: false,
    section: 'Parents Information',
    placeholder: "Enter father's full name (if known)",
  },
  {
    id: 'fatherIsLiving',
    type: 'radio',
    label: 'Is the father still living?',
    required: false,
    section: 'Parents Information',
    options: [
      { value: 'true', label: 'Yes, father is still living' },
      { value: 'false', label: 'No, father is deceased' },
    ],
    condition: { field: 'fatherName', value: '!empty' },
  },
  {
    id: 'fatherDateOfDeath',
    type: 'date',
    label: "Father's Date of Death",
    required: false,
    section: 'Parents Information',
    condition: { field: 'fatherIsLiving', value: 'false' },
  },
  {
    id: 'motherName',
    type: 'text',
    label: "Deceased's Mother's Name",
    required: false,
    section: 'Parents Information',
    placeholder: "Enter mother's full name (if known)",
  },
  {
    id: 'motherIsLiving',
    type: 'radio',
    label: 'Is the mother still living?',
    required: false,
    section: 'Parents Information',
    options: [
      { value: 'true', label: 'Yes, mother is still living' },
      { value: 'false', label: 'No, mother is deceased' },
    ],
    condition: { field: 'motherName', value: '!empty' },
  },
  {
    id: 'motherDateOfDeath',
    type: 'date',
    label: "Mother's Date of Death",
    required: false,
    section: 'Parents Information',
    condition: { field: 'motherIsLiving', value: 'false' },
  },

  // Section 7: Siblings Information
  {
    id: 'hasSiblings',
    type: 'radio',
    label: 'Did the deceased have any siblings (brothers or sisters)?',
    required: true,
    section: 'Siblings',
    options: [
      { value: 'true', label: 'Yes, the deceased had siblings' },
      { value: 'false', label: 'No, the deceased had no siblings' },
    ],
  },
  {
    id: 'siblings',
    type: 'array',
    label: 'Siblings Information',
    required: false,
    section: 'Siblings',
    condition: { field: 'hasSiblings', value: 'true' },
    description: 'List all siblings of the deceased.',
    arrayConfig: {
      minItems: 1,
      maxItems: 20,
      fields: [
        {
          id: 'name',
          type: 'text',
          label: 'Full Name',
          required: true,
          placeholder: 'Enter sibling full name',
        },
        {
          id: 'dateOfBirth',
          type: 'date',
          label: 'Date of Birth',
          required: false,
        },
        {
          id: 'isLiving',
          type: 'radio',
          label: 'Living Status',
          required: true,
          options: [
            { value: 'true', label: 'Living' },
            { value: 'false', label: 'Deceased' },
          ],
        },
        {
          id: 'dateOfDeath',
          type: 'date',
          label: 'Date of Death',
          required: false,
          condition: { field: 'isLiving', value: 'false' },
        },
        {
          id: 'address',
          type: 'text',
          label: 'Current Address',
          required: false,
          placeholder: 'Enter current address if living',
          condition: { field: 'isLiving', value: 'true' },
        },
      ],
    },
  },

  // Section 8: Other Heirs
  {
    id: 'hasOtherHeirs',
    type: 'radio',
    label: 'Are there any other heirs (grandchildren, nieces, nephews, etc.)?',
    required: true,
    section: 'Other Heirs',
    options: [
      { value: 'true', label: 'Yes, there are other heirs' },
      { value: 'false', label: 'No, there are no other heirs' },
    ],
  },
  {
    id: 'otherHeirs',
    type: 'array',
    label: 'Other Heirs Information',
    required: false,
    section: 'Other Heirs',
    condition: { field: 'hasOtherHeirs', value: 'true' },
    description: 'List all other heirs of the deceased.',
    arrayConfig: {
      minItems: 1,
      maxItems: 20,
      fields: [
        {
          id: 'name',
          type: 'text',
          label: 'Full Name',
          required: true,
          placeholder: 'Enter heir full name',
        },
        {
          id: 'relationship',
          type: 'text',
          label: 'Relationship to Deceased',
          required: true,
          placeholder: 'e.g., Grandchild, Niece, Nephew',
        },
        {
          id: 'dateOfBirth',
          type: 'date',
          label: 'Date of Birth',
          required: false,
        },
        {
          id: 'isLiving',
          type: 'radio',
          label: 'Living Status',
          required: true,
          options: [
            { value: 'true', label: 'Living' },
            { value: 'false', label: 'Deceased' },
          ],
        },
        {
          id: 'dateOfDeath',
          type: 'date',
          label: 'Date of Death',
          required: false,
          condition: { field: 'isLiving', value: 'false' },
        },
        {
          id: 'address',
          type: 'text',
          label: 'Current Address',
          required: true,
          placeholder: 'Enter current address',
        },
      ],
    },
  },

  // Section 9: Estate Information
  {
    id: 'hasWill',
    type: 'radio',
    label: 'Did the deceased leave a will?',
    required: true,
    section: 'Estate Information',
    options: [
      { value: 'true', label: 'Yes, the deceased left a will' },
      {
        value: 'false',
        label: 'No, the deceased died without a will (intestate)',
      },
    ],
  },
  {
    id: 'willDescription',
    type: 'textarea',
    label: 'Description of Will',
    required: false,
    section: 'Estate Information',
    placeholder: 'Describe the will and its provisions...',
    condition: { field: 'hasWill', value: 'true' },
  },
  {
    id: 'hasProbateProceedings',
    type: 'radio',
    label: 'Are there any probate proceedings?',
    required: true,
    section: 'Estate Information',
    options: [
      { value: 'true', label: 'Yes, there are probate proceedings' },
      { value: 'false', label: 'No, there are no probate proceedings' },
    ],
  },
  {
    id: 'probateDescription',
    type: 'textarea',
    label: 'Description of Probate Proceedings',
    required: false,
    section: 'Estate Information',
    placeholder: 'Describe the probate proceedings...',
    condition: { field: 'hasProbateProceedings', value: 'true' },
  },

  // Section 10: Property Information
  {
    id: 'propertyDescription',
    type: 'textarea',
    label: 'Description of Property/Assets',
    required: true,
    section: 'Property Information',
    placeholder:
      'Describe the property or assets for which heirship is being established...',
    description:
      'Include detailed description of all property, real estate, or assets.',
  },
  {
    id: 'propertyAddress',
    type: 'text',
    label: 'Property Address',
    required: true,
    section: 'Property Information',
    placeholder: 'Enter the property street address',
  },
  {
    id: 'propertyCity',
    type: 'text',
    label: 'Property City',
    required: true,
    section: 'Property Information',
    placeholder: 'Enter the property city',
  },
  {
    id: 'propertyState',
    type: 'select',
    label: 'Property State',
    required: true,
    section: 'Property Information',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
  },
  {
    id: 'propertyZip',
    type: 'text',
    label: 'Property ZIP Code',
    required: true,
    section: 'Property Information',
    placeholder: 'Enter the property ZIP code',
  },
  {
    id: 'propertyValue',
    type: 'text',
    label: 'Estimated Property Value',
    required: true,
    section: 'Property Information',
    placeholder: 'e.g., $150,000',
  },

  // Section 11: Additional Information
  {
    id: 'additionalInformation',
    type: 'textarea',
    label: 'Additional Information',
    required: false,
    section: 'Additional Information',
    placeholder:
      'Provide any additional relevant information about the deceased or their family...',
    description:
      'Include any other relevant information that supports the heirship claims.',
  },

  // Section 12: Witnesses
  {
    id: 'witness1Name',
    type: 'text',
    label: 'First Witness Full Name',
    required: false,
    section: 'Witnesses',
    placeholder: 'Enter first witness full name',
    description:
      'Witnesses should be disinterested parties who knew the deceased.',
  },
  {
    id: 'witness1Address',
    type: 'text',
    label: 'First Witness Address',
    required: false,
    section: 'Witnesses',
    placeholder: 'Enter first witness address',
  },
  {
    id: 'witness2Name',
    type: 'text',
    label: 'Second Witness Full Name',
    required: false,
    section: 'Witnesses',
    placeholder: 'Enter second witness full name',
  },
  {
    id: 'witness2Address',
    type: 'text',
    label: 'Second Witness Address',
    required: false,
    section: 'Witnesses',
    placeholder: 'Enter second witness address',
  },

  // Section 13: Legal Information
  {
    id: 'state',
    type: 'select',
    label: 'State Where This Affidavit Will Be Used',
    required: true,
    section: 'Legal Information',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
    description:
      'Select the state where this affidavit of heirship will be filed.',
  },
  {
    id: 'county',
    type: 'text',
    label: 'County',
    required: true,
    section: 'Legal Information',
    placeholder: 'Enter the county name',
  },
  {
    id: 'dateCreated',
    type: 'date',
    label: 'Date of Creation',
    required: true,
    section: 'Legal Information',
    description: 'The date this affidavit is being created.',
  },

  // Section 14: Notarization
  {
    id: 'notaryName',
    type: 'text',
    label: 'Notary Public Name',
    required: false,
    section: 'Notarization',
    placeholder: 'Enter notary public name',
    description: 'This will be filled when the document is notarized.',
  },
  {
    id: 'notaryCommissionExpires',
    type: 'date',
    label: 'Notary Commission Expires',
    required: false,
    section: 'Notarization',
    description: 'This will be filled when the document is notarized.',
  },
];
