// src/lib/documents/us/livestock-purchase-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const livestockPurchaseAgreementQuestions: FormQuestion[] = [
  {
    id: 'sellerName',
    type: 'text',
    label: 'Seller Name',
    placeholder: 'Enter livestock seller name',
    required: true,
    group: 'seller',
  },
  {
    id: 'buyerName',
    type: 'text',
    label: 'Buyer Name',
    placeholder: 'Enter livestock buyer name',
    required: true,
    group: 'buyer',
  },
  {
    id: 'animalType',
    type: 'select',
    label: 'Animal Type',
    options: [
      { value: 'cattle', label: 'Cattle' },
      { value: 'horses', label: 'Horses' },
      { value: 'pigs', label: 'Pigs' },
      { value: 'sheep', label: 'Sheep' },
      { value: 'goats', label: 'Goats' },
      { value: 'chickens', label: 'Chickens' },
      { value: 'ducks', label: 'Ducks' },
      { value: 'turkeys', label: 'Turkeys' },
      { value: 'alpacas', label: 'Alpacas' },
      { value: 'llamas', label: 'Llamas' },
    ],
    required: false,
    group: 'livestock',
  },
  {
    id: 'animalBreed',
    type: 'text',
    label: 'Animal Breed',
    placeholder: 'Enter breed information',
    required: false,
    group: 'livestock',
  },
  {
    id: 'numberOfAnimals',
    type: 'text',
    label: 'Number of Animals',
    placeholder: 'Enter total count',
    required: false,
    group: 'livestock',
  },
  {
    id: 'animalWeight',
    type: 'text',
    label: 'Animal Weight',
    placeholder: 'Enter average or total weight',
    required: false,
    group: 'livestock',
  },
  {
    id: 'totalPurchasePrice',
    type: 'text',
    label: 'Total Purchase Price',
    placeholder: 'Enter total sale amount',
    required: false,
    group: 'purchase',
  },
  {
    id: 'pricePerHead',
    type: 'text',
    label: 'Price Per Head',
    placeholder: 'Enter price per animal',
    required: false,
    group: 'purchase',
  },
  {
    id: 'deliveryDate',
    type: 'text',
    label: 'Delivery Date',
    placeholder: 'Enter expected delivery date',
    required: false,
    group: 'delivery',
  },
  {
    id: 'deliveryMethod',
    type: 'select',
    label: 'Delivery Method',
    options: [
      { value: 'buyer-pickup', label: 'Buyer Pickup' },
      { value: 'seller-delivery', label: 'Seller Delivery' },
      { value: 'third-party', label: 'Third Party Transport' },
    ],
    required: false,
    group: 'delivery',
  },
  {
    id: 'healthCertificate',
    type: 'boolean',
    label: 'Health certificate required?',
    required: false,
    group: 'health',
  },
  {
    id: 'vaccinations',
    type: 'boolean',
    label: 'Current vaccinations required?',
    required: false,
    group: 'health',
  },
  {
    id: 'registrationPapers',
    type: 'boolean',
    label: 'Registration papers included?',
    required: false,
    group: 'documentation',
  },
  {
    id: 'healthWarranty',
    type: 'boolean',
    label: 'Health warranty provided?',
    required: false,
    group: 'warranties',
  },
  {
    id: 'predeliveryInspection',
    type: 'boolean',
    label: 'Pre-delivery inspection allowed?',
    required: false,
    group: 'inspection',
  },
];