// src/lib/documents/us/index.ts
// Auto-generated US documents index - connects all document folders

export { affidavit } from './affidavit';
export { affidavitGeneral } from './affidavit-general';
export { articlesOfIncorporation } from './articles-of-incorporation';
export { articlesOfIncorporationBiz } from './articles-of-incorporation-biz';
export { boatBillOfSale } from './boat-bill-of-sale';
export { businessContract } from './business-contract';
export { childCustodyAgreement } from './child-custody-agreement';
export { childMedicalConsent } from './child-medical-consent';
export { childSupportAgreementMeta as childSupportAgreement } from './child-support-agreement';
export { codicilToWill } from './codicil-to-will';
export { commissionAgreementMeta as commissionAgreement } from './commission-agreement';
export { commercialLeaseAgreement } from './commercial-lease-agreement';
export { consignmentAgreement } from './consignment-agreement';
export { constructionContractMeta as constructionContract } from './construction-contract';
export { consultingAgreement } from './consulting-agreement';
export { copyrightAssignment } from './copyright-assignment';
export { copyrightAssignmentAgreementMeta as copyrightAssignmentAgreement } from './copyright-assignment-agreement';
export { demandLetter } from './demand-letter';
export { demandLetterPayment } from './demand-letter-payment';
export { divorceSettlement } from './divorce-settlement';
export { divorceSettlementAgreement } from './divorce-settlement-agreement';
export { durablePowerOfAttorney } from './durable-power-of-attorney';
export { employeeEvaluationFormMeta as employeeEvaluationForm } from './employee-evaluation-form';
export { employeeHandbookMeta as employeeHandbook } from './employee-handbook';
export { employmentContract } from './employment-contract';
export { employmentOfferLetter } from './employment-offer-letter';
export { employmentTerminationLetter } from './employment-termination-letter';
export { employmentVerificationLetterMeta as employmentVerificationLetter } from './employment-verification-letter';
export { evictionNotice } from './eviction-notice';
export { generalInquiry } from './general-inquiry';
export { healthcarePowerOfAttorney } from './healthcare-power-of-attorney';
export { homeImprovementContractMeta as homeImprovementContract } from './home-improvement-contract';
export { independentContractorAgreement } from './independent-contractor-agreement';
export { invoice } from './invoice';
export { jobApplicationFormMeta as jobApplicationForm } from './job-application-form';
export { lastWillTestament } from './last-will-testament';
export { leaseAgreement } from './lease-agreement';
export { leaseRenewalAgreement } from './lease-renewal-agreement';
export { leaseTerminationLetter } from './lease-termination-letter';
export { letterOfIntent } from './letter-of-intent';
export { licensingAgreement } from './licensing-agreement';
export { livingTrust } from './living-trust';
export { livingWill } from './living-will';
export { loanAgreement } from './loan-agreement';
export { loanModificationAgreementMeta as loanModificationAgreement } from './loan-modification-agreement';
export { medicalConsent } from './medical-consent';
export { nda } from './nda';
export { nonCompeteAgreement } from './non-compete-agreement';
export { nonDisclosureAgreement } from './non-disclosure-agreement';
export { offerLetter } from './offer-letter';
export { llcOperatingAgreement } from './operating-agreement';
export { partnershipAgreement } from './partnership-agreement';
export { patentLicenseAgreementMeta as patentLicenseAgreement } from './patent-license-agreement';
export { personalCareAgreementMeta as personalCareAgreement } from './personal-care-agreement';
export { personalLoanAgreementMeta as personalLoanAgreement } from './personal-loan-agreement';
export { petAgreement } from './pet-agreement';
export { petCustodyAgreementMeta as petCustodyAgreement } from './pet-custody-agreement';
export { powerOfAttorney } from './power-of-attorney';
export { prenuptialAgreement } from './prenuptial-agreement';
export { promissoryNote } from './promissory-note';
export { propertyDeed } from './property-deed';
export { purchaseAgreement } from './purchase-agreement';
export { quitclaimDeed } from './quitclaim-deed';
export { rentalAgreement } from './rental-agreement';
export { residentialLeaseAgreement } from './residential-lease-agreement';
export { roomRentalAgreement } from './room-rental-agreement';
export { roommateAgreement } from './roommate-agreement';
export { salesAgreement } from './sales-agreement';
export { securityAgreementMeta as securityAgreement } from './security-agreement';
export { serviceAgreement } from './service-agreement';
export { severanceAgreement } from './severance-agreement';
export { simpleWill } from './simple-will';
export { subleaseAgreement } from './sublease-agreement';
export { subcontractorAgreementMeta as subcontractorAgreement } from './subcontractor-agreement';
export { terminationLetter } from './termination-letter';
export { trademarkAssignment } from './trademark-assignment';
export { trademarkLicenseAgreementMeta as trademarkLicenseAgreement } from './trademark-license-agreement';
export { vehicleBillOfSale } from './vehicle-bill-of-sale';
export { workFromHomeAgreementMeta as workFromHomeAgreement } from './work-from-home-agreement';
export { generalLiabilityWaiverMeta as generalLiabilityWaiver } from './general-liability-waiver';
export { productLiabilityWaiverMeta as productLiabilityWaiver } from './product-liability-waiver';
export { professionalLiabilityWaiverMeta as professionalLiabilityWaiver } from './professional-liability-waiver';
export { arbitrationAgreementMeta as arbitrationAgreement } from './arbitration-agreement';
export { mediationAgreementMeta as mediationAgreement } from './mediation-agreement';
export { settlementAgreementMeta as settlementAgreement } from './settlement-agreement';
export { taxPreparationAgreementMeta as taxPreparationAgreement } from './tax-preparation-agreement';
export { bookkeepingServicesAgreementMeta as bookkeepingServicesAgreement } from './bookkeeping-services-agreement';
export { websiteDevelopmentAgreementMeta as websiteDevelopmentAgreement } from './website-development-agreement';
export { socialMediaManagementAgreementMeta as socialMediaManagementAgreement } from './social-media-management-agreement';
export { influencerAgreementMeta as influencerAgreement } from './influencer-agreement';
export { affiliateMarketingAgreementMeta as affiliateMarketingAgreement } from './affiliate-marketing-agreement';
export { brandAmbassadorAgreementMeta as brandAmbassadorAgreement } from './brand-ambassador-agreement';
export { autoRepairAgreementMeta as autoRepairAgreement } from './auto-repair-agreement';
export { vehicleLeaseAgreementMeta as vehicleLeaseAgreement } from './vehicle-lease-agreement';
export { transportationServiceAgreementMeta as transportationServiceAgreement } from './transportation-service-agreement';
export { medicalConsentFormMeta as medicalConsentForm } from './medical-consent-form';
export { hipaaAuthorizationFormMeta as hipaaAuthorizationForm } from './hipaa-authorization-form';
export { softwareLicenseAgreementMeta as softwareLicenseAgreement } from './software-license-agreement';
export { dataProcessingAgreementMeta as dataProcessingAgreement } from './data-processing-agreement';
export { internshipAgreementMeta as internshipAgreement } from './internship-agreement';
export { volunteerAgreementMeta as volunteerAgreement } from './volunteer-agreement';
export { talentAgreementMeta as talentAgreement } from './talent-agreement';
export { musicLicensingAgreementMeta as musicLicensingAgreement } from './music-licensing-agreement';
export { photographyReleaseMeta as photographyRelease } from './photography-release';
export { notarizationRequestMeta as notarizationRequest } from './notarization-request';
export { immigrationAffidavitMeta as immigrationAffidavit } from './immigration-affidavit';
export { fitnessWaiverMeta as fitnessWaiver } from './fitness-waiver';
export { eventPlanningContractMeta as eventPlanningContract } from './event-planning-contract';
export { personalTrainingAgreementMeta as personalTrainingAgreement } from './personal-training-agreement';

// Export count for verification
export const US_DOCUMENT_COUNT = 109;
