// src/lib/documents/us/index.ts
// Auto-generated US documents index - connects all document folders

// Removed: export { affidavit } from './affidavit'; // Use affidavit-general instead
export { affidavitGeneral } from './affidavit-general';
export { articlesOfIncorporation } from './articles-of-incorporation';
export { articlesOfIncorporationBiz } from './articles-of-incorporation-biz';
export { boatBillOfSale } from './boat-bill-of-sale';
export { businessContractMeta } from './business-contract';
export { childCustodyAgreement } from './child-custody-agreement';
export { childMedicalConsent } from './child-medical-consent';
export { childSupportAgreementMeta as childSupportAgreement } from './child-support-agreement';
export { codicilToWillMeta as codicilToWill } from './codicil-to-will';
export { commissionAgreementMeta as commissionAgreement } from './commission-agreement';
export { commercialLeaseAgreement } from './commercial-lease-agreement';
export { consignmentAgreement } from './consignment-agreement';
export { constructionContractMeta as constructionContract } from './construction-contract';
export { consultingAgreementMeta } from './consulting-agreement';
export { copyrightAssignment } from './copyright-assignment';
export { copyrightAssignmentAgreementMeta as copyrightAssignmentAgreement } from './copyright-assignment-agreement';
export { demandLetter } from './demand-letter';
export { demandLetterPayment } from './demand-letter-payment';
export { divorceSettlement } from './divorce-settlement';
export { divorceSettlementAgreement } from './divorce-settlement-agreement';
export { durablePowerOfAttorneyMeta as durablePowerOfAttorney } from './durable-power-of-attorney';
export { educationTrust } from './education-trust';
export { employeeEvaluationFormMeta as employeeEvaluationForm } from './employee-evaluation-form';
export { employeeHandbookMeta as employeeHandbook } from './employee-handbook';
export { employmentContract } from './employment-contract';
export { employmentOfferLetter } from './employment-offer-letter';
export { employmentTerminationLetter } from './employment-termination-letter';
export { employmentVerificationLetterMeta as employmentVerificationLetter } from './employment-verification-letter';
export { evictionNotice } from './eviction-notice';
export { generalInquiry } from './general-inquiry';
export { healthCareDirective } from './health-care-directive';
export { healthcarePowerOfAttorney } from './healthcare-power-of-attorney';
export { homeImprovementContractMeta as homeImprovementContract } from './home-improvement-contract';
export { independentContractorAgreement } from './independent-contractor-agreement';
export { invoice } from './invoice';
export { jobApplicationFormMeta as jobApplicationForm } from './job-application-form';
export { jointLivingTrust } from './joint-living-trust';
export { lastWillTestament } from './last-will-testament';
export { leaseAgreement } from './lease-agreement';
export { leaseRenewalAgreementMeta as leaseRenewalAgreement } from './lease-renewal-agreement';
export { leaseTerminationLetterMeta as leaseTerminationLetter } from './lease-termination-letter';
export { letterOfIntentMeta as letterOfIntent } from './letter-of-intent';
export { licensingAgreement } from './licensing-agreement';
export { livingTrust } from './living-trust';
export { livingTrustAmendment } from './living-trust-amendment';
export { livingWill } from './living-will';
export { loanAgreement } from './loan-agreement';
export { loanModificationAgreementMeta as loanModificationAgreement } from './loan-modification-agreement';
export { medicalConsent } from './medical-consent';
export { medicalPowerOfAttorney } from './medical-power-of-attorney';
// Removed: export { nda } from './nda'; // Use non-disclosure-agreement instead
export { nonCompeteAgreement } from './non-compete-agreement';
export { nonDisclosureAgreement } from './non-disclosure-agreement';
// Removed: export { offerLetter } from './offer-letter'; // Use employment-offer-letter instead
export { llcOperatingAgreement } from './operating-agreement';
export { partnershipAgreement } from './partnership-agreement';
export { patentLicenseAgreementMeta as patentLicenseAgreement } from './patent-license-agreement';
export { personalCareAgreementMeta as personalCareAgreement } from './personal-care-agreement';
export { personalLoanAgreementMeta as personalLoanAgreement } from './personal-loan-agreement';
export { petAgreementMeta as petAgreement } from './pet-agreement';
export { petCustodyAgreementMeta as petCustodyAgreement } from './pet-custody-agreement';
export { pourOverWill } from './pour-over-will';
export { powerOfAttorney } from './power-of-attorney';
export { powerOfAttorneyForChild } from './power-of-attorney-for-child';
export { prenuptialAgreement } from './prenuptial-agreement';
export { promissoryNote } from './promissory-note';
export { propertyDeed } from './property-deed';
export { purchaseAgreement } from './purchase-agreement';
export { quitclaimDeed } from './quitclaim-deed';
export { rentalAgreement } from './rental-agreement';
export { residentialLeaseAgreement } from './residential-lease-agreement';
export { revocationOfPowerOfAttorney } from './revocation-of-power-of-attorney';
export { metadata as roomRentalAgreement } from './room-rental-agreement';
export { roommateAgreementMeta as roommateAgreement } from './roommate-agreement';
export { salesAgreementMeta as salesAgreement } from './sales-agreement';
export { securityAgreementMeta as securityAgreement } from './security-agreement';
export { serviceAgreement } from './service-agreement';
export { severanceAgreement } from './severance-agreement';
export { simpleWillMeta as simpleWill } from './simple-will';
export { subleaseAgreementMeta as subleaseAgreement } from './sublease-agreement';
export { subcontractorAgreementMeta as subcontractorAgreement } from './subcontractor-agreement';
export { terminationLetter } from './termination-letter';
export { trademarkAssignment } from './trademark-assignment';
export { trademarkLicenseAgreementMeta as trademarkLicenseAgreement } from './trademark-license-agreement';
export { vehicleBillOfSale } from './vehicle-bill-of-sale';
export { workFromHomeAgreementMeta as workFromHomeAgreement } from './work-from-home-agreement';
export { generalLiabilityWaiverMeta as generalLiabilityWaiver } from './general-liability-waiver';
export { productLiabilityWaiverMeta as productLiabilityWaiver } from './product-liability-waiver';
export { professionalLiabilityWaiverMeta as professionalLiabilityWaiver } from './professional-liability-waiver';
export { arbitrationAgreementMeta as arbitrationAgreement } from './arbitration-agreement';
export { mediationAgreementMeta as mediationAgreement } from './mediation-agreement';
export { settlementAgreementMeta as settlementAgreement } from './settlement-agreement';
export { taxPreparationAgreementMeta as taxPreparationAgreement } from './tax-preparation-agreement';
export { bookkeepingServicesAgreementMeta as bookkeepingServicesAgreement } from './bookkeeping-services-agreement';
export { websiteDevelopmentAgreementMeta as websiteDevelopmentAgreement } from './website-development-agreement';
export { socialMediaManagementAgreementMeta as socialMediaManagementAgreement } from './social-media-management-agreement';
export { influencerAgreementMeta as influencerAgreement } from './influencer-agreement';
export { affiliateMarketingAgreementMeta as affiliateMarketingAgreement } from './affiliate-marketing-agreement';
export { brandAmbassadorAgreementMeta as brandAmbassadorAgreement } from './brand-ambassador-agreement';
export { autoRepairAgreementMeta as autoRepairAgreement } from './auto-repair-agreement';
export { vehicleLeaseAgreementMeta as vehicleLeaseAgreement } from './vehicle-lease-agreement';
export { transportationServiceAgreementMeta as transportationServiceAgreement } from './transportation-service-agreement';
export { medicalConsentFormMeta as medicalConsentForm } from './medical-consent-form';

// New Employment Documents
export { executiveEmploymentAgreement } from './executive-employment-agreement';
export { telecommutingAgreement } from './telecommuting-agreement';
export { progressiveDisciplinePolicy } from './progressive-discipline-policy';
export { employeeBonusPlan } from './employee-bonus-plan';
export { directDepositForm } from './direct-deposit-form';
export { proofOfIncomeLetter } from './proof-of-income-letter';
export { equityIncentivePlan } from './equity-incentive-plan';
export { leaveOfAbsenceRequestForm } from './leave-of-absence-request-form';
export { employeeWarningNotice } from './employee-warning-notice';
export { resignationLetter } from './resignation-letter';
export { twoweeksnoticeletter } from './two-weeks-notice-letter';
export { employeeNonDisclosureAgreement } from './employee-non-disclosure-agreement';
export { salaryVerificationLetter } from './salary-verification-letter';
export { hipaaAuthorizationFormMeta as hipaaAuthorizationForm } from './hipaa-authorization-form';
export { softwareLicenseAgreementMeta as softwareLicenseAgreement } from './software-license-agreement';
export { dataProcessingAgreementMeta as dataProcessingAgreement } from './data-processing-agreement';
export { internshipAgreementMeta as internshipAgreement } from './internship-agreement';
export { volunteerAgreementMeta as volunteerAgreement } from './volunteer-agreement';
export { talentAgreementMeta as talentAgreement } from './talent-agreement';
export { musicLicensingAgreementMeta as musicLicensingAgreement } from './music-licensing-agreement';
export { photographyReleaseMeta as photographyRelease } from './photography-release';
export { notarizationRequestMeta as notarizationRequest } from './notarization-request';
export { immigrationAffidavitMeta as immigrationAffidavit } from './immigration-affidavit';
export { fitnessWaiverMeta as fitnessWaiver } from './fitness-waiver';
export { eventPlanningContractMeta as eventPlanningContract } from './event-planning-contract';
export { personalTrainingAgreementMeta as personalTrainingAgreement } from './personal-training-agreement';
export { researchAgreementMeta as researchAgreement } from './research-agreement';
export { licensingAgreementGeneralMeta as licensingAgreementGeneral } from './licensing-agreement-general';
export { courtFilingDocumentMeta as courtFilingDocument } from './court-filing-document';
export { agriculturalAgreementMeta as agriculturalAgreement } from './agricultural-agreement';
export { cryptocurrencyAgreementMeta as cryptocurrencyAgreement } from './cryptocurrency-agreement';
export { sportsAgreementMeta as sportsAgreement } from './sports-agreement';
export { environmentalAgreementMeta as environmentalAgreement } from './environmental-agreement';
export { gamingAgreementMeta as gamingAgreement } from './gaming-agreement';
export { travelInsuranceAgreementMeta as travelInsuranceAgreement } from './travel-insurance-agreement';
export { vacationRentalAgreementMeta as vacationRentalAgreement } from './vacation-rental-agreement';
export { cateringAgreementMeta as cateringAgreement } from './catering-agreement';
export { restaurantAgreementMeta as restaurantAgreement } from './restaurant-agreement';
export { barAgreementMeta as barAgreement } from './bar-agreement';
export { hotelAgreementMeta as hotelAgreement } from './hotel-agreement';
export { franchiseAgreementMeta as franchiseAgreement } from './franchise-agreement';
export { membershipAgreementMeta as membershipAgreement } from './membership-agreement';
export { donationAgreementMeta as donationAgreement } from './donation-agreement';
export { sponsorshipAgreementMeta as sponsorshipAgreement } from './sponsorship-agreement';
export { tuitionAgreementMeta as tuitionAgreement } from './tuition-agreement';
export { coachingAgreementMeta as coachingAgreement } from './coaching-agreement';
export { tutoringAgreementMeta as tutoringAgreement } from './tutoring-agreement';
export { dogBreedingAgreementMeta as dogBreedingAgreement } from './dog-breeding-agreement';
export { horseBoardingAgreementMeta as horseBoardingAgreement } from './horse-boarding-agreement';
export { cropSharingAgreementMeta as cropSharingAgreement } from './crop-sharing-agreement';
export { miningAgreementMeta as miningAgreement } from './mining-agreement';
// Removed: export { oilGasLeaseMeta as oilGasLease } from './oil-gas-lease'; // Use oil-gas-lease-agreement instead
export { appDevelopmentAgreementMeta as appDevelopmentAgreement } from './app-development-agreement';
export { cloudServicesAgreementMeta as cloudServicesAgreement } from './cloud-services-agreement';
export { cybersecurityAgreementMeta as cybersecurityAgreement } from './cybersecurity-agreement';
export { automotiveServiceAgreementMeta as automotiveServiceAgreement } from './automotive-service-agreement';
export { rideSharingAgreementMeta as rideSharingAgreement } from './ride-sharing-agreement';
export { telemedicineAgreementMeta as telemedicineAgreement } from './telemedicine-agreement';
export { realEstatePurchaseAgreementMeta as realEstatePurchaseAgreement } from './real-estate-purchase-agreement';
export { creditCardAgreementMeta as creditCardAgreement } from './credit-card-agreement';
export { mortgageAgreementMeta as mortgageAgreement } from './mortgage-agreement';
export { investmentAgreementMeta as investmentAgreement } from './investment-agreement';
export { startupEquityAgreementMeta as startupEquityAgreement } from './startup-equity-agreement';
export { insuranceClaimFormMeta as insuranceClaimForm } from './insurance-claim-form';
export { retirementPlanAgreementMeta as retirementPlanAgreement } from './retirement-plan-agreement';
export { elderCareAgreementMeta as elderCareAgreement } from './elder-care-agreement';
export { guardianshipAgreementMeta as guardianshipAgreement } from './guardianship-agreement';
export { ecommerceTermsOfServiceMeta as ecommerceTermsOfService } from './ecommerce-terms-of-service';
export { internationalTradeAgreementMeta as internationalTradeAgreement } from './international-trade-agreement';
export { digitalAssetAgreementMeta as digitalAssetAgreement } from './digital-asset-agreement';
export { maritimeCharterAgreementMeta as maritimeCharterAgreement } from './maritime-charter-agreement';
export { aviationCharterAgreementMeta as aviationCharterAgreement } from './aviation-charter-agreement';
export { filmProductionAgreementMeta as filmProductionAgreement } from './film-production-agreement';
export { recordingArtistAgreementMeta as recordingArtistAgreement } from './recording-artist-agreement';
export { talentManagementAgreementMeta as talentManagementAgreement } from './talent-management-agreement';
export { solarEnergyAgreementMeta as solarEnergyAgreement } from './solar-energy-agreement';
export { foodTruckAgreementMeta as foodTruckAgreement } from './food-truck-agreement';
export { athleticScholarshipAgreementMeta as athleticScholarshipAgreement } from './athletic-scholarship-agreement';
export { clinicalTrialAgreementMeta as clinicalTrialAgreement } from './clinical-trial-agreement';
export { generalContractorAgreementMeta as generalContractorAgreement } from './general-contractor-agreement';
export { governmentContractAgreementMeta as governmentContractAgreement } from './government-contract-agreement';
export { miningLeaseAgreementMeta as miningLeaseAgreement } from './mining-lease-agreement';
export { nonprofitBylawsMeta as nonprofitBylaws } from './nonprofit-bylaws';
export { oilGasLeaseAgreementMeta as oilGasLeaseAgreement } from './oil-gas-lease-agreement';
export { farmLeaseAgreementMeta as farmLeaseAgreement } from './farm-lease-agreement';
export { franchiseDisclosureAgreementMeta as franchiseDisclosureAgreement } from './franchise-disclosure-agreement';
export { huntingLeaseAgreementMeta as huntingLeaseAgreement } from './hunting-lease-agreement';
export { livestockPurchaseAgreementMeta as livestockPurchaseAgreement } from './livestock-purchase-agreement';
export { timberSaleAgreementMeta as timberSaleAgreement } from './timber-sale-agreement';
export { waterRightsAgreementMeta as waterRightsAgreement } from './water-rights-agreement';
export { postnuptialAgreementMeta as postnuptialAgreement } from './postnuptial-agreement';
export { marriageSeparationAgreementMeta as marriageSeparationAgreement } from './marriage-separation-agreement';
export { separationAgreementMeta as separationAgreement } from './separation-agreement';
export { childCareContractMeta as childCareContract } from './child-care-contract';
export { childCareAuthorizationFormMeta as childCareAuthorizationForm } from './child-care-authorization-form';
export { childTravelConsentMeta as childTravelConsent } from './child-travel-consent';
export { parentingPlanMeta as parentingPlan } from './parenting-plan';
export { nameChangeNotificationLetterMeta as nameChangeNotificationLetter } from './name-change-notification-letter';
export { affidavitOfIdentityMeta as affidavitOfIdentity } from './affidavit-of-identity';
export { complaintLetterMeta as complaintLetter } from './complaint-letter';
export { membershipCancellationLetterMeta as membershipCancellationLetter } from './membership-cancellation-letter';
export { lotteryPoolContractMeta as lotteryPoolContract } from './lottery-pool-contract';
export { resignationLetterPersonalMeta as resignationLetterPersonal } from './resignation-letter-personal';
export { metadata as cohabitationAgreement } from './cohabitation-agreement';
export { metadata as leaseAmendment } from './lease-amendment';
export { metadata as leaseAddendum } from './lease-addendum';
export { metadata as petAddendum } from './pet-addendum';
export { metadata as rentReceipt } from './rent-receipt';
export { metadata as residentialRentalApplication } from './residential-rental-application';
export { metadata as residentialRentalInspectionReport } from './residential-rental-inspection-report';
export { metadata as tenantMaintenanceRequest } from './tenant-maintenance-request';
export { metadata as lateRentNotice } from './late-rent-notice';
export { metadata as noticeToPayRentOrQuit } from './notice-to-pay-rent-or-quit';
export { metadata as noticeToEnter } from './notice-to-enter';
export { metadata as noticeOfLeaseViolation } from './notice-of-lease-violation';
export { metadata as rentIncreaseLetter } from './rent-increase-letter';
export { metadata as tripleNetLease } from './triple-net-lease';
export { metadata as officeSpaceLease } from './office-space-lease';
export { metadata as retailSpaceLease } from './retail-space-lease';
export { metadata as restaurantLease } from './restaurant-lease';
export { metadata as warehouseLease } from './warehouse-lease';
export { metadata as commercialLeaseWithOptionToPurchase } from './commercial-lease-with-option-to-purchase';
export { metadata as storageSpaceLeaseAgreement } from './storage-space-lease-agreement';
export { metadata as parkingSpaceLeaseAgreement } from './parking-space-lease-agreement';
export { metadata as propertyManagerAgreement } from './property-manager-agreement';
export { metadata as earnestMoneyAgreement } from './earnest-money-agreement';
export { warrantyDeedMeta as warrantyDeed } from './warranty-deed';
export { releaseOfLiabilityMeta as releaseOfLiability } from './release-of-liability';
export { holdHarmlessAgreementMetadata as holdHarmlessAgreement } from './hold-harmless-agreement';
export { liabilityWaiverMetadata as liabilityWaiver } from './liability-waiver';
export { indemnityAgreementMetadata as indemnityAgreement } from './indemnity-agreement';
export { incidentReportMetadata as incidentReport } from './incident-report';
export { accidentReportMetadata as accidentReport } from './accident-report';
export { covid19HealthScreeningMetadata as covid19HealthScreening } from './covid19-health-screening';
export { ceaseDesistLetterMetadata as ceaseDesistLetter } from './cease-desist-letter';
export { smallClaimsWorksheetMetadata as smallClaimsWorksheet } from './small-claims-worksheet';
export { forceMajeureNoticeMetadata as forceMajeureNotice } from './force-majeure-notice';
export { breachContractNoticeMetadata as breachContractNotice } from './breach-contract-notice';

// New Business Documents
export { privatePlacementMemorandum } from './private-placement-memorandum';
export { buySellAgreement } from './buy-sell-agreement';
export { limitedPartnershipAgreement } from './limited-partnership-agreement';
export { partnershipAmendment } from './partnership-amendment';
export { partnershipDissolutionAgreement } from './partnership-dissolution-agreement';
export { jointVentureAgreement } from './joint-venture-agreement';

// Export count for verification
export const US_DOCUMENT_COUNT = 245;
