import type { Question } from '@/types/documents';

export const questions: Question[] = [
  {
    id: 'parentName',
    label: 'Parent/Guardian Full Name',
    type: 'text',
    required: true,
    placeholder: 'Enter your full legal name',
  },
  {
    id: 'parentAddress',
    label: 'Parent/Guardian Address',
    type: 'textarea',
    required: true,
    placeholder: 'Enter your complete address',
  },
  {
    id: 'parentPhone',
    label: 'Parent/Guardian Phone Number',
    type: 'text',
    required: true,
    placeholder: 'Primary phone number',
  },
  {
    id: 'coParentName',
    label: 'Co-Parent/Guardian Full Name (Optional)',
    type: 'text',
    placeholder: 'Other parent or guardian if applicable',
  },
  {
    id: 'coParentAddress',
    label: 'Co-Parent/Guardian Address (Optional)',
    type: 'textarea',
    placeholder: 'Complete address of co-parent/guardian',
  },
  {
    id: 'coParentPhone',
    label: 'Co-Parent/Guardian Phone Number (Optional)',
    type: 'text',
    placeholder: 'Phone number of co-parent/guardian',
  },
  {
    id: 'childName',
    label: "Child's Full Name",
    type: 'text',
    required: true,
    placeholder: "Enter child's full legal name",
  },
  {
    id: 'childDateOfBirth',
    label: "Child's Date of Birth",
    type: 'date',
    required: true,
  },
  {
    id: 'childAddress',
    label: "Child's Address",
    type: 'textarea',
    required: true,
    placeholder: "Child's current address",
  },
  {
    id: 'additionalChildren',
    label: 'Additional Children Covered (Optional)',
    type: 'textarea',
    placeholder: 'List any other children this POA should cover',
  },
  {
    id: 'agentName',
    label: 'Agent Full Name',
    type: 'text',
    required: true,
    placeholder: 'Person receiving authority over the child',
  },
  {
    id: 'agentAddress',
    label: 'Agent Address',
    type: 'textarea',
    required: true,
    placeholder: 'Complete address of the agent',
  },
  {
    id: 'agentPhone',
    label: 'Agent Phone Number',
    type: 'text',
    required: true,
    placeholder: 'Primary phone number for the agent',
  },
  {
    id: 'agentRelationship',
    label: "Agent's Relationship to Child",
    type: 'text',
    required: true,
    placeholder: 'e.g., grandparent, aunt, uncle, family friend',
  },
  {
    id: 'backupAgentName',
    label: 'Backup Agent Full Name (Optional)',
    type: 'text',
    placeholder: 'Alternative person if primary agent cannot serve',
  },
  {
    id: 'backupAgentAddress',
    label: 'Backup Agent Address (Optional)',
    type: 'textarea',
    placeholder: 'Complete address of backup agent',
  },
  {
    id: 'backupAgentPhone',
    label: 'Backup Agent Phone Number (Optional)',
    type: 'text',
    placeholder: 'Phone number for backup agent',
  },
  {
    id: 'effectiveDate',
    label: 'Effective Date',
    type: 'date',
    required: true,
  },
  {
    id: 'expirationDate',
    label: 'Expiration Date',
    type: 'date',
    required: true,
  },
  {
    id: 'purposeOfAuthority',
    label: 'Purpose/Reason for This Authority',
    type: 'textarea',
    required: true,
    placeholder:
      'Explain why this POA is needed (travel, temporary care, etc.)',
  },
  {
    id: 'medicalCareAuthority',
    label: 'Authority to Make Medical Care Decisions',
    type: 'checkbox',
    defaultValue: true,
  },
  {
    id: 'emergencyMedicalCare',
    label: 'Authority for Emergency Medical Care',
    type: 'checkbox',
    defaultValue: true,
  },
  {
    id: 'routineMedicalCare',
    label: 'Authority for Routine Medical Care',
    type: 'checkbox',
    defaultValue: false,
  },
  {
    id: 'dentalCare',
    label: 'Authority for Dental Care',
    type: 'checkbox',
    defaultValue: false,
  },
  {
    id: 'mentalHealthCare',
    label: 'Authority for Mental Health Care',
    type: 'checkbox',
    defaultValue: false,
  },
  {
    id: 'educationalDecisions',
    label: 'Authority to Make Educational Decisions',
    type: 'checkbox',
    defaultValue: true,
  },
  {
    id: 'schoolEnrollment',
    label: 'Authority to Enroll in School',
    type: 'checkbox',
    defaultValue: false,
  },
  {
    id: 'extracurricularActivities',
    label: 'Authority for Extracurricular Activities',
    type: 'checkbox',
    defaultValue: true,
  },
  {
    id: 'dailyCareDecisions',
    label: 'Authority for Daily Care Decisions',
    type: 'checkbox',
    defaultValue: true,
  },
  {
    id: 'travelAuthorization',
    label: 'Authority to Travel with Child',
    type: 'checkbox',
    defaultValue: false,
  },
  {
    id: 'financialDecisions',
    label: 'Authority for Financial Decisions',
    type: 'checkbox',
    defaultValue: false,
  },
  {
    id: 'financialLimit',
    label: 'Financial Decision Limit (if applicable)',
    type: 'text',
    placeholder: 'Maximum amount for financial decisions',
    dependsOn: { field: 'financialDecisions', value: true },
  },
  {
    id: 'specificAuthorizations',
    label: 'Specific Additional Authorizations (Optional)',
    type: 'textarea',
    placeholder: 'Any specific additional powers granted to the agent',
  },
  {
    id: 'specificRestrictions',
    label: 'Specific Restrictions (Optional)',
    type: 'textarea',
    placeholder: "Any limitations or restrictions on the agent's authority",
  },
  {
    id: 'medicalInformation',
    label: 'Important Medical Information (Optional)',
    type: 'textarea',
    placeholder:
      'Any medical conditions or health information the agent should know',
  },
  {
    id: 'allergies',
    label: "Child's Allergies (Optional)",
    type: 'textarea',
    placeholder: 'List any allergies the child has',
  },
  {
    id: 'medications',
    label: 'Current Medications (Optional)',
    type: 'textarea',
    placeholder: 'List any medications the child is currently taking',
  },
  {
    id: 'primaryPhysician',
    label: 'Primary Physician Name (Optional)',
    type: 'text',
    placeholder: "Child's primary doctor",
  },
  {
    id: 'primaryPhysicianPhone',
    label: 'Primary Physician Phone (Optional)',
    type: 'text',
    placeholder: "Phone number for child's primary doctor",
  },
  {
    id: 'insurance',
    label: 'Insurance Provider (Optional)',
    type: 'text',
    placeholder: "Child's health insurance provider",
  },
  {
    id: 'insurancePolicyNumber',
    label: 'Insurance Policy Number (Optional)',
    type: 'text',
    placeholder: 'Health insurance policy number',
  },
  {
    id: 'emergencyContact',
    label: 'Emergency Contact (Optional)',
    type: 'text',
    placeholder: 'Additional emergency contact besides parents',
  },
  {
    id: 'emergencyContactPhone',
    label: 'Emergency Contact Phone (Optional)',
    type: 'text',
    placeholder: 'Phone number for emergency contact',
  },
  {
    id: 'specialInstructions',
    label: 'Special Instructions (Optional)',
    type: 'textarea',
    placeholder: 'Any special care instructions, routines, or preferences',
  },
  {
    id: 'witnessOneName',
    label: 'First Witness Full Name',
    type: 'text',
    required: true,
    placeholder: 'Adult witness to POA signing',
  },
  {
    id: 'witnessOneAddress',
    label: 'First Witness Address',
    type: 'textarea',
    required: true,
    placeholder: 'Complete address of first witness',
  },
  {
    id: 'witnessTwoName',
    label: 'Second Witness Full Name',
    type: 'text',
    required: true,
    placeholder: 'Second adult witness to POA signing',
  },
  {
    id: 'witnessTwoAddress',
    label: 'Second Witness Address',
    type: 'textarea',
    required: true,
    placeholder: 'Complete address of second witness',
  },
  {
    id: 'executionDate',
    label: 'POA Execution Date',
    type: 'date',
    required: true,
  },
  {
    id: 'executionState',
    label: 'State Where POA is Executed',
    type: 'text',
    required: true,
    placeholder: 'State where you are signing this POA',
  },
  {
    id: 'executionCounty',
    label: 'County Where POA is Executed',
    type: 'text',
    required: true,
    placeholder: 'County where you are signing this POA',
  },
];
