import { z } from 'zod';

export const schema = z.object({
  parentName: z.string().min(1, 'Parent name is required'),
  parentAddress: z.string().min(1, 'Parent address is required'),
  parentPhone: z.string().min(1, 'Parent phone number is required'),
  coParentName: z.string().optional(),
  coParentAddress: z.string().optional(),
  coParentPhone: z.string().optional(),
  childName: z.string().min(1, 'Child name is required'),
  childDateOfBirth: z.string().min(1, 'Child date of birth is required'),
  childAddress: z.string().min(1, 'Child address is required'),
  additionalChildren: z.string().optional(),
  agentName: z.string().min(1, 'Agent name is required'),
  agentAddress: z.string().min(1, 'Agent address is required'),
  agentPhone: z.string().min(1, 'Agent phone number is required'),
  agentRelationship: z.string().min(1, 'Agent relationship is required'),
  backupAgentName: z.string().optional(),
  backupAgentAddress: z.string().optional(),
  backupAgentPhone: z.string().optional(),
  backupAgentRelationship: z.string().optional(),
  effectiveDate: z.string().min(1, 'Effective date is required'),
  expirationDate: z.string().min(1, 'Expiration date is required'),
  purposeOfAuthority: z.string().min(1, 'Purpose of authority is required'),
  medicalCareAuthority: z.boolean().default(true),
  educationalDecisions: z.boolean().default(true),
  dailyCareDecisions: z.boolean().default(true),
  travelAuthorization: z.boolean().default(false),
  emergencyMedicalCare: z.boolean().default(true),
  routineMedicalCare: z.boolean().default(false),
  dentalCare: z.boolean().default(false),
  mentalHealthCare: z.boolean().default(false),
  schoolEnrollment: z.boolean().default(false),
  extracurricularActivities: z.boolean().default(true),
  financialDecisions: z.boolean().default(false),
  financialLimit: z.string().optional(),
  specificAuthorizations: z.string().optional(),
  specificRestrictions: z.string().optional(),
  medicalInformation: z.string().optional(),
  allergies: z.string().optional(),
  medications: z.string().optional(),
  primaryPhysician: z.string().optional(),
  primaryPhysicianPhone: z.string().optional(),
  insurance: z.string().optional(),
  insurancePolicyNumber: z.string().optional(),
  emergencyContact: z.string().optional(),
  emergencyContactPhone: z.string().optional(),
  specialInstructions: z.string().optional(),
  revocationConditions: z.string().optional(),
  witnessOneName: z.string().min(1, 'First witness name is required'),
  witnessOneAddress: z.string().min(1, 'First witness address is required'),
  witnessTwoName: z.string().min(1, 'Second witness name is required'),
  witnessTwoAddress: z.string().min(1, 'Second witness address is required'),
  notaryName: z.string().optional(),
  notaryCommission: z.string().optional(),
  executionDate: z.string().min(1, 'Execution date is required'),
  executionState: z.string().min(1, 'State of execution is required'),
  executionCounty: z.string().min(1, 'County of execution is required'),
});