import type { Question } from '@/types/documents';

export const questions: Question[] = [
  {
    id: 'principalName',
    label: 'Your Full Legal Name (Principal)',
    type: 'text',
    required: true,
    placeholder: 'Enter your full legal name',
  },
  {
    id: 'principalAddress',
    label: 'Your Address',
    type: 'textarea',
    required: true,
    placeholder: 'Enter your complete address',
  },
  {
    id: 'principalDateOfBirth',
    label: 'Your Date of Birth',
    type: 'date',
    required: true,
  },
  {
    id: 'agentName',
    label: 'Medical Agent Full Name',
    type: 'text',
    required: true,
    placeholder: 'Person you are appointing as your medical agent',
  },
  {
    id: 'agentAddress',
    label: 'Medical Agent Address',
    type: 'textarea',
    required: true,
    placeholder: 'Complete address of your medical agent',
  },
  {
    id: 'agentPhone',
    label: 'Medical Agent Phone Number',
    type: 'text',
    required: true,
    placeholder: 'Primary phone number for your medical agent',
  },
  {
    id: 'agentRelationship',
    label: 'Relationship to Medical Agent',
    type: 'text',
    required: true,
    placeholder: 'e.g., spouse, child, parent, sibling, friend',
  },
  {
    id: 'alternateAgentName',
    label: 'Alternate Agent Full Name (Optional)',
    type: 'text',
    placeholder: 'Backup person if primary agent cannot serve',
  },
  {
    id: 'alternateAgentAddress',
    label: 'Alternate Agent Address (Optional)',
    type: 'textarea',
    placeholder: 'Complete address of alternate agent',
  },
  {
    id: 'alternateAgentPhone',
    label: 'Alternate Agent Phone Number (Optional)',
    type: 'text',
    placeholder: 'Phone number for alternate agent',
  },
  {
    id: 'alternateAgentRelationship',
    label: 'Relationship to Alternate Agent (Optional)',
    type: 'text',
    placeholder: 'Your relationship to the alternate agent',
  },
  {
    id: 'effectiveDate',
    label: 'When Should This Power of Attorney Take Effect?',
    type: 'select',
    required: true,
    options: [
      { value: 'immediately', label: 'Immediately upon signing' },
      { value: 'upon_incapacity', label: 'Only upon my incapacity' },
      { value: 'specific_date', label: 'On a specific date' },
    ],
  },
  {
    id: 'specificEffectiveDate',
    label: 'Specific Effective Date (if applicable)',
    type: 'date',
    dependsOn: { field: 'effectiveDate', value: 'specific_date' },
  },
  {
    id: 'medicalTreatmentAuthority',
    label: 'Medical Treatment Authority',
    type: 'textarea',
    required: true,
    placeholder: 'Describe the scope of medical treatment decisions your agent may make',
  },
  {
    id: 'hospitalAdmissionAuthority',
    label: 'Authority to Admit to Hospital or Medical Facility',
    type: 'checkbox',
    defaultValue: true,
  },
  {
    id: 'medicationAuthority',
    label: 'Authority to Consent to Medication',
    type: 'checkbox',
    defaultValue: true,
  },
  {
    id: 'surgicalProcedureAuthority',
    label: 'Authority to Consent to Surgical Procedures',
    type: 'checkbox',
    defaultValue: true,
  },
  {
    id: 'diagnosticTestAuthority',
    label: 'Authority to Consent to Diagnostic Tests',
    type: 'checkbox',
    defaultValue: true,
  },
  {
    id: 'mentalHealthTreatmentAuthority',
    label: 'Authority to Make Mental Health Treatment Decisions',
    type: 'checkbox',
    defaultValue: false,
  },
  {
    id: 'hipaaAuthorization',
    label: 'HIPAA Authorization (Access to Medical Records)',
    type: 'checkbox',
    defaultValue: true,
  },
  {
    id: 'medicalRecordsAccess',
    label: 'Authority to Access Medical Records',
    type: 'checkbox',
    defaultValue: true,
  },
  {
    id: 'lifeSupport',
    label: 'Life Support Decisions',
    type: 'select',
    required: true,
    options: [
      { value: 'continue', label: 'Continue life support' },
      { value: 'discontinue', label: 'Discontinue life support' },
      { value: 'agent_discretion', label: 'Leave to agent\'s discretion' },
    ],
  },
  {
    id: 'organDonation',
    label: 'Organ Donation Decision',
    type: 'select',
    required: true,
    options: [
      { value: 'yes', label: 'Yes, authorize organ donation' },
      { value: 'no', label: 'No, do not authorize organ donation' },
      { value: 'agent_discretion', label: 'Leave to agent\'s discretion' },
    ],
  },
  {
    id: 'autopsy',
    label: 'Autopsy Decision',
    type: 'select',
    required: true,
    options: [
      { value: 'yes', label: 'Yes, authorize autopsy' },
      { value: 'no', label: 'No, do not authorize autopsy' },
      { value: 'agent_discretion', label: 'Leave to agent\'s discretion' },
    ],
  },
  {
    id: 'specificMedicalInstructions',
    label: 'Specific Medical Instructions (Optional)',
    type: 'textarea',
    placeholder: 'Any specific medical instructions or preferences',
  },
  {
    id: 'medicationRestrictions',
    label: 'Medication Restrictions (Optional)',
    type: 'textarea',
    placeholder: 'Any medications you do not want administered',
  },
  {
    id: 'treatmentRestrictions',
    label: 'Treatment Restrictions (Optional)',
    type: 'textarea',
    placeholder: 'Any medical treatments you do not want',
  },
  {
    id: 'religiousMoralBeliefs',
    label: 'Religious or Moral Beliefs (Optional)',
    type: 'textarea',
    placeholder: 'Any religious or moral beliefs that should guide medical decisions',
  },
  {
    id: 'nursingHomePlacement',
    label: 'Authority to Place in Nursing Home or Care Facility',
    type: 'checkbox',
    defaultValue: false,
  },
  {
    id: 'limitationsOnAuthority',
    label: 'Limitations on Agent\'s Authority (Optional)',
    type: 'textarea',
    placeholder: 'Any limitations or restrictions on your agent\'s decision-making authority',
  },
  {
    id: 'witnessOneName',
    label: 'First Witness Full Name',
    type: 'text',
    required: true,
    placeholder: 'Adult witness to POA signing',
  },
  {
    id: 'witnessOneAddress',
    label: 'First Witness Address',
    type: 'textarea',
    required: true,
    placeholder: 'Complete address of first witness',
  },
  {
    id: 'witnessTwoName',
    label: 'Second Witness Full Name',
    type: 'text',
    required: true,
    placeholder: 'Second adult witness to POA signing',
  },
  {
    id: 'witnessTwoAddress',
    label: 'Second Witness Address',
    type: 'textarea',
    required: true,
    placeholder: 'Complete address of second witness',
  },
  {
    id: 'executionDate',
    label: 'POA Execution Date',
    type: 'date',
    required: true,
  },
  {
    id: 'executionState',
    label: 'State Where POA is Executed',
    type: 'text',
    required: true,
    placeholder: 'State where you are signing this POA',
  },
  {
    id: 'executionCounty',
    label: 'County Where POA is Executed',
    type: 'text',
    required: true,
    placeholder: 'County where you are signing this POA',
  },
];