import { z } from 'zod';

export const schema = z.object({
  principalName: z.string().min(1, 'Principal name is required'),
  principalAddress: z.string().min(1, 'Principal address is required'),
  principalDateOfBirth: z
    .string()
    .min(1, 'Principal date of birth is required'),
  agentName: z.string().min(1, 'Agent name is required'),
  agentAddress: z.string().min(1, 'Agent address is required'),
  agentPhone: z.string().min(1, 'Agent phone number is required'),
  agentRelationship: z.string().min(1, 'Agent relationship is required'),
  alternateAgentName: z.string().optional(),
  alternateAgentAddress: z.string().optional(),
  alternateAgentPhone: z.string().optional(),
  alternateAgentRelationship: z.string().optional(),
  secondAlternateAgentName: z.string().optional(),
  secondAlternateAgentAddress: z.string().optional(),
  effectiveDate: z.enum(['immediately', 'upon_incapacity', 'specific_date']),
  specificEffectiveDate: z.string().optional(),
  medicalTreatmentAuthority: z
    .string()
    .min(1, 'Medical treatment authority is required'),
  hospitalAdmissionAuthority: z.boolean().default(true),
  medicationAuthority: z.boolean().default(true),
  surgicalProcedureAuthority: z.boolean().default(true),
  diagnosticTestAuthority: z.boolean().default(true),
  mentalHealthTreatmentAuthority: z.boolean().default(false),
  hipaaAuthorization: z.boolean().default(true),
  medicalRecordsAccess: z.boolean().default(true),
  lifeSupport: z.enum(['continue', 'discontinue', 'agent_discretion']),
  organDonation: z.enum(['yes', 'no', 'agent_discretion']),
  autopsy: z.enum(['yes', 'no', 'agent_discretion']),
  specificMedicalInstructions: z.string().optional(),
  medicationRestrictions: z.string().optional(),
  treatmentRestrictions: z.string().optional(),
  religiousMoralBeliefs: z.string().optional(),
  nursingHomePlacement: z.boolean().default(false),
  financialAuthority: z.boolean().default(false),
  limitationsOnAuthority: z.string().optional(),
  additionalProvisions: z.string().optional(),
  durability: z.boolean().default(true),
  revocationConditions: z.string().optional(),
  witnessOneName: z.string().min(1, 'First witness name is required'),
  witnessOneAddress: z.string().min(1, 'First witness address is required'),
  witnessTwoName: z.string().min(1, 'Second witness name is required'),
  witnessTwoAddress: z.string().min(1, 'Second witness address is required'),
  notaryName: z.string().optional(),
  notaryCommission: z.string().optional(),
  executionDate: z.string().min(1, 'Execution date is required'),
  executionState: z.string().min(1, 'State of execution is required'),
  executionCounty: z.string().min(1, 'County of execution is required'),
});
