// src/lib/formSchemas/vehicleBillOfSale.ts
import type { FormField } from '@/data/formSchemas';
import { usStatesOptions } from '@/data/formSchemas';

export const vehicleBillOfSale: FormField[] = [
  {
    id: 'seller_name',
    label: "Seller's Full Name",
    type: 'text',
    required: true,
    tooltip:
      'Enter the full legal name of the person or entity selling the vehicle.',
  },
  {
    id: 'seller_phone',
    label: "Seller's Phone Number",
    type: 'text',
    required: false,
    placeholder: '(XXX) XXX-XXXX',
    tooltip: 'A valid phone number for the seller.',
  },
  {
    id: 'seller_address',
    label: "Seller's Full Address",
    type: 'textarea',
    required: true,
    tooltip: 'Include street, city, state, and ZIP code.',
  },
  {
    id: 'buyer_name',
    label: "Buyer's Full Name",
    type: 'text',
    required: true,
    tooltip: 'Full legal name of the buyer.',
  },
  {
    id: 'buyer_address',
    label: "Buyer's Full Address",
    type: 'textarea',
    required: true,
    tooltip: 'Include street, city, state, and ZIP code.',
  },
  {
    id: 'buyer_phone',
    label: "Buyer's Phone Number",
    type: 'text',
    required: false,
    placeholder: '(XXX) XXX-XXXX',
    tooltip: 'A valid phone number for the buyer.',
  },
  {
    id: 'year',
    label: 'Vehicle Year',
    type: 'number',
    required: true,
    placeholder: 'e.g., 2020',
    tooltip: 'Manufacturing year of the vehicle.',
  },
  {
    id: 'make',
    label: 'Vehicle Make',
    type: 'text',
    required: true,
    placeholder: 'e.g., Toyota',
    tooltip: 'Manufacturer of the vehicle.',
  },
  {
    id: 'model',
    label: 'Vehicle Model',
    type: 'text',
    required: true,
    placeholder: 'e.g., Camry',
    tooltip: 'Specific model of the vehicle.',
  },
  {
    id: 'vin',
    label: 'Vehicle Identification Number (VIN)',
    type: 'text',
    required: true,
    tooltip: '17-character VIN.',
  },
  {
    id: 'sale_price',
    label: 'Sale Price ($)',
    type: 'number',
    required: true,
    placeholder: 'e.g., 15000',
    tooltip: 'Total sale price in USD.',
  },
  {
    id: 'sale_date',
    label: 'Date of Sale',
    type: 'date',
    required: true,
    tooltip: 'When the sale is finalized.',
  },
  {
    id: 'state',
    label: 'State of Sale',
    type: 'select',
    required: true,
    options: usStatesOptions.filter((o) => o.value !== 'Other'),
    tooltip: 'Governing state.',
  },
  {
    id: 'as_is',
    label: 'Is the vehicle sold "as-is"?',
    type: 'select',
    required: true,
    options: [
      { value: 'yes', label: 'Yes' },
      { value: 'no', label: 'No, with warranties' },
    ],
    tooltip: 'Whether the vehicle is sold without warranties.',
  },
  {
    id: 'warranty_details',
    label: 'Warranty Details (if not as-is)',
    type: 'textarea',
    required: false,
    placeholder: 'e.g., 30-day warranty on drivetrain',
    tooltip: 'Describe any warranties provided.',
  },
];
