// src/lib/documents/us/timber-sale-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const timberSaleAgreementQuestions: FormQuestion[] = [
  {
    id: 'landownerName',
    type: 'text',
    label: 'Landowner Name',
    placeholder: 'Enter property owner name',
    required: true,
    group: 'landowner',
  },
  {
    id: 'buyerName',
    type: 'text',
    label: 'Buyer Name',
    placeholder: 'Enter timber buyer/logger name',
    required: true,
    group: 'buyer',
  },
  {
    id: 'propertyDescription',
    type: 'textarea',
    label: 'Property Description',
    placeholder: 'Describe the forested property',
    required: false,
    group: 'property',
  },
  {
    id: 'acres',
    type: 'text',
    label: 'Total Property Acres',
    placeholder: 'Enter total property size',
    required: false,
    group: 'property',
  },
  {
    id: 'timberAcres',
    type: 'text',
    label: 'Timber Harvest Acres',
    placeholder: 'Enter acres to be harvested',
    required: false,
    group: 'property',
  },
  {
    id: 'timberTypes',
    type: 'multi-select',
    label: 'Timber Types',
    options: [
      { value: 'pine', label: 'Pine' },
      { value: 'oak', label: 'Oak' },
      { value: 'maple', label: 'Maple' },
      { value: 'cedar', label: 'Cedar' },
      { value: 'fir', label: 'Fir' },
      { value: 'poplar', label: 'Poplar' },
      { value: 'walnut', label: 'Walnut' },
      { value: 'cherry', label: 'Cherry' },
      { value: 'ash', label: 'Ash' },
      { value: 'hickory', label: 'Hickory' },
      { value: 'mixed-hardwood', label: 'Mixed Hardwood' },
      { value: 'mixed-softwood', label: 'Mixed Softwood' },
    ],
    required: false,
    group: 'timber',
  },
  {
    id: 'estimatedVolume',
    type: 'text',
    label: 'Estimated Volume',
    placeholder: 'Enter estimated timber volume',
    required: false,
    group: 'timber',
  },
  {
    id: 'volumeUnit',
    type: 'select',
    label: 'Volume Unit',
    options: [
      { value: 'board-feet', label: 'Board Feet' },
      { value: 'cords', label: 'Cords' },
      { value: 'tons', label: 'Tons' },
      { value: 'cubic-feet', label: 'Cubic Feet' },
    ],
    required: false,
    group: 'timber',
  },
  {
    id: 'saleType',
    type: 'select',
    label: 'Sale Type',
    options: [
      { value: 'lump-sum', label: 'Lump Sum' },
      { value: 'per-unit', label: 'Per Unit' },
      { value: 'percentage', label: 'Percentage' },
    ],
    required: false,
    group: 'sale',
  },
  {
    id: 'totalSalePrice',
    type: 'text',
    label: 'Total Sale Price',
    placeholder: 'Enter total purchase price',
    required: false,
    group: 'sale',
  },
  {
    id: 'harvestingMethod',
    type: 'select',
    label: 'Harvesting Method',
    options: [
      { value: 'selective-cutting', label: 'Selective Cutting' },
      { value: 'clear-cutting', label: 'Clear Cutting' },
      { value: 'shelterwood', label: 'Shelterwood' },
      { value: 'seed-tree', label: 'Seed Tree' },
    ],
    required: false,
    group: 'harvesting',
  },
  {
    id: 'harvestingPeriod',
    type: 'text',
    label: 'Harvesting Period',
    placeholder: 'Enter time allowed for harvesting',
    required: false,
    group: 'harvesting',
  },
  {
    id: 'roadConstruction',
    type: 'boolean',
    label: 'Road construction required?',
    required: false,
    group: 'access',
  },
  {
    id: 'liabilityAmount',
    type: 'text',
    label: 'Required Insurance Amount',
    placeholder: 'Enter minimum insurance coverage',
    required: false,
    group: 'insurance',
  },
];
