// src/lib/documents/us/loan-modification-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const loanModificationAgreementQuestions: FormQuestion[] = [
  {
    id: 'originalLoanDate',
    type: 'date',
    label: 'Original Loan Date',
    required: true,
    group: 'original-loan',
  },
  {
    id: 'originalLoanAmount',
    type: 'text',
    label: 'Original Loan Amount',
    placeholder: 'Enter original loan amount',
    required: true,
    group: 'original-loan',
  },
  {
    id: 'originalInterestRate',
    type: 'text',
    label: 'Original Interest Rate',
    placeholder: 'e.g., 6.5% per year',
    required: true,
    group: 'original-loan',
  },
  {
    id: 'currentBalance',
    type: 'text',
    label: 'Current Outstanding Balance',
    placeholder: 'Current amount owed on loan',
    required: true,
    group: 'original-loan',
  },
  {
    id: 'lenderName',
    type: 'text',
    label: 'Lender Name',
    placeholder: 'Enter lender name',
    required: true,
    group: 'lender',
  },
  {
    id: 'lenderAddress',
    type: 'text',
    label: 'Lender Address',
    placeholder: 'Enter complete lender address',
    required: true,
    group: 'lender',
  },
  {
    id: 'borrowerName',
    type: 'text',
    label: 'Borrower Name',
    placeholder: 'Enter borrower name',
    required: true,
    group: 'borrower',
  },
  {
    id: 'borrowerAddress',
    type: 'text',
    label: 'Borrower Address',
    placeholder: 'Enter complete borrower address',
    required: true,
    group: 'borrower',
  },
  {
    id: 'modificationDate',
    type: 'date',
    label: 'Modification Agreement Date',
    required: true,
    group: 'modification-details',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Modification Effective Date',
    required: true,
    group: 'modification-details',
  },
  {
    id: 'modifyPaymentAmount',
    type: 'checkbox',
    label: 'Modify payment amount',
    required: false,
    group: 'payment-changes',
  },
  {
    id: 'newPaymentAmount',
    type: 'text',
    label: 'New Payment Amount',
    placeholder: 'Enter new payment amount',
    required: false,
    group: 'payment-changes',
    dependsOn: 'modifyPaymentAmount',
  },
  {
    id: 'modifyPaymentSchedule',
    type: 'checkbox',
    label: 'Modify payment schedule',
    required: false,
    group: 'payment-changes',
  },
  {
    id: 'newPaymentFrequency',
    type: 'select',
    label: 'New Payment Frequency',
    options: [
      { value: 'weekly', label: 'Weekly' },
      { value: 'bi-weekly', label: 'Bi-weekly' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
    ],
    required: false,
    group: 'payment-changes',
    dependsOn: 'modifyPaymentSchedule',
  },
  {
    id: 'modifyInterestRate',
    type: 'checkbox',
    label: 'Modify interest rate',
    required: false,
    group: 'interest-changes',
  },
  {
    id: 'newInterestRate',
    type: 'text',
    label: 'New Interest Rate',
    placeholder: 'e.g., 4.5% per year',
    required: false,
    group: 'interest-changes',
    dependsOn: 'modifyInterestRate',
  },
  {
    id: 'newInterestType',
    type: 'select',
    label: 'New Interest Type',
    options: [
      { value: 'fixed', label: 'Fixed Rate' },
      { value: 'variable', label: 'Variable Rate' },
    ],
    required: false,
    group: 'interest-changes',
    dependsOn: 'modifyInterestRate',
  },
  {
    id: 'modifyLoanTerm',
    type: 'checkbox',
    label: 'Modify loan term',
    required: false,
    group: 'term-changes',
  },
  {
    id: 'newMaturityDate',
    type: 'date',
    label: 'New Maturity Date',
    required: false,
    group: 'term-changes',
    dependsOn: 'modifyLoanTerm',
  },
  {
    id: 'extendTerm',
    type: 'checkbox',
    label: 'Extend loan term',
    required: false,
    group: 'term-changes',
  },
  {
    id: 'termExtension',
    type: 'text',
    label: 'Term Extension Period',
    placeholder: 'e.g., 2 years',
    required: false,
    group: 'term-changes',
    dependsOn: 'extendTerm',
  },
  {
    id: 'modifyPrincipal',
    type: 'checkbox',
    label: 'Modify principal amount',
    required: false,
    group: 'principal-changes',
  },
  {
    id: 'principalReduction',
    type: 'text',
    label: 'Principal Reduction Amount',
    placeholder: 'Amount to reduce principal',
    required: false,
    group: 'principal-changes',
    dependsOn: 'modifyPrincipal',
  },
  {
    id: 'principalIncrease',
    type: 'text',
    label: 'Principal Increase Amount',
    placeholder: 'Amount to increase principal',
    required: false,
    group: 'principal-changes',
    dependsOn: 'modifyPrincipal',
  },
  {
    id: 'principalForgiveness',
    type: 'text',
    label: 'Principal Forgiveness Amount',
    placeholder: 'Amount of principal to forgive',
    required: false,
    group: 'principal-changes',
    dependsOn: 'modifyPrincipal',
  },
  {
    id: 'includePaymentDeferral',
    type: 'checkbox',
    label: 'Include payment deferral',
    required: false,
    group: 'deferral',
  },
  {
    id: 'deferralPeriod',
    type: 'text',
    label: 'Deferral Period',
    placeholder: 'e.g., 6 months',
    required: false,
    group: 'deferral',
    dependsOn: 'includePaymentDeferral',
  },
  {
    id: 'deferredAmount',
    type: 'text',
    label: 'Deferred Payment Amount',
    placeholder: 'Amount of payments to defer',
    required: false,
    group: 'deferral',
    dependsOn: 'includePaymentDeferral',
  },
  {
    id: 'includeForbearance',
    type: 'checkbox',
    label: 'Include forbearance agreement',
    required: false,
    group: 'forbearance',
  },
  {
    id: 'forbearancePeriod',
    type: 'text',
    label: 'Forbearance Period',
    placeholder: 'e.g., 3 months',
    required: false,
    group: 'forbearance',
    dependsOn: 'includeForbearance',
  },
  {
    id: 'forbearanceTerms',
    type: 'textarea',
    label: 'Forbearance Terms',
    placeholder: 'Describe forbearance conditions',
    required: false,
    group: 'forbearance',
    dependsOn: 'includeForbearance',
  },
  {
    id: 'modifyLateFees',
    type: 'checkbox',
    label: 'Modify late fee structure',
    required: false,
    group: 'late-fees',
  },
  {
    id: 'waiveExistingLateFees',
    type: 'checkbox',
    label: 'Waive existing late fees',
    required: false,
    group: 'late-fees',
  },
  {
    id: 'newLateFeeStructure',
    type: 'text',
    label: 'New Late Fee Structure',
    placeholder: 'Describe new late fee terms',
    required: false,
    group: 'late-fees',
    dependsOn: 'modifyLateFees',
  },
  {
    id: 'cureExistingDefault',
    type: 'checkbox',
    label: 'Cure existing default',
    required: false,
    group: 'default-cure',
  },
  {
    id: 'defaultAmount',
    type: 'text',
    label: 'Default Amount',
    placeholder: 'Amount in default',
    required: false,
    group: 'default-cure',
    dependsOn: 'cureExistingDefault',
  },
  {
    id: 'cureConditions',
    type: 'textarea',
    label: 'Conditions to Cure Default',
    placeholder: 'Describe conditions for curing default',
    required: false,
    group: 'default-cure',
    dependsOn: 'cureExistingDefault',
  },
  {
    id: 'modifyCollateral',
    type: 'checkbox',
    label: 'Modify collateral',
    required: false,
    group: 'collateral',
  },
  {
    id: 'addCollateral',
    type: 'textarea',
    label: 'Additional Collateral',
    placeholder: 'Describe additional collateral',
    required: false,
    group: 'collateral',
    dependsOn: 'modifyCollateral',
  },
  {
    id: 'releaseCollateral',
    type: 'textarea',
    label: 'Released Collateral',
    placeholder: 'Describe collateral to be released',
    required: false,
    group: 'collateral',
    dependsOn: 'modifyCollateral',
  },
  {
    id: 'capitalizeInterest',
    type: 'checkbox',
    label: 'Capitalize accrued interest',
    required: false,
    group: 'additional-terms',
  },
  {
    id: 'capitalizedAmount',
    type: 'text',
    label: 'Amount to Capitalize',
    placeholder: 'Amount of interest to capitalize',
    required: false,
    group: 'additional-terms',
    dependsOn: 'capitalizeInterest',
  },
  {
    id: 'waivePrepaymentPenalty',
    type: 'checkbox',
    label: 'Waive prepayment penalty',
    required: false,
    group: 'additional-terms',
  },
  {
    id: 'currentOnOtherDebts',
    type: 'checkbox',
    label: 'Borrower is current on other debts',
    required: false,
    group: 'representations',
  },
  {
    id: 'noMaterialChange',
    type: 'checkbox',
    label: 'No material adverse change in financial condition',
    required: false,
    group: 'representations',
  },
  {
    id: 'authorizedToModify',
    type: 'checkbox',
    label: 'Borrower authorized to enter modification',
    required: false,
    group: 'representations',
  },
  {
    id: 'remainInCompliance',
    type: 'checkbox',
    label: 'Remain in compliance with all terms',
    required: false,
    group: 'compliance',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law (State)',
    placeholder: 'e.g., State of California',
    required: false,
    group: 'legal',
  },
  {
    id: 'attorneyFees',
    type: 'checkbox',
    label: 'Include attorney fees clause',
    required: false,
    group: 'legal',
  },
  {
    id: 'recordModification',
    type: 'checkbox',
    label: 'Record modification agreement',
    required: false,
    group: 'recording',
  },
  {
    id: 'ratifyOriginalLoan',
    type: 'checkbox',
    label: 'Ratify and confirm original loan',
    required: false,
    group: 'ratification',
  },
  {
    id: 'confirmSecurityInterest',
    type: 'checkbox',
    label: 'Confirm existing security interests',
    required: false,
    group: 'ratification',
  },
  {
    id: 'requireNotarization',
    type: 'checkbox',
    label: 'Require notarization',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireBorrowerSignature',
    type: 'checkbox',
    label: 'Require borrower signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireLenderSignature',
    type: 'checkbox',
    label: 'Require lender signature',
    required: false,
    group: 'signatures',
  },
];
