// src/lib/documents/us/product-liability-waiver/questions.ts
import type { FormQuestion } from '@/types/documents';

export const productLiabilityWaiverQuestions: FormQuestion[] = [
  {
    id: 'companyName',
    type: 'text',
    label: 'Company Name',
    placeholder: 'Enter company or business name',
    required: true,
    group: 'company',
  },
  {
    id: 'companyAddress',
    type: 'text',
    label: 'Company Address',
    placeholder: 'Enter complete company address',
    required: true,
    group: 'company',
  },
  {
    id: 'companyPhone',
    type: 'text',
    label: 'Company Phone',
    placeholder: 'Enter phone number',
    required: false,
    group: 'company',
  },
  {
    id: 'companyEmail',
    type: 'email',
    label: 'Company Email',
    placeholder: 'Enter email address',
    required: false,
    group: 'company',
  },
  {
    id: 'companyType',
    type: 'select',
    label: 'Company Type',
    options: [
      { value: 'manufacturer', label: 'Manufacturer' },
      { value: 'retailer', label: 'Retailer' },
      { value: 'distributor', label: 'Distributor' },
      { value: 'wholesaler', label: 'Wholesaler' },
    ],
    required: true,
    group: 'company',
  },
  {
    id: 'productName',
    type: 'text',
    label: 'Product Name',
    placeholder: 'Enter product name or brand',
    required: true,
    group: 'product',
  },
  {
    id: 'productModel',
    type: 'text',
    label: 'Product Model',
    placeholder: 'Enter model number or name',
    required: false,
    group: 'product',
  },
  {
    id: 'productCategory',
    type: 'text',
    label: 'Product Category',
    placeholder: 'e.g., Electronics, Appliances, Tools',
    required: true,
    group: 'product',
  },
  {
    id: 'productDescription',
    type: 'textarea',
    label: 'Product Description',
    placeholder: 'Detailed description of the product',
    required: true,
    group: 'product',
  },
  {
    id: 'serialNumber',
    type: 'text',
    label: 'Serial Number',
    placeholder: 'Enter serial number if applicable',
    required: false,
    group: 'product',
  },
  {
    id: 'manufacturingDate',
    type: 'text',
    label: 'Manufacturing Date',
    placeholder: 'Date or date range of manufacturing',
    required: false,
    group: 'product',
  },
  {
    id: 'productType',
    type: 'select',
    label: 'Product Type',
    options: [
      { value: 'consumer-goods', label: 'Consumer Goods' },
      { value: 'industrial-equipment', label: 'Industrial Equipment' },
      { value: 'medical-device', label: 'Medical Device' },
      { value: 'automotive', label: 'Automotive' },
      { value: 'electronics', label: 'Electronics' },
      { value: 'food-beverage', label: 'Food & Beverage' },
      { value: 'pharmaceutical', label: 'Pharmaceutical' },
      { value: 'cosmetic', label: 'Cosmetic' },
      { value: 'toy', label: 'Toy' },
      { value: 'sporting-goods', label: 'Sporting Goods' },
      { value: 'tools', label: 'Tools' },
      { value: 'appliance', label: 'Appliance' },
      { value: 'furniture', label: 'Furniture' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'product',
  },
  {
    id: 'collectCustomerName',
    type: 'checkbox',
    label: 'Collect customer name',
    required: false,
    group: 'customer-data',
  },
  {
    id: 'collectCustomerAddress',
    type: 'checkbox',
    label: 'Collect customer address',
    required: false,
    group: 'customer-data',
  },
  {
    id: 'collectCustomerPhone',
    type: 'checkbox',
    label: 'Collect customer phone',
    required: false,
    group: 'customer-data',
  },
  {
    id: 'collectCustomerEmail',
    type: 'checkbox',
    label: 'Collect customer email',
    required: false,
    group: 'customer-data',
  },
  {
    id: 'collectPurchaseDate',
    type: 'checkbox',
    label: 'Collect purchase date',
    required: false,
    group: 'customer-data',
  },
  {
    id: 'collectPurchaseLocation',
    type: 'checkbox',
    label: 'Collect purchase location',
    required: false,
    group: 'customer-data',
  },
  {
    id: 'intendedUse',
    type: 'textarea',
    label: 'Intended Use',
    placeholder: 'Describe the intended use of the product',
    required: true,
    group: 'usage',
  },
  {
    id: 'properUseInstructions',
    type: 'checkbox',
    label: 'Proper use instructions provided',
    required: false,
    group: 'usage',
  },
  {
    id: 'safetyWarnings',
    type: 'checkbox',
    label: 'Safety warnings provided',
    required: false,
    group: 'usage',
  },
  {
    id: 'maintenanceRequirements',
    type: 'checkbox',
    label: 'Maintenance requirements specified',
    required: false,
    group: 'usage',
  },
  {
    id: 'ageRestrictions',
    type: 'text',
    label: 'Age Restrictions',
    placeholder: 'e.g., 18 years and older',
    required: false,
    group: 'usage',
  },
  {
    id: 'skillRequirements',
    type: 'text',
    label: 'Skill Requirements',
    placeholder: 'Required skills or experience',
    required: false,
    group: 'usage',
  },
  {
    id: 'inherentRisks',
    type: 'multiselect',
    label: 'Inherent Risks',
    options: [
      { value: 'mechanical-failure', label: 'Mechanical Failure' },
      { value: 'electrical-shock', label: 'Electrical Shock' },
      { value: 'sharp-edges', label: 'Sharp Edges' },
      { value: 'chemical-exposure', label: 'Chemical Exposure' },
      { value: 'fire-burn', label: 'Fire/Burn Risk' },
      { value: 'moving-parts', label: 'Moving Parts' },
      { value: 'pressure-release', label: 'Pressure Release' },
      { value: 'toxic-materials', label: 'Toxic Materials' },
    ],
    required: false,
    group: 'risks',
  },
  {
    id: 'specificHazards',
    type: 'textarea',
    label: 'Specific Hazards',
    placeholder: 'Describe specific hazards associated with this product',
    required: false,
    group: 'risks',
  },
  {
    id: 'potentialInjuries',
    type: 'multiselect',
    label: 'Potential Injuries',
    options: [
      { value: 'cuts-lacerations', label: 'Cuts/Lacerations' },
      { value: 'burns', label: 'Burns' },
      { value: 'electrical-injury', label: 'Electrical Injury' },
      { value: 'chemical-burns', label: 'Chemical Burns' },
      { value: 'eye-injury', label: 'Eye Injury' },
      { value: 'respiratory-injury', label: 'Respiratory Injury' },
      { value: 'crushing-injury', label: 'Crushing Injury' },
      { value: 'poisoning', label: 'Poisoning' },
    ],
    required: false,
    group: 'risks',
  },
  {
    id: 'environmentalRisks',
    type: 'textarea',
    label: 'Environmental Risks',
    placeholder: 'Describe environmental risks or considerations',
    required: false,
    group: 'risks',
  },
  {
    id: 'materialSafetyRisks',
    type: 'checkbox',
    label: 'Product contains hazardous materials',
    required: false,
    group: 'risks',
  },
  {
    id: 'riskLevel',
    type: 'select',
    label: 'Overall Risk Level',
    options: [
      { value: 'low', label: 'Low Risk' },
      { value: 'medium', label: 'Medium Risk' },
      { value: 'high', label: 'High Risk' },
    ],
    required: true,
    group: 'risks',
  },
  {
    id: 'waiverScope',
    type: 'select',
    label: 'Waiver Scope',
    options: [
      { value: 'manufacturing-defects', label: 'Manufacturing Defects Only' },
      { value: 'design-defects', label: 'Design Defects Only' },
      { value: 'warning-defects', label: 'Warning Defects Only' },
      { value: 'all-defects', label: 'All Defects' },
    ],
    required: true,
    group: 'waiver-scope',
  },
  {
    id: 'includeManufacturingClaims',
    type: 'checkbox',
    label: 'Include manufacturing defect claims',
    required: false,
    group: 'waiver-scope',
  },
  {
    id: 'includeDesignClaims',
    type: 'checkbox',
    label: 'Include design defect claims',
    required: false,
    group: 'waiver-scope',
  },
  {
    id: 'includeWarningClaims',
    type: 'checkbox',
    label: 'Include warning defect claims',
    required: false,
    group: 'waiver-scope',
  },
  {
    id: 'includeNegligenceClaims',
    type: 'checkbox',
    label: 'Include negligence claims',
    required: false,
    group: 'waiver-scope',
  },
  {
    id: 'includeStrictLiabilityClaims',
    type: 'checkbox',
    label: 'Include strict liability claims',
    required: false,
    group: 'waiver-scope',
  },
  {
    id: 'includeBreachOfWarrantyClaims',
    type: 'checkbox',
    label: 'Include breach of warranty claims',
    required: false,
    group: 'waiver-scope',
  },
  {
    id: 'releasedParties',
    type: 'multiselect',
    label: 'Additional Released Parties',
    options: [
      { value: 'parent-company', label: 'Parent Company' },
      { value: 'subsidiaries', label: 'Subsidiaries' },
      { value: 'affiliates', label: 'Affiliates' },
      { value: 'licensors', label: 'Licensors' },
      { value: 'contractors', label: 'Contractors' },
      { value: 'consultants', label: 'Consultants' },
    ],
    required: false,
    group: 'released-parties',
  },
  {
    id: 'includeManufacturer',
    type: 'checkbox',
    label: 'Include manufacturer',
    required: false,
    group: 'released-parties',
  },
  {
    id: 'includeRetailer',
    type: 'checkbox',
    label: 'Include retailer',
    required: false,
    group: 'released-parties',
  },
  {
    id: 'includeDistributor',
    type: 'checkbox',
    label: 'Include distributor',
    required: false,
    group: 'released-parties',
  },
  {
    id: 'includeSuppliers',
    type: 'checkbox',
    label: 'Include suppliers',
    required: false,
    group: 'released-parties',
  },
  {
    id: 'includeComponentManufacturers',
    type: 'checkbox',
    label: 'Include component manufacturers',
    required: false,
    group: 'released-parties',
  },
  {
    id: 'includeOfficersDirectors',
    type: 'checkbox',
    label: 'Include officers and directors',
    required: false,
    group: 'released-parties',
  },
  {
    id: 'includeEmployees',
    type: 'checkbox',
    label: 'Include employees',
    required: false,
    group: 'released-parties',
  },
  {
    id: 'personalInjuryClaims',
    type: 'checkbox',
    label: 'Release personal injury claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'propertyDamageClaims',
    type: 'checkbox',
    label: 'Release property damage claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'economicLossClaims',
    type: 'checkbox',
    label: 'Release economic loss claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'consequentialDamages',
    type: 'checkbox',
    label: 'Release consequential damages',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'incidentalDamages',
    type: 'checkbox',
    label: 'Release incidental damages',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'punitiveDamages',
    type: 'checkbox',
    label: 'Release punitive damages',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'wrongfulDeathClaims',
    type: 'checkbox',
    label: 'Release wrongful death claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'warningsProvided',
    type: 'checkbox',
    label: 'Product warnings provided',
    required: false,
    group: 'warnings-instructions',
  },
  {
    id: 'instructionsProvided',
    type: 'checkbox',
    label: 'Instructions provided',
    required: false,
    group: 'warnings-instructions',
  },
  {
    id: 'safetyLabelsProvided',
    type: 'checkbox',
    label: 'Safety labels provided',
    required: false,
    group: 'warnings-instructions',
  },
  {
    id: 'userManualProvided',
    type: 'checkbox',
    label: 'User manual provided',
    required: false,
    group: 'warnings-instructions',
  },
  {
    id: 'trainingProvided',
    type: 'checkbox',
    label: 'Training provided',
    required: false,
    group: 'warnings-instructions',
  },
  {
    id: 'demonstrationProvided',
    type: 'checkbox',
    label: 'Demonstration provided',
    required: false,
    group: 'warnings-instructions',
  },
  {
    id: 'properUseAcknowledgment',
    type: 'checkbox',
    label: 'User acknowledges proper use',
    required: false,
    group: 'user-responsibilities',
  },
  {
    id: 'followInstructionsAcknowledgment',
    type: 'checkbox',
    label: 'User agrees to follow instructions',
    required: false,
    group: 'user-responsibilities',
  },
  {
    id: 'maintenanceResponsibility',
    type: 'checkbox',
    label: 'User responsible for maintenance',
    required: false,
    group: 'user-responsibilities',
  },
  {
    id: 'inspectionResponsibility',
    type: 'checkbox',
    label: 'User responsible for inspection',
    required: false,
    group: 'user-responsibilities',
  },
  {
    id: 'storageResponsibility',
    type: 'checkbox',
    label: 'User responsible for proper storage',
    required: false,
    group: 'user-responsibilities',
  },
  {
    id: 'disposalResponsibility',
    type: 'checkbox',
    label: 'User responsible for proper disposal',
    required: false,
    group: 'user-responsibilities',
  },
  {
    id: 'noModificationClause',
    type: 'checkbox',
    label: 'Prohibit product modification',
    required: false,
    group: 'modifications',
  },
  {
    id: 'noAlterationClause',
    type: 'checkbox',
    label: 'Prohibit product alteration',
    required: false,
    group: 'modifications',
  },
  {
    id: 'voidsWarrantyClause',
    type: 'checkbox',
    label: 'Modifications void warranty',
    required: false,
    group: 'modifications',
  },
  {
    id: 'thirdPartyModifications',
    type: 'checkbox',
    label: 'Prohibit third-party modifications',
    required: false,
    group: 'modifications',
  },
  {
    id: 'minimumAge',
    type: 'text',
    label: 'Minimum Age Requirement',
    placeholder: 'e.g., 18 years old',
    required: false,
    group: 'age-capacity',
  },
  {
    id: 'parentalConsent',
    type: 'checkbox',
    label: 'Require parental consent for minors',
    required: false,
    group: 'age-capacity',
  },
  {
    id: 'guardianSupervision',
    type: 'checkbox',
    label: 'Require guardian supervision',
    required: false,
    group: 'age-capacity',
  },
  {
    id: 'competencyRequirement',
    type: 'checkbox',
    label: 'Require legal competency',
    required: false,
    group: 'age-capacity',
  },
  {
    id: 'physicalCapabilityWarning',
    type: 'checkbox',
    label: 'Include physical capability warning',
    required: false,
    group: 'medical-warnings',
  },
  {
    id: 'medicalConditionWarning',
    type: 'checkbox',
    label: 'Include medical condition warning',
    required: false,
    group: 'medical-warnings',
  },
  {
    id: 'pregnancyWarning',
    type: 'checkbox',
    label: 'Include pregnancy warning',
    required: false,
    group: 'medical-warnings',
  },
  {
    id: 'medicationWarning',
    type: 'checkbox',
    label: 'Include medication warning',
    required: false,
    group: 'medical-warnings',
  },
  {
    id: 'allergiesWarning',
    type: 'checkbox',
    label: 'Include allergies warning',
    required: false,
    group: 'medical-warnings',
  },
  {
    id: 'qualityTestingCompleted',
    type: 'checkbox',
    label: 'Quality testing completed',
    required: false,
    group: 'testing-quality',
  },
  {
    id: 'safetyTestingCompleted',
    type: 'checkbox',
    label: 'Safety testing completed',
    required: false,
    group: 'testing-quality',
  },
  {
    id: 'industryStandardsCompliance',
    type: 'checkbox',
    label: 'Complies with industry standards',
    required: false,
    group: 'testing-quality',
  },
  {
    id: 'governmentRegulationsCompliance',
    type: 'checkbox',
    label: 'Complies with government regulations',
    required: false,
    group: 'testing-quality',
  },
  {
    id: 'certificationProvided',
    type: 'checkbox',
    label: 'Certification provided',
    required: false,
    group: 'testing-quality',
  },
  {
    id: 'warrantyDisclaimer',
    type: 'checkbox',
    label: 'Include warranty disclaimer',
    required: false,
    group: 'warranties',
  },
  {
    id: 'expressWarrantyLimitation',
    type: 'checkbox',
    label: 'Limit express warranties',
    required: false,
    group: 'warranties',
  },
  {
    id: 'impliedWarrantyDisclaimer',
    type: 'checkbox',
    label: 'Disclaim implied warranties',
    required: false,
    group: 'warranties',
  },
  {
    id: 'merchantabilityDisclaimer',
    type: 'checkbox',
    label: 'Disclaim merchantability warranty',
    required: false,
    group: 'warranties',
  },
  {
    id: 'fitnessForPurposeDisclaimer',
    type: 'checkbox',
    label: 'Disclaim fitness for purpose warranty',
    required: false,
    group: 'warranties',
  },
  {
    id: 'liabilityLimitation',
    type: 'checkbox',
    label: 'Include liability limitation',
    required: false,
    group: 'liability-limits',
  },
  {
    id: 'damageLimitation',
    type: 'select',
    label: 'Damage Limitation Method',
    options: [
      { value: 'purchase-price', label: 'Purchase Price' },
      { value: 'repair-cost', label: 'Repair Cost' },
      { value: 'replacement-cost', label: 'Replacement Cost' },
      { value: 'specific-amount', label: 'Specific Amount' },
    ],
    required: false,
    group: 'liability-limits',
    dependsOn: 'liabilityLimitation',
  },
  {
    id: 'limitationAmount',
    type: 'text',
    label: 'Limitation Amount',
    placeholder: 'Enter specific dollar amount',
    required: false,
    group: 'liability-limits',
    dependsOn: 'damageLimitation',
  },
  {
    id: 'noConsequentialDamages',
    type: 'checkbox',
    label: 'Exclude consequential damages',
    required: false,
    group: 'liability-limits',
  },
  {
    id: 'noIncidentalDamages',
    type: 'checkbox',
    label: 'Exclude incidental damages',
    required: false,
    group: 'liability-limits',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'e.g., State of California',
    required: false,
    group: 'legal',
  },
  {
    id: 'jurisdiction',
    type: 'text',
    label: 'Jurisdiction',
    placeholder: 'Where disputes will be resolved',
    required: false,
    group: 'legal',
  },
  {
    id: 'venue',
    type: 'text',
    label: 'Venue',
    placeholder: 'Specific court or location',
    required: false,
    group: 'legal',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'litigation', label: 'Court Litigation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'mediation', label: 'Mediation' },
    ],
    required: false,
    group: 'legal',
  },
  {
    id: 'requireCustomerSignature',
    type: 'checkbox',
    label: 'Require customer signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireParentGuardianSignature',
    type: 'checkbox',
    label: 'Require parent/guardian signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireWitnessSignature',
    type: 'checkbox',
    label: 'Require witness signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireNotarization',
    type: 'checkbox',
    label: 'Require notarization',
    required: false,
    group: 'signatures',
  },
  {
    id: 'electronicSignatureAccepted',
    type: 'checkbox',
    label: 'Accept electronic signatures',
    required: false,
    group: 'signatures',
  },
];