// src/lib/documents/us/commission-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const commissionAgreementQuestions: FormQuestion[] = [
  {
    id: 'companyName',
    type: 'text',
    label: 'Company Name',
    placeholder: 'Enter company name',
    required: true,
    group: 'company',
  },
  {
    id: 'companyAddress',
    type: 'text',
    label: 'Company Address',
    placeholder: 'Enter complete company address',
    required: true,
    group: 'company',
  },
  {
    id: 'employeeName',
    type: 'text',
    label: 'Employee/Salesperson Name',
    placeholder: 'Enter employee full name',
    required: true,
    group: 'employee',
  },
  {
    id: 'employeeAddress',
    type: 'text',
    label: 'Employee Address',
    placeholder: 'Enter employee address',
    required: true,
    group: 'employee',
  },
  {
    id: 'jobTitle',
    type: 'text',
    label: 'Job Title',
    placeholder: 'e.g., Sales Representative, Account Manager',
    required: true,
    group: 'employee',
  },
  {
    id: 'agreementDate',
    type: 'date',
    label: 'Agreement Date',
    required: true,
    group: 'dates',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Effective Date',
    required: true,
    group: 'dates',
  },
  {
    id: 'endDate',
    type: 'date',
    label: 'End Date (if applicable)',
    required: false,
    group: 'dates',
  },
  {
    id: 'commissionType',
    type: 'select',
    label: 'Commission Structure Type',
    options: [
      { value: 'percentage', label: 'Percentage of Sales' },
      { value: 'flat-rate', label: 'Flat Rate per Sale' },
      { value: 'tiered', label: 'Tiered Commission' },
      { value: 'sliding-scale', label: 'Sliding Scale' },
    ],
    required: true,
    group: 'commission',
  },
  {
    id: 'commissionRate',
    type: 'text',
    label: 'Commission Rate',
    placeholder: 'e.g., 5%, $100 per sale, etc.',
    required: true,
    group: 'commission',
  },
  {
    id: 'minimumSale',
    type: 'text',
    label: 'Minimum Sale Amount (if applicable)',
    placeholder: 'Minimum sale amount to earn commission',
    required: false,
    group: 'commission',
  },
  {
    id: 'maximumCommission',
    type: 'text',
    label: 'Maximum Commission Cap (if applicable)',
    placeholder: 'Maximum commission per sale/period',
    required: false,
    group: 'commission',
  },
  {
    id: 'includeBaseSalary',
    type: 'checkbox',
    label: 'Include base salary',
    required: false,
    group: 'salary',
  },
  {
    id: 'baseSalaryAmount',
    type: 'text',
    label: 'Base Salary Amount',
    placeholder: 'Annual base salary amount',
    required: false,
    group: 'salary',
    dependsOn: 'includeBaseSalary',
  },
  {
    id: 'salaryFrequency',
    type: 'select',
    label: 'Salary Payment Frequency',
    options: [
      { value: 'weekly', label: 'Weekly' },
      { value: 'bi-weekly', label: 'Bi-weekly' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'annually', label: 'Annually' },
    ],
    required: false,
    group: 'salary',
    dependsOn: 'includeBaseSalary',
  },
  {
    id: 'commissionBase',
    type: 'select',
    label: 'Commission Calculated On',
    options: [
      { value: 'gross-sales', label: 'Gross Sales' },
      { value: 'net-sales', label: 'Net Sales' },
      { value: 'gross-profit', label: 'Gross Profit' },
      { value: 'net-profit', label: 'Net Profit' },
    ],
    required: true,
    group: 'calculation',
  },
  {
    id: 'deductionsAllowed',
    type: 'checkbox',
    label: 'Allow deductions from commission base',
    required: false,
    group: 'calculation',
  },
  {
    id: 'hasTerritory',
    type: 'checkbox',
    label: 'Assign specific sales territory',
    required: false,
    group: 'territory',
  },
  {
    id: 'territoryDescription',
    type: 'textarea',
    label: 'Territory Description',
    placeholder: 'Describe the assigned sales territory',
    required: false,
    group: 'territory',
    dependsOn: 'hasTerritory',
  },
  {
    id: 'exclusiveTerritory',
    type: 'checkbox',
    label: 'Exclusive territory rights',
    required: false,
    group: 'territory',
    dependsOn: 'hasTerritory',
  },
  {
    id: 'allProducts',
    type: 'checkbox',
    label: 'Commission applies to all products/services',
    required: false,
    group: 'products',
  },
  {
    id: 'paymentFrequency',
    type: 'select',
    label: 'Commission Payment Frequency',
    options: [
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
      { value: 'upon-collection', label: 'Upon Payment Collection' },
      { value: 'upon-sale', label: 'Upon Sale Completion' },
    ],
    required: true,
    group: 'payment',
  },
  {
    id: 'paymentDate',
    type: 'text',
    label: 'Payment Date',
    placeholder: 'e.g., 15th of each month',
    required: false,
    group: 'payment',
  },
  {
    id: 'advanceCommissions',
    type: 'checkbox',
    label: 'Allow advance commission payments',
    required: false,
    group: 'payment',
  },
  {
    id: 'chargebacks',
    type: 'checkbox',
    label: 'Include chargeback provisions',
    required: false,
    group: 'payment',
  },
  {
    id: 'salesQuota',
    type: 'checkbox',
    label: 'Establish sales quota requirements',
    required: false,
    group: 'performance',
  },
  {
    id: 'quotaAmount',
    type: 'text',
    label: 'Sales Quota Amount',
    placeholder: 'Required sales amount per period',
    required: false,
    group: 'performance',
    dependsOn: 'salesQuota',
  },
  {
    id: 'quotaPeriod',
    type: 'select',
    label: 'Quota Period',
    options: [
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
      { value: 'annually', label: 'Annually' },
    ],
    required: false,
    group: 'performance',
    dependsOn: 'salesQuota',
  },
  {
    id: 'expenseReimbursement',
    type: 'checkbox',
    label: 'Provide expense reimbursement',
    required: false,
    group: 'expenses',
  },
  {
    id: 'expenseApprovalRequired',
    type: 'checkbox',
    label: 'Require expense pre-approval',
    required: false,
    group: 'expenses',
    dependsOn: 'expenseReimbursement',
  },
  {
    id: 'nonCompeteClause',
    type: 'checkbox',
    label: 'Include non-compete clause',
    required: false,
    group: 'restrictions',
  },
  {
    id: 'nonCompetePeriod',
    type: 'text',
    label: 'Non-compete Period',
    placeholder: 'e.g., 6 months after termination',
    required: false,
    group: 'restrictions',
    dependsOn: 'nonCompeteClause',
  },
  {
    id: 'nonSolicitationClause',
    type: 'checkbox',
    label: 'Include non-solicitation clause',
    required: false,
    group: 'restrictions',
  },
  {
    id: 'confidentialityClause',
    type: 'checkbox',
    label: 'Include confidentiality clause',
    required: false,
    group: 'restrictions',
  },
  {
    id: 'trainingRequired',
    type: 'checkbox',
    label: 'Require training completion',
    required: false,
    group: 'training',
  },
  {
    id: 'trainingDescription',
    type: 'textarea',
    label: 'Training Requirements',
    placeholder: 'Describe required training',
    required: false,
    group: 'training',
    dependsOn: 'trainingRequired',
  },
  {
    id: 'customerOwnership',
    type: 'select',
    label: 'Customer Relationship Ownership',
    options: [
      { value: 'company', label: 'Company Owns Customers' },
      { value: 'shared', label: 'Shared Ownership' },
      { value: 'employee', label: 'Employee Owns Relationships' },
    ],
    required: true,
    group: 'customers',
  },
  {
    id: 'terminationClause',
    type: 'checkbox',
    label: 'Include termination clause',
    required: false,
    group: 'termination',
  },
  {
    id: 'terminationNotice',
    type: 'text',
    label: 'Termination Notice Period',
    placeholder: 'e.g., 30 days written notice',
    required: false,
    group: 'termination',
    dependsOn: 'terminationClause',
  },
  {
    id: 'commissionOnTermination',
    type: 'select',
    label: 'Commission Treatment Upon Termination',
    options: [
      { value: 'forfeit', label: 'Forfeit Unpaid Commissions' },
      { value: 'pro-rated', label: 'Pro-rated Payment' },
      { value: 'full-payment', label: 'Full Payment of Earned Commissions' },
    ],
    required: false,
    group: 'termination',
  },
  {
    id: 'recordKeeping',
    type: 'checkbox',
    label: 'Include record keeping requirements',
    required: false,
    group: 'administration',
  },
  {
    id: 'auditRights',
    type: 'checkbox',
    label: 'Include audit rights for employee',
    required: false,
    group: 'administration',
  },
  {
    id: 'independentContractor',
    type: 'checkbox',
    label: 'Employee is independent contractor',
    required: false,
    group: 'classification',
  },
  {
    id: 'benefitsEligible',
    type: 'checkbox',
    label: 'Employee eligible for company benefits',
    required: false,
    group: 'benefits',
  },
  {
    id: 'requireEmployeeSignature',
    type: 'checkbox',
    label: 'Require employee signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireEmployerSignature',
    type: 'checkbox',
    label: 'Require employer signature',
    required: false,
    group: 'signatures',
  },
];
