// src/lib/documents/us/donation-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const donationAgreementQuestions: FormQuestion[] = [
  {
    id: 'donorName',
    type: 'text',
    label: 'Donor Name',
    placeholder: 'Enter donor full name',
    required: true,
    group: 'donor',
  },
  {
    id: 'donorEmail',
    type: 'email',
    label: 'Donor Email',
    placeholder: 'Enter donor email',
    required: false,
    group: 'donor',
  },
  {
    id: 'donorType',
    type: 'select',
    label: 'Donor Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'foundation', label: 'Foundation' },
      { value: 'trust', label: 'Trust' },
      { value: 'estate', label: 'Estate' },
    ],
    required: false,
    group: 'donor',
  },
  {
    id: 'recipientName',
    type: 'text',
    label: 'Recipient Organization Name',
    placeholder: 'Enter recipient organization name',
    required: true,
    group: 'recipient',
  },
  {
    id: 'recipientType',
    type: 'select',
    label: 'Recipient Type',
    options: [
      { value: 'charity', label: 'Charity' },
      { value: 'nonprofit', label: 'Nonprofit' },
      { value: 'educational', label: 'Educational Institution' },
      { value: 'religious', label: 'Religious Organization' },
      { value: 'individual', label: 'Individual' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
    group: 'recipient',
  },
  {
    id: 'recipientTaxId',
    type: 'text',
    label: 'Recipient Tax ID',
    placeholder: 'Enter tax ID number',
    required: false,
    group: 'recipient',
  },
  {
    id: 'donationType',
    type: 'select',
    label: 'Donation Type',
    options: [
      { value: 'cash', label: 'Cash' },
      { value: 'property', label: 'Property' },
      { value: 'securities', label: 'Securities/Stocks' },
      { value: 'real-estate', label: 'Real Estate' },
      { value: 'in-kind', label: 'In-Kind Services' },
      { value: 'pledge', label: 'Pledge' },
    ],
    required: false,
    group: 'donation',
  },
  {
    id: 'donationAmount',
    type: 'text',
    label: 'Donation Amount/Value',
    placeholder: 'Enter donation amount or value',
    required: false,
    group: 'donation',
  },
  {
    id: 'donationDescription',
    type: 'textarea',
    label: 'Donation Description',
    placeholder: 'Describe the donation',
    required: false,
    group: 'donation',
  },
  {
    id: 'paymentMethod',
    type: 'select',
    label: 'Payment Method',
    options: [
      { value: 'check', label: 'Check' },
      { value: 'wire-transfer', label: 'Wire Transfer' },
      { value: 'credit-card', label: 'Credit Card' },
      { value: 'cash', label: 'Cash' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
    group: 'payment',
    conditional: { field: 'donationType', value: 'cash' },
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'one-time', label: 'One-Time Payment' },
      { value: 'installments', label: 'Installments' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
      { value: 'annual', label: 'Annual' },
    ],
    required: false,
    group: 'payment',
  },
  {
    id: 'donationPurpose',
    type: 'textarea',
    label: 'Donation Purpose',
    placeholder: 'Specify the purpose of the donation',
    required: false,
    group: 'purpose',
  },
  {
    id: 'useRestrictions',
    type: 'boolean',
    label: 'Are there use restrictions?',
    required: false,
    group: 'purpose',
  },
  {
    id: 'restrictionDetails',
    type: 'textarea',
    label: 'Restriction Details',
    placeholder: 'Describe any use restrictions',
    required: false,
    group: 'purpose',
    conditional: { field: 'useRestrictions', value: true },
  },
  {
    id: 'taxDeductible',
    type: 'boolean',
    label: 'Tax deductible donation?',
    required: false,
    group: 'tax',
  },
  {
    id: 'taxReceiptRequired',
    type: 'boolean',
    label: 'Tax receipt required?',
    required: false,
    group: 'tax',
  },
  {
    id: 'donorRecognition',
    type: 'boolean',
    label: 'Donor recognition desired?',
    required: false,
    group: 'recognition',
  },
  {
    id: 'anonymousDonation',
    type: 'boolean',
    label: 'Anonymous donation?',
    required: false,
    group: 'recognition',
  },
  {
    id: 'pledgeAmount',
    type: 'text',
    label: 'Pledge Amount',
    placeholder: 'Enter pledge amount',
    required: false,
    group: 'pledge',
    conditional: { field: 'donationType', value: 'pledge' },
  },
  {
    id: 'pledgePeriod',
    type: 'text',
    label: 'Pledge Period',
    placeholder: 'Enter pledge period (e.g., 3 years)',
    required: false,
    group: 'pledge',
    conditional: { field: 'donationType', value: 'pledge' },
  },
  {
    id: 'matchingGift',
    type: 'boolean',
    label: 'Matching gift?',
    required: false,
    group: 'conditions',
  },
  {
    id: 'impactReporting',
    type: 'boolean',
    label: 'Impact reporting requested?',
    required: false,
    group: 'reporting',
  },
  {
    id: 'revocability',
    type: 'select',
    label: 'Donation Revocability',
    options: [
      { value: 'revocable', label: 'Revocable' },
      { value: 'irrevocable', label: 'Irrevocable' },
    ],
    required: false,
    group: 'legal',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Effective Date',
    required: false,
    group: 'legal',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'Enter governing law/state',
    required: false,
    group: 'legal',
  },
];
