// src/lib/documents/us/subcontractor-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const subcontractorAgreementQuestions: FormQuestion[] = [
  {
    id: 'contractorName',
    type: 'text',
    label: 'General Contractor Name',
    placeholder: 'Enter general contractor company name',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorAddress',
    type: 'text',
    label: 'General Contractor Address',
    placeholder: 'Enter complete contractor address',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorPhone',
    type: 'text',
    label: 'General Contractor Phone',
    placeholder: 'Enter phone number',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorLicense',
    type: 'text',
    label: 'General Contractor License',
    placeholder: 'Enter license number',
    required: false,
    group: 'contractor',
  },
  {
    id: 'subcontractorName',
    type: 'text',
    label: 'Subcontractor Name',
    placeholder: 'Enter subcontractor company name',
    required: true,
    group: 'subcontractor',
  },
  {
    id: 'subcontractorAddress',
    type: 'text',
    label: 'Subcontractor Address',
    placeholder: 'Enter complete subcontractor address',
    required: true,
    group: 'subcontractor',
  },
  {
    id: 'subcontractorPhone',
    type: 'text',
    label: 'Subcontractor Phone',
    placeholder: 'Enter phone number',
    required: true,
    group: 'subcontractor',
  },
  {
    id: 'subcontractorLicense',
    type: 'text',
    label: 'Subcontractor License',
    placeholder: 'Enter license number',
    required: false,
    group: 'subcontractor',
  },
  {
    id: 'subcontractorTrade',
    type: 'text',
    label: 'Trade Specialty',
    placeholder: 'e.g., Electrical, Plumbing, HVAC',
    required: true,
    group: 'subcontractor',
  },
  {
    id: 'projectName',
    type: 'text',
    label: 'Project Name',
    placeholder: 'Enter project name/title',
    required: true,
    group: 'project',
  },
  {
    id: 'projectAddress',
    type: 'text',
    label: 'Project Address',
    placeholder: 'Where the work will be performed',
    required: true,
    group: 'project',
  },
  {
    id: 'ownerName',
    type: 'text',
    label: 'Property Owner Name',
    placeholder: 'Enter property owner name',
    required: false,
    group: 'project',
  },
  {
    id: 'agreementDate',
    type: 'date',
    label: 'Agreement Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'workStartDate',
    type: 'date',
    label: 'Work Start Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'workCompletionDate',
    type: 'date',
    label: 'Work Completion Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'workDescription',
    type: 'textarea',
    label: 'Scope of Work Description',
    placeholder: 'Detailed description of work to be performed',
    required: true,
    group: 'scope',
  },
  {
    id: 'tradeSpecialty',
    type: 'select',
    label: 'Trade Specialty',
    options: [
      { value: 'electrical', label: 'Electrical' },
      { value: 'plumbing', label: 'Plumbing' },
      { value: 'hvac', label: 'HVAC' },
      { value: 'roofing', label: 'Roofing' },
      { value: 'flooring', label: 'Flooring' },
      { value: 'drywall', label: 'Drywall' },
      { value: 'painting', label: 'Painting' },
      { value: 'concrete', label: 'Concrete' },
      { value: 'masonry', label: 'Masonry' },
      { value: 'landscaping', label: 'Landscaping' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'scope',
  },
  {
    id: 'detailedSpecifications',
    type: 'textarea',
    label: 'Detailed Specifications',
    placeholder: 'Specific technical requirements and specifications',
    required: false,
    group: 'scope',
  },
  {
    id: 'materialsIncluded',
    type: 'checkbox',
    label: 'Materials included in subcontract',
    required: false,
    group: 'scope',
  },
  {
    id: 'laborIncluded',
    type: 'checkbox',
    label: 'Labor included in subcontract',
    required: false,
    group: 'scope',
  },
  {
    id: 'equipmentIncluded',
    type: 'checkbox',
    label: 'Equipment/tools included in subcontract',
    required: false,
    group: 'scope',
  },
  {
    id: 'contractAmount',
    type: 'text',
    label: 'Contract Amount',
    placeholder: 'Total subcontract amount',
    required: true,
    group: 'pricing',
  },
  {
    id: 'pricingMethod',
    type: 'select',
    label: 'Pricing Method',
    options: [
      { value: 'lump-sum', label: 'Lump Sum' },
      { value: 'unit-price', label: 'Unit Price' },
      { value: 'cost-plus', label: 'Cost Plus' },
      { value: 'time-and-material', label: 'Time and Material' },
    ],
    required: true,
    group: 'pricing',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'completion', label: 'Upon Completion' },
      { value: 'progress-payments', label: 'Progress Payments' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'milestone-based', label: 'Milestone Based' },
    ],
    required: true,
    group: 'payment',
  },
  {
    id: 'retainagePercentage',
    type: 'text',
    label: 'Retainage Percentage',
    placeholder: 'e.g., 10%',
    required: false,
    group: 'payment',
  },
  {
    id: 'paymentPeriod',
    type: 'text',
    label: 'Payment Period',
    placeholder: 'e.g., Net 30 days',
    required: false,
    group: 'payment',
  },
  {
    id: 'latePaymentPenalty',
    type: 'checkbox',
    label: 'Include late payment penalty',
    required: false,
    group: 'payment',
  },
  {
    id: 'performanceStandards',
    type: 'textarea',
    label: 'Performance Standards',
    placeholder: 'Quality and performance requirements',
    required: false,
    group: 'performance',
  },
  {
    id: 'codeCompliance',
    type: 'checkbox',
    label: 'Work must comply with building codes',
    required: false,
    group: 'performance',
  },
  {
    id: 'inspectionRequirements',
    type: 'checkbox',
    label: 'Work subject to inspections',
    required: false,
    group: 'performance',
  },
  {
    id: 'correctionOfWork',
    type: 'checkbox',
    label: 'Subcontractor must correct defective work',
    required: false,
    group: 'performance',
  },
  {
    id: 'workingHours',
    type: 'text',
    label: 'Working Hours',
    placeholder: 'e.g., 7 AM - 4 PM',
    required: false,
    group: 'schedule',
  },
  {
    id: 'scheduleCoordination',
    type: 'checkbox',
    label: 'Coordinate schedule with other trades',
    required: false,
    group: 'schedule',
  },
  {
    id: 'progressReporting',
    type: 'checkbox',
    label: 'Require progress reporting',
    required: false,
    group: 'schedule',
  },
  {
    id: 'delayNotification',
    type: 'checkbox',
    label: 'Notify of potential delays',
    required: false,
    group: 'schedule',
  },
  {
    id: 'liquidatedDamages',
    type: 'checkbox',
    label: 'Include liquidated damages for delays',
    required: false,
    group: 'schedule',
  },
  {
    id: 'generalLiabilityInsurance',
    type: 'text',
    label: 'General Liability Insurance Amount',
    placeholder: 'Minimum coverage amount',
    required: false,
    group: 'insurance',
  },
  {
    id: 'workersCompensation',
    type: 'checkbox',
    label: 'Require workers compensation insurance',
    required: false,
    group: 'insurance',
  },
  {
    id: 'autoInsurance',
    type: 'checkbox',
    label: 'Require automobile insurance',
    required: false,
    group: 'insurance',
  },
  {
    id: 'additionalInsured',
    type: 'checkbox',
    label: 'General contractor as additional insured',
    required: false,
    group: 'insurance',
  },
  {
    id: 'certificateOfInsurance',
    type: 'checkbox',
    label: 'Provide certificate of insurance',
    required: false,
    group: 'insurance',
  },
  {
    id: 'safetyCompliance',
    type: 'checkbox',
    label: 'Comply with safety requirements',
    required: false,
    group: 'safety',
  },
  {
    id: 'personalProtectiveEquipment',
    type: 'checkbox',
    label: 'Provide personal protective equipment',
    required: false,
    group: 'safety',
  },
  {
    id: 'accidentReporting',
    type: 'checkbox',
    label: 'Report accidents immediately',
    required: false,
    group: 'safety',
  },
  {
    id: 'oshaCompliance',
    type: 'checkbox',
    label: 'Comply with OSHA requirements',
    required: false,
    group: 'safety',
  },
  {
    id: 'changeOrderProcess',
    type: 'checkbox',
    label: 'Include change order process',
    required: false,
    group: 'changes',
  },
  {
    id: 'changeOrderApproval',
    type: 'select',
    label: 'Change Order Approval Method',
    options: [
      { value: 'written-only', label: 'Written Approval Only' },
      { value: 'verbal-allowed', label: 'Verbal Approval Allowed' },
      { value: 'email-allowed', label: 'Email Approval Allowed' },
    ],
    required: false,
    group: 'changes',
    dependsOn: 'changeOrderProcess',
  },
  {
    id: 'materialProcurement',
    type: 'select',
    label: 'Material Procurement Responsibility',
    options: [
      { value: 'subcontractor', label: 'Subcontractor' },
      { value: 'contractor', label: 'General Contractor' },
      { value: 'owner', label: 'Owner' },
      { value: 'shared', label: 'Shared' },
    ],
    required: false,
    group: 'materials',
  },
  {
    id: 'materialApproval',
    type: 'checkbox',
    label: 'Require material approval',
    required: false,
    group: 'materials',
  },
  {
    id: 'materialWarranties',
    type: 'checkbox',
    label: 'Transfer material warranties',
    required: false,
    group: 'materials',
  },
  {
    id: 'cleanupResponsibility',
    type: 'checkbox',
    label: 'Subcontractor responsible for cleanup',
    required: false,
    group: 'obligations',
  },
  {
    id: 'wasteDisposal',
    type: 'checkbox',
    label: 'Subcontractor responsible for waste disposal',
    required: false,
    group: 'obligations',
  },
  {
    id: 'siteProtection',
    type: 'checkbox',
    label: 'Protect existing work and property',
    required: false,
    group: 'obligations',
  },
  {
    id: 'coordinationWithOthers',
    type: 'checkbox',
    label: 'Coordinate with other subcontractors',
    required: false,
    group: 'obligations',
  },
  {
    id: 'workmanshipWarranty',
    type: 'checkbox',
    label: 'Include workmanship warranty',
    required: false,
    group: 'warranty',
  },
  {
    id: 'warrantyPeriod',
    type: 'text',
    label: 'Warranty Period',
    placeholder: 'e.g., 1 year',
    required: false,
    group: 'warranty',
    dependsOn: 'workmanshipWarranty',
  },
  {
    id: 'callbackResponsibility',
    type: 'checkbox',
    label: 'Responsible for warranty callbacks',
    required: false,
    group: 'warranty',
  },
  {
    id: 'terminationRights',
    type: 'checkbox',
    label: 'Include termination rights',
    required: false,
    group: 'termination',
  },
  {
    id: 'terminationNotice',
    type: 'text',
    label: 'Termination Notice Period',
    placeholder: 'e.g., 7 days written notice',
    required: false,
    group: 'termination',
    dependsOn: 'terminationRights',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'negotiation', label: 'Negotiation' },
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'litigation', label: 'Court Litigation' },
    ],
    required: false,
    group: 'disputes',
  },
  {
    id: 'attorneyFees',
    type: 'checkbox',
    label: 'Include attorney fees clause',
    required: false,
    group: 'disputes',
  },
  {
    id: 'subcontractorIndemnity',
    type: 'checkbox',
    label: 'Subcontractor indemnifies general contractor',
    required: false,
    group: 'indemnification',
  },
  {
    id: 'lienWaiver',
    type: 'checkbox',
    label: 'Require lien waivers',
    required: false,
    group: 'liens',
  },
  {
    id: 'lienWaiverTiming',
    type: 'select',
    label: 'Lien Waiver Timing',
    options: [
      { value: 'progress-payments', label: 'With Progress Payments' },
      { value: 'final-payment', label: 'With Final Payment' },
      { value: 'both', label: 'Both Progress and Final' },
    ],
    required: false,
    group: 'liens',
    dependsOn: 'lienWaiver',
  },
  {
    id: 'independentContractor',
    type: 'checkbox',
    label: 'Subcontractor is independent contractor',
    required: false,
    group: 'contractor-status',
  },
  {
    id: 'taxResponsibility',
    type: 'checkbox',
    label: 'Subcontractor responsible for own taxes',
    required: false,
    group: 'contractor-status',
  },
  {
    id: 'assignmentAllowed',
    type: 'checkbox',
    label: 'Allow assignment of subcontract',
    required: false,
    group: 'assignment',
  },
  {
    id: 'furtherSubcontracting',
    type: 'checkbox',
    label: 'Allow further subcontracting',
    required: false,
    group: 'assignment',
  },
  {
    id: 'finalInspection',
    type: 'checkbox',
    label: 'Require final inspection',
    required: false,
    group: 'completion',
  },
  {
    id: 'punchList',
    type: 'checkbox',
    label: 'Include punch list process',
    required: false,
    group: 'completion',
  },
  {
    id: 'finalAcceptance',
    type: 'checkbox',
    label: 'Require final acceptance',
    required: false,
    group: 'completion',
  },
  {
    id: 'requireContractorSignature',
    type: 'checkbox',
    label: 'Require general contractor signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireSubcontractorSignature',
    type: 'checkbox',
    label: 'Require subcontractor signature',
    required: false,
    group: 'signatures',
  },
];
