// src/lib/documents/us/change-order/questions.ts
import type { FormQuestion } from '@/types/documents';

export const changeOrderQuestions: FormQuestion[] = [
  {
    id: 'originalContractNumber',
    type: 'text',
    label: 'Original Contract Number',
    placeholder: 'Enter the original contract number',
    required: true,
    group: 'reference',
  },
  {
    id: 'originalContractDate',
    type: 'date',
    label: 'Original Contract Date',
    required: true,
    group: 'reference',
  },
  {
    id: 'changeOrderNumber',
    type: 'text',
    label: 'Change Order Number',
    placeholder: 'e.g., CO-001, Change Order #1',
    required: true,
    group: 'reference',
  },
  {
    id: 'changeOrderDate',
    type: 'date',
    label: 'Change Order Date',
    required: true,
    group: 'reference',
  },
  {
    id: 'client',
    type: 'text',
    label: 'Client Name',
    placeholder: 'Enter client company or individual name',
    required: true,
    group: 'parties',
  },
  {
    id: 'clientAddress',
    type: 'textarea',
    label: 'Client Address',
    placeholder: 'Enter complete client address',
    required: true,
    group: 'parties',
  },
  {
    id: 'contractor',
    type: 'text',
    label: 'Contractor Name',
    placeholder: 'Enter contractor company or individual name',
    required: true,
    group: 'parties',
  },
  {
    id: 'contractorAddress',
    type: 'textarea',
    label: 'Contractor Address',
    placeholder: 'Enter complete contractor address',
    required: true,
    group: 'parties',
  },
  {
    id: 'changeType',
    type: 'select',
    label: 'Type of Change',
    options: [
      { value: 'scope', label: 'Scope Change' },
      { value: 'timeline', label: 'Timeline Change' },
      { value: 'budget', label: 'Budget Change' },
      { value: 'specifications', label: 'Specifications Change' },
      { value: 'resources', label: 'Resources Change' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'change',
  },
  {
    id: 'urgency',
    type: 'select',
    label: 'Urgency Level',
    options: [
      { value: 'low', label: 'Low' },
      { value: 'medium', label: 'Medium' },
      { value: 'high', label: 'High' },
      { value: 'critical', label: 'Critical' },
    ],
    required: true,
    group: 'change',
  },
  {
    id: 'changeDescription',
    type: 'textarea',
    label: 'Description of Change',
    placeholder: 'Provide a detailed description of the proposed changes',
    required: true,
    group: 'change',
  },
  {
    id: 'reasonForChange',
    type: 'textarea',
    label: 'Reason for Change',
    placeholder: 'Explain why this change is necessary',
    required: true,
    group: 'change',
  },
  {
    id: 'originalScope',
    type: 'textarea',
    label: 'Original Scope',
    placeholder: 'Describe the original scope of work',
    required: false,
    group: 'scope',
  },
  {
    id: 'revisedScope',
    type: 'textarea',
    label: 'Revised Scope',
    placeholder: 'Describe the revised scope of work',
    required: false,
    group: 'scope',
  },
  {
    id: 'addedWork',
    type: 'textarea',
    label: 'Added Work',
    placeholder: 'Describe any work being added',
    required: false,
    group: 'scope',
  },
  {
    id: 'deletedWork',
    type: 'textarea',
    label: 'Deleted Work',
    placeholder: 'Describe any work being removed',
    required: false,
    group: 'scope',
  },
  {
    id: 'originalTimeline',
    type: 'text',
    label: 'Original Timeline',
    placeholder: 'Describe the original project timeline',
    required: false,
    group: 'timeline',
  },
  {
    id: 'revisedTimeline',
    type: 'text',
    label: 'Revised Timeline',
    placeholder: 'Describe the revised project timeline',
    required: false,
    group: 'timeline',
  },
  {
    id: 'originalDeadline',
    type: 'date',
    label: 'Original Deadline',
    required: false,
    group: 'timeline',
  },
  {
    id: 'revisedDeadline',
    type: 'date',
    label: 'Revised Deadline',
    required: false,
    group: 'timeline',
  },
  {
    id: 'timeExtension',
    type: 'text',
    label: 'Time Extension',
    placeholder: 'e.g., 2 weeks, 30 days',
    required: false,
    group: 'timeline',
  },
  {
    id: 'originalContractValue',
    type: 'number',
    label: 'Original Contract Value ($)',
    placeholder: '100000',
    required: false,
    group: 'financial',
  },
  {
    id: 'changeOrderValue',
    type: 'number',
    label: 'Change Order Value ($)',
    placeholder: '5000',
    required: true,
    group: 'financial',
  },
  {
    id: 'revisedContractValue',
    type: 'number',
    label: 'Revised Contract Value ($)',
    placeholder: '105000',
    required: false,
    group: 'financial',
  },
  {
    id: 'costBreakdown',
    type: 'textarea',
    label: 'Cost Breakdown',
    placeholder: 'Provide detailed breakdown of costs',
    required: false,
    group: 'financial',
  },
  {
    id: 'additionalCosts',
    type: 'textarea',
    label: 'Additional Costs',
    placeholder: 'Describe any additional costs or savings',
    required: false,
    group: 'financial',
  },
  {
    id: 'additionalResources',
    type: 'textarea',
    label: 'Additional Resources Required',
    placeholder: 'Describe any additional resources needed',
    required: false,
    group: 'resources',
  },
  {
    id: 'materialChanges',
    type: 'textarea',
    label: 'Material Changes',
    placeholder: 'Describe any changes to materials',
    required: false,
    group: 'resources',
  },
  {
    id: 'personnelChanges',
    type: 'textarea',
    label: 'Personnel Changes',
    placeholder: 'Describe any changes to personnel requirements',
    required: false,
    group: 'resources',
  },
  {
    id: 'scheduleImpact',
    type: 'textarea',
    label: 'Schedule Impact',
    placeholder: 'Describe impact on project schedule',
    required: false,
    group: 'impact',
  },
  {
    id: 'budgetImpact',
    type: 'textarea',
    label: 'Budget Impact',
    placeholder: 'Describe impact on project budget',
    required: false,
    group: 'impact',
  },
  {
    id: 'qualityImpact',
    type: 'textarea',
    label: 'Quality Impact',
    placeholder: 'Describe impact on project quality',
    required: false,
    group: 'impact',
  },
  {
    id: 'riskImpact',
    type: 'textarea',
    label: 'Risk Impact',
    placeholder: 'Describe any new risks or risk mitigation',
    required: false,
    group: 'impact',
  },
  {
    id: 'requestedBy',
    type: 'text',
    label: 'Requested By',
    placeholder: 'Name and title of person requesting change',
    required: false,
    group: 'approval',
  },
  {
    id: 'requestDate',
    type: 'date',
    label: 'Request Date',
    required: false,
    group: 'approval',
  },
  {
    id: 'approvedBy',
    type: 'text',
    label: 'Approved By',
    placeholder: 'Name and title of approving authority',
    required: false,
    group: 'approval',
  },
  {
    id: 'approvalDate',
    type: 'date',
    label: 'Approval Date',
    required: false,
    group: 'approval',
  },
  {
    id: 'approvalStatus',
    type: 'select',
    label: 'Approval Status',
    options: [
      { value: 'pending', label: 'Pending' },
      { value: 'approved', label: 'Approved' },
      { value: 'rejected', label: 'Rejected' },
      { value: 'conditional', label: 'Conditionally Approved' },
    ],
    required: false,
    group: 'approval',
  },
  {
    id: 'implementationDate',
    type: 'date',
    label: 'Implementation Date',
    required: false,
    group: 'implementation',
  },
  {
    id: 'implementationPlan',
    type: 'textarea',
    label: 'Implementation Plan',
    placeholder: 'Describe how the change will be implemented',
    required: false,
    group: 'implementation',
  },
  {
    id: 'implementationResponsibilities',
    type: 'textarea',
    label: 'Implementation Responsibilities',
    placeholder: 'Define responsibilities for implementing the change',
    required: false,
    group: 'implementation',
  },
  {
    id: 'paymentTerms',
    type: 'textarea',
    label: 'Payment Terms for Change Order',
    placeholder: 'Specify payment terms for the change order',
    required: false,
    group: 'terms',
  },
  {
    id: 'warrantyImpact',
    type: 'textarea',
    label: 'Warranty Impact',
    placeholder: 'Describe any impact on warranties',
    required: false,
    group: 'terms',
  },
  {
    id: 'legalReview',
    type: 'checkbox',
    label: 'Legal review required',
    required: false,
    group: 'legal',
  },
  {
    id: 'contractualBasis',
    type: 'textarea',
    label: 'Contractual Basis',
    placeholder: 'Specify the contractual basis for this change',
    required: false,
    group: 'legal',
  },
  {
    id: 'assumptions',
    type: 'textarea',
    label: 'Assumptions',
    placeholder: 'List any assumptions related to this change',
    required: false,
    group: 'additional',
  },
  {
    id: 'constraints',
    type: 'textarea',
    label: 'Constraints',
    placeholder: 'List any constraints or limitations',
    required: false,
    group: 'additional',
  },
  {
    id: 'dependencies',
    type: 'textarea',
    label: 'Dependencies',
    placeholder: 'List any dependencies for this change',
    required: false,
    group: 'additional',
  },
  {
    id: 'additionalNotes',
    type: 'textarea',
    label: 'Additional Notes',
    placeholder: 'Any additional information or notes',
    required: false,
    group: 'additional',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Effective Date',
    required: false,
    group: 'signatures',
  },
];