// src/lib/documents/us/mining-lease-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const miningLeaseAgreementQuestions: FormQuestion[] = [
  {
    id: 'lessorName',
    type: 'text',
    label: 'Lessor Name',
    placeholder: 'Enter property owner name',
    required: true,
    group: 'lessor',
  },
  {
    id: 'lesseeName',
    type: 'text',
    label: 'Lessee Name',
    placeholder: 'Enter mining company name',
    required: true,
    group: 'lessee',
  },
  {
    id: 'propertyDescription',
    type: 'textarea',
    label: 'Property Description',
    placeholder: 'Describe the property to be leased',
    required: false,
    group: 'property',
  },
  {
    id: 'acres',
    type: 'text',
    label: 'Property Size (Acres)',
    placeholder: 'Enter property size in acres',
    required: false,
    group: 'property',
  },
  {
    id: 'mineralTypes',
    type: 'multi-select',
    label: 'Mineral Types',
    options: [
      { value: 'coal', label: 'Coal' },
      { value: 'oil', label: 'Oil' },
      { value: 'gas', label: 'Natural Gas' },
      { value: 'gold', label: 'Gold' },
      { value: 'silver', label: 'Silver' },
      { value: 'copper', label: 'Copper' },
      { value: 'iron', label: 'Iron Ore' },
      { value: 'limestone', label: 'Limestone' },
      { value: 'gravel', label: 'Gravel' },
      { value: 'sand', label: 'Sand' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
    group: 'minerals',
  },
  {
    id: 'exclusiveRights',
    type: 'boolean',
    label: 'Exclusive mining rights?',
    required: false,
    group: 'minerals',
  },
  {
    id: 'leaseTerm',
    type: 'text',
    label: 'Lease Term',
    placeholder: 'Enter lease duration (e.g., 5 years)',
    required: false,
    group: 'terms',
  },
  {
    id: 'royaltyRate',
    type: 'text',
    label: 'Royalty Rate',
    placeholder: 'Enter royalty percentage',
    required: false,
    group: 'payment',
  },
  {
    id: 'bonusPayment',
    type: 'text',
    label: 'Bonus Payment',
    placeholder: 'Enter signing bonus amount',
    required: false,
    group: 'payment',
  },
  {
    id: 'environmentalPermits',
    type: 'boolean',
    label: 'Environmental permits required?',
    required: false,
    group: 'environmental',
  },
  {
    id: 'reclamationPlan',
    type: 'boolean',
    label: 'Land reclamation plan required?',
    required: false,
    group: 'environmental',
  },
  {
    id: 'bondAmount',
    type: 'text',
    label: 'Performance Bond Amount',
    placeholder: 'Enter bond amount if required',
    required: false,
    group: 'environmental',
  },
  {
    id: 'safetyStandards',
    type: 'boolean',
    label: 'Safety standards compliance required?',
    required: false,
    group: 'safety',
  },
  {
    id: 'liabilityAmount',
    type: 'text',
    label: 'Insurance Liability Amount',
    placeholder: 'Enter required insurance coverage',
    required: false,
    group: 'insurance',
  },
];
