// src/lib/documents/us/mechanics-lien-waiver/questions.ts
import type { FormQuestion } from '@/types/documents';

export const mechanicslienwaiverQuestions: FormQuestion[] = [
  {
    id: 'waiverType',
    type: 'select',
    label: 'Waiver Type',
    options: [
      { value: 'partial', label: 'Partial Waiver' },
      { value: 'final', label: 'Final Waiver' },
      { value: 'conditional', label: 'Conditional Waiver' },
      { value: 'unconditional', label: 'Unconditional Waiver' },
    ],
    required: true,
    group: 'waiver',
  },
  {
    id: 'waiverDate',
    type: 'date',
    label: 'Waiver Date',
    required: true,
    group: 'waiver',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Effective Date',
    required: false,
    group: 'waiver',
  },
  {
    id: 'claimantName',
    type: 'text',
    label: 'Claimant Name',
    placeholder: 'Name of person/company waiving lien rights',
    required: true,
    group: 'claimant',
  },
  {
    id: 'claimantAddress',
    type: 'text',
    label: 'Claimant Address',
    placeholder: 'Complete claimant address',
    required: true,
    group: 'claimant',
  },
  {
    id: 'claimantPhone',
    type: 'text',
    label: 'Claimant Phone',
    placeholder: 'Contact phone number',
    required: false,
    group: 'claimant',
  },
  {
    id: 'claimantEmail',
    type: 'email',
    label: 'Claimant Email',
    placeholder: 'Contact email address',
    required: false,
    group: 'claimant',
  },
  {
    id: 'claimantCapacity',
    type: 'select',
    label: 'Claimant Capacity',
    options: [
      { value: 'contractor', label: 'General Contractor' },
      { value: 'subcontractor', label: 'Subcontractor' },
      { value: 'supplier', label: 'Material Supplier' },
      { value: 'laborer', label: 'Laborer' },
      { value: 'materialman', label: 'Materialman' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'claimant',
  },
  {
    id: 'claimantLicense',
    type: 'text',
    label: 'Claimant License Number',
    placeholder: 'Professional license number if applicable',
    required: false,
    group: 'claimant',
  },
  {
    id: 'propertyOwner',
    type: 'text',
    label: 'Property Owner Name',
    placeholder: 'Name of property owner',
    required: true,
    group: 'property',
  },
  {
    id: 'propertyAddress',
    type: 'text',
    label: 'Property Address',
    placeholder: 'Complete property address',
    required: true,
    group: 'property',
  },
  {
    id: 'propertyDescription',
    type: 'textarea',
    label: 'Property Description',
    placeholder: 'General description of the property',
    required: false,
    group: 'property',
  },
  {
    id: 'propertyLegalDescription',
    type: 'textarea',
    label: 'Legal Description',
    placeholder: 'Legal description of the property',
    required: false,
    group: 'property',
  },
  {
    id: 'projectName',
    type: 'text',
    label: 'Project Name',
    placeholder: 'Name of construction project',
    required: false,
    group: 'project',
  },
  {
    id: 'projectDescription',
    type: 'textarea',
    label: 'Project Description',
    placeholder: 'Description of construction project',
    required: false,
    group: 'project',
  },
  {
    id: 'workPerformed',
    type: 'textarea',
    label: 'Work Performed',
    placeholder: 'Detailed description of work performed',
    required: true,
    group: 'project',
  },
  {
    id: 'materialsSupplied',
    type: 'textarea',
    label: 'Materials Supplied',
    placeholder: 'Description of materials supplied',
    required: false,
    group: 'project',
  },
  {
    id: 'contractWith',
    type: 'text',
    label: 'Contract With',
    placeholder: 'Name of party contracted with',
    required: true,
    group: 'contract',
  },
  {
    id: 'contractDate',
    type: 'date',
    label: 'Contract Date',
    required: false,
    group: 'contract',
  },
  {
    id: 'contractAmount',
    type: 'text',
    label: 'Contract Amount',
    placeholder: 'Total contract amount',
    required: false,
    group: 'contract',
  },
  {
    id: 'contractDescription',
    type: 'textarea',
    label: 'Contract Description',
    placeholder: 'Description of contract work',
    required: false,
    group: 'contract',
  },
  {
    id: 'amountDue',
    type: 'text',
    label: 'Amount Due',
    placeholder: 'Total amount due for work/materials',
    required: true,
    group: 'payment',
  },
  {
    id: 'amountPaid',
    type: 'text',
    label: 'Amount Paid',
    placeholder: 'Amount being paid',
    required: true,
    group: 'payment',
  },
  {
    id: 'paymentDate',
    type: 'date',
    label: 'Payment Date',
    required: false,
    group: 'payment',
  },
  {
    id: 'paymentMethod',
    type: 'select',
    label: 'Payment Method',
    options: [
      { value: 'check', label: 'Check' },
      { value: 'cash', label: 'Cash' },
      { value: 'wire-transfer', label: 'Wire Transfer' },
      { value: 'ach', label: 'ACH Transfer' },
      { value: 'credit-card', label: 'Credit Card' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
    group: 'payment',
  },
  {
    id: 'checkNumber',
    type: 'text',
    label: 'Check Number',
    placeholder: 'Check number if applicable',
    required: false,
    group: 'payment',
    dependsOn: 'paymentMethod',
  },
  {
    id: 'workStartDate',
    type: 'date',
    label: 'Work Start Date',
    required: false,
    group: 'timeline',
  },
  {
    id: 'workEndDate',
    type: 'date',
    label: 'Work End Date',
    required: false,
    group: 'timeline',
  },
  {
    id: 'lastWorkDate',
    type: 'date',
    label: 'Last Work Date',
    required: false,
    group: 'timeline',
  },
  {
    id: 'waiverScope',
    type: 'select',
    label: 'Waiver Scope',
    options: [
      { value: 'work-to-date', label: 'All Work to Date' },
      { value: 'specific-period', label: 'Specific Time Period' },
      { value: 'specific-work', label: 'Specific Work Items' },
      { value: 'final-payment', label: 'Final Payment' },
    ],
    required: true,
    group: 'scope',
  },
  {
    id: 'periodFrom',
    type: 'date',
    label: 'Period From',
    required: false,
    group: 'scope',
    dependsOn: 'waiverScope',
  },
  {
    id: 'periodTo',
    type: 'date',
    label: 'Period To',
    required: false,
    group: 'scope',
    dependsOn: 'waiverScope',
  },
  {
    id: 'specificWork',
    type: 'textarea',
    label: 'Specific Work',
    placeholder: 'Description of specific work being waived',
    required: false,
    group: 'scope',
    dependsOn: 'waiverScope',
  },
  {
    id: 'mechanicsLienRights',
    type: 'checkbox',
    label: 'Waive mechanics lien rights',
    required: false,
    group: 'rights',
  },
  {
    id: 'stopNoticeRights',
    type: 'checkbox',
    label: 'Waive stop notice rights',
    required: false,
    group: 'rights',
  },
  {
    id: 'bondClaimRights',
    type: 'checkbox',
    label: 'Waive bond claim rights',
    required: false,
    group: 'rights',
  },
  {
    id: 'retentionAmount',
    type: 'text',
    label: 'Retention Amount',
    placeholder: 'Amount of retention held',
    required: false,
    group: 'retention',
  },
  {
    id: 'retentionReleased',
    type: 'checkbox',
    label: 'Retention released with this waiver',
    required: false,
    group: 'retention',
  },
  {
    id: 'futureWorkRights',
    type: 'checkbox',
    label: 'Reserve rights for future work',
    required: false,
    group: 'exceptions',
  },
  {
    id: 'changeOrderRights',
    type: 'checkbox',
    label: 'Reserve rights for change orders',
    required: false,
    group: 'exceptions',
  },
  {
    id: 'paymentConditions',
    type: 'textarea',
    label: 'Payment Conditions',
    placeholder: 'Conditions that must be met for waiver to be effective',
    required: false,
    group: 'conditions',
  },
  {
    id: 'checkClearanceRequired',
    type: 'checkbox',
    label: 'Waiver conditional on check clearance',
    required: false,
    group: 'conditions',
  },
  {
    id: 'jointCheckRequired',
    type: 'checkbox',
    label: 'Joint check required',
    required: false,
    group: 'joint-check',
  },
  {
    id: 'trustFundClaimsWaived',
    type: 'checkbox',
    label: 'Trust fund claims waived',
    required: false,
    group: 'trust-fund',
  },
  {
    id: 'trustFundExceptions',
    type: 'textarea',
    label: 'Trust Fund Exceptions',
    placeholder: 'Exceptions to trust fund waiver',
    required: false,
    group: 'trust-fund',
  },
  {
    id: 'subcontractorWaivers',
    type: 'checkbox',
    label: 'Subcontractor waivers required',
    required: false,
    group: 'subcontractors',
  },
  {
    id: 'supplierWaivers',
    type: 'checkbox',
    label: 'Supplier waivers required',
    required: false,
    group: 'suppliers',
  },
  {
    id: 'noticeToOwner',
    type: 'checkbox',
    label: 'Notice to owner provided',
    required: false,
    group: 'notice',
  },
  {
    id: 'noticeToPrincipal',
    type: 'checkbox',
    label: 'Notice to principal provided',
    required: false,
    group: 'notice',
  },
  {
    id: 'noticeToLender',
    type: 'checkbox',
    label: 'Notice to lender provided',
    required: false,
    group: 'notice',
  },
  {
    id: 'disputeWaiver',
    type: 'checkbox',
    label: 'Waive right to dispute payment',
    required: false,
    group: 'dispute',
  },
  {
    id: 'litigationWaiver',
    type: 'checkbox',
    label: 'Waive right to litigation',
    required: false,
    group: 'dispute',
  },
  {
    id: 'workCompleteWarranty',
    type: 'checkbox',
    label: 'Warrant that work is complete',
    required: false,
    group: 'warranty',
  },
  {
    id: 'noUnpaidDebtsWarranty',
    type: 'checkbox',
    label: 'Warrant no unpaid debts for labor/materials',
    required: false,
    group: 'warranty',
  },
  {
    id: 'authorityWarranty',
    type: 'checkbox',
    label: 'Warrant authority to execute waiver',
    required: false,
    group: 'warranty',
  },
  {
    id: 'indemnificationClause',
    type: 'checkbox',
    label: 'Include indemnification clause',
    required: false,
    group: 'indemnification',
  },
  {
    id: 'indemnificationScope',
    type: 'textarea',
    label: 'Indemnification Scope',
    placeholder: 'Scope of indemnification',
    required: false,
    group: 'indemnification',
    dependsOn: 'indemnificationClause',
  },
  {
    id: 'statutoryCompliance',
    type: 'checkbox',
    label: 'Comply with state statutory requirements',
    required: false,
    group: 'statutory',
  },
  {
    id: 'recordingRequired',
    type: 'checkbox',
    label: 'Recording required',
    required: false,
    group: 'recording',
  },
  {
    id: 'recordingOffice',
    type: 'text',
    label: 'Recording Office',
    placeholder: 'County recorder or clerk office',
    required: false,
    group: 'recording',
    dependsOn: 'recordingRequired',
  },
  {
    id: 'retroactiveEffect',
    type: 'checkbox',
    label: 'Waiver has retroactive effect',
    required: false,
    group: 'effective',
  },
  {
    id: 'terminationDate',
    type: 'date',
    label: 'Waiver Termination Date',
    required: false,
    group: 'effective',
  },
  {
    id: 'generalRelease',
    type: 'checkbox',
    label: 'Include general release of all claims',
    required: false,
    group: 'release',
  },
  {
    id: 'relatedClaimsWaived',
    type: 'checkbox',
    label: 'Waive related claims',
    required: false,
    group: 'release',
  },
  {
    id: 'assignabilityRights',
    type: 'checkbox',
    label: 'Waiver rights are assignable',
    required: false,
    group: 'third-party',
  },
  {
    id: 'modificationRights',
    type: 'checkbox',
    label: 'Allow waiver modifications',
    required: false,
    group: 'modification',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'State governing law',
    required: false,
    group: 'legal',
  },
  {
    id: 'jurisdiction',
    type: 'text',
    label: 'Jurisdiction',
    placeholder: 'Court jurisdiction',
    required: false,
    group: 'legal',
  },
  {
    id: 'receiptAcknowledgment',
    type: 'checkbox',
    label: 'Acknowledge receipt of payment',
    required: false,
    group: 'acknowledgments',
  },
  {
    id: 'voluntaryExecution',
    type: 'checkbox',
    label: 'Acknowledge voluntary execution',
    required: false,
    group: 'acknowledgments',
  },
  {
    id: 'legalAdviceReceived',
    type: 'checkbox',
    label: 'Legal advice received',
    required: false,
    group: 'acknowledgments',
  },
  {
    id: 'corporateResolution',
    type: 'checkbox',
    label: 'Corporate resolution authorizes waiver',
    required: false,
    group: 'corporate',
  },
  {
    id: 'officerCapacity',
    type: 'text',
    label: 'Officer Capacity',
    placeholder: 'Title of corporate officer',
    required: false,
    group: 'corporate',
  },
  {
    id: 'claimantSignature',
    type: 'checkbox',
    label: 'Require claimant signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'claimantTitle',
    type: 'text',
    label: 'Claimant Title',
    placeholder: 'Title of person signing',
    required: false,
    group: 'signatures',
  },
  {
    id: 'witnessSignature',
    type: 'checkbox',
    label: 'Require witness signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'witnessName',
    type: 'text',
    label: 'Witness Name',
    placeholder: 'Name of witness',
    required: false,
    group: 'signatures',
    dependsOn: 'witnessSignature',
  },
  {
    id: 'requireNotarization',
    type: 'checkbox',
    label: 'Require notarization',
    required: false,
    group: 'notary',
  },
  {
    id: 'notaryState',
    type: 'text',
    label: 'Notary State',
    placeholder: 'State where notarized',
    required: false,
    group: 'notary',
    dependsOn: 'requireNotarization',
  },
  {
    id: 'notaryCounty',
    type: 'text',
    label: 'Notary County',
    placeholder: 'County where notarized',
    required: false,
    group: 'notary',
    dependsOn: 'requireNotarization',
  },
  {
    id: 'deliveryMethod',
    type: 'select',
    label: 'Delivery Method',
    options: [
      { value: 'hand-delivery', label: 'Hand Delivery' },
      { value: 'certified-mail', label: 'Certified Mail' },
      { value: 'email', label: 'Email' },
      { value: 'regular-mail', label: 'Regular Mail' },
    ],
    required: false,
    group: 'delivery',
  },
  {
    id: 'deliveryAddress',
    type: 'text',
    label: 'Delivery Address',
    placeholder: 'Address for waiver delivery',
    required: false,
    group: 'delivery',
  },
  {
    id: 'effectiveUponDelivery',
    type: 'checkbox',
    label: 'Effective upon delivery',
    required: false,
    group: 'delivery',
  },
];
