// src/lib/documents/us/construction-management-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const constructionmanagementagreementQuestions: FormQuestion[] = [
  {
    id: 'ownerName',
    type: 'text',
    label: 'Owner Name',
    placeholder: 'Enter property owner name',
    required: true,
    group: 'owner',
  },
  {
    id: 'ownerAddress',
    type: 'text',
    label: 'Owner Address',
    placeholder: 'Enter complete owner address',
    required: true,
    group: 'owner',
  },
  {
    id: 'ownerPhone',
    type: 'text',
    label: 'Owner Phone',
    placeholder: 'Enter phone number',
    required: true,
    group: 'owner',
  },
  {
    id: 'ownerEmail',
    type: 'email',
    label: 'Owner Email',
    placeholder: 'Enter email address',
    required: false,
    group: 'owner',
  },
  {
    id: 'managerName',
    type: 'text',
    label: 'Construction Manager Name',
    placeholder: 'Enter construction manager/company name',
    required: true,
    group: 'manager',
  },
  {
    id: 'managerAddress',
    type: 'text',
    label: 'Construction Manager Address',
    placeholder: 'Enter complete manager address',
    required: true,
    group: 'manager',
  },
  {
    id: 'managerPhone',
    type: 'text',
    label: 'Construction Manager Phone',
    placeholder: 'Enter phone number',
    required: true,
    group: 'manager',
  },
  {
    id: 'managerEmail',
    type: 'email',
    label: 'Construction Manager Email',
    placeholder: 'Enter email address',
    required: false,
    group: 'manager',
  },
  {
    id: 'managerLicense',
    type: 'text',
    label: 'Construction Manager License',
    placeholder: 'Enter license number',
    required: true,
    group: 'manager',
  },
  {
    id: 'projectName',
    type: 'text',
    label: 'Project Name',
    placeholder: 'Enter project name/title',
    required: true,
    group: 'project',
  },
  {
    id: 'projectAddress',
    type: 'text',
    label: 'Project Address',
    placeholder: 'Where construction will take place',
    required: true,
    group: 'project',
  },
  {
    id: 'projectDescription',
    type: 'textarea',
    label: 'Project Description',
    placeholder: 'Detailed description of construction project',
    required: true,
    group: 'project',
  },
  {
    id: 'projectType',
    type: 'select',
    label: 'Project Type',
    options: [
      { value: 'residential', label: 'Residential' },
      { value: 'commercial', label: 'Commercial' },
      { value: 'industrial', label: 'Industrial' },
      { value: 'infrastructure', label: 'Infrastructure' },
      { value: 'renovation', label: 'Renovation' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'project',
  },
  {
    id: 'serviceType',
    type: 'select',
    label: 'Management Service Type',
    options: [
      { value: 'cm-at-risk', label: 'Construction Manager at Risk' },
      { value: 'agency-cm', label: 'Agency Construction Management' },
      { value: 'guaranteed-maximum-price', label: 'Guaranteed Maximum Price' },
      { value: 'cost-plus-fee', label: 'Cost Plus Fee' },
    ],
    required: true,
    group: 'services',
  },
  {
    id: 'managementPhases',
    type: 'checkbox',
    label: 'Management Phases',
    options: [
      { value: 'pre-construction', label: 'Pre-Construction' },
      { value: 'construction', label: 'Construction' },
      { value: 'post-construction', label: 'Post-Construction' },
    ],
    required: true,
    group: 'services',
  },
  {
    id: 'designReview',
    type: 'checkbox',
    label: 'Include design review services',
    required: false,
    group: 'pre-construction',
  },
  {
    id: 'costEstimating',
    type: 'checkbox',
    label: 'Include cost estimating services',
    required: false,
    group: 'pre-construction',
  },
  {
    id: 'scheduleDevelopment',
    type: 'checkbox',
    label: 'Include schedule development services',
    required: false,
    group: 'pre-construction',
  },
  {
    id: 'valueEngineering',
    type: 'checkbox',
    label: 'Include value engineering services',
    required: false,
    group: 'pre-construction',
  },
  {
    id: 'permitAssistance',
    type: 'checkbox',
    label: 'Include permit assistance services',
    required: false,
    group: 'pre-construction',
  },
  {
    id: 'projectSupervision',
    type: 'checkbox',
    label: 'Include project supervision',
    required: false,
    group: 'construction',
  },
  {
    id: 'contractorManagement',
    type: 'checkbox',
    label: 'Include contractor management',
    required: false,
    group: 'construction',
  },
  {
    id: 'qualityControl',
    type: 'checkbox',
    label: 'Include quality control services',
    required: false,
    group: 'construction',
  },
  {
    id: 'safetyManagement',
    type: 'checkbox',
    label: 'Include safety management',
    required: false,
    group: 'construction',
  },
  {
    id: 'progressReporting',
    type: 'checkbox',
    label: 'Include progress reporting',
    required: false,
    group: 'construction',
  },
  {
    id: 'changeOrderManagement',
    type: 'checkbox',
    label: 'Include change order management',
    required: false,
    group: 'construction',
  },
  {
    id: 'finalInspections',
    type: 'checkbox',
    label: 'Include final inspections',
    required: false,
    group: 'post-construction',
  },
  {
    id: 'warrantyManagement',
    type: 'checkbox',
    label: 'Include warranty management',
    required: false,
    group: 'post-construction',
  },
  {
    id: 'closeoutDocumentation',
    type: 'checkbox',
    label: 'Include closeout documentation',
    required: false,
    group: 'post-construction',
  },
  {
    id: 'contractDate',
    type: 'date',
    label: 'Contract Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'serviceCommencementDate',
    type: 'date',
    label: 'Service Commencement Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'projectCompletionDate',
    type: 'date',
    label: 'Project Completion Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'compensationType',
    type: 'select',
    label: 'Compensation Type',
    options: [
      { value: 'fixed-fee', label: 'Fixed Fee' },
      { value: 'percentage-of-cost', label: 'Percentage of Construction Cost' },
      { value: 'cost-plus-fee', label: 'Cost Plus Fee' },
      { value: 'hourly-rate', label: 'Hourly Rate' },
      { value: 'lump-sum', label: 'Lump Sum' },
    ],
    required: true,
    group: 'compensation',
  },
  {
    id: 'managementFee',
    type: 'text',
    label: 'Management Fee',
    placeholder: 'Enter fee amount or percentage',
    required: true,
    group: 'compensation',
  },
  {
    id: 'feePercentage',
    type: 'text',
    label: 'Fee Percentage',
    placeholder: 'e.g., 3.5%',
    required: false,
    group: 'compensation',
    dependsOn: 'compensationType',
  },
  {
    id: 'reimbursableExpenses',
    type: 'checkbox',
    label: 'Include reimbursable expenses',
    required: false,
    group: 'compensation',
  },
  {
    id: 'projectBudget',
    type: 'text',
    label: 'Project Budget',
    placeholder: 'Total project budget amount',
    required: false,
    group: 'budget',
  },
  {
    id: 'budgetReporting',
    type: 'checkbox',
    label: 'Require budget reporting',
    required: false,
    group: 'budget',
  },
  {
    id: 'costReportingFrequency',
    type: 'select',
    label: 'Cost Reporting Frequency',
    options: [
      { value: 'weekly', label: 'Weekly' },
      { value: 'bi-weekly', label: 'Bi-weekly' },
      { value: 'monthly', label: 'Monthly' },
    ],
    required: false,
    group: 'budget',
    dependsOn: 'budgetReporting',
  },
  {
    id: 'contractorSelectionMethod',
    type: 'select',
    label: 'Contractor Selection Method',
    options: [
      { value: 'owner-selects', label: 'Owner Selects' },
      { value: 'manager-recommends', label: 'Manager Recommends' },
      { value: 'joint-selection', label: 'Joint Selection' },
    ],
    required: true,
    group: 'authority',
  },
  {
    id: 'purchasingAuthority',
    type: 'text',
    label: 'Purchasing Authority Limit',
    placeholder: 'Maximum amount manager can authorize',
    required: false,
    group: 'authority',
  },
  {
    id: 'changeOrderAuthority',
    type: 'text',
    label: 'Change Order Authority Limit',
    placeholder: 'Maximum change order amount',
    required: false,
    group: 'authority',
  },
  {
    id: 'meetingSchedule',
    type: 'text',
    label: 'Meeting Schedule',
    placeholder: 'e.g., Weekly progress meetings',
    required: false,
    group: 'performance',
  },
  {
    id: 'riskManagementPlan',
    type: 'checkbox',
    label: 'Include risk management plan',
    required: false,
    group: 'risk',
  },
  {
    id: 'contingencyManagement',
    type: 'checkbox',
    label: 'Include contingency management',
    required: false,
    group: 'risk',
  },
  {
    id: 'generalLiabilityInsurance',
    type: 'text',
    label: 'General Liability Insurance Amount',
    placeholder: 'Minimum coverage amount',
    required: true,
    group: 'insurance',
  },
  {
    id: 'professionalLiabilityInsurance',
    type: 'text',
    label: 'Professional Liability Insurance',
    placeholder: 'Professional liability coverage amount',
    required: false,
    group: 'insurance',
  },
  {
    id: 'errorAndOmissionsInsurance',
    type: 'checkbox',
    label: 'Require errors and omissions insurance',
    required: false,
    group: 'insurance',
  },
  {
    id: 'workersCompensation',
    type: 'checkbox',
    label: 'Require workers compensation insurance',
    required: false,
    group: 'insurance',
  },
  {
    id: 'managerIndemnifiesOwner',
    type: 'checkbox',
    label: 'Manager indemnifies owner',
    required: false,
    group: 'indemnification',
  },
  {
    id: 'intellectualPropertyRights',
    type: 'select',
    label: 'Intellectual Property Rights',
    options: [
      { value: 'owner-retains', label: 'Owner Retains' },
      { value: 'manager-retains', label: 'Manager Retains' },
      { value: 'shared', label: 'Shared' },
    ],
    required: true,
    group: 'intellectual-property',
  },
  {
    id: 'workProductOwnership',
    type: 'select',
    label: 'Work Product Ownership',
    options: [
      { value: 'owner', label: 'Owner' },
      { value: 'manager', label: 'Manager' },
      { value: 'shared', label: 'Shared' },
    ],
    required: true,
    group: 'intellectual-property',
  },
  {
    id: 'confidentialityClause',
    type: 'checkbox',
    label: 'Include confidentiality clause',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'proprietaryInformationProtection',
    type: 'checkbox',
    label: 'Include proprietary information protection',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'terminationForConvenience',
    type: 'checkbox',
    label: 'Allow termination for convenience',
    required: false,
    group: 'termination',
  },
  {
    id: 'terminationForCause',
    type: 'checkbox',
    label: 'Allow termination for cause',
    required: false,
    group: 'termination',
  },
  {
    id: 'terminationNotice',
    type: 'text',
    label: 'Termination Notice Period',
    placeholder: 'e.g., 30 days written notice',
    required: false,
    group: 'termination',
  },
  {
    id: 'disputeResolutionMethod',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'negotiation', label: 'Negotiation' },
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'litigation', label: 'Court Litigation' },
    ],
    required: true,
    group: 'disputes',
  },
  {
    id: 'projectManagementSoftware',
    type: 'text',
    label: 'Project Management Software',
    placeholder: 'Software platform to be used',
    required: false,
    group: 'technology',
  },
  {
    id: 'documentManagementSystem',
    type: 'checkbox',
    label: 'Use document management system',
    required: false,
    group: 'technology',
  },
  {
    id: 'environmentalCompliance',
    type: 'checkbox',
    label: 'Include environmental compliance requirements',
    required: false,
    group: 'sustainability',
  },
  {
    id: 'leedCertificationSupport',
    type: 'checkbox',
    label: 'Include LEED certification support',
    required: false,
    group: 'sustainability',
  },
  {
    id: 'forceMajeureClause',
    type: 'checkbox',
    label: 'Include force majeure clause',
    required: false,
    group: 'force-majeure',
  },
  {
    id: 'requireOwnerSignature',
    type: 'checkbox',
    label: 'Require owner signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireManagerSignature',
    type: 'checkbox',
    label: 'Require manager signature',
    required: false,
    group: 'signatures',
  },
];