// src/lib/documents/us/home-improvement-contract/questions.ts
import type { FormQuestion } from '@/types/documents';

export const homeImprovementContractQuestions: FormQuestion[] = [
  {
    id: 'homeownerName',
    type: 'text',
    label: 'Homeowner Name',
    placeholder: 'Enter homeowner full name',
    required: true,
    group: 'homeowner',
  },
  {
    id: 'homeownerAddress',
    type: 'text',
    label: 'Homeowner Address',
    placeholder: 'Enter complete homeowner address',
    required: true,
    group: 'homeowner',
  },
  {
    id: 'homeownerPhone',
    type: 'text',
    label: 'Homeowner Phone',
    placeholder: 'Enter phone number',
    required: true,
    group: 'homeowner',
  },
  {
    id: 'homeownerEmail',
    type: 'email',
    label: 'Homeowner Email',
    placeholder: 'Enter email address',
    required: false,
    group: 'homeowner',
  },
  {
    id: 'contractorName',
    type: 'text',
    label: 'Contractor Name',
    placeholder: 'Enter contractor/company name',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorAddress',
    type: 'text',
    label: 'Contractor Address',
    placeholder: 'Enter complete contractor address',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorPhone',
    type: 'text',
    label: 'Contractor Phone',
    placeholder: 'Enter phone number',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorEmail',
    type: 'email',
    label: 'Contractor Email',
    placeholder: 'Enter email address',
    required: false,
    group: 'contractor',
  },
  {
    id: 'contractorLicense',
    type: 'text',
    label: 'Contractor License Number',
    placeholder: 'Enter license number if applicable',
    required: false,
    group: 'contractor',
  },
  {
    id: 'projectAddress',
    type: 'text',
    label: 'Project Address',
    placeholder: 'Where the work will be performed',
    required: true,
    group: 'project',
  },
  {
    id: 'projectDescription',
    type: 'textarea',
    label: 'Project Description',
    placeholder: 'Detailed description of work to be performed',
    required: true,
    group: 'project',
  },
  {
    id: 'projectType',
    type: 'select',
    label: 'Project Type',
    options: [
      { value: 'kitchen-remodel', label: 'Kitchen Remodel' },
      { value: 'bathroom-remodel', label: 'Bathroom Remodel' },
      { value: 'addition', label: 'Home Addition' },
      { value: 'roofing', label: 'Roofing' },
      { value: 'flooring', label: 'Flooring' },
      { value: 'painting', label: 'Painting' },
      { value: 'electrical', label: 'Electrical' },
      { value: 'plumbing', label: 'Plumbing' },
      { value: 'hvac', label: 'HVAC' },
      { value: 'landscaping', label: 'Landscaping' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'project',
  },
  {
    id: 'contractDate',
    type: 'date',
    label: 'Contract Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'startDate',
    type: 'date',
    label: 'Project Start Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'completionDate',
    type: 'date',
    label: 'Project Completion Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'contractPrice',
    type: 'text',
    label: 'Total Contract Price',
    placeholder: 'Enter total project cost',
    required: true,
    group: 'financial',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'upfront', label: 'Payment in Full Upfront' },
      { value: 'progress-payments', label: 'Progress Payments' },
      { value: 'completion', label: 'Payment Upon Completion' },
      { value: 'custom', label: 'Custom Schedule' },
    ],
    required: true,
    group: 'financial',
  },
  {
    id: 'downPayment',
    type: 'text',
    label: 'Down Payment Amount',
    placeholder: 'Initial payment amount',
    required: false,
    group: 'financial',
  },
  {
    id: 'materialsIncluded',
    type: 'checkbox',
    label: 'Materials included in contract price',
    required: false,
    group: 'materials',
  },
  {
    id: 'laborIncluded',
    type: 'checkbox',
    label: 'Labor included in contract price',
    required: false,
    group: 'materials',
  },
  {
    id: 'materialAllowance',
    type: 'text',
    label: 'Material Allowance',
    placeholder: 'Budget allocated for materials',
    required: false,
    group: 'materials',
  },
  {
    id: 'materialUpgrades',
    type: 'checkbox',
    label: 'Allow material upgrades at additional cost',
    required: false,
    group: 'materials',
  },
  {
    id: 'permitsRequired',
    type: 'checkbox',
    label: 'Building permits required',
    required: false,
    group: 'permits',
  },
  {
    id: 'permitResponsibility',
    type: 'select',
    label: 'Permit Responsibility',
    options: [
      { value: 'homeowner', label: 'Homeowner Responsible' },
      { value: 'contractor', label: 'Contractor Responsible' },
      { value: 'shared', label: 'Shared Responsibility' },
    ],
    required: false,
    group: 'permits',
    dependsOn: 'permitsRequired',
  },
  {
    id: 'permitCosts',
    type: 'select',
    label: 'Permit Costs',
    options: [
      { value: 'homeowner', label: 'Homeowner Pays' },
      { value: 'contractor', label: 'Contractor Pays' },
      { value: 'included', label: 'Included in Contract Price' },
    ],
    required: false,
    group: 'permits',
    dependsOn: 'permitsRequired',
  },
  {
    id: 'contractorInsuranceRequired',
    type: 'checkbox',
    label: 'Require contractor insurance',
    required: false,
    group: 'insurance',
  },
  {
    id: 'liabilityInsurance',
    type: 'text',
    label: 'Liability Insurance Amount',
    placeholder: 'Minimum coverage amount',
    required: false,
    group: 'insurance',
    dependsOn: 'contractorInsuranceRequired',
  },
  {
    id: 'workersCompensation',
    type: 'checkbox',
    label: 'Require workers compensation insurance',
    required: false,
    group: 'insurance',
  },
  {
    id: 'bondingRequired',
    type: 'checkbox',
    label: 'Require contractor bonding',
    required: false,
    group: 'insurance',
  },
  {
    id: 'bondAmount',
    type: 'text',
    label: 'Bond Amount',
    placeholder: 'Performance bond amount',
    required: false,
    group: 'insurance',
    dependsOn: 'bondingRequired',
  },
  {
    id: 'workSpecifications',
    type: 'textarea',
    label: 'Work Specifications',
    placeholder: 'Detailed specifications for work quality and methods',
    required: false,
    group: 'specifications',
  },
  {
    id: 'materialSpecifications',
    type: 'textarea',
    label: 'Material Specifications',
    placeholder: 'Specific materials, brands, models to be used',
    required: false,
    group: 'specifications',
  },
  {
    id: 'codeCompliance',
    type: 'checkbox',
    label: 'Work must comply with building codes',
    required: false,
    group: 'specifications',
  },
  {
    id: 'workingHours',
    type: 'text',
    label: 'Working Hours',
    placeholder: 'e.g., 8 AM - 5 PM',
    required: false,
    group: 'schedule',
  },
  {
    id: 'workingDays',
    type: 'text',
    label: 'Working Days',
    placeholder: 'e.g., Monday through Friday',
    required: false,
    group: 'schedule',
  },
  {
    id: 'weatherDelays',
    type: 'checkbox',
    label: 'Allow extensions for weather delays',
    required: false,
    group: 'schedule',
  },
  {
    id: 'changeOrderProcess',
    type: 'checkbox',
    label: 'Include change order process',
    required: false,
    group: 'changes',
  },
  {
    id: 'changeOrderApproval',
    type: 'select',
    label: 'Change Order Approval Method',
    options: [
      { value: 'written-only', label: 'Written Approval Only' },
      { value: 'verbal-allowed', label: 'Verbal Approval Allowed' },
      { value: 'email-allowed', label: 'Email Approval Allowed' },
    ],
    required: false,
    group: 'changes',
    dependsOn: 'changeOrderProcess',
  },
  {
    id: 'dailyCleanup',
    type: 'checkbox',
    label: 'Require daily cleanup',
    required: false,
    group: 'cleanup',
  },
  {
    id: 'finalCleanup',
    type: 'checkbox',
    label: 'Require final cleanup',
    required: false,
    group: 'cleanup',
  },
  {
    id: 'wasteDisposal',
    type: 'select',
    label: 'Waste Disposal Responsibility',
    options: [
      { value: 'contractor', label: 'Contractor Responsible' },
      { value: 'homeowner', label: 'Homeowner Responsible' },
      { value: 'shared', label: 'Shared Responsibility' },
    ],
    required: false,
    group: 'cleanup',
  },
  {
    id: 'dumpsterProvision',
    type: 'checkbox',
    label: 'Contractor provides dumpster',
    required: false,
    group: 'cleanup',
  },
  {
    id: 'workmanshipWarranty',
    type: 'checkbox',
    label: 'Include workmanship warranty',
    required: false,
    group: 'warranty',
  },
  {
    id: 'warrantyPeriod',
    type: 'text',
    label: 'Warranty Period',
    placeholder: 'e.g., 1 year, 2 years',
    required: false,
    group: 'warranty',
    dependsOn: 'workmanshipWarranty',
  },
  {
    id: 'materialWarranties',
    type: 'checkbox',
    label: 'Transfer material warranties to homeowner',
    required: false,
    group: 'warranty',
  },
  {
    id: 'propertyProtection',
    type: 'checkbox',
    label: 'Protect existing property during work',
    required: false,
    group: 'protection',
  },
  {
    id: 'existingStructureProtection',
    type: 'text',
    label: 'Existing Structure Protection',
    placeholder: 'Describe protection measures for existing structures',
    required: false,
    group: 'protection',
  },
  {
    id: 'utilityProtection',
    type: 'checkbox',
    label: 'Protect existing utilities',
    required: false,
    group: 'protection',
  },
  {
    id: 'subcontractorsAllowed',
    type: 'checkbox',
    label: 'Allow use of subcontractors',
    required: false,
    group: 'subcontractors',
  },
  {
    id: 'subcontractorApproval',
    type: 'checkbox',
    label: 'Require homeowner approval of subcontractors',
    required: false,
    group: 'subcontractors',
    dependsOn: 'subcontractorsAllowed',
  },
  {
    id: 'subcontractorInsurance',
    type: 'checkbox',
    label: 'Require subcontractor insurance',
    required: false,
    group: 'subcontractors',
    dependsOn: 'subcontractorsAllowed',
  },
  {
    id: 'homeownerOccupancy',
    type: 'checkbox',
    label: 'Homeowner will occupy during construction',
    required: false,
    group: 'access',
  },
  {
    id: 'accessHours',
    type: 'text',
    label: 'Property Access Hours',
    placeholder: 'When contractor can access property',
    required: false,
    group: 'access',
  },
  {
    id: 'keyProvision',
    type: 'checkbox',
    label: 'Provide keys to contractor',
    required: false,
    group: 'access',
  },
  {
    id: 'unforeseeableConditions',
    type: 'checkbox',
    label: 'Include unforeseeable conditions clause',
    required: false,
    group: 'delays',
  },
  {
    id: 'liquidatedDamages',
    type: 'checkbox',
    label: 'Include liquidated damages for delays',
    required: false,
    group: 'delays',
  },
  {
    id: 'terminationRights',
    type: 'checkbox',
    label: 'Include termination rights',
    required: false,
    group: 'termination',
  },
  {
    id: 'terminationNotice',
    type: 'text',
    label: 'Termination Notice Period',
    placeholder: 'e.g., 7 days written notice',
    required: false,
    group: 'termination',
    dependsOn: 'terminationRights',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'litigation', label: 'Court Litigation' },
    ],
    required: false,
    group: 'disputes',
  },
  {
    id: 'attorneyFees',
    type: 'checkbox',
    label: 'Include attorney fees clause',
    required: false,
    group: 'disputes',
  },
  {
    id: 'lienWaiver',
    type: 'checkbox',
    label: 'Require lien waivers',
    required: false,
    group: 'liens',
  },
  {
    id: 'lienWaiverTiming',
    type: 'select',
    label: 'Lien Waiver Timing',
    options: [
      { value: 'progress-payments', label: 'With Progress Payments' },
      { value: 'final-payment', label: 'With Final Payment' },
      { value: 'both', label: 'Both Progress and Final' },
    ],
    required: false,
    group: 'liens',
    dependsOn: 'lienWaiver',
  },
  {
    id: 'leadPaintDisclosure',
    type: 'checkbox',
    label: 'Include lead paint disclosure (pre-1978 homes)',
    required: false,
    group: 'environmental',
  },
  {
    id: 'asbestosDisclosure',
    type: 'checkbox',
    label: 'Include asbestos disclosure',
    required: false,
    group: 'environmental',
  },
  {
    id: 'hazardousMaterials',
    type: 'checkbox',
    label: 'Address hazardous materials handling',
    required: false,
    group: 'environmental',
  },
  {
    id: 'finalInspection',
    type: 'checkbox',
    label: 'Require final inspection',
    required: false,
    group: 'completion',
  },
  {
    id: 'punchList',
    type: 'checkbox',
    label: 'Include punch list process',
    required: false,
    group: 'completion',
  },
  {
    id: 'finalAcceptance',
    type: 'checkbox',
    label: 'Require written final acceptance',
    required: false,
    group: 'completion',
  },
  {
    id: 'plansAndSpecifications',
    type: 'checkbox',
    label: 'Attach plans and specifications',
    required: false,
    group: 'documentation',
  },
  {
    id: 'materialsList',
    type: 'checkbox',
    label: 'Attach materials list',
    required: false,
    group: 'documentation',
  },
  {
    id: 'photoDocumentation',
    type: 'checkbox',
    label: 'Require photo documentation',
    required: false,
    group: 'documentation',
  },
  {
    id: 'requireHomeownerSignature',
    type: 'checkbox',
    label: 'Require homeowner signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireContractorSignature',
    type: 'checkbox',
    label: 'Require contractor signature',
    required: false,
    group: 'signatures',
  },
];