import type { Question } from '@/types/documents';

export const collectionLetterQuestions: Question[] = [
  { id: 'date', label: 'Letter Date', type: 'date', required: true },
  { id: 'creditorName', label: 'Creditor Name', type: 'text', required: true },
  {
    id: 'creditorAddress',
    label: 'Creditor Address',
    type: 'text',
    required: true,
    placeholder: 'Street, City, State, ZIP',
  },
  { id: 'debtorName', label: 'Debtor Name', type: 'text', required: true },
  {
    id: 'debtorAddress',
    label: 'Debtor Address',
    type: 'text',
    required: true,
    placeholder: 'Street, City, State, ZIP',
  },
  {
    id: 'originalDebtAmount',
    label: 'Original Debt Amount',
    type: 'number',
    required: true,
    placeholder: 'e.g., 5000',
  },
  {
    id: 'currentBalance',
    label: 'Current Balance',
    type: 'number',
    required: true,
    placeholder: 'e.g., 5500',
  },
  {
    id: 'accountNumber',
    label: 'Account Number',
    type: 'text',
    required: true,
    placeholder: 'Account or reference number',
  },
  { id: 'dueDate', label: 'Original Due Date', type: 'date', required: true },
  {
    id: 'daysPastDue',
    label: 'Days Past Due',
    type: 'number',
    required: true,
    placeholder: 'e.g., 45',
  },
  {
    id: 'collectionType',
    label: 'Collection Type',
    type: 'select',
    required: true,
    options: [
      { value: 'First Notice', label: 'First Notice' },
      { value: 'Second Notice', label: 'Second Notice' },
      { value: 'Final Notice', label: 'Final Notice' },
      { value: 'Pre-Legal', label: 'Pre-Legal Notice' },
    ],
  },
  {
    id: 'responseDeadline',
    label: 'Response Deadline',
    type: 'date',
    required: true,
  },
  {
    id: 'lateFees',
    label: 'Late Fees',
    type: 'number',
    required: false,
    placeholder: 'e.g., 50',
  },
  {
    id: 'interestCharges',
    label: 'Interest Charges',
    type: 'number',
    required: false,
    placeholder: 'e.g., 150',
  },
  {
    id: 'totalAmountDue',
    label: 'Total Amount Due',
    type: 'number',
    required: true,
    placeholder: 'Including all fees and interest',
  },
  {
    id: 'contactPhone',
    label: 'Contact Phone',
    type: 'text',
    required: true,
    placeholder: '(555) 123-4567',
  },
  {
    id: 'contactEmail',
    label: 'Contact Email',
    type: 'email',
    required: false,
    placeholder: 'collections@company.com',
  },
  {
    id: 'legalConsequences',
    label: 'Legal Consequences',
    type: 'textarea',
    required: true,
    placeholder: 'Describe potential legal actions if debt remains unpaid...',
  },
  {
    id: 'disputeRights',
    label: 'Include Dispute Rights Notice',
    type: 'boolean',
    required: true,
    tooltip: 'Whether to include information about debt dispute rights',
  },
  {
    id: 'validationPeriod',
    label: 'Validation Period (Days)',
    type: 'number',
    required: false,
    tooltip: 'Days debtor has to request debt validation',
  },
];
