// src/lib/documents/us/general-liability-waiver/questions.ts
import type { FormQuestion } from '@/types/documents';

export const generalLiabilityWaiverQuestions: FormQuestion[] = [
  {
    id: 'organizationName',
    type: 'text',
    label: 'Organization Name',
    placeholder: 'Enter organization or business name',
    required: true,
    group: 'organization',
  },
  {
    id: 'organizationAddress',
    type: 'text',
    label: 'Organization Address',
    placeholder: 'Enter complete organization address',
    required: true,
    group: 'organization',
  },
  {
    id: 'organizationPhone',
    type: 'text',
    label: 'Organization Phone',
    placeholder: 'Enter phone number',
    required: false,
    group: 'organization',
  },
  {
    id: 'organizationEmail',
    type: 'email',
    label: 'Organization Email',
    placeholder: 'Enter email address',
    required: false,
    group: 'organization',
  },
  {
    id: 'activityName',
    type: 'text',
    label: 'Activity/Event Name',
    placeholder: 'Enter name of activity or event',
    required: true,
    group: 'activity',
  },
  {
    id: 'activityDescription',
    type: 'textarea',
    label: 'Activity Description',
    placeholder: 'Describe the activity, service, or event',
    required: true,
    group: 'activity',
  },
  {
    id: 'activityLocation',
    type: 'text',
    label: 'Activity Location',
    placeholder: 'Where will the activity take place?',
    required: true,
    group: 'activity',
  },
  {
    id: 'activityDate',
    type: 'text',
    label: 'Activity Date',
    placeholder: 'Date or date range of activity',
    required: false,
    group: 'activity',
  },
  {
    id: 'activityDuration',
    type: 'text',
    label: 'Activity Duration',
    placeholder: 'How long will the activity last?',
    required: false,
    group: 'activity',
  },
  {
    id: 'collectParticipantName',
    type: 'checkbox',
    label: 'Collect participant name',
    required: false,
    group: 'participant-data',
  },
  {
    id: 'collectParticipantAddress',
    type: 'checkbox',
    label: 'Collect participant address',
    required: false,
    group: 'participant-data',
  },
  {
    id: 'collectParticipantPhone',
    type: 'checkbox',
    label: 'Collect participant phone',
    required: false,
    group: 'participant-data',
  },
  {
    id: 'collectParticipantEmail',
    type: 'checkbox',
    label: 'Collect participant email',
    required: false,
    group: 'participant-data',
  },
  {
    id: 'collectEmergencyContact',
    type: 'checkbox',
    label: 'Collect emergency contact information',
    required: false,
    group: 'participant-data',
  },
  {
    id: 'collectMedicalInformation',
    type: 'checkbox',
    label: 'Collect medical information',
    required: false,
    group: 'participant-data',
  },
  {
    id: 'minimumAge',
    type: 'text',
    label: 'Minimum Age Requirement',
    placeholder: 'e.g., 18 years old',
    required: false,
    group: 'age-capacity',
  },
  {
    id: 'minorParticipants',
    type: 'checkbox',
    label: 'Allow minor participants',
    required: false,
    group: 'age-capacity',
  },
  {
    id: 'parentGuardianSignature',
    type: 'checkbox',
    label: 'Require parent/guardian signature for minors',
    required: false,
    group: 'age-capacity',
    dependsOn: 'minorParticipants',
  },
  {
    id: 'capacityVerification',
    type: 'checkbox',
    label: 'Verify legal capacity to sign',
    required: false,
    group: 'age-capacity',
  },
  {
    id: 'inherentRisks',
    type: 'multiselect',
    label: 'Inherent Risks',
    options: [
      { value: 'physical-injury', label: 'Physical Injury' },
      { value: 'property-damage', label: 'Property Damage' },
      { value: 'equipment-failure', label: 'Equipment Failure' },
      { value: 'weather-conditions', label: 'Weather Conditions' },
      { value: 'other-participants', label: 'Actions of Other Participants' },
      { value: 'facility-conditions', label: 'Facility Conditions' },
      { value: 'transportation', label: 'Transportation Risks' },
    ],
    required: false,
    group: 'risks',
  },
  {
    id: 'specificRisks',
    type: 'textarea',
    label: 'Specific Activity Risks',
    placeholder: 'Describe specific risks related to this activity',
    required: false,
    group: 'risks',
  },
  {
    id: 'riskAcknowledgment',
    type: 'checkbox',
    label: 'Require risk acknowledgment',
    required: false,
    group: 'risks',
  },
  {
    id: 'assumptionOfRisk',
    type: 'checkbox',
    label: 'Include assumption of risk clause',
    required: false,
    group: 'risks',
  },
  {
    id: 'waiverScope',
    type: 'select',
    label: 'Waiver Scope',
    options: [
      { value: 'negligence-only', label: 'Negligence Only' },
      { value: 'all-claims', label: 'All Claims' },
      { value: 'specific-claims', label: 'Specific Claims' },
    ],
    required: false,
    group: 'waiver-scope',
  },
  {
    id: 'includeNegligence',
    type: 'checkbox',
    label: 'Include ordinary negligence',
    required: false,
    group: 'waiver-scope',
  },
  {
    id: 'includeGrossNegligence',
    type: 'checkbox',
    label: 'Include gross negligence',
    required: false,
    group: 'waiver-scope',
  },
  {
    id: 'includeIntentionalActs',
    type: 'checkbox',
    label: 'Include intentional acts',
    required: false,
    group: 'waiver-scope',
  },
  {
    id: 'futureClaimsWaiver',
    type: 'checkbox',
    label: 'Waive future claims',
    required: false,
    group: 'waiver-scope',
  },
  {
    id: 'releasedParties',
    type: 'multiselect',
    label: 'Released Parties',
    options: [
      { value: 'organization', label: 'Organization' },
      { value: 'owners', label: 'Owners' },
      { value: 'directors', label: 'Directors' },
      { value: 'officers', label: 'Officers' },
      { value: 'managers', label: 'Managers' },
      { value: 'instructors', label: 'Instructors' },
      { value: 'contractors', label: 'Contractors' },
    ],
    required: false,
    group: 'released-parties',
  },
  {
    id: 'includeEmployees',
    type: 'checkbox',
    label: 'Include employees',
    required: false,
    group: 'released-parties',
  },
  {
    id: 'includeVolunteers',
    type: 'checkbox',
    label: 'Include volunteers',
    required: false,
    group: 'released-parties',
  },
  {
    id: 'includeAgents',
    type: 'checkbox',
    label: 'Include agents and representatives',
    required: false,
    group: 'released-parties',
  },
  {
    id: 'includeAffiliates',
    type: 'checkbox',
    label: 'Include affiliates',
    required: false,
    group: 'released-parties',
  },
  {
    id: 'includeSponsors',
    type: 'checkbox',
    label: 'Include sponsors',
    required: false,
    group: 'released-parties',
  },
  {
    id: 'personalInjuryClaims',
    type: 'checkbox',
    label: 'Release personal injury claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'propertyDamageClaims',
    type: 'checkbox',
    label: 'Release property damage claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'emotionalDistressClaims',
    type: 'checkbox',
    label: 'Release emotional distress claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'economicLossClaims',
    type: 'checkbox',
    label: 'Release economic loss claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'wrongfulDeathClaims',
    type: 'checkbox',
    label: 'Release wrongful death claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'indemnificationClause',
    type: 'checkbox',
    label: 'Include indemnification clause',
    required: false,
    group: 'indemnification',
  },
  {
    id: 'indemnifyAgainst',
    type: 'multiselect',
    label: 'Indemnify Against',
    options: [
      { value: 'legal-costs', label: 'Legal Costs' },
      { value: 'damages', label: 'Damages' },
      { value: 'settlements', label: 'Settlements' },
      { value: 'judgments', label: 'Judgments' },
      { value: 'expenses', label: 'Expenses' },
    ],
    required: false,
    group: 'indemnification',
    dependsOn: 'indemnificationClause',
  },
  {
    id: 'attorneyFeesIndemnity',
    type: 'checkbox',
    label: 'Include attorney fees in indemnity',
    required: false,
    group: 'indemnification',
  },
  {
    id: 'medicalTreatmentConsent',
    type: 'checkbox',
    label: 'Include medical treatment consent',
    required: false,
    group: 'medical',
  },
  {
    id: 'emergencyMedicalConsent',
    type: 'checkbox',
    label: 'Include emergency medical consent',
    required: false,
    group: 'medical',
  },
  {
    id: 'medicalInsuranceDisclaimer',
    type: 'checkbox',
    label: 'Include medical insurance disclaimer',
    required: false,
    group: 'medical',
  },
  {
    id: 'medicalExpenseResponsibility',
    type: 'select',
    label: 'Medical Expense Responsibility',
    options: [
      { value: 'participant', label: 'Participant' },
      { value: 'organization', label: 'Organization' },
      { value: 'insurance', label: 'Insurance' },
    ],
    required: false,
    group: 'medical',
  },
  {
    id: 'equipmentUse',
    type: 'checkbox',
    label: 'Activity involves equipment use',
    required: false,
    group: 'equipment',
  },
  {
    id: 'equipmentRisks',
    type: 'textarea',
    label: 'Equipment Risks',
    placeholder: 'Describe risks related to equipment use',
    required: false,
    group: 'equipment',
    dependsOn: 'equipmentUse',
  },
  {
    id: 'personalPropertyDisclaimer',
    type: 'checkbox',
    label: 'Include personal property disclaimer',
    required: false,
    group: 'equipment',
  },
  {
    id: 'equipmentInspection',
    type: 'checkbox',
    label: 'Require equipment inspection',
    required: false,
    group: 'equipment',
  },
  {
    id: 'photographyConsent',
    type: 'checkbox',
    label: 'Include photography consent',
    required: false,
    group: 'media',
  },
  {
    id: 'mediaUseConsent',
    type: 'checkbox',
    label: 'Include media use consent',
    required: false,
    group: 'media',
  },
  {
    id: 'publicityRights',
    type: 'checkbox',
    label: 'Include publicity rights waiver',
    required: false,
    group: 'media',
  },
  {
    id: 'socialMediaPolicy',
    type: 'checkbox',
    label: 'Include social media policy',
    required: false,
    group: 'media',
  },
  {
    id: 'alcoholPolicy',
    type: 'checkbox',
    label: 'Include alcohol policy',
    required: false,
    group: 'substances',
  },
  {
    id: 'substancePolicy',
    type: 'checkbox',
    label: 'Include substance abuse policy',
    required: false,
    group: 'substances',
  },
  {
    id: 'breathalyzerConsent',
    type: 'checkbox',
    label: 'Include breathalyzer consent',
    required: false,
    group: 'substances',
  },
  {
    id: 'transportationWaiver',
    type: 'checkbox',
    label: 'Include transportation waiver',
    required: false,
    group: 'transportation',
  },
  {
    id: 'vehicleUse',
    type: 'checkbox',
    label: 'Activity involves vehicle use',
    required: false,
    group: 'transportation',
  },
  {
    id: 'drivingRequirements',
    type: 'text',
    label: 'Driving Requirements',
    placeholder: 'e.g., Valid license, insurance',
    required: false,
    group: 'transportation',
    dependsOn: 'vehicleUse',
  },
  {
    id: 'transportationRisks',
    type: 'textarea',
    label: 'Transportation Risks',
    placeholder: 'Describe transportation-related risks',
    required: false,
    group: 'transportation',
  },
  {
    id: 'weatherConditions',
    type: 'checkbox',
    label: 'Include weather condition warnings',
    required: false,
    group: 'conditions',
  },
  {
    id: 'equipmentConditions',
    type: 'checkbox',
    label: 'Include equipment condition warnings',
    required: false,
    group: 'conditions',
  },
  {
    id: 'facilityConditions',
    type: 'checkbox',
    label: 'Include facility condition warnings',
    required: false,
    group: 'conditions',
  },
  {
    id: 'otherParticipants',
    type: 'checkbox',
    label: 'Include warnings about other participants',
    required: false,
    group: 'conditions',
  },
  {
    id: 'rulesCompliance',
    type: 'checkbox',
    label: 'Require compliance with rules',
    required: false,
    group: 'compliance',
  },
  {
    id: 'safetyInstructions',
    type: 'checkbox',
    label: 'Require following safety instructions',
    required: false,
    group: 'compliance',
  },
  {
    id: 'supervisorInstructions',
    type: 'checkbox',
    label: 'Require following supervisor instructions',
    required: false,
    group: 'compliance',
  },
  {
    id: 'codeOfConduct',
    type: 'checkbox',
    label: 'Include code of conduct',
    required: false,
    group: 'compliance',
  },
  {
    id: 'insuranceRequirement',
    type: 'checkbox',
    label: 'Require participant insurance',
    required: false,
    group: 'insurance',
  },
  {
    id: 'insuranceDisclaimer',
    type: 'checkbox',
    label: 'Include insurance disclaimer',
    required: false,
    group: 'insurance',
  },
  {
    id: 'insuranceCoordination',
    type: 'checkbox',
    label: 'Include insurance coordination clause',
    required: false,
    group: 'insurance',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'e.g., State of California',
    required: false,
    group: 'legal',
  },
  {
    id: 'jurisdiction',
    type: 'text',
    label: 'Jurisdiction',
    placeholder: 'Where disputes will be resolved',
    required: false,
    group: 'legal',
  },
  {
    id: 'venueSelection',
    type: 'text',
    label: 'Venue Selection',
    placeholder: 'Specific court or location',
    required: false,
    group: 'legal',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'litigation', label: 'Court Litigation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'mediation', label: 'Mediation' },
    ],
    required: false,
    group: 'legal',
  },
  {
    id: 'severabilityClause',
    type: 'checkbox',
    label: 'Include severability clause',
    required: false,
    group: 'legal-structure',
  },
  {
    id: 'entireAgreement',
    type: 'checkbox',
    label: 'Include entire agreement clause',
    required: false,
    group: 'legal-structure',
  },
  {
    id: 'modificationRequirements',
    type: 'checkbox',
    label: 'Include modification requirements',
    required: false,
    group: 'legal-structure',
  },
  {
    id: 'bindingEffect',
    type: 'checkbox',
    label: 'Include binding effect clause',
    required: false,
    group: 'legal-structure',
  },
  {
    id: 'readAndUnderstood',
    type: 'checkbox',
    label: 'Require "read and understood" acknowledgment',
    required: false,
    group: 'acknowledgment',
  },
  {
    id: 'voluntaryParticipation',
    type: 'checkbox',
    label: 'Acknowledge voluntary participation',
    required: false,
    group: 'acknowledgment',
  },
  {
    id: 'competentToSign',
    type: 'checkbox',
    label: 'Acknowledge legal competence to sign',
    required: false,
    group: 'acknowledgment',
  },
  {
    id: 'noCoercion',
    type: 'checkbox',
    label: 'Acknowledge no coercion or duress',
    required: false,
    group: 'acknowledgment',
  },
  {
    id: 'pregnancyWarning',
    type: 'checkbox',
    label: 'Include pregnancy warning',
    required: false,
    group: 'special-populations',
  },
  {
    id: 'heartConditionWarning',
    type: 'checkbox',
    label: 'Include heart condition warning',
    required: false,
    group: 'special-populations',
  },
  {
    id: 'physicalLimitationWarning',
    type: 'checkbox',
    label: 'Include physical limitation warning',
    required: false,
    group: 'special-populations',
  },
  {
    id: 'medicationWarning',
    type: 'checkbox',
    label: 'Include medication warning',
    required: false,
    group: 'special-populations',
  },
  {
    id: 'waiverDuration',
    type: 'select',
    label: 'Waiver Duration',
    options: [
      { value: 'single-event', label: 'Single Event' },
      { value: 'multiple-events', label: 'Multiple Events' },
      { value: 'ongoing', label: 'Ongoing' },
      { value: 'specified-period', label: 'Specified Period' },
    ],
    required: false,
    group: 'duration',
  },
  {
    id: 'eventSeries',
    type: 'checkbox',
    label: 'Covers series of events',
    required: false,
    group: 'duration',
  },
  {
    id: 'membershipWaiver',
    type: 'checkbox',
    label: 'Membership-based waiver',
    required: false,
    group: 'duration',
  },
  {
    id: 'assumptionOfRiskClause',
    type: 'checkbox',
    label: 'Include assumption of risk clause',
    required: false,
    group: 'additional-clauses',
  },
  {
    id: 'primaryAssumptionOfRisk',
    type: 'checkbox',
    label: 'Include primary assumption of risk',
    required: false,
    group: 'additional-clauses',
  },
  {
    id: 'secondaryAssumptionOfRisk',
    type: 'checkbox',
    label: 'Include secondary assumption of risk',
    required: false,
    group: 'additional-clauses',
  },
  {
    id: 'requireParticipantSignature',
    type: 'checkbox',
    label: 'Require participant signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireParentSignature',
    type: 'checkbox',
    label: 'Require parent/guardian signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireWitnessSignature',
    type: 'checkbox',
    label: 'Require witness signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireNotarization',
    type: 'checkbox',
    label: 'Require notarization',
    required: false,
    group: 'signatures',
  },
  {
    id: 'electronicSignatureAccepted',
    type: 'checkbox',
    label: 'Accept electronic signatures',
    required: false,
    group: 'signatures',
  },
];
