import type { Question } from '@/types/documents';

export const questions: Question[] = [
  {
    id: 'companyName',
    type: 'text',
    label: 'Company Name',
    required: true,
    category: 'Company Information',
  },
  {
    id: 'employeeName',
    type: 'text',
    label: 'Employee Full Name',
    required: true,
    category: 'Employee Information',
  },
  {
    id: 'employeeId',
    type: 'text',
    label: 'Employee ID (Optional)',
    required: false,
    category: 'Employee Information',
  },
  {
    id: 'socialSecurityNumber',
    type: 'text',
    label: 'Social Security Number',
    required: true,
    category: 'Employee Information',
    placeholder: 'XXX-XX-XXXX',
  },
  {
    id: 'bankName',
    type: 'text',
    label: 'Bank Name',
    required: true,
    category: 'Bank Information',
  },
  {
    id: 'bankAddress',
    type: 'text',
    label: 'Bank Address',
    required: true,
    category: 'Bank Information',
  },
  {
    id: 'routingNumber',
    type: 'text',
    label: 'Bank Routing Number',
    required: true,
    category: 'Bank Information',
    placeholder: '9-digit routing number',
  },
  {
    id: 'accountNumber',
    type: 'text',
    label: 'Account Number',
    required: true,
    category: 'Bank Information',
  },
  {
    id: 'accountType',
    type: 'select',
    label: 'Account Type',
    required: true,
    category: 'Bank Information',
    options: ['Checking', 'Savings'],
  },
  {
    id: 'depositType',
    type: 'select',
    label: 'Deposit Type',
    required: true,
    category: 'Deposit Instructions',
    options: ['Full amount', 'Partial amount', 'Split deposit'],
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Effective Date',
    required: true,
    category: 'Authorization',
  },
  {
    id: 'signatureDate',
    type: 'date',
    label: 'Signature Date',
    required: true,
    category: 'Signatures',
  },
];
