// src/lib/documents/us/franchise-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const franchiseAgreementQuestions: FormQuestion[] = [
  {
    id: 'franchisorName',
    type: 'text',
    label: 'Franchisor Name',
    placeholder: 'Enter franchisor company name',
    required: true,
    group: 'franchisor',
  },
  {
    id: 'franchiseeName',
    type: 'text',
    label: 'Franchisee Name',
    placeholder: 'Enter franchisee name',
    required: true,
    group: 'franchisee',
  },
  {
    id: 'franchiseBrandName',
    type: 'text',
    label: 'Franchise Brand Name',
    placeholder: 'Enter franchise brand name',
    required: true,
    group: 'franchise',
  },
  {
    id: 'industryType',
    type: 'select',
    label: 'Industry Type',
    options: [
      { value: 'food-service', label: 'Food Service' },
      { value: 'retail', label: 'Retail' },
      { value: 'automotive', label: 'Automotive' },
      { value: 'health-fitness', label: 'Health & Fitness' },
      { value: 'education', label: 'Education' },
      { value: 'service', label: 'Service' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
    group: 'franchise',
  },
  {
    id: 'territoryDescription',
    type: 'textarea',
    label: 'Territory Description',
    placeholder: 'Describe the franchise territory',
    required: false,
    group: 'territory',
  },
  {
    id: 'exclusiveTerritory',
    type: 'boolean',
    label: 'Exclusive territory rights?',
    required: false,
    group: 'territory',
  },
  {
    id: 'initialFranchiseFee',
    type: 'text',
    label: 'Initial Franchise Fee',
    placeholder: 'Enter initial franchise fee',
    required: false,
    group: 'financial',
  },
  {
    id: 'royaltyFeePercentage',
    type: 'text',
    label: 'Ongoing Royalty Fee (%)',
    placeholder: 'Enter royalty percentage (e.g., 6%)',
    required: false,
    group: 'financial',
  },
  {
    id: 'advertisingFeePercentage',
    type: 'text',
    label: 'Advertising Fee (%)',
    placeholder: 'Enter advertising fee percentage',
    required: false,
    group: 'financial',
  },
  {
    id: 'totalInvestmentMin',
    type: 'text',
    label: 'Minimum Total Investment',
    placeholder: 'Enter minimum investment amount',
    required: false,
    group: 'investment',
  },
  {
    id: 'totalInvestmentMax',
    type: 'text',
    label: 'Maximum Total Investment',
    placeholder: 'Enter maximum investment amount',
    required: false,
    group: 'investment',
  },
  {
    id: 'liquidCapitalRequired',
    type: 'text',
    label: 'Liquid Capital Required',
    placeholder: 'Enter liquid capital requirement',
    required: false,
    group: 'investment',
  },
  {
    id: 'locationApprovalRequired',
    type: 'boolean',
    label: 'Location approval required?',
    required: false,
    group: 'location',
  },
  {
    id: 'realEstateRequirements',
    type: 'textarea',
    label: 'Real Estate Requirements',
    placeholder: 'Describe real estate requirements',
    required: false,
    group: 'location',
  },
  {
    id: 'initialTrainingRequired',
    type: 'boolean',
    label: 'Initial training required?',
    required: false,
    group: 'training',
  },
  {
    id: 'trainingDuration',
    type: 'text',
    label: 'Training Duration',
    placeholder: 'Enter training duration (e.g., 2 weeks)',
    required: false,
    group: 'training',
  },
  {
    id: 'hoursOfOperation',
    type: 'text',
    label: 'Required Hours of Operation',
    placeholder: 'Enter required operating hours',
    required: false,
    group: 'operations',
  },
  {
    id: 'operatingStandards',
    type: 'textarea',
    label: 'Operating Standards',
    placeholder: 'Describe operating standards',
    required: false,
    group: 'operations',
  },
  {
    id: 'nationalAdvertising',
    type: 'boolean',
    label: 'National advertising fund?',
    required: false,
    group: 'marketing',
  },
  {
    id: 'localAdvertisingRequirements',
    type: 'textarea',
    label: 'Local Advertising Requirements',
    placeholder: 'Describe local advertising requirements',
    required: false,
    group: 'marketing',
  },
  {
    id: 'posSystemRequired',
    type: 'boolean',
    label: 'POS system required?',
    required: false,
    group: 'technology',
  },
  {
    id: 'trademarkUsage',
    type: 'boolean',
    label: 'Trademark usage rights?',
    required: false,
    group: 'intellectual',
  },
  {
    id: 'initialTerm',
    type: 'text',
    label: 'Initial Term',
    placeholder: 'Enter initial term (e.g., 10 years)',
    required: false,
    group: 'term',
  },
  {
    id: 'renewalOptions',
    type: 'boolean',
    label: 'Renewal options available?',
    required: false,
    group: 'term',
  },
  {
    id: 'nonCompeteClause',
    type: 'boolean',
    label: 'Non-compete clause?',
    required: false,
    group: 'restrictions',
  },
  {
    id: 'nonCompetePeriod',
    type: 'text',
    label: 'Non-Compete Period',
    placeholder: 'Enter non-compete period',
    required: false,
    group: 'restrictions',
  },
  {
    id: 'transferRights',
    type: 'boolean',
    label: 'Transfer rights allowed?',
    required: false,
    group: 'transfer',
  },
  {
    id: 'transferApproval',
    type: 'boolean',
    label: 'Transfer approval required?',
    required: false,
    group: 'transfer',
  },
  {
    id: 'multiUnitRights',
    type: 'boolean',
    label: 'Multi-unit development rights?',
    required: false,
    group: 'development',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'court', label: 'Court' },
    ],
    required: false,
    group: 'legal',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'Enter governing law/state',
    required: false,
    group: 'legal',
  },
];
