// src/lib/documents/us/cohabitation-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const cohabitationAgreementQuestions: FormQuestion[] = [
  {
    id: 'partner1Name',
    type: 'text',
    label: 'Partner 1 Full Name',
    placeholder: 'Enter partner 1\'s full legal name',
    required: true,
    group: 'partner1',
  },
  {
    id: 'partner1Address',
    type: 'textarea',
    label: 'Partner 1 Address',
    placeholder: 'Enter partner 1\'s current address',
    required: true,
    group: 'partner1',
  },
  {
    id: 'partner1Phone',
    type: 'tel',
    label: 'Partner 1 Phone Number',
    placeholder: '(555) 123-4567',
    required: false,
    group: 'partner1',
  },
  {
    id: 'partner1Email',
    type: 'email',
    label: 'Partner 1 Email',
    placeholder: 'partner1@example.com',
    required: false,
    group: 'partner1',
  },
  {
    id: 'partner1Occupation',
    type: 'text',
    label: 'Partner 1 Occupation',
    placeholder: 'Enter occupation',
    required: false,
    group: 'partner1',
  },
  {
    id: 'partner1DateOfBirth',
    type: 'date',
    label: 'Partner 1 Date of Birth',
    required: false,
    group: 'partner1',
  },
  {
    id: 'partner2Name',
    type: 'text',
    label: 'Partner 2 Full Name',
    placeholder: 'Enter partner 2\'s full legal name',
    required: true,
    group: 'partner2',
  },
  {
    id: 'partner2Address',
    type: 'textarea',
    label: 'Partner 2 Address',
    placeholder: 'Enter partner 2\'s current address',
    required: true,
    group: 'partner2',
  },
  {
    id: 'partner2Phone',
    type: 'tel',
    label: 'Partner 2 Phone Number',
    placeholder: '(555) 123-4567',
    required: false,
    group: 'partner2',
  },
  {
    id: 'partner2Email',
    type: 'email',
    label: 'Partner 2 Email',
    placeholder: 'partner2@example.com',
    required: false,
    group: 'partner2',
  },
  {
    id: 'partner2Occupation',
    type: 'text',
    label: 'Partner 2 Occupation',
    placeholder: 'Enter occupation',
    required: false,
    group: 'partner2',
  },
  {
    id: 'partner2DateOfBirth',
    type: 'date',
    label: 'Partner 2 Date of Birth',
    required: false,
    group: 'partner2',
  },
  {
    id: 'relationshipStartDate',
    type: 'date',
    label: 'Relationship Start Date',
    required: true,
    group: 'relationship',
  },
  {
    id: 'cohabitationStartDate',
    type: 'date',
    label: 'Living Together Start Date',
    required: true,
    group: 'relationship',
  },
  {
    id: 'sharedResidenceAddress',
    type: 'textarea',
    label: 'Shared Residence Address',
    placeholder: 'Enter the address where you live together',
    required: true,
    group: 'relationship',
  },
  {
    id: 'separateProperty',
    type: 'checkbox',
    label: 'Keep Property Separate',
    required: false,
    group: 'financial',
  },
  {
    id: 'sharedExpenses',
    type: 'checkbox',
    label: 'Share Living Expenses',
    required: false,
    group: 'financial',
  },
  {
    id: 'expenseSharingMethod',
    type: 'select',
    label: 'How to Share Expenses',
    options: [
      { value: 'equal', label: 'Split Equally (50/50)' },
      { value: 'proportional-income', label: 'Proportional to Income' },
      { value: 'other', label: 'Other Arrangement' },
    ],
    required: true,
    group: 'financial',
    dependsOn: 'sharedExpenses',
  },
  {
    id: 'expenseSharingDetails',
    type: 'textarea',
    label: 'Expense Sharing Details',
    placeholder: 'Explain the expense sharing arrangement',
    required: false,
    group: 'financial',
  },
  {
    id: 'jointBankAccount',
    type: 'checkbox',
    label: 'Joint Bank Account',
    required: false,
    group: 'financial',
  },
  {
    id: 'jointBankAccountDetails',
    type: 'textarea',
    label: 'Joint Account Details',
    placeholder: 'Describe the joint account arrangements',
    required: false,
    group: 'financial',
    dependsOn: 'jointBankAccount',
  },
  {
    id: 'realEstateOwnership',
    type: 'select',
    label: 'Real Estate Ownership',
    options: [
      { value: 'separate', label: 'Keep Separate' },
      { value: 'joint', label: 'Joint Ownership' },
      { value: 'none', label: 'No Real Estate' },
    ],
    required: true,
    group: 'property',
  },
  {
    id: 'realEstateDetails',
    type: 'textarea',
    label: 'Real Estate Details',
    placeholder: 'Describe real estate ownership arrangements',
    required: false,
    group: 'property',
  },
  {
    id: 'personalPropertySeparate',
    type: 'checkbox',
    label: 'Keep Personal Property Separate',
    required: false,
    group: 'property',
  },
  {
    id: 'jointPurchasesHandling',
    type: 'textarea',
    label: 'Joint Purchases Handling',
    placeholder: 'How will joint purchases be handled?',
    required: false,
    group: 'property',
  },
  {
    id: 'priorDebtsResponsibility',
    type: 'select',
    label: 'Prior Debts Responsibility',
    options: [
      { value: 'separate', label: 'Each Responsible for Own Debts' },
      { value: 'shared', label: 'Share All Debts' },
    ],
    required: true,
    group: 'debt',
  },
  {
    id: 'futureDebtsResponsibility',
    type: 'select',
    label: 'Future Debts Responsibility',
    options: [
      { value: 'separate', label: 'Each Responsible for Own Debts' },
      { value: 'shared', label: 'Share Future Debts' },
    ],
    required: true,
    group: 'debt',
  },
  {
    id: 'financialSupport',
    type: 'checkbox',
    label: 'Financial Support Agreement',
    required: false,
    group: 'support',
  },
  {
    id: 'supportAmount',
    type: 'number',
    label: 'Monthly Support Amount ($)',
    placeholder: '1000',
    required: false,
    group: 'support',
    dependsOn: 'financialSupport',
  },
  {
    id: 'supportDuration',
    type: 'text',
    label: 'Support Duration',
    placeholder: 'e.g., 6 months after separation',
    required: false,
    group: 'support',
    dependsOn: 'financialSupport',
  },
  {
    id: 'existingChildren',
    type: 'checkbox',
    label: 'Either Partner Has Children',
    required: false,
    group: 'children',
  },
  {
    id: 'existingChildrenDetails',
    type: 'textarea',
    label: 'Existing Children Details',
    placeholder: 'Describe arrangements for existing children',
    required: false,
    group: 'children',
    dependsOn: 'existingChildren',
  },
  {
    id: 'futureChildren',
    type: 'checkbox',
    label: 'Planning to Have Children Together',
    required: false,
    group: 'children',
  },
  {
    id: 'futureChildrenDetails',
    type: 'textarea',
    label: 'Future Children Plans',
    placeholder: 'Describe plans for future children',
    required: false,
    group: 'children',
    dependsOn: 'futureChildren',
  },
  {
    id: 'healthInsurance',
    type: 'select',
    label: 'Health Insurance Arrangement',
    options: [
      { value: 'separate', label: 'Separate Policies' },
      { value: 'shared', label: 'Shared Policy' },
      { value: 'one-covers-both', label: 'One Partner Covers Both' },
    ],
    required: true,
    group: 'healthcare',
  },
  {
    id: 'medicalDecisionMaking',
    type: 'checkbox',
    label: 'Medical Decision Making Rights',
    required: false,
    group: 'healthcare',
  },
  {
    id: 'terminationNotice',
    type: 'number',
    label: 'Termination Notice (Days)',
    placeholder: '30',
    required: true,
    group: 'termination',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'court', label: 'Court' },
    ],
    required: true,
    group: 'termination',
  },
  {
    id: 'inheritanceRights',
    type: 'checkbox',
    label: 'Inheritance Rights',
    required: false,
    group: 'legal',
  },
  {
    id: 'governingState',
    type: 'text',
    label: 'Governing State',
    placeholder: 'e.g., California',
    required: true,
    group: 'legal',
  },
  {
    id: 'additionalTerms',
    type: 'textarea',
    label: 'Additional Terms',
    placeholder: 'Any additional terms or conditions',
    required: false,
    group: 'additional',
  },
];