import type { Question } from '@/types/documents';

export const questions: Question[] = [
  {
    id: 'declarantName',
    label: 'Your Full Legal Name',
    type: 'text',
    required: true,
    placeholder: 'Enter your full legal name',
  },
  {
    id: 'declarantAddress',
    label: 'Your Address',
    type: 'textarea',
    required: true,
    placeholder: 'Enter your complete address',
  },
  {
    id: 'declarantDateOfBirth',
    label: 'Your Date of Birth',
    type: 'date',
    required: true,
  },
  {
    id: 'declarantSSN',
    label: 'Social Security Number (Optional)',
    type: 'text',
    placeholder: 'Last 4 digits or full SSN for identification',
  },
  {
    id: 'healthcareAgent',
    label: 'Healthcare Agent/Proxy (Optional)',
    type: 'text',
    placeholder: 'Person authorized to make healthcare decisions if you cannot',
  },
  {
    id: 'healthcareAgentAddress',
    label: 'Healthcare Agent Address (Optional)',
    type: 'textarea',
    placeholder: 'Complete address of healthcare agent',
    dependsOn: { field: 'healthcareAgent' },
  },
  {
    id: 'healthcareAgentPhone',
    label: 'Healthcare Agent Phone (Optional)',
    type: 'text',
    placeholder: 'Phone number for healthcare agent',
    dependsOn: { field: 'healthcareAgent' },
  },
  {
    id: 'alternateHealthcareAgent',
    label: 'Alternate Healthcare Agent (Optional)',
    type: 'text',
    placeholder: 'Backup person if primary agent cannot serve',
  },
  {
    id: 'alternateHealthcareAgentAddress',
    label: 'Alternate Healthcare Agent Address (Optional)',
    type: 'textarea',
    placeholder: 'Complete address of alternate agent',
    dependsOn: { field: 'alternateHealthcareAgent' },
  },
  {
    id: 'terminalConditionDefinition',
    label: 'Terminal Condition Treatment Preferences',
    type: 'textarea',
    required: true,
    placeholder:
      'Your wishes regarding treatment if you have a terminal condition',
  },
  {
    id: 'persistentVegetativeState',
    label: 'Persistent Vegetative State Preferences',
    type: 'textarea',
    required: true,
    placeholder: 'Your wishes if you are in a persistent vegetative state',
  },
  {
    id: 'irreversibleCondition',
    label: 'Irreversible Condition Preferences',
    type: 'textarea',
    required: true,
    placeholder: 'Your wishes regarding treatment for irreversible conditions',
  },
  {
    id: 'lifeSustainingTreatment',
    label: 'Life-Sustaining Treatment Preference',
    type: 'select',
    required: true,
    options: [
      { value: 'continue', label: 'Continue all life-sustaining treatment' },
      { value: 'discontinue', label: 'Discontinue life-sustaining treatment' },
      { value: 'trial_period', label: 'Trial period then reassess' },
      { value: 'specific_conditions', label: 'Only under specific conditions' },
    ],
  },
  {
    id: 'lifeSustainingConditions',
    label: 'Specific Life-Sustaining Treatment Conditions (if applicable)',
    type: 'textarea',
    placeholder: 'Describe specific conditions for life-sustaining treatment',
    dependsOn: {
      field: 'lifeSustainingTreatment',
      value: 'specific_conditions',
    },
  },
  {
    id: 'artificialNutrition',
    label: 'Artificial Nutrition (Feeding Tubes)',
    type: 'select',
    required: true,
    options: [
      { value: 'yes', label: 'Yes, provide artificial nutrition' },
      { value: 'no', label: 'No artificial nutrition' },
      { value: 'temporary', label: 'Temporary only' },
      { value: 'comfort_only', label: 'Only for comfort' },
    ],
  },
  {
    id: 'artificialHydration',
    label: 'Artificial Hydration (IV Fluids)',
    type: 'select',
    required: true,
    options: [
      { value: 'yes', label: 'Yes, provide artificial hydration' },
      { value: 'no', label: 'No artificial hydration' },
      { value: 'temporary', label: 'Temporary only' },
      { value: 'comfort_only', label: 'Only for comfort' },
    ],
  },
  {
    id: 'mechanicalVentilation',
    label: 'Mechanical Ventilation (Breathing Machines)',
    type: 'select',
    required: true,
    options: [
      { value: 'yes', label: 'Yes, use mechanical ventilation' },
      { value: 'no', label: 'No mechanical ventilation' },
      { value: 'temporary', label: 'Temporary only' },
      { value: 'trial_period', label: 'Trial period then reassess' },
    ],
  },
  {
    id: 'cardiopulmonaryResuscitation',
    label: 'CPR (Cardiopulmonary Resuscitation)',
    type: 'select',
    required: true,
    options: [
      { value: 'yes', label: 'Yes, attempt CPR' },
      { value: 'no', label: 'No CPR (DNR)' },
      {
        value: 'limited_circumstances',
        label: 'Only in limited circumstances',
      },
    ],
  },
  {
    id: 'dialysis',
    label: 'Dialysis Treatment',
    type: 'select',
    required: true,
    options: [
      { value: 'yes', label: 'Yes, provide dialysis' },
      { value: 'no', label: 'No dialysis' },
      { value: 'temporary', label: 'Temporary only' },
      { value: 'comfort_only', label: 'Only for comfort' },
    ],
  },
  {
    id: 'antibiotics',
    label: 'Antibiotic Treatment',
    type: 'select',
    required: true,
    options: [
      { value: 'yes', label: 'Yes, provide antibiotics' },
      { value: 'no', label: 'No antibiotics' },
      { value: 'infection_only', label: 'Only for treatable infections' },
      { value: 'comfort_only', label: 'Only for comfort' },
    ],
  },
  {
    id: 'painManagement',
    label: 'Pain Management Preference',
    type: 'select',
    required: true,
    options: [
      { value: 'maximum', label: 'Maximum pain relief' },
      { value: 'moderate', label: 'Moderate pain relief' },
      { value: 'minimal', label: 'Minimal pain medication' },
      { value: 'comfort_focused', label: 'Comfort-focused care' },
    ],
  },
  {
    id: 'sedation',
    label: 'Sedation Preference',
    type: 'select',
    required: true,
    options: [
      { value: 'yes', label: 'Yes, allow sedation' },
      { value: 'no', label: 'No sedation' },
      { value: 'comfort_only', label: 'Only for comfort' },
      { value: 'end_of_life_only', label: 'Only at end of life' },
    ],
  },
  {
    id: 'organDonation',
    label: 'Organ Donation',
    type: 'select',
    required: true,
    options: [
      { value: 'yes', label: 'Yes, donate organs' },
      { value: 'no', label: 'No organ donation' },
      { value: 'specific_organs', label: 'Specific organs only' },
      { value: 'research_only', label: 'For research only' },
    ],
  },
  {
    id: 'organDonationDetails',
    label: 'Organ Donation Details (if applicable)',
    type: 'textarea',
    placeholder: 'Specify which organs or research purposes',
    dependsOn: {
      field: 'organDonation',
      value: ['specific_organs', 'research_only'],
    },
  },
  {
    id: 'tissueDonation',
    label: 'Tissue Donation',
    type: 'select',
    required: true,
    options: [
      { value: 'yes', label: 'Yes, donate tissues' },
      { value: 'no', label: 'No tissue donation' },
      { value: 'specific_tissues', label: 'Specific tissues only' },
    ],
  },
  {
    id: 'bodyDonation',
    label: 'Body Donation for Medical Science',
    type: 'select',
    required: true,
    options: [
      { value: 'yes', label: 'Yes, donate body' },
      { value: 'no', label: 'No body donation' },
      { value: 'medical_research', label: 'Medical research only' },
      { value: 'education', label: 'Medical education only' },
    ],
  },
  {
    id: 'autopsy',
    label: 'Autopsy Preference',
    type: 'select',
    required: true,
    options: [
      { value: 'yes', label: 'Yes, allow autopsy' },
      { value: 'no', label: 'No autopsy' },
      { value: 'medical_necessity_only', label: 'Only if medically necessary' },
    ],
  },
  {
    id: 'qualityOfLifeFactors',
    label: 'Quality of Life Considerations (Optional)',
    type: 'textarea',
    placeholder: 'Describe what quality of life means to you',
  },
  {
    id: 'religiousBeliefs',
    label: 'Religious Beliefs and Considerations (Optional)',
    type: 'textarea',
    placeholder: 'Any religious beliefs that should guide treatment decisions',
  },
  {
    id: 'culturalConsiderations',
    label: 'Cultural Considerations (Optional)',
    type: 'textarea',
    placeholder: 'Any cultural factors that should be considered',
  },
  {
    id: 'burialCremationPreference',
    label: 'Burial/Cremation Preference',
    type: 'select',
    required: true,
    options: [
      { value: 'burial', label: 'Burial' },
      { value: 'cremation', label: 'Cremation' },
      { value: 'no_preference', label: 'No preference' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'burialCremationDetails',
    label: 'Burial/Cremation Details (Optional)',
    type: 'textarea',
    placeholder:
      'Specific instructions for burial, cremation, or other arrangements',
  },
  {
    id: 'pregnancyConsiderations',
    label: 'Pregnancy Considerations (Optional)',
    type: 'textarea',
    placeholder:
      'Special instructions if you are pregnant when this directive applies',
  },
  {
    id: 'specificMedicalConditions',
    label: 'Specific Medical Conditions (Optional)',
    type: 'textarea',
    placeholder:
      'Any current medical conditions that affect your treatment preferences',
  },
  {
    id: 'treatmentPreferences',
    label: 'Preferred Treatments (Optional)',
    type: 'textarea',
    placeholder: 'Specific treatments you would want to receive',
  },
  {
    id: 'treatmentToAvoid',
    label: 'Treatments to Avoid (Optional)',
    type: 'textarea',
    placeholder: 'Specific treatments you would not want to receive',
  },
  {
    id: 'hospitalPreferences',
    label: 'Hospital Preferences (Optional)',
    type: 'textarea',
    placeholder: 'Preferred hospitals or medical facilities',
  },
  {
    id: 'doctorPreferences',
    label: 'Doctor Preferences (Optional)',
    type: 'textarea',
    placeholder: 'Preferred doctors or medical specialists',
  },
  {
    id: 'homeCarePriority',
    label: 'Prefer Care at Home',
    type: 'checkbox',
    defaultValue: false,
  },
  {
    id: 'hospiceCare',
    label: 'Allow Hospice Care',
    type: 'checkbox',
    defaultValue: false,
  },
  {
    id: 'emergencyContacts',
    label: 'Emergency Contacts (Optional)',
    type: 'textarea',
    placeholder: 'People to contact in medical emergencies',
  },
  {
    id: 'additionalInstructions',
    label: 'Additional Instructions (Optional)',
    type: 'textarea',
    placeholder: 'Any other healthcare instructions or preferences',
  },
  {
    id: 'effectiveDate',
    label: 'Effective Date',
    type: 'date',
    required: true,
  },
  {
    id: 'witnessOneName',
    label: 'First Witness Full Name',
    type: 'text',
    required: true,
    placeholder: 'Adult witness to directive signing',
  },
  {
    id: 'witnessOneAddress',
    label: 'First Witness Address',
    type: 'textarea',
    required: true,
    placeholder: 'Complete address of first witness',
  },
  {
    id: 'witnessTwoName',
    label: 'Second Witness Full Name',
    type: 'text',
    required: true,
    placeholder: 'Second adult witness to directive signing',
  },
  {
    id: 'witnessTwoAddress',
    label: 'Second Witness Address',
    type: 'textarea',
    required: true,
    placeholder: 'Complete address of second witness',
  },
  {
    id: 'executionDate',
    label: 'Directive Execution Date',
    type: 'date',
    required: true,
  },
  {
    id: 'executionState',
    label: 'State Where Directive is Executed',
    type: 'text',
    required: true,
    placeholder: 'State where you are signing this directive',
  },
  {
    id: 'executionCounty',
    label: 'County Where Directive is Executed',
    type: 'text',
    required: true,
    placeholder: 'County where you are signing this directive',
  },
];
