import { z } from 'zod';

export const schema = z.object({
  declarantName: z.string().min(1, 'Declarant name is required'),
  declarantAddress: z.string().min(1, 'Declarant address is required'),
  declarantDateOfBirth: z.string().min(1, 'Declarant date of birth is required'),
  declarantSSN: z.string().optional(),
  healthcareAgent: z.string().optional(),
  healthcareAgentAddress: z.string().optional(),
  healthcareAgentPhone: z.string().optional(),
  alternateHealthcareAgent: z.string().optional(),
  alternateHealthcareAgentAddress: z.string().optional(),
  alternateHealthcareAgentPhone: z.string().optional(),
  lifeSustainingTreatment: z.enum(['continue', 'discontinue', 'trial_period', 'specific_conditions']),
  lifeSustainingConditions: z.string().optional(),
  artificialNutrition: z.enum(['yes', 'no', 'temporary', 'comfort_only']),
  artificialHydration: z.enum(['yes', 'no', 'temporary', 'comfort_only']),
  mechanicalVentilation: z.enum(['yes', 'no', 'temporary', 'trial_period']),
  cardiopulmonaryResuscitation: z.enum(['yes', 'no', 'limited_circumstances']),
  dialysis: z.enum(['yes', 'no', 'temporary', 'comfort_only']),
  antibiotics: z.enum(['yes', 'no', 'infection_only', 'comfort_only']),
  painManagement: z.enum(['maximum', 'moderate', 'minimal', 'comfort_focused']),
  sedation: z.enum(['yes', 'no', 'comfort_only', 'end_of_life_only']),
  terminalConditionDefinition: z.string().min(1, 'Terminal condition definition is required'),
  persistentVegetativeState: z.string().min(1, 'Persistent vegetative state preferences are required'),
  irreversibleCondition: z.string().min(1, 'Irreversible condition preferences are required'),
  qualityOfLifeFactors: z.string().optional(),
  religiousBeliefs: z.string().optional(),
  culturalConsiderations: z.string().optional(),
  organDonation: z.enum(['yes', 'no', 'specific_organs', 'research_only']),
  organDonationDetails: z.string().optional(),
  tissueDonation: z.enum(['yes', 'no', 'specific_tissues']),
  tissueDonationDetails: z.string().optional(),
  bodyDonation: z.enum(['yes', 'no', 'medical_research', 'education']),
  autopsy: z.enum(['yes', 'no', 'medical_necessity_only']),
  funeralArrangements: z.string().optional(),
  burialCremationPreference: z.enum(['burial', 'cremation', 'no_preference', 'other']),
  burialCremationDetails: z.string().optional(),
  pregnancyConsiderations: z.string().optional(),
  specificMedicalConditions: z.string().optional(),
  treatmentPreferences: z.string().optional(),
  treatmentToAvoid: z.string().optional(),
  hospitalPreferences: z.string().optional(),
  doctorPreferences: z.string().optional(),
  homeCarePriority: z.boolean().default(false),
  nursingHomeCare: z.boolean().default(false),
  hospiceCare: z.boolean().default(false),
  familyNotification: z.string().optional(),
  emergencyContacts: z.string().optional(),
  additionalInstructions: z.string().optional(),
  effectiveDate: z.string().min(1, 'Effective date is required'),
  revocationConditions: z.string().optional(),
  witnessOneName: z.string().min(1, 'First witness name is required'),
  witnessOneAddress: z.string().min(1, 'First witness address is required'),
  witnessTwoName: z.string().min(1, 'Second witness name is required'),
  witnessTwoAddress: z.string().min(1, 'Second witness address is required'),
  notaryName: z.string().optional(),
  notaryCommission: z.string().optional(),
  executionDate: z.string().min(1, 'Execution date is required'),
  executionState: z.string().min(1, 'State of execution is required'),
  executionCounty: z.string().min(1, 'County of execution is required'),
});