// src/lib/documents/us/consulting-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const consultingAgreementQuestions: FormQuestion[] = [
  {
    id: 'consultingType',
    type: 'select',
    label: 'Type of Consulting',
    options: [
      { value: 'strategic', label: 'Strategic Consulting' },
      { value: 'technical', label: 'Technical Consulting' },
      { value: 'marketing', label: 'Marketing Consulting' },
      { value: 'financial', label: 'Financial Consulting' },
      { value: 'hr', label: 'HR Consulting' },
      { value: 'legal', label: 'Legal Consulting' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'services',
  },
  {
    id: 'serviceDescription',
    type: 'textarea',
    label: 'Service Description',
    placeholder: 'Describe the consulting services to be provided',
    required: true,
    group: 'services',
  },
  {
    id: 'projectScope',
    type: 'textarea',
    label: 'Project Scope',
    placeholder: 'Define the scope and boundaries of the consulting engagement',
    required: true,
    group: 'services',
  },
  {
    id: 'consultantName',
    type: 'text',
    label: 'Consultant Name',
    placeholder: 'Enter consultant or company name',
    required: true,
    group: 'consultant',
  },
  {
    id: 'consultantType',
    type: 'select',
    label: 'Consultant Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'llc', label: 'LLC' },
    ],
    required: true,
    group: 'consultant',
  },
  {
    id: 'consultantAddress',
    type: 'textarea',
    label: 'Consultant Address',
    placeholder: 'Enter consultant complete address',
    required: true,
    group: 'consultant',
  },
  {
    id: 'consultantPhone',
    type: 'tel',
    label: 'Consultant Phone',
    placeholder: '(555) 123-4567',
    required: false,
    group: 'consultant',
  },
  {
    id: 'consultantEmail',
    type: 'email',
    label: 'Consultant Email',
    placeholder: 'consultant@email.com',
    required: false,
    group: 'consultant',
  },
  {
    id: 'clientName',
    type: 'text',
    label: 'Client Name',
    placeholder: 'Enter client or company name',
    required: true,
    group: 'client',
  },
  {
    id: 'clientType',
    type: 'select',
    label: 'Client Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'llc', label: 'LLC' },
    ],
    required: true,
    group: 'client',
  },
  {
    id: 'clientAddress',
    type: 'textarea',
    label: 'Client Address',
    placeholder: 'Enter client complete address',
    required: true,
    group: 'client',
  },
  {
    id: 'clientContact',
    type: 'text',
    label: 'Client Contact Person',
    placeholder: 'Main contact person name and title',
    required: false,
    group: 'client',
  },
  {
    id: 'startDate',
    type: 'date',
    label: 'Engagement Start Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'endDate',
    type: 'date',
    label: 'Engagement End Date',
    required: false,
    group: 'timeline',
  },
  {
    id: 'termLength',
    type: 'text',
    label: 'Engagement Term',
    placeholder: 'e.g., 6 months, 1 year, ongoing',
    required: false,
    group: 'timeline',
  },
  {
    id: 'timeCommitment',
    type: 'select',
    label: 'Time Commitment',
    options: [
      { value: 'full-time', label: 'Full-time' },
      { value: 'part-time', label: 'Part-time' },
      { value: 'as-needed', label: 'As Needed' },
      { value: 'project-based', label: 'Project-based' },
    ],
    required: true,
    group: 'timeline',
  },
  {
    id: 'workSchedule',
    type: 'textarea',
    label: 'Work Schedule',
    placeholder: 'Specify working hours, days, or schedule details',
    required: false,
    group: 'timeline',
  },
  {
    id: 'deliverables',
    type: 'textarea',
    label: 'Deliverables',
    placeholder: 'List specific deliverables expected',
    required: false,
    group: 'deliverables',
  },
  {
    id: 'deliverySchedule',
    type: 'textarea',
    label: 'Delivery Schedule',
    placeholder: 'Specify when deliverables are due',
    required: false,
    group: 'deliverables',
  },
  {
    id: 'milestones',
    type: 'textarea',
    label: 'Project Milestones',
    placeholder: 'Define key project milestones',
    required: false,
    group: 'deliverables',
  },
  {
    id: 'compensationType',
    type: 'select',
    label: 'Compensation Type',
    options: [
      { value: 'hourly', label: 'Hourly Rate' },
      { value: 'daily', label: 'Daily Rate' },
      { value: 'monthly', label: 'Monthly Fee' },
      { value: 'project-fee', label: 'Project Fee' },
      { value: 'retainer', label: 'Retainer' },
    ],
    required: true,
    group: 'compensation',
  },
  {
    id: 'hourlyRate',
    type: 'number',
    label: 'Hourly Rate ($)',
    placeholder: '150',
    required: false,
    group: 'compensation',
  },
  {
    id: 'projectFee',
    type: 'number',
    label: 'Project Fee ($)',
    placeholder: '10000',
    required: false,
    group: 'compensation',
  },
  {
    id: 'retainerAmount',
    type: 'number',
    label: 'Retainer Amount ($)',
    placeholder: '5000',
    required: false,
    group: 'compensation',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'weekly', label: 'Weekly' },
      { value: 'bi-weekly', label: 'Bi-weekly' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'upon-completion', label: 'Upon Completion' },
      { value: 'milestone-based', label: 'Milestone-based' },
    ],
    required: true,
    group: 'compensation',
  },
  {
    id: 'paymentTerms',
    type: 'textarea',
    label: 'Payment Terms',
    placeholder: 'Specify payment terms, net days, late fees, etc.',
    required: false,
    group: 'compensation',
  },
  {
    id: 'expenseReimbursement',
    type: 'checkbox',
    label: 'Client will reimburse expenses',
    required: false,
    group: 'expenses',
  },
  {
    id: 'expensePolicy',
    type: 'textarea',
    label: 'Expense Policy',
    placeholder: 'Define what expenses are reimbursable',
    required: false,
    group: 'expenses',
    dependsOn: 'expenseReimbursement',
  },
  {
    id: 'workLocation',
    type: 'select',
    label: 'Work Location',
    options: [
      { value: 'on-site', label: 'On-site at Client Location' },
      { value: 'remote', label: 'Remote' },
      { value: 'hybrid', label: 'Hybrid (On-site + Remote)' },
    ],
    required: true,
    group: 'work-arrangement',
  },
  {
    id: 'equipmentProvided',
    type: 'checkbox',
    label: 'Client will provide equipment',
    required: false,
    group: 'work-arrangement',
  },
  {
    id: 'equipmentDetails',
    type: 'textarea',
    label: 'Equipment Details',
    placeholder: 'Specify what equipment will be provided',
    required: false,
    group: 'work-arrangement',
    dependsOn: 'equipmentProvided',
  },
  {
    id: 'ipOwnership',
    type: 'select',
    label: 'Intellectual Property Ownership',
    options: [
      { value: 'consultant', label: 'Consultant Retains Ownership' },
      { value: 'client', label: 'Client Owns All Work Product' },
      { value: 'shared', label: 'Shared Ownership' },
    ],
    required: true,
    group: 'intellectual-property',
  },
  {
    id: 'workForHire',
    type: 'checkbox',
    label: 'Work is considered "work for hire"',
    required: false,
    group: 'intellectual-property',
  },
  {
    id: 'confidentialityClause',
    type: 'checkbox',
    label: 'Include confidentiality clause',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'confidentialityPeriod',
    type: 'text',
    label: 'Confidentiality Period',
    placeholder: 'e.g., 5 years, indefinite',
    required: false,
    group: 'confidentiality',
    dependsOn: 'confidentialityClause',
  },
  {
    id: 'nonCompeteClause',
    type: 'checkbox',
    label: 'Include non-compete clause',
    required: false,
    group: 'restrictions',
  },
  {
    id: 'nonCompetePeriod',
    type: 'text',
    label: 'Non-compete Period',
    placeholder: 'e.g., 1 year, 2 years',
    required: false,
    group: 'restrictions',
    dependsOn: 'nonCompeteClause',
  },
  {
    id: 'nonSolicitationClause',
    type: 'checkbox',
    label: 'Include non-solicitation clause',
    required: false,
    group: 'restrictions',
  },
  {
    id: 'performanceMetrics',
    type: 'textarea',
    label: 'Performance Metrics',
    placeholder: 'Define how performance will be measured',
    required: false,
    group: 'performance',
  },
  {
    id: 'reportingRequirements',
    type: 'textarea',
    label: 'Reporting Requirements',
    placeholder: 'Specify reporting frequency and format',
    required: false,
    group: 'performance',
  },
  {
    id: 'terminationNotice',
    type: 'text',
    label: 'Termination Notice Period',
    placeholder: '30 days',
    required: false,
    group: 'termination',
  },
  {
    id: 'terminationCause',
    type: 'textarea',
    label: 'Termination for Cause',
    placeholder: 'Define what constitutes cause for termination',
    required: false,
    group: 'termination',
  },
  {
    id: 'additionalTerms',
    type: 'textarea',
    label: 'Additional Terms',
    placeholder: 'Any additional terms or special provisions',
    required: false,
    group: 'additional',
  },
];
