// src/lib/documents/us/advance-directive/questions.ts
import type { Question } from '@/types/documents';

export const questions: Question[] = [
  // Section 1: Principal Information
  {
    id: 'principalName',
    type: 'text',
    label: 'Full Legal Name',
    required: true,
    section: 'Principal Information',
    placeholder: 'Enter your full legal name',
  },
  {
    id: 'principalAddress',
    type: 'text',
    label: 'Street Address',
    required: true,
    section: 'Principal Information',
    placeholder: 'Enter your street address',
  },
  {
    id: 'principalCity',
    type: 'text',
    label: 'City',
    required: true,
    section: 'Principal Information',
    placeholder: 'Enter your city',
  },
  {
    id: 'principalState',
    type: 'select',
    label: 'State',
    required: true,
    section: 'Principal Information',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
  },
  {
    id: 'principalZip',
    type: 'text',
    label: 'ZIP Code',
    required: true,
    section: 'Principal Information',
    placeholder: 'Enter your ZIP code',
  },
  {
    id: 'principalPhone',
    type: 'text',
    label: 'Phone Number',
    required: true,
    section: 'Principal Information',
    placeholder: 'Enter your phone number',
  },
  {
    id: 'principalDateOfBirth',
    type: 'date',
    label: 'Date of Birth',
    required: true,
    section: 'Principal Information',
  },

  // Section 2: Health Care Agent
  {
    id: 'agentName',
    type: 'text',
    label: "Health Care Agent's Full Name",
    required: true,
    section: 'Health Care Agent',
    placeholder: "Enter your health care agent's full name",
    description:
      'This person will make medical decisions for you if you cannot.',
  },
  {
    id: 'agentAddress',
    type: 'text',
    label: "Health Care Agent's Address",
    required: true,
    section: 'Health Care Agent',
    placeholder: "Enter your health care agent's address",
  },
  {
    id: 'agentCity',
    type: 'text',
    label: "Health Care Agent's City",
    required: true,
    section: 'Health Care Agent',
    placeholder: "Enter your health care agent's city",
  },
  {
    id: 'agentState',
    type: 'select',
    label: "Health Care Agent's State",
    required: true,
    section: 'Health Care Agent',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
  },
  {
    id: 'agentZip',
    type: 'text',
    label: "Health Care Agent's ZIP Code",
    required: true,
    section: 'Health Care Agent',
    placeholder: "Enter your health care agent's ZIP code",
  },
  {
    id: 'agentPhone',
    type: 'text',
    label: "Health Care Agent's Phone Number",
    required: true,
    section: 'Health Care Agent',
    placeholder: "Enter your health care agent's phone number",
  },
  {
    id: 'agentRelationship',
    type: 'text',
    label: 'Relationship to You',
    required: true,
    section: 'Health Care Agent',
    placeholder: 'e.g., Spouse, Child, Sibling, Friend',
  },

  // Section 3: Alternate Agent
  {
    id: 'hasAlternateAgent',
    type: 'radio',
    label: 'Do you want to designate an alternate health care agent?',
    required: true,
    section: 'Alternate Health Care Agent',
    options: [
      { value: 'true', label: 'Yes, I want to designate an alternate agent' },
      { value: 'false', label: 'No, I only want one health care agent' },
    ],
    description:
      'An alternate agent will act if your primary agent is unavailable.',
  },
  {
    id: 'alternateAgentName',
    type: 'text',
    label: "Alternate Agent's Full Name",
    required: false,
    section: 'Alternate Health Care Agent',
    placeholder: "Enter your alternate agent's full name",
    condition: { field: 'hasAlternateAgent', value: 'true' },
  },
  {
    id: 'alternateAgentAddress',
    type: 'text',
    label: "Alternate Agent's Address",
    required: false,
    section: 'Alternate Health Care Agent',
    placeholder: "Enter your alternate agent's address",
    condition: { field: 'hasAlternateAgent', value: 'true' },
  },
  {
    id: 'alternateAgentCity',
    type: 'text',
    label: "Alternate Agent's City",
    required: false,
    section: 'Alternate Health Care Agent',
    placeholder: "Enter your alternate agent's city",
    condition: { field: 'hasAlternateAgent', value: 'true' },
  },
  {
    id: 'alternateAgentState',
    type: 'select',
    label: "Alternate Agent's State",
    required: false,
    section: 'Alternate Health Care Agent',
    condition: { field: 'hasAlternateAgent', value: 'true' },
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
  },
  {
    id: 'alternateAgentZip',
    type: 'text',
    label: "Alternate Agent's ZIP Code",
    required: false,
    section: 'Alternate Health Care Agent',
    placeholder: "Enter your alternate agent's ZIP code",
    condition: { field: 'hasAlternateAgent', value: 'true' },
  },
  {
    id: 'alternateAgentPhone',
    type: 'text',
    label: "Alternate Agent's Phone Number",
    required: false,
    section: 'Alternate Health Care Agent',
    placeholder: "Enter your alternate agent's phone number",
    condition: { field: 'hasAlternateAgent', value: 'true' },
  },
  {
    id: 'alternateAgentRelationship',
    type: 'text',
    label: "Alternate Agent's Relationship to You",
    required: false,
    section: 'Alternate Health Care Agent',
    placeholder: 'e.g., Spouse, Child, Sibling, Friend',
    condition: { field: 'hasAlternateAgent', value: 'true' },
  },

  // Section 4: Medical Treatment Preferences
  {
    id: 'lifeSustainingTreatment',
    type: 'radio',
    label: 'Life-Sustaining Treatment',
    required: true,
    section: 'Medical Treatment Preferences',
    options: [
      {
        value: 'continue',
        label: 'I want life-sustaining treatment to be provided',
      },
      {
        value: 'discontinue',
        label: 'I want life-sustaining treatment to be withheld or withdrawn',
      },
      {
        value: 'undecided',
        label: 'I want my agent to decide based on my best interests',
      },
    ],
    description:
      'Life-sustaining treatment includes mechanical ventilation, dialysis, and other treatments that may prolong life.',
  },
  {
    id: 'artificialNutrition',
    type: 'radio',
    label: 'Artificial Nutrition and Hydration',
    required: true,
    section: 'Medical Treatment Preferences',
    options: [
      {
        value: 'provide',
        label: 'I want artificial nutrition and hydration to be provided',
      },
      {
        value: 'withhold',
        label: 'I want artificial nutrition and hydration to be withheld',
      },
      {
        value: 'undecided',
        label: 'I want my agent to decide based on my best interests',
      },
    ],
    description:
      'Artificial nutrition and hydration includes feeding tubes and IV fluids.',
  },
  {
    id: 'painMedication',
    type: 'radio',
    label: 'Pain Relief Medication',
    required: true,
    section: 'Medical Treatment Preferences',
    options: [
      {
        value: 'provide',
        label: 'I want pain relief medication even if it hastens death',
      },
      {
        value: 'withhold',
        label: 'I want pain relief medication only if it does not hasten death',
      },
      {
        value: 'undecided',
        label: 'I want my agent to decide based on my best interests',
      },
    ],
    description:
      'Pain relief medication may sometimes hasten death as a side effect.',
  },
  {
    id: 'comfortCare',
    type: 'radio',
    label: 'Comfort Care',
    required: true,
    section: 'Medical Treatment Preferences',
    options: [
      {
        value: 'provide',
        label: 'I want comfort care and palliative measures',
      },
      { value: 'withhold', label: 'I do not want comfort care' },
      {
        value: 'undecided',
        label: 'I want my agent to decide based on my best interests',
      },
    ],
    description:
      'Comfort care includes measures to keep you comfortable and free from pain.',
  },

  // Section 5: Additional Instructions
  {
    id: 'additionalInstructions',
    type: 'textarea',
    label: 'Additional Instructions for Your Health Care Agent',
    required: false,
    section: 'Additional Instructions',
    placeholder:
      'Provide any additional instructions or preferences for your health care agent...',
    description:
      'Include any specific wishes about your medical care that are not covered above.',
  },
  {
    id: 'specificMedicalConditions',
    type: 'textarea',
    label: 'Specific Medical Conditions or Treatments',
    required: false,
    section: 'Additional Instructions',
    placeholder:
      'Describe any specific medical conditions or treatments you want to address...',
    description:
      'Include instructions for specific medical conditions you have or treatments you do/do not want.',
  },
  {
    id: 'religiousBeliefs',
    type: 'textarea',
    label: 'Religious or Personal Beliefs',
    required: false,
    section: 'Additional Instructions',
    placeholder:
      'Describe any religious or personal beliefs that should guide your medical care...',
    description:
      'Include any religious, spiritual, or personal beliefs that should influence your care.',
  },

  // Section 6: Organ Donation
  {
    id: 'organDonation',
    type: 'radio',
    label: 'Organ and Tissue Donation',
    required: true,
    section: 'Organ Donation',
    options: [
      {
        value: 'yes',
        label: 'I want to donate my organs and tissues for transplantation',
      },
      { value: 'no', label: 'I do not want to donate my organs and tissues' },
      {
        value: 'undecided',
        label: 'I want my agent to decide about organ donation',
      },
    ],
    description:
      'This preference will be communicated to medical professionals and your agent.',
  },
  {
    id: 'organDonationSpecific',
    type: 'textarea',
    label: 'Specific Organ Donation Instructions',
    required: false,
    section: 'Organ Donation',
    placeholder:
      'Specify any particular organs or tissues you want to donate or exclude...',
    description:
      'If you have specific preferences about which organs or tissues to donate, include them here.',
    condition: { field: 'organDonation', value: 'yes' },
  },

  // Section 7: Witnesses
  {
    id: 'witness1Name',
    type: 'text',
    label: 'First Witness Full Name',
    required: true,
    section: 'Witnesses',
    placeholder: 'Enter first witness full name',
    description:
      'Witnesses cannot be related to you or beneficiaries of your estate.',
  },
  {
    id: 'witness1Address',
    type: 'text',
    label: 'First Witness Address',
    required: true,
    section: 'Witnesses',
    placeholder: 'Enter first witness address',
  },
  {
    id: 'witness2Name',
    type: 'text',
    label: 'Second Witness Full Name',
    required: true,
    section: 'Witnesses',
    placeholder: 'Enter second witness full name',
    description:
      'The second witness must be a different person from the first witness.',
  },
  {
    id: 'witness2Address',
    type: 'text',
    label: 'Second Witness Address',
    required: true,
    section: 'Witnesses',
    placeholder: 'Enter second witness address',
  },

  // Section 8: Legal Information
  {
    id: 'state',
    type: 'select',
    label: 'State Where This Document Will Be Used',
    required: true,
    section: 'Legal Information',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
    description: 'Select the state where this advance directive will be used.',
  },
  {
    id: 'county',
    type: 'text',
    label: 'County',
    required: true,
    section: 'Legal Information',
    placeholder: 'Enter the county name',
  },
  {
    id: 'dateCreated',
    type: 'date',
    label: 'Date of Creation',
    required: true,
    section: 'Legal Information',
    description: 'The date this advance directive is being created.',
  },
];
