// src/lib/documents/us/assignment-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const assignmentAgreementQuestions: FormQuestion[] = [
  // Assignor Information
  {
    id: 'assignorName',
    type: 'text',
    label: 'Assignor Full Name',
    placeholder: 'Enter the full name of the party assigning rights',
    required: true,
    section: 'Assignor Information',
  },
  {
    id: 'assignorAddress',
    type: 'address',
    label: 'Assignor Address',
    placeholder: 'Enter complete address of assignor',
    required: true,
    section: 'Assignor Information',
  },
  {
    id: 'assignorType',
    type: 'select',
    label: 'Assignor Entity Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'llc', label: 'LLC' },
      { value: 'partnership', label: 'Partnership' },
    ],
    required: true,
    section: 'Assignor Information',
  },
  {
    id: 'assignorTitle',
    type: 'text',
    label: 'Assignor Title (if applicable)',
    placeholder: 'e.g., President, Managing Member',
    required: false,
    section: 'Assignor Information',
    conditional: {
      field: 'assignorType',
      value: ['corporation', 'llc', 'partnership'],
    },
  },

  // Assignee Information
  {
    id: 'assigneeName',
    type: 'text',
    label: 'Assignee Full Name',
    placeholder: 'Enter the full name of the party receiving rights',
    required: true,
    section: 'Assignee Information',
  },
  {
    id: 'assigneeAddress',
    type: 'address',
    label: 'Assignee Address',
    placeholder: 'Enter complete address of assignee',
    required: true,
    section: 'Assignee Information',
  },
  {
    id: 'assigneeType',
    type: 'select',
    label: 'Assignee Entity Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'llc', label: 'LLC' },
      { value: 'partnership', label: 'Partnership' },
    ],
    required: true,
    section: 'Assignee Information',
  },
  {
    id: 'assigneeTitle',
    type: 'text',
    label: 'Assignee Title (if applicable)',
    placeholder: 'e.g., President, Managing Member',
    required: false,
    section: 'Assignee Information',
    conditional: {
      field: 'assigneeType',
      value: ['corporation', 'llc', 'partnership'],
    },
  },

  // Original Contract Information
  {
    id: 'originalContractTitle',
    type: 'text',
    label: 'Original Contract Title',
    placeholder: 'Enter the title of the contract being assigned',
    required: true,
    section: 'Original Contract Details',
  },
  {
    id: 'originalContractDate',
    type: 'date',
    label: 'Original Contract Date',
    required: true,
    section: 'Original Contract Details',
  },
  {
    id: 'originalContractParties',
    type: 'textarea',
    label: 'Original Contract Parties',
    placeholder: 'List all parties to the original contract',
    required: true,
    section: 'Original Contract Details',
  },
  {
    id: 'contractDescription',
    type: 'textarea',
    label: 'Contract Description',
    placeholder: 'Briefly describe the nature and subject matter of the original contract',
    required: true,
    section: 'Original Contract Details',
  },

  // Assignment Details
  {
    id: 'assignmentType',
    type: 'radio',
    label: 'Type of Assignment',
    options: [
      { value: 'complete', label: 'Complete Assignment (all rights and obligations)' },
      { value: 'partial', label: 'Partial Assignment (specific rights only)' },
    ],
    required: true,
    section: 'Assignment Details',
  },
  {
    id: 'rightsAssigned',
    type: 'textarea',
    label: 'Rights Being Assigned',
    placeholder: 'Describe the specific rights being transferred',
    required: true,
    section: 'Assignment Details',
  },
  {
    id: 'obligationsAssigned',
    type: 'textarea',
    label: 'Obligations Being Assigned',
    placeholder: 'Describe the specific obligations being transferred',
    required: true,
    section: 'Assignment Details',
  },
  {
    id: 'assignmentDate',
    type: 'date',
    label: 'Effective Date of Assignment',
    required: true,
    section: 'Assignment Details',
  },
  {
    id: 'assignmentConsideration',
    type: 'textarea',
    label: 'Consideration for Assignment',
    placeholder: 'Describe what the assignee is providing in exchange (money, services, etc.)',
    required: true,
    section: 'Assignment Details',
  },

  // Warranties and Representations
  {
    id: 'assignorWarranties',
    type: 'checkbox',
    label: 'Assignor provides warranties and representations',
    required: true,
    section: 'Warranties',
  },
  {
    id: 'validContract',
    type: 'checkbox',
    label: 'Original contract is valid and enforceable',
    required: true,
    section: 'Warranties',
  },
  {
    id: 'noBreachExists',
    type: 'checkbox',
    label: 'No breach of the original contract exists',
    required: true,
    section: 'Warranties',
  },
  {
    id: 'rightToAssign',
    type: 'checkbox',
    label: 'Assignor has the right to make this assignment',
    required: true,
    section: 'Warranties',
  },

  // Consent and Notice
  {
    id: 'consentRequired',
    type: 'radio',
    label: 'Is consent from other parties required?',
    options: [
      { value: true, label: 'Yes, consent is required' },
      { value: false, label: 'No, consent is not required' },
    ],
    required: true,
    section: 'Consent and Notice',
  },
  {
    id: 'consentObtained',
    type: 'checkbox',
    label: 'Consent has been obtained from all required parties',
    required: false,
    section: 'Consent and Notice',
    conditional: {
      field: 'consentRequired',
      value: [true],
    },
  },
  {
    id: 'noticeRequired',
    type: 'radio',
    label: 'Is notice to other parties required?',
    options: [
      { value: true, label: 'Yes, notice is required' },
      { value: false, label: 'No, notice is not required' },
    ],
    required: true,
    section: 'Consent and Notice',
  },
  {
    id: 'noticeGiven',
    type: 'checkbox',
    label: 'Notice has been given to all required parties',
    required: false,
    section: 'Consent and Notice',
    conditional: {
      field: 'noticeRequired',
      value: [true],
    },
  },

  // Liabilities
  {
    id: 'liabilityRelease',
    type: 'radio',
    label: 'Release of assignor liability',
    options: [
      { value: true, label: 'Assignor is released from all liability' },
      { value: false, label: 'Assignor retains some liability' },
    ],
    required: true,
    section: 'Liability',
  },
  {
    id: 'liabilityRetention',
    type: 'textarea',
    label: 'Retained Liability Description',
    placeholder: 'Describe what liability the assignor retains',
    required: false,
    section: 'Liability',
    conditional: {
      field: 'liabilityRelease',
      value: [false],
    },
  },
  {
    id: 'indemnificationClause',
    type: 'checkbox',
    label: 'Include indemnification clause',
    required: true,
    section: 'Liability',
  },

  // Governing Law
  {
    id: 'governingState',
    type: 'select',
    label: 'Governing State Law',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
    required: true,
    section: 'Legal Terms',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'courts', label: 'Court litigation' },
      { value: 'arbitration', label: 'Binding arbitration' },
      { value: 'mediation', label: 'Mediation first, then courts' },
    ],
    required: true,
    section: 'Legal Terms',
  },

  // Additional Terms
  {
    id: 'additionalTerms',
    type: 'textarea',
    label: 'Additional Terms',
    placeholder: 'Enter any additional terms or conditions',
    required: false,
    section: 'Additional Terms',
  },
  {
    id: 'specialConditions',
    type: 'textarea',
    label: 'Special Conditions',
    placeholder: 'Enter any special conditions or requirements',
    required: false,
    section: 'Additional Terms',
  },

  // Execution
  {
    id: 'executionDate',
    type: 'date',
    label: 'Agreement Execution Date',
    required: true,
    section: 'Signatures',
  },
  {
    id: 'witnessRequired',
    type: 'radio',
    label: 'Are witnesses required?',
    options: [
      { value: true, label: 'Yes, witnesses are required' },
      { value: false, label: 'No, witnesses are not required' },
    ],
    required: true,
    section: 'Signatures',
  },
  {
    id: 'witnessName',
    type: 'text',
    label: 'Witness Name',
    placeholder: 'Enter witness full name',
    required: false,
    section: 'Signatures',
    conditional: {
      field: 'witnessRequired',
      value: [true],
    },
  },
  {
    id: 'notaryRequired',
    type: 'radio',
    label: 'Is notarization required?',
    options: [
      { value: true, label: 'Yes, notarization is required' },
      { value: false, label: 'No, notarization is not required' },
    ],
    required: true,
    section: 'Signatures',
  },
  {
    id: 'notaryName',
    type: 'text',
    label: 'Notary Public Name',
    placeholder: 'Enter notary public name',
    required: false,
    section: 'Signatures',
    conditional: {
      field: 'notaryRequired',
      value: [true],
    },
  },
  {
    id: 'notaryCommission',
    type: 'text',
    label: 'Notary Commission Number',
    placeholder: 'Enter notary commission number',
    required: false,
    section: 'Signatures',
    conditional: {
      field: 'notaryRequired',
      value: [true],
    },
  },
];