// src/lib/documents/us/payment-bond/questions.ts
import type { FormQuestion } from '@/types/documents';

export const paymentbondQuestions: FormQuestion[] = [
  {
    id: 'bondNumber',
    type: 'text',
    label: 'Bond Number',
    placeholder: 'Enter bond number',
    required: true,
    group: 'bond',
  },
  {
    id: 'bondDate',
    type: 'date',
    label: 'Bond Date',
    required: true,
    group: 'bond',
  },
  {
    id: 'bondAmount',
    type: 'text',
    label: 'Bond Amount',
    placeholder: 'Bond amount in dollars',
    required: true,
    group: 'bond',
  },
  {
    id: 'bondAmountWords',
    type: 'text',
    label: 'Bond Amount in Words',
    placeholder: 'Bond amount written out in words',
    required: true,
    group: 'bond',
  },
  {
    id: 'principalName',
    type: 'text',
    label: 'Principal (Contractor) Name',
    placeholder: 'Contractor or company name',
    required: true,
    group: 'principal',
  },
  {
    id: 'principalAddress',
    type: 'text',
    label: 'Principal Address',
    placeholder: 'Complete contractor address',
    required: true,
    group: 'principal',
  },
  {
    id: 'principalPhone',
    type: 'text',
    label: 'Principal Phone',
    placeholder: 'Contact phone number',
    required: false,
    group: 'principal',
  },
  {
    id: 'principalEmail',
    type: 'email',
    label: 'Principal Email',
    placeholder: 'Contact email address',
    required: false,
    group: 'principal',
  },
  {
    id: 'principalLicense',
    type: 'text',
    label: 'Principal License Number',
    placeholder: 'Contractor license number',
    required: false,
    group: 'principal',
  },
  {
    id: 'obligeeName',
    type: 'text',
    label: 'Obligee (Owner) Name',
    placeholder: 'Project owner name',
    required: true,
    group: 'obligee',
  },
  {
    id: 'obligeeAddress',
    type: 'text',
    label: 'Obligee Address',
    placeholder: 'Complete owner address',
    required: true,
    group: 'obligee',
  },
  {
    id: 'obligeePhone',
    type: 'text',
    label: 'Obligee Phone',
    placeholder: 'Owner contact number',
    required: false,
    group: 'obligee',
  },
  {
    id: 'obligeeEmail',
    type: 'email',
    label: 'Obligee Email',
    placeholder: 'Owner email address',
    required: false,
    group: 'obligee',
  },
  {
    id: 'suretyName',
    type: 'text',
    label: 'Surety Company Name',
    placeholder: 'Surety company name',
    required: true,
    group: 'surety',
  },
  {
    id: 'suretyAddress',
    type: 'text',
    label: 'Surety Company Address',
    placeholder: 'Complete surety address',
    required: true,
    group: 'surety',
  },
  {
    id: 'suretyLicense',
    type: 'text',
    label: 'Surety License Number',
    placeholder: 'Surety license or certificate number',
    required: false,
    group: 'surety',
  },
  {
    id: 'suretyAMBestRating',
    type: 'text',
    label: 'Surety A.M. Best Rating',
    placeholder: 'e.g., A++, A+, A',
    required: false,
    group: 'surety',
  },
  {
    id: 'contractDate',
    type: 'date',
    label: 'Construction Contract Date',
    required: true,
    group: 'contract',
  },
  {
    id: 'contractAmount',
    type: 'text',
    label: 'Contract Amount',
    placeholder: 'Total contract amount',
    required: true,
    group: 'contract',
  },
  {
    id: 'contractDescription',
    type: 'textarea',
    label: 'Contract Description',
    placeholder: 'Description of construction contract',
    required: true,
    group: 'contract',
  },
  {
    id: 'projectName',
    type: 'text',
    label: 'Project Name',
    placeholder: 'Construction project name',
    required: true,
    group: 'project',
  },
  {
    id: 'projectAddress',
    type: 'text',
    label: 'Project Address',
    placeholder: 'Construction site address',
    required: true,
    group: 'project',
  },
  {
    id: 'projectDescription',
    type: 'textarea',
    label: 'Project Description',
    placeholder: 'Detailed project description',
    required: false,
    group: 'project',
  },
  {
    id: 'projectType',
    type: 'select',
    label: 'Project Type',
    options: [
      { value: 'residential', label: 'Residential' },
      { value: 'commercial', label: 'Commercial' },
      { value: 'industrial', label: 'Industrial' },
      { value: 'public', label: 'Public' },
      { value: 'private', label: 'Private' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'project',
  },
  {
    id: 'bondEffectiveDate',
    type: 'date',
    label: 'Bond Effective Date',
    required: true,
    group: 'terms',
  },
  {
    id: 'bondExpirationDate',
    type: 'date',
    label: 'Bond Expiration Date',
    required: false,
    group: 'terms',
  },
  {
    id: 'bondTermination',
    type: 'select',
    label: 'Bond Termination Condition',
    options: [
      { value: 'project-completion', label: 'Project Completion' },
      { value: 'specific-date', label: 'Specific Date' },
      { value: 'payment-completion', label: 'Payment Completion' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'terms',
  },
  {
    id: 'coverageScope',
    type: 'checkbox',
    label: 'Coverage Scope',
    options: [
      { value: 'labor-costs', label: 'Labor Costs' },
      { value: 'material-costs', label: 'Material Costs' },
      { value: 'equipment-costs', label: 'Equipment Costs' },
      { value: 'subcontractor-payments', label: 'Subcontractor Payments' },
      { value: 'supplier-payments', label: 'Supplier Payments' },
      { value: 'other-costs', label: 'Other Costs' },
    ],
    required: true,
    group: 'coverage',
  },
  {
    id: 'claimNotificationPeriod',
    type: 'text',
    label: 'Claim Notification Period',
    placeholder: 'e.g., 90 days, 1 year',
    required: false,
    group: 'claims',
  },
  {
    id: 'claimProcedure',
    type: 'textarea',
    label: 'Claim Procedure',
    placeholder: 'Description of claim filing procedure',
    required: false,
    group: 'claims',
  },
  {
    id: 'laborProtection',
    type: 'checkbox',
    label: 'Labor protection included',
    required: false,
    group: 'protection',
  },
  {
    id: 'materialProtection',
    type: 'checkbox',
    label: 'Material protection included',
    required: false,
    group: 'protection',
  },
  {
    id: 'equipmentProtection',
    type: 'checkbox',
    label: 'Equipment protection included',
    required: false,
    group: 'protection',
  },
  {
    id: 'subcontractorProtection',
    type: 'checkbox',
    label: 'Subcontractor protection included',
    required: false,
    group: 'protection',
  },
  {
    id: 'supplierProtection',
    type: 'checkbox',
    label: 'Supplier protection included',
    required: false,
    group: 'protection',
  },
  {
    id: 'generalExclusions',
    type: 'checkbox',
    label: 'Include general exclusions',
    required: false,
    group: 'exclusions',
  },
  {
    id: 'designExclusions',
    type: 'checkbox',
    label: 'Include design exclusions',
    required: false,
    group: 'exclusions',
  },
  {
    id: 'environmentalExclusions',
    type: 'checkbox',
    label: 'Include environmental exclusions',
    required: false,
    group: 'exclusions',
  },
  {
    id: 'paymentTerms',
    type: 'textarea',
    label: 'Payment Terms',
    placeholder: 'Payment terms and conditions',
    required: false,
    group: 'payment',
  },
  {
    id: 'retainageHandling',
    type: 'textarea',
    label: 'Retainage Handling',
    placeholder: 'How retainage will be handled',
    required: false,
    group: 'payment',
  },
  {
    id: 'millerActCompliance',
    type: 'checkbox',
    label: 'Miller Act compliance required',
    required: false,
    group: 'statutory',
  },
  {
    id: 'littleMillerActCompliance',
    type: 'checkbox',
    label: 'Little Miller Act compliance required',
    required: false,
    group: 'statutory',
  },
  {
    id: 'stateStatuteCompliance',
    type: 'checkbox',
    label: 'State statute compliance required',
    required: false,
    group: 'statutory',
  },
  {
    id: 'noticeToSurety',
    type: 'checkbox',
    label: 'Notice to surety required',
    required: false,
    group: 'notice',
  },
  {
    id: 'noticeToPrincipal',
    type: 'checkbox',
    label: 'Notice to principal required',
    required: false,
    group: 'notice',
  },
  {
    id: 'noticeMethod',
    type: 'select',
    label: 'Notice Method',
    options: [
      { value: 'certified-mail', label: 'Certified Mail' },
      { value: 'registered-mail', label: 'Registered Mail' },
      { value: 'personal-service', label: 'Personal Service' },
      { value: 'email', label: 'Email' },
    ],
    required: false,
    group: 'notice',
  },
  {
    id: 'jointVenture',
    type: 'checkbox',
    label: 'Joint venture involved',
    required: false,
    group: 'joint-venture',
  },
  {
    id: 'bondAssignable',
    type: 'checkbox',
    label: 'Bond is assignable',
    required: false,
    group: 'assignment',
  },
  {
    id: 'modificationRights',
    type: 'checkbox',
    label: 'Bond modification rights included',
    required: false,
    group: 'modification',
  },
  {
    id: 'consentToChanges',
    type: 'checkbox',
    label: 'Consent to contract changes required',
    required: false,
    group: 'modification',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'State governing law',
    required: false,
    group: 'legal',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'litigation', label: 'Court Litigation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'mediation', label: 'Mediation' },
    ],
    required: false,
    group: 'legal',
  },
  {
    id: 'contractAttached',
    type: 'checkbox',
    label: 'Construction contract attached',
    required: false,
    group: 'attachments',
  },
  {
    id: 'plansAttached',
    type: 'checkbox',
    label: 'Plans and drawings attached',
    required: false,
    group: 'attachments',
  },
  {
    id: 'specificationsAttached',
    type: 'checkbox',
    label: 'Specifications attached',
    required: false,
    group: 'attachments',
  },
  {
    id: 'principalCertification',
    type: 'checkbox',
    label: 'Principal certification included',
    required: false,
    group: 'certifications',
  },
  {
    id: 'suretyCertification',
    type: 'checkbox',
    label: 'Surety certification included',
    required: false,
    group: 'certifications',
  },
  {
    id: 'principalSignature',
    type: 'checkbox',
    label: 'Require principal signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'suretySignature',
    type: 'checkbox',
    label: 'Require surety signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'attorneyInFactSignature',
    type: 'checkbox',
    label: 'Attorney-in-fact signature required',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireNotarization',
    type: 'checkbox',
    label: 'Require notarization',
    required: false,
    group: 'notary',
  },
  {
    id: 'notaryState',
    type: 'text',
    label: 'Notary State',
    placeholder: 'State where notarized',
    required: false,
    group: 'notary',
    dependsOn: 'requireNotarization',
  },
  {
    id: 'notaryCounty',
    type: 'text',
    label: 'Notary County',
    placeholder: 'County where notarized',
    required: false,
    group: 'notary',
    dependsOn: 'requireNotarization',
  },
];