// src/lib/documents/us/security-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const securityAgreementQuestions: FormQuestion[] = [
  {
    id: 'securedPartyName',
    type: 'text',
    label: 'Secured Party Name',
    placeholder: 'Enter secured party (creditor) name',
    required: true,
    group: 'secured-party',
  },
  {
    id: 'securedPartyAddress',
    type: 'text',
    label: 'Secured Party Address',
    placeholder: 'Enter complete secured party address',
    required: true,
    group: 'secured-party',
  },
  {
    id: 'securedPartyType',
    type: 'select',
    label: 'Secured Party Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'partnership', label: 'Partnership' },
      { value: 'llc', label: 'LLC' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'secured-party',
  },
  {
    id: 'debtorName',
    type: 'text',
    label: 'Debtor Name',
    placeholder: 'Enter debtor (borrower) name',
    required: true,
    group: 'debtor',
  },
  {
    id: 'debtorAddress',
    type: 'text',
    label: 'Debtor Address',
    placeholder: 'Enter complete debtor address',
    required: true,
    group: 'debtor',
  },
  {
    id: 'debtorType',
    type: 'select',
    label: 'Debtor Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'partnership', label: 'Partnership' },
      { value: 'llc', label: 'LLC' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'debtor',
  },
  {
    id: 'debtorSSN',
    type: 'text',
    label: 'Debtor SSN (for individuals)',
    placeholder: 'Enter Social Security Number',
    required: false,
    group: 'debtor',
  },
  {
    id: 'debtorEIN',
    type: 'text',
    label: 'Debtor EIN (for businesses)',
    placeholder: 'Enter Employer Identification Number',
    required: false,
    group: 'debtor',
  },
  {
    id: 'agreementDate',
    type: 'date',
    label: 'Agreement Date',
    required: true,
    group: 'basic',
  },
  {
    id: 'securedDebtAmount',
    type: 'text',
    label: 'Secured Debt Amount',
    placeholder: 'Amount of debt being secured',
    required: true,
    group: 'obligation',
  },
  {
    id: 'securedDebtDescription',
    type: 'textarea',
    label: 'Description of Secured Debt',
    placeholder: 'Describe the debt or obligation being secured',
    required: true,
    group: 'obligation',
  },
  {
    id: 'maxSecuredAmount',
    type: 'text',
    label: 'Maximum Secured Amount (optional)',
    placeholder: 'Maximum amount that may be secured',
    required: false,
    group: 'obligation',
  },
  {
    id: 'interestRate',
    type: 'text',
    label: 'Interest Rate (if applicable)',
    placeholder: 'e.g., 6% per year',
    required: false,
    group: 'obligation',
  },
  {
    id: 'collateralType',
    type: 'select',
    label: 'Type of Collateral',
    options: [
      { value: 'goods', label: 'Goods' },
      { value: 'equipment', label: 'Equipment' },
      { value: 'inventory', label: 'Inventory' },
      { value: 'accounts', label: 'Accounts Receivable' },
      { value: 'instruments', label: 'Instruments' },
      { value: 'documents', label: 'Documents' },
      { value: 'chattel-paper', label: 'Chattel Paper' },
      { value: 'general-intangibles', label: 'General Intangibles' },
      { value: 'investment-property', label: 'Investment Property' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'collateral',
  },
  {
    id: 'collateralDescription',
    type: 'textarea',
    label: 'Detailed Collateral Description',
    placeholder: 'Provide detailed description of collateral property',
    required: true,
    group: 'collateral',
  },
  {
    id: 'collateralLocation',
    type: 'text',
    label: 'Collateral Location',
    placeholder: 'Where the collateral is located',
    required: true,
    group: 'collateral',
  },
  {
    id: 'futureAdvances',
    type: 'checkbox',
    label: 'Secure future advances',
    required: false,
    group: 'advances',
  },
  {
    id: 'maxFutureAdvances',
    type: 'text',
    label: 'Maximum Future Advances',
    placeholder: 'Maximum amount of future advances',
    required: false,
    group: 'advances',
    dependsOn: 'futureAdvances',
  },
  {
    id: 'afterAcquiredProperty',
    type: 'checkbox',
    label: 'Include after-acquired property',
    required: false,
    group: 'after-acquired',
  },
  {
    id: 'afterAcquiredDescription',
    type: 'textarea',
    label: 'After-Acquired Property Description',
    placeholder: 'Describe types of after-acquired property',
    required: false,
    group: 'after-acquired',
    dependsOn: 'afterAcquiredProperty',
  },
  {
    id: 'proceedsCoverage',
    type: 'checkbox',
    label: 'Security interest covers proceeds',
    required: false,
    group: 'proceeds',
  },
  {
    id: 'maintainCollateral',
    type: 'checkbox',
    label: 'Debtor must maintain collateral',
    required: false,
    group: 'covenants',
  },
  {
    id: 'insuranceRequired',
    type: 'checkbox',
    label: 'Require insurance on collateral',
    required: false,
    group: 'covenants',
  },
  {
    id: 'insuranceAmount',
    type: 'text',
    label: 'Required Insurance Amount',
    placeholder: 'Minimum insurance coverage amount',
    required: false,
    group: 'insurance',
    dependsOn: 'insuranceRequired',
  },
  {
    id: 'prohibitSale',
    type: 'checkbox',
    label: 'Prohibit sale of collateral without consent',
    required: false,
    group: 'covenants',
  },
  {
    id: 'prohibitEncumbrance',
    type: 'checkbox',
    label: 'Prohibit additional liens on collateral',
    required: false,
    group: 'covenants',
  },
  {
    id: 'allowInspection',
    type: 'checkbox',
    label: 'Allow secured party to inspect collateral',
    required: false,
    group: 'covenants',
  },
  {
    id: 'curePeriod',
    type: 'text',
    label: 'Cure Period for Default',
    placeholder: 'e.g., 30 days to cure default',
    required: false,
    group: 'default',
  },
  {
    id: 'defaultNotice',
    type: 'checkbox',
    label: 'Require notice before declaring default',
    required: false,
    group: 'default',
  },
  {
    id: 'rightToTake',
    type: 'checkbox',
    label: 'Right to take possession upon default',
    required: false,
    group: 'remedies',
  },
  {
    id: 'rightToSell',
    type: 'checkbox',
    label: 'Right to sell collateral upon default',
    required: false,
    group: 'remedies',
  },
  {
    id: 'commerciallyReasonable',
    type: 'checkbox',
    label: 'Require commercially reasonable disposition',
    required: false,
    group: 'remedies',
  },
  {
    id: 'dispositionNotice',
    type: 'checkbox',
    label: 'Provide notice before disposing of collateral',
    required: false,
    group: 'notice',
  },
  {
    id: 'noticeMethod',
    type: 'select',
    label: 'Notice Method',
    options: [
      { value: 'mail', label: 'Mail' },
      { value: 'email', label: 'Email' },
      { value: 'personal-delivery', label: 'Personal Delivery' },
    ],
    required: false,
    group: 'notice',
  },
  {
    id: 'noticePeriod',
    type: 'text',
    label: 'Notice Period',
    placeholder: 'e.g., 10 days before disposition',
    required: false,
    group: 'notice',
  },
  {
    id: 'uccFilingAuthorized',
    type: 'checkbox',
    label: 'Authorize UCC financing statement filing',
    required: false,
    group: 'ucc-filing',
  },
  {
    id: 'uccFilingState',
    type: 'text',
    label: 'State for UCC Filing',
    placeholder: 'State where UCC statement will be filed',
    required: false,
    group: 'ucc-filing',
  },
  {
    id: 'assignmentAllowed',
    type: 'checkbox',
    label: 'Allow assignment of security interest',
    required: false,
    group: 'assignment',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law (State)',
    placeholder: 'e.g., State of California',
    required: false,
    group: 'legal',
  },
  {
    id: 'attorneyFees',
    type: 'checkbox',
    label: 'Include attorney fees clause',
    required: false,
    group: 'legal',
  },
  {
    id: 'waiveJuryTrial',
    type: 'checkbox',
    label: 'Waive right to jury trial',
    required: false,
    group: 'legal',
  },
  {
    id: 'releaseOfLien',
    type: 'checkbox',
    label: 'Automatic release upon payment',
    required: false,
    group: 'termination',
  },
  {
    id: 'requireNotarization',
    type: 'checkbox',
    label: 'Require notarization',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireDebtorSignature',
    type: 'checkbox',
    label: 'Require debtor signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireSecuredPartySignature',
    type: 'checkbox',
    label: 'Require secured party signature',
    required: false,
    group: 'signatures',
  },
];
