// src/lib/documents/us/remodeling-contract/questions.ts
import type { FormQuestion } from '@/types/documents';

export const remodelingContractQuestions: FormQuestion[] = [
  {
    id: 'homeownerName',
    type: 'text',
    label: 'Homeowner Name',
    placeholder: 'Enter homeowner full name',
    required: true,
    group: 'homeowner',
  },
  {
    id: 'homeownerAddress',
    type: 'text',
    label: 'Homeowner Address',
    placeholder: 'Enter complete homeowner address',
    required: true,
    group: 'homeowner',
  },
  {
    id: 'homeownerPhone',
    type: 'text',
    label: 'Homeowner Phone',
    placeholder: 'Enter phone number',
    required: true,
    group: 'homeowner',
  },
  {
    id: 'homeownerEmail',
    type: 'email',
    label: 'Homeowner Email',
    placeholder: 'Enter email address',
    required: false,
    group: 'homeowner',
  },
  {
    id: 'contractorName',
    type: 'text',
    label: 'Contractor Name',
    placeholder: 'Enter contractor/company name',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorAddress',
    type: 'text',
    label: 'Contractor Address',
    placeholder: 'Enter complete contractor address',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorPhone',
    type: 'text',
    label: 'Contractor Phone',
    placeholder: 'Enter phone number',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorLicense',
    type: 'text',
    label: 'Contractor License Number',
    placeholder: 'Enter contractor license number',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorInsurance',
    type: 'text',
    label: 'Insurance Information',
    placeholder: 'Insurance company and policy details',
    required: true,
    group: 'contractor',
  },
  {
    id: 'projectAddress',
    type: 'text',
    label: 'Project Address',
    placeholder: 'Where remodeling will take place',
    required: true,
    group: 'project',
  },
  {
    id: 'projectDescription',
    type: 'textarea',
    label: 'Project Description',
    placeholder: 'Detailed description of remodeling work',
    required: true,
    group: 'project',
  },
  {
    id: 'remodelingType',
    type: 'select',
    label: 'Type of Remodeling',
    options: [
      { value: 'kitchen', label: 'Kitchen Remodel' },
      { value: 'bathroom', label: 'Bathroom Remodel' },
      { value: 'basement', label: 'Basement Finishing' },
      { value: 'attic', label: 'Attic Conversion' },
      { value: 'room-addition', label: 'Room Addition' },
      { value: 'whole-house', label: 'Whole House Remodel' },
      { value: 'exterior', label: 'Exterior Remodel' },
      { value: 'multiple-rooms', label: 'Multiple Rooms' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'project',
  },
  {
    id: 'workScope',
    type: 'textarea',
    label: 'Detailed Work Scope',
    placeholder: 'Specific work to be performed',
    required: true,
    group: 'scope',
  },
  {
    id: 'materialsIncluded',
    type: 'checkbox',
    label: 'Contractor provides materials',
    required: false,
    group: 'scope',
  },
  {
    id: 'materialsList',
    type: 'textarea',
    label: 'Materials List',
    placeholder: 'List of materials to be provided',
    required: false,
    group: 'scope',
    dependsOn: 'materialsIncluded',
  },
  {
    id: 'contractDate',
    type: 'date',
    label: 'Contract Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'startDate',
    type: 'date',
    label: 'Project Start Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'completionDate',
    type: 'date',
    label: 'Project Completion Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'workingHours',
    type: 'text',
    label: 'Working Hours',
    placeholder: 'e.g., 8:00 AM - 5:00 PM',
    required: false,
    group: 'timeline',
  },
  {
    id: 'contractPrice',
    type: 'text',
    label: 'Total Contract Price',
    placeholder: 'Enter total project cost',
    required: true,
    group: 'pricing',
  },
  {
    id: 'priceType',
    type: 'select',
    label: 'Price Type',
    options: [
      { value: 'fixed-price', label: 'Fixed Price' },
      { value: 'cost-plus-fixed-fee', label: 'Cost Plus Fixed Fee' },
      { value: 'time-and-materials', label: 'Time and Materials' },
    ],
    required: true,
    group: 'pricing',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      {
        value: 'upfront-progress-final',
        label: 'Down Payment + Progress + Final',
      },
      { value: 'milestone-based', label: 'Milestone-Based Payments' },
      { value: 'weekly', label: 'Weekly Payments' },
      { value: 'monthly', label: 'Monthly Payments' },
    ],
    required: true,
    group: 'payment',
  },
  {
    id: 'downPayment',
    type: 'text',
    label: 'Down Payment Amount',
    placeholder: 'Initial payment amount',
    required: false,
    group: 'payment',
  },
  {
    id: 'permitsRequired',
    type: 'checkbox',
    label: 'Building permits required',
    required: false,
    group: 'permits',
  },
  {
    id: 'permitResponsibility',
    type: 'select',
    label: 'Permit Responsibility',
    options: [
      { value: 'homeowner', label: 'Homeowner Responsible' },
      { value: 'contractor', label: 'Contractor Responsible' },
      { value: 'shared', label: 'Shared Responsibility' },
    ],
    required: false,
    group: 'permits',
    dependsOn: 'permitsRequired',
  },
  {
    id: 'materialSelection',
    type: 'select',
    label: 'Material Selection',
    options: [
      { value: 'homeowner-selects', label: 'Homeowner Selects' },
      { value: 'contractor-selects', label: 'Contractor Selects' },
      { value: 'joint-selection', label: 'Joint Selection' },
    ],
    required: true,
    group: 'materials',
  },
  {
    id: 'materialApproval',
    type: 'checkbox',
    label: 'Homeowner approval required for materials',
    required: false,
    group: 'materials',
  },
  {
    id: 'wasteDisposal',
    type: 'select',
    label: 'Waste Disposal Responsibility',
    options: [
      { value: 'contractor-responsibility', label: 'Contractor Responsible' },
      { value: 'homeowner-responsibility', label: 'Homeowner Responsible' },
      { value: 'shared', label: 'Shared Responsibility' },
    ],
    required: true,
    group: 'materials',
  },
  {
    id: 'changeOrderProcess',
    type: 'checkbox',
    label: 'Include change order procedures',
    required: false,
    group: 'changes',
  },
  {
    id: 'changeOrderApproval',
    type: 'select',
    label: 'Change Order Approval',
    options: [
      { value: 'written-only', label: 'Written Approval Only' },
      { value: 'verbal-written', label: 'Verbal + Written Confirmation' },
      { value: 'homeowner-approval', label: 'Homeowner Approval Required' },
    ],
    required: false,
    group: 'changes',
    dependsOn: 'changeOrderProcess',
  },
  {
    id: 'contractorInsuranceCoverage',
    type: 'text',
    label: 'Insurance Coverage Amount',
    placeholder: 'Minimum coverage amount required',
    required: true,
    group: 'insurance',
  },
  {
    id: 'liabilityInsurance',
    type: 'checkbox',
    label: 'General liability insurance required',
    required: false,
    group: 'insurance',
  },
  {
    id: 'workersCompensation',
    type: 'checkbox',
    label: 'Workers compensation insurance required',
    required: false,
    group: 'insurance',
  },
  {
    id: 'workmanshipWarranty',
    type: 'checkbox',
    label: 'Include workmanship warranty',
    required: false,
    group: 'warranty',
  },
  {
    id: 'warrantyPeriod',
    type: 'text',
    label: 'Warranty Period',
    placeholder: 'e.g., 1 year, 2 years',
    required: false,
    group: 'warranty',
    dependsOn: 'workmanshipWarranty',
  },
  {
    id: 'safetyMeasures',
    type: 'checkbox',
    label: 'Safety measures required',
    required: false,
    group: 'safety',
  },
  {
    id: 'propertyProtection',
    type: 'checkbox',
    label: 'Property protection required',
    required: false,
    group: 'safety',
  },
  {
    id: 'cleanupDaily',
    type: 'checkbox',
    label: 'Daily cleanup required',
    required: false,
    group: 'cleanup',
  },
  {
    id: 'cleanupFinal',
    type: 'checkbox',
    label: 'Final cleanup included',
    required: false,
    group: 'cleanup',
  },
  {
    id: 'subcontractorsAllowed',
    type: 'checkbox',
    label: 'Subcontractors allowed',
    required: false,
    group: 'subcontractors',
  },
  {
    id: 'subcontractorApproval',
    type: 'checkbox',
    label: 'Homeowner approval required for subcontractors',
    required: false,
    group: 'subcontractors',
    dependsOn: 'subcontractorsAllowed',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'negotiation', label: 'Negotiation' },
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'litigation', label: 'Court Litigation' },
    ],
    required: true,
    group: 'disputes',
  },
  {
    id: 'terminationClause',
    type: 'checkbox',
    label: 'Include termination clause',
    required: false,
    group: 'termination',
  },
  {
    id: 'terminationNotice',
    type: 'text',
    label: 'Termination Notice Period',
    placeholder: 'e.g., 3 days written notice',
    required: false,
    group: 'termination',
    dependsOn: 'terminationClause',
  },
];
