// src/lib/documents/us/lease-amendment/questions.ts
import type { FormQuestion } from '@/types/documents';

export const leaseAmendmentQuestions: FormQuestion[] = [
  {
    id: 'originalLeaseDate',
    type: 'date',
    label: 'Original Lease Date',
    required: true,
    group: 'original-lease',
  },
  {
    id: 'propertyAddress',
    type: 'textarea',
    label: 'Property Address',
    placeholder: 'Enter the full property address',
    required: true,
    group: 'original-lease',
  },
  {
    id: 'landlordName',
    type: 'text',
    label: 'Landlord Name',
    placeholder: "Enter landlord's full name",
    required: true,
    group: 'parties',
  },
  {
    id: 'landlordAddress',
    type: 'textarea',
    label: 'Landlord Address',
    placeholder: "Enter landlord's address",
    required: true,
    group: 'parties',
  },
  {
    id: 'tenantName',
    type: 'text',
    label: 'Tenant Name',
    placeholder: "Enter tenant's full name",
    required: true,
    group: 'parties',
  },
  {
    id: 'amendmentDate',
    type: 'date',
    label: 'Amendment Date',
    required: true,
    group: 'amendment',
  },
  {
    id: 'amendmentType',
    type: 'select',
    label: 'Type of Amendment',
    options: [
      { value: 'rent-change', label: 'Rent Change' },
      { value: 'term-extension', label: 'Term Extension' },
      { value: 'term-modification', label: 'Term Modification' },
      { value: 'add-provision', label: 'Add Provision' },
      { value: 'remove-provision', label: 'Remove Provision' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'amendment',
  },
  {
    id: 'rentChange',
    type: 'checkbox',
    label: 'Rent Change',
    required: false,
    group: 'rent',
  },
  {
    id: 'currentRent',
    type: 'number',
    label: 'Current Monthly Rent ($)',
    placeholder: '1200',
    required: false,
    group: 'rent',
    dependsOn: 'rentChange',
  },
  {
    id: 'newRent',
    type: 'number',
    label: 'New Monthly Rent ($)',
    placeholder: '1350',
    required: false,
    group: 'rent',
    dependsOn: 'rentChange',
  },
  {
    id: 'rentChangeEffectiveDate',
    type: 'date',
    label: 'Rent Change Effective Date',
    required: false,
    group: 'rent',
    dependsOn: 'rentChange',
  },
  {
    id: 'termChange',
    type: 'checkbox',
    label: 'Lease Term Change',
    required: false,
    group: 'term',
  },
  {
    id: 'currentLeaseEndDate',
    type: 'date',
    label: 'Current Lease End Date',
    required: false,
    group: 'term',
    dependsOn: 'termChange',
  },
  {
    id: 'newLeaseEndDate',
    type: 'date',
    label: 'New Lease End Date',
    required: false,
    group: 'term',
    dependsOn: 'termChange',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Amendment Effective Date',
    required: true,
    group: 'legal',
  },
  {
    id: 'governingState',
    type: 'text',
    label: 'Governing State',
    placeholder: 'e.g., California',
    required: true,
    group: 'legal',
  },
  {
    id: 'additionalTerms',
    type: 'textarea',
    label: 'Additional Terms',
    placeholder: 'Any additional terms or modifications',
    required: false,
    group: 'additional',
  },
];
