// src/lib/documents/us/landscaping-contract/questions.ts
import type { FormQuestion } from '@/types/documents';

export const landscapingContractQuestions: FormQuestion[] = [
  {
    id: 'ownerName',
    type: 'text',
    label: 'Property Owner Name',
    placeholder: 'Enter property owner full name',
    required: true,
    group: 'owner',
  },
  {
    id: 'ownerAddress',
    type: 'text',
    label: 'Owner Address',
    placeholder: 'Enter complete owner address',
    required: true,
    group: 'owner',
  },
  {
    id: 'ownerPhone',
    type: 'text',
    label: 'Owner Phone',
    placeholder: 'Enter phone number',
    required: true,
    group: 'owner',
  },
  {
    id: 'contractorName',
    type: 'text',
    label: 'Landscaping Contractor Name',
    placeholder: 'Enter contractor/company name',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorAddress',
    type: 'text',
    label: 'Contractor Address',
    placeholder: 'Enter complete contractor address',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorPhone',
    type: 'text',
    label: 'Contractor Phone',
    placeholder: 'Enter phone number',
    required: true,
    group: 'contractor',
  },
  {
    id: 'businessInsurance',
    type: 'text',
    label: 'Business Insurance Information',
    placeholder: 'Insurance company and policy details',
    required: true,
    group: 'contractor',
  },
  {
    id: 'projectAddress',
    type: 'text',
    label: 'Project Address',
    placeholder: 'Where landscaping work will be performed',
    required: true,
    group: 'project',
  },
  {
    id: 'serviceType',
    type: 'select',
    label: 'Type of Landscaping Service',
    options: [
      { value: 'design-installation', label: 'Design and Installation' },
      { value: 'installation-only', label: 'Installation Only' },
      { value: 'maintenance', label: 'Ongoing Maintenance' },
      { value: 'one-time-service', label: 'One-Time Service' },
      { value: 'seasonal-maintenance', label: 'Seasonal Maintenance' },
    ],
    required: true,
    group: 'project',
  },
  {
    id: 'projectDescription',
    type: 'textarea',
    label: 'Project Description',
    placeholder: 'Detailed description of landscaping work to be performed',
    required: true,
    group: 'project',
  },
  {
    id: 'propertySize',
    type: 'text',
    label: 'Property Size',
    placeholder: 'Enter property size (e.g., 1/2 acre, 5,000 sq ft)',
    required: false,
    group: 'project',
  },
  {
    id: 'designServices',
    type: 'checkbox',
    label: 'Include landscape design services',
    required: false,
    group: 'services',
  },
  {
    id: 'plantInstallation',
    type: 'checkbox',
    label: 'Plant installation',
    required: false,
    group: 'services',
  },
  {
    id: 'sodInstallation',
    type: 'checkbox',
    label: 'Sod installation',
    required: false,
    group: 'services',
  },
  {
    id: 'irrigationInstall',
    type: 'checkbox',
    label: 'Irrigation system installation',
    required: false,
    group: 'services',
  },
  {
    id: 'hardscaping',
    type: 'checkbox',
    label: 'Hardscaping (patios, walkways, etc.)',
    required: false,
    group: 'services',
  },
  {
    id: 'materialsIncluded',
    type: 'checkbox',
    label: 'Contractor provides all materials',
    required: false,
    group: 'materials',
  },
  {
    id: 'plantSelection',
    type: 'select',
    label: 'Plant Selection',
    options: [
      { value: 'contractor-selects', label: 'Contractor Selects' },
      { value: 'owner-selects', label: 'Owner Selects' },
      { value: 'joint-selection', label: 'Joint Selection' },
    ],
    required: true,
    group: 'materials',
  },
  {
    id: 'plantWarranty',
    type: 'checkbox',
    label: 'Include plant warranty',
    required: false,
    group: 'materials',
  },
  {
    id: 'plantWarrantyPeriod',
    type: 'text',
    label: 'Plant Warranty Period',
    placeholder: 'e.g., 90 days, 1 year',
    required: false,
    group: 'materials',
    dependsOn: 'plantWarranty',
  },
  {
    id: 'contractDate',
    type: 'date',
    label: 'Contract Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'startDate',
    type: 'date',
    label: 'Start Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'completionDate',
    type: 'date',
    label: 'Completion Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'weatherDelayPolicy',
    type: 'checkbox',
    label: 'Include weather delay policy',
    required: false,
    group: 'timeline',
  },
  {
    id: 'contractPrice',
    type: 'text',
    label: 'Total Contract Price',
    placeholder: 'Enter total landscaping project cost',
    required: true,
    group: 'pricing',
  },
  {
    id: 'priceType',
    type: 'select',
    label: 'Price Type',
    options: [
      { value: 'fixed-price', label: 'Fixed Price' },
      { value: 'hourly-rate', label: 'Hourly Rate' },
      { value: 'per-square-foot', label: 'Per Square Foot' },
      { value: 'per-plant', label: 'Per Plant' },
    ],
    required: true,
    group: 'pricing',
  },
  {
    id: 'hourlyRate',
    type: 'text',
    label: 'Hourly Rate',
    placeholder: 'Enter hourly rate',
    required: false,
    group: 'pricing',
    dependsOn: 'priceType',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'upfront', label: 'Payment Upfront' },
      { value: 'progress-payments', label: 'Progress Payments' },
      { value: 'monthly', label: 'Monthly Payments' },
      { value: 'seasonal', label: 'Seasonal Payments' },
      { value: 'completion', label: 'Payment on Completion' },
    ],
    required: true,
    group: 'payment',
  },
  {
    id: 'downPayment',
    type: 'text',
    label: 'Down Payment Amount',
    placeholder: 'Initial payment amount',
    required: false,
    group: 'payment',
  },
  {
    id: 'maintenanceIncluded',
    type: 'checkbox',
    label: 'Include ongoing maintenance services',
    required: false,
    group: 'maintenance',
  },
  {
    id: 'maintenanceSchedule',
    type: 'text',
    label: 'Maintenance Schedule',
    placeholder: 'e.g., Weekly, Bi-weekly, Monthly',
    required: false,
    group: 'maintenance',
    dependsOn: 'maintenanceIncluded',
  },
  {
    id: 'seasonalCleanup',
    type: 'checkbox',
    label: 'Include seasonal cleanup',
    required: false,
    group: 'maintenance',
  },
  {
    id: 'sitePreparation',
    type: 'checkbox',
    label: 'Site preparation included',
    required: false,
    group: 'preparation',
  },
  {
    id: 'soilTesting',
    type: 'checkbox',
    label: 'Soil testing required',
    required: false,
    group: 'preparation',
  },
  {
    id: 'grading',
    type: 'checkbox',
    label: 'Grading work required',
    required: false,
    group: 'preparation',
  },
  {
    id: 'permitsRequired',
    type: 'checkbox',
    label: 'Permits required',
    required: false,
    group: 'permits',
  },
  {
    id: 'permitResponsibility',
    type: 'select',
    label: 'Permit Responsibility',
    options: [
      { value: 'owner', label: 'Owner Responsible' },
      { value: 'contractor', label: 'Contractor Responsible' },
    ],
    required: false,
    group: 'permits',
    dependsOn: 'permitsRequired',
  },
  {
    id: 'cleanupIncluded',
    type: 'checkbox',
    label: 'Daily cleanup included',
    required: false,
    group: 'cleanup',
  },
  {
    id: 'debrisRemoval',
    type: 'checkbox',
    label: 'Debris removal included',
    required: false,
    group: 'cleanup',
  },
  {
    id: 'liabilityInsurance',
    type: 'text',
    label: 'Liability Insurance Amount',
    placeholder: 'Minimum coverage amount required',
    required: true,
    group: 'insurance',
  },
  {
    id: 'workersCompensation',
    type: 'checkbox',
    label: 'Workers compensation insurance required',
    required: false,
    group: 'insurance',
  },
  {
    id: 'fertilizationIncluded',
    type: 'checkbox',
    label: 'Fertilization services included',
    required: false,
    group: 'chemicals',
  },
  {
    id: 'pestControlIncluded',
    type: 'checkbox',
    label: 'Pest control services included',
    required: false,
    group: 'chemicals',
  },
  {
    id: 'organicMethods',
    type: 'checkbox',
    label: 'Use organic methods only',
    required: false,
    group: 'chemicals',
  },
  {
    id: 'changeOrderProcess',
    type: 'checkbox',
    label: 'Include change order procedures',
    required: false,
    group: 'changes',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'negotiation', label: 'Negotiation' },
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'litigation', label: 'Court Litigation' },
    ],
    required: true,
    group: 'disputes',
  },
];
