// src/lib/documents/us/sponsorship-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const sponsorshipAgreementQuestions: FormQuestion[] = [
  {
    id: 'sponsorName',
    type: 'text',
    label: 'Sponsor Company Name',
    placeholder: 'Enter sponsor company name',
    required: true,
    group: 'sponsor',
  },
  {
    id: 'sponsorContactPerson',
    type: 'text',
    label: 'Sponsor Contact Person',
    placeholder: 'Enter contact person name',
    required: false,
    group: 'sponsor',
  },
  {
    id: 'sponsorEmail',
    type: 'email',
    label: 'Sponsor Email',
    placeholder: 'Enter sponsor email',
    required: false,
    group: 'sponsor',
  },
  {
    id: 'sponsoredPartyName',
    type: 'text',
    label: 'Sponsored Party Name',
    placeholder: 'Enter sponsored party name',
    required: true,
    group: 'sponsored',
  },
  {
    id: 'sponsoredPartyType',
    type: 'select',
    label: 'Sponsored Party Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'team', label: 'Team' },
      { value: 'organization', label: 'Organization' },
      { value: 'event', label: 'Event' },
      { value: 'venue', label: 'Venue' },
    ],
    required: false,
    group: 'sponsored',
  },
  {
    id: 'sponsorshipType',
    type: 'select',
    label: 'Sponsorship Type',
    options: [
      { value: 'event', label: 'Event Sponsorship' },
      { value: 'sports', label: 'Sports Sponsorship' },
      { value: 'media', label: 'Media Sponsorship' },
      { value: 'venue', label: 'Venue Sponsorship' },
      { value: 'program', label: 'Program Sponsorship' },
      { value: 'individual', label: 'Individual Sponsorship' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
    group: 'sponsorship',
  },
  {
    id: 'sponsorshipLevel',
    type: 'select',
    label: 'Sponsorship Level',
    options: [
      { value: 'title', label: 'Title Sponsor' },
      { value: 'presenting', label: 'Presenting Sponsor' },
      { value: 'platinum', label: 'Platinum' },
      { value: 'gold', label: 'Gold' },
      { value: 'silver', label: 'Silver' },
      { value: 'bronze', label: 'Bronze' },
      { value: 'supporting', label: 'Supporting' },
    ],
    required: false,
    group: 'sponsorship',
  },
  {
    id: 'exclusivity',
    type: 'boolean',
    label: 'Exclusive sponsorship?',
    required: false,
    group: 'sponsorship',
  },
  {
    id: 'eventName',
    type: 'text',
    label: 'Event/Activity Name',
    placeholder: 'Enter event or activity name',
    required: false,
    group: 'event',
  },
  {
    id: 'eventDate',
    type: 'date',
    label: 'Event Date',
    required: false,
    group: 'event',
  },
  {
    id: 'eventLocation',
    type: 'text',
    label: 'Event Location',
    placeholder: 'Enter event location',
    required: false,
    group: 'event',
  },
  {
    id: 'sponsorshipFee',
    type: 'text',
    label: 'Sponsorship Fee',
    placeholder: 'Enter sponsorship fee amount',
    required: false,
    group: 'financial',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'upfront', label: 'Upfront Payment' },
      { value: 'installments', label: 'Installments' },
      { value: 'milestone-based', label: 'Milestone Based' },
      { value: 'performance-based', label: 'Performance Based' },
    ],
    required: false,
    group: 'financial',
  },
  {
    id: 'inkindValue',
    type: 'text',
    label: 'In-Kind Value',
    placeholder: 'Enter value of in-kind contributions',
    required: false,
    group: 'financial',
  },
  {
    id: 'logoPlacement',
    type: 'boolean',
    label: 'Logo placement rights?',
    required: false,
    group: 'benefits',
  },
  {
    id: 'namingRights',
    type: 'boolean',
    label: 'Naming rights?',
    required: false,
    group: 'benefits',
  },
  {
    id: 'speakingOpportunity',
    type: 'boolean',
    label: 'Speaking opportunity?',
    required: false,
    group: 'benefits',
  },
  {
    id: 'boothSpace',
    type: 'boolean',
    label: 'Booth/exhibition space?',
    required: false,
    group: 'benefits',
  },
  {
    id: 'ticketsProvided',
    type: 'text',
    label: 'Tickets/Passes Provided',
    placeholder: 'Enter number of tickets/passes',
    required: false,
    group: 'benefits',
  },
  {
    id: 'socialMediaRights',
    type: 'boolean',
    label: 'Social media rights?',
    required: false,
    group: 'marketing',
  },
  {
    id: 'websitePresence',
    type: 'boolean',
    label: 'Website presence?',
    required: false,
    group: 'marketing',
  },
  {
    id: 'activationBudget',
    type: 'text',
    label: 'Activation Budget',
    placeholder: 'Enter activation budget amount',
    required: false,
    group: 'activation',
  },
  {
    id: 'deliverables',
    type: 'textarea',
    label: 'Deliverables',
    placeholder: 'List sponsorship deliverables',
    required: false,
    group: 'performance',
  },
  {
    id: 'agreementStartDate',
    type: 'date',
    label: 'Agreement Start Date',
    required: false,
    group: 'term',
  },
  {
    id: 'agreementEndDate',
    type: 'date',
    label: 'Agreement End Date',
    required: false,
    group: 'term',
  },
  {
    id: 'renewalOptions',
    type: 'boolean',
    label: 'Renewal options?',
    required: false,
    group: 'term',
  },
  {
    id: 'competitorExclusion',
    type: 'boolean',
    label: 'Competitor exclusion?',
    required: false,
    group: 'exclusions',
  },
  {
    id: 'categoryExclusivity',
    type: 'boolean',
    label: 'Category exclusivity?',
    required: false,
    group: 'exclusions',
  },
  {
    id: 'terminationNotice',
    type: 'text',
    label: 'Termination Notice Period',
    placeholder: 'Enter notice period (e.g., 30 days)',
    required: false,
    group: 'termination',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'Enter governing law/state',
    required: false,
    group: 'legal',
  },
];