// src/lib/documents/us/patent-license-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const patentLicenseAgreementQuestions: FormQuestion[] = [
  {
    id: 'licensorName',
    type: 'text',
    label: 'Licensor Name (Patent Owner)',
    placeholder: 'Enter patent owner name',
    required: true,
    group: 'licensor',
  },
  {
    id: 'licensorAddress',
    type: 'text',
    label: 'Licensor Address',
    placeholder: 'Enter complete licensor address',
    required: true,
    group: 'licensor',
  },
  {
    id: 'licensorType',
    type: 'select',
    label: 'Licensor Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'partnership', label: 'Partnership' },
      { value: 'llc', label: 'LLC' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'licensor',
  },
  {
    id: 'licenseeName',
    type: 'text',
    label: 'Licensee Name',
    placeholder: 'Enter licensee name',
    required: true,
    group: 'licensee',
  },
  {
    id: 'licenseeAddress',
    type: 'text',
    label: 'Licensee Address',
    placeholder: 'Enter complete licensee address',
    required: true,
    group: 'licensee',
  },
  {
    id: 'licenseeType',
    type: 'select',
    label: 'Licensee Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'partnership', label: 'Partnership' },
      { value: 'llc', label: 'LLC' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'licensee',
  },
  {
    id: 'licenseDate',
    type: 'date',
    label: 'License Agreement Date',
    required: true,
    group: 'dates',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Effective Date',
    required: true,
    group: 'dates',
  },
  {
    id: 'patentTitle',
    type: 'text',
    label: 'Patent Title',
    placeholder: 'Enter patent title/invention name',
    required: true,
    group: 'patent',
  },
  {
    id: 'patentNumber',
    type: 'text',
    label: 'Patent Number (if issued)',
    placeholder: 'Enter U.S. Patent Number',
    required: false,
    group: 'patent',
  },
  {
    id: 'applicationNumber',
    type: 'text',
    label: 'Application Number',
    placeholder: 'Enter patent application number',
    required: false,
    group: 'patent',
  },
  {
    id: 'filingDate',
    type: 'date',
    label: 'Filing Date',
    required: false,
    group: 'patent',
  },
  {
    id: 'issuanceDate',
    type: 'date',
    label: 'Issuance Date (if issued)',
    required: false,
    group: 'patent',
  },
  {
    id: 'includeMultiplePatents',
    type: 'checkbox',
    label: 'License covers multiple patents',
    required: false,
    group: 'patent',
  },
  {
    id: 'licenseType',
    type: 'select',
    label: 'License Type',
    options: [
      { value: 'exclusive', label: 'Exclusive License' },
      { value: 'non-exclusive', label: 'Non-exclusive License' },
      { value: 'sole', label: 'Sole License' },
      { value: 'co-exclusive', label: 'Co-exclusive License' },
    ],
    required: true,
    group: 'license-grant',
  },
  {
    id: 'licenseScope',
    type: 'select',
    label: 'Licensed Rights',
    options: [
      { value: 'make', label: 'Right to Make Only' },
      { value: 'use', label: 'Right to Use Only' },
      { value: 'sell', label: 'Right to Sell Only' },
      { value: 'make-use', label: 'Right to Make and Use' },
      { value: 'make-sell', label: 'Right to Make and Sell' },
      { value: 'use-sell', label: 'Right to Use and Sell' },
      { value: 'make-use-sell', label: 'Right to Make, Use, and Sell' },
      { value: 'import', label: 'Right to Import' },
      { value: 'full-rights', label: 'All Patent Rights' },
    ],
    required: true,
    group: 'license-grant',
  },
  {
    id: 'hasFieldOfUse',
    type: 'checkbox',
    label: 'Limit to specific field of use',
    required: false,
    group: 'field-of-use',
  },
  {
    id: 'fieldOfUseDescription',
    type: 'textarea',
    label: 'Field of Use Description',
    placeholder: 'Describe the specific field or application',
    required: false,
    group: 'field-of-use',
    dependsOn: 'hasFieldOfUse',
  },
  {
    id: 'territoryScope',
    type: 'select',
    label: 'Territory Scope',
    options: [
      { value: 'worldwide', label: 'Worldwide' },
      { value: 'united-states', label: 'United States Only' },
      { value: 'specific-countries', label: 'Specific Countries' },
      { value: 'specific-regions', label: 'Specific Regions' },
    ],
    required: true,
    group: 'territory',
  },
  {
    id: 'specificTerritory',
    type: 'text',
    label: 'Specific Territory',
    placeholder: 'List specific countries or regions',
    required: false,
    group: 'territory',
    dependsOn: 'territoryScope',
  },
  {
    id: 'termType',
    type: 'select',
    label: 'License Term Type',
    options: [
      { value: 'life-of-patent', label: 'Life of Patent' },
      { value: 'fixed-term', label: 'Fixed Term' },
      { value: 'renewable', label: 'Renewable Term' },
      { value: 'at-will', label: 'At-Will' },
    ],
    required: true,
    group: 'term',
  },
  {
    id: 'termLength',
    type: 'text',
    label: 'Term Length',
    placeholder: 'e.g., 5 years',
    required: false,
    group: 'term',
    dependsOn: 'termType',
  },
  {
    id: 'hasRoyalties',
    type: 'checkbox',
    label: 'Include royalty payments',
    required: false,
    group: 'royalties',
  },
  {
    id: 'royaltyStructure',
    type: 'select',
    label: 'Royalty Structure',
    options: [
      { value: 'running-royalty', label: 'Running Royalty (% of sales)' },
      { value: 'lump-sum', label: 'Lump Sum Payment' },
      { value: 'milestone', label: 'Milestone Payments' },
      { value: 'hybrid', label: 'Hybrid Structure' },
    ],
    required: false,
    group: 'royalties',
    dependsOn: 'hasRoyalties',
  },
  {
    id: 'royaltyRate',
    type: 'text',
    label: 'Royalty Rate',
    placeholder: 'e.g., 3% of net sales',
    required: false,
    group: 'royalties',
    dependsOn: 'hasRoyalties',
  },
  {
    id: 'minimumRoyalty',
    type: 'text',
    label: 'Minimum Royalty',
    placeholder: 'Minimum payment per period',
    required: false,
    group: 'royalties',
    dependsOn: 'hasRoyalties',
  },
  {
    id: 'upfrontPayment',
    type: 'text',
    label: 'Upfront Payment',
    placeholder: 'Initial license fee',
    required: false,
    group: 'royalties',
  },
  {
    id: 'hasMilestones',
    type: 'checkbox',
    label: 'Include milestone payments',
    required: false,
    group: 'milestones',
  },
  {
    id: 'paymentFrequency',
    type: 'select',
    label: 'Payment Frequency',
    options: [
      { value: 'monthly', label: 'Monthly' },
      { value: 'quarterly', label: 'Quarterly' },
      { value: 'annually', label: 'Annually' },
      { value: 'upon-sale', label: 'Upon Sale' },
    ],
    required: false,
    group: 'payment-terms',
    dependsOn: 'hasRoyalties',
  },
  {
    id: 'reportingRequirements',
    type: 'checkbox',
    label: 'Require sales/usage reporting',
    required: false,
    group: 'payment-terms',
  },
  {
    id: 'auditRights',
    type: 'checkbox',
    label: 'Include audit rights',
    required: false,
    group: 'payment-terms',
  },
  {
    id: 'prosecutionResponsibility',
    type: 'select',
    label: 'Patent Prosecution Responsibility',
    options: [
      { value: 'licensor', label: 'Licensor' },
      { value: 'licensee', label: 'Licensee' },
      { value: 'shared', label: 'Shared' },
    ],
    required: false,
    group: 'patent-management',
  },
  {
    id: 'maintenanceResponsibility',
    type: 'select',
    label: 'Patent Maintenance Responsibility',
    options: [
      { value: 'licensor', label: 'Licensor' },
      { value: 'licensee', label: 'Licensee' },
      { value: 'shared', label: 'Shared' },
    ],
    required: false,
    group: 'patent-management',
  },
  {
    id: 'improvementRights',
    type: 'select',
    label: 'Rights to Improvements',
    options: [
      { value: 'none', label: 'No Special Rights' },
      { value: 'licensor-owns', label: 'Licensor Owns Improvements' },
      { value: 'licensee-owns', label: 'Licensee Owns Improvements' },
      { value: 'shared', label: 'Shared Ownership' },
      { value: 'grant-back', label: 'Grant-back License' },
    ],
    required: false,
    group: 'improvements',
  },
  {
    id: 'includeKnowHow',
    type: 'checkbox',
    label: 'Include technical know-how',
    required: false,
    group: 'technology-transfer',
  },
  {
    id: 'technicalDocumentation',
    type: 'checkbox',
    label: 'Provide technical documentation',
    required: false,
    group: 'technology-transfer',
  },
  {
    id: 'trainingProvided',
    type: 'checkbox',
    label: 'Provide training',
    required: false,
    group: 'technology-transfer',
  },
  {
    id: 'minimumSalesRequirements',
    type: 'text',
    label: 'Minimum Sales Requirements',
    placeholder: 'e.g., $500,000 annually',
    required: false,
    group: 'performance',
  },
  {
    id: 'sublicensingAllowed',
    type: 'checkbox',
    label: 'Allow sublicensing',
    required: false,
    group: 'sublicensing',
  },
  {
    id: 'sublicenseApproval',
    type: 'checkbox',
    label: 'Require approval for sublicenses',
    required: false,
    group: 'sublicensing',
    dependsOn: 'sublicensingAllowed',
  },
  {
    id: 'enforcementRights',
    type: 'select',
    label: 'Patent Enforcement Rights',
    options: [
      { value: 'licensor-only', label: 'Licensor Only' },
      { value: 'licensee-only', label: 'Licensee Only' },
      { value: 'both', label: 'Both Parties' },
      { value: 'cooperation', label: 'Cooperation Required' },
    ],
    required: false,
    group: 'enforcement',
  },
  {
    id: 'infringementNotification',
    type: 'checkbox',
    label: 'Require infringement notification',
    required: false,
    group: 'enforcement',
  },
  {
    id: 'invalidityChallenge',
    type: 'select',
    label: 'Validity Challenge Rights',
    options: [
      { value: 'prohibited', label: 'Prohibited' },
      { value: 'allowed', label: 'Allowed' },
      { value: 'terminates-license', label: 'Terminates License' },
    ],
    required: false,
    group: 'validity',
  },
  {
    id: 'confidentialityRequirements',
    type: 'checkbox',
    label: 'Include confidentiality requirements',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'patentValidityWarranty',
    type: 'checkbox',
    label: 'Warrant patent validity',
    required: false,
    group: 'warranties',
  },
  {
    id: 'nonInfringementWarranty',
    type: 'checkbox',
    label: 'Warrant non-infringement',
    required: false,
    group: 'warranties',
  },
  {
    id: 'licenseeIndemnifies',
    type: 'checkbox',
    label: 'Licensee indemnifies licensor',
    required: false,
    group: 'indemnification',
  },
  {
    id: 'terminationForCause',
    type: 'checkbox',
    label: 'Include termination for cause',
    required: false,
    group: 'termination',
  },
  {
    id: 'terminationNotice',
    type: 'text',
    label: 'Termination Notice Period',
    placeholder: 'e.g., 60 days written notice',
    required: false,
    group: 'termination',
  },
  {
    id: 'exportControlCompliance',
    type: 'checkbox',
    label: 'Include export control compliance',
    required: false,
    group: 'export-control',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law (State)',
    placeholder: 'e.g., State of California',
    required: false,
    group: 'legal',
  },
  {
    id: 'recordWithPTO',
    type: 'checkbox',
    label: 'Record license with Patent Office',
    required: false,
    group: 'recordation',
  },
  {
    id: 'requireLicensorSignature',
    type: 'checkbox',
    label: 'Require licensor signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireLicenseeSignature',
    type: 'checkbox',
    label: 'Require licensee signature',
    required: false,
    group: 'signatures',
  },
];
