// src/lib/documents/us/pet-addendum/questions.ts
import type { FormQuestion } from '@/types/documents';

export const petAddendumQuestions: FormQuestion[] = [
  {
    id: 'originalLeaseDate',
    type: 'date',
    label: 'Original Lease Date',
    required: true,
    group: 'lease',
  },
  {
    id: 'propertyAddress',
    type: 'textarea',
    label: 'Property Address',
    placeholder: 'Enter the full property address',
    required: true,
    group: 'lease',
  },
  {
    id: 'landlordName',
    type: 'text',
    label: 'Landlord Name',
    placeholder: "Enter landlord's full name",
    required: true,
    group: 'parties',
  },
  {
    id: 'landlordAddress',
    type: 'textarea',
    label: 'Landlord Address',
    placeholder: "Enter landlord's address",
    required: true,
    group: 'parties',
  },
  {
    id: 'tenantName',
    type: 'text',
    label: 'Tenant Name',
    placeholder: "Enter tenant's full name",
    required: true,
    group: 'parties',
  },
  {
    id: 'petType',
    type: 'select',
    label: 'Pet Type',
    options: [
      { value: 'dog', label: 'Dog' },
      { value: 'cat', label: 'Cat' },
      { value: 'bird', label: 'Bird' },
      { value: 'fish', label: 'Fish' },
      { value: 'reptile', label: 'Reptile' },
      { value: 'small-mammal', label: 'Small Mammal' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'pet',
  },
  {
    id: 'petName',
    type: 'text',
    label: 'Pet Name',
    placeholder: "Enter pet's name",
    required: true,
    group: 'pet',
  },
  {
    id: 'petBreed',
    type: 'text',
    label: 'Pet Breed',
    placeholder: "Enter pet's breed",
    required: false,
    group: 'pet',
  },
  {
    id: 'petAge',
    type: 'number',
    label: 'Pet Age (years)',
    placeholder: '3',
    required: true,
    group: 'pet',
  },
  {
    id: 'petWeight',
    type: 'number',
    label: 'Pet Weight (lbs)',
    placeholder: '45',
    required: true,
    group: 'pet',
  },
  {
    id: 'petColor',
    type: 'text',
    label: 'Pet Color',
    placeholder: 'Brown and white',
    required: false,
    group: 'pet',
  },
  {
    id: 'petDescription',
    type: 'textarea',
    label: 'Pet Description',
    placeholder: 'Brief description of the pet',
    required: false,
    group: 'pet',
  },
  {
    id: 'vaccinationsCurrent',
    type: 'checkbox',
    label: 'Vaccinations Current',
    required: false,
    group: 'documentation',
  },
  {
    id: 'vaccinationExpiryDate',
    type: 'date',
    label: 'Vaccination Expiry Date',
    required: false,
    group: 'documentation',
    dependsOn: 'vaccinationsCurrent',
  },
  {
    id: 'spayedNeutered',
    type: 'checkbox',
    label: 'Spayed/Neutered',
    required: false,
    group: 'documentation',
  },
  {
    id: 'microchipped',
    type: 'checkbox',
    label: 'Microchipped',
    required: false,
    group: 'documentation',
  },
  {
    id: 'microchipNumber',
    type: 'text',
    label: 'Microchip Number',
    placeholder: 'Enter microchip number',
    required: false,
    group: 'documentation',
    dependsOn: 'microchipped',
  },
  {
    id: 'petDeposit',
    type: 'number',
    label: 'Pet Security Deposit ($)',
    placeholder: '300',
    required: true,
    group: 'financial',
  },
  {
    id: 'petRent',
    type: 'number',
    label: 'Monthly Pet Rent ($)',
    placeholder: '25',
    required: true,
    group: 'financial',
  },
  {
    id: 'maximumPets',
    type: 'number',
    label: 'Maximum Number of Pets',
    placeholder: '1',
    required: true,
    group: 'restrictions',
  },
  {
    id: 'petSizeLimit',
    type: 'number',
    label: 'Pet Size Limit (lbs)',
    placeholder: '50',
    required: false,
    group: 'restrictions',
  },
  {
    id: 'leashedInCommonAreas',
    type: 'checkbox',
    label: 'Pet Must Be Leashed in Common Areas',
    required: false,
    group: 'rules',
  },
  {
    id: 'wasteCleanupRequired',
    type: 'checkbox',
    label: 'Owner Responsible for Waste Cleanup',
    required: false,
    group: 'rules',
  },
  {
    id: 'petLiabilityInsurance',
    type: 'checkbox',
    label: 'Pet Liability Insurance Required',
    required: false,
    group: 'insurance',
  },
  {
    id: 'insuranceAmount',
    type: 'number',
    label: 'Insurance Coverage Amount ($)',
    placeholder: '100000',
    required: false,
    group: 'insurance',
    dependsOn: 'petLiabilityInsurance',
  },
  {
    id: 'addendumDate',
    type: 'date',
    label: 'Addendum Date',
    required: true,
    group: 'legal',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Effective Date',
    required: true,
    group: 'legal',
  },
  {
    id: 'additionalPetTerms',
    type: 'textarea',
    label: 'Additional Pet Terms',
    placeholder: 'Any additional pet-related terms or conditions',
    required: false,
    group: 'additional',
  },
];
