// src/lib/documents/us/hotel-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const hotelAgreementQuestions: FormQuestion[] = [
  {
    id: 'primaryPartyName',
    type: 'text',
    label: 'Primary Party Name',
    placeholder: 'Enter primary party name',
    required: true,
    group: 'parties',
  },
  {
    id: 'secondaryPartyName',
    type: 'text',
    label: 'Secondary Party Name',
    placeholder: 'Enter secondary party name',
    required: true,
    group: 'parties',
  },
  {
    id: 'hotelName',
    type: 'text',
    label: 'Hotel Name',
    placeholder: 'Enter hotel name',
    required: true,
    group: 'hotel',
  },
  {
    id: 'hotelAddress',
    type: 'text',
    label: 'Hotel Address',
    placeholder: 'Enter hotel address',
    required: false,
    group: 'hotel',
  },
  {
    id: 'hotelType',
    type: 'select',
    label: 'Hotel Type',
    options: [
      { value: 'budget', label: 'Budget Hotel' },
      { value: 'mid-range', label: 'Mid-Range Hotel' },
      { value: 'luxury', label: 'Luxury Hotel' },
      { value: 'boutique', label: 'Boutique Hotel' },
      { value: 'resort', label: 'Resort' },
      { value: 'extended-stay', label: 'Extended Stay' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
    group: 'hotel',
  },
  {
    id: 'numberOfRooms',
    type: 'text',
    label: 'Number of Rooms',
    placeholder: 'Enter total number of rooms',
    required: false,
    group: 'hotel',
  },
  {
    id: 'starRating',
    type: 'select',
    label: 'Star Rating',
    options: [
      { value: '1', label: '1 Star' },
      { value: '2', label: '2 Stars' },
      { value: '3', label: '3 Stars' },
      { value: '4', label: '4 Stars' },
      { value: '5', label: '5 Stars' },
    ],
    required: false,
    group: 'hotel',
  },
  {
    id: 'totalInvestment',
    type: 'text',
    label: 'Total Investment',
    placeholder: 'Enter total investment amount',
    required: false,
    group: 'financial',
  },
  {
    id: 'ownershipPercentage',
    type: 'text',
    label: 'Ownership Percentage',
    placeholder: 'Enter ownership split (e.g., 60/40)',
    required: false,
    group: 'financial',
  },
  {
    id: 'averageDailyRate',
    type: 'text',
    label: 'Average Daily Rate',
    placeholder: 'Enter average room rate',
    required: false,
    group: 'rates',
  },
  {
    id: 'seasonalRates',
    type: 'boolean',
    label: 'Seasonal rate variations?',
    required: false,
    group: 'rates',
  },
  {
    id: 'operationsManagement',
    type: 'select',
    label: 'Operations Management',
    options: [
      { value: 'joint', label: 'Joint Management' },
      { value: 'primary-party', label: 'Primary Party' },
      { value: 'secondary-party', label: 'Secondary Party' },
      { value: 'hired-manager', label: 'Hired Manager' },
    ],
    required: false,
    group: 'management',
  },
  {
    id: 'frontDeskStaff',
    type: 'text',
    label: 'Front Desk Staff',
    placeholder: 'Enter number of front desk staff',
    required: false,
    group: 'staffing',
  },
  {
    id: 'housekeepingStaff',
    type: 'text',
    label: 'Housekeeping Staff',
    placeholder: 'Enter number of housekeeping staff',
    required: false,
    group: 'staffing',
  },
  {
    id: 'securityStaff',
    type: 'boolean',
    label: 'Security staff required?',
    required: false,
    group: 'staffing',
  },
  {
    id: 'wifiIncluded',
    type: 'boolean',
    label: 'WiFi included?',
    required: false,
    group: 'amenities',
  },
  {
    id: 'parkingAvailable',
    type: 'boolean',
    label: 'Parking available?',
    required: false,
    group: 'amenities',
  },
  {
    id: 'fitnessCenter',
    type: 'boolean',
    label: 'Fitness center?',
    required: false,
    group: 'amenities',
  },
  {
    id: 'swimmingPool',
    type: 'boolean',
    label: 'Swimming pool?',
    required: false,
    group: 'amenities',
  },
  {
    id: 'restaurant',
    type: 'boolean',
    label: 'Restaurant on-site?',
    required: false,
    group: 'amenities',
  },
  {
    id: 'checkinTime',
    type: 'text',
    label: 'Check-in Time',
    placeholder: 'Enter check-in time (e.g., 3:00 PM)',
    required: false,
    group: 'policies',
  },
  {
    id: 'checkoutTime',
    type: 'text',
    label: 'Check-out Time',
    placeholder: 'Enter check-out time (e.g., 11:00 AM)',
    required: false,
    group: 'policies',
  },
  {
    id: 'cancellationPolicy',
    type: 'select',
    label: 'Cancellation Policy',
    options: [
      { value: 'flexible', label: 'Flexible' },
      { value: 'moderate', label: 'Moderate' },
      { value: 'strict', label: 'Strict' },
      { value: 'super-strict', label: 'Super Strict' },
    ],
    required: false,
    group: 'policies',
  },
  {
    id: 'petPolicy',
    type: 'select',
    label: 'Pet Policy',
    options: [
      { value: 'no-pets', label: 'No Pets' },
      { value: 'pets-allowed', label: 'Pets Allowed' },
      { value: 'pets-with-fee', label: 'Pets with Fee' },
    ],
    required: false,
    group: 'policies',
  },
  {
    id: 'smokingPolicy',
    type: 'select',
    label: 'Smoking Policy',
    options: [
      { value: 'no-smoking', label: 'No Smoking' },
      { value: 'smoking-rooms-available', label: 'Smoking Rooms Available' },
      { value: 'designated-areas', label: 'Designated Smoking Areas' },
    ],
    required: false,
    group: 'policies',
  },
  {
    id: 'propertyManagementSystem',
    type: 'boolean',
    label: 'Property management system?',
    required: false,
    group: 'technology',
  },
  {
    id: 'onlineBookingSystem',
    type: 'boolean',
    label: 'Online booking system?',
    required: false,
    group: 'technology',
  },
  {
    id: 'marketingStrategy',
    type: 'textarea',
    label: 'Marketing Strategy',
    placeholder: 'Describe marketing and promotion strategy',
    required: false,
    group: 'marketing',
  },
  {
    id: 'corporateContracts',
    type: 'boolean',
    label: 'Corporate contracts?',
    required: false,
    group: 'marketing',
  },
  {
    id: 'meetingRooms',
    type: 'boolean',
    label: 'Meeting rooms available?',
    required: false,
    group: 'events',
  },
  {
    id: 'banquetFacilities',
    type: 'boolean',
    label: 'Banquet facilities?',
    required: false,
    group: 'events',
  },
  {
    id: 'sustainabilityPractices',
    type: 'boolean',
    label: 'Sustainability practices?',
    required: false,
    group: 'environment',
  },
  {
    id: 'agreementTerm',
    type: 'text',
    label: 'Agreement Term',
    placeholder: 'Enter agreement duration (e.g., 5 years)',
    required: false,
    group: 'term',
  },
  {
    id: 'renewalOptions',
    type: 'boolean',
    label: 'Include renewal options?',
    required: false,
    group: 'term',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'Enter governing law/state',
    required: false,
    group: 'legal',
  },
];