// src/lib/documents/us/certificate-substantial-completion/questions.ts
import type { FormQuestion } from '@/types/documents';

export const certificatesubstantialcompletionQuestions: FormQuestion[] = [
  {
    id: 'certificateNumber',
    type: 'text',
    label: 'Certificate Number',
    placeholder: 'Certificate reference number',
    required: false,
    group: 'certificate',
  },
  {
    id: 'certificateDate',
    type: 'date',
    label: 'Certificate Date',
    required: true,
    group: 'certificate',
  },
  {
    id: 'completionDate',
    type: 'date',
    label: 'Substantial Completion Date',
    required: true,
    group: 'certificate',
  },
  {
    id: 'projectName',
    type: 'text',
    label: 'Project Name',
    placeholder: 'Enter project name',
    required: true,
    group: 'project',
  },
  {
    id: 'projectAddress',
    type: 'text',
    label: 'Project Address',
    placeholder: 'Complete project address',
    required: true,
    group: 'project',
  },
  {
    id: 'projectDescription',
    type: 'textarea',
    label: 'Project Description',
    placeholder: 'Detailed description of construction project',
    required: true,
    group: 'project',
  },
  {
    id: 'projectType',
    type: 'select',
    label: 'Project Type',
    options: [
      { value: 'residential', label: 'Residential' },
      { value: 'commercial', label: 'Commercial' },
      { value: 'industrial', label: 'Industrial' },
      { value: 'public', label: 'Public' },
      { value: 'infrastructure', label: 'Infrastructure' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'project',
  },
  {
    id: 'ownerName',
    type: 'text',
    label: 'Owner Name',
    placeholder: 'Property owner name',
    required: true,
    group: 'owner',
  },
  {
    id: 'ownerAddress',
    type: 'text',
    label: 'Owner Address',
    placeholder: 'Complete owner address',
    required: true,
    group: 'owner',
  },
  {
    id: 'ownerPhone',
    type: 'text',
    label: 'Owner Phone',
    placeholder: 'Contact phone number',
    required: false,
    group: 'owner',
  },
  {
    id: 'ownerEmail',
    type: 'email',
    label: 'Owner Email',
    placeholder: 'Contact email address',
    required: false,
    group: 'owner',
  },
  {
    id: 'contractorName',
    type: 'text',
    label: 'Contractor Name',
    placeholder: 'General contractor name',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorAddress',
    type: 'text',
    label: 'Contractor Address',
    placeholder: 'Complete contractor address',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorPhone',
    type: 'text',
    label: 'Contractor Phone',
    placeholder: 'Contractor phone number',
    required: false,
    group: 'contractor',
  },
  {
    id: 'contractorLicense',
    type: 'text',
    label: 'Contractor License Number',
    placeholder: 'State license number',
    required: false,
    group: 'contractor',
  },
  {
    id: 'architectName',
    type: 'text',
    label: 'Architect Name',
    placeholder: 'Project architect name',
    required: false,
    group: 'architect',
  },
  {
    id: 'architectAddress',
    type: 'text',
    label: 'Architect Address',
    placeholder: 'Architect office address',
    required: false,
    group: 'architect',
  },
  {
    id: 'architectLicense',
    type: 'text',
    label: 'Architect License Number',
    placeholder: 'Professional license number',
    required: false,
    group: 'architect',
  },
  {
    id: 'contractDate',
    type: 'date',
    label: 'Original Contract Date',
    required: true,
    group: 'contract',
  },
  {
    id: 'contractAmount',
    type: 'text',
    label: 'Contract Amount',
    placeholder: 'Total contract amount',
    required: true,
    group: 'contract',
  },
  {
    id: 'originalCompletionDate',
    type: 'date',
    label: 'Original Completion Date',
    required: true,
    group: 'contract',
  },
  {
    id: 'workCompleted',
    type: 'textarea',
    label: 'Work Completed',
    placeholder: 'Description of substantially completed work',
    required: true,
    group: 'completion',
  },
  {
    id: 'completionPercentage',
    type: 'text',
    label: 'Completion Percentage',
    placeholder: 'e.g., 98%, 99%',
    required: false,
    group: 'completion',
  },
  {
    id: 'remainingWork',
    type: 'textarea',
    label: 'Remaining Work',
    placeholder: 'Description of work still to be completed',
    required: false,
    group: 'completion',
  },
  {
    id: 'inspectionDate',
    type: 'date',
    label: 'Inspection Date',
    required: false,
    group: 'inspection',
  },
  {
    id: 'inspectedBy',
    type: 'text',
    label: 'Inspected By',
    placeholder: 'Inspector name',
    required: false,
    group: 'inspection',
  },
  {
    id: 'inspectorTitle',
    type: 'text',
    label: 'Inspector Title',
    placeholder: 'Inspector title or position',
    required: false,
    group: 'inspection',
  },
  {
    id: 'inspectionResults',
    type: 'textarea',
    label: 'Inspection Results',
    placeholder: 'Summary of inspection findings',
    required: false,
    group: 'inspection',
  },
  {
    id: 'buildingCodeCompliance',
    type: 'checkbox',
    label: 'Building code compliance verified',
    required: false,
    group: 'compliance',
  },
  {
    id: 'permitCompliance',
    type: 'checkbox',
    label: 'Permit compliance verified',
    required: false,
    group: 'compliance',
  },
  {
    id: 'zoningCompliance',
    type: 'checkbox',
    label: 'Zoning compliance verified',
    required: false,
    group: 'compliance',
  },
  {
    id: 'accessibilityCompliance',
    type: 'checkbox',
    label: 'Accessibility compliance verified',
    required: false,
    group: 'compliance',
  },
  {
    id: 'certificateOfOccupancy',
    type: 'checkbox',
    label: 'Certificate of occupancy obtained',
    required: false,
    group: 'occupancy',
  },
  {
    id: 'occupancyDate',
    type: 'date',
    label: 'Occupancy Date',
    required: false,
    group: 'occupancy',
    dependsOn: 'certificateOfOccupancy',
  },
  {
    id: 'occupancyType',
    type: 'select',
    label: 'Occupancy Type',
    options: [
      { value: 'temporary', label: 'Temporary' },
      { value: 'partial', label: 'Partial' },
      { value: 'full', label: 'Full' },
    ],
    required: false,
    group: 'occupancy',
    dependsOn: 'certificateOfOccupancy',
  },
  {
    id: 'utilitiesConnected',
    type: 'checkbox',
    label: 'Utilities Connected',
    options: [
      { value: 'electrical', label: 'Electrical' },
      { value: 'plumbing', label: 'Plumbing' },
      { value: 'hvac', label: 'HVAC' },
      { value: 'gas', label: 'Gas' },
      { value: 'water', label: 'Water' },
      { value: 'sewer', label: 'Sewer' },
      { value: 'telecommunications', label: 'Telecommunications' },
      { value: 'fire-suppression', label: 'Fire Suppression' },
      { value: 'security', label: 'Security System' },
    ],
    required: false,
    group: 'utilities',
  },
  {
    id: 'systemsOperational',
    type: 'checkbox',
    label: 'All systems tested and operational',
    required: false,
    group: 'utilities',
  },
  {
    id: 'safetyInspections',
    type: 'checkbox',
    label: 'Safety inspections completed',
    required: false,
    group: 'safety',
  },
  {
    id: 'environmentalCompliance',
    type: 'checkbox',
    label: 'Environmental compliance verified',
    required: false,
    group: 'safety',
  },
  {
    id: 'hazardousMaterialsRemoval',
    type: 'checkbox',
    label: 'Hazardous materials removal completed',
    required: false,
    group: 'safety',
  },
  {
    id: 'qualityControlInspections',
    type: 'checkbox',
    label: 'Quality control inspections completed',
    required: false,
    group: 'quality',
  },
  {
    id: 'materialTesting',
    type: 'checkbox',
    label: 'Material testing completed',
    required: false,
    group: 'quality',
  },
  {
    id: 'structuralInspections',
    type: 'checkbox',
    label: 'Structural inspections completed',
    required: false,
    group: 'quality',
  },
  {
    id: 'warrantyPeriod',
    type: 'text',
    label: 'Warranty Period',
    placeholder: 'e.g., 1 year, 2 years',
    required: false,
    group: 'warranty',
  },
  {
    id: 'warrantyStartDate',
    type: 'date',
    label: 'Warranty Start Date',
    required: false,
    group: 'warranty',
  },
  {
    id: 'materialWarranties',
    type: 'checkbox',
    label: 'Material warranties provided',
    required: false,
    group: 'warranty',
  },
  {
    id: 'equipmentWarranties',
    type: 'checkbox',
    label: 'Equipment warranties provided',
    required: false,
    group: 'warranty',
  },
  {
    id: 'workmanshipWarranty',
    type: 'checkbox',
    label: 'Workmanship warranty provided',
    required: false,
    group: 'warranty',
  },
  {
    id: 'asBuiltDrawings',
    type: 'checkbox',
    label: 'As-built drawings provided',
    required: false,
    group: 'documentation',
  },
  {
    id: 'operationManuals',
    type: 'checkbox',
    label: 'Operation manuals provided',
    required: false,
    group: 'documentation',
  },
  {
    id: 'maintenanceManuals',
    type: 'checkbox',
    label: 'Maintenance manuals provided',
    required: false,
    group: 'documentation',
  },
  {
    id: 'warrantyDocuments',
    type: 'checkbox',
    label: 'Warranty documents provided',
    required: false,
    group: 'documentation',
  },
  {
    id: 'ownerTraining',
    type: 'checkbox',
    label: 'Owner training provided',
    required: false,
    group: 'training',
  },
  {
    id: 'trainingDate',
    type: 'date',
    label: 'Training Date',
    required: false,
    group: 'training',
    dependsOn: 'ownerTraining',
  },
  {
    id: 'keyHandover',
    type: 'checkbox',
    label: 'Keys handed over to owner',
    required: false,
    group: 'training',
  },
  {
    id: 'retainageAmount',
    type: 'text',
    label: 'Retainage Amount',
    placeholder: 'Amount of retainage held',
    required: false,
    group: 'financial',
  },
  {
    id: 'retainageReleaseConditions',
    type: 'textarea',
    label: 'Retainage Release Conditions',
    placeholder: 'Conditions for releasing retainage',
    required: false,
    group: 'financial',
  },
  {
    id: 'changOrdersCompleted',
    type: 'checkbox',
    label: 'All change orders completed',
    required: false,
    group: 'financial',
  },
  {
    id: 'lienWaiversReceived',
    type: 'checkbox',
    label: 'Lien waivers received',
    required: false,
    group: 'liens',
  },
  {
    id: 'subcontractorLienWaivers',
    type: 'checkbox',
    label: 'Subcontractor lien waivers received',
    required: false,
    group: 'liens',
  },
  {
    id: 'supplierLienWaivers',
    type: 'checkbox',
    label: 'Supplier lien waivers received',
    required: false,
    group: 'liens',
  },
  {
    id: 'openDisputes',
    type: 'checkbox',
    label: 'Open disputes exist',
    required: false,
    group: 'disputes',
  },
  {
    id: 'disputeDescription',
    type: 'textarea',
    label: 'Dispute Description',
    placeholder: 'Description of any open disputes',
    required: false,
    group: 'disputes',
    dependsOn: 'openDisputes',
  },
  {
    id: 'maintenancePeriod',
    type: 'text',
    label: 'Maintenance Period',
    placeholder: 'e.g., 1 year from substantial completion',
    required: false,
    group: 'maintenance',
  },
  {
    id: 'maintenanceResponsibilities',
    type: 'textarea',
    label: 'Maintenance Responsibilities',
    placeholder: 'Description of maintenance responsibilities',
    required: false,
    group: 'maintenance',
  },
  {
    id: 'additionalRequirements',
    type: 'textarea',
    label: 'Additional Requirements',
    placeholder: 'Any additional requirements or conditions',
    required: false,
    group: 'conditions',
  },
  {
    id: 'ownerApproval',
    type: 'checkbox',
    label: 'Owner approval obtained',
    required: false,
    group: 'approvals',
  },
  {
    id: 'contractorCertification',
    type: 'checkbox',
    label: 'Contractor certification provided',
    required: false,
    group: 'approvals',
  },
  {
    id: 'architectApproval',
    type: 'checkbox',
    label: 'Architect approval obtained',
    required: false,
    group: 'approvals',
  },
  {
    id: 'complianceStatement',
    type: 'checkbox',
    label: 'Include compliance statement',
    required: false,
    group: 'certification',
  },
  {
    id: 'ownerSignature',
    type: 'checkbox',
    label: 'Require owner signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'contractorSignature',
    type: 'checkbox',
    label: 'Require contractor signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'architectSignature',
    type: 'checkbox',
    label: 'Require architect signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireNotarization',
    type: 'checkbox',
    label: 'Require notarization',
    required: false,
    group: 'notary',
  },
];
