// src/lib/documents/us/website-development-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const websiteDevelopmentAgreementQuestions: FormQuestion[] = [
  {
    id: 'developerName',
    type: 'text',
    label: 'Developer Name',
    placeholder: 'Enter developer or company name',
    required: true,
    group: 'developer',
  },
  {
    id: 'developerBusinessName',
    type: 'text',
    label: 'Developer Business Name',
    placeholder: 'Enter business name if different',
    required: false,
    group: 'developer',
  },
  {
    id: 'developerAddress',
    type: 'text',
    label: 'Developer Address',
    placeholder: 'Enter complete business address',
    required: true,
    group: 'developer',
  },
  {
    id: 'developerPhone',
    type: 'text',
    label: 'Developer Phone',
    placeholder: 'Enter phone number',
    required: false,
    group: 'developer',
  },
  {
    id: 'developerEmail',
    type: 'email',
    label: 'Developer Email',
    placeholder: 'Enter email address',
    required: false,
    group: 'developer',
  },
  {
    id: 'developerWebsite',
    type: 'text',
    label: 'Developer Website',
    placeholder: 'Enter website URL',
    required: false,
    group: 'developer',
  },
  {
    id: 'clientName',
    type: 'text',
    label: 'Client Name',
    placeholder: 'Enter client name',
    required: true,
    group: 'client',
  },
  {
    id: 'clientBusinessName',
    type: 'text',
    label: 'Client Business Name',
    placeholder: 'Enter business name',
    required: false,
    group: 'client',
  },
  {
    id: 'clientAddress',
    type: 'text',
    label: 'Client Address',
    placeholder: 'Enter complete address',
    required: true,
    group: 'client',
  },
  {
    id: 'clientPhone',
    type: 'text',
    label: 'Client Phone',
    placeholder: 'Enter phone number',
    required: false,
    group: 'client',
  },
  {
    id: 'clientEmail',
    type: 'email',
    label: 'Client Email',
    placeholder: 'Enter email address',
    required: false,
    group: 'client',
  },
  {
    id: 'clientWebsite',
    type: 'text',
    label: 'Current Website',
    placeholder: 'Enter current website URL if any',
    required: false,
    group: 'client',
  },
  {
    id: 'projectName',
    type: 'text',
    label: 'Project Name',
    placeholder: 'Enter project or website name',
    required: true,
    group: 'project',
  },
  {
    id: 'websitePurpose',
    type: 'textarea',
    label: 'Website Purpose',
    placeholder: 'Describe the purpose and goals of the website',
    required: true,
    group: 'project',
  },
  {
    id: 'targetAudience',
    type: 'text',
    label: 'Target Audience',
    placeholder: 'Describe the target audience',
    required: false,
    group: 'project',
  },
  {
    id: 'projectDescription',
    type: 'textarea',
    label: 'Project Description',
    placeholder: 'Detailed description of the project requirements',
    required: true,
    group: 'project',
  },
  {
    id: 'websiteType',
    type: 'select',
    label: 'Website Type',
    options: [
      { value: 'informational', label: 'Informational/Business' },
      { value: 'e-commerce', label: 'E-commerce' },
      { value: 'portfolio', label: 'Portfolio' },
      { value: 'blog', label: 'Blog' },
      { value: 'application', label: 'Web Application' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'project',
  },
  {
    id: 'serviceType',
    type: 'select',
    label: 'Service Type',
    options: [
      { value: 'design-only', label: 'Design Only' },
      { value: 'development-only', label: 'Development Only' },
      { value: 'full-service', label: 'Design & Development' },
      { value: 'maintenance', label: 'Maintenance Only' },
    ],
    required: true,
    group: 'scope',
  },
  {
    id: 'includedServices',
    type: 'multiselect',
    label: 'Included Services',
    options: [
      { value: 'website-design', label: 'Website Design' },
      { value: 'frontend-development', label: 'Frontend Development' },
      { value: 'backend-development', label: 'Backend Development' },
      { value: 'cms-integration', label: 'CMS Integration' },
      { value: 'e-commerce-setup', label: 'E-commerce Setup' },
      { value: 'seo-optimization', label: 'SEO Optimization' },
      { value: 'responsive-design', label: 'Responsive Design' },
      { value: 'hosting-setup', label: 'Hosting Setup' },
    ],
    required: false,
    group: 'scope',
  },
  {
    id: 'excludedServices',
    type: 'multiselect',
    label: 'Excluded Services',
    options: [
      { value: 'content-creation', label: 'Content Creation' },
      { value: 'ongoing-maintenance', label: 'Ongoing Maintenance' },
      { value: 'domain-registration', label: 'Domain Registration' },
      { value: 'hosting-fees', label: 'Hosting Fees' },
      { value: 'third-party-licenses', label: 'Third-party Licenses' },
      { value: 'training', label: 'Training' },
    ],
    required: false,
    group: 'scope',
  },
  {
    id: 'numberOfPages',
    type: 'text',
    label: 'Number of Pages',
    placeholder: 'Estimated number of pages',
    required: false,
    group: 'scope',
  },
  {
    id: 'customFunctionality',
    type: 'textarea',
    label: 'Custom Functionality',
    placeholder: 'Describe any custom features or functionality needed',
    required: false,
    group: 'scope',
  },
  {
    id: 'thirdPartyIntegrations',
    type: 'text',
    label: 'Third-party Integrations',
    placeholder: 'List any third-party services to integrate',
    required: false,
    group: 'scope',
  },
  {
    id: 'websiteDesign',
    type: 'checkbox',
    label: 'Include website design',
    required: false,
    group: 'design-services',
  },
  {
    id: 'uiUxDesign',
    type: 'checkbox',
    label: 'Include UI/UX design',
    required: false,
    group: 'design-services',
  },
  {
    id: 'responsiveDesign',
    type: 'checkbox',
    label: 'Include responsive design',
    required: false,
    group: 'design-services',
  },
  {
    id: 'mobileOptimization',
    type: 'checkbox',
    label: 'Include mobile optimization',
    required: false,
    group: 'design-services',
  },
  {
    id: 'logoDesign',
    type: 'checkbox',
    label: 'Include logo design',
    required: false,
    group: 'design-services',
  },
  {
    id: 'brandingServices',
    type: 'checkbox',
    label: 'Include branding services',
    required: false,
    group: 'design-services',
  },
  {
    id: 'customGraphics',
    type: 'checkbox',
    label: 'Include custom graphics',
    required: false,
    group: 'design-services',
  },
  {
    id: 'frontEndDevelopment',
    type: 'checkbox',
    label: 'Include frontend development',
    required: false,
    group: 'development-services',
  },
  {
    id: 'backEndDevelopment',
    type: 'checkbox',
    label: 'Include backend development',
    required: false,
    group: 'development-services',
  },
  {
    id: 'databaseDesign',
    type: 'checkbox',
    label: 'Include database design',
    required: false,
    group: 'development-services',
  },
  {
    id: 'cmsIntegration',
    type: 'checkbox',
    label: 'Include CMS integration',
    required: false,
    group: 'development-services',
  },
  {
    id: 'eCommerceIntegration',
    type: 'checkbox',
    label: 'Include e-commerce integration',
    required: false,
    group: 'development-services',
  },
  {
    id: 'apiIntegration',
    type: 'checkbox',
    label: 'Include API integration',
    required: false,
    group: 'development-services',
  },
  {
    id: 'customProgramming',
    type: 'checkbox',
    label: 'Include custom programming',
    required: false,
    group: 'development-services',
  },
  {
    id: 'programmingLanguages',
    type: 'text',
    label: 'Programming Languages',
    placeholder: 'e.g., HTML, CSS, JavaScript, PHP',
    required: false,
    group: 'technical',
  },
  {
    id: 'frameworks',
    type: 'text',
    label: 'Frameworks',
    placeholder: 'e.g., React, Angular, Laravel',
    required: false,
    group: 'technical',
  },
  {
    id: 'contentManagementSystem',
    type: 'text',
    label: 'Content Management System',
    placeholder: 'e.g., WordPress, Drupal, Custom CMS',
    required: false,
    group: 'technical',
  },
  {
    id: 'hostingRequirements',
    type: 'text',
    label: 'Hosting Requirements',
    placeholder: 'Describe hosting requirements',
    required: false,
    group: 'technical',
  },
  {
    id: 'browserCompatibility',
    type: 'text',
    label: 'Browser Compatibility',
    placeholder: 'Required browser support',
    required: false,
    group: 'technical',
  },
  {
    id: 'performanceRequirements',
    type: 'text',
    label: 'Performance Requirements',
    placeholder: 'Page load speed, performance metrics',
    required: false,
    group: 'technical',
  },
  {
    id: 'projectStartDate',
    type: 'date',
    label: 'Project Start Date',
    required: false,
    group: 'timeline',
  },
  {
    id: 'projectEndDate',
    type: 'date',
    label: 'Project End Date',
    required: false,
    group: 'timeline',
  },
  {
    id: 'totalProjectDuration',
    type: 'text',
    label: 'Total Project Duration',
    placeholder: 'e.g., 8 weeks, 3 months',
    required: false,
    group: 'timeline',
  },
  {
    id: 'milestones',
    type: 'multiselect',
    label: 'Project Milestones',
    options: [
      { value: 'design-approval', label: 'Design Approval' },
      { value: 'development-completion', label: 'Development Completion' },
      { value: 'content-integration', label: 'Content Integration' },
      { value: 'testing-completion', label: 'Testing Completion' },
      { value: 'client-approval', label: 'Client Approval' },
      { value: 'go-live', label: 'Go Live' },
    ],
    required: false,
    group: 'timeline',
  },
  {
    id: 'launchDate',
    type: 'date',
    label: 'Target Launch Date',
    required: false,
    group: 'timeline',
  },
  {
    id: 'contentProvision',
    type: 'checkbox',
    label: 'Client provides content',
    required: false,
    group: 'client-responsibilities',
  },
  {
    id: 'timelyApprovals',
    type: 'checkbox',
    label: 'Client provides timely approvals',
    required: false,
    group: 'client-responsibilities',
  },
  {
    id: 'feedbackProvision',
    type: 'checkbox',
    label: 'Client provides feedback',
    required: false,
    group: 'client-responsibilities',
  },
  {
    id: 'assetProvision',
    type: 'checkbox',
    label: 'Client provides assets (images, logos, etc.)',
    required: false,
    group: 'client-responsibilities',
  },
  {
    id: 'testingParticipation',
    type: 'checkbox',
    label: 'Client participates in testing',
    required: false,
    group: 'client-responsibilities',
  },
  {
    id: 'hostingArrangement',
    type: 'checkbox',
    label: 'Client arranges hosting',
    required: false,
    group: 'client-responsibilities',
  },
  {
    id: 'clientProvidedContent',
    type: 'checkbox',
    label: 'Client provides all content',
    required: false,
    group: 'content',
  },
  {
    id: 'contentCreationServices',
    type: 'checkbox',
    label: 'Include content creation services',
    required: false,
    group: 'content',
  },
  {
    id: 'stockPhotos',
    type: 'checkbox',
    label: 'Include stock photos',
    required: false,
    group: 'content',
  },
  {
    id: 'customPhotography',
    type: 'checkbox',
    label: 'Include custom photography',
    required: false,
    group: 'content',
  },
  {
    id: 'copywriting',
    type: 'checkbox',
    label: 'Include copywriting services',
    required: false,
    group: 'content',
  },
  {
    id: 'seoContent',
    type: 'checkbox',
    label: 'Include SEO content optimization',
    required: false,
    group: 'content',
  },
  {
    id: 'pricingModel',
    type: 'select',
    label: 'Pricing Model',
    options: [
      { value: 'fixed-price', label: 'Fixed Price' },
      { value: 'hourly', label: 'Hourly Rate' },
      { value: 'milestone-based', label: 'Milestone Based' },
      { value: 'retainer', label: 'Monthly Retainer' },
    ],
    required: true,
    group: 'pricing',
  },
  {
    id: 'totalProjectCost',
    type: 'text',
    label: 'Total Project Cost',
    placeholder: 'Enter total project cost',
    required: false,
    group: 'pricing',
  },
  {
    id: 'hourlyRate',
    type: 'text',
    label: 'Hourly Rate',
    placeholder: 'Enter hourly rate',
    required: false,
    group: 'pricing',
    dependsOn: 'pricingModel',
  },
  {
    id: 'depositAmount',
    type: 'text',
    label: 'Deposit Amount',
    placeholder: 'Enter deposit amount or percentage',
    required: false,
    group: 'pricing',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'upfront', label: 'Full Payment Upfront' },
      { value: 'milestone-based', label: 'Milestone Based Payments' },
      { value: 'net-30', label: 'Net 30 Days' },
      { value: 'split-payments', label: 'Split Payments' },
    ],
    required: true,
    group: 'payment',
  },
  {
    id: 'depositRequired',
    type: 'checkbox',
    label: 'Require deposit before starting',
    required: false,
    group: 'payment',
  },
  {
    id: 'depositPercentage',
    type: 'text',
    label: 'Deposit Percentage',
    placeholder: 'e.g., 50%',
    required: false,
    group: 'payment',
    dependsOn: 'depositRequired',
  },
  {
    id: 'finalPaymentDue',
    type: 'select',
    label: 'Final Payment Due',
    options: [
      { value: 'upon-completion', label: 'Upon Completion' },
      { value: 'upon-launch', label: 'Upon Launch' },
      { value: 'net-30', label: 'Net 30 Days' },
    ],
    required: true,
    group: 'payment',
  },
  {
    id: 'latePaymentFees',
    type: 'checkbox',
    label: 'Include late payment fees',
    required: false,
    group: 'payment',
  },
  {
    id: 'includedRevisions',
    type: 'text',
    label: 'Included Revisions',
    placeholder: 'Number of revisions included',
    required: false,
    group: 'revisions',
  },
  {
    id: 'additionalRevisionCost',
    type: 'text',
    label: 'Additional Revision Cost',
    placeholder: 'Cost for additional revisions',
    required: false,
    group: 'revisions',
  },
  {
    id: 'changeOrderRequirement',
    type: 'checkbox',
    label: 'Require change orders for scope changes',
    required: false,
    group: 'revisions',
  },
  {
    id: 'scopeChangeApproval',
    type: 'checkbox',
    label: 'Require approval for scope changes',
    required: false,
    group: 'revisions',
  },
  {
    id: 'userAcceptanceTesting',
    type: 'checkbox',
    label: 'Include user acceptance testing',
    required: false,
    group: 'testing',
  },
  {
    id: 'performanceTesting',
    type: 'checkbox',
    label: 'Include performance testing',
    required: false,
    group: 'testing',
  },
  {
    id: 'securityTesting',
    type: 'checkbox',
    label: 'Include security testing',
    required: false,
    group: 'testing',
  },
  {
    id: 'crossBrowserTesting',
    type: 'checkbox',
    label: 'Include cross-browser testing',
    required: false,
    group: 'testing',
  },
  {
    id: 'mobileTesting',
    type: 'checkbox',
    label: 'Include mobile testing',
    required: false,
    group: 'testing',
  },
  {
    id: 'testingPeriod',
    type: 'text',
    label: 'Testing Period',
    placeholder: 'Duration of testing phase',
    required: false,
    group: 'testing',
  },
  {
    id: 'hostingSetup',
    type: 'checkbox',
    label: 'Include hosting setup',
    required: false,
    group: 'launch',
  },
  {
    id: 'domainSetup',
    type: 'checkbox',
    label: 'Include domain setup',
    required: false,
    group: 'launch',
  },
  {
    id: 'sslCertificate',
    type: 'checkbox',
    label: 'Include SSL certificate setup',
    required: false,
    group: 'launch',
  },
  {
    id: 'goLiveSupport',
    type: 'checkbox',
    label: 'Include go-live support',
    required: false,
    group: 'launch',
  },
  {
    id: 'postLaunchTesting',
    type: 'checkbox',
    label: 'Include post-launch testing',
    required: false,
    group: 'launch',
  },
  {
    id: 'clientTraining',
    type: 'checkbox',
    label: 'Include client training',
    required: false,
    group: 'training',
  },
  {
    id: 'userManual',
    type: 'checkbox',
    label: 'Provide user manual',
    required: false,
    group: 'training',
  },
  {
    id: 'technicalDocumentation',
    type: 'checkbox',
    label: 'Provide technical documentation',
    required: false,
    group: 'training',
  },
  {
    id: 'videoTutorials',
    type: 'checkbox',
    label: 'Provide video tutorials',
    required: false,
    group: 'training',
  },
  {
    id: 'warrantyPeriod',
    type: 'text',
    label: 'Warranty Period',
    placeholder: 'e.g., 30 days, 3 months',
    required: false,
    group: 'support',
  },
  {
    id: 'bugFixWarranty',
    type: 'checkbox',
    label: 'Include bug fix warranty',
    required: false,
    group: 'support',
  },
  {
    id: 'ongoingMaintenance',
    type: 'checkbox',
    label: 'Include ongoing maintenance',
    required: false,
    group: 'support',
  },
  {
    id: 'supportHours',
    type: 'text',
    label: 'Support Hours',
    placeholder: 'Hours of support included',
    required: false,
    group: 'support',
  },
  {
    id: 'emergencySupport',
    type: 'checkbox',
    label: 'Include emergency support',
    required: false,
    group: 'support',
  },
  {
    id: 'workForHire',
    type: 'checkbox',
    label: 'Work for hire agreement',
    required: false,
    group: 'intellectual-property',
  },
  {
    id: 'copyrightOwnership',
    type: 'select',
    label: 'Copyright Ownership',
    options: [
      { value: 'client', label: 'Client Owns All Rights' },
      { value: 'developer', label: 'Developer Retains Rights' },
      { value: 'shared', label: 'Shared Ownership' },
    ],
    required: true,
    group: 'intellectual-property',
  },
  {
    id: 'portfolioRights',
    type: 'checkbox',
    label: 'Developer may use in portfolio',
    required: false,
    group: 'intellectual-property',
  },
  {
    id: 'creditRequirement',
    type: 'checkbox',
    label: 'Require developer credit on website',
    required: false,
    group: 'intellectual-property',
  },
  {
    id: 'confidentialityClause',
    type: 'checkbox',
    label: 'Include confidentiality clause',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'ndaRequired',
    type: 'checkbox',
    label: 'Require separate NDA',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'proprietaryInformation',
    type: 'checkbox',
    label: 'Protect proprietary information',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'clientDataProtection',
    type: 'checkbox',
    label: 'Include client data protection',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'basicSEO',
    type: 'checkbox',
    label: 'Include basic SEO',
    required: false,
    group: 'seo-marketing',
  },
  {
    id: 'googleAnalytics',
    type: 'checkbox',
    label: 'Include Google Analytics setup',
    required: false,
    group: 'seo-marketing',
  },
  {
    id: 'socialMediaIntegration',
    type: 'checkbox',
    label: 'Include social media integration',
    required: false,
    group: 'seo-marketing',
  },
  {
    id: 'communicationMethod',
    type: 'select',
    label: 'Primary Communication Method',
    options: [
      { value: 'email', label: 'Email' },
      { value: 'phone', label: 'Phone' },
      { value: 'video-calls', label: 'Video Calls' },
      { value: 'project-management-tool', label: 'Project Management Tool' },
    ],
    required: true,
    group: 'communication',
  },
  {
    id: 'progressReporting',
    type: 'select',
    label: 'Progress Reporting Frequency',
    options: [
      { value: 'weekly', label: 'Weekly' },
      { value: 'bi-weekly', label: 'Bi-weekly' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'milestone-based', label: 'Milestone Based' },
    ],
    required: true,
    group: 'communication',
  },
  {
    id: 'terminationRights',
    type: 'checkbox',
    label: 'Include termination rights',
    required: false,
    group: 'termination',
  },
  {
    id: 'terminationNotice',
    type: 'text',
    label: 'Termination Notice',
    placeholder: 'Required notice for termination',
    required: false,
    group: 'termination',
  },
  {
    id: 'workCompletedPayment',
    type: 'checkbox',
    label: 'Payment due for completed work',
    required: false,
    group: 'termination',
  },
  {
    id: 'fileTransfer',
    type: 'checkbox',
    label: 'Transfer files upon termination',
    required: false,
    group: 'termination',
  },
  {
    id: 'liabilityLimitation',
    type: 'checkbox',
    label: 'Include liability limitation',
    required: false,
    group: 'legal',
  },
  {
    id: 'liabilityAmount',
    type: 'text',
    label: 'Liability Limitation Amount',
    placeholder: 'Maximum liability amount',
    required: false,
    group: 'legal',
    dependsOn: 'liabilityLimitation',
  },
  {
    id: 'warrantiesDisclaimer',
    type: 'checkbox',
    label: 'Include warranties disclaimer',
    required: false,
    group: 'legal',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'negotiation', label: 'Negotiation' },
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'litigation', label: 'Court Litigation' },
    ],
    required: false,
    group: 'legal',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'e.g., State of California',
    required: false,
    group: 'legal',
  },
  {
    id: 'jurisdiction',
    type: 'text',
    label: 'Jurisdiction',
    placeholder: 'Where disputes will be resolved',
    required: false,
    group: 'legal',
  },
  {
    id: 'requireDeveloperSignature',
    type: 'checkbox',
    label: 'Require developer signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireClientSignature',
    type: 'checkbox',
    label: 'Require client signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'witnessRequired',
    type: 'checkbox',
    label: 'Require witness',
    required: false,
    group: 'signatures',
  },
  {
    id: 'notarizationRequired',
    type: 'checkbox',
    label: 'Require notarization',
    required: false,
    group: 'signatures',
  },
  {
    id: 'electronicSignatureAccepted',
    type: 'checkbox',
    label: 'Accept electronic signatures',
    required: false,
    group: 'signatures',
  },
];