import type { Question } from '@/types/documents';

export const statementOfAccountQuestions: Question[] = [
  {
    id: 'statementDate',
    label: 'Statement Date',
    type: 'date',
    required: true,
  },
  {
    id: 'statementPeriodStart',
    label: 'Statement Period Start',
    type: 'date',
    required: true,
  },
  {
    id: 'statementPeriodEnd',
    label: 'Statement Period End',
    type: 'date',
    required: true,
  },
  {
    id: 'accountHolderName',
    label: 'Account Holder Name',
    type: 'text',
    required: true,
  },
  {
    id: 'accountHolderAddress',
    label: 'Account Holder Address',
    type: 'text',
    required: true,
    placeholder: 'Street, City, State, ZIP',
  },
  {
    id: 'accountNumber',
    label: 'Account Number',
    type: 'text',
    required: true,
    placeholder: 'Account identifier',
  },
  { id: 'companyName', label: 'Company Name', type: 'text', required: true },
  {
    id: 'companyAddress',
    label: 'Company Address',
    type: 'text',
    required: true,
    placeholder: 'Street, City, State, ZIP',
  },
  {
    id: 'previousBalance',
    label: 'Previous Balance',
    type: 'number',
    required: true,
    placeholder: 'Balance from previous statement',
  },
  {
    id: 'totalCharges',
    label: 'Total Charges',
    type: 'number',
    required: true,
    placeholder: 'New charges this period',
  },
  {
    id: 'totalPayments',
    label: 'Total Payments',
    type: 'number',
    required: true,
    placeholder: 'Payments received this period',
  },
  {
    id: 'totalCredits',
    label: 'Total Credits',
    type: 'number',
    required: true,
    placeholder: 'Credits applied this period',
  },
  {
    id: 'currentBalance',
    label: 'Current Balance',
    type: 'number',
    required: true,
    placeholder: 'Current account balance',
  },
  {
    id: 'minimumPaymentDue',
    label: 'Minimum Payment Due',
    type: 'number',
    required: true,
    placeholder: 'Minimum payment required',
  },
  {
    id: 'paymentDueDate',
    label: 'Payment Due Date',
    type: 'date',
    required: true,
  },
  {
    id: 'interestRate',
    label: 'Interest Rate (%)',
    type: 'number',
    required: false,
    placeholder: 'Annual interest rate',
  },
  {
    id: 'interestCharges',
    label: 'Interest Charges',
    type: 'number',
    required: false,
    placeholder: 'Interest charged this period',
  },
  {
    id: 'lateFees',
    label: 'Late Fees',
    type: 'number',
    required: false,
    placeholder: 'Late fees assessed',
  },
  {
    id: 'creditLimit',
    label: 'Credit Limit',
    type: 'number',
    required: false,
    placeholder: 'Total credit limit',
  },
  {
    id: 'availableCredit',
    label: 'Available Credit',
    type: 'number',
    required: false,
    placeholder: 'Remaining available credit',
  },
  {
    id: 'accountType',
    label: 'Account Type',
    type: 'select',
    required: true,
    options: [
      { value: 'Credit Account', label: 'Credit Account' },
      { value: 'Loan Account', label: 'Loan Account' },
      { value: 'Service Account', label: 'Service Account' },
      { value: 'Business Account', label: 'Business Account' },
    ],
  },
  {
    id: 'statementType',
    label: 'Statement Type',
    type: 'select',
    required: true,
    options: [
      { value: 'Monthly', label: 'Monthly' },
      { value: 'Quarterly', label: 'Quarterly' },
      { value: 'Annual', label: 'Annual' },
      { value: 'Final', label: 'Final Statement' },
    ],
  },
  {
    id: 'paymentInstructions',
    label: 'Payment Instructions',
    type: 'textarea',
    required: true,
    placeholder: 'How to make payments, where to send checks, etc...',
  },
  {
    id: 'contactInformation',
    label: 'Contact Information',
    type: 'text',
    required: true,
    placeholder: 'Phone, email, or address for questions',
  },
  {
    id: 'disputePeriod',
    label: 'Dispute Period (Days)',
    type: 'number',
    required: false,
    tooltip: 'Days customer has to dispute charges',
  },
];
