// src/lib/documents/us/professional-liability-waiver/questions.ts
import type { FormQuestion } from '@/types/documents';

export const professionalLiabilityWaiverQuestions: FormQuestion[] = [
  {
    id: 'professionalName',
    type: 'text',
    label: 'Professional Name',
    placeholder: 'Enter professional or practitioner name',
    required: true,
    group: 'professional',
  },
  {
    id: 'professionalTitle',
    type: 'text',
    label: 'Professional Title',
    placeholder: 'e.g., Doctor, Attorney, CPA, Engineer',
    required: true,
    group: 'professional',
  },
  {
    id: 'businessName',
    type: 'text',
    label: 'Business/Practice Name',
    placeholder: 'Enter business or practice name',
    required: false,
    group: 'professional',
  },
  {
    id: 'businessAddress',
    type: 'text',
    label: 'Business Address',
    placeholder: 'Enter complete business address',
    required: true,
    group: 'professional',
  },
  {
    id: 'businessPhone',
    type: 'text',
    label: 'Business Phone',
    placeholder: 'Enter phone number',
    required: false,
    group: 'professional',
  },
  {
    id: 'businessEmail',
    type: 'email',
    label: 'Business Email',
    placeholder: 'Enter email address',
    required: false,
    group: 'professional',
  },
  {
    id: 'licenseNumber',
    type: 'text',
    label: 'License Number',
    placeholder: 'Enter professional license number',
    required: false,
    group: 'professional',
  },
  {
    id: 'certificationNumber',
    type: 'text',
    label: 'Certification Number',
    placeholder: 'Enter certification number',
    required: false,
    group: 'professional',
  },
  {
    id: 'professionalType',
    type: 'select',
    label: 'Professional Type',
    options: [
      { value: 'doctor', label: 'Doctor/Physician' },
      { value: 'lawyer', label: 'Attorney/Lawyer' },
      { value: 'accountant', label: 'Accountant/CPA' },
      { value: 'engineer', label: 'Engineer' },
      { value: 'architect', label: 'Architect' },
      { value: 'consultant', label: 'Consultant' },
      { value: 'therapist', label: 'Therapist/Counselor' },
      { value: 'financial-advisor', label: 'Financial Advisor' },
      { value: 'real-estate-agent', label: 'Real Estate Agent' },
      { value: 'contractor', label: 'Contractor' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'professional',
  },
  {
    id: 'specialization',
    type: 'text',
    label: 'Specialization',
    placeholder: 'Area of specialization',
    required: false,
    group: 'professional',
  },
  {
    id: 'yearsOfExperience',
    type: 'text',
    label: 'Years of Experience',
    placeholder: 'Number of years practicing',
    required: false,
    group: 'professional',
  },
  {
    id: 'clientType',
    type: 'select',
    label: 'Client Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'business', label: 'Business' },
      { value: 'organization', label: 'Organization' },
      { value: 'government', label: 'Government' },
    ],
    required: true,
    group: 'client',
  },
  {
    id: 'collectClientName',
    type: 'checkbox',
    label: 'Collect client name',
    required: false,
    group: 'client-data',
  },
  {
    id: 'collectClientAddress',
    type: 'checkbox',
    label: 'Collect client address',
    required: false,
    group: 'client-data',
  },
  {
    id: 'collectClientPhone',
    type: 'checkbox',
    label: 'Collect client phone',
    required: false,
    group: 'client-data',
  },
  {
    id: 'collectClientEmail',
    type: 'checkbox',
    label: 'Collect client email',
    required: false,
    group: 'client-data',
  },
  {
    id: 'serviceType',
    type: 'text',
    label: 'Service Type',
    placeholder: 'Type of professional service',
    required: true,
    group: 'service',
  },
  {
    id: 'serviceDescription',
    type: 'textarea',
    label: 'Service Description',
    placeholder: 'Detailed description of services to be provided',
    required: true,
    group: 'service',
  },
  {
    id: 'serviceDuration',
    type: 'text',
    label: 'Service Duration',
    placeholder: 'Expected duration of service',
    required: false,
    group: 'service',
  },
  {
    id: 'serviceLocation',
    type: 'text',
    label: 'Service Location',
    placeholder: 'Where services will be provided',
    required: false,
    group: 'service',
  },
  {
    id: 'serviceStartDate',
    type: 'date',
    label: 'Service Start Date',
    required: false,
    group: 'service',
  },
  {
    id: 'serviceEndDate',
    type: 'date',
    label: 'Service End Date',
    required: false,
    group: 'service',
  },
  {
    id: 'standardOfCare',
    type: 'select',
    label: 'Standard of Care',
    options: [
      { value: 'reasonable-care', label: 'Reasonable Care' },
      { value: 'industry-standard', label: 'Industry Standard' },
      { value: 'best-efforts', label: 'Best Efforts' },
      { value: 'specific-standard', label: 'Specific Standard' },
    ],
    required: true,
    group: 'standards',
  },
  {
    id: 'industryStandards',
    type: 'checkbox',
    label: 'Follow industry standards',
    required: false,
    group: 'standards',
  },
  {
    id: 'professionalGuidelines',
    type: 'checkbox',
    label: 'Follow professional guidelines',
    required: false,
    group: 'standards',
  },
  {
    id: 'ethicalStandards',
    type: 'checkbox',
    label: 'Follow ethical standards',
    required: false,
    group: 'standards',
  },
  {
    id: 'continuingEducation',
    type: 'checkbox',
    label: 'Maintain continuing education',
    required: false,
    group: 'standards',
  },
  {
    id: 'waiverScope',
    type: 'select',
    label: 'Waiver Scope',
    options: [
      { value: 'negligence-only', label: 'Negligence Only' },
      { value: 'malpractice-only', label: 'Malpractice Only' },
      { value: 'all-professional-claims', label: 'All Professional Claims' },
      { value: 'specific-services', label: 'Specific Services Only' },
    ],
    required: true,
    group: 'waiver-scope',
  },
  {
    id: 'includeMalpracticeClaims',
    type: 'checkbox',
    label: 'Include malpractice claims',
    required: false,
    group: 'waiver-scope',
  },
  {
    id: 'includeNegligenceClaims',
    type: 'checkbox',
    label: 'Include negligence claims',
    required: false,
    group: 'waiver-scope',
  },
  {
    id: 'includeErrorsOmissionsClaims',
    type: 'checkbox',
    label: 'Include errors and omissions claims',
    required: false,
    group: 'waiver-scope',
  },
  {
    id: 'includeBreachOfDutyClaims',
    type: 'checkbox',
    label: 'Include breach of duty claims',
    required: false,
    group: 'waiver-scope',
  },
  {
    id: 'includeBreachOfContractClaims',
    type: 'checkbox',
    label: 'Include breach of contract claims',
    required: false,
    group: 'waiver-scope',
  },
  {
    id: 'includeMisrepresentationClaims',
    type: 'checkbox',
    label: 'Include misrepresentation claims',
    required: false,
    group: 'waiver-scope',
  },
  {
    id: 'clinicalErrors',
    type: 'checkbox',
    label: 'Include clinical errors',
    required: false,
    group: 'error-types',
  },
  {
    id: 'diagnosticErrors',
    type: 'checkbox',
    label: 'Include diagnostic errors',
    required: false,
    group: 'error-types',
  },
  {
    id: 'treatmentErrors',
    type: 'checkbox',
    label: 'Include treatment errors',
    required: false,
    group: 'error-types',
  },
  {
    id: 'legalErrors',
    type: 'checkbox',
    label: 'Include legal errors',
    required: false,
    group: 'error-types',
  },
  {
    id: 'accountingErrors',
    type: 'checkbox',
    label: 'Include accounting errors',
    required: false,
    group: 'error-types',
  },
  {
    id: 'designErrors',
    type: 'checkbox',
    label: 'Include design errors',
    required: false,
    group: 'error-types',
  },
  {
    id: 'adviceErrors',
    type: 'checkbox',
    label: 'Include advice errors',
    required: false,
    group: 'error-types',
  },
  {
    id: 'communicationErrors',
    type: 'checkbox',
    label: 'Include communication errors',
    required: false,
    group: 'error-types',
  },
  {
    id: 'releasedParties',
    type: 'multiselect',
    label: 'Additional Released Parties',
    options: [
      { value: 'supervisors', label: 'Supervisors' },
      { value: 'mentors', label: 'Mentors' },
      { value: 'referral-sources', label: 'Referral Sources' },
      { value: 'collaborators', label: 'Collaborators' },
      { value: 'specialists', label: 'Specialists' },
    ],
    required: false,
    group: 'released-parties',
  },
  {
    id: 'includeProfessional',
    type: 'checkbox',
    label: 'Include professional',
    required: false,
    group: 'released-parties',
  },
  {
    id: 'includeFirm',
    type: 'checkbox',
    label: 'Include firm/practice',
    required: false,
    group: 'released-parties',
  },
  {
    id: 'includePartners',
    type: 'checkbox',
    label: 'Include partners',
    required: false,
    group: 'released-parties',
  },
  {
    id: 'includeAssociates',
    type: 'checkbox',
    label: 'Include associates',
    required: false,
    group: 'released-parties',
  },
  {
    id: 'includeEmployees',
    type: 'checkbox',
    label: 'Include employees',
    required: false,
    group: 'released-parties',
  },
  {
    id: 'includeConsultants',
    type: 'checkbox',
    label: 'Include consultants',
    required: false,
    group: 'released-parties',
  },
  {
    id: 'includeReferralSources',
    type: 'checkbox',
    label: 'Include referral sources',
    required: false,
    group: 'released-parties',
  },
  {
    id: 'personalInjuryClaims',
    type: 'checkbox',
    label: 'Release personal injury claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'propertyDamageClaims',
    type: 'checkbox',
    label: 'Release property damage claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'economicLossClaims',
    type: 'checkbox',
    label: 'Release economic loss claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'emotionalDistressClaims',
    type: 'checkbox',
    label: 'Release emotional distress claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'punitiveDamages',
    type: 'checkbox',
    label: 'Release punitive damages',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'consequentialDamages',
    type: 'checkbox',
    label: 'Release consequential damages',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'lossOfProfitsClaims',
    type: 'checkbox',
    label: 'Release loss of profits claims',
    required: false,
    group: 'claim-types',
  },
  {
    id: 'confidentialityObligation',
    type: 'checkbox',
    label: 'Maintain confidentiality',
    required: false,
    group: 'obligations',
  },
  {
    id: 'fiduciaryDutyObligation',
    type: 'checkbox',
    label: 'Maintain fiduciary duty',
    required: false,
    group: 'obligations',
  },
  {
    id: 'competenceObligation',
    type: 'checkbox',
    label: 'Maintain professional competence',
    required: false,
    group: 'obligations',
  },
  {
    id: 'timelinessObligation',
    type: 'checkbox',
    label: 'Provide timely service',
    required: false,
    group: 'obligations',
  },
  {
    id: 'communicationObligation',
    type: 'checkbox',
    label: 'Maintain proper communication',
    required: false,
    group: 'obligations',
  },
  {
    id: 'documentationObligation',
    type: 'checkbox',
    label: 'Maintain proper documentation',
    required: false,
    group: 'obligations',
  },
  {
    id: 'clientCooperation',
    type: 'checkbox',
    label: 'Client agrees to cooperate',
    required: false,
    group: 'client-responsibilities',
  },
  {
    id: 'provideTruthfulInformation',
    type: 'checkbox',
    label: 'Client provides truthful information',
    required: false,
    group: 'client-responsibilities',
  },
  {
    id: 'followRecommendations',
    type: 'checkbox',
    label: 'Client follows recommendations',
    required: false,
    group: 'client-responsibilities',
  },
  {
    id: 'timelyPayment',
    type: 'checkbox',
    label: 'Client makes timely payment',
    required: false,
    group: 'client-responsibilities',
  },
  {
    id: 'timelyResponse',
    type: 'checkbox',
    label: 'Client provides timely responses',
    required: false,
    group: 'client-responsibilities',
  },
  {
    id: 'maintainConfidentiality',
    type: 'checkbox',
    label: 'Client maintains confidentiality',
    required: false,
    group: 'client-responsibilities',
  },
  {
    id: 'risksExplained',
    type: 'checkbox',
    label: 'Risks explained to client',
    required: false,
    group: 'informed-consent',
  },
  {
    id: 'alternativesDiscussed',
    type: 'checkbox',
    label: 'Alternatives discussed',
    required: false,
    group: 'informed-consent',
  },
  {
    id: 'limitationsExplained',
    type: 'checkbox',
    label: 'Limitations explained',
    required: false,
    group: 'informed-consent',
  },
  {
    id: 'noGuaranteeDisclosed',
    type: 'checkbox',
    label: 'No guarantee disclosed',
    required: false,
    group: 'informed-consent',
  },
  {
    id: 'uncertaintyAcknowledged',
    type: 'checkbox',
    label: 'Uncertainty acknowledged',
    required: false,
    group: 'informed-consent',
  },
  {
    id: 'malpracticeInsurance',
    type: 'checkbox',
    label: 'Professional carries malpractice insurance',
    required: false,
    group: 'insurance',
  },
  {
    id: 'insuranceAmount',
    type: 'text',
    label: 'Insurance Coverage Amount',
    placeholder: 'Amount of coverage',
    required: false,
    group: 'insurance',
    dependsOn: 'malpracticeInsurance',
  },
  {
    id: 'insuranceCarrier',
    type: 'text',
    label: 'Insurance Carrier',
    placeholder: 'Name of insurance company',
    required: false,
    group: 'insurance',
    dependsOn: 'malpracticeInsurance',
  },
  {
    id: 'liabilityLimitation',
    type: 'checkbox',
    label: 'Include liability limitation',
    required: false,
    group: 'liability-limits',
  },
  {
    id: 'damageLimitation',
    type: 'select',
    label: 'Damage Limitation Method',
    options: [
      { value: 'fee-amount', label: 'Fee Amount' },
      { value: 'insurance-coverage', label: 'Insurance Coverage' },
      { value: 'specific-amount', label: 'Specific Amount' },
      { value: 'no-limitation', label: 'No Limitation' },
    ],
    required: false,
    group: 'liability-limits',
    dependsOn: 'liabilityLimitation',
  },
  {
    id: 'limitationAmount',
    type: 'text',
    label: 'Limitation Amount',
    placeholder: 'Enter specific dollar amount',
    required: false,
    group: 'liability-limits',
    dependsOn: 'damageLimitation',
  },
  {
    id: 'consequentialDamagesExclusion',
    type: 'checkbox',
    label: 'Exclude consequential damages',
    required: false,
    group: 'liability-limits',
  },
  {
    id: 'incidentalDamagesExclusion',
    type: 'checkbox',
    label: 'Exclude incidental damages',
    required: false,
    group: 'liability-limits',
  },
  {
    id: 'clientAssumptionOfRisk',
    type: 'checkbox',
    label: 'Client assumes risk',
    required: false,
    group: 'assumption-of-risk',
  },
  {
    id: 'treatmentRisks',
    type: 'checkbox',
    label: 'Include treatment risks',
    required: false,
    group: 'assumption-of-risk',
  },
  {
    id: 'serviceRisks',
    type: 'checkbox',
    label: 'Include service risks',
    required: false,
    group: 'assumption-of-risk',
  },
  {
    id: 'decisionRisks',
    type: 'checkbox',
    label: 'Include decision risks',
    required: false,
    group: 'assumption-of-risk',
  },
  {
    id: 'delayRisks',
    type: 'checkbox',
    label: 'Include delay risks',
    required: false,
    group: 'assumption-of-risk',
  },
  {
    id: 'serviceNatureUnderstood',
    type: 'checkbox',
    label: 'Client understands service nature',
    required: false,
    group: 'acknowledgment',
  },
  {
    id: 'limitationsUnderstood',
    type: 'checkbox',
    label: 'Client understands limitations',
    required: false,
    group: 'acknowledgment',
  },
  {
    id: 'risksUnderstood',
    type: 'checkbox',
    label: 'Client understands risks',
    required: false,
    group: 'acknowledgment',
  },
  {
    id: 'noGuaranteeUnderstood',
    type: 'checkbox',
    label: 'Client understands no guarantee',
    required: false,
    group: 'acknowledgment',
  },
  {
    id: 'voluntaryEngagement',
    type: 'checkbox',
    label: 'Client engages services voluntarily',
    required: false,
    group: 'acknowledgment',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'e.g., State of California',
    required: false,
    group: 'legal',
  },
  {
    id: 'jurisdiction',
    type: 'text',
    label: 'Jurisdiction',
    placeholder: 'Where disputes will be resolved',
    required: false,
    group: 'legal',
  },
  {
    id: 'venue',
    type: 'text',
    label: 'Venue',
    placeholder: 'Specific court or location',
    required: false,
    group: 'legal',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'litigation', label: 'Court Litigation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'mediation', label: 'Mediation' },
    ],
    required: false,
    group: 'legal',
  },
  {
    id: 'requireProfessionalSignature',
    type: 'checkbox',
    label: 'Require professional signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireClientSignature',
    type: 'checkbox',
    label: 'Require client signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireWitnessSignature',
    type: 'checkbox',
    label: 'Require witness signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'requireNotarization',
    type: 'checkbox',
    label: 'Require notarization',
    required: false,
    group: 'signatures',
  },
  {
    id: 'electronicSignatureAccepted',
    type: 'checkbox',
    label: 'Accept electronic signatures',
    required: false,
    group: 'signatures',
  },
];