// src/lib/documents/us/catering-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const cateringAgreementQuestions: FormQuestion[] = [
  {
    id: 'clientName',
    type: 'text',
    label: 'Client Name',
    placeholder: 'Enter client full name',
    required: true,
    group: 'client',
  },
  {
    id: 'clientEmail',
    type: 'email',
    label: 'Client Email',
    placeholder: 'Enter client email address',
    required: false,
    group: 'client',
  },
  {
    id: 'clientPhone',
    type: 'text',
    label: 'Client Phone',
    placeholder: 'Enter client phone number',
    required: false,
    group: 'client',
  },
  {
    id: 'catererName',
    type: 'text',
    label: 'Caterer Name',
    placeholder: 'Enter caterer name',
    required: true,
    group: 'caterer',
  },
  {
    id: 'catererBusinessName',
    type: 'text',
    label: 'Catering Business Name',
    placeholder: 'Enter business name',
    required: false,
    group: 'caterer',
  },
  {
    id: 'catererEmail',
    type: 'email',
    label: 'Caterer Email',
    placeholder: 'Enter caterer email',
    required: false,
    group: 'caterer',
  },
  {
    id: 'eventName',
    type: 'text',
    label: 'Event Name',
    placeholder: 'Enter event name',
    required: false,
    group: 'event',
  },
  {
    id: 'eventType',
    type: 'select',
    label: 'Event Type',
    options: [
      { value: 'wedding', label: 'Wedding' },
      { value: 'corporate', label: 'Corporate Event' },
      { value: 'birthday', label: 'Birthday Party' },
      { value: 'anniversary', label: 'Anniversary' },
      { value: 'graduation', label: 'Graduation' },
      { value: 'holiday', label: 'Holiday Party' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
    group: 'event',
  },
  {
    id: 'eventDate',
    type: 'date',
    label: 'Event Date',
    required: false,
    group: 'event',
  },
  {
    id: 'eventStartTime',
    type: 'text',
    label: 'Event Start Time',
    placeholder: 'Enter start time (e.g., 6:00 PM)',
    required: false,
    group: 'event',
  },
  {
    id: 'eventEndTime',
    type: 'text',
    label: 'Event End Time',
    placeholder: 'Enter end time (e.g., 11:00 PM)',
    required: false,
    group: 'event',
  },
  {
    id: 'venueAddress',
    type: 'text',
    label: 'Venue Address',
    placeholder: 'Enter venue address',
    required: false,
    group: 'venue',
  },
  {
    id: 'venueName',
    type: 'text',
    label: 'Venue Name',
    placeholder: 'Enter venue name',
    required: false,
    group: 'venue',
  },
  {
    id: 'kitchenFacilities',
    type: 'boolean',
    label: 'Kitchen facilities available at venue?',
    required: false,
    group: 'venue',
  },
  {
    id: 'guestCount',
    type: 'text',
    label: 'Expected Guest Count',
    placeholder: 'Enter estimated number of guests',
    required: false,
    group: 'guests',
  },
  {
    id: 'finalCountDeadline',
    type: 'date',
    label: 'Final Guest Count Deadline',
    required: false,
    group: 'guests',
  },
  {
    id: 'serviceStyle',
    type: 'select',
    label: 'Service Style',
    options: [
      { value: 'buffet', label: 'Buffet' },
      { value: 'plated', label: 'Plated Service' },
      { value: 'family-style', label: 'Family Style' },
      { value: 'cocktail', label: 'Cocktail Reception' },
      { value: 'stations', label: 'Food Stations' },
      { value: 'other', label: 'Other' },
    ],
    required: false,
    group: 'service',
  },
  {
    id: 'menuDescription',
    type: 'textarea',
    label: 'Menu Description',
    placeholder: 'Describe the menu and food items',
    required: false,
    group: 'menu',
  },
  {
    id: 'vegetarianOptions',
    type: 'boolean',
    label: 'Vegetarian options needed?',
    required: false,
    group: 'dietary',
  },
  {
    id: 'veganOptions',
    type: 'boolean',
    label: 'Vegan options needed?',
    required: false,
    group: 'dietary',
  },
  {
    id: 'glutenFreeOptions',
    type: 'boolean',
    label: 'Gluten-free options needed?',
    required: false,
    group: 'dietary',
  },
  {
    id: 'allergyAccommodations',
    type: 'boolean',
    label: 'Allergy accommodations needed?',
    required: false,
    group: 'dietary',
  },
  {
    id: 'allergyDetails',
    type: 'textarea',
    label: 'Allergy Details',
    placeholder: 'Describe specific allergies to accommodate',
    required: false,
    group: 'dietary',
  },
  {
    id: 'tablesChainsProvided',
    type: 'boolean',
    label: 'Tables and chairs provided by caterer?',
    required: false,
    group: 'equipment',
  },
  {
    id: 'linensProvided',
    type: 'boolean',
    label: 'Linens provided by caterer?',
    required: false,
    group: 'equipment',
  },
  {
    id: 'chinaProvided',
    type: 'boolean',
    label: 'China/plates provided by caterer?',
    required: false,
    group: 'equipment',
  },
  {
    id: 'alcoholService',
    type: 'boolean',
    label: 'Alcohol service required?',
    required: false,
    group: 'alcohol',
  },
  {
    id: 'barService',
    type: 'select',
    label: 'Bar Service Type',
    options: [
      { value: 'open-bar', label: 'Open Bar' },
      { value: 'cash-bar', label: 'Cash Bar' },
      { value: 'wine-beer-only', label: 'Wine & Beer Only' },
      { value: 'signature-cocktails', label: 'Signature Cocktails' },
      { value: 'none', label: 'No Bar Service' },
    ],
    required: false,
    group: 'alcohol',
  },
  {
    id: 'totalCost',
    type: 'text',
    label: 'Total Cost',
    placeholder: 'Enter total catering cost',
    required: false,
    group: 'pricing',
  },
  {
    id: 'perPersonCost',
    type: 'text',
    label: 'Per Person Cost',
    placeholder: 'Enter cost per person',
    required: false,
    group: 'pricing',
  },
  {
    id: 'serviceFee',
    type: 'text',
    label: 'Service Fee',
    placeholder: 'Enter service fee amount',
    required: false,
    group: 'pricing',
  },
  {
    id: 'depositAmount',
    type: 'text',
    label: 'Deposit Amount',
    placeholder: 'Enter deposit amount',
    required: false,
    group: 'payment',
  },
  {
    id: 'depositDueDate',
    type: 'date',
    label: 'Deposit Due Date',
    required: false,
    group: 'payment',
  },
  {
    id: 'finalPaymentDue',
    type: 'date',
    label: 'Final Payment Due Date',
    required: false,
    group: 'payment',
  },
  {
    id: 'paymentMethod',
    type: 'select',
    label: 'Payment Method',
    options: [
      { value: 'cash', label: 'Cash' },
      { value: 'check', label: 'Check' },
      { value: 'credit-card', label: 'Credit Card' },
      { value: 'bank-transfer', label: 'Bank Transfer' },
    ],
    required: false,
    group: 'payment',
  },
  {
    id: 'cancellationDeadline',
    type: 'date',
    label: 'Cancellation Deadline',
    required: false,
    group: 'cancellation',
  },
  {
    id: 'cancellationFee',
    type: 'text',
    label: 'Cancellation Fee',
    placeholder: 'Enter cancellation fee amount',
    required: false,
    group: 'cancellation',
  },
  {
    id: 'menuChangeDeadline',
    type: 'date',
    label: 'Menu Change Deadline',
    required: false,
    group: 'changes',
  },
  {
    id: 'specialRequests',
    type: 'textarea',
    label: 'Special Requests',
    placeholder: 'Enter any special requests or requirements',
    required: false,
    group: 'special',
  },
  {
    id: 'emergencyContact',
    type: 'text',
    label: 'Emergency Contact',
    placeholder: 'Enter emergency contact information',
    required: false,
    group: 'emergency',
  },
];