import { usStates } from '@/lib/usStates';
import type { Question } from '@/types/documents';

export const revolvingCreditAgreementQuestions: Question[] = [
  { id: 'date', label: 'Agreement Date', type: 'date', required: true },
  { id: 'creditorName', label: 'Creditor Name', type: 'text', required: true },
  {
    id: 'creditorAddress',
    label: 'Creditor Address',
    type: 'text',
    required: true,
    placeholder: 'Street, City, State, ZIP',
  },
  { id: 'debtorName', label: 'Debtor Name', type: 'text', required: true },
  {
    id: 'debtorAddress',
    label: 'Debtor Address',
    type: 'text',
    required: true,
    placeholder: 'Street, City, State, ZIP',
  },
  {
    id: 'creditLimit',
    label: 'Credit Limit',
    type: 'number',
    required: true,
    placeholder: 'e.g., 10000',
  },
  {
    id: 'interestRate',
    label: 'Interest Rate (%)',
    type: 'number',
    required: true,
    placeholder: 'e.g., 18.5',
  },
  {
    id: 'minimumPaymentPercentage',
    label: 'Minimum Payment Percentage (%)',
    type: 'number',
    required: true,
    placeholder: 'e.g., 3',
  },
  {
    id: 'billingCycle',
    label: 'Billing Cycle',
    type: 'select',
    required: true,
    options: [
      { value: 'Monthly', label: 'Monthly' },
      { value: 'Bi-monthly', label: 'Bi-monthly' },
    ],
  },
  {
    id: 'paymentDueDate',
    label: 'Payment Due Date (Day of Month)',
    type: 'number',
    required: true,
    placeholder: 'e.g., 15',
  },
  {
    id: 'gracePerod',
    label: 'Grace Period (Days)',
    type: 'number',
    required: true,
    placeholder: 'e.g., 21',
  },
  {
    id: 'lateFeeAmount',
    label: 'Late Fee Amount ($)',
    type: 'number',
    required: true,
    placeholder: 'e.g., 25',
  },
  {
    id: 'overlimitFee',
    label: 'Over-limit Fee ($)',
    type: 'number',
    required: true,
    placeholder: 'e.g., 35',
  },
  {
    id: 'cashAdvanceFee',
    label: 'Cash Advance Fee ($)',
    type: 'number',
    required: true,
    placeholder: 'e.g., 10',
  },
  {
    id: 'cashAdvanceRate',
    label: 'Cash Advance Rate (%)',
    type: 'number',
    required: true,
    placeholder: 'e.g., 24.5',
  },
  {
    id: 'governingLaw',
    label: 'Governing Law',
    type: 'select',
    required: true,
    options: usStates.map((s) => ({ value: s.value, label: s.label })),
  },
  {
    id: 'creditReviewFrequency',
    label: 'Credit Review Frequency',
    type: 'select',
    required: true,
    options: [
      { value: 'Quarterly', label: 'Quarterly' },
      { value: 'Semi-annually', label: 'Semi-annually' },
      { value: 'Annually', label: 'Annually' },
    ],
  },
  {
    id: 'defaultRate',
    label: 'Default Interest Rate (%)',
    type: 'number',
    required: false,
    tooltip: 'Higher rate applied after default',
  },
  {
    id: 'annualFee',
    label: 'Annual Fee ($)',
    type: 'number',
    required: false,
    tooltip: 'Annual fee for maintaining the credit line',
  },
];
