// src/lib/documents/us/roofing-contract/questions.ts
import type { FormQuestion } from '@/types/documents';

export const roofingContractQuestions: FormQuestion[] = [
  {
    id: 'ownerName',
    type: 'text',
    label: 'Property Owner Name',
    placeholder: 'Enter property owner full name',
    required: true,
    group: 'owner',
  },
  {
    id: 'ownerAddress',
    type: 'text',
    label: 'Owner Address',
    placeholder: 'Enter complete owner address',
    required: true,
    group: 'owner',
  },
  {
    id: 'ownerPhone',
    type: 'text',
    label: 'Owner Phone',
    placeholder: 'Enter phone number',
    required: true,
    group: 'owner',
  },
  {
    id: 'contractorName',
    type: 'text',
    label: 'Roofing Contractor Name',
    placeholder: 'Enter contractor/company name',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorAddress',
    type: 'text',
    label: 'Contractor Address',
    placeholder: 'Enter complete contractor address',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorPhone',
    type: 'text',
    label: 'Contractor Phone',
    placeholder: 'Enter phone number',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorLicense',
    type: 'text',
    label: 'Contractor License Number',
    placeholder: 'Enter contractor license number',
    required: true,
    group: 'contractor',
  },
  {
    id: 'businessInsurance',
    type: 'text',
    label: 'Business Insurance Information',
    placeholder: 'Insurance company and policy details',
    required: true,
    group: 'contractor',
  },
  {
    id: 'projectAddress',
    type: 'text',
    label: 'Project Address',
    placeholder: 'Where roofing work will be performed',
    required: true,
    group: 'project',
  },
  {
    id: 'roofingType',
    type: 'select',
    label: 'Type of Roofing Work',
    options: [
      { value: 'repair', label: 'Roof Repair' },
      { value: 'replacement', label: 'Full Roof Replacement' },
      { value: 'new-installation', label: 'New Roof Installation' },
      { value: 'partial-replacement', label: 'Partial Roof Replacement' },
      { value: 'inspection-repair', label: 'Inspection and Minor Repairs' },
    ],
    required: true,
    group: 'project',
  },
  {
    id: 'roofType',
    type: 'select',
    label: 'Roof Type',
    options: [
      { value: 'asphalt-shingles', label: 'Asphalt Shingles' },
      { value: 'metal', label: 'Metal Roofing' },
      { value: 'tile', label: 'Tile Roofing' },
      { value: 'slate', label: 'Slate Roofing' },
      { value: 'flat-roof', label: 'Flat Roof' },
      { value: 'wood-shingles', label: 'Wood Shingles' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'project',
  },
  {
    id: 'roofSize',
    type: 'text',
    label: 'Roof Size',
    placeholder: 'Enter roof size (e.g., 2,000 sq ft, 20 squares)',
    required: true,
    group: 'project',
  },
  {
    id: 'workDescription',
    type: 'textarea',
    label: 'Work Description',
    placeholder: 'Detailed description of roofing work to be performed',
    required: true,
    group: 'scope',
  },
  {
    id: 'workScope',
    type: 'textarea',
    label: 'Detailed Work Scope',
    placeholder: 'Specific tasks and materials included',
    required: true,
    group: 'scope',
  },
  {
    id: 'materialsSpecified',
    type: 'checkbox',
    label: 'Contractor provides all materials',
    required: false,
    group: 'materials',
  },
  {
    id: 'shingleType',
    type: 'text',
    label: 'Shingle Type/Brand',
    placeholder: 'Specify shingle manufacturer and type',
    required: false,
    group: 'materials',
  },
  {
    id: 'shingleColor',
    type: 'text',
    label: 'Shingle Color',
    placeholder: 'Specify shingle color',
    required: false,
    group: 'materials',
  },
  {
    id: 'contractDate',
    type: 'date',
    label: 'Contract Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'startDate',
    type: 'date',
    label: 'Start Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'completionDate',
    type: 'date',
    label: 'Completion Date',
    required: true,
    group: 'timeline',
  },
  {
    id: 'weatherDelayPolicy',
    type: 'checkbox',
    label: 'Include weather delay policy',
    required: false,
    group: 'timeline',
  },
  {
    id: 'contractPrice',
    type: 'text',
    label: 'Total Contract Price',
    placeholder: 'Enter total roofing project cost',
    required: true,
    group: 'pricing',
  },
  {
    id: 'priceType',
    type: 'select',
    label: 'Price Type',
    options: [
      { value: 'fixed-price', label: 'Fixed Price' },
      { value: 'per-square', label: 'Per Square Foot' },
      { value: 'time-and-materials', label: 'Time and Materials' },
    ],
    required: true,
    group: 'pricing',
  },
  {
    id: 'paymentSchedule',
    type: 'select',
    label: 'Payment Schedule',
    options: [
      { value: 'down-payment-completion', label: 'Down Payment + Completion' },
      { value: 'progress-payments', label: 'Progress Payments' },
      { value: 'payment-on-completion', label: 'Payment on Completion' },
    ],
    required: true,
    group: 'payment',
  },
  {
    id: 'downPayment',
    type: 'text',
    label: 'Down Payment Amount',
    placeholder: 'Initial payment amount',
    required: false,
    group: 'payment',
  },
  {
    id: 'permitsRequired',
    type: 'checkbox',
    label: 'Building permits required',
    required: false,
    group: 'permits',
  },
  {
    id: 'permitResponsibility',
    type: 'select',
    label: 'Permit Responsibility',
    options: [
      { value: 'owner', label: 'Owner Responsible' },
      { value: 'contractor', label: 'Contractor Responsible' },
    ],
    required: false,
    group: 'permits',
    dependsOn: 'permitsRequired',
  },
  {
    id: 'debrisRemoval',
    type: 'checkbox',
    label: 'Contractor handles debris removal',
    required: false,
    group: 'cleanup',
  },
  {
    id: 'magneticSweep',
    type: 'checkbox',
    label: 'Magnetic sweep for nails and metal',
    required: false,
    group: 'cleanup',
  },
  {
    id: 'propertyProtection',
    type: 'checkbox',
    label: 'Property protection during work',
    required: false,
    group: 'cleanup',
  },
  {
    id: 'liabilityInsurance',
    type: 'text',
    label: 'Liability Insurance Amount',
    placeholder: 'Minimum coverage amount required',
    required: true,
    group: 'insurance',
  },
  {
    id: 'workersCompensation',
    type: 'checkbox',
    label: 'Workers compensation insurance required',
    required: false,
    group: 'insurance',
  },
  {
    id: 'workmanshipWarranty',
    type: 'checkbox',
    label: 'Include workmanship warranty',
    required: false,
    group: 'warranty',
  },
  {
    id: 'workmanshipWarrantyPeriod',
    type: 'text',
    label: 'Workmanship Warranty Period',
    placeholder: 'e.g., 2 years, 5 years',
    required: false,
    group: 'warranty',
    dependsOn: 'workmanshipWarranty',
  },
  {
    id: 'materialWarranty',
    type: 'checkbox',
    label: 'Transfer material warranties to owner',
    required: false,
    group: 'warranty',
  },
  {
    id: 'leakWarranty',
    type: 'checkbox',
    label: 'Include leak warranty',
    required: false,
    group: 'warranty',
  },
  {
    id: 'weatherProtection',
    type: 'checkbox',
    label: 'Weather protection measures',
    required: false,
    group: 'weather',
  },
  {
    id: 'tarpingPolicy',
    type: 'checkbox',
    label: 'Tarping policy for unexpected weather',
    required: false,
    group: 'weather',
  },
  {
    id: 'safetyCompliance',
    type: 'checkbox',
    label: 'Safety compliance required',
    required: false,
    group: 'safety',
  },
  {
    id: 'oshaCompliance',
    type: 'checkbox',
    label: 'OSHA compliance required',
    required: false,
    group: 'safety',
  },
  {
    id: 'changeOrderProcess',
    type: 'checkbox',
    label: 'Include change order procedures',
    required: false,
    group: 'changes',
  },
  {
    id: 'qualityStandards',
    type: 'textarea',
    label: 'Quality Standards',
    placeholder: 'Specific quality requirements',
    required: false,
    group: 'quality',
  },
  {
    id: 'finalInspection',
    type: 'checkbox',
    label: 'Final inspection required',
    required: false,
    group: 'quality',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution Method',
    options: [
      { value: 'negotiation', label: 'Negotiation' },
      { value: 'mediation', label: 'Mediation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'litigation', label: 'Court Litigation' },
    ],
    required: true,
    group: 'disputes',
  },
];
