// src/lib/documents/us/pet-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const petAgreementQuestions: FormQuestion[] = [
  {
    id: 'landlordName',
    type: 'text',
    label: 'Landlord Name',
    placeholder: 'Enter landlord full name',
    required: true,
    group: 'parties',
  },
  {
    id: 'tenantName',
    type: 'text',
    label: 'Tenant Name',
    placeholder: 'Enter tenant full name',
    required: true,
    group: 'parties',
  },
  {
    id: 'propertyAddress',
    type: 'textarea',
    label: 'Property Address',
    placeholder: 'Enter the rental property address',
    required: true,
    group: 'parties',
  },
  {
    id: 'originalLeaseDate',
    type: 'date',
    label: 'Original Lease Date',
    required: true,
    group: 'lease',
  },
  {
    id: 'petName',
    type: 'text',
    label: 'Pet Name',
    placeholder: 'Enter your pet\'s name',
    required: true,
    group: 'pet',
  },
  {
    id: 'petType',
    type: 'select',
    label: 'Pet Type',
    options: [
      { value: 'dog', label: 'Dog' },
      { value: 'cat', label: 'Cat' },
      { value: 'bird', label: 'Bird' },
      { value: 'fish', label: 'Fish' },
      { value: 'reptile', label: 'Reptile' },
      { value: 'small-mammal', label: 'Small Mammal (rabbit, hamster, etc.)' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'pet',
  },
  {
    id: 'petBreed',
    type: 'text',
    label: 'Pet Breed',
    placeholder: 'e.g., Golden Retriever, Persian Cat',
    required: false,
    group: 'pet',
  },
  {
    id: 'petAge',
    type: 'text',
    label: 'Pet Age',
    placeholder: 'e.g., 3 years, 6 months',
    required: false,
    group: 'pet',
  },
  {
    id: 'petWeight',
    type: 'text',
    label: 'Pet Weight',
    placeholder: 'e.g., 25 lbs, 10 kg',
    required: false,
    group: 'pet',
  },
  {
    id: 'petColor',
    type: 'text',
    label: 'Pet Color/Description',
    placeholder: 'e.g., Brown and white, Black',
    required: false,
    group: 'pet',
  },
  {
    id: 'petGender',
    type: 'select',
    label: 'Pet Gender',
    options: [
      { value: 'male', label: 'Male' },
      { value: 'female', label: 'Female' },
      { value: 'unknown', label: 'Unknown' },
    ],
    required: false,
    group: 'pet',
  },
  {
    id: 'hasAdditionalPets',
    type: 'checkbox',
    label: 'I have additional pets',
    required: false,
    group: 'pet',
  },
  {
    id: 'hasVaccinations',
    type: 'checkbox',
    label: 'Pet is up-to-date on vaccinations',
    required: false,
    group: 'documentation',
  },
  {
    id: 'hasSpayNeuter',
    type: 'checkbox',
    label: 'Pet is spayed/neutered',
    required: false,
    group: 'documentation',
  },
  {
    id: 'hasLicense',
    type: 'checkbox',
    label: 'Pet has current license',
    required: false,
    group: 'documentation',
  },
  {
    id: 'hasMicrochip',
    type: 'checkbox',
    label: 'Pet has microchip',
    required: false,
    group: 'documentation',
  },
  {
    id: 'petDeposit',
    type: 'number',
    label: 'Pet Deposit ($)',
    placeholder: '300',
    required: false,
    group: 'financial',
  },
  {
    id: 'petFee',
    type: 'number',
    label: 'Non-refundable Pet Fee ($)',
    placeholder: '200',
    required: false,
    group: 'financial',
  },
  {
    id: 'monthlyPetRent',
    type: 'number',
    label: 'Monthly Pet Rent ($)',
    placeholder: '25',
    required: false,
    group: 'financial',
  },
  {
    id: 'petCareRequirements',
    type: 'textarea',
    label: 'Pet Care Requirements',
    placeholder: 'Special care instructions, feeding schedules, etc.',
    required: false,
    group: 'rules',
  },
  {
    id: 'noiseRestrictions',
    type: 'textarea',
    label: 'Noise Restrictions',
    placeholder: 'Rules about barking, noise levels, quiet hours',
    required: false,
    group: 'rules',
  },
  {
    id: 'liabilityInsurance',
    type: 'checkbox',
    label: 'Tenant will maintain liability insurance for pet',
    required: false,
    group: 'liability',
  },
  {
    id: 'insuranceAmount',
    type: 'number',
    label: 'Insurance Coverage Amount ($)',
    placeholder: '100000',
    required: false,
    group: 'liability',
    dependsOn: 'liabilityInsurance',
  },
  {
    id: 'additionalTerms',
    type: 'textarea',
    label: 'Additional Terms',
    placeholder: 'Any additional pet-related rules or agreements',
    required: false,
    group: 'additional',
  },
];