// src/lib/documents/us/simple-will/questions.ts
import type { FormQuestion } from '@/types/documents';

export const simpleWillQuestions: FormQuestion[] = [
  {
    id: 'testatorName',
    type: 'text',
    label: 'Your Full Legal Name',
    placeholder: 'Enter your full legal name as it appears on official documents',
    required: true,
    group: 'testator',
  },
  {
    id: 'testatorAddress',
    type: 'textarea',
    label: 'Your Address',
    placeholder: 'Enter your complete address',
    required: true,
    group: 'testator',
  },
  {
    id: 'testatorCounty',
    type: 'text',
    label: 'County',
    placeholder: 'Enter the county where you reside',
    required: true,
    group: 'testator',
  },
  {
    id: 'testatorState',
    type: 'text',
    label: 'State',
    placeholder: 'Enter your state',
    required: true,
    group: 'testator',
  },
  {
    id: 'executorName',
    type: 'text',
    label: 'Executor Full Name',
    placeholder: 'Name of person who will execute your will',
    required: true,
    group: 'executor',
  },
  {
    id: 'executorAddress',
    type: 'textarea',
    label: 'Executor Address',
    placeholder: 'Complete address of your executor',
    required: true,
    group: 'executor',
  },
  {
    id: 'executorRelationship',
    type: 'text',
    label: 'Executor Relationship',
    placeholder: 'e.g., spouse, child, friend, attorney',
    required: true,
    group: 'executor',
  },
  {
    id: 'alternateExecutorName',
    type: 'text',
    label: 'Alternate Executor Name',
    placeholder: 'Name of backup executor (optional)',
    required: false,
    group: 'executor',
  },
  {
    id: 'alternateExecutorAddress',
    type: 'textarea',
    label: 'Alternate Executor Address',
    placeholder: 'Address of backup executor',
    required: false,
    group: 'executor',
  },
  {
    id: 'alternateExecutorRelationship',
    type: 'text',
    label: 'Alternate Executor Relationship',
    placeholder: 'Relationship to alternate executor',
    required: false,
    group: 'executor',
  },
  {
    id: 'hasMinorChildren',
    type: 'checkbox',
    label: 'I have minor children (under 18)',
    required: false,
    group: 'children',
  },
  {
    id: 'guardianName',
    type: 'text',
    label: 'Guardian for Minor Children',
    placeholder: 'Name of proposed guardian',
    required: false,
    group: 'children',
    dependsOn: 'hasMinorChildren',
  },
  {
    id: 'guardianAddress',
    type: 'textarea',
    label: 'Guardian Address',
    placeholder: 'Address of proposed guardian',
    required: false,
    group: 'children',
    dependsOn: 'hasMinorChildren',
  },
  {
    id: 'guardianRelationship',
    type: 'text',
    label: 'Guardian Relationship',
    placeholder: 'Relationship to proposed guardian',
    required: false,
    group: 'children',
    dependsOn: 'hasMinorChildren',
  },
  {
    id: 'alternateGuardianName',
    type: 'text',
    label: 'Alternate Guardian Name',
    placeholder: 'Name of backup guardian',
    required: false,
    group: 'children',
    dependsOn: 'hasMinorChildren',
  },
  {
    id: 'alternateGuardianAddress',
    type: 'textarea',
    label: 'Alternate Guardian Address',
    placeholder: 'Address of backup guardian',
    required: false,
    group: 'children',
    dependsOn: 'hasMinorChildren',
  },
  {
    id: 'primaryBeneficiary',
    type: 'text',
    label: 'Primary Beneficiary',
    placeholder: 'Name of main beneficiary',
    required: true,
    group: 'beneficiaries',
  },
  {
    id: 'primaryBeneficiaryRelationship',
    type: 'text',
    label: 'Primary Beneficiary Relationship',
    placeholder: 'e.g., spouse, child, parent',
    required: true,
    group: 'beneficiaries',
  },
  {
    id: 'primaryBeneficiaryShare',
    type: 'text',
    label: 'Primary Beneficiary Share',
    placeholder: 'e.g., 100%, 50%',
    required: false,
    group: 'beneficiaries',
  },
  {
    id: 'hasAdditionalBeneficiaries',
    type: 'checkbox',
    label: 'I have additional beneficiaries',
    required: false,
    group: 'beneficiaries',
  },
  {
    id: 'hasSpecificBequests',
    type: 'checkbox',
    label: 'I want to leave specific items to specific people',
    required: false,
    group: 'bequests',
  },
  {
    id: 'residuaryBeneficiary',
    type: 'text',
    label: 'Residuary Beneficiary',
    placeholder: 'Who gets everything else not specifically mentioned',
    required: false,
    group: 'residuary',
  },
  {
    id: 'residuaryBeneficiaryRelationship',
    type: 'text',
    label: 'Residuary Beneficiary Relationship',
    placeholder: 'Relationship to residuary beneficiary',
    required: false,
    group: 'residuary',
  },
  {
    id: 'debtPaymentInstructions',
    type: 'select',
    label: 'How should debts and expenses be paid?',
    options: [
      { value: 'pay from estate', label: 'Pay from estate before distribution' },
      { value: 'specific source', label: 'Pay from specific assets' },
      { value: 'proportional', label: 'Deduct proportionally from all gifts' },
    ],
    required: false,
    group: 'debts',
  },
  {
    id: 'additionalProvisions',
    type: 'textarea',
    label: 'Additional Provisions',
    placeholder: 'Any additional instructions or provisions',
    required: false,
    group: 'additional',
  },
];