// src/lib/documents/us/sale-of-goods/questions.ts
import type { FormQuestion } from '@/types/documents';

export const saleOfGoodsQuestions: FormQuestion[] = [
  // Seller Information
  {
    id: 'sellerName',
    type: 'text',
    label: 'Seller Full Name',
    placeholder: "Enter seller's full name or business name",
    required: true,
    section: 'Seller Information',
  },
  {
    id: 'sellerAddress',
    type: 'address',
    label: 'Seller Address',
    placeholder: "Enter seller's complete address",
    required: true,
    section: 'Seller Information',
  },
  {
    id: 'sellerType',
    type: 'select',
    label: 'Seller Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'llc', label: 'LLC' },
      { value: 'partnership', label: 'Partnership' },
    ],
    required: true,
    section: 'Seller Information',
  },
  {
    id: 'sellerPhone',
    type: 'tel',
    label: 'Seller Phone Number',
    placeholder: 'Enter phone number',
    required: false,
    section: 'Seller Information',
  },
  {
    id: 'sellerEmail',
    type: 'email',
    label: 'Seller Email',
    placeholder: 'Enter email address',
    required: false,
    section: 'Seller Information',
  },

  // Buyer Information
  {
    id: 'buyerName',
    type: 'text',
    label: 'Buyer Full Name',
    placeholder: "Enter buyer's full name or business name",
    required: true,
    section: 'Buyer Information',
  },
  {
    id: 'buyerAddress',
    type: 'address',
    label: 'Buyer Address',
    placeholder: "Enter buyer's complete address",
    required: true,
    section: 'Buyer Information',
  },
  {
    id: 'buyerType',
    type: 'select',
    label: 'Buyer Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'corporation', label: 'Corporation' },
      { value: 'llc', label: 'LLC' },
      { value: 'partnership', label: 'Partnership' },
    ],
    required: true,
    section: 'Buyer Information',
  },
  {
    id: 'buyerPhone',
    type: 'tel',
    label: 'Buyer Phone Number',
    placeholder: 'Enter phone number',
    required: false,
    section: 'Buyer Information',
  },
  {
    id: 'buyerEmail',
    type: 'email',
    label: 'Buyer Email',
    placeholder: 'Enter email address',
    required: false,
    section: 'Buyer Information',
  },

  // Goods Description
  {
    id: 'goodsDescription',
    type: 'textarea',
    label: 'Goods Description',
    placeholder: 'Provide detailed description of the goods being sold',
    required: true,
    section: 'Goods Details',
  },
  {
    id: 'goodsQuantity',
    type: 'text',
    label: 'Quantity',
    placeholder: 'Enter quantity (e.g., 10, 100)',
    required: true,
    section: 'Goods Details',
  },
  {
    id: 'goodsUnit',
    type: 'text',
    label: 'Unit of Measurement',
    placeholder: 'e.g., pieces, tons, gallons, boxes',
    required: true,
    section: 'Goods Details',
  },
  {
    id: 'goodsCondition',
    type: 'select',
    label: 'Condition of Goods',
    options: [
      { value: 'new', label: 'New' },
      { value: 'used', label: 'Used' },
      { value: 'refurbished', label: 'Refurbished' },
      { value: 'as_is', label: 'As-Is' },
    ],
    required: true,
    section: 'Goods Details',
  },
  {
    id: 'goodsCategory',
    type: 'select',
    label: 'Category of Goods',
    options: [
      { value: 'equipment', label: 'Equipment' },
      { value: 'inventory', label: 'Inventory' },
      { value: 'materials', label: 'Materials' },
      { value: 'vehicles', label: 'Vehicles' },
      { value: 'electronics', label: 'Electronics' },
      { value: 'furniture', label: 'Furniture' },
      { value: 'clothing', label: 'Clothing' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    section: 'Goods Details',
  },

  // Identification Numbers
  {
    id: 'serialNumbers',
    type: 'textarea',
    label: 'Serial Numbers (if applicable)',
    placeholder: 'Enter serial numbers for goods',
    required: false,
    section: 'Identification',
  },
  {
    id: 'modelNumbers',
    type: 'textarea',
    label: 'Model Numbers (if applicable)',
    placeholder: 'Enter model numbers',
    required: false,
    section: 'Identification',
  },
  {
    id: 'partNumbers',
    type: 'textarea',
    label: 'Part Numbers (if applicable)',
    placeholder: 'Enter part numbers',
    required: false,
    section: 'Identification',
  },

  // Price and Payment
  {
    id: 'totalPrice',
    type: 'currency',
    label: 'Total Purchase Price',
    placeholder: 'Enter total price',
    required: true,
    section: 'Price and Payment',
  },
  {
    id: 'currency',
    type: 'select',
    label: 'Currency',
    options: [
      { value: 'USD', label: 'US Dollar (USD)' },
      { value: 'EUR', label: 'Euro (EUR)' },
      { value: 'CAD', label: 'Canadian Dollar (CAD)' },
      { value: 'GBP', label: 'British Pound (GBP)' },
    ],
    required: true,
    section: 'Price and Payment',
  },
  {
    id: 'paymentMethod',
    type: 'select',
    label: 'Payment Method',
    options: [
      { value: 'cash', label: 'Cash' },
      { value: 'check', label: 'Check' },
      { value: 'wire_transfer', label: 'Wire Transfer' },
      { value: 'credit_card', label: 'Credit Card' },
      { value: 'financing', label: 'Financing' },
      { value: 'installments', label: 'Installment Payments' },
    ],
    required: true,
    section: 'Price and Payment',
  },
  {
    id: 'paymentTerms',
    type: 'textarea',
    label: 'Payment Terms',
    placeholder: 'Describe when and how payment will be made',
    required: true,
    section: 'Price and Payment',
  },
  {
    id: 'downPayment',
    type: 'currency',
    label: 'Down Payment (if applicable)',
    placeholder: 'Enter down payment amount',
    required: false,
    section: 'Price and Payment',
  },
  {
    id: 'balanceDue',
    type: 'currency',
    label: 'Balance Due (if applicable)',
    placeholder: 'Enter remaining balance',
    required: false,
    section: 'Price and Payment',
  },

  // Delivery Terms
  {
    id: 'deliveryMethod',
    type: 'select',
    label: 'Delivery Method',
    options: [
      { value: 'pickup', label: 'Buyer pickup' },
      { value: 'seller_delivery', label: 'Seller delivery' },
      { value: 'shipping', label: 'Shipping/Mail' },
      { value: 'third_party_carrier', label: 'Third-party carrier' },
    ],
    required: true,
    section: 'Delivery',
  },
  {
    id: 'deliveryLocation',
    type: 'address',
    label: 'Delivery Location',
    placeholder: 'Enter delivery address',
    required: true,
    section: 'Delivery',
  },
  {
    id: 'deliveryDate',
    type: 'date',
    label: 'Delivery Date',
    required: true,
    section: 'Delivery',
  },
  {
    id: 'deliveryCost',
    type: 'currency',
    label: 'Delivery Cost (if applicable)',
    placeholder: 'Enter delivery cost',
    required: false,
    section: 'Delivery',
  },
  {
    id: 'riskOfLoss',
    type: 'select',
    label: 'Risk of Loss',
    options: [
      { value: 'seller', label: 'Seller bears risk until delivery' },
      { value: 'buyer', label: 'Buyer bears risk from purchase' },
      { value: 'delivery', label: 'Risk transfers at delivery' },
    ],
    required: true,
    section: 'Delivery',
  },

  // Inspection and Acceptance
  {
    id: 'inspectionRights',
    type: 'radio',
    label: 'Buyer inspection rights',
    options: [
      { value: true, label: 'Buyer has right to inspect goods' },
      { value: false, label: 'No inspection rights' },
    ],
    required: true,
    section: 'Inspection',
  },
  {
    id: 'inspectionPeriod',
    type: 'text',
    label: 'Inspection Period',
    placeholder: 'e.g., 7 days, 48 hours',
    required: false,
    section: 'Inspection',
    conditional: {
      field: 'inspectionRights',
      value: [true],
    },
  },
  {
    id: 'acceptanceCriteria',
    type: 'textarea',
    label: 'Acceptance Criteria',
    placeholder: 'Describe criteria for acceptance of goods',
    required: false,
    section: 'Inspection',
    conditional: {
      field: 'inspectionRights',
      value: [true],
    },
  },
  {
    id: 'rejectionRights',
    type: 'radio',
    label: 'Buyer rejection rights',
    options: [
      { value: true, label: 'Buyer can reject non-conforming goods' },
      { value: false, label: 'No rejection rights' },
    ],
    required: true,
    section: 'Inspection',
  },

  // Warranties
  {
    id: 'warrantyOffered',
    type: 'radio',
    label: 'Warranty offered?',
    options: [
      { value: true, label: 'Yes, warranty is offered' },
      { value: false, label: 'No warranty offered' },
    ],
    required: true,
    section: 'Warranties',
  },
  {
    id: 'warrantyType',
    type: 'select',
    label: 'Type of Warranty',
    options: [
      { value: 'express', label: 'Express warranty' },
      { value: 'implied', label: 'Implied warranty' },
      { value: 'limited', label: 'Limited warranty' },
      { value: 'none', label: 'No warranty' },
    ],
    required: false,
    section: 'Warranties',
    conditional: {
      field: 'warrantyOffered',
      value: [true],
    },
  },
  {
    id: 'warrantyPeriod',
    type: 'text',
    label: 'Warranty Period',
    placeholder: 'e.g., 1 year, 90 days',
    required: false,
    section: 'Warranties',
    conditional: {
      field: 'warrantyOffered',
      value: [true],
    },
  },
  {
    id: 'warrantyTerms',
    type: 'textarea',
    label: 'Warranty Terms',
    placeholder: 'Describe warranty coverage and limitations',
    required: false,
    section: 'Warranties',
    conditional: {
      field: 'warrantyOffered',
      value: [true],
    },
  },
  {
    id: 'asIsClause',
    type: 'radio',
    label: 'Include "As-Is" clause?',
    options: [
      { value: true, label: 'Yes, goods sold "as-is"' },
      { value: false, label: 'No "as-is" clause' },
    ],
    required: true,
    section: 'Warranties',
  },

  // Title and Ownership
  {
    id: 'titleTransfer',
    type: 'select',
    label: 'When does title transfer?',
    options: [
      { value: 'delivery', label: 'Upon delivery' },
      { value: 'payment', label: 'Upon payment' },
      { value: 'acceptance', label: 'Upon acceptance' },
    ],
    required: true,
    section: 'Title Transfer',
  },
  {
    id: 'titleWarranty',
    type: 'radio',
    label: 'Seller warrants clear title?',
    options: [
      { value: true, label: 'Yes, seller warrants clear title' },
      { value: false, label: 'No title warranty' },
    ],
    required: true,
    section: 'Title Transfer',
  },
  {
    id: 'lienDisclosure',
    type: 'radio',
    label: 'Are there any liens on the goods?',
    options: [
      { value: true, label: 'Yes, liens exist' },
      { value: false, label: 'No liens' },
    ],
    required: true,
    section: 'Title Transfer',
  },
  {
    id: 'encumbranceDisclosure',
    type: 'textarea',
    label: 'Lien/Encumbrance Details',
    placeholder: 'Describe any liens or encumbrances',
    required: false,
    section: 'Title Transfer',
    conditional: {
      field: 'lienDisclosure',
      value: [true],
    },
  },

  // Return and Exchange
  {
    id: 'returnPolicy',
    type: 'radio',
    label: 'Return policy included?',
    options: [
      { value: true, label: 'Yes, returns are allowed' },
      { value: false, label: 'No returns allowed' },
    ],
    required: true,
    section: 'Returns',
  },
  {
    id: 'returnPeriod',
    type: 'text',
    label: 'Return Period',
    placeholder: 'e.g., 30 days, 14 days',
    required: false,
    section: 'Returns',
    conditional: {
      field: 'returnPolicy',
      value: [true],
    },
  },
  {
    id: 'returnConditions',
    type: 'textarea',
    label: 'Return Conditions',
    placeholder: 'Describe conditions for returns',
    required: false,
    section: 'Returns',
    conditional: {
      field: 'returnPolicy',
      value: [true],
    },
  },
  {
    id: 'restockingFee',
    type: 'currency',
    label: 'Restocking Fee (if applicable)',
    placeholder: 'Enter restocking fee amount',
    required: false,
    section: 'Returns',
    conditional: {
      field: 'returnPolicy',
      value: [true],
    },
  },

  // Taxes and Fees
  {
    id: 'salesTaxResponsibility',
    type: 'select',
    label: 'Who pays sales tax?',
    options: [
      { value: 'seller', label: 'Seller pays sales tax' },
      { value: 'buyer', label: 'Buyer pays sales tax' },
    ],
    required: true,
    section: 'Taxes and Fees',
  },
  {
    id: 'otherTaxes',
    type: 'textarea',
    label: 'Other Taxes (if applicable)',
    placeholder: 'Describe any other applicable taxes',
    required: false,
    section: 'Taxes and Fees',
  },
  {
    id: 'additionalFees',
    type: 'textarea',
    label: 'Additional Fees (if applicable)',
    placeholder: 'Describe any additional fees',
    required: false,
    section: 'Taxes and Fees',
  },

  // Governing Law
  {
    id: 'governingState',
    type: 'select',
    label: 'Governing State Law',
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AK', label: 'Alaska' },
      { value: 'AZ', label: 'Arizona' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'CA', label: 'California' },
      { value: 'CO', label: 'Colorado' },
      { value: 'CT', label: 'Connecticut' },
      { value: 'DE', label: 'Delaware' },
      { value: 'FL', label: 'Florida' },
      { value: 'GA', label: 'Georgia' },
      { value: 'HI', label: 'Hawaii' },
      { value: 'ID', label: 'Idaho' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IN', label: 'Indiana' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'ME', label: 'Maine' },
      { value: 'MD', label: 'Maryland' },
      { value: 'MA', label: 'Massachusetts' },
      { value: 'MI', label: 'Michigan' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NV', label: 'Nevada' },
      { value: 'NH', label: 'New Hampshire' },
      { value: 'NJ', label: 'New Jersey' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'NY', label: 'New York' },
      { value: 'NC', label: 'North Carolina' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'OH', label: 'Ohio' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'OR', label: 'Oregon' },
      { value: 'PA', label: 'Pennsylvania' },
      { value: 'RI', label: 'Rhode Island' },
      { value: 'SC', label: 'South Carolina' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'TX', label: 'Texas' },
      { value: 'UT', label: 'Utah' },
      { value: 'VT', label: 'Vermont' },
      { value: 'VA', label: 'Virginia' },
      { value: 'WA', label: 'Washington' },
      { value: 'WV', label: 'West Virginia' },
      { value: 'WI', label: 'Wisconsin' },
      { value: 'WY', label: 'Wyoming' },
    ],
    required: true,
    section: 'Legal Terms',
  },
  {
    id: 'disputeResolution',
    type: 'select',
    label: 'Dispute Resolution',
    options: [
      { value: 'courts', label: 'Court litigation' },
      { value: 'arbitration', label: 'Binding arbitration' },
      { value: 'mediation', label: 'Mediation first, then courts' },
    ],
    required: true,
    section: 'Legal Terms',
  },

  // Contract Terms
  {
    id: 'contractDate',
    type: 'date',
    label: 'Contract Date',
    required: true,
    section: 'Contract Terms',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Effective Date',
    required: true,
    section: 'Contract Terms',
  },
  {
    id: 'expirationDate',
    type: 'date',
    label: 'Expiration Date (if applicable)',
    required: false,
    section: 'Contract Terms',
  },

  // Additional Terms
  {
    id: 'additionalTerms',
    type: 'textarea',
    label: 'Additional Terms',
    placeholder: 'Enter any additional terms or conditions',
    required: false,
    section: 'Additional Terms',
  },
  {
    id: 'specialConditions',
    type: 'textarea',
    label: 'Special Conditions',
    placeholder: 'Enter any special conditions',
    required: false,
    section: 'Additional Terms',
  },
  {
    id: 'attachments',
    type: 'textarea',
    label: 'Attachments/Exhibits',
    placeholder: 'List any attachments or exhibits',
    required: false,
    section: 'Additional Terms',
  },

  // Signatures
  {
    id: 'witnessRequired',
    type: 'radio',
    label: 'Witnesses required?',
    options: [
      { value: true, label: 'Yes, witnesses required' },
      { value: false, label: 'No witnesses required' },
    ],
    required: true,
    section: 'Signatures',
  },
  {
    id: 'witnessName',
    type: 'text',
    label: 'Witness Name',
    placeholder: 'Enter witness name',
    required: false,
    section: 'Signatures',
    conditional: {
      field: 'witnessRequired',
      value: [true],
    },
  },
  {
    id: 'notaryRequired',
    type: 'radio',
    label: 'Notarization required?',
    options: [
      { value: true, label: 'Yes, notarization required' },
      { value: false, label: 'No notarization required' },
    ],
    required: true,
    section: 'Signatures',
  },
];
