name: Test Coverage

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: Coverage Summary
        run: |
          echo "## Test Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo "$(cat coverage/coverage-summary.json | jq -r '.total | "- **Lines**: \(.lines.pct)% (\(.lines.covered)/\(.lines.total))"')" >> $GITHUB_STEP_SUMMARY
          echo "$(cat coverage/coverage-summary.json | jq -r '.total | "- **Functions**: \(.functions.pct)% (\(.functions.covered)/\(.functions.total))"')" >> $GITHUB_STEP_SUMMARY
          echo "$(cat coverage/coverage-summary.json | jq -r '.total | "- **Branches**: \(.branches.pct)% (\(.branches.covered)/\(.branches.total))"')" >> $GITHUB_STEP_SUMMARY
          echo "$(cat coverage/coverage-summary.json | jq -r '.total | "- **Statements**: \(.statements.pct)% (\(.statements.covered)/\(.statements.total))"')" >> $GITHUB_STEP_SUMMARY
