// src/lib/documents/us/equipment-rental-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const equipmentRentalAgreementQuestions: FormQuestion[] = [
  // Lessor Information
  {
    id: 'lessorName',
    type: 'text',
    label: 'Equipment Owner Full Name',
    placeholder: 'Enter the equipment owner\'s full name',
    required: true,
    group: 'lessor',
  },
  {
    id: 'lessorCompany',
    type: 'text',
    label: 'Owner Company Name (if applicable)',
    placeholder: 'Enter company name',
    required: false,
    group: 'lessor',
  },
  {
    id: 'lessorAddress',
    type: 'textarea',
    label: 'Owner Address',
    placeholder: 'Enter the owner\'s complete address',
    required: true,
    group: 'lessor',
  },
  {
    id: 'lessorPhone',
    type: 'tel',
    label: 'Owner Phone Number',
    placeholder: '(555) 123-4567',
    required: true,
    group: 'lessor',
  },
  {
    id: 'lessorEmail',
    type: 'email',
    label: 'Owner Email',
    placeholder: 'owner@example.com',
    required: true,
    group: 'lessor',
  },
  
  // Lessee Information
  {
    id: 'lesseeName',
    type: 'text',
    label: 'Renter Full Name',
    placeholder: 'Enter the renter\'s full name',
    required: true,
    group: 'lessee',
  },
  {
    id: 'lesseeCompany',
    type: 'text',
    label: 'Renter Company Name (if applicable)',
    placeholder: 'Enter company name',
    required: false,
    group: 'lessee',
  },
  {
    id: 'lesseeAddress',
    type: 'textarea',
    label: 'Renter Address',
    placeholder: 'Enter the renter\'s complete address',
    required: true,
    group: 'lessee',
  },
  {
    id: 'lesseePhone',
    type: 'tel',
    label: 'Renter Phone Number',
    placeholder: '(555) 123-4567',
    required: true,
    group: 'lessee',
  },
  {
    id: 'lesseeEmail',
    type: 'email',
    label: 'Renter Email',
    placeholder: 'renter@example.com',
    required: true,
    group: 'lessee',
  },
  {
    id: 'lesseeDriverLicense',
    type: 'text',
    label: 'Renter Driver\'s License Number',
    placeholder: 'Enter driver\'s license number',
    required: false,
    group: 'lessee',
  },
  
  // Equipment Details
  {
    id: 'equipmentType',
    type: 'text',
    label: 'Equipment Type',
    placeholder: 'e.g., Excavator, Generator, Forklift',
    required: true,
    group: 'equipment',
  },
  {
    id: 'equipmentMake',
    type: 'text',
    label: 'Equipment Make/Manufacturer',
    placeholder: 'e.g., Caterpillar, John Deere',
    required: false,
    group: 'equipment',
  },
  {
    id: 'equipmentModel',
    type: 'text',
    label: 'Equipment Model',
    placeholder: 'Enter model number',
    required: false,
    group: 'equipment',
  },
  {
    id: 'equipmentSerialNumber',
    type: 'text',
    label: 'Serial Number',
    placeholder: 'Enter equipment serial number',
    required: false,
    group: 'equipment',
  },
  {
    id: 'equipmentYear',
    type: 'text',
    label: 'Equipment Year',
    placeholder: 'e.g., 2023',
    required: false,
    group: 'equipment',
  },
  {
    id: 'equipmentDescription',
    type: 'textarea',
    label: 'Equipment Description',
    placeholder: 'Describe the equipment, including any accessories or attachments',
    required: true,
    group: 'equipment',
  },
  {
    id: 'equipmentValue',
    type: 'number',
    label: 'Equipment Value ($)',
    placeholder: '5000',
    required: true,
    group: 'equipment',
  },
  {
    id: 'equipmentCondition',
    type: 'select',
    label: 'Equipment Condition',
    options: [
      { value: 'excellent', label: 'Excellent' },
      { value: 'good', label: 'Good' },
      { value: 'fair', label: 'Fair' },
      { value: 'poor', label: 'Poor' },
    ],
    required: true,
    group: 'equipment',
  },
  
  // Rental Terms
  {
    id: 'rentalStartDate',
    type: 'date',
    label: 'Rental Start Date',
    required: true,
    group: 'terms',
  },
  {
    id: 'rentalEndDate',
    type: 'date',
    label: 'Rental End Date',
    required: true,
    group: 'terms',
  },
  {
    id: 'rentalPeriod',
    type: 'select',
    label: 'Rental Period Type',
    options: [
      { value: 'hourly', label: 'Hourly' },
      { value: 'daily', label: 'Daily' },
      { value: 'weekly', label: 'Weekly' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'custom', label: 'Custom Period' },
    ],
    required: true,
    group: 'terms',
  },
  {
    id: 'deliveryRequired',
    type: 'checkbox',
    label: 'Delivery Required',
    required: false,
    group: 'terms',
  },
  {
    id: 'deliveryAddress',
    type: 'textarea',
    label: 'Delivery Address',
    placeholder: 'Enter delivery address',
    required: false,
    group: 'terms',
    dependsOn: 'deliveryRequired',
  },
  {
    id: 'pickupRequired',
    type: 'checkbox',
    label: 'Pickup Required',
    required: false,
    group: 'terms',
  },
  
  // Financial Terms
  {
    id: 'rentalRate',
    type: 'number',
    label: 'Rental Rate ($)',
    placeholder: '100',
    required: true,
    group: 'financial',
  },
  {
    id: 'securityDeposit',
    type: 'number',
    label: 'Security Deposit ($)',
    placeholder: '500',
    required: true,
    group: 'financial',
  },
  {
    id: 'paymentFrequency',
    type: 'select',
    label: 'Payment Frequency',
    options: [
      { value: 'advance', label: 'In Advance' },
      { value: 'weekly', label: 'Weekly' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'upon-return', label: 'Upon Return' },
    ],
    required: true,
    group: 'financial',
  },
  {
    id: 'paymentMethod',
    type: 'select',
    label: 'Payment Method',
    options: [
      { value: 'cash', label: 'Cash' },
      { value: 'check', label: 'Check' },
      { value: 'credit-card', label: 'Credit Card' },
      { value: 'bank-transfer', label: 'Bank Transfer' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'financial',
  },
  {
    id: 'lateFeePerDay',
    type: 'number',
    label: 'Late Fee Per Day ($)',
    placeholder: '50',
    required: true,
    group: 'financial',
  },
  
  // Insurance and Liability
  {
    id: 'insuranceRequired',
    type: 'checkbox',
    label: 'Insurance Required',
    required: false,
    group: 'insurance',
  },
  {
    id: 'insuranceProvider',
    type: 'text',
    label: 'Insurance Provider',
    placeholder: 'Enter insurance company name',
    required: false,
    group: 'insurance',
    dependsOn: 'insuranceRequired',
  },
  {
    id: 'insurancePolicyNumber',
    type: 'text',
    label: 'Insurance Policy Number',
    placeholder: 'Enter policy number',
    required: false,
    group: 'insurance',
    dependsOn: 'insuranceRequired',
  },
  {
    id: 'liabilityLimit',
    type: 'number',
    label: 'Liability Limit ($)',
    placeholder: '10000',
    required: false,
    group: 'insurance',
  },
  {
    id: 'damageWaiver',
    type: 'checkbox',
    label: 'Damage Waiver Available',
    required: false,
    group: 'insurance',
  },
  {
    id: 'damageWaiverFee',
    type: 'number',
    label: 'Damage Waiver Fee ($)',
    placeholder: '100',
    required: false,
    group: 'insurance',
    dependsOn: 'damageWaiver',
  },
  
  // Operating Conditions
  {
    id: 'authorizedOperators',
    type: 'textarea',
    label: 'Authorized Operators',
    placeholder: 'List names of authorized operators',
    required: false,
    group: 'operations',
  },
  {
    id: 'operatorCertificationRequired',
    type: 'checkbox',
    label: 'Operator Certification Required',
    required: false,
    group: 'operations',
  },
  {
    id: 'usageRestrictions',
    type: 'textarea',
    label: 'Usage Restrictions',
    placeholder: 'Describe any restrictions on equipment use',
    required: false,
    group: 'operations',
  },
  {
    id: 'geographicRestrictions',
    type: 'text',
    label: 'Geographic Restrictions',
    placeholder: 'e.g., Within 50 miles of rental location',
    required: false,
    group: 'operations',
  },
  {
    id: 'maintenanceResponsibility',
    type: 'select',
    label: 'Maintenance Responsibility',
    options: [
      { value: 'lessor', label: 'Owner' },
      { value: 'lessee', label: 'Renter' },
      { value: 'shared', label: 'Shared' },
    ],
    required: true,
    group: 'operations',
  },
  
  // Additional Terms
  {
    id: 'fuelPolicy',
    type: 'select',
    label: 'Fuel Policy',
    options: [
      { value: 'full-to-full', label: 'Full to Full' },
      { value: 'lessee-pays', label: 'Renter Pays for Fuel' },
      { value: 'included', label: 'Fuel Included' },
      { value: 'not-applicable', label: 'Not Applicable' },
    ],
    required: false,
    group: 'additional',
  },
  {
    id: 'cleaningRequired',
    type: 'checkbox',
    label: 'Equipment Must Be Returned Clean',
    required: false,
    group: 'additional',
  },
  {
    id: 'normalWearAndTear',
    type: 'checkbox',
    label: 'Normal Wear and Tear Accepted',
    required: false,
    group: 'additional',
  },
  {
    id: 'subleaseAllowed',
    type: 'checkbox',
    label: 'Sublease Allowed',
    required: false,
    group: 'additional',
  },
  {
    id: 'earlyTerminationAllowed',
    type: 'checkbox',
    label: 'Early Termination Allowed',
    required: false,
    group: 'additional',
  },
  {
    id: 'earlyTerminationFee',
    type: 'number',
    label: 'Early Termination Fee ($)',
    placeholder: '200',
    required: false,
    group: 'additional',
    dependsOn: 'earlyTerminationAllowed',
  },
  
  // Special Conditions
  {
    id: 'specialConditions',
    type: 'textarea',
    label: 'Special Conditions',
    placeholder: 'Enter any special conditions or requirements',
    required: false,
    group: 'special',
  },
  {
    id: 'prohibitedUses',
    type: 'textarea',
    label: 'Prohibited Uses',
    placeholder: 'List any prohibited uses of the equipment',
    required: false,
    group: 'special',
  },
  {
    id: 'requiredPermits',
    type: 'text',
    label: 'Required Permits',
    placeholder: 'List any permits required for operation',
    required: false,
    group: 'special',
  },
  
  // Emergency Contact
  {
    id: 'emergencyContactName',
    type: 'text',
    label: 'Emergency Contact Name',
    placeholder: 'Enter emergency contact name',
    required: false,
    group: 'emergency',
  },
  {
    id: 'emergencyContactPhone',
    type: 'tel',
    label: 'Emergency Contact Phone',
    placeholder: '(555) 123-4567',
    required: false,
    group: 'emergency',
  },
];