// src/lib/documents/us/settlement-agreement/questions.ts
import type { FormQuestion } from '@/types/documents';

export const settlementAgreementQuestions: FormQuestion[] = [
  {
    id: 'party1Name',
    type: 'text',
    label: 'Party 1 Name',
    placeholder: 'Enter first party name',
    required: true,
    group: 'parties',
  },
  {
    id: 'party1Address',
    type: 'text',
    label: 'Party 1 Address',
    placeholder: 'Enter complete address',
    required: true,
    group: 'parties',
  },
  {
    id: 'party1Type',
    type: 'select',
    label: 'Party 1 Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'business', label: 'Business' },
      { value: 'organization', label: 'Organization' },
      { value: 'government', label: 'Government Entity' },
    ],
    required: true,
    group: 'parties',
  },
  {
    id: 'party1Representative',
    type: 'text',
    label: 'Party 1 Representative',
    placeholder: 'Attorney or representative name',
    required: false,
    group: 'parties',
  },
  {
    id: 'party2Name',
    type: 'text',
    label: 'Party 2 Name',
    placeholder: 'Enter second party name',
    required: true,
    group: 'parties',
  },
  {
    id: 'party2Address',
    type: 'text',
    label: 'Party 2 Address',
    placeholder: 'Enter complete address',
    required: true,
    group: 'parties',
  },
  {
    id: 'party2Type',
    type: 'select',
    label: 'Party 2 Type',
    options: [
      { value: 'individual', label: 'Individual' },
      { value: 'business', label: 'Business' },
      { value: 'organization', label: 'Organization' },
      { value: 'government', label: 'Government Entity' },
    ],
    required: true,
    group: 'parties',
  },
  {
    id: 'party2Representative',
    type: 'text',
    label: 'Party 2 Representative',
    placeholder: 'Attorney or representative name',
    required: false,
    group: 'parties',
  },
  {
    id: 'disputeDescription',
    type: 'textarea',
    label: 'Dispute Description',
    placeholder: 'Describe the nature of the dispute being settled',
    required: true,
    group: 'dispute',
  },
  {
    id: 'disputeType',
    type: 'select',
    label: 'Dispute Type',
    options: [
      { value: 'contract', label: 'Contract Dispute' },
      { value: 'tort', label: 'Tort Claim' },
      { value: 'employment', label: 'Employment Dispute' },
      { value: 'personal-injury', label: 'Personal Injury' },
      { value: 'property', label: 'Property Dispute' },
      { value: 'commercial', label: 'Commercial Dispute' },
      { value: 'family', label: 'Family Law' },
      { value: 'other', label: 'Other' },
    ],
    required: true,
    group: 'dispute',
  },
  {
    id: 'disputeOriginDate',
    type: 'text',
    label: 'Dispute Origin Date',
    placeholder: 'When did the dispute arise?',
    required: false,
    group: 'dispute',
  },
  {
    id: 'litigationStatus',
    type: 'select',
    label: 'Litigation Status',
    options: [
      { value: 'no-litigation', label: 'No Litigation Filed' },
      { value: 'pending-litigation', label: 'Litigation Pending' },
      { value: 'resolved-litigation', label: 'Litigation Resolved' },
      { value: 'threatened-litigation', label: 'Litigation Threatened' },
    ],
    required: true,
    group: 'dispute',
  },
  {
    id: 'caseNumber',
    type: 'text',
    label: 'Case Number',
    placeholder: 'Court case number if applicable',
    required: false,
    group: 'dispute',
    dependsOn: 'litigationStatus',
  },
  {
    id: 'court',
    type: 'text',
    label: 'Court',
    placeholder: 'Name of court if applicable',
    required: false,
    group: 'dispute',
    dependsOn: 'litigationStatus',
  },
  {
    id: 'settlementAmount',
    type: 'text',
    label: 'Settlement Amount',
    placeholder: 'Total monetary settlement amount',
    required: false,
    group: 'settlement-terms',
  },
  {
    id: 'paymentStructure',
    type: 'select',
    label: 'Payment Structure',
    options: [
      { value: 'lump-sum', label: 'Lump Sum Payment' },
      { value: 'installments', label: 'Installment Payments' },
      { value: 'performance-based', label: 'Performance-Based Payment' },
      { value: 'non-monetary', label: 'Non-Monetary Settlement' },
    ],
    required: true,
    group: 'settlement-terms',
  },
  {
    id: 'installmentSchedule',
    type: 'textarea',
    label: 'Installment Schedule',
    placeholder: 'Describe payment schedule if installments',
    required: false,
    group: 'settlement-terms',
    dependsOn: 'paymentStructure',
  },
  {
    id: 'paymentDeadline',
    type: 'text',
    label: 'Payment Deadline',
    placeholder: 'When must payment be made?',
    required: false,
    group: 'settlement-terms',
  },
  {
    id: 'paymentMethod',
    type: 'text',
    label: 'Payment Method',
    placeholder: 'How will payment be made?',
    required: false,
    group: 'settlement-terms',
  },
  {
    id: 'interestOnLatePayment',
    type: 'checkbox',
    label: 'Include interest on late payment',
    required: false,
    group: 'settlement-terms',
  },
  {
    id: 'defaultConsequences',
    type: 'text',
    label: 'Default Consequences',
    placeholder: 'What happens if payment defaults?',
    required: false,
    group: 'settlement-terms',
  },
  {
    id: 'nonMonetaryTerms',
    type: 'multiselect',
    label: 'Non-Monetary Terms',
    options: [
      { value: 'apology', label: 'Apology' },
      { value: 'policy-changes', label: 'Policy Changes' },
      { value: 'training', label: 'Training Programs' },
      { value: 'compliance-monitoring', label: 'Compliance Monitoring' },
      { value: 'performance-obligations', label: 'Performance Obligations' },
      { value: 'future-conduct', label: 'Future Conduct Requirements' },
    ],
    required: false,
    group: 'settlement-terms',
  },
  {
    id: 'performanceObligations',
    type: 'textarea',
    label: 'Performance Obligations',
    placeholder: 'Describe any performance obligations',
    required: false,
    group: 'settlement-terms',
  },
  {
    id: 'deliverables',
    type: 'text',
    label: 'Deliverables',
    placeholder: 'What must be delivered?',
    required: false,
    group: 'settlement-terms',
  },
  {
    id: 'timeframeForPerformance',
    type: 'text',
    label: 'Performance Timeframe',
    placeholder: 'When must performance be completed?',
    required: false,
    group: 'settlement-terms',
  },
  {
    id: 'releaseScope',
    type: 'select',
    label: 'Release Scope',
    options: [
      { value: 'specific-claims', label: 'Specific Claims Only' },
      { value: 'all-claims', label: 'All Claims' },
      { value: 'known-claims', label: 'Known Claims Only' },
      { value: 'broad-release', label: 'Broad General Release' },
    ],
    required: true,
    group: 'release',
  },
  {
    id: 'releasedClaims',
    type: 'multiselect',
    label: 'Released Claims',
    options: [
      { value: 'breach-of-contract', label: 'Breach of Contract' },
      { value: 'negligence', label: 'Negligence' },
      { value: 'fraud', label: 'Fraud' },
      { value: 'discrimination', label: 'Discrimination' },
      { value: 'personal-injury', label: 'Personal Injury' },
      { value: 'property-damage', label: 'Property Damage' },
      { value: 'defamation', label: 'Defamation' },
      { value: 'employment-claims', label: 'Employment Claims' },
    ],
    required: false,
    group: 'release',
  },
  {
    id: 'releasedParties',
    type: 'multiselect',
    label: 'Released Parties',
    options: [
      { value: 'employees', label: 'Employees' },
      { value: 'officers', label: 'Officers' },
      { value: 'directors', label: 'Directors' },
      { value: 'agents', label: 'Agents' },
      { value: 'attorneys', label: 'Attorneys' },
      { value: 'insurers', label: 'Insurers' },
      { value: 'subsidiaries', label: 'Subsidiaries' },
      { value: 'affiliates', label: 'Affiliates' },
    ],
    required: false,
    group: 'release',
  },
  {
    id: 'releasePeriod',
    type: 'select',
    label: 'Release Period',
    options: [
      { value: 'all-time', label: 'All Time Periods' },
      { value: 'specific-period', label: 'Specific Time Period' },
      { value: 'up-to-date', label: 'Up to Settlement Date' },
    ],
    required: true,
    group: 'release',
  },
  {
    id: 'unknownClaimsWaiver',
    type: 'checkbox',
    label: 'Waive unknown claims',
    required: false,
    group: 'release',
  },
  {
    id: 'futureClaimsReservation',
    type: 'checkbox',
    label: 'Reserve future claims',
    required: false,
    group: 'release',
  },
  {
    id: 'mutualRelease',
    type: 'checkbox',
    label: 'Mutual release (both parties release each other)',
    required: false,
    group: 'release-type',
  },
  {
    id: 'unilateralRelease',
    type: 'checkbox',
    label: 'Unilateral release (one party releases the other)',
    required: false,
    group: 'release-type',
  },
  {
    id: 'releasingParty',
    type: 'text',
    label: 'Releasing Party',
    placeholder: 'Who is giving the release?',
    required: false,
    group: 'release-type',
    dependsOn: 'unilateralRelease',
  },
  {
    id: 'releasedParty',
    type: 'text',
    label: 'Released Party',
    placeholder: 'Who is being released?',
    required: false,
    group: 'release-type',
    dependsOn: 'unilateralRelease',
  },
  {
    id: 'dismissWithPrejudice',
    type: 'checkbox',
    label: 'Dismiss with prejudice',
    required: false,
    group: 'litigation-dismissal',
  },
  {
    id: 'dismissWithoutPrejudice',
    type: 'checkbox',
    label: 'Dismiss without prejudice',
    required: false,
    group: 'litigation-dismissal',
  },
  {
    id: 'courtDismissal',
    type: 'checkbox',
    label: 'Court dismissal required',
    required: false,
    group: 'litigation-dismissal',
  },
  {
    id: 'stipulatedDismissal',
    type: 'checkbox',
    label: 'Stipulated dismissal',
    required: false,
    group: 'litigation-dismissal',
  },
  {
    id: 'dismissalDeadline',
    type: 'text',
    label: 'Dismissal Deadline',
    placeholder: 'When must dismissal be filed?',
    required: false,
    group: 'litigation-dismissal',
  },
  {
    id: 'confidentialityClause',
    type: 'checkbox',
    label: 'Include confidentiality clause',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'nonDisclosureTerms',
    type: 'textarea',
    label: 'Non-Disclosure Terms',
    placeholder: 'Describe confidentiality requirements',
    required: false,
    group: 'confidentiality',
    dependsOn: 'confidentialityClause',
  },
  {
    id: 'publicDisclosureAllowed',
    type: 'checkbox',
    label: 'Allow public disclosure',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'mediaStatements',
    type: 'text',
    label: 'Media Statements',
    placeholder: 'Agreed statement for media if applicable',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'confidentialityDuration',
    type: 'text',
    label: 'Confidentiality Duration',
    placeholder: 'How long does confidentiality last?',
    required: false,
    group: 'confidentiality',
  },
  {
    id: 'nonAdmissionClause',
    type: 'checkbox',
    label: 'Include non-admission clause',
    required: false,
    group: 'non-admission',
  },
  {
    id: 'noAdmissionOfLiability',
    type: 'checkbox',
    label: 'No admission of liability',
    required: false,
    group: 'non-admission',
  },
  {
    id: 'noAdmissionOfWrongdoing',
    type: 'checkbox',
    label: 'No admission of wrongdoing',
    required: false,
    group: 'non-admission',
  },
  {
    id: 'settlementNotEvidence',
    type: 'checkbox',
    label: 'Settlement not evidence of liability',
    required: false,
    group: 'non-admission',
  },
  {
    id: 'futureCooperation',
    type: 'checkbox',
    label: 'Include future cooperation provision',
    required: false,
    group: 'cooperation',
  },
  {
    id: 'cooperationScope',
    type: 'text',
    label: 'Cooperation Scope',
    placeholder: 'Describe cooperation requirements',
    required: false,
    group: 'cooperation',
    dependsOn: 'futureCooperation',
  },
  {
    id: 'informationSharing',
    type: 'checkbox',
    label: 'Require information sharing',
    required: false,
    group: 'cooperation',
  },
  {
    id: 'documentPreservation',
    type: 'checkbox',
    label: 'Require document preservation',
    required: false,
    group: 'cooperation',
  },
  {
    id: 'testimonyCooperation',
    type: 'checkbox',
    label: 'Require testimony cooperation',
    required: false,
    group: 'cooperation',
  },
  {
    id: 'complianceReporting',
    type: 'checkbox',
    label: 'Include compliance reporting',
    required: false,
    group: 'compliance',
  },
  {
    id: 'monitoringProcedures',
    type: 'text',
    label: 'Monitoring Procedures',
    placeholder: 'How will compliance be monitored?',
    required: false,
    group: 'compliance',
  },
  {
    id: 'auditRights',
    type: 'checkbox',
    label: 'Include audit rights',
    required: false,
    group: 'compliance',
  },
  {
    id: 'recordKeeping',
    type: 'checkbox',
    label: 'Require record keeping',
    required: false,
    group: 'compliance',
  },
  {
    id: 'thirdPartyBeneficiaries',
    type: 'checkbox',
    label: 'Include third-party beneficiaries',
    required: false,
    group: 'third-parties',
  },
  {
    id: 'thirdPartyReleases',
    type: 'checkbox',
    label: 'Include third-party releases',
    required: false,
    group: 'third-parties',
  },
  {
    id: 'insuranceAssignment',
    type: 'checkbox',
    label: 'Include insurance assignment',
    required: false,
    group: 'third-parties',
  },
  {
    id: 'subrogationWaiver',
    type: 'checkbox',
    label: 'Include subrogation waiver',
    required: false,
    group: 'third-parties',
  },
  {
    id: 'taxTreatment',
    type: 'text',
    label: 'Tax Treatment',
    placeholder: 'How should settlement be treated for tax purposes?',
    required: false,
    group: 'tax',
  },
  {
    id: 'taxReporting',
    type: 'checkbox',
    label: 'Include tax reporting obligations',
    required: false,
    group: 'tax',
  },
  {
    id: 'form1099Issuance',
    type: 'checkbox',
    label: 'Require Form 1099 issuance',
    required: false,
    group: 'tax',
  },
  {
    id: 'taxAdviceDisclaimer',
    type: 'checkbox',
    label: 'Include tax advice disclaimer',
    required: false,
    group: 'tax',
  },
  {
    id: 'enforcementMechanism',
    type: 'text',
    label: 'Enforcement Mechanism',
    placeholder: 'How will agreement be enforced?',
    required: false,
    group: 'enforcement',
  },
  {
    id: 'breachRemedies',
    type: 'multiselect',
    label: 'Breach Remedies',
    options: [
      { value: 'monetary-damages', label: 'Monetary Damages' },
      { value: 'specific-performance', label: 'Specific Performance' },
      { value: 'injunctive-relief', label: 'Injunctive Relief' },
      { value: 'return-of-settlement', label: 'Return of Settlement' },
      { value: 'attorney-fees', label: 'Attorney Fees' },
      { value: 'liquidated-damages', label: 'Liquidated Damages' },
    ],
    required: false,
    group: 'enforcement',
  },
  {
    id: 'specificPerformance',
    type: 'checkbox',
    label: 'Allow specific performance',
    required: false,
    group: 'enforcement',
  },
  {
    id: 'injunctiveRelief',
    type: 'checkbox',
    label: 'Allow injunctive relief',
    required: false,
    group: 'enforcement',
  },
  {
    id: 'liquidatedDamages',
    type: 'checkbox',
    label: 'Include liquidated damages',
    required: false,
    group: 'enforcement',
  },
  {
    id: 'attorneyFeesClause',
    type: 'checkbox',
    label: 'Include attorney fees clause',
    required: false,
    group: 'enforcement',
  },
  {
    id: 'disputeResolutionMethod',
    type: 'select',
    label: 'Dispute Resolution for This Agreement',
    options: [
      { value: 'litigation', label: 'Court Litigation' },
      { value: 'arbitration', label: 'Arbitration' },
      { value: 'mediation', label: 'Mediation' },
      { value: 'negotiation', label: 'Negotiation' },
    ],
    required: false,
    group: 'agreement-disputes',
  },
  {
    id: 'arbitrationClause',
    type: 'checkbox',
    label: 'Include arbitration clause',
    required: false,
    group: 'agreement-disputes',
  },
  {
    id: 'mediationFirst',
    type: 'checkbox',
    label: 'Require mediation first',
    required: false,
    group: 'agreement-disputes',
  },
  {
    id: 'jurisdiction',
    type: 'text',
    label: 'Jurisdiction',
    placeholder: 'Which court has jurisdiction?',
    required: false,
    group: 'agreement-disputes',
  },
  {
    id: 'venue',
    type: 'text',
    label: 'Venue',
    placeholder: 'Where will disputes be resolved?',
    required: false,
    group: 'agreement-disputes',
  },
  {
    id: 'governingLaw',
    type: 'text',
    label: 'Governing Law',
    placeholder: 'e.g., State of California',
    required: false,
    group: 'agreement-disputes',
  },
  {
    id: 'modificationRequirements',
    type: 'select',
    label: 'Modification Requirements',
    options: [
      { value: 'written-only', label: 'Written Modification Only' },
      { value: 'mutual-consent', label: 'Mutual Consent Required' },
      { value: 'specific-process', label: 'Specific Process Required' },
    ],
    required: true,
    group: 'modification',
  },
  {
    id: 'noOralModification',
    type: 'checkbox',
    label: 'Prohibit oral modifications',
    required: false,
    group: 'modification',
  },
  {
    id: 'signedModificationRequired',
    type: 'checkbox',
    label: 'Require signed modifications',
    required: false,
    group: 'modification',
  },
  {
    id: 'authorityRepresentation',
    type: 'checkbox',
    label: 'Include authority representation',
    required: false,
    group: 'representations',
  },
  {
    id: 'capacityRepresentation',
    type: 'checkbox',
    label: 'Include capacity representation',
    required: false,
    group: 'representations',
  },
  {
    id: 'noOtherAgreements',
    type: 'checkbox',
    label: 'Represent no other agreements exist',
    required: false,
    group: 'representations',
  },
  {
    id: 'materialFactsDisclosure',
    type: 'checkbox',
    label: 'Require material facts disclosure',
    required: false,
    group: 'representations',
  },
  {
    id: 'conditionsPrecedent',
    type: 'multiselect',
    label: 'Conditions Precedent',
    options: [
      { value: 'board-approval', label: 'Board Approval' },
      { value: 'regulatory-approval', label: 'Regulatory Approval' },
      { value: 'court-approval', label: 'Court Approval' },
      { value: 'insurance-approval', label: 'Insurance Approval' },
      { value: 'due-diligence', label: 'Due Diligence Completion' },
      { value: 'documentation', label: 'Documentation Completion' },
    ],
    required: false,
    group: 'conditions',
  },
  {
    id: 'bindingOnSuccessors',
    type: 'checkbox',
    label: 'Binding on successors and assigns',
    required: false,
    group: 'successors',
  },
  {
    id: 'assignmentRights',
    type: 'checkbox',
    label: 'Allow assignment rights',
    required: false,
    group: 'successors',
  },
  {
    id: 'noticeRequirements',
    type: 'text',
    label: 'Notice Requirements',
    placeholder: 'How must notices be given?',
    required: false,
    group: 'notices',
  },
  {
    id: 'noticeMethod',
    type: 'multiselect',
    label: 'Notice Methods',
    options: [
      { value: 'certified-mail', label: 'Certified Mail' },
      { value: 'personal-delivery', label: 'Personal Delivery' },
      { value: 'overnight-delivery', label: 'Overnight Delivery' },
      { value: 'email', label: 'Email' },
      { value: 'fax', label: 'Fax' },
    ],
    required: false,
    group: 'notices',
  },
  {
    id: 'electronicNotice',
    type: 'checkbox',
    label: 'Allow electronic notice',
    required: false,
    group: 'notices',
  },
  {
    id: 'entireAgreement',
    type: 'checkbox',
    label: 'Include entire agreement clause',
    required: false,
    group: 'integration',
  },
  {
    id: 'supersedingEffect',
    type: 'checkbox',
    label: 'Supersedes prior agreements',
    required: false,
    group: 'integration',
  },
  {
    id: 'severabilityClause',
    type: 'checkbox',
    label: 'Include severability clause',
    required: false,
    group: 'severability',
  },
  {
    id: 'counterpartExecution',
    type: 'checkbox',
    label: 'Allow counterpart execution',
    required: false,
    group: 'execution',
  },
  {
    id: 'electronicSignatures',
    type: 'checkbox',
    label: 'Accept electronic signatures',
    required: false,
    group: 'execution',
  },
  {
    id: 'notarizationRequired',
    type: 'checkbox',
    label: 'Require notarization',
    required: false,
    group: 'execution',
  },
  {
    id: 'witnessRequired',
    type: 'checkbox',
    label: 'Require witness',
    required: false,
    group: 'execution',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Effective Date',
    required: true,
    group: 'timing',
  },
  {
    id: 'termDuration',
    type: 'text',
    label: 'Term Duration',
    placeholder: 'How long does agreement last?',
    required: false,
    group: 'timing',
  },
  {
    id: 'perpetualAgreement',
    type: 'checkbox',
    label: 'Perpetual agreement',
    required: false,
    group: 'timing',
  },
  {
    id: 'requireAllPartySignatures',
    type: 'checkbox',
    label: 'Require all party signatures',
    required: false,
    group: 'signatures',
  },
  {
    id: 'authorizedSignatories',
    type: 'text',
    label: 'Authorized Signatories',
    placeholder: 'Who is authorized to sign?',
    required: false,
    group: 'signatures',
  },
  {
    id: 'corporateResolutions',
    type: 'checkbox',
    label: 'Require corporate resolutions',
    required: false,
    group: 'signatures',
  },
];
