// src/app/disclaimer/page.tsx
import React from 'react';

export default function DisclaimerPage() {
  return (
    <main className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-4">Disclaimer</h1>
      <div className="space-y-4 text-muted-foreground">
        <p>Effective Date: [Insert Date]</p>

        <h2 className="text-xl font-semibold text-foreground pt-4">
          No Attorney-Client Relationship
        </h2>
        <p>
          123LegalDoc is an AI-powered software service designed to assist users
          in identifying potential legal document needs and generating documents
          based on user-provided information.{' '}
          <strong>123LegalDoc is not a law firm.</strong>
          Use of our website, services, or any generated documents does not
          create an attorney-client relationship between you and 123LegalDoc,
          its owners, employees, or affiliates.
        </p>

        <h2 className="text-xl font-semibold text-foreground pt-4">
          Not Legal Advice
        </h2>
        <p>
          The information, suggestions, document templates, and generated
          documents provided by the Service are for informational and self-help
          purposes only. They <strong>do not constitute legal advice</strong>{' '}
          and should not be relied upon as such. The law is complex and varies
          by jurisdiction. The application of legal principles depends heavily
          on the specific facts of each situation.
        </p>
        <p>
          The AI&apos;s document type inference is a suggestion based on the
          limited information you provide and may not be accurate or appropriate
          for your specific circumstances. Documents generated by the Service
          are based on standard templates and the information you input; they
          may not cover all relevant legal issues or be suitable for your
          particular needs or jurisdiction.
        </p>

        <h2 className="text-xl font-semibold text-foreground pt-4">
          Consult a Qualified Attorney
        </h2>
        <p>
          We strongly recommend that you consult with a licensed attorney in
          your jurisdiction before making any decisions or taking any actions
          based on information or documents obtained through the Service. An
          attorney can review your specific situation, provide tailored legal
          advice, and ensure that any legal document accurately reflects your
          intentions and complies with applicable laws.
        </p>

        <h2 className="text-xl font-semibold text-foreground pt-4">
          No Guarantees or Warranties
        </h2>
        <p>
          While we strive to provide helpful tools, 123LegalDoc makes no
          representations or warranties regarding the accuracy, completeness,
          suitability, or legality of the information or documents provided
          through the Service. We disclaim all liability for any errors or
          omissions in the content provided and for any actions taken or not
          taken based on that content. Your use of the Service is entirely at
          your own risk.
        </p>

        <h2 className="text-xl font-semibold text-foreground pt-4">
          Third-Party Services
        </h2>
        <p>
          The Service may integrate with or rely on third-party services,
          including AI providers (e.g., Google Generative AI) and digital
          signature providers. We are not responsible for the performance,
          accuracy, or reliability of these third-party services. Your use of
          such services may be subject to their own terms and privacy policies.
        </p>
      </div>
    </main>
  );
}
