// src/lib/documents/us/notice-to-proceed/questions.ts
import type { FormQuestion } from '@/types/documents';

export const noticetoproceedQuestions: FormQuestion[] = [
  {
    id: 'noticeNumber',
    type: 'text',
    label: 'Notice Number',
    placeholder: 'Notice reference number',
    required: false,
    group: 'notice',
  },
  {
    id: 'noticeDate',
    type: 'date',
    label: 'Notice Date',
    required: true,
    group: 'notice',
  },
  {
    id: 'effectiveDate',
    type: 'date',
    label: 'Effective Date',
    required: true,
    group: 'notice',
  },
  {
    id: 'projectName',
    type: 'text',
    label: 'Project Name',
    placeholder: 'Enter project name',
    required: true,
    group: 'project',
  },
  {
    id: 'projectNumber',
    type: 'text',
    label: 'Project Number',
    placeholder: 'Project reference number',
    required: false,
    group: 'project',
  },
  {
    id: 'projectAddress',
    type: 'text',
    label: 'Project Address',
    placeholder: 'Complete project address',
    required: true,
    group: 'project',
  },
  {
    id: 'projectDescription',
    type: 'textarea',
    label: 'Project Description',
    placeholder: 'Detailed description of construction project',
    required: true,
    group: 'project',
  },
  {
    id: 'ownerName',
    type: 'text',
    label: 'Owner Name',
    placeholder: 'Property owner name',
    required: true,
    group: 'owner',
  },
  {
    id: 'ownerAddress',
    type: 'text',
    label: 'Owner Address',
    placeholder: 'Complete owner address',
    required: true,
    group: 'owner',
  },
  {
    id: 'ownerPhone',
    type: 'text',
    label: 'Owner Phone',
    placeholder: 'Contact phone number',
    required: false,
    group: 'owner',
  },
  {
    id: 'ownerEmail',
    type: 'email',
    label: 'Owner Email',
    placeholder: 'Contact email address',
    required: false,
    group: 'owner',
  },
  {
    id: 'ownerRepresentative',
    type: 'text',
    label: 'Owner Representative',
    placeholder: 'Authorized owner representative',
    required: false,
    group: 'owner',
  },
  {
    id: 'contractorName',
    type: 'text',
    label: 'Contractor Name',
    placeholder: 'General contractor name',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorAddress',
    type: 'text',
    label: 'Contractor Address',
    placeholder: 'Complete contractor address',
    required: true,
    group: 'contractor',
  },
  {
    id: 'contractorPhone',
    type: 'text',
    label: 'Contractor Phone',
    placeholder: 'Contractor phone number',
    required: false,
    group: 'contractor',
  },
  {
    id: 'contractorEmail',
    type: 'email',
    label: 'Contractor Email',
    placeholder: 'Contractor email address',
    required: false,
    group: 'contractor',
  },
  {
    id: 'contractorLicense',
    type: 'text',
    label: 'Contractor License Number',
    placeholder: 'State license number',
    required: false,
    group: 'contractor',
  },
  {
    id: 'architectName',
    type: 'text',
    label: 'Architect Name',
    placeholder: 'Project architect name',
    required: false,
    group: 'architect',
  },
  {
    id: 'architectAddress',
    type: 'text',
    label: 'Architect Address',
    placeholder: 'Architect office address',
    required: false,
    group: 'architect',
  },
  {
    id: 'contractDate',
    type: 'date',
    label: 'Contract Date',
    required: true,
    group: 'contract',
  },
  {
    id: 'contractAmount',
    type: 'text',
    label: 'Contract Amount',
    placeholder: 'Total contract amount',
    required: true,
    group: 'contract',
  },
  {
    id: 'contractNumber',
    type: 'text',
    label: 'Contract Number',
    placeholder: 'Contract reference number',
    required: false,
    group: 'contract',
  },
  {
    id: 'authorizedWork',
    type: 'textarea',
    label: 'Authorized Work',
    placeholder: 'Description of work authorized to proceed',
    required: true,
    group: 'authorization',
  },
  {
    id: 'workScope',
    type: 'textarea',
    label: 'Work Scope',
    placeholder: 'Detailed scope of work',
    required: false,
    group: 'authorization',
  },
  {
    id: 'commencementDate',
    type: 'date',
    label: 'Work Commencement Date',
    required: true,
    group: 'schedule',
  },
  {
    id: 'completionDate',
    type: 'date',
    label: 'Work Completion Date',
    required: true,
    group: 'schedule',
  },
  {
    id: 'workingDays',
    type: 'text',
    label: 'Working Days',
    placeholder: 'Number of working days',
    required: false,
    group: 'schedule',
  },
  {
    id: 'calendarDays',
    type: 'text',
    label: 'Calendar Days',
    placeholder: 'Number of calendar days',
    required: false,
    group: 'schedule',
  },
  {
    id: 'preConstructionMeeting',
    type: 'checkbox',
    label: 'Pre-construction meeting required',
    required: false,
    group: 'pre-construction',
  },
  {
    id: 'meetingDate',
    type: 'date',
    label: 'Meeting Date',
    required: false,
    group: 'pre-construction',
    dependsOn: 'preConstructionMeeting',
  },
  {
    id: 'meetingLocation',
    type: 'text',
    label: 'Meeting Location',
    placeholder: 'Location of pre-construction meeting',
    required: false,
    group: 'pre-construction',
    dependsOn: 'preConstructionMeeting',
  },
  {
    id: 'permitsObtained',
    type: 'checkbox',
    label: 'All required permits obtained',
    required: false,
    group: 'permits',
  },
  {
    id: 'approvalsObtained',
    type: 'checkbox',
    label: 'All required approvals obtained',
    required: false,
    group: 'permits',
  },
  {
    id: 'insuranceVerified',
    type: 'checkbox',
    label: 'Insurance coverage verified',
    required: false,
    group: 'insurance',
  },
  {
    id: 'bondsProvided',
    type: 'checkbox',
    label: 'Required bonds provided',
    required: false,
    group: 'insurance',
  },
  {
    id: 'performanceBondAmount',
    type: 'text',
    label: 'Performance Bond Amount',
    placeholder: 'Performance bond amount',
    required: false,
    group: 'insurance',
    dependsOn: 'bondsProvided',
  },
  {
    id: 'paymentBondAmount',
    type: 'text',
    label: 'Payment Bond Amount',
    placeholder: 'Payment bond amount',
    required: false,
    group: 'insurance',
    dependsOn: 'bondsProvided',
  },
  {
    id: 'siteAccess',
    type: 'checkbox',
    label: 'Site access granted',
    required: false,
    group: 'site',
  },
  {
    id: 'siteAccessDate',
    type: 'date',
    label: 'Site Access Date',
    required: false,
    group: 'site',
    dependsOn: 'siteAccess',
  },
  {
    id: 'siteConditions',
    type: 'textarea',
    label: 'Site Conditions',
    placeholder: 'Description of current site conditions',
    required: false,
    group: 'site',
  },
  {
    id: 'materialDeliverySchedule',
    type: 'textarea',
    label: 'Material Delivery Schedule',
    placeholder: 'Schedule for material deliveries',
    required: false,
    group: 'materials',
  },
  {
    id: 'equipmentMobilization',
    type: 'textarea',
    label: 'Equipment Mobilization',
    placeholder: 'Equipment mobilization schedule',
    required: false,
    group: 'materials',
  },
  {
    id: 'safetyPlan',
    type: 'checkbox',
    label: 'Safety plan required',
    required: false,
    group: 'safety',
  },
  {
    id: 'safetyOfficer',
    type: 'text',
    label: 'Safety Officer',
    placeholder: 'Designated safety officer name',
    required: false,
    group: 'safety',
  },
  {
    id: 'safetyTraining',
    type: 'checkbox',
    label: 'Safety training required',
    required: false,
    group: 'safety',
  },
  {
    id: 'qualityControlPlan',
    type: 'checkbox',
    label: 'Quality control plan required',
    required: false,
    group: 'quality',
  },
  {
    id: 'inspectionSchedule',
    type: 'textarea',
    label: 'Inspection Schedule',
    placeholder: 'Schedule for inspections',
    required: false,
    group: 'quality',
  },
  {
    id: 'environmentalPermits',
    type: 'checkbox',
    label: 'Environmental permits obtained',
    required: false,
    group: 'environmental',
  },
  {
    id: 'erosionControl',
    type: 'checkbox',
    label: 'Erosion control measures required',
    required: false,
    group: 'environmental',
  },
  {
    id: 'wasteMangement',
    type: 'checkbox',
    label: 'Waste management plan required',
    required: false,
    group: 'environmental',
  },
  {
    id: 'projectManager',
    type: 'text',
    label: 'Project Manager',
    placeholder: 'Assigned project manager name',
    required: false,
    group: 'communication',
  },
  {
    id: 'superintendent',
    type: 'text',
    label: 'Superintendent',
    placeholder: 'On-site superintendent name',
    required: false,
    group: 'communication',
  },
  {
    id: 'communicationMethod',
    type: 'select',
    label: 'Primary Communication Method',
    options: [
      { value: 'email', label: 'Email' },
      { value: 'phone', label: 'Phone' },
      { value: 'meetings', label: 'Meetings' },
      {
        value: 'project-management-software',
        label: 'Project Management Software',
      },
    ],
    required: false,
    group: 'communication',
  },
  {
    id: 'reportingFrequency',
    type: 'select',
    label: 'Reporting Frequency',
    options: [
      { value: 'daily', label: 'Daily' },
      { value: 'weekly', label: 'Weekly' },
      { value: 'bi-weekly', label: 'Bi-weekly' },
      { value: 'monthly', label: 'Monthly' },
    ],
    required: false,
    group: 'communication',
  },
  {
    id: 'progressReports',
    type: 'checkbox',
    label: 'Progress reports required',
    required: false,
    group: 'reporting',
  },
  {
    id: 'reportSchedule',
    type: 'text',
    label: 'Report Schedule',
    placeholder: 'Schedule for progress reports',
    required: false,
    group: 'reporting',
    dependsOn: 'progressReports',
  },
  {
    id: 'paymentSchedule',
    type: 'textarea',
    label: 'Payment Schedule',
    placeholder: 'Schedule for progress payments',
    required: false,
    group: 'payment',
  },
  {
    id: 'firstPaymentDate',
    type: 'date',
    label: 'First Payment Date',
    required: false,
    group: 'payment',
  },
  {
    id: 'workingHours',
    type: 'text',
    label: 'Working Hours',
    placeholder: 'e.g., 7:00 AM to 5:00 PM',
    required: false,
    group: 'conditions',
  },
  {
    id: 'weatherDelays',
    type: 'checkbox',
    label: 'Weather delays considered',
    required: false,
    group: 'conditions',
  },
  {
    id: 'coordinationWithOthers',
    type: 'checkbox',
    label: 'Coordination with other contractors required',
    required: false,
    group: 'coordination',
  },
  {
    id: 'sequencing',
    type: 'textarea',
    label: 'Work Sequencing',
    placeholder: 'Required work sequencing',
    required: false,
    group: 'coordination',
  },
  {
    id: 'shopDrawings',
    type: 'checkbox',
    label: 'Shop drawings required',
    required: false,
    group: 'documentation',
  },
  {
    id: 'materialSamples',
    type: 'checkbox',
    label: 'Material samples required',
    required: false,
    group: 'documentation',
  },
  {
    id: 'specialRequirements',
    type: 'textarea',
    label: 'Special Requirements',
    placeholder: 'Any special requirements or conditions',
    required: false,
    group: 'special',
  },
  {
    id: 'forceMajeureProvisions',
    type: 'checkbox',
    label: 'Force majeure provisions apply',
    required: false,
    group: 'legal',
  },
  {
    id: 'modificationRights',
    type: 'checkbox',
    label: 'Owner reserves modification rights',
    required: false,
    group: 'legal',
  },
  {
    id: 'terminationRights',
    type: 'checkbox',
    label: 'Owner reserves termination rights',
    required: false,
    group: 'legal',
  },
  {
    id: 'contractorAcknowledgment',
    type: 'checkbox',
    label: 'Contractor acknowledgment required',
    required: false,
    group: 'acknowledgment',
  },
  {
    id: 'acknowledgmentDeadline',
    type: 'date',
    label: 'Acknowledgment Deadline',
    required: false,
    group: 'acknowledgment',
    dependsOn: 'contractorAcknowledgment',
  },
  {
    id: 'qualityStandards',
    type: 'textarea',
    label: 'Quality Standards',
    placeholder: 'Required quality standards',
    required: false,
    group: 'standards',
  },
  {
    id: 'ownerSignature',
    type: 'checkbox',
    label: 'Require owner signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'projectManagerSignature',
    type: 'checkbox',
    label: 'Require project manager signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'architectSignature',
    type: 'checkbox',
    label: 'Require architect signature',
    required: false,
    group: 'signatures',
  },
  {
    id: 'deliveryMethod',
    type: 'select',
    label: 'Delivery Method',
    options: [
      { value: 'email', label: 'Email' },
      { value: 'certified-mail', label: 'Certified Mail' },
      { value: 'hand-delivery', label: 'Hand Delivery' },
      { value: 'fax', label: 'Fax' },
    ],
    required: false,
    group: 'delivery',
  },
  {
    id: 'deliveryConfirmation',
    type: 'checkbox',
    label: 'Delivery confirmation required',
    required: false,
    group: 'delivery',
  },
  {
    id: 'receiptRequired',
    type: 'checkbox',
    label: 'Receipt acknowledgment required',
    required: false,
    group: 'delivery',
  },
];
